### ISSUE TITLE
FileExistsError : [WinError 183] Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by AbhimanyuHK** [pre-commit/pre-commit#1010]
version : 1.15.2
OS : Windows 10

```console
$ pre-commit install

An unexpected error has occurred: FileExistsError: [WinError 183] Cannot create a file when that file already exists: '.git\\hooks\\pre-commit' -> '.git\\hooks\\pre-commit.legacy'
```

when i tried second times this was the error.

**Comment by asottile** [comment]
Interesting, can you produce a full trace? (should be in the pre-commit log mentioned in the error output)

**Comment by asottile** [comment]
nevermind! I was able to reproduce this by doing the following:

```bash
echo -e '#!/usr/bin/env bash\necho hi' > .git/hook/pre-commit
pre-commit install
echo -e '#!/usr/bin/env bash\necho hi' > .git/hook/pre-commit
pre-commit install
```

When I ran the last `pre-commit install` I ended up with this output:

```console
$ pre-commit install
An unexpected error has occurred: FileExistsError: [WinError 183] Canno
t create a file when that file already exists: '.git\\hooks\\pre-commit
' -> '.git\\hooks\\pre-commit.legacy'
Check the log at C:\Users\Anthony/.cache\pre-commit\pre-commit.log
```

And here's the contents of the stacktrace in the log


```python
An unexpected error has occurred: FileExistsError: [WinError 183] Cannot create a file when that file already exists: '.git\\hooks\\pre-commit' -> '.git\\hooks\\pre-commit.legacy'
Traceback (most recent call last):
  File "c:\users\anthony\appdata\local\temp\t\pyupgrade\venv\lib\site-packages\pre_commit\error_handler.py", line 46, in error_handler
    yield
  File "c:\users\anthony\appdata\local\temp\t\pyupgrade\venv\lib\site-packages\pre_commit\main.py", line 271, in main
    skip_on_missing_conf=args.allow_missing_config,
  File "c:\users\anthony\appdata\local\temp\t\pyupgrade\venv\lib\site-packages\pre_commit\commands\install_uninstall.py", line 87, in install
    os.rename(hook_path, legacy_path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '.git\\hooks\\pre-commit' -> '.git\\hooks\\pre-commit.legacy'
```
