### ISSUE TITLE
ansible-lint failure only when run via pre-commit

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1019]
I am not yet sure if the bug is caused by pre-commit but I am raising it here first because I was not able to reproduce it without pre-commit, every time I called ansible-lint directly/manually it did pass. 

I should also mention that this issue does not always happen, on some system it seems to be working fine but I am sure that on those that where I seen it failing it was always a python2.7 environment.

```
root@smini:~/.rtox/ansible-role-tripleo-ci-reproducer# pre-commit run -a --verbose
[ansible-lint] Ansible-lint..............................................Failed
hookid: ansible-lint

Examining playbooks/tripleo-ci-reproducer/ci_jobs_config.yaml of type playbook
Examining tasks/main.yaml of type playbook
Examining /root/.rtox/ansible-role-tripleo-ci-reproducer/tasks/build-pbrx-container.yaml of type playbook
Examining /root/.rtox/ansible-role-tripleo-ci-reproducer/tasks/install.yaml of type playbook
Examining /root/.rtox/ansible-role-tripleo-ci-reproducer/tasks/start.yaml of type block
Examining /root/.rtox/ansible-role-tripleo-ci-reproducer/tasks/encrypt-gerrit-key.yaml of type block
Examining /root/.rtox/ansible-role-tripleo-ci-reproducer/tasks/launch-job.yaml of type playbook
Examining /root/.rtox/ansible-role-tripleo-ci-reproducer/tasks/stop.yaml of type block
Examining files/playbooks/add_rdo_config.yml of type playbook
Examining files/playbooks/wait-gerrit.yaml of type playbook
Examining tasks/encrypt-gerrit-key.yaml of type playbook
Examining tasks/install.yaml of type playbook
Examining files/projects/zuul-config/zuul.d/jobs.yaml of type playbook
Examining zuul.yaml of type playbook
Examining files/projects/zuul-config/playbooks/base/post-failure.yaml of type playbook
Examining tasks/stop.yaml of type playbook
Examining files/playbooks/roles/create_project/defaults/main.yaml of type playbook
Examining files/playbooks/setup-gerrit.yaml of type playbook
Examining /root/.rtox/ansible-role-tripleo-ci-reproducer/files/playbooks/roles/create_project/tasks/main.yaml of type tasks
Examining /root/.rtox/ansible-role-tripleo-ci-reproducer/files/playbooks/add_rdo_config.yml of type tasks
Examining tasks/start.yaml of type playbook
Examining files/playbooks/add-gerrit-host-keys.yaml of type playbook
Examining playbooks/tripleo-ci-reproducer/pre.yaml of type playbook
Examining defaults/main.yaml of type playbook
Examining .pre-commit-config.yaml of type playbook
Examining tasks/launch-job.yaml of type playbook
Examining playbooks/tripleo-ci-reproducer/post.yaml of type playbook
Examining files/projects/test1/playbooks/run.yaml of type playbook
Examining tasks/libvirt/main.yaml of type playbook
Examining files/projects/zuul-config/playbooks/base/pre.yaml of type playbook
Examining files/playbooks/roles/create_project/tasks/main.yaml of type playbook
Examining files/projects/zuul-config/zuul.d/pipelines.yaml of type playbook
Examining tasks/libvirt/vars/settings.yaml of type playbook
Examining tasks/libvirt/prepare.yaml of type playbook
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/bin/ansible-lint", line 10, in <module>
    sys.exit(main())
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 264, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 171, in find_children
    for child in play_children(basedir, item, playbook[1], playbook_dir):
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 222, in play_children
    fail_on_undefined=False)
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 190, in template
    **dict(kwargs, fail_on_undefined=fail_on_undefined))
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 78, in ansible_template
    return templar.template(varname, **kwargs)
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 528, in template
    ) for v in variable]
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 540, in template
    disable_lookups=disable_lookups,
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 540, in template
    disable_lookups=disable_lookups,
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 495, in template
    disable_lookups=disable_lookups,
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansible/template/__init__.py", line 746, in do_template
    res = j2_concat(rf)
  File "<template>", line 12, in root
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/ansible/plugins/filter/core.py", line 74, in to_nice_yaml
    transformed = yaml.dump(a, Dumper=AnsibleDumper, indent=indent, allow_unicode=True, default_flow_style=False, **kw)
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/yaml/__init__.py", line 293, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/yaml/__init__.py", line 281, in dump_all
    dumper.represent(data)
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/yaml/representer.py", line 29, in represent
    node = self.represent_data(data)
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/yaml/representer.py", line 68, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/yaml/representer.py", line 251, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', Undefined)
 [WARNING]: Unable to find '/var/ssh/id_rsa.pub' in expected paths (use -vvvvv
to see paths)
```

I tried to make pre-commit more verbose but apparently I was not able to get more out of it than this, even adding `verbose: true` to the hook config did not added more.

**Comment by ssbarnea** [comment]
This is not really pre-commit but as I was able to narrow it down to https://github.com/yaml/pyyaml/issues/297 -- shortly, if you encounter it, add a temporary ceiling on pyyaml to avoid 5.x versions.
