### ISSUE TITLE
pre-commit install --install-hooks fails with an error from git about empty strings

### ISSUE THREAD

**Issue by TauPan** [pre-commit/pre-commit#1036]
The following .pre-commit-config.yaml:
```yaml
-   repo: https://gitlab.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    -   id: flake8

```

And the command `pre-commit install --install-hooks` (or any other
pre-commit command) leads to the following error:

```python
An unexpected error has occurred: CalledProcessError: Command: ('/usr/bin/git', 'checkout', '')
Return code: 1
Expected return code: 0
Output: (none)
Errors:
    warning: empty strings as pathspecs will be made invalid in upcoming releases. please use . instead if you meant to match all paths
    error: pathspec '' did not match any file(s) known to git.


Traceback (most recent call last):
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/store.py", line 172, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/store.py", line 150, in _shallow_clone
    git_cmd('checkout', ref)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/store.py", line 166, in _git_cmd
    cmd_output('git', *args, cwd=directory, env=env)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/util.py", line 153, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/usr/bin/git', 'checkout', '')
Return code: 1
Expected return code: 0
Output: (none)
Errors:
    warning: empty strings as pathspecs will be made invalid in upcoming releases. please use . instead if you meant to match all paths
    error: pathspec '' did not match any file(s) known to git.



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/main.py", line 273, in main
    skip_on_missing_conf=args.allow_missing_config,
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/commands/install_uninstall.py", line 124, in install
    install_hooks(config_file, store)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/commands/install_uninstall.py", line 130, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/repository.py", line 221, in all_hooks
    for repo in root_config['repos']
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/repository.py", line 222, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/repository.py", line 197, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/repository.py", line 166, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/store.py", line 176, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/store.py", line 128, in _new_repo
    make_strategy(directory)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/store.py", line 174, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/store.py", line 142, in _complete_clone
    git_cmd('checkout', ref)
  File "/home/taupan/nobackup/virtualenvs/project/lib/python3.4/site-packages/pre_commit/store.py", line 166, in _git_cmd
    cmd_output('git', *args, cwd=directory, env=env)
  File "/home/taupan/nobackup/virtualenvs/project  /lib/python3.4/site-packages/pre_commit/util.py", line 153, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/usr/bin/git', 'checkout', '')
Return code: 1
Expected return code: 0
Output: (none)
Errors:
    warning: empty strings as pathspecs will be made invalid in upcoming releases. please use . instead if you meant to match all paths
    error: pathspec '' did not match any file(s) known to git.

```

Here are (hopefully all) relevant versions:
```
flake8==3.7.7
git version 2.13.7
pre-commit==1.16.1
Python 3.4.8
```

**Comment by TauPan** [comment]
Sorry, I just noticed the empty string came from the example config in the flake8 documentation. (Doh!)

**Comment by TauPan** [comment]
For posterity: rev: '3.7.7' works... I assumed the example given in the flake8 config snippet was a *valid* example. https://flake8.pycqa.org/en/latest/user/using-hooks.html#using-version-control-hooks

**Comment by asottile** [comment]
see also #1023
