### ISSUE TITLE
What if there is no branch named 'master' ?

### ISSUE THREAD

**Issue by pillarsdotnet** [pre-commit/pre-commit#1041]
Trying to use `pre-commit` with a Puppet control repo which only has a `dev` branch at the moment.

```
]$ pre-commit run -a
[INFO] Initializing environment for https://github.com/pillarsdotnet/puppet-pre-commit-hooks.git.
An unexpected error has occurred: CalledProcessError: Command: ('/usr/bin/git', 'checkout', 'master')
Return code: 1
Expected return code: 0
Output: (none)
Errors:
    error: pathspec 'master' did not match any file(s) known to git.


Check the log at /home/robvin/.cache/pre-commit/pre-commit.log
$ cat /home/robvin/.cache/pre-commit/pre-commit.log
An unexpected error has occurred: CalledProcessError: Command: ('/usr/bin/git', 'checkout', 'master')
Return code: 1
Expected return code: 0
Output: (none)
Errors:
    error: pathspec 'master' did not match any file(s) known to git.


Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/usr/lib/python2.7/site-packages/pre_commit/main.py", line 294, in main
    return run(args.config, store, args)
  File "/usr/lib/python2.7/site-packages/pre_commit/commands/run.py", line 276, in run
    for hook in all_hooks(config, store)
  File "/usr/lib/python2.7/site-packages/pre_commit/repository.py", line 221, in all_hooks
    for repo in root_config['repos']
  File "/usr/lib/python2.7/site-packages/pre_commit/repository.py", line 222, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/usr/lib/python2.7/site-packages/pre_commit/repository.py", line 197, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/usr/lib/python2.7/site-packages/pre_commit/repository.py", line 166, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/usr/lib/python2.7/site-packages/pre_commit/store.py", line 176, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/usr/lib/python2.7/site-packages/pre_commit/store.py", line 128, in _new_repo
    make_strategy(directory)
  File "/usr/lib/python2.7/site-packages/pre_commit/store.py", line 174, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/usr/lib/python2.7/site-packages/pre_commit/store.py", line 142, in _complete_clone
    git_cmd('checkout', ref)
  File "/usr/lib/python2.7/site-packages/pre_commit/store.py", line 166, in _git_cmd
    cmd_output('git', *args, cwd=directory, env=env)
  File "/usr/lib/python2.7/site-packages/pre_commit/util.py", line 153, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
CalledProcessError: Command: ('/usr/bin/git', 'checkout', 'master')
Return code: 1
Expected return code: 0
Output: (none)
Errors:
    error: pathspec 'master' did not match any file(s) known to git.

```

**Comment by asottile** [comment]
what does your `.pre-commit-oconfig.yaml` look like?

The only mention of `master` in the pre-commit codebase is in `pre_commit.commands.autoupdate` (which isn't involved at all here)

**Comment by pillarsdotnet** [comment]
Gotcha.  I had:

```
- repo: 'https://github.com/pillarsdotnet/puppet-pre-commit-hooks.git'
  sha: 'master'
  hooks:
    - id: 'puppet-validate'
    - id: 'erb-validate'
    - id: 'epp-validate'
    - id: 'puppet-lint'
      args:
        - '--fail-on-warnings'
```
... and the `puppet-pre-commit-hooks` repo *does* have a `master` branch, but I guess it's an error to reference it.

So I cloned the repo, looked up the current hash of the `master` branch, and put the number in.  Now it works.  But do I have to manually update that hash every time?

Anyhow; thanks for the help.  Closing...

**Comment by asottile** [comment]
You should be able to use `pre-commit autoupdate` to bump the revision -- if it doesn't work for non-master default branch then that's a bug that we need to fix 👍
