### ISSUE TITLE
Permission denied when installed this environment

### ISSUE THREAD

**Issue by detailyang** [pre-commit/pre-commit#1042]
Hello.

I'm not sure the permission is about the pre-commit but it looks likes so.

Here is my config

````yaml
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt

- repo: git://github.com/golangci/golangci-lint
  rev: master
  hooks:
    - id: golangci-lint
      args:
      - --config .golangci.yml

- repo: git://github.com/detailyang/pre-commit-shell
  rev: v1.0.6
  hooks:
  - id: shell-lint
    args: [--color=always, "--exclude=SC1090,SC1091,SC2206"]
````

it looks like python3.7 shutil.rmtree raise the erorr as the following:
````python
An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '/Users/detailyang/.cache/pre-commit/repo2ba1f3b5/golangenv-default/pkg/mod/github.com/!burnt!sushi/toml@v0.3.1/.gitignore'
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 447, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '.gitignore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/usr/local/lib/python3.7/site-packages/pre_commit/main.py", line 294, in main
    return run(args.config, store, args)
  File "/usr/local/lib/python3.7/site-packages/pre_commit/commands/run.py", line 285, in run
    install_hook_envs(hooks, store)
  File "/usr/local/lib/python3.7/site-packages/pre_commit/repository.py", line 215, in install_hook_envs
    hook.install()
  File "/usr/local/lib/python3.7/site-packages/pre_commit/repository.py", line 90, in install
    rmtree(self.prefix.path(venv))
  File "/usr/local/lib/python3.7/site-packages/pre_commit/util.py", line 171, in rmtree
    shutil.rmtree(path, ignore_errors=False, onerror=handle_remove_readonly)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 429, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 429, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 429, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 2 more times]
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 449, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/pre_commit/util.py", line 168, in handle_remove_readonly
    func(path)
PermissionError: [Errno 13] Permission denied: '/Users/detailyang/.cache/pre-commit/repo2ba1f3b5/golangenv-default/pkg/mod/github.com/!burnt!sushi/toml@v0.3.1/.gitignore'
````

**Comment by detailyang** [comment]
It looks like the directory permission is not right (no w and x mode), See the below:

````bash
╰─λ ls -lah /Users/detailyang/.cache/pre-commit/repo2ba1f3b5/golangenv-default/pkg/mod/github.com/!burnt!sushi/                                                    0 < 19:58:09
dr-x------  detailyang  staff   -  Wed May 22 19:43:34 2019    toml@v0.3.1
````

**Comment by detailyang** [comment]
The question is who is the bad bod create the `golangenv-default` ?

**Comment by detailyang** [comment]
It's the go mod builtin feature (bug?), see https://github.com/golang/go/issues/27161 @absassi try `go clean -modcache`?

**Comment by asottile** [comment]
bummer, I'm not able to reproduce:

```console
(venv) asottile-mac:t asottile$ pre-commit install-hooks
[INFO] Initializing environment for git://github.com/golangci/golangci-lint.
[INFO] Installing environment for git://github.com/golangci/golangci-lint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
(venv) asottile-mac:t asottile$ 
```

**Comment by asottile** [comment]
ahah! but I am able to reproduce by forcing go modules:

```console
(venv) asottile-mac:t asottile$ GO111MODULE=on pre-commit install-hooks
[INFO] Initializing environment for git://github.com/golangci/golangci-lint.
[INFO] Installing environment for git://github.com/golangci/golangci-lint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '/Users/asottile/.cache/pre-commit/repofxcjmytd/golangenv-default/pkg/mod/gopkg.in/yaml.v2@v2.2.1/decode_test.go'
Check the log at /Users/asottile/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
Thanks for the report!  This'll make it into the next release :tada:

**Comment by detailyang** [comment]
@asottile many thanks:) Now I know the trick way:)

**Comment by asottile** [comment]
this has been released as part of [v1.17.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.17.0) -- thanks again for the issue!

**Comment by jlucktay** [comment]
I think I've hit a regression on this.

Here is the relevant bit from my hook config:
``` yaml
fail_fast: true

repos:
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.18.0
    hooks:
      - id: golangci-lint
        args: ["--enable-all"]
```

And here is my `~/.cache/pre-commit/pre-commit.log`:
``` text
An unexpected error has occurred: OSError: [Errno 13] Permission denied: '/Users/jameslucktaylor/.cache/pre-commit/repoCX3AKK/golangenv-default/pkg/mod/gopkg.in/yaml.v2@v2.2.2/decode_test.go'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/usr/local/lib/python2.7/site-packages/pre_commit/main.py", line 291, in main
    return run(args.config, store, args)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/commands/run.py", line 271, in run
    install_hook_envs(hooks, store)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/repository.py", line 215, in install_hook_envs
    hook.install()
  File "/usr/local/lib/python2.7/site-packages/pre_commit/repository.py", line 93, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "/usr/local/lib/python2.7/site-packages/pre_commit/languages/golang.py", line 80, in install_environment
    rmtree(pkgdir)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/util.py", line 40, in clean_path_on_failure
    rmtree(path)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/util.py", line 171, in rmtree
    shutil.rmtree(path, ignore_errors=False, onerror=handle_remove_readonly)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 270, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 270, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 270, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 270, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 275, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/pre_commit/util.py", line 168, in handle_remove_readonly
    func(path)
OSError: [Errno 13] Permission denied: '/Users/jameslucktaylor/.cache/pre-commit/repoCX3AKK/golangenv-default/pkg/mod/gopkg.in/yaml.v2@v2.2.2/decode_test.go'
```

@asottile thoughts?

**Comment by asottile** [comment]
what version of pre-commit are you using? (probably `python2.7 -m pre_commit --version`)

**Comment by jlucktay** [comment]
I thought it was current; am using Homebrew to install.
```
$ pre-commit --version
pre-commit 1.18.3

$ python2.7 -m pre_commit --version
__main__.py 1.14.4
```
That doesn't look good though. Looks like I need to figure out how to kick Python's tires and then do so.

**Comment by asottile** [comment]
probably `python2.7 -m pip uninstall pre-commit` and `brew reinstall pre-commit`

**Comment by jlucktay** [comment]
> `python2.7 -m pip uninstall pre-commit` and `brew reinstall pre-commit`

That straightened it out, thank you very much for the quick response! 😃

**Comment by asottile** [comment]
no problem!
