### ISSUE TITLE
Node environment fails to initialize on alpine based images

### ISSUE THREAD

**Issue by eyalzek** [pre-commit/pre-commit#1064]
We use `alpine` based images on our CI and we encountered the following issue when a developer tried to integrate the `prettier` [pre-commit hooks](https://prettier.io/docs/en/precommit.html). The error is encountered while initializing the environment (`pre-commit install-hooks`):
```
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmph8j6p9ne/repodk2x4bmu/node_env-default/bin/node': '/tmp/tmph8j6p9ne/repodk2x4bmu/node_env-default/bin/node'
Check the log at /root/.cache/pre-commit/pre-commit.log
The command '/bin/sh -c pre-commit try-repo . prettier --verbose --all-files' returned a non-zero code: 1
```

the contents of `/root/.cache/pre-commit/pre-commit.log`:
```
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmph8j6p9ne/repodk2x4bmu/node_env-default/bin/node': '/tmp/tmph8j6p9ne/repodk2x4bmu/node_env-default/bin/node'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/usr/lib/python3.6/site-packages/pre_commit/main.py", line 298, in main
    return try_repo(args)
  File "/usr/lib/python3.6/site-packages/pre_commit/commands/try_repo.py", line 80, in try_repo
    return run(config_filename, store, args)
  File "/usr/lib/python3.6/site-packages/pre_commit/commands/run.py", line 285, in run
    install_hook_envs(hooks, store)
  File "/usr/lib/python3.6/site-packages/pre_commit/repository.py", line 215, in install_hook_envs
    hook.install()
  File "/usr/lib/python3.6/site-packages/pre_commit/repository.py", line 93, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "/usr/lib/python3.6/site-packages/pre_commit/languages/node.py", line 70, in install_environment
    helpers.run_setup_cmd(prefix, ('npm', 'install'))
  File "/usr/lib/python3.6/site-packages/pre_commit/languages/helpers.py", line 18, in run_setup_cmd
    cmd_output(*cmd, cwd=prefix.prefix_dir, encoding=None)
  File "/usr/lib/python3.6/site-packages/pre_commit/util.py", line 143, in cmd_output
    proc = subprocess.Popen(cmd, **popen_kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmph8j6p9ne/repodk2x4bmu/node_env-default/bin/node': '/tmp/tmph8j6p9ne/repodk2x4bmu/node_env-default/bin/node'
```

I've tested this on debian based images and it ran as expected with no errors. The issue can be reproduced with the following `Dockerfile`:
```
FROM alpine:latest

RUN apk --no-cache add py3-pip openssh-client git && \
    pip3 install pre-commit

WORKDIR /tmp/test

RUN git clone https://github.com/prettier/prettier.git .

RUN pre-commit try-repo . prettier --verbose --all-files
```

**Comment by asottile** [comment]
this is due to an upstream issue, I've tried to get the node folks to produce alpine binaries but haven't had much success

Here's the issues from last time:

- https://github.com/pre-commit/mirrors-jshint/issues/4
- https://github.com/ekalinin/nodeenv/issues/204
- https://github.com/nodejs/nodejs.org/issues/1569
- https://github.com/nodejs/build/issues/1140

I'd suggest pinging the latter two for forward movement

thanks for the issue!  :tada:

**Comment by eyalzek** [comment]
Interesting. @asottile so the problem is specifically with `node` on alpine due to differences of `libc` ?

**Comment by asottile** [comment]
the current `node`'s prebuilt binaries target `glibc`, whereas `alpine` is built upon `musl`

the first link above includes a workaround using `language_version: system` which may be useful

**Comment by dannyadair** [comment]
I'm sorry but I'm still getting this:

```
...
...
$ pip3 install pre-commit
Collecting pre-commit
  Downloading pre_commit-3.1.1-py2.py3-none-any.whl (202 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.3/202.3 kB 4.6 MB/s eta 0:00:00
...
...
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.7.0-py2.py3-none-any.whl (21 kB)
...
...
Successfully installed cfgv-3.3.1 distlib-0.3.6 filelock-3.9.0 identify-2.5.20 nodeenv-1.7.0 platformdirs-3.1.1 pre-commit-3.1.1 pyyaml-6.0 virtualenv-20.21.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
$ pre-commit run --all-files
...
...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/builds/mygroup/shared/myrepo/.cache/pre-commit/repoo2gui_f2/node_env-16.17.0/bin/node', '/builds/mygroup/shared/myrepo/.cache/pre-commit/repoo2gui_f2/node_env-16.17.0/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
stdout:
    [Errno 2] No such file or directory: '/builds/mygroup/shared/myrepo/.cache/pre-commit/repoo2gui_f2/node_env-16.17.0/bin/node'
stderr: (none)
```

when using the following for gitlab-ci on gitlab.com:

```
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    # https://pre-commit.com/#gitlab-ci-example
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
    - apk add --update --no-cache git
    - apk add --update --no-cache libstdc++
    - python3 -m ensurepip
    - pip3 install --no-cache --upgrade pip setuptools
    - pip3 install pre-commit
    - pre-commit run --all-files
```

I thought nodeenv now grabs unoffical builds?
https://github.com/ekalinin/nodeenv/pull/247/files#diff-b1a3d588879f5a952b82404133da86b955aca26ab38936bf8d3135c05bd7c4feR1033

With .pre-commit-config.yaml being shared with developers, I don't really want to necessitate having npm installed on every laptop (language=system).

**Comment by asottile** [comment]
if you add `nodejs` to your image pre-commit will automatically use `language_version: system` for node hooks -- you shouldn't need to change your config for this and this is separate from `language: system`

I suspect the error message you're seeing is some _other_ shared library that's missing -- since nodeenv has support for alpine builds for quite some time

**Comment by dannyadair** [comment]
Thank you @asottile,
sorry that this won't help future readers with the same issue, but I've opted to just run all the static tests in an Ubuntu container instead.
