### ISSUE TITLE
Error installing hooks: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

### ISSUE THREAD

**Issue by Fogapod** [pre-commit/pre-commit#1151]
### Issue
Installing any pre-commit hook results in error.

### environment
```
$ pip show pre-commit
Name: pre-commit
Version: 1.18.3
Summary: A framework for managing and maintaining multi-language pre-commit hooks.
Home-page: https://github.com/pre-commit/pre-commit
Author: Anthony Sottile
Author-email: asottile@umich.edu
License: MIT
Location: /home/eugene/.local/lib/python3.7/site-packages
Requires: identify, six, importlib-metadata, cfgv, nodeenv, toml, aspy.yaml, virtualenv, pyyaml
Required-by:

$ uname -a
Linux laptop 5.2.11-1-MANJARO #1 SMP PREEMPT Thu Aug 29 07:41:24 UTC 2019 x86_64 GNU/Linux
```

### .pre-commit-config.yaml
```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
```

### Steps to reproduce:
```
rm -rf ~/.cache/pre-commit
pre-commit install-hooks
```

### result
```
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/home/eugene/.cache/pre-commit/repokj2t2rtt/py_env-python3.7/bin/python', '/home/eugene/.cache/pre-commit/repokj2t2rtt/py_env-python3.7/bin/pip', 'install', '.')
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
    WARNING: You are using pip version 19.2.1, however version 19.2.3 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    

Check the log at /home/eugene/.cache/pre-commit/pre-commit.log
```

### log file
```
An unexpected error has occurred: CalledProcessError: Command: ('/home/eugene/.cache/pre-commit/repokj2t2rtt/py_env-python3.7/bin/python', '/home/eugene/.cache/pre-commit/repokj2t2rtt/py_env-python3.7/bin/pip', 'install', '.')
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
    WARNING: You are using pip version 19.2.1, however version 19.2.3 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    

Traceback (most recent call last):
  File "/home/eugene/.local/lib/python3.7/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/home/eugene/.local/lib/python3.7/site-packages/pre_commit/main.py", line 312, in main
    return install_hooks(args.config, store)
  File "/home/eugene/.local/lib/python3.7/site-packages/pre_commit/commands/install_uninstall.py", line 131, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/home/eugene/.local/lib/python3.7/site-packages/pre_commit/repository.py", line 215, in install_hook_envs
    hook.install()
  File "/home/eugene/.local/lib/python3.7/site-packages/pre_commit/repository.py", line 93, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "/home/eugene/.local/lib/python3.7/site-packages/pre_commit/languages/python.py", line 171, in install_environment
    prefix, ('pip', 'install', '.') + additional_dependencies,
  File "/home/eugene/.local/lib/python3.7/site-packages/pre_commit/languages/helpers.py", line 18, in run_setup_cmd
    cmd_output(*cmd, cwd=prefix.prefix_dir, encoding=None)
  File "/home/eugene/.local/lib/python3.7/site-packages/pre_commit/util.py", line 153, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/home/eugene/.cache/pre-commit/repokj2t2rtt/py_env-python3.7/bin/python', '/home/eugene/.cache/pre-commit/repokj2t2rtt/py_env-python3.7/bin/pip', 'install', '.')
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
    WARNING: You are using pip version 19.2.1, however version 19.2.3 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    


```

**Comment by asottile** [comment]
can you show the contents of `env`? I suspect you have an environment variable which is interfering

**Comment by Fogapod** [comment]
This is full list, I did not remove anything
```
$ env
COLORFGBG=15;0
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=/usr/share/xsessions/plasma
DISPLAY=:0
GS_LIB=/home/eugene/.fonts
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/eugene/.gtkrc-2.0:/home/eugene/.config/gtkrc-2.0
GTK_MODULES=canberra-gtk-module
GTK_RC_FILES=/etc/gtk/gtkrc:/home/eugene/.gtkrc:/home/eugene/.config/gtkrc
HOME=/home/eugene
KDE_FULL_SESSION=true
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=5
KONSOLE_DBUS_SERVICE=:1.32
KONSOLE_DBUS_SESSION=/Sessions/2
KONSOLE_PROFILE_NAME=Profile 3
KONSOLE_VERSION=190800
LANG=en_US.UTF-8
LANGUAGE=
LC_MEASUREMENT=ru_RU.UTF-8
LC_MONETARY=ru_RU.UTF-8
LOGNAME=eugene
MAIL=/var/spool/mail/eugene
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
OLDPWD=/home/eugene
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
PATH=/home/eugene/.gem/ruby/2.6.0/bin:/home/eugene/go/bin:/home/eugene/.local/bin:/home/eugene/go/bin:/home/eugene/.local/bin:/home/eugene/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
PROFILEHOME=
PT7HOME=/opt/pt
PWD=/home/eugene/projects/iomirea/run-api
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_DEVICE_PIXEL_RATIO=auto
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
SESSION_MANAGER=local/laptop:@/tmp/.ICE-unix/936,unix/laptop:/tmp/.ICE-unix/936
SHELL=/usr/bin/zsh
SHELL_SESSION_ID=baf6ab2b85a74440b0eba3a14d7c0a72
SHLVL=2
SSH_AGENT_PID=865
SSH_AUTH_SOCK=/tmp/ssh-eOBjMfoQSbEc/agent.864
TERM=xterm-256color
USER=eugene
WINDOWID=48234503
XAUTHORITY=/tmp/xauth-1000-_0
XCURSOR_THEME=breeze_cursors
XDG_CURRENT_DESKTOP=KDE
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=KDE
XDG_SESSION_ID=2
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_SESSION_TYPE=x11
XDG_VTNR=1
_=/usr/bin/env
PAGER=less
LESS=-R
LC_CTYPE=en_US.UTF-8
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
```

**Comment by asottile** [comment]
Do you have a `~/.config/pip/pip.conf` or `~/.pip/pip.conf` file?

**Comment by Fogapod** [comment]
No, neither of 2

**Comment by asottile** [comment]
Can you try this for me? I suspect it will fail in the same way:

```bash
virtualenv tmpvenv
tmpvenv/bin/pip install astpretty
```

I'd be interested in finding out how you've configured pip globally so it always performs user installs, that's a little bit weird to me 🤔  -- can you look into the possible configuration files and see if there's something in one of those? https://pip.pypa.io/en/stable/user_guide/#config-file

**Comment by Fogapod** [comment]
Yes, running this causes same error.
I never configured pip to always use `--user` flag, at least not intentionally.
I found `/etc/pip.conf` file with the following contents:
```
[global]
user = true
```

deleting `user` setting fixed my problem

**Comment by asottile** [comment]
interesting!  doesn't seem like there's an option in pip to disable the `--user` setting so I don't think there's anything we can do to protect against this 🤷‍♂

**Comment by partham16** [comment]
> interesting! doesn't seem like there's an option in pip to disable the `--user` setting so I don't think there's anything we can do to protect against this 🤷‍♂

As per [pip config-file](https://pip.pypa.io/en/stable/user_guide/#environment-variables), `export PIP_USER=false`  works!

Just faced this issue while setting up 'gitpod' and the `export` worked for me - which I guess is the same as @Fogapod 


> Yes, running this causes same error.
> I never configured pip to always use `--user` flag, at least not intentionally.
> I found `/etc/pip.conf` file with the following contents:
> 
> ```
> [global]
> user = true
> ```
> 
> deleting `user` setting fixed my problem

**Comment by Lyounessi** [comment]
@asottile it worked for me, but I have to alwasy  use pip by asigning the directory path tmpvenv/bin/pip install <Packages> ?? 


> interesting! doesn't seem like there's an option in pip to disable the `--user` setting so I don't think there's anything we can do to protect against this

**Comment by ToucheSir** [comment]
Ran into this issue the other way. Would it be possible to add a config option that sets `PIP_USER=false` before installing hook venvs? Having to change per-user pip configuration (especially for people who expect `user = true` to always be set) or needing to remember to set an env var before every invocation of `pre-commit` is rather cumbersome.

**Comment by asottile** [comment]
setting user globally is a bad idea already, imo pre-commit shouldn't have to defend against very poor choices

**Comment by danielhollas** [comment]
Apologies for commenting on closed issue, we're running into this as well. (Due to *unfortunate reasons*, we're setting PIP_USER=1 in our container environment and it's not easy to get rid of)

> doesn't seem like there's an option in pip to disable the --user setting so I don't think there's anything we can do to protect against this 🤷‍♂

Actually, pip supports the `--no-user` flag since version [10.0.0b1](https://pip.pypa.io/en/stable/news/#id1041) (released in 2018) so the potential patch  to fix this might be fairly small

```diff
diff --git a/pre_commit/languages/python.py b/pre_commit/languages/python.py
index 0c4bb62..e154620 100644
--- a/pre_commit/languages/python.py
+++ b/pre_commit/languages/python.py
@@ -207,7 +207,7 @@ def install_environment(
     python = norm_version(version)
     if python is not None:
         venv_cmd.extend(('-p', python))
-    install_cmd = ('python', '-mpip', 'install', '.', *additional_dependencies)
+    install_cmd = ('python', '-mpip', 'install', '--no-user', '.', *additional_dependencies)
 
     cmd_output_b(*venv_cmd, cwd='/')
     with in_env(prefix, version):
```

Happy to submit a PR if that is desired.

**Comment by asottile** [comment]
as the comment directly above yours states I'd rather not.  user installs are a bad idea in general (especially in a container and especially forced via the environment)
