### ISSUE TITLE
Getting ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found even if setup.py file available

### ISSUE THREAD

**Issue by virad3** [pre-commit/pre-commit#1163]
I tried to run my unit testcases through pre-commit (pre-push stage). But I'm not able to install local directory in virtualenv. Getting an error like "**Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found**" even if setup.py file available.

#### Here is my .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        stages: [commit]
  - repo: local
    hooks:
      - id: unittests
        name: unittests
        entry: python -m tests.initiate
        language: python
        language_version: python3.6
        additional_dependencies: ['--trusted-host' ,'pypi.org' ,'--trusted-host' ,'files.pythonhosted.org']
        stages: [commit]
```

#### And finally, here's the error I'm getting from pre-commit:

```bash
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks commit -q -F C:\Users\xxxxx\AppData\Local\Temp\1t5bmasv.vpz
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...

An unexpected error has occurred: CalledProcessError: Command: ('C:\\Users\\xxxxx\\.cache\\pre-commit\\reposrc_pe7u\\py_env-python3.6\\Scripts\\pip.exe', 'install', '.', '--trusted-host', 'pypi.org', '--trusted-host', 'files.pythonhosted.org')
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

Check the log at C:\Users\xxxxx/.cache\pre-commit\pre-commit.log
```

I have debugged the pre-commit code and changed [pre_commit/languages/python.py#L171](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/python.py#L171) for verification.

`` prefix, ('pip', 'install', Path.cwd())+ additional_dependencies
``

After this change, again I ran pre-push then the code in local directory installed in **C:\\Users\\xxxxx\\.cache\\pre-commit\\reposrc_pe7u\\py_env-python3.6\\lib\\python3.6\\site-packages**

Can anyone please guide me on this. Please provide a solution

**Comment by asottile** [comment]
what version of pre-commit are you using?

**Comment by virad3** [comment]
pre-commit 1.18.3

**Comment by asottile** [comment]
that output above should only be possible with the latest version, can you show the full output of the log file?

**Comment by asottile** [comment]
this is the output I get when trying out your configuration:

```console
$ pre-commit  run --all-files
[INFO] Initializing environment for local:--trusted-host,--trusted-host,files.pythonhosted.org,pypi.org.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
unittests............................................(no files to check)Skipped
$ touch t.py
$ git add t.py
$ touch t.py
$ pre-commit  run --all-files
unittests................................................................Failed
hookid: unittests

/home/asottile/.cache/pre-commit/repoq014d6ab/py_env-python3.6/bin/python: Error while finding module specification for 'tests.initiate' (ModuleNotFoundError: No module named 'tests')

```

which is what I expect :thinking:

**Comment by virad3** [comment]
Error log file:

```bash
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Users\\xxxxx\\.cache\\pre-commit\\reposrc_pe7u\\py_env-python3.6\\Scripts\\pip.exe', 'install', '.', '--trusted-host', 'pypi.org', '--trusted-host', 'files.pythonhosted.org')
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
    

Traceback (most recent call last):
  File "c:\users\xxxxx\documents\venv\lib\site-packages\pre_commit\error_handler.py", line 46, in error_handler
    yield
  File "c:\users\xxxxx\documents\venv\lib\site-packages\pre_commit\main.py", line 316, in main
    return run(args.config, store, args)
  File "c:\users\xxxxx\documents\venv\lib\site-packages\pre_commit\commands\run.py", line 295, in run
    install_hook_envs(hooks, store)
  File "c:\users\xxxxx\documents\venv\lib\site-packages\pre_commit\repository.py", line 215, in install_hook_envs
    hook.install()
  File "c:\users\xxxxx\documents\venv\lib\site-packages\pre_commit\repository.py", line 93, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "c:\users\xxxxx\documents\venv\lib\site-packages\pre_commit\languages\python.py", line 176, in install_environment
    prefix, ('pip', 'install','.')+ additional_dependencies,
  File "c:\users\xxxxx\documents\venv\lib\site-packages\pre_commit\languages\helpers.py", line 18, in run_setup_cmd
    cmd_output(*cmd, cwd=prefix.prefix_dir, encoding=None)
  File "c:\users\xxxxx\documents\venv\lib\site-packages\pre_commit\util.py", line 155, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('C:\\Users\\xxxxx\\.cache\\pre-commit\\reposrc_pe7u\\py_env-python3.6\\Scripts\\pip.exe', 'install', '.', '--trusted-host', 'pypi.org', '--trusted-host', 'files.pythonhosted.org')
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by asottile** [comment]
ok there's definitely something important you're not telling me

```
  File "c:\users\xxxxx\documents\venv\lib\site-packages\pre_commit\languages\python.py", line 176, in install_environment
    prefix, ('pip', 'install','.')+ additional_dependencies,
```

for one, I don't format my code like that so there's something sketch happening

for two line 176 at that version is here: https://github.com/pre-commit/pre-commit/blob/0245a6783130975c786b9140e2d8695473b2c105/pre_commit/languages/python.py#L176

**Comment by asottile** [comment]
at this point I'd encourage you to uninstall (and reinstall), perhaps even with a `pre-commit clean` because my guess is whatever you've changed has broken the internal structures

**Comment by virad3** [comment]
@asottile Thank you. Now its working fine

**Comment by asottile** [comment]
I'm at a loss for words, glad you figured it out in the end

**Comment by mmphego** [comment]
@virad3 How did you get it to work? I am also experiencing the same problem.

```bash

mmphego@4n0m41y on 10.8.10.199:~/tmp/test-repo  [disk: 89%]  master [Last updated: Fri Nov 8 11:48:21 2019 +0200]
└─ [2019-11-13 15:48:32] $ >>> pre-commit try-repo /home/mmphego/GitHub/Productivity_Projects/pre-commit-hooks/ --files test.py 
[WARNING] Creating temporary repo with uncommitted changes...
[INFO] Initializing environment for /tmp/tmpidh0b8p5/shadow-repo.
===============================================================================
Using config:
===============================================================================
repos:
-   repo: /tmp/tmpidh0b8p5/shadow-repo
    rev: b5eeefd05105d4d0f5e3e74d25012ff403b6d762
    hooks:
    -   id: autopep8
    -   id: black
    -   id: flake8
    -   id: isort
    -   id: prepend-jira-link
    -   id: pytest
    -   id: shellcheck
===============================================================================
[INFO] Initializing environment for /tmp/tmpidh0b8p5/shadow-repo:autopep8.
[INFO] Initializing environment for /tmp/tmpidh0b8p5/shadow-repo:black.
[INFO] Initializing environment for /tmp/tmpidh0b8p5/shadow-repo:dlint,flake8,flake8-2020,flake8-blind-except,flake8-bugbear,flake8-builtins,flake8-comprehensions,flake8-copyright,flake8-deprecated,flake8-docstrings,flake8-license,flake8-pytest,flake8-tabs,flake8-variables-names,pandas-vet,pep8-naming.
[INFO] Initializing environment for /tmp/tmpidh0b8p5/shadow-repo:isort.
[INFO] Initializing environment for /tmp/tmpidh0b8p5/shadow-repo:pytest,pytest-cov,pytest-mock.
[INFO] Initializing environment for /tmp/tmpidh0b8p5/shadow-repo:shellcheck.
[INFO] Installing environment for /tmp/tmpidh0b8p5/shadow-repo.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/tmp/tmpidh0b8p5/repoxxoa4yi5/py_env-python3/bin/python', '/tmp/tmpidh0b8p5/repoxxoa4yi5/py_env-python3/bin/pip', 'install', '.', 'autopep8')
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
    WARNING: You are using pip version 19.2.2, however version 19.3.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    

Check the log at /home/mmphego/.cache/pre-commit/pre-commit.log
mmphego@4n0m41y on 10.8.10.199:~/tmp/test-repo  [disk: 89%]  master [Last updated: Fri Nov 8 11:48:21 2019 +0200]
└─ [2019-11-13 15:53:20] $ >>> pre-commi
pre-commit                    pre-commit-validate-config    pre-commit-validate-manifest  
mmphego@4n0m41y on 10.8.10.199:~/tmp/test-repo  [disk: 89%]  master [Last updated: Fri Nov 8 11:48:21 2019 +0200]
└─ [2019-11-13 15:53:20] $ >>> pre-commit --version
pre-commit 1.18.2
```

**Comment by asottile** [comment]
can you run `git status` in your pre-commit-hooks repo?

**Comment by mmphego** [comment]
It was working just fine about 20min ago.

Then suddenly the dreaded ERROR.

![image](https://user-images.githubusercontent.com/7910856/68771102-062c8800-0630-11ea-9e16-55726dfe41bd.png)

**Comment by mmphego** [comment]
Suddenly fixed itself... :man_shrugging:

**Comment by asottile** [comment]
probably because setup.* was unstaged (and never checked in)

**Comment by ssbarnea** [comment]
I faced this issue today and it happened after I installed and activated poetry. Still doing a `pre-commit clean` fixed the very confusing error.

**Comment by asottile** [comment]
@ssbarnea could you share your configuration?

**Comment by abbasabaei** [comment]
I have same problem and used this
https://stackoverflow.com/a/67883441/13181871

**Comment by asottile** [comment]
@abbasabaei that's unrelated entirely -- this person had modified the pre-commit source and broken it and then reported the issue to github for some reason

I'm locking this because all comments after the original have been off topic -- if you think you ahve the same issue please open a new issue
