### ISSUE TITLE
python: unable to enforce virtualenv requirements

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#1175]
Some recent changes made to [setuptools broke ansible-lint package](https://github.com/ansible/ansible-lint/issues/590) installation and this uncovered the fact that we cannot use `additional_dependencies` feature to enforce a supported verison of setoptools, mainly because these are installed after the hook package.

As this is a breaking change that blocks any CI/CD change and that ansible-lint maintenance
is not really at its best, we tried to workaround by making pre-commit install a supported version. This did not work. For example if we were using tox, this could have being possible to workaround.

Is there a way to implement such workaround with pre-commit?
```
linters installed: aspy.yaml==1.3.0,cfgv==2.0.1,identify==1.4.7,importlib-metadata==0.23,more-itertools==7.2.0,nodeenv==1.3.3,pre-commit==1.18.3,PyYAML==5.1.2,six==1.12.0,toml==0.10.0,virtualenv==16.7.6,zipp==0.6.0
linters run-test-pre: PYTHONHASHSEED='313936725'
linters run-test: commands[0] | python -m pre_commit run -a
[INFO] Initializing environment for https://github.com/ansible/ansible-lint.git:pip==19.2.3,setuptools==41.0.0.
[INFO] Installing environment for https://github.com/ansible/ansible-lint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/Users/ssbarnea/.cache/pre-commit/repocf1o9ab3/py_env-python3/bin/python', '/Users/ssbarnea/.cache/pre-commit/repocf1o9ab3/py_env-python3/bin/pip', 'install', '.', 'pip==19.2.3', 'setuptools==41.0.0')
Return code: 1
Expected return code: 0
Output:
    Processing /Users/ssbarnea/.cache/pre-commit/repocf1o9ab3

Errors:
        ERROR: Command errored out with exit status 1:
         command: /Users/ssbarnea/.cache/pre-commit/repocf1o9ab3/py_env-python3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/pip-req-build-hk1_b2gb/setup.py'"'"'; __file__='"'"'/private/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/pip-req-build-hk1_b2gb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/pip-req-build-hk1_b2gb/pip-egg-info
             cwd: /private/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/pip-req-build-hk1_b2gb/
        Complete output (21 lines):
        /private/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/pip-req-build-hk1_b2gb/.eggs/setuptools_scm-3.3.3-py3.7.egg/setuptools_scm/git.py:68: UserWarning: "/private/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/pip-req-build-hk1_b2gb" is shallow and may cause errors
          warnings.warn('"%s" is shallow and may cause errors' % (wd.path,))
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/pip-req-build-hk1_b2gb/setup.py", line 150, in <module>
            __name__ == '__main__' and setuptools.setup(**setup_params)
          File "/Users/ssbarnea/.cache/pre-commit/repocf1o9ab3/py_env-python3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
            return distutils.core.setup(**attrs)
          File "/Users/ssbarnea/.pyenv/versions/3.7.4/lib/python3.7/distutils/core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "/Users/ssbarnea/.cache/pre-commit/repocf1o9ab3/py_env-python3/lib/python3.7/site-packages/setuptools/dist.py", line 447, in __init__
            k: v for k, v in attrs.items()
          File "/Users/ssbarnea/.pyenv/versions/3.7.4/lib/python3.7/distutils/dist.py", line 292, in __init__
            self.finalize_options()
          File "/Users/ssbarnea/.cache/pre-commit/repocf1o9ab3/py_env-python3/lib/python3.7/site-packages/setuptools/dist.py", line 735, in finalize_options
            ep.load()(self, ep.name, value)
          File "/Users/ssbarnea/.cache/pre-commit/repocf1o9ab3/py_env-python3/lib/python3.7/site-packages/setuptools/dist.py", line 291, in check_specifier
            packaging.specifiers.SpecifierSet(value)
          File "/Users/ssbarnea/.cache/pre-commit/repocf1o9ab3/py_env-python3/lib/python3.7/site-packages/setuptools/_vendor/packaging/specifiers.py", line 594, in __init__
            specifiers = [s.strip() for s in specifiers.split(",") if s.strip()]
        AttributeError: 'SpecifierSet' object has no attribute 'split'
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


Check the log at /Users/ssbarnea/.cache/pre-commit/pre-commit.log
ERROR: InvocationError for command /Users/ssbarnea/rdo/rdo-infra/rdo-jobs/.tox/linters/bin/python -m pre_commit run -a (exited with code 1)
```

**Comment by ssbarnea** [comment]
@asottile Thanks for the hint! I may end-up using it if I fail to patch ansible-lint in time.
