### ISSUE TITLE
-mvirtualenv does not support MSYS2 (no symlinks)

### ISSUE THREAD

**Issue by zhihaoy** [pre-commit/pre-commit#1216]
`pre-commit run -a` on MSYS2:

```
Traceback (most recent call last):
  File "/c/Users/zy/.local/lib/python3.7/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/c/Users/zy/.local/lib/python3.7/site-packages/pre_commit/main.py", line 316, in main
    return run(args.config, store, args)
  File "/c/Users/zy/.local/lib/python3.7/site-packages/pre_commit/commands/run.py", line 295, in run
    install_hook_envs(hooks, store)
  File "/c/Users/zy/.local/lib/python3.7/site-packages/pre_commit/repository.py", line 215, in install_hook_envs
    hook.install()
  File "/c/Users/zy/.local/lib/python3.7/site-packages/pre_commit/repository.py", line 93, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "/c/Users/zy/.local/lib/python3.7/site-packages/pre_commit/languages/python.py", line 168, in install_environment
    _make_venv(env_dir, python)
  File "/c/Users/zy/.local/lib/python3.7/site-packages/pre_commit/languages/python.py", line 180, in make_venv
    cmd_output(*cmd, env=env, cwd='/')
  File "/c/Users/zy/.local/lib/python3.7/site-packages/pre_commit/util.py", line 153, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/usr/bin/python3.exe', '-mvirtualenv', '/c/Users/zy/.cache/pre-commit/repo5lr2wp32/py_env-python3', '-p', '/usr/bin/python3.exe')
Return code: 1
Expected return code: 0
Output:
    Already using interpreter /usr/bin/python3.exe
    Using base prefix '/usr'
    New python executable in /c/Users/zy/.cache/pre-commit/repo5lr2wp32/py_env-python3/bin/python3.exe
    Also creating executable in /c/Users/zy/.cache/pre-commit/repo5lr2wp32/py_env-python3/bin/python.exe

Errors:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/c/Users/zy/.local/lib/python3.7/site-packages/virtualenv.py", line 2628, in <module>
        main()
      File "/c/Users/zy/.local/lib/python3.7/site-packages/virtualenv.py", line 870, in main
        symlink=options.symlink,
      File "/c/Users/zy/.local/lib/python3.7/site-packages/virtualenv.py", line 1156, in create_environment
        install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
      File "/c/Users/zy/.local/lib/python3.7/site-packages/virtualenv.py", line 1666, in install_python
        os.symlink(py_executable_base, full_pth)
    FileNotFoundError: [Errno 2] No such file or directory: 'python3.exe' -> '/c/Users/zy/.cache/pre-commit/repo5lr2wp32/py_env-python3/bin/python3'
```

Changing https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/python.py#L180 to
```python
cmd = (sys.executable, '-mvenv', envdir)
```

Solves the problem.

**Comment by asottile** [comment]
you can override the language to use `venv` by setting `language: python_venv` -- note that the portability is less in that case

the upstream `virtualenv` issue is here: https://github.com/pypa/virtualenv/issues/1378
