### ISSUE TITLE
Unable to create environment

### ISSUE THREAD

**Issue by dycw** [pre-commit/pre-commit#1239]
Hi, thanks for the great tool!

I've suddenly started being unable to create my pre-commit environments. Here are some possibly relevant facts:

- I use `conda` to manage my environments.
- I was in the middle of constantly adding/removing/testing a number of `flake8` extensions and `prospector`.
- We have a company repository, specified in my `pip.conf`, where it says `Looking in indexes: ...` below. Two things have been redacted.

```
[WARNING] Unstaged files detected.                                                                                                                                                           
[INFO] Stashing unstaged files to /home/dwan/.cache/pre-commit/patch1575608473.                                                                                                              
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.                                                                                                            
[INFO] Once installed this environment will be reused.                                                                                                                                       
[INFO] This may take a few minutes...                                                                                                                                                        
[INFO] Restored changes from /home/dwan/.cache/pre-commit/patch1575608473.                                                                                                                   
An unexpected error has occurred: CalledProcessError: Command: ('/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/bin/python', '/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-py
thon3.7/bin/pip', 'install', '.')                                                                                                                                                            
Return code: 2                                                                                                                                                                               
Expected return code: 0                                                                                                                                                                      
Output:                                                                                                                                                                                      
    Looking in indexes: [http://***]
    Processing /home/dwan/.cache/pre-commit/repopw7a59ul
    Collecting flake8 (from pre-commit-hooks==2.4.0)
    User for [***.com]: User for [***.com]:

Errors: 
    ERROR: Exception:
    Traceback (most recent call last):
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
        status = self.run(options, args)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 345, in run
        resolver.resolve(requirement_set)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
        self._resolve_one(requirement_set, req)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
        self.require_hashes
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 134, in prepare_linked_requirement
        req.populate_link(finder, upgrade_allowed, require_hashes)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 211, in populate_link
        self.link = finder.find_requirement(self, upgrade)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index.py", line 1201, in find_requirement
        req.name, specifier=req.specifier, hashes=hashes,
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index.py", line 1183, in find_candidates
        candidates = self.find_all_candidates(project_name)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index.py", line 1128, in find_all_candidates
        for page in self._get_pages(url_locations, project_name):
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index.py", line 1282, in _get_pages
        page = _get_html_page(location, session=self.session)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index.py", line 234, in _get_html_page
        resp = _get_html_response(url, session=session)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index.py", line 182, in _get_html_response
        "Cache-Control": "max-age=0",
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/download.py", line 624, in request
        return super(PipSession, self).request(method, url, *args, **kwargs)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 653, in send
        r = dispatch_hook('response', hooks, r, **kwargs)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/requests/hooks.py", line 31, in dispatch_hook
        _hook_data = hook(hook_data, **kwargs)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/download.py", line 386, in handle_401
        username, password, save = self._prompt_for_password(parsed.netloc)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/download.py", line 358, in _prompt_for_password
        username = ask_input("User for %s: " % netloc)
      File "/home/dwan/.cache/pre-commit/repopw7a59ul/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 281, in ask_input
        return input(message)
    EOFError: EOF when reading a line
```

Anyone able to offer any help please?

**Comment by asottile** [comment]
it's trying to basic auth to whatever the `***.com` is -- probably meaning your `pip.conf` is misconfigured

this has nothing to do with pre-commit I'm afraid, the same would happen if you ran `pip` alone

**Comment by dycw** [comment]
Thanks for your help!

**Comment by migueltorrescosta** [comment]
I observe the same error as above. `pip install` works as expected. In particular I am able to do `pip install black` and run black locally, but it fails when attempted from within `pre-commit`.

**Comment by asottile** [comment]
"works as expected" meaning you typed a password or used a keychain and it worked?

again this isn't a pre-commit problem.  it just calls pip
