### ISSUE TITLE
Fails to install black with setuptools-scm error

### ISSUE THREAD

**Issue by Siecje** [pre-commit/pre-commit#1241]
```shell
foo@foo-VirtualBox:~/root/microservices/billing$ pre-commit install
pre-commit installed at /home/foo/root/.git/modules/microservices/billing/hooks/pre-commit
foo@foo-VirtualBox:~/root/microservices/billing$ git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   a.py

foo@foo-VirtualBox:~/root/microservices/billing$ git commit -m "foo"
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/home/foo/.cache/pre-commit/repox7sb94wd/py_env-python3.7/bin/python3.7', '/home/foo/.cache/pre-commit/repox7sb94wd/py_env-python3.7/bin/pip', 'install', '.')
Return code: 1
Expected return code: 0
Output: 
    Processing /home/foo/.cache/pre-commit/repox7sb94wd
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'error'
    
Errors: 
        ERROR: Command errored out with exit status 1:
         command: /home/foo/.cache/pre-commit/repox7sb94wd/py_env-python3.7/bin/python3.7 /home/foo/.cache/pre-commit/repox7sb94wd/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpq2o70erc
             cwd: /tmp/pip-req-build-sy15f1qc
        Complete output (36 lines):
        Traceback (most recent call last):
          File "/home/foo/.cache/pre-commit/repox7sb94wd/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
            main()
          File "/home/foo/.cache/pre-commit/repox7sb94wd/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/home/foo/.cache/pre-commit/repox7sb94wd/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "/tmp/pip-build-env-ewlgs0nn/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "/tmp/pip-build-env-ewlgs0nn/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 65, in <module>
            "blackd=blackd:patched_main [d]",
          File "/tmp/pip-build-env-ewlgs0nn/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
            return distutils.core.setup(**attrs)
          File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.5/lib/python3.7/distutils/core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "/tmp/pip-build-env-ewlgs0nn/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 448, in __init__
            k: v for k, v in attrs.items()
          File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.5/lib/python3.7/distutils/dist.py", line 292, in __init__
            self.finalize_options()
          File "/tmp/pip-build-env-ewlgs0nn/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 740, in finalize_options
            ep.load()(self)
          File "/tmp/pip-build-env-ewlgs0nn/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
            ep.load()(self, ep.name, value)
          File "/tmp/pip-build-env-ewlgs0nn/overlay/lib/python3.7/site-packages/setuptools_scm/integration.py", line 17, in version_keyword
            dist.metadata.version = get_version(**value)
          File "/tmp/pip-build-env-ewlgs0nn/overlay/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 150, in get_version
            parsed_version = _do_parse(config)
          File "/tmp/pip-build-env-ewlgs0nn/overlay/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 113, in _do_parse
            "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
        LookupError: setuptools-scm was unable to detect version for '/tmp/pip-req-build-sy15f1qc'.
        
        Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
        
        For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
        ----------------------------------------
    ERROR: Command errored out with exit status 1: /home/foo/.cache/pre-commit/repox7sb94wd/py_env-python3.7/bin/python3.7 /home/foo/.cache/pre-commit/repox7sb94wd/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpq2o70erc Check the logs for full command output.
    
Check the log at /home/foo/.cache/pre-commit/pre-commit.log
foo@foo-VirtualBox:~/root/microservices/billing$ cat .pre-commit-config.yaml 
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
foo@foo-VirtualBox:~/root/microservices/billing$ 
```

**Comment by asottile** [comment]
can you provide more information here: https://github.com/psf/black/issues/1180

I haven't been able to reproduce at all, if you could get a reproduction using docker that would be great
