### ISSUE TITLE
pylint cannot find module when run by pre-commit

### ISSUE THREAD

**Issue by aleb** [pre-commit/pre-commit#1244]
I'm trying to use the pylint hook like this:

```
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
    -   id: pylint
        args:
        -   --rcfile=pylint.rc
        -   --limit=10.0
```

But I get an error about a Python module not being available:
```
[ptv] bash-5.0$ pre-commit run --config .pre-commit-config.yaml 
Validate Pre-Commit Manifest.........................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Fix python encoding pragma...............................................Passed
Check docstring is first.................................................Passed
Debug Statements (Python)................................................Passed
Reorder python imports...................................................Passed
pydocstyle...............................................................Passed
pylint...................................................................Failed
hookid: pylint

Traceback (most recent call last):
  File "/home/aleb/.cache/pre-commit/repogxgsxchc/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/aleb/.cache/pre-commit/repogxgsxchc/py_env-python3/lib/python3.7/site-packages/pylint/__init__.py", line 23, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/aleb/.cache/pre-commit/repogxgsxchc/py_env-python3/lib/python3.7/site-packages/pylint/lint.py", line 1681, in __init__
    "init-hook", utils._unquote(config_parser.get("MASTER", "init-hook"))
  File "/home/aleb/.cache/pre-commit/repogxgsxchc/py_env-python3/lib/python3.7/site-packages/pylint/lint.py", line 1813, in cb_init_hook
    exec(value)  # pylint: disable=exec-used
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gi'
```

This happens because of this line in pylint.rc:
```
init-hook='import gi; gi.require_version("Gtk", "3.0"); gi.require_version("Gst", "1.0"); from gi.repository import Gst; Gst.init(None); gi.require_version("GES", "1.0"); from gi.repository import GES; GES.init()'
```

It should not fail because the gi module is available:
```
[ptv] bash-5.0$ python3 -c "import gi; print (gi.__version__)"
3.34.0

[ptv] bash-5.0$ echo $PYTHONPATH

[ptv] bash-5.0$ echo $PYTHONUSERBASE/
/app//

[ptv] bash-5.0$ ls /app/lib/python3.7/site-packages/gi/
overrides

[ptv] bash-5.0$ ls /usr/lib/python3.7/site-packages/gi/
_compat.py     docstring.py  _gi_cairo.cpython-37m-x86_64-linux-gnu.so	_gtktemplate.py  __init__.py  _option.py       overrides	   __pycache__	   repository	     types.py
_constants.py  _error.py     _gi.cpython-37m-x86_64-linux-gnu.so	importer.py	 module.py    _ossighelper.py  _propertyhelper.py  pygtkcompat.py  _signalhelper.py
```

Pylint seems to work fine by itself:
```
[ptv] bash-5.0$ pylint --rcfile pylint.rc build/flatpak/pitivi-flatpak 

-------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 7.38/10, +2.62)
```

The error seems to be due to pre-commit using its own pylint rather than the "system" pylint. Any idea how to make this work?

**Comment by asottile** [comment]
hi, thanks for the issue but in the future please [search the issue tracker](https://github.com/pre-commit/pre-commit-hooks/issues/157) or [read the docs](https://pre-commit.com/#repository-local-hooks)!

**Comment by aleb** [comment]
Every time I read the "Repository local hooks" I skipped that section, because I never thought I have a "local hook". All the hooks I'm using are external hooks, which are not part of my project. I think a different title would draw more attention to what's possible.

I'll make time to at least propose a fix to https://github.com/pre-commit/mirrors-pylint/blob/master/README.md to explain the limitations.

Thanks for the quick reply!

**Comment by asottile** [comment]
PRs welcome of course, if you think you can improve what's there :)

**Comment by allen-munsch** [comment]
wipe and reinstall seemed to work.

something got funked up

```
sudo rm $(which pre-commit)
sudo rm $(which pre-commit-validate-config)
sudo rm $(which pre-commit-validate-manifest)
sudo rm -rf my_venv
virtualenv new_venv
source new_venv/bin/activate
pip install -r requirements.txt
# ... some time later ...
pre-commit install
```

**Comment by asottile** [comment]
I suspect it's your liberal use of `sudo` -- which should never be necessary when using `pre-commit`
