### ISSUE TITLE
RuntimeError: 'Exec format error' when using pipenv+pyenv-installed python 3.8.1 to install environment

### ISSUE THREAD

**Issue by mhoonjeon** [pre-commit/pre-commit#1321]
I have been using pre-commit for pipenv + pyenv-installed python 3.8.1 django development.
Up until yesterday everything was working, then after trying to update with `pre-commit autoupdate`, I cannot recreate pre-commit environment.

# Console log
```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/bin/python3', '-mvirtualenv', '/Users/mhjeon/.cache/pre-commit/repoezpu4zo2/py_env-python3', '-p', '/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/bin/python3')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to query /Users/mhjeon/.pyenv/versions/3.8.1/Python.framework/Versions/3.8/python with code 8 err: 'Exec format error'

stderr: (none)
Check the log at /Users/mhjeon/.cache/pre-commit/pre-commit.log
```

# Output of pre-commit.log
```
### version information
pre-commit version: 2.0.1
sys.version:
    3.8.1 (default, Feb  8 2020, 01:32:24)
    [Clang 11.0.0 (clang-1100.0.33.17)]
sys.executable: /Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/bin/python3
os.name: posix
sys.platform: darwin

### error information
An unexpected error has occurred: CalledProcessError: command: ('/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/bin/python3', '-mvirtualenv', '/Users/mhjeon/.cache/pre-commit/repoezpu4zo2/py_env-python3', '-p', '/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/bin/python3')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to query /Users/mhjeon/.pyenv/versions/3.8.1/Python.framework/Versions/3.8/python with code 8 err: 'Exec format error'

stderr: (none)
Traceback (most recent call last):
  File "/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/lib/python3.8/site-packages/pre_commit/error_handler.py", line 54, in error_handler
    yield
  File "/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/lib/python3.8/site-packages/pre_commit/main.py", line 344, in main
    return hook_impl(
  File "/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/lib/python3.8/site-packages/pre_commit/commands/hook_impl.py", line 180, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/lib/python3.8/site-packages/pre_commit/commands/run.py", line 337, in run
    install_hook_envs(hooks, store)
  File "/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/lib/python3.8/site-packages/pre_commit/repository.py", line 200, in install_hook_envs
    _hook_install(hook)
  File "/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/lib/python3.8/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/lib/python3.8/site-packages/pre_commit/languages/python.py", line 192, in install_environment
    _make_venv(env_dir, python)
  File "/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/lib/python3.8/site-packages/pre_commit/languages/python.py", line 204, in make_venv
    cmd_output_b(*cmd, env=env, cwd='/')
  File "/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/lib/python3.8/site-packages/pre_commit/util.py", line 126, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/bin/python3', '-mvirtualenv', '/Users/mhjeon/.cache/pre-commit/repoezpu4zo2/py_env-python3', '-p', '/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/bin/python3')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to query /Users/mhjeon/.pyenv/versions/3.8.1/Python.framework/Versions/3.8/python with code 8 err: 'Exec format error'
stderr: (none)
```
 
# .pre-commit-config-yaml
```
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml
    - id: debug-statements
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: flake8
    - id: pretty-format-json
      args:
      - --autofix
      exclude: Pipfile.lock
    - id: trailing-whitespace

- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3.8

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5
  hooks:
    - id: autopep8

- repo: https://github.com/pre-commit/pre-commit
  rev: v2.0.1
  hooks:
    - id: validate_manifest

- repo: https://github.com/asottile/pyupgrade
  rev: v1.26.2
  hooks:
  - id: pyupgrade

- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.4
  hooks:
  - id: seed-isort-config
    args: [--application-directories=nowwow]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort
    language_version: python3.8

```

I have been trying to recreate the environment after cleaning up pre-commit cache with `pre-commit clean` but it did not work. Any ideas?

**Comment by asottile** [comment]
sounds like you've broken you renvironment in some way?  you're invoking `virtualenv` and it's crashing in that way -- my guess is if you ran this separately you'd see the same problem (without involving pre-commit)

```
/Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/bin/python3 -mvirtualenv /tmp/env -p /Users/mhjeon/.local/share/virtualenvs/nowwow-0D8RInBf/bin/python3
```

That error message is coming from `virtualenv` (and the 20.x betas) so I suspect something is broken there -- please open an issue on virtualenv (ideally with a reproduction not involving pre-commit, the command above should suffice)

CC @gaborbernat

**Comment by asottile** [comment]
a workaround is likely to use `virtualenv<20` until it is fixed
