### ISSUE TITLE
git commit error when installing precommit hook in venv

### ISSUE THREAD

**Issue by kguoskupos** [pre-commit/pre-commit#1327]
Hi, when I try to commit with pre-commit hooks I kept getting the following error: 

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/bin/python3', '-mvirtualenv', '/Users/kaiki/.cache/pre-commit/repo64vxufbr/py_env-python3', '-p', '/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/bin/python3')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to query /Library/Frameworks/Python.framework/Versions/3.8/python with code 8 err: 'Exec format error'
    
stderr: (none)

Traceback (most recent call last):
  File "/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/lib/python3.8/site-packages/pre_commit/error_handler.py", line 54, in error_handler
    yield
  File "/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/lib/python3.8/site-packages/pre_commit/main.py", line 344, in main
    return hook_impl(
  File "/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/lib/python3.8/site-packages/pre_commit/commands/hook_impl.py", line 180, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/lib/python3.8/site-packages/pre_commit/commands/run.py", line 337, in run
    install_hook_envs(hooks, store)
  File "/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/lib/python3.8/site-packages/pre_commit/repository.py", line 200, in install_hook_envs
    _hook_install(hook)
  File "/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/lib/python3.8/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/lib/python3.8/site-packages/pre_commit/languages/python.py", line 192, in install_environment
    _make_venv(env_dir, python)
  File "/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/lib/python3.8/site-packages/pre_commit/languages/python.py", line 204, in make_venv
    cmd_output_b(*cmd, env=env, cwd='/')
  File "/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/lib/python3.8/site-packages/pre_commit/util.py", line 126, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/bin/python3', '-mvirtualenv', '/Users/kaiki/.cache/pre-commit/repo64vxufbr/py_env-python3', '-p', '/Users/kaiki/.local/share/virtualenvs/DataOps-scripts-FQNCwOd4/bin/python3')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to query /Library/Frameworks/Python.framework/Versions/3.8/python with code 8 err: 'Exec format error'
    
stderr: (none)
```

pre-commit version:  `2.0.1`
git version: `2.20.1` 

.pre-commit-config.yaml:
```
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v1.5.0
    hooks:
      - id: add-trailing-comma
```
Thank you for your help!

**Comment by asottile** [comment]
this appears to be the same as #1312 and caused by virtualenv 20.x CC @gaborbernat

if you have a consistent reproduction I'd suggest posting it to #1545
