### ISSUE TITLE
 AttributeError: 'str' object has no attribute 'exists'

### ISSUE THREAD

**Issue by milind-shakya-sp** [pre-commit/pre-commit#1347]
```
16:33:21  [INFO] This may take a few minutes...
16:33:22  An unexpected error has occurred: CalledProcessError: Command: ('/tmp/jenkins-PR-4834-1/precommit/bin/python', '-mvirtualenv', '/home/jenkins/.cache/pre-commit/repo3o_xa3rm/py_env-python3', '-p', 'python3')
16:33:22  Return code: 1
16:33:22  Expected return code: 0
16:33:22  Output: 
16:33:22      AttributeError: 'str' object has no attribute 'exists'
```

Any ideas on how to fix the above precommit issue? 
  

Precommit version: 1.11.1
Python: 3.6.8

**Comment by milind-shakya-sp** [comment]
Tried `pre-commit clean` but that did not seem to help either

**Comment by asottile** [comment]
can you provide the full log output? note that pre-commit 1.11.1 is very very old (2018-09-22)

**Comment by milind-shakya-sp** [comment]
Yeah need to update it but I just bumped up the version to 2.1.1 and it still had the same issue.

Heres the output, thanks for the extra pair of 👀 

```
Traceback (most recent call last):

[2020-02-25T19:52:15.259Z]   File "/tmp/jenkins-PR-4829-12/precommit/lib/python3.6/site-packages/pre_commit/error_handler.py", line 47, in error_handler

[2020-02-25T19:52:15.259Z]     yield

[2020-02-25T19:52:15.259Z]   File "/tmp/jenkins-PR-4829-12/precommit/lib/python3.6/site-packages/pre_commit/main.py", line 261, in main

[2020-02-25T19:52:15.259Z]     return run(runner, store, args)

[2020-02-25T19:52:15.259Z]   File "/tmp/jenkins-PR-4829-12/precommit/lib/python3.6/site-packages/pre_commit/commands/run.py", line 268, in run

[2020-02-25T19:52:15.259Z]     repo.require_installed()

[2020-02-25T19:52:15.259Z]   File "/tmp/jenkins-PR-4829-12/precommit/lib/python3.6/site-packages/pre_commit/repository.py", line 195, in require_installed

[2020-02-25T19:52:15.259Z]     _install_all(self._venvs(), self.repo_config['repo'], self.store)

[2020-02-25T19:52:15.259Z]   File "/tmp/jenkins-PR-4829-12/precommit/lib/python3.6/site-packages/pre_commit/repository.py", line 102, in _install_all

[2020-02-25T19:52:15.259Z]     language.install_environment(prefix, version, deps)

[2020-02-25T19:52:15.259Z]   File "/tmp/jenkins-PR-4829-12/precommit/lib/python3.6/site-packages/pre_commit/languages/python.py", line 142, in install_environment

[2020-02-25T19:52:15.259Z]     _make_venv(env_dir, python)

[2020-02-25T19:52:15.259Z]   File "/tmp/jenkins-PR-4829-12/precommit/lib/python3.6/site-packages/pre_commit/languages/python.py", line 154, in make_venv

[2020-02-25T19:52:15.259Z]     cmd_output(*cmd, env=env, cwd='/')

[2020-02-25T19:52:15.259Z]   File "/tmp/jenkins-PR-4829-12/precommit/lib/python3.6/site-packages/pre_commit/util.py", line 177, in cmd_output

[2020-02-25T19:52:15.259Z]     returncode, cmd, retcode, output=(stdout, stderr),

[2020-02-25T19:52:15.259Z] pre_commit.util.CalledProcessError: Command: ('/tmp/jenkins-PR-4829-12/precommit/bin/python', '-mvirtualenv', '/home/jenkins/.cache/pre-commit/repo3fatk3iz/py_env-python3', '-p', 'python3')

[2020-02-25T19:52:15.259Z] Return code: 1

[2020-02-25T19:52:15.259Z] Expected return code: 0

[2020-02-25T19:52:15.259Z] Output: 

[2020-02-25T19:52:15.259Z]     AttributeError: 'str' object has no attribute 'exists'

[2020-02-25T19:52:15.259Z]     

[2020-02-25T19:52:15.259Z] Errors: (none)
```

**Comment by asottile** [comment]
what version of `virtualenv` do you have installed?

**Comment by milind-shakya-sp** [comment]
`virtualenv 20.0.5`

btw it looks like it started happening after the introduction of `https://github.com/pre-commit/mirrors-mypy` hook. which is weird because it works locally, but it does not work on some remote machines.

**Comment by asottile** [comment]
the error implies that `virtualenv` is failing (and not actually `pre-commit` itself) -- it's possible you have a `virtualenv.py` file? -- what does this give you?

```python
/tmp/jenkins-PR-4829-12/precommit/bin/python -c 'import virtualenv; print(virtualenv)'
```

**Comment by milind-shakya-sp** [comment]
Gives the following
```
<module 'virtualenv' from '/tmp/jenkins-PR-4836-2/precommit/lib/python3.6/site-packages/virtualenv/__init__.py'>
```

**Comment by asottile** [comment]
and what happens if you run:

```
python3 --version
/tmp/jenkins-PR-4829-12/precommit/bin/python -m virtualenv venv -ppython3
```

**Comment by milind-shakya-sp** [comment]
```
InvocationError for command /tmp/jenkins-PR-4836-2/precommit/bin/python -c 'import virtualenv; print(virtualenv)' (exited with code 2)
```

**Comment by asottile** [comment]
but wait, that's the command that ran before and spit out the `<module ...>` output?

**Comment by milind-shakya-sp** [comment]
sorry, had a typo.

It returns `Python 3.6.8`

**Comment by asottile** [comment]
and the second command there which tries to invoke virtualenv?

**Comment by milind-shakya-sp** [comment]
```
<module 'virtualenv' from '/tmp/jenkins-singleplatform-spdj-PR-4836-7/precommit/lib/python3.6/site-packages/virtualenv/__init__.py'>
```

**Comment by asottile** [comment]
the second command is very different (but looks similar) to the one I had before, make sure you're copying the right one

**Comment by milind-shakya-sp** [comment]
its the same, its running in a build so the numbers get updated.

**Comment by asottile** [comment]
right, but the output should look something like this (for example using virtualenv 20.0.5):

```console
$ virtualenv venv -vvv -p python3
49 setup logging to NOTSET [DEBUG report:43]
55 find interpreter for spec PythonSpec(implementation=CPython, major=3) [INFO builtin:43]
56 discover system for PythonInfo(spec=CPython3.6.9.final.0-64, exe=/home/asottile/workspace/covdefaults/venv/bin/python, platform=linux, version='3.6.9 (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]', encoding_fs_io=utf-8-UTF-8) in /usr [DEBUG py_info:336]
56 filesystem is case-sensitive [DEBUG info:28]
57 Attempting to acquire lock 140119707858144 on /home/asottile/.local/share/virtualenv/py-info/20.0.5/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [DEBUG filelock:270]
57 Lock 140119707858144 acquired on /home/asottile/.local/share/virtualenv/py-info/20.0.5/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [INFO filelock:274]
57 get PythonInfo from /home/asottile/.local/share/virtualenv/py-info/20.0.5/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.json for /usr/bin/python3.6 [DEBUG cached_py_info:72]
57 Attempting to release lock 140119707858144 on /home/asottile/.local/share/virtualenv/py-info/20.0.5/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [DEBUG filelock:315]
57 Lock 140119707858144 released on /home/asottile/.local/share/virtualenv/py-info/20.0.5/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [INFO filelock:318]
57 proposed PythonInfo(spec=CPython3.6.9.final.0-64, system=/usr/bin/python3.6, exe=/home/asottile/workspace/covdefaults/venv/bin/python, platform=linux, version='3.6.9 (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]', encoding_fs_io=utf-8-UTF-8) [INFO builtin:49]
57 accepted PythonInfo(spec=CPython3.6.9.final.0-64, system=/usr/bin/python3.6, exe=/home/asottile/workspace/covdefaults/venv/bin/python, platform=linux, version='3.6.9 (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]', encoding_fs_io=utf-8-UTF-8) [DEBUG builtin:51]
75 create virtual environment via CPython3Posix(dest=/tmp/venv, clear=False, global=False) [INFO session:51]
75 create folder /tmp/venv/bin [DEBUG _sync:20]
75 create folder /tmp/venv/lib/python3.6/site-packages [DEBUG _sync:20]
75 write /tmp/venv/pyvenv.cfg [DEBUG pyenv_cfg:34]
75 	home = /usr [DEBUG pyenv_cfg:38]
75 	implementation = CPython [DEBUG pyenv_cfg:38]
76 	version_info = 3.6.9.final.0 [DEBUG pyenv_cfg:38]
76 	virtualenv = 20.0.5 [DEBUG pyenv_cfg:38]
76 	include-system-site-packages = false [DEBUG pyenv_cfg:38]
76 	base-prefix = /usr [DEBUG pyenv_cfg:38]
76 	base-exec-prefix = /usr [DEBUG pyenv_cfg:38]
76 	base-executable = /usr/bin/python3.6 [DEBUG pyenv_cfg:38]
76 symlink /usr/bin/python3.6 to /tmp/venv/bin/python [DEBUG _sync:39]
76 ============================== target debug ============================== [DEBUG session:53]
76 debug via /tmp/venv/bin/python /home/asottile/workspace/covdefaults/venv/lib/python3.6/site-packages/virtualenv/create/debug.py [DEBUG creator:191]
76 {
  "sys": {
    "executable": "/tmp/venv/bin/python",
    "_base_executable": null,
    "prefix": "/tmp/venv",
    "base_prefix": "/usr",
    "real_prefix": null,
    "exec_prefix": "/tmp/venv",
    "base_exec_prefix": "/usr",
    "path": [
      "/usr/lib/python36.zip",
      "/usr/lib/python3.6",
      "/usr/lib/python3.6/lib-dynload",
      "/tmp/venv/lib/python3.6/site-packages"
    ],
    "meta_path": [
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "UTF-8"
  },
  "version": "3.6.9 (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]",
  "os": "<module 'os' from '/usr/lib/python3.6/os.py'>",
  "site": "<module 'site' from '/usr/lib/python3.6/site.py'>",
  "datetime": "<module 'datetime' from '/usr/lib/python3.6/datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from '/usr/lib/python3.6/json/__init__.py'>"
} [DEBUG session:54]
100 add seed packages via FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/asottile/.local/share/virtualenv/seed-v1) [INFO session:58]
101 Attempting to acquire lock 140119707278920 on /home/asottile/.local/share/virtualenv/seed-v1/3.6/wheels.lock [DEBUG filelock:270]
101 Lock 140119707278920 acquired on /home/asottile/.local/share/virtualenv/seed-v1/3.6/wheels.lock [INFO filelock:274]
102 install pip from wheel /home/asottile/.local/share/virtualenv/seed-v1/3.6/wheels/pip-20.0.2-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:56]
102 install setuptools from wheel /home/asottile/.local/share/virtualenv/seed-v1/3.6/wheels/setuptools-45.2.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:56]
102 copy directory /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/pip-20.0.2-py2.py3-none-any/pip to /tmp/venv/lib/python3.6/site-packages/pip [DEBUG _sync:47]
102 install wheel from wheel /home/asottile/.local/share/virtualenv/seed-v1/3.6/wheels/wheel-0.34.2-py2.py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:56]
103 copy directory /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/setuptools-45.2.0-py3-none-any/setuptools-45.2.0.dist-info to /tmp/venv/lib/python3.6/site-packages/setuptools-45.2.0.dist-info [DEBUG _sync:47]
103 copy directory /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel to /tmp/venv/lib/python3.6/site-packages/wheel [DEBUG _sync:47]
107 copy /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/setuptools-45.2.0-py3-none-any/setuptools-45.2.0.virtualenv to /tmp/venv/lib/python3.6/site-packages/setuptools-45.2.0.virtualenv [DEBUG _sync:47]
107 copy directory /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/setuptools-45.2.0-py3-none-any/pkg_resources to /tmp/venv/lib/python3.6/site-packages/pkg_resources [DEBUG _sync:47]
111 copy directory /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel-0.34.2.dist-info to /tmp/venv/lib/python3.6/site-packages/wheel-0.34.2.dist-info [DEBUG _sync:47]
115 copy /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/wheel-0.34.2-py2.py3-none-any/wheel-0.34.2.virtualenv to /tmp/venv/lib/python3.6/site-packages/wheel-0.34.2.virtualenv [DEBUG _sync:47]
117 copy /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/setuptools-45.2.0-py3-none-any/easy_install.py to /tmp/venv/lib/python3.6/site-packages/easy_install.py [DEBUG _sync:47]
118 copy directory /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/setuptools-45.2.0-py3-none-any/setuptools to /tmp/venv/lib/python3.6/site-packages/setuptools [DEBUG _sync:47]
151 changing mode of /tmp/venv/bin/wheel-3.6 to 755 [INFO util:566]
151 changing mode of /tmp/venv/bin/wheel3 to 755 [INFO util:566]
151 changing mode of /tmp/venv/bin/wheel to 755 [INFO util:566]
152 generated console scripts wheel wheel3 wheel-3.6 [DEBUG base:48]
166 changing mode of /tmp/venv/bin/easy_install3 to 755 [INFO util:566]
166 changing mode of /tmp/venv/bin/easy_install to 755 [INFO util:566]
166 changing mode of /tmp/venv/bin/easy_install-3.6 to 755 [INFO util:566]
167 generated console scripts easy_install easy_install-3.6 easy_install3 [DEBUG base:48]
188 copy /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/pip-20.0.2-py2.py3-none-any/pip-20.0.2.virtualenv to /tmp/venv/lib/python3.6/site-packages/pip-20.0.2.virtualenv [DEBUG _sync:47]
189 copy directory /home/asottile/.local/share/virtualenv/seed-v1/3.6/image/CopyPipInstall/pip-20.0.2-py2.py3-none-any/pip-20.0.2.dist-info to /tmp/venv/lib/python3.6/site-packages/pip-20.0.2.dist-info [DEBUG _sync:47]
190 changing mode of /tmp/venv/bin/pip-3.6 to 755 [INFO util:566]
190 changing mode of /tmp/venv/bin/pip3 to 755 [INFO util:566]
190 changing mode of /tmp/venv/bin/pip to 755 [INFO util:566]
190 generated console scripts pip-3.6 pip pip3 [DEBUG base:48]
190 Attempting to release lock 140119707278920 on /home/asottile/.local/share/virtualenv/seed-v1/3.6/wheels.lock [DEBUG filelock:315]
190 Lock 140119707278920 released on /home/asottile/.local/share/virtualenv/seed-v1/3.6/wheels.lock [INFO filelock:318]
191 add activators for Bash, CShell, Fish, PowerShell, Python, Xonsh [INFO session:64]
192 write /tmp/venv/pyvenv.cfg [DEBUG pyenv_cfg:34]
192 	home = /usr [DEBUG pyenv_cfg:38]
192 	implementation = CPython [DEBUG pyenv_cfg:38]
192 	version_info = 3.6.9.final.0 [DEBUG pyenv_cfg:38]
192 	virtualenv = 20.0.5 [DEBUG pyenv_cfg:38]
192 	include-system-site-packages = false [DEBUG pyenv_cfg:38]
192 	base-prefix = /usr [DEBUG pyenv_cfg:38]
192 	base-exec-prefix = /usr [DEBUG pyenv_cfg:38]
192 	base-executable = /usr/bin/python3.6 [DEBUG pyenv_cfg:38]
192 created virtual environment CPython3.6.9.final.0-64 in 144ms
  creator CPython3Posix(dest=/tmp/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/asottile/.local/share/virtualenv/seed-v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator [WARNING __main__:21]
```

**Comment by milind-shakya-sp** [comment]
```
[2020-02-25T23:02:41.376Z] precommit run-test: commands[3] | /tmp/jenkins-PR-4836-9/precommit/bin/python -m virtualenv venv -ppython3

[2020-02-25T23:02:41.626Z] AttributeError: 'str' object has no attribute 'exists'

[2020-02-25T23:02:41.634Z] ERROR: InvocationError for command /tmp/jenkins--PR-4836-9/precommit/bin/python -m virtualenv venv -ppython3 (exited with code 1)

[2020-02-25T23:02:41.634Z] ___________________________________ summary ____________________________________
```

**Comment by milind-shakya-sp** [comment]
Thats what I get, looks like the 2nd command did not run earlier.

**Comment by asottile** [comment]
looks like your installation of `virtualenv` is corrupted in some way -- since that  looks like `tox` output can you paste more of it? I'm particularly interested in the list of pip packages it has

**Comment by asottile** [comment]
oh could you also try that command with `--with-traceback`? that should give a better output so you can report a bug at https://github.com/pypa/virtualenv

**Comment by milind-shakya-sp** [comment]
```
[2020-02-26T19:03:47.920Z] + tox --workdir=/tmp/jenkins---PR-4836-12/ -e precommit
[2020-02-26T19:03:48.839Z] precommit create: /tmp/jenkins---PR-4836-12/precommit
[2020-02-26T19:04:10.644Z] precommit installdeps: pre-commit==1.11.1
[2020-02-26T19:04:25.413Z] precommit installed: appdirs==1.4.3,aspy.yaml==1.3.0,cached-property==1.5.1,cfgv==3.1.0,distlib==0.3.0,file
lock==3.0.12,identify==1.4.11,importlib-metadata==1.5.0,importlib-resources==1.0.2,nodeenv==1.3.5,pre-commit==1.11.1,PyYAML==5.3,six==
1.14.0,toml==0.10.0,virtualenv==20.0.7,zipp==3.0.0
[2020-02-26T19:04:25.421Z] precommit run-test-pre: PYTHONHASHSEED='1694222676'
[2020-02-26T19:04:25.421Z] precommit run-test: commands[0] | virtualenv --version
[2020-02-26T19:04:25.421Z] virtualenv 20.0.7 from /tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/_init_.
py
[2020-02-26T19:04:25.421Z] precommit run-test: commands[1] | /tmp/jenkins---PR-4836-12/precommit/bin/python -c 'import virtualenv; pri
nt(virtualenv)'
[2020-02-26T19:04:25.421Z] <module 'virtualenv' from '/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/_ini
t_.py'>
[2020-02-26T19:04:25.421Z] precommit run-test: commands[2] | python3 --version
[2020-02-26T19:04:25.421Z] Python 3.6.8
[2020-02-26T19:04:25.421Z] precommit run-test: commands[3] | /tmp/jenkins---PR-4836-12/precommit/bin/python -m virtualenv venv -ppytho
n3 --with-traceback
[2020-02-26T19:04:25.421Z] Traceback (most recent call last):
[2020-02-26T19:04:25.421Z]   File "/opt/Python-3.6.8/lib/python3.6/runpy.py", line 193, in _run_module_as_main
[2020-02-26T19:04:25.421Z]     "_main_", mod_spec)
[2020-02-26T19:04:25.421Z]   File "/opt/Python-3.6.8/lib/python3.6/runpy.py", line 85, in _run_code
[2020-02-26T19:04:25.421Z]     exec(code, run_globals)
[2020-02-26T19:04:25.421Z]   File "/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/_main_.py", line 61, i
n <module>
[2020-02-26T19:04:25.421Z]     run_with_catch()
[2020-02-26T19:04:25.421Z]   File "/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/_main_.py", line 50, i
n run_with_catch
[2020-02-26T19:04:25.421Z]     run(args, options)
[2020-02-26T19:04:25.421Z]   File "/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/_main_.py", line 20, i
n run
[2020-02-26T19:04:25.421Z]     session = cli_run(args, options)
[2020-02-26T19:04:25.421Z]   File "/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/run/_init_.py", line 2
7, in cli_run
[2020-02-26T19:04:25.421Z]     session = session_via_cli(args, options)
[2020-02-26T19:04:25.421Z]   File "/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/run/_init_.py", line 3
7, in session_via_cli
[2020-02-26T19:04:25.421Z]     creator, seeder, activators = tuple(e.create(parser._options) for e in parser._elements)  # create type
s
[2020-02-26T19:04:25.421Z]   File "/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/run/_init_.py", line 3
7, in <genexpr>
[2020-02-26T19:04:25.421Z]     creator, seeder, activators = tuple(e.create(parser._options) for e in parser._elements)  # create type
s
[2020-02-26T19:04:25.421Z]   File "/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/run/plugin/seeders.py",
line 31, in create
[2020-02-26T19:04:25.421Z]     return self._impl_class(options)
[2020-02-26T19:04:25.421Z]   File "/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/seed/via_app_data/via_ap
p_data.py", line 19, in _init_
[2020-02-26T19:04:25.421Z]     super(FromAppData, self)._init_(options)
[2020-02-26T19:04:25.421Z]   File "/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/seed/embed/base_embed.py
", line 21, in _init_
[2020-02-26T19:04:25.421Z]     self.extra_search_dir = [i.resolve() for i in options.extra_search_dir if i.exists()]
[2020-02-26T19:04:25.421Z]   File "/tmp/jenkins---PR-4836-12/precommit/lib/python3.6/site-packages/virtualenv/seed/embed/base_embed.py
", line 21, in <listcomp>
[2020-02-26T19:04:25.421Z]     self.extra_search_dir = [i.resolve() for i in options.extra_search_dir if i.exists()]
[2020-02-26T19:04:25.421Z] AttributeError: 'str' object has no attribute 'exists'
[2020-02-26T19:04:25.421Z] ERROR: InvocationError for command /tmp/jenkins---PR-4836-12/precommit/bin/python -m virtualenv venv -ppyth
on3 --with-traceback (exited with code 1)
[2020-02-26T19:04:25.421Z] ___________________________________ summary ____________________________________
[2020-02-26T19:04:25.421Z] ERROR:   precommit: commands failed
script returned exit code 1
```

**Comment by milind-shakya-sp** [comment]
i ll open an issue https://github.com/pypa/virtualenv. Thanks for your help.

**Comment by asottile** [comment]
sounds good :+1:
