### ISSUE TITLE
Windows: shebang gets crippled

### ISSUE THREAD

**Issue by MrGung** [pre-commit/pre-commit#1373]
I am trying to get pre-commit working for two days now.

I tried back and forth and settled with going down the py-script road. I.e. I abandoned console_script in my setup and switched to plain scripts-option.

It's now that the shebang that gets generated into the scripts and looks something like
`#!\\remotedrive\HOME\.cache\pre-commit\repoe1_y_asr\py_env-python3.7\Scripts\python.exe`

will be parsed (obviously via shlex) as
`\remotedriveHOME.cachepre-commitrepoe1_y_asrpy_env-python3.7Scriptspython.exe`

What went wrong? Is there a setting I am missing?

desperately ;-)
Steffen

**Comment by asottile** [comment]
do you have a reproduction?  as far as I know setuptools/distutils `scripts` isn't designed to work on windows and that `console_scripts` is the only portable option

**Comment by MrGung** [comment]
So I switched back to console_scripts. Thanks for that.

The first push results in:

```
[INFO] Initializing environment for https://.../githooks.
[INFO] Installing environment for https://.../githooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('Q:\\HOME\\.cache\\pre-commit\\repordqzkn96\\py_env-python3.7\\Scripts\\pip.EXE', 'install', '.')
return code: 2
expected return code: 0
stdout:
Looking in indexes: https://.../artifactory/api/pypi/py-quarantaene-mirror/simple/
Processing q:\home\.cache\pre-commit\repordqzkn96
Building wheels for collected packages: pre-commit-push-hooks
Building wheel for pre-commit-push-hooks (setup.py): started
Building wheel for pre-commit-push-hooks (setup.py): finished with status 'done'
Created wheel for pre-commit-push-hooks: filename=pre_commit_push_hooks-0.1.0-py2.py3-none-any.whl size=2383 sha256=c2b7813f857e34882540801ce54ce3d58157f964bb428f48c23bbda3fc572bd2
Stored in directory: D:\Users\...\AppData\Local\Temp\pip-ephem-wheel-cache-66d5ffna\wheels\d4\3a\8b\2329a3a91af63fa286ed3616d30f4b11ec03a6c92a4c6ed7b2
Successfully built pre-commit-push-hooks
Installing collected packages: pre-commit-push-hooks
Successfully installed pre-commit-push-hooks-0.1.0
User for repo.bk.datev.de:
stderr:
ERROR: Exception:
Traceback (most recent call last):
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
status = self.run(options, args)
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_internal\commands\install.py", line 449, in run
requirement_set.cleanup_files()
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_internal\req\req_set.py", line 209, in cleanup_files
req.remove_temporary_source()
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_internal\req\req_install.py", line 424, in remove_temporary_source
self._temp_build_dir.cleanup()
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_internal\utils\temp_dir.py", line 175, in cleanup
rmtree(self._path)
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
return Retrying(*dargs, **dkw).call(f, *args, **kw)
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
raise attempt.get()
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
six.reraise(self.value[0], self.value[1], self.value[2])
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_vendor\six.py", line 703, in reraise
raise value
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
File "\\...\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\lib\site-packages\pip\_internal\utils\misc.py", line 136, in rmtree
onerror=rmtree_errorhandler)
File "c:\program files\anaconda3\lib\shutil.py", line 516, in rmtree
return _rmtree_unsafe(path, onerror)
File "c:\program files\anaconda3\lib\shutil.py", line 377, in _rmtree_unsafe
onerror(os.scandir, path, sys.exc_info())
File "c:\program files\anaconda3\lib\shutil.py", line 374, in _rmtree_unsafe
with os.scandir(path) as scandir_it:
PermissionError: [WinError 5] Zugriff verweigert: 'D:\\Users\\...\\AppData\\Local\\Temp\\pip-req-build-akgqlpv0'

Check the log at Q:\HOME/.cache\pre-commit\pre-commit.log
error: failed to push some refs to 'https://.../tools/splunkdb2analyzer.git'
```

Without changing anything - another push gets me this:

```
[INFO] Installing environment for https://.../githooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Keeping marked commits local.............................................Failed
- hook id: KEEP_LOCAL
- exit code: 1

Traceback (most recent call last):
File "c:\program files\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\program files\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "Q:\HOME\.cache\pre-commit\repordqzkn96\py_env-python3.7\Scripts\KEEP_LOCAL.EXE\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'KEEP_LOCAL'
```

Which is what me got to trying out the scripts-option.

Somehow **__main__.py** gets added to the actual exe's name...

Debugging this I went down the rabbit hole until I stumbled over **runpy**...

**Comment by asottile** [comment]
can you share your source repository? I suspect you're missing `packages` in `setup.py`/`setup.cfg`

**Comment by MrGung** [comment]
No, I currently can't share it. What would I have to look out for?

**Comment by asottile** [comment]
your setup.py+setup.cfg would be a good start 👍

**Comment by MrGung** [comment]
Here we go:

```
[metadata]
name = pre_commit|push_hooks
version = 0.1.0
description = pre-commit and pre-push hooks
long_description = file: README.md
long_description_content_type = text/markdown
url = https://.../githooks

[options]
packages = find:
python_requires = >=3.6.1

[options.entry_points]
console_scripts =
    keep_local = KEEP_LOCAL:main
    reki_releasebuild = REKI_RELEASEBUILD:main

[options.packages.find]
exclude =
    tests*
    testing*

[bdist_wheel]
universal = True
```

and setup.py:

```
from setuptools import setup
setup()
```

**Comment by asottile** [comment]
ok that looks good except the `name` is invalid (it cannot contain `|` -- needs to be `[a-zA-Z0-9_]+`

can you show the files in that directory? `dir` / `ls -al` / `tree`

**Comment by MrGung** [comment]
That would be - quite simply:

```
.pre-commit-hooks.yaml
applypatch-msg.sample
commit-msg.sample
fsmonitor-watchman.sample
KEEP_LOCAL
post-update.sample
pre-applypatch.sample
pre-commit.sample
prepare-commit-msg.sample
pre-push.sample
pre-rebase.sample
pre-receive.sample
README.md
REKI_RELEASEBUILD
setup.cfg
setup.py
update.sample
```

The content of .pre-commit-hooks.yaml being:

```
- id: KEEP_LOCAL
  name: Keeping marked commits local
  description: Commits with messages containing LOCAL or KEEPLOCAL will cause the push to abort.
  entry: KEEP_LOCAL
  pass_filenames: false
  language: python

- id: REKI_RELEASEBUILD
  name: Starting local Release-Build
  description: Trying a local Release-Build in the background. Preparing for Gated Checkin.
  entry: REKI_RELEASEBUILD
  pass_filenames: false
  language: python
```

**Comment by asottile** [comment]
mk, those `entry`s should match case for portability but it's probably not your problem (your entries in `setup.cfg` are lower case but upper case in `.pre-commit-hooks.yaml`)

can you show the contents of `KEEP_LOCAL/__init__.py`?

**Comment by MrGung** [comment]
KEEP_LOCAL.EXE exists in \py_env-python3.7\Scripts\...

**Comment by MrGung** [comment]
KEEP_LOCAL is not a module - it's python-script.

**Comment by asottile** [comment]
ok, well that's why `console_scripts` is not working then :)

you've got two options then

1. convert it to a package: `KEEP_LOCAL/__init__.py` (this keeps your setup.cfg the same)
2. convert it to a python file `KEEP_LOCAL.py` -- this changes your setup.cfg:
    - remove `options.packages.find` section
    - replace `[options]packages` with `[options]py_modules` and put `KEEP_LOCAL` as a py_module (for example: https://github.com/asottile/pyupgrade/blob/0e8c31e03e15a13526a6c03b559fdd22dd253a20/setup.cfg#L23)

**Comment by MrGung** [comment]
That was it. 

Thank you so much! Thanks for your quick responses!

**Comment by asottile** [comment]
cheers, python packaging is hard ;)
