### ISSUE TITLE
C:\python2\python.exe does not exists

### ISSUE THREAD

**Issue by Mattwmaster58** [pre-commit/pre-commit#1396]
Here's the log entry:
<details>

```
### version information

\```
pre-commit version: 2.2.0
sys.version:
    3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
sys.executable: c:\users\<my username>\.local\pipx\venvs\pre-commit\scripts\python.exe
os.name: nt
sys.platform: win32
\```

### error information

\```
An unexpected error has occurred: CalledProcessError: command: ('c:\\users\\<my username>\\.local\\pipx\\venvs\\pre-commit\\scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\<my username>\\.cache\\pre-commit\\repownrpu7d5\\py_env-python2', '-p', 'C:\\python2\\python.exe')
return code: 1
expected return code: 0
stdout:
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\python2\\python.exe'
    
stderr: (none)
\```

\```
Traceback (most recent call last):
  File "c:\users\<my username>\.local\pipx\venvs\pre-commit\lib\site-packages\pre_commit\error_handler.py", line 56, in error_handler
    yield
  File "c:\users\<my username>\.local\pipx\venvs\pre-commit\lib\site-packages\pre_commit\main.py", line 365, in main
    return hook_impl(
  File "c:\users\<my username>\.local\pipx\venvs\pre-commit\lib\site-packages\pre_commit\commands\hook_impl.py", line 187, in hook_impl
    return retv | run(config, store, ns)
  File "c:\users\<my username>\.local\pipx\venvs\pre-commit\lib\site-packages\pre_commit\commands\run.py", line 355, in run
    install_hook_envs(hooks, store)
  File "c:\users\<my username>\.local\pipx\venvs\pre-commit\lib\site-packages\pre_commit\repository.py", line 200, in install_hook_envs
    _hook_install(hook)
  File "c:\users\<my username>\.local\pipx\venvs\pre-commit\lib\site-packages\pre_commit\repository.py", line 82, in _hook_install
    lang.install_environment(
  File "c:\users\<my username>\.local\pipx\venvs\pre-commit\lib\site-packages\pre_commit\languages\python.py", line 194, in install_environment
    _make_venv(env_dir, python)
  File "c:\users\<my username>\.local\pipx\venvs\pre-commit\lib\site-packages\pre_commit\languages\python.py", line 206, in make_venv
    cmd_output_b(*cmd, env=env, cwd='/')
  File "c:\users\<my username>\.local\pipx\venvs\pre-commit\lib\site-packages\pre_commit\util.py", line 156, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('c:\\users\\<my username>\\.local\\pipx\\venvs\\pre-commit\\scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\<my username>\\.cache\\pre-commit\\repownrpu7d5\\py_env-python2', '-p', 'C:\\python2\\python.exe')
return code: 1
expected return code: 0
stdout:
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\python2\\python.exe'
    
stderr: (none)

\```
</details>

I'm trying to run the commit hooks for `pytest-timeout`. I'm not sure why it's insisting on trying to find Python2, but I suspect it has to do with the fact I've install the `pre-commit` packages with `pipx`.

**Comment by asottile** [comment]
that configuration [for whatever reason specifices python2 here](https://github.com/pytest-dev/pytest-timeout/blob/aafe48740344aec3ee246876db37ffea208ac929/.pre-commit-config.yaml#L33)

pre-commit couldn't detect any version of python2 and so it attempted it's final fallback which is `C:\pythonXX\python.exe`

You can probably fix it by installing python2 on your machine, or adjusting their configuration to not reference python2

**Comment by Mattwmaster58** [comment]
Out of the initial scope of this issue, but is there any reason a more informative warning couldn't be printed? Eg precommit hook x requires python x.x, but it could not be found

**Comment by asottile** [comment]
pre-commit passes the value of `language_version` along to the underlying tool (in this case `virtualenv`) so that's where the error message is coming from

**Comment by asottile** [comment]
your original output (doesn't appear to be in the issue) has `[INFO] installing environment for (repo name)` right before the error fwiw
