### ISSUE TITLE
On a win7 system, performing a pre-commit reports RPC failed error

### ISSUE THREAD

**Issue by xiaohuazi123** [pre-commit/pre-commit#1430]
Hi All,
I have another problem, when I commit, the pre-commit prints out the error, this error seems not to be my own code problem, it seems to be a pre-commit problem

The problem environment
Windows 7
Python version: Python 3.7.6

Here's the detail log
```
[INFO] Initializing environment for https://github.com/timothycrosley/isort.
An unexpected error has occurred: CalledProcessError: command: ('C:\\Program Files\\Git\\mingw64\\libexec\\git-core\\git.EXE', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: early EOF
    fatal: the remote end hung up unexpectedly
    fatal: index-pack failed
    error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
    
Check the log at C:\Users\Administrator/.cache\pre-commit\pre-commit.log
```

### version information

```
pre-commit version: 2.3.0
sys.version:
    3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
sys.executable: c:\program files\python37\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Program Files\\Git\\mingw64\\libexec\\git-core\\git.EXE', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: early EOF
    fatal: the remote end hung up unexpectedly
    fatal: index-pack failed
    error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
    
```

```
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\pre_commit\store.py", line 178, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "c:\program files\python37\lib\site-packages\pre_commit\store.py", line 160, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "c:\program files\python37\lib\site-packages\pre_commit\store.py", line 175, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "c:\program files\python37\lib\site-packages\pre_commit\util.py", line 156, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Program Files\\Git\\mingw64\\libexec\\git-core\\git.EXE', '-c', 'protocol.version=2', 'fetch', 'origin', 'stable', '--depth=1')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: couldn't find remote ref stable
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\pre_commit\error_handler.py", line 56, in error_handler
    yield
  File "c:\program files\python37\lib\site-packages\pre_commit\main.py", line 372, in main
    args=args.rest[1:],
  File "c:\program files\python37\lib\site-packages\pre_commit\commands\hook_impl.py", line 216, in hook_impl
    return retv | run(config, store, ns)
  File "c:\program files\python37\lib\site-packages\pre_commit\commands\run.py", line 350, in run
    for hook in all_hooks(config, store)
  File "c:\program files\python37\lib\site-packages\pre_commit\repository.py", line 206, in all_hooks
    for repo in root_config['repos']
  File "c:\program files\python37\lib\site-packages\pre_commit\repository.py", line 207, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "c:\program files\python37\lib\site-packages\pre_commit\repository.py", line 182, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "c:\program files\python37\lib\site-packages\pre_commit\repository.py", line 148, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "c:\program files\python37\lib\site-packages\pre_commit\store.py", line 182, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "c:\program files\python37\lib\site-packages\pre_commit\store.py", line 139, in _new_repo
    make_strategy(directory)
  File "c:\program files\python37\lib\site-packages\pre_commit\store.py", line 180, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "c:\program files\python37\lib\site-packages\pre_commit\store.py", line 152, in _complete_clone
    git_cmd('fetch', 'origin', '--tags')
  File "c:\program files\python37\lib\site-packages\pre_commit\store.py", line 175, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "c:\program files\python37\lib\site-packages\pre_commit\util.py", line 156, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Program Files\\Git\\mingw64\\libexec\\git-core\\git.EXE', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: early EOF
    fatal: the remote end hung up unexpectedly
    fatal: index-pack failed
    error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
    

```

pre-commit file content as following:

```


#!/usr/bin/env python.exe
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
import os
import sys
from isort.hooks import git_hook

# we try our best, but the shebang of this script is difficult to determine:
# - macos doesn't ship with python3
# - windows executables are almost always `python.exe`
# therefore we continue to support python2 for this small script
if sys.version_info < (3, 3):
    from distutils.spawn import find_executable as which
else:
    from shutil import which

# work around https://github.com/Homebrew/homebrew-core/issues/30445
os.environ.pop('__PYVENV_LAUNCHER__', None)

# start templated
INSTALL_PYTHON = 'c:\\program files\\python37\\python.exe'
ARGS = ['hook-impl', '--config=.pre-commit-config.yaml', '--hook-type=pre-commit']
# end templated
ARGS.extend(('--hook-dir', os.path.realpath(os.path.dirname(__file__))))
ARGS.append('--')
ARGS.extend(sys.argv[1:])

DNE = '`pre-commit` not found.  Did you forget to activate your virtualenv?'
if os.access(INSTALL_PYTHON, os.X_OK):
    CMD = [INSTALL_PYTHON, '-mpre_commit']
elif which('pre-commit'):
    CMD = ['pre-commit']
else:
    raise SystemExit(DNE)

CMD.extend(ARGS)
if sys.platform == 'win32':  # https://bugs.python.org/issue19124
    import subprocess

    if sys.version_info < (3, 7):  # https://bugs.python.org/issue25942
        raise SystemExit(subprocess.Popen(CMD).wait())
    else:
        raise SystemExit(subprocess.call(CMD))
else:
    os.execvp(CMD[0], CMD)



sys.exit(git_hook(strict=True, modify=True))

```

.pre-commit-config.yaml  content as  following:
```

repos:
  - repo: https://github.com/timothycrosley/isort
    rev: stable
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        entry:  isort
        language: python
  - repo: https://github.com/psf/black
    rev: stable  
    hooks:
      - id: black
        language_version: python3.7
```

**What should I do next? I need help. Thank you.**

**Comment by asottile** [comment]
I don't see a `stable` branch/tag in `isort` -- the error looks like protocol v1 is broken on your computer though, this will probably show the same error (without pre-commit)

```bash
git init x
cd x
git remote add origin https://github.com/timothycrosley/isort
git fetch origin --tags
```

**Comment by asottile** [comment]
an aside, using a mutable ref like `stable` / `master` / `HEAD` / etc. is [not supported](https://pre-commit.com/#using-the-latest-version-for-a-repository)

**Comment by xiaohuazi123** [comment]
> an aside, using a mutable ref like `stable` / `master` / `HEAD` / etc. is [not supported](https://pre-commit.com/#using-the-latest-version-for-a-repository)
First of all, thank you for your reply.

Sorry, I have solved this problem, it is a network problem, but now I have another problem, because I used  [black](https://github.com/psf/black )  format code, git failed to commit when I committed the code, it seems that black and isort conflict

What should I do next?

Here's the detail log
```
	
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing E:\shell-scripts\tt.py

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted tt.py
All done! \u2728 \U0001f370 \u2728
1 file reformatted.



git 未能顺利结束 (退出码 1) (1513 ms @ 2020/5/4 11:11:53)


```

Here is the content of .pre-commit-config.yaml file
```
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: develop
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        entry:  isort
        language: python
  - repo: https://github.com/psf/black
    rev: stable  
    hooks:
      - id: black
        language_version: python3.7

```

pre-commit file content as following:
```  
#!/usr/bin/env python.exe
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
import os
import sys
from isort.hooks import git_hook



# we try our best, but the shebang of this script is difficult to determine:
# - macos doesn't ship with python3
# - windows executables are almost always `python.exe`
# therefore we continue to support python2 for this small script
if sys.version_info < (3, 3):
    from distutils.spawn import find_executable as which
else:
    from shutil import which

# work around https://github.com/Homebrew/homebrew-core/issues/30445
os.environ.pop('__PYVENV_LAUNCHER__', None)

# start templated
INSTALL_PYTHON = 'c:\\program files\\python37\\python.exe'
ARGS = ['hook-impl', '--config=.pre-commit-config.yaml', '--hook-type=pre-commit']
# end templated
ARGS.extend(('--hook-dir', os.path.realpath(os.path.dirname(__file__))))
ARGS.append('--')
ARGS.extend(sys.argv[1:])

DNE = '`pre-commit` not found.  Did you forget to activate your virtualenv?'
if os.access(INSTALL_PYTHON, os.X_OK):
    CMD = [INSTALL_PYTHON, '-mpre_commit']
elif which('pre-commit'):
    CMD = ['pre-commit']
else:
    raise SystemExit(DNE)

CMD.extend(ARGS)
if sys.platform == 'win32':  # https://bugs.python.org/issue19124
    import subprocess

    if sys.version_info < (3, 7):  # https://bugs.python.org/issue25942
        raise SystemExit(subprocess.Popen(CMD).wait())
    else:
        raise SystemExit(subprocess.call(CMD))
else:
    os.execvp(CMD[0], CMD)


sys.exit(git_hook(strict=True, modify=True))

```

**Comment by asottile** [comment]
there's instructions in both the `black` and `isort` READMEs about how to make a compatible configuration for both tools 👍 

since there isn't a pre-commit issue here, I'm going to close this -- thanks again for the thorough report!

**Comment by xiaohuazi123** [comment]
Thank you again.
