### ISSUE TITLE
Error creating pip environment when index requires a login

### ISSUE THREAD

**Issue by sodre** [pre-commit/pre-commit#1454]
I am having a problem creating a pre-commit virtual environment when running behind a proxying/private pypi repository that requires a login.
I have setup my pip.conf file to point to that index, and I am using `keyring` to manage my passwords, so it is not stored in plain-text.

To reproduce on my system:

```
$ pip install pre-commit
# no passwords are prompted
```

Create a very simple `.pre-commit-config.yaml` file, with "psf/black"
```
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
```

Try to initialize the `pre-commit` virtual environments...
<details>

```
± pre-commit
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Looking in indexes: https://<NEXUS PRIVATE REPOSITORY>/repository/pypi-all/simple
    Processing /home/pcarlos/.cache/pre-commit/repodmjniiuo
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
    User for <NEXUS PRIVATE REPOSITORY>: 
stderr:
      ERROR: Command errored out with exit status 2:
       command: /home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/bin/python /home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-oget82ct/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://<NEXUS PRIVATE REPOSITORY>/repository/pypi-all/simple -- 'setuptools>=41.0' setuptools-scm wheel
           cwd: None
      Complete output (48 lines):
      Looking in indexes: https://<NEXUS PRIVATE REPOSITORY>/repository/pypi-all/simple
      Collecting setuptools>=41.0
      User for <NEXUS PRIVATE REPOSITORY>: ERROR: Exception:
```
</details>

Traceback:
<details>

```python-traceback
      Traceback (most recent call last):
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in main
          status = self.run(options, args)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 345, in run
          resolver.resolve(requirement_set)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
          self._resolve_one(requirement_set, req)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
          abstract_dist = self._get_abstract_dist_for(req_to_install)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 305, in _get_abstract_dist_for
          abstract_dist = self.preparer.prepare_linked_requirement(
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 134, in prepare_linked_requirement
          req.populate_link(finder, upgrade_allowed, require_hashes)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 211, in populate_link
          self.link = finder.find_requirement(self, upgrade)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/index.py", line 1200, in find_requirement
          candidates = self.find_candidates(
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/index.py", line 1183, in find_candidates
          candidates = self.find_all_candidates(project_name)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/index.py", line 1128, in find_all_candidates
          for page in self._get_pages(url_locations, project_name):
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/index.py", line 1282, in _get_pages
          page = _get_html_page(location, session=self.session)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/index.py", line 234, in _get_html_page
          resp = _get_html_response(url, session=session)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/index.py", line 165, in _get_html_response
          resp = session.get(
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 546, in get
          return self.request('GET', url, **kwargs)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/download.py", line 624, in request
          return super(PipSession, self).request(method, url, *args, **kwargs)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 533, in request
          resp = self.send(prep, **send_kwargs)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 653, in send
          r = dispatch_hook('response', hooks, r, **kwargs)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_vendor/requests/hooks.py", line 31, in dispatch_hook
          _hook_data = hook(hook_data, **kwargs)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/download.py", line 386, in handle_401
          username, password, save = self._prompt_for_password(parsed.netloc)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/download.py", line 358, in _prompt_for_password
          username = ask_input("User for %s: " % netloc)
        File "/home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 281, in ask_input
          return input(message)
      EOFError: EOF when reading a line
      User for <NEXUS PRIVATE REPOSITORY>:
      ----------------------------------------
    ERROR: Command errored out with exit status 2: /home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/bin/python /home/pcarlos/.cache/pre-commit/repodmjniiuo/py_env-python3/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-oget82ct/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://<NEXUS PRIVATE REPOSITORY>/repository/pypi-all/simple -- 'setuptools>=41.0' setuptools-scm wheel Check the logs for full command output.
    
Check the log at /home/pcarlos/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
installation is entirely non-interactive, so you'll have to configure your keyring in such a way that that works

there's nothing particularly special about the installation beyond `cd / && pip install` (the `cd /` is done to avoid `setup.cfg` / `distutils.cfg` of the current project polluting the installation area).

from the traceback it looks like pip is not using your keyring at all, but is attempting to read the passwords from stdin?

**Comment by sodre** [comment]
I have configured keyring so my installs are non-interactive, e.g. I can "pip install pre-commit", and it will pull the package from our private registry.

Maybe the second "pip" install is running from the virtualenv, and that environment does not have keyring installed. Does that make sense?

**Comment by asottile** [comment]
ah ok so this would fail for you then:
```
virtualenv py_venv
py_env/bin/pip install astpretty
```

**Comment by asottile** [comment]
actually, if that fails, how does this work?

```bash
rm -rf py_env
virtualenv py_env
py_env/bin/pip install keyring
```

**Comment by sodre** [comment]
Both failed for me. 

This seems to be a virtualenv issue then. It should have a way to pre-install keyring when it first creates the environment.

**Comment by asottile** [comment]
yeah makes sense -- I think @gaborbernat was working on option to have "bootstrap" packages

**Comment by gaborbernat** [comment]
There's no plan for bootstrap any more. I'd recommend doing a pip install no deps on the wheel of the keyring 🤷‍♂️ or symlink the packages across pythons... But they might version control.

**Comment by sodre** [comment]
@gaborbernat, thanks! 

I did some additional digging and it seems that `virtualenv` bypasses the `index-url` if it depends on `keyring` for its login and uses the embedded `.whl` files instead. 

I will do some digging on the plugin mechanism for virtualenv.

Should we open a ticket directly against virtualenv?

**Comment by sodre** [comment]
Documenting this in case someone comes across the same issue...

If the end-user is willing to store a password(or token) to disk, then the `~/.netrc`-solution described in the StackOverflow post [Credentials in pip.conf for private PyPi](https://stackoverflow.com/questions/50468951/credentials-in-pip-conf-for-private-pypi/55978589#55978589) works. 

@asottile, I think it makes sense to close this issue. First, it is really a missing feature of `virtualenv`. Second, creating a separate user and token just for connecting to the repository was an acceptable risk on my side.

**Comment by asottile** [comment]
sounds good -- thanks for the issue!

**Comment by sbor23** [comment]
Just hit this as well. IMO this issue is not solved, `.netrc` should be seen as an insecure workaround. You cannot roll this out across an organization...
The problem here is not (only) that there is no keyring in the virtualenv, but that pre-commit has no way to "pass through" the stdin prompt from pip.

Note that is the same issue as `pip` has with it's PEP517 isolated builds. Running `pip` in a subprocess will not work like that.
https://github.com/pypa/pip/issues/10665

A similar issue is also in `build` https://github.com/pypa/build/issues/409

The python / pip-based packaging ecosystem is really frustrating sometimes...

**Comment by sbor23** [comment]
Is there an option to ignore the pip.conf index settings, e.g passing `--no-index` to the pip subprocess? That would be an alternative workaround, given that no pre-commit hooks are pulled from this index.
