### ISSUE TITLE
An unexpected error has occurred: CalledProcessError: Command: ['bash', '-c', ". '/Users/dfd/.pre-commit/repodyEcO7/py_env-default/bin/activate' && cd '/Users/dfd/.pre-commit/repodyEcO7/' && pip install ."] Return code: 2 Expected return code: 0

### ISSUE THREAD

**Issue by kunal5** [pre-commit/pre-commit#1558]
I am getting this error. 
<img width="1440" alt="Screenshot 2020-08-10 at 7 50 00 PM" src="https://user-images.githubusercontent.com/15965156/89795734-5f393600-db46-11ea-8999-8f3d00ea9d48.png">

I have tried making a new fresh environment but still the error persists. Please help

**Comment by asottile** [comment]
pre-commit hasn't used bash internally for a very very long time

I suspect you've either modified the source or you're using an ancient version of pre-commit.

Either way you haven't provided enough information, please at least provide the version you're using and the error log that pre-commit produces

**Comment by kunal5** [comment]
pre-commit version is 0.5.5
`Errors: 
    Exception:
    Traceback (most recent call last):
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
        status = self.run(options, args)
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
        root=options.root_path,
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
        **kwargs
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
        self.move_wheel_files(self.source_dir, root=root)
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
        isolated=self.isolated,
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/wheel.py", line 341, in move_wheel_files
        assert info_dir, "%s .dist-info directory not found" % req
    AssertionError: configparser .dist-info directory not found
    You are using pip version 7.1.2, however version 20.2.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
`
this is the error log

**Comment by asottile** [comment]
lol 0.5.5 was released on 2015-09-04

**Comment by asottile** [comment]
that's not actually the error log by the way, pre-commit should tell you about a file which contains the actual error log

**Comment by kunal5** [comment]
I have copied the error from the log file and pasted here

**Comment by asottile** [comment]
yeah that's markedly not helpful -- paste **the entire log**

if you don't know what's wrong, cherry-picking a small part of an error log is not going to help someone else understand your problem

**Comment by kunal5** [comment]
An unexpected error has occurred: CalledProcessError: Command: ['bash', '-c', ". '/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/bin/activate' && cd '/Users/kunal/.pre-commit/repoPg4f7o/' && pip install ."]
Return code: 2
Expected return code: 0
Output: 
    Processing /Users/kunal/.pre-commit/repoPg4f7o
    Collecting flake8 (from pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/6c/20/6326a9a0c6f0527612bae748c4c03df5cd69cf06dfb2cf59d85c6e165a6a/flake8-3.8.3-py2.py3-none-any.whl
    Collecting argparse (from pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
    Collecting autopep8>=1.1 (from pre-commit-hooks==0.4.2)
    Collecting pyyaml (from pre-commit-hooks==0.4.2)
    Collecting simplejson (from pre-commit-hooks==0.4.2)
    Collecting six (from pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
    Collecting enum34 (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
    Collecting pycodestyle<2.7.0,>=2.6.0a1 (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/10/5b/88879fb861ab79aef45c7e199cae3ef7af487b5603dcb363517a50602dd7/pycodestyle-2.6.0-py2.py3-none-any.whl
    Collecting typing (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/3b/c0/e44213fcb799eac02881e2485724ba5b0914600bc9df6ed922e364fdc059/typing-3.7.4.3-py2-none-any.whl
    Collecting pyflakes<2.3.0,>=2.2.0 (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/69/5b/fd01b0c696f2f9a6d2c839883b642493b431f28fa32b29abc465ef675473/pyflakes-2.2.0-py2.py3-none-any.whl
    Collecting configparser (from flake8->pre-commit-hooks==0.4.2)
    Collecting mccabe<0.7.0,>=0.6.0 (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
    Collecting functools32 (from flake8->pre-commit-hooks==0.4.2)
    Collecting importlib-metadata (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/8e/58/cdea07eb51fc2b906db0968a94700866fc46249bdc75cac23f9d13168929/importlib_metadata-1.7.0-py2.py3-none-any.whl
    Collecting toml (from autopep8>=1.1->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/9f/e1/1b40b80f2e1663a6b9f497123c11d7d988c0919abbf3c3f2688e448c5363/toml-0.10.1-py2.py3-none-any.whl
    Collecting zipp>=0.5 (from importlib-metadata->flake8->pre-commit-hooks==0.4.2)
    Collecting contextlib2 (from importlib-metadata->flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/85/60/370352f7ef6aa96c52fb001831622f50f923c1d575427d021b8ab3311236/contextlib2-0.6.0.post1-py2.py3-none-any.whl
    Collecting pathlib2 (from importlib-metadata->flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/e9/45/9c82d3666af4ef9f221cbb954e1d77ddbb513faf552aea6df5f37f1a4859/pathlib2-2.3.5-py2.py3-none-any.whl
    Collecting scandir (from pathlib2->importlib-metadata->flake8->pre-commit-hooks==0.4.2)
    Installing collected packages: enum34, pycodestyle, typing, pyflakes, configparser, mccabe, functools32, zipp, contextlib2, six, scandir, pathlib2, importlib-metadata, flake8, argparse, toml, autopep8, pyyaml, simplejson, pre-commit-hooks
    
Errors: 
    Exception:
    Traceback (most recent call last):
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
        status = self.run(options, args)
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
        root=options.root_path,
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
        **kwargs
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
        self.move_wheel_files(self.source_dir, root=root)
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
        isolated=self.isolated,
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/wheel.py", line 341, in move_wheel_files
        assert info_dir, "%s .dist-info directory not found" % req
    AssertionError: configparser .dist-info directory not found
    You are using pip version 7.1.2, however version 20.2.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    

Traceback (most recent call last):
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/error_handler.py", line 34, in error_handler
    yield
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/main.py", line 144, in main
    return run(runner, args)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/commands/run.py", line 177, in run
    repo_hooks = list(get_repo_hooks(runner))
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/commands/run.py", line 123, in get_repo_hooks
    for repo in runner.repositories:
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/runner.py", line 43, in repositories
    repository.require_installed()
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/repository.py", line 72, in require_installed
    self.install()
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/repository.py", line 110, in install
    language.install_environment(self.cmd_runner, language_version)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/languages/python.py", line 59, in install_environment
    env.run("cd '{prefix}' && pip install .")
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/languages/helpers.py", line 51, in run
    ['bash', '-c', ' '.join([self.env_prefix, cmd])], **kwargs
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/prefixed_command_runner.py", line 41, in run
    return cmd_output(*replaced_cmd, __popen=self.__popen, **kwargs)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/util.py", line 160, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
CalledProcessError: Command: ['bash', '-c', ". '/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/bin/activate' && cd '/Users/kunal/.pre-commit/repoPg4f7o/' && pip install ."]
Return code: 2
Expected return code: 0
Output: 
    Processing /Users/kunal/.pre-commit/repoPg4f7o
    Collecting flake8 (from pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/6c/20/6326a9a0c6f0527612bae748c4c03df5cd69cf06dfb2cf59d85c6e165a6a/flake8-3.8.3-py2.py3-none-any.whl
    Collecting argparse (from pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
    Collecting autopep8>=1.1 (from pre-commit-hooks==0.4.2)
    Collecting pyyaml (from pre-commit-hooks==0.4.2)
    Collecting simplejson (from pre-commit-hooks==0.4.2)
    Collecting six (from pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
    Collecting enum34 (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
    Collecting pycodestyle<2.7.0,>=2.6.0a1 (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/10/5b/88879fb861ab79aef45c7e199cae3ef7af487b5603dcb363517a50602dd7/pycodestyle-2.6.0-py2.py3-none-any.whl
    Collecting typing (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/3b/c0/e44213fcb799eac02881e2485724ba5b0914600bc9df6ed922e364fdc059/typing-3.7.4.3-py2-none-any.whl
    Collecting pyflakes<2.3.0,>=2.2.0 (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/69/5b/fd01b0c696f2f9a6d2c839883b642493b431f28fa32b29abc465ef675473/pyflakes-2.2.0-py2.py3-none-any.whl
    Collecting configparser (from flake8->pre-commit-hooks==0.4.2)
    Collecting mccabe<0.7.0,>=0.6.0 (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
    Collecting functools32 (from flake8->pre-commit-hooks==0.4.2)
    Collecting importlib-metadata (from flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/8e/58/cdea07eb51fc2b906db0968a94700866fc46249bdc75cac23f9d13168929/importlib_metadata-1.7.0-py2.py3-none-any.whl
    Collecting toml (from autopep8>=1.1->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/9f/e1/1b40b80f2e1663a6b9f497123c11d7d988c0919abbf3c3f2688e448c5363/toml-0.10.1-py2.py3-none-any.whl
    Collecting zipp>=0.5 (from importlib-metadata->flake8->pre-commit-hooks==0.4.2)
    Collecting contextlib2 (from importlib-metadata->flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/85/60/370352f7ef6aa96c52fb001831622f50f923c1d575427d021b8ab3311236/contextlib2-0.6.0.post1-py2.py3-none-any.whl
    Collecting pathlib2 (from importlib-metadata->flake8->pre-commit-hooks==0.4.2)
      Using cached https://files.pythonhosted.org/packages/e9/45/9c82d3666af4ef9f221cbb954e1d77ddbb513faf552aea6df5f37f1a4859/pathlib2-2.3.5-py2.py3-none-any.whl
    Collecting scandir (from pathlib2->importlib-metadata->flake8->pre-commit-hooks==0.4.2)
    Installing collected packages: enum34, pycodestyle, typing, pyflakes, configparser, mccabe, functools32, zipp, contextlib2, six, scandir, pathlib2, importlib-metadata, flake8, argparse, toml, autopep8, pyyaml, simplejson, pre-commit-hooks
    
Errors: 
    Exception:
    Traceback (most recent call last):
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
        status = self.run(options, args)
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
        root=options.root_path,
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
        **kwargs
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
        self.move_wheel_files(self.source_dir, root=root)
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
        isolated=self.isolated,
      File "/Users/kunal/.pre-commit/repoPg4f7o/py_env-default/lib/python2.7/site-packages/pip/wheel.py", line 341, in move_wheel_files
        assert info_dir, "%s .dist-info directory not found" % req
    AssertionError: configparser .dist-info directory not found
    You are using pip version 7.1.2, however version 20.2.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by kunal5** [comment]
this is the whole stack trace

**Comment by kunal5** [comment]
also my pre-commit-config.yaml file is 

-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 616c1ebd1898c91de9a0548866a59cbd9f4547f6
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args: ['--config=.flake8']
-   repo: git@github.com:pre-commit/mirrors-jshint
    sha: e86225836aadd058036f47a6de9b0ee0440476eb
    hooks:
    -   id: jshint
        language_version: 4.2.1
        entry: jshint myapp/static/js/app/*
        args:
        - --exclude-path=myapp/static/js/app/.jshintignore
        exclude: myapp/static/js/libs/*
-   repo: git@github.com:MyApp/mirrors-jscs
    sha: 95925b07080773eb2c323f5597adbae31277aea3
    hooks:
    -   id: jscs
        language_version: 4.2.1
        entry: jscs myapp/static/js/app/
        exclude: myapp/static/js/libs/*
-   repo: local
    hooks:
    -   id: myapp_linter
        entry: ./shell_scripts/myapp_linter.sh
        name: myapp_linter
        language: script
        files: ''

**Comment by asottile** [comment]
oh, if it wasn't clear the problem is likely fixed in the five years of development since the ancient version you're using and you need to upgrade

**Comment by kunal5** [comment]
@asottile now I am using the current version of pre-commit, but this time I am getting this error```


### version information

```
pre-commit version: 1.21.0
sys.version:
    2.7.16 (default, Nov  9 2019, 05:55:08)
    [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
sys.executable: /Users/kunal/Desktop/environments/squadrun/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An error has occurred: InvalidManifestError:
=====> /Users/kunal/.cache/pre-commit/repoBnu8qF/.pre-commit-hooks.yaml does not exist
```

```
Traceback (most recent call last):
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/error_handler.py", line 72, in error_handler
    yield
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/main.py", line 344, in main
    return run(args.config, store, args)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/commands/run.py", line 279, in run
    for hook in all_hooks(config, store)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/repository.py", line 226, in all_hooks
    for repo in root_config['repos']
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/repository.py", line 227, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/repository.py", line 202, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/repository.py", line 172, in _cloned_repository_hooks
    by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/cfgv.py", line 424, in load_from_filename
    return apply_defaults(data, schema)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/cfgv.py", line 49, in reraise_as
    six.reraise(tp, tp(e), tb)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/cfgv.py", line 46, in reraise_as
    yield
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/cfgv.py", line 412, in load_from_filename
    raise ValidationError('{} does not exist'.format(filename))
InvalidManifestError:
=====> /Users/kunal/.cache/pre-commit/repoBnu8qF/.pre-commit-hooks.yaml does not exist
```

**Comment by asottile** [comment]
now your config is old, use pre-commit autoupdate

**Comment by kunal5** [comment]
But now the problem is the current version of pre-commit is not compatible with python2.7. How can I use it for python2.7. Here is the stack trace

### version information

```
pre-commit version: 1.21.0
sys.version:
    2.7.16 (default, Nov  9 2019, 05:55:08)
    [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
sys.executable: /Users/kunal/Desktop/environments/squadrun/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/kunal/.cache/pre-commit/repo9qog2Y/py_env-python2.7/bin/python', u'/Users/kunal/.cache/pre-commit/repo9qog2Y/py_env-python2.7/bin/pip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /Users/kunal/.cache/pre-commit/repo9qog2Y

stderr:
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    ERROR: Package 'pre-commit-hooks' requires a different Python: 2.7.16 not in '>=3.6.1'

```

```
Traceback (most recent call last):
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/error_handler.py", line 72, in error_handler
    yield
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/main.py", line 344, in main
    return run(args.config, store, args)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/commands/run.py", line 292, in run
    install_hook_envs(hooks, store)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/repository.py", line 220, in install_hook_envs
    hook.install()
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/repository.py", line 98, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/languages/python.py", line 172, in install_environment
    prefix, ('pip', 'install', '.') + additional_dependencies,
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/languages/helpers.py", line 17, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir)
  File "/Users/kunal/Desktop/environments/squadrun/lib/python2.7/site-packages/pre_commit/util.py", line 141, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
CalledProcessError: command: ('/Users/kunal/.cache/pre-commit/repo9qog2Y/py_env-python2.7/bin/python', u'/Users/kunal/.cache/pre-commit/repo9qog2Y/py_env-python2.7/bin/pip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /Users/kunal/.cache/pre-commit/repo9qog2Y

stderr:
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    ERROR: Package 'pre-commit-hooks' requires a different Python: 2.7.16 not in '>=3.6.1'


```

**Comment by asottile** [comment]
pick a version that's less that 3.0.0

**Comment by kunal5** [comment]
It worked finally. Thanks alot ! @asottile

**Comment by ShubhamMittal98** [comment]
@kunal5 Did you set up a python version < 3.0.0 using pyenv?
