### ISSUE TITLE
Migration mode does not work on Windows if legacy script starts with `#!/bin/sh`

### ISSUE THREAD

**Issue by MaratFM** [pre-commit/pre-commit#1588]
**Repro steps:**
1. Create a git repo on windows, install git-lfs. It will add pre-push hook with this content:
```
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
```

2. Install pre-commit and call `pre-commit install -t pre-push`
It will rename `pre-push` to `pre-push.legacy`, command output:
```
pre-commit installed at .git\hooks\pre-commit
Running in migration mode with existing hooks at .git\hooks\pre-push.legacy
Use -f to use only pre-commit.
pre-commit installed at .git\hooks\pre-push
```

3. Try pushing with `git push`
It will fail with:
```
An unexpected error has occurred: ExecutableNotFoundError: Executable `/bin/sh` not found
Check the log at C:\Users\<username>\.cache\pre-commit\pre-commit.log
error: failed to push some refs to <repo url>
```

**Expected:** git push will work and will successfully call legacy git-lfs hook

**Actual:** git push fails

-----------------------------------------------------------

Log file content:

### version information

```
pre-commit version: 2.7.1
sys.version:
    3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
sys.executable: d:\envs\polymer\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: ExecutableNotFoundError: Executable `/bin/sh` not found
```

```
Traceback (most recent call last):
  File "d:\envs\polymer\lib\site-packages\pre_commit\error_handler.py", line 63, in error_handler
    yield
  File "d:\envs\polymer\lib\site-packages\pre_commit\main.py", line 369, in main
    args=args.rest[1:],
  File "d:\envs\polymer\lib\site-packages\pre_commit\commands\hook_impl.py", line 211, in hook_impl
    retv, stdin = _run_legacy(hook_type, hook_dir, args)
  File "d:\envs\polymer\lib\site-packages\pre_commit\commands\hook_impl.py", line 42, in _run_legacy
    cmd = normalize_cmd((legacy_hook, *args))
  File "d:\envs\polymer\lib\site-packages\pre_commit\parse_shebang.py", line 82, in normalize_cmd
    exe = normexe(cmd[0])
  File "d:\envs\polymer\lib\site-packages\pre_commit\parse_shebang.py", line 61, in normexe
    _error('not found')
  File "d:\envs\polymer\lib\site-packages\pre_commit\parse_shebang.py", line 51, in _error
    raise ExecutableNotFoundError(f'Executable `{orig}` {msg}')
pre_commit.parse_shebang.ExecutableNotFoundError: Executable `/bin/sh` not found

```

**Comment by asottile** [comment]
use `/usr/bin/env sh`

`/bin/sh` is not portable

**Comment by MaratFM** [comment]
@asottile thank you, it worked!

Maybe git-lfs should use it by default.

**Comment by carlosmdelc** [comment]
@asottile when you say use /usr/bin/env sh where should we use it? I have the same issue but don't know where exactly to use. Thanks in advance. I'm using ggshield for pre-commit.

**Comment by asottile** [comment]
whatever script you're calling should be using that as a shebang

**Comment by carlosmdelc** [comment]
Looks like running the pre-commit autoupdate and update with the path you mentioned at .git>hooks>pre-commit.legacy fixed. Thanks.

**Comment by kmgamboa-mdsol** [comment]
Hi @carlosmdelc I will ask you the same question you asked before, where is this path located? I can not find .git>hooks>pre-commit.legacy

**Comment by kmgamboa-mdsol** [comment]
Never mind, the folder was hidden ... all good .. thanks
