### ISSUE TITLE
Error in setting up prettier hook

### ISSUE THREAD

**Issue by oshiiii** [pre-commit/pre-commit#1631]
# Error while installing environment for prettier, `pre-commit run --all` results into error.

After `pre-commit install`
`sudo -H pre-commit run --all` produces error while installing prettier environment. The following happens

![Screenshot 2020-10-04 at 14 33 43](https://user-images.githubusercontent.com/72258338/95453693-f07f2a00-0988-11eb-8f17-34f9136c7cfa.png)

I am on MacOS 10.15 Catalina
NodeJS v14.11.0
npm v6.14.8
pre-commit v2.7.1

## The contents of my `.pre-commit-config.yaml `

> repos:
>  - repo: https://gitlab.com/pycqa/flake8
>    rev: 3.7.9
>    hooks:
>      - id: flake8
>  - repo: https://github.com/prettier/prettier
>    rev: 1.19.1
>    hooks:
>      - id: prettier
>  - repo: https://github.com/psf/black
>    rev: 20.8b1
>    hooks:
>      - id: black
>        language_version: python3.8

I have tried clearing npm cache, and even reinstalling node, but nothing works. Both `node` and `pre-commit` are installed via `Homebrew`.

**Please help me resolve this as I couldn't find anything on the internet.**

P. S. In the screenshot it shows that `/usr/bin/git ls-remote -h -t ssh://git@github.com/ikatyang/parse-srcset.git` is producing an error but the command runs just as fine when I run it in terminal. And gives the following output

```
54eb9c1cb21db5c62b4d0e275d7249516df6f0ee	refs/heads/feat/report-error
03104fe7a2cdfd898e3717fef402fce528740370	refs/heads/master
c9aa6c9b2743dba0ad4bf0268e8bf547600a26ac	refs/tags/v1.0.1
d39290d2f6f8acfe2485710446317425d3ee9cf8	refs/tags/v1.0.1^{}
e0d646b04ca055c3f42eeffd597d0dfc2c0a0a67	refs/tags/v1.0.2
03104fe7a2cdfd898e3717fef402fce528740370	refs/tags/v1.0.2^{}

```

Below are the contents of my `/private/var/root/.cache/pre-commit/pre-commit.log`

### version information

```
pre-commit version: 2.7.1
sys.version:
    3.9.0 (default, Oct  6 2020, 04:17:54) 
    [Clang 12.0.0 (clang-1200.0.32.2)]
sys.executable: /usr/local/Cellar/pre-commit/2.7.1_1/libexec/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/private/var/root/.cache/pre-commit/repo2t6cav93/node_env-system/bin/node', '/usr/local/bin/npm', 'install')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
    npm WARN deprecated rollup-plugin-babel@4.3.3: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
    npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
    npm WARN deprecated rollup-plugin-json@4.0.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-json.
    npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
    npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
    npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
    npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
    npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
    npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
    npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npm WARN deprecated har-validator@5.1.5: this library is no longer supported
    npm ERR! Error while executing:
    npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/ikatyang/parse-srcset.git
    npm ERR! 
    npm ERR! fatal: Unable to read current working directory: Permission denied
    npm ERR! 
    npm ERR! exited with error code: 128
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /var/root/.npm/_logs/2020-10-08T11_45_40_833Z-debug.log
    
```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/2.7.1_1/libexec/lib/python3.9/site-packages/pre_commit/error_handler.py", line 63, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/2.7.1_1/libexec/lib/python3.9/site-packages/pre_commit/main.py", line 390, in main
    return run(args.config, store, args)
  File "/usr/local/Cellar/pre-commit/2.7.1_1/libexec/lib/python3.9/site-packages/pre_commit/commands/run.py", line 388, in run
    install_hook_envs(hooks, store)
  File "/usr/local/Cellar/pre-commit/2.7.1_1/libexec/lib/python3.9/site-packages/pre_commit/repository.py", line 206, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/Cellar/pre-commit/2.7.1_1/libexec/lib/python3.9/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/usr/local/Cellar/pre-commit/2.7.1_1/libexec/lib/python3.9/site-packages/pre_commit/languages/node.py", line 97, in install_environment
    helpers.run_setup_cmd(prefix, ('npm', 'install'))
  File "/usr/local/Cellar/pre-commit/2.7.1_1/libexec/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 25, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir)
  File "/usr/local/Cellar/pre-commit/2.7.1_1/libexec/lib/python3.9/site-packages/pre_commit/util.py", line 157, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/private/var/root/.cache/pre-commit/repo2t6cav93/node_env-system/bin/node', '/usr/local/bin/npm', 'install')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
    npm WARN deprecated rollup-plugin-babel@4.3.3: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
    npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
    npm WARN deprecated rollup-plugin-json@4.0.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-json.
    npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
    npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
    npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
    npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
    npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
    npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
    npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npm WARN deprecated har-validator@5.1.5: this library is no longer supported
    npm ERR! Error while executing:
    npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/ikatyang/parse-srcset.git
    npm ERR! 
    npm ERR! fatal: Unable to read current working directory: Permission denied
    npm ERR! 
    npm ERR! exited with error code: 128
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /var/root/.npm/_logs/2020-10-08T11_45_40_833Z-debug.log
    

```

**Comment by asottile** [comment]
there's so much wrong with what you're doing I don't know where to begin

- don't use `sudo` -- pre-commit is designed to run in user space and *not* need any system resources
- don't screenshot text in images -- it's text, we're programmers, it's inaccessible to hide text in images because the user cannot view it with their own accessibility options / contrast / font size / etc.
- when writing markdown, use fenced code blocks (you can even specify the optional language as I've done):

    ```markdown
        ```yaml
        like: this
        ```
    ```
- by running `sudo` (and especially with `-H`) you've almost certainly polluted your home directory with root owned objects
- `npm` doesn't like running as root and will change to another user
- it's probably changing to a user which doesn't exist and then trying to access root-owned temporary directories and erroring on permission denied

so I'd start by fixing all of those things and then try again.  Your configuration is fine and I'm able to run it on my machine as well as on my mac so it's something you're doing with the way you're running it.  As such, I'm closing this as invalid

**Comment by oshiiii** [comment]
Thank you @asottile I had to change the owner of `~/.caches/pre-commit/` to current user which for some weird reason was root so I got error running it without super user. I should have done this thing before running it with sudo, sorry my bad.

**Comment by asottile** [comment]
sudo should almost never be used **unless** you're managing system tools -- good rule of thumb in general
