### ISSUE TITLE
pre-commit failing with sample config (WSL1/Ubuntu20.4.1/Conda)

### ISSUE THREAD

**Issue by payoto** [pre-commit/pre-commit#1632]
Hello,
This is my first time setting `pre-commit` up and I got a module not found error when I try to commit.
I'm attaching as much detail as I can. Am I doing something silly or does this look like a bug?

Thanks a lot for the help.

I'm using:

* Windows subsystem for linux (WSL1)
*  Ubuntu 20.04.1 LTS
*  conda 4.8.5
* pre-commit 2.7.1

and ran:

     conda install -c conda-forge pre-commit
     pre-commit sample-config > .pre-commit-config.yaml
     pre-commit install
     git stage .pre-commit-config.yaml
     git commit -m "Add pre-commit to setup"

And got the following error :

```
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/payoto/anaconda3/envs/env_name/bin/python', '-mvirtualenv', '/home/payoto/.cache/pre-commit/repori8p5rmh/py_env-python3.8', '-p', '/home/payoto/anaconda3/envs/env_name/bin/python')
return code: 1
expected return code: 0
stdout:
ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'

stderr: (none)
Check the log at /home/payoto/.cache/pre-commit/pre-commit.log
```

### version information

```
pre-commit version: 2.7.1
sys.version:
    3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:55:52) 
    [GCC 7.5.0]
sys.executable: /home/payoto/anaconda3/envs/env_name/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/payoto/anaconda3/envs/env_name/bin/python', '-mvirtualenv', '/home/payoto/.cache/pre-commit/repohfj4i3ar/py_env-python3.8', '-p', '/home/payoto/anaconda3/envs/env_name/bin/python')
return code: 1
expected return code: 0
stdout:
    ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "/home/payoto/anaconda3/envs/env_name/lib/python3.8/site-packages/pre_commit/error_handler.py", line 63, in error_handler
    yield
  File "/home/payoto/anaconda3/envs/env_name/lib/python3.8/site-packages/pre_commit/main.py", line 362, in main
    return hook_impl(
  File "/home/payoto/anaconda3/envs/env_name/lib/python3.8/site-packages/pre_commit/commands/hook_impl.py", line 217, in hook_impl
    return retv | run(config, store, ns)
  File "/home/payoto/anaconda3/envs/env_name/lib/python3.8/site-packages/pre_commit/commands/run.py", line 388, in run
    install_hook_envs(hooks, store)
  File "/home/payoto/anaconda3/envs/env_name/lib/python3.8/site-packages/pre_commit/repository.py", line 206, in install_hook_envs
    _hook_install(hook)
  File "/home/payoto/anaconda3/envs/env_name/lib/python3.8/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/home/payoto/anaconda3/envs/env_name/lib/python3.8/site-packages/pre_commit/languages/python.py", line 213, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/home/payoto/anaconda3/envs/env_name/lib/python3.8/site-packages/pre_commit/util.py", line 157, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/payoto/anaconda3/envs/env_name/bin/python', '-mvirtualenv', '/home/payoto/.cache/pre-commit/repohfj4i3ar/py_env-python3.8', '-p', '/home/payoto/anaconda3/envs/env_name/bin/python')
return code: 1
expected return code: 0
stdout:
    ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
    
stderr: (none)

```

**Comment by asottile** [comment]
try `python -m virtualenv vvv` -- probably a bug with virtualenv and there's nothing we can do about it

**Comment by asottile** [comment]
you can report a bug on virtualenv [here](https://github.com/pypa/virtualenv)

**Comment by payoto** [comment]
Does seem that way I get the same error with that command:

    ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'

Thanks for the help.

**Comment by asottile** [comment]
cheers!  good luck with the upstream issue!

**Comment by MarcoGorelli** [comment]
> Does seem that way I get the same error with that command:
> 
> ```
> ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
> ```
> 
> Thanks for the help.

I ran into this too, the problem was that I had conflicting versions of virtualenv installed and I fixed this by uninstalling one of them

**Comment by payoto** [comment]
That is what it was, thanks for the tip.
