### ISSUE TITLE
Pre-commit fails looking for python 3.6 interpreter in python 3.7.8 venv 

### ISSUE THREAD

**Issue by anudeepsamaiya** [pre-commit/pre-commit#1646]
```


An unexpected error has occurred: CalledProcessError: 
Command: ('/Users/as/.pyenv/versions/3.7.8/envs/ctixs/bin/python3.7', '-mvirtualenv', '/Users/as/.cache/pre-commit/repo2jxgpyes/py_env-python3.6', '-p', 'python3.6')
Return code: 1
Expected return code: 0
Output:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'

Errors: (none)

Traceback (most recent call last):
  File "/Users/as/.pyenv/versions/3.7.8/envs/ctixs/lib/python3.7/site-packages/pre_commit/error_handler.py", line 46, in error_handler
    yield
  File "/Users/as/.pyenv/versions/3.7.8/envs/ctixs/lib/python3.7/site-packages/pre_commit/main.py", line 316, in main
    return run(args.config, store, args)
  File "/Users/as/.pyenv/versions/3.7.8/envs/ctixs/lib/python3.7/site-packages/pre_commit/commands/run.py", line 295, in run
    install_hook_envs(hooks, store)
  File "/Users/as/.pyenv/versions/3.7.8/envs/ctixs/lib/python3.7/site-packages/pre_commit/repository.py", line 215, in install_hook_envs
    hook.install()
  File "/Users/as/.pyenv/versions/3.7.8/envs/ctixs/lib/python3.7/site-packages/pre_commit/repository.py", line 93, in install
    self.prefix, self.language_version, self.additional_dependencies,
  File "/Users/as/.pyenv/versions/3.7.8/envs/ctixs/lib/python3.7/site-packages/pre_commit/languages/python.py", line 161, in install_environment
    _make_venv(env_dir, python)
  File "/Users/as/.pyenv/versions/3.7.8/envs/ctixs/lib/python3.7/site-packages/pre_commit/languages/python.py", line 173, in make_venv
    cmd_output(*cmd, env=env, cwd='/')
  File "/Users/as/.pyenv/versions/3.7.8/envs/ctixs/lib/python3.7/site-packages/pre_commit/util.py", line 153, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/Users/as/.pyenv/versions/3.7.8/envs/ctixs/bin/python3.7', '-mvirtualenv', '/Users/as/.cache/pre-commit/repo2jxgpyes/py_env-python3.6', '-p', 'python3.6')
Return code: 1
Expected return code: 0
Output:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'

Errors: (none)
```

**Comment by rkm** [comment]
Can you post your full config, please? This seems similar to #1375, and I've also seen this myself when a hook is set to look for a different python version than is available.

**Comment by anudeepsamaiya** [comment]
@rkm This here is the config.
```
 5 repos:
  4   - repo: https://github.com/psf/black
  3     rev: stable
  2     hooks:
  1       - id: black
6           language_version: python3.6
  1         # override until resolved: https://github.com/psf/black/issues/402
  2         files: \.pyi?$
  3         types: []
  4
  5   - repo: https://gitlab.com/pycqa/flake8
  6     rev: 3.7.9
  7     hooks:
  8     - id: flake8
  9       language_version: python3.6
 10       exclude: docs/code_examples
 11
 12   - repo: https://github.com/timothycrosley/isort
 13     rev: 4.3.21
 14     hooks:
 15       - id: isort
 16         additional_dependencies: [toml]
 17         language_version: python3.6
 18
 19   - repo: https://github.com/pre-commit/pre-commit-hooks
 20     rev: v2.4.0
 21     hooks:
 22       - id: trailing-whitespace
 23       - id: end-of-file-fixer
 24       - id: debug-statements
 25       - id: check-ast
 26       - id: check-merge-conflict
 27   #
 28   # - repo: https://github.com/asottile/seed-isort-config
 29   #   rev: v1.9.4
 30   #   hooks:
 31   #     - id: seed-isort-config
```

**Comment by asottile** [comment]
do you have `python3.6` installed on your computer?

**Comment by anudeepsamaiya** [comment]
yes, I have installed 3.6.8 with pyenv and have set it as global. In this venv 3.7.8 is the local version.

**Comment by asottile** [comment]
what does `cd / && python3.6 --version --version` give you

and `virtualenv venv36 -ppython3.6`

**Comment by anudeepsamaiya** [comment]
> cd / && python3.6 --version --version give you

Python 3.6.8

>  virtualenv venv36 -ppython3.6

RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'

**Comment by asottile** [comment]
I'd suggest making an issue on virtualenv then

**Comment by limbuu** [comment]
I ran into same problem. Any progress on this @anudeepsamaiya

**Comment by asottile** [comment]
I don;t see an issue on virtualenv's side so it's likely that never happened -- could you make one instead @limbuu  ?

**Comment by raholler** [comment]
I have the same issue with conda environment and python version 3.8:

### version information

```
pre-commit version: 2.8.2
sys.version:
    3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:20:24) [MSC v.1916 64 bit (AMD64)]
sys.executable: C:\Users\radostwork\anaconda3\envs\geo\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\radostwork\\anaconda3\\envs\\geo\\python.exe', '-mvirtualenv', 'C:\\Users\\radostwork\\.cache\\pre-commit\\repoy369p2qn\\py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "C:\Users\radostwork\anaconda3\envs\geo\lib\site-packages\pre_commit\error_handler.py", line 65, in error_handler
    yield
  File "C:\Users\radostwork\anaconda3\envs\geo\lib\site-packages\pre_commit\main.py", line 347, in main
    return hook_impl(
  File "C:\Users\radostwork\anaconda3\envs\geo\lib\site-packages\pre_commit\commands\hook_impl.py", line 217, in hook_impl
    return retv | run(config, store, ns)
  File "C:\Users\radostwork\anaconda3\envs\geo\lib\site-packages\pre_commit\commands\run.py", line 388, in run
    install_hook_envs(hooks, store)
  File "C:\Users\radostwork\anaconda3\envs\geo\lib\site-packages\pre_commit\repository.py", line 206, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\radostwork\anaconda3\envs\geo\lib\site-packages\pre_commit\repository.py", line 82, in _hook_install
    lang.install_environment(
  File "C:\Users\radostwork\anaconda3\envs\geo\lib\site-packages\pre_commit\languages\python.py", line 202, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "C:\Users\radostwork\anaconda3\envs\geo\lib\site-packages\pre_commit\util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\radostwork\\anaconda3\\envs\\geo\\python.exe', '-mvirtualenv', 'C:\\Users\\radostwork\\.cache\\pre-commit\\repoy369p2qn\\py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)
```

**Comment by asottile** [comment]
please don't report here, report to virtualenv -- thanks!
