### ISSUE TITLE
Environment installation fails with `missing posixpath`

### ISSUE THREAD

**Issue by gruentee** [pre-commit/pre-commit#1647]
Hello, thanks for this great project.

My installation fails with the following log output.
Steps done before: `pre-commit install`
I tried with both system python (3.8.6) and 2.7 in a virtualenv, to no avail.

### version information

```
pre-commit version: 2.6.0
sys.version:
    3.8.6 (default, Sep 30 2020, 04:00:38) 
    [GCC 10.2.0]
sys.executable: /usr/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/constantin/.cache/pre-commit/repo1wqs52el/py_env-python2.7/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/home/constantin/.local/lib/python2.7/site-packages/site.py", line 73, in <module>
        __boot()
      File "/home/constantin/.local/lib/python2.7/site-packages/site.py", line 3, in __boot
        import os
      File "/home/constantin/.cache/pre-commit/repo1wqs52el/py_env-python2.7/lib/python2.7/os.py", line 49, in <module>
        import posixpath as path
    ImportError: No module named posixpath
    
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pre_commit/error_handler.py", line 56, in error_handler
    yield
  File "/usr/lib/python3.8/site-packages/pre_commit/main.py", line 392, in main
    return run(args.config, store, args)
  File "/usr/lib/python3.8/site-packages/pre_commit/commands/run.py", line 380, in run
    install_hook_envs(hooks, store)
  File "/usr/lib/python3.8/site-packages/pre_commit/repository.py", line 200, in install_hook_envs
    _hook_install(hook)
  File "/usr/lib/python3.8/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/usr/lib/python3.8/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/usr/lib/python3.8/site-packages/pre_commit/languages/helpers.py", line 25, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir)
  File "/usr/lib/python3.8/site-packages/pre_commit/util.py", line 157, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/constantin/.cache/pre-commit/repo1wqs52el/py_env-python2.7/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/home/constantin/.local/lib/python2.7/site-packages/site.py", line 73, in <module>
        __boot()
      File "/home/constantin/.local/lib/python2.7/site-packages/site.py", line 3, in __boot
        import os
      File "/home/constantin/.cache/pre-commit/repo1wqs52el/py_env-python2.7/lib/python2.7/os.py", line 49, in <module>
        import posixpath as path
    ImportError: No module named posixpath
    

```

**Comment by asottile** [comment]
`posixpath` is part of the standard library -- this looks like an issue with virtualenv -- what does this do:

```
python -m virtualenv venv -p python2.7
venv/bin/pip --version
```

**Comment by asottile** [comment]
actually, looks like a virtualenv issue -- I'd suggest following up here: #1638

**Comment by gruentee** [comment]
Thanks, Anthony, first for this great project, second for your quick reply.
As you suspected it was related to the virtualenv, `venv/bin/pip --version` yielded the same error. After deleting my `.local/lib/python2.7/site-packages/` folder and reinstalling pre-commit invocation works fine, except that install pre-commit-hooks now fails because of Python version being < 3. What is the last supported version for Python 2.7?

**Comment by asottile** [comment]
you can either set [`language_version`](https://pre-commit.com/#config-language_version) or take a look at [the changelog](https://github.com/pre-commit/pre-commit-hooks/blob/master/CHANGELOG.md)

**Comment by gruentee** [comment]
Thanks, I got it working.
