### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by brianmcconnel** [pre-commit/pre-commit#1648]
This seems like it might be virtualenv issue, but as I ran across it using pre-commit I posted it here in case anyone has the same issue.  

When doing a standard install of pre-commit on windows 10 I got the following error:
```
An unexpected error has occurred: CalledProcessError: command: ('c:\\users\\<user>\\development\\anaconda\\envs\\<conda env>\\python.exe', '-mvirtualenv', 'C:\\Users\\<user>\\.cache\\pre-commit\\repoh4kvdsco\\py_env-default', '-p', 'c:\\users\\<user>\\development\\anaconda\\envs\\<conda env>\\python.exe')
return code: 1
expected return code: 0
stdout:
    FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\<user>\\development\\anaconda\\envs\\<conda env>\\Lib\\venv\\scripts\\nt\\python.exe'

stderr: (none)
Check the log at C:\Users\<user>\.cache\pre-commit\pre-commit.log
```

When I downgraded virtualenv to 20.0.35 to 20.0.33 everything worked again.

**Comment by asottile** [comment]
dupe #1645 -- yes it is a virtualenv issue please report it there

**Comment by gaborbernat** [comment]
upstream issue https://github.com/pypa/virtualenv/issues/1986

**Comment by MrBrrr** [comment]
I faced similar issue on Python 3.10, while on Python 3.9 installation works correctly.

Tratceback:

```
$ pre-commit run --all-files
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\<user_name>\\.cache\\pre-commit\\repo_3uqkk65\\py_env-python3.10\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "C:\Users\<user_name>\Miniconda3\envs\<conda_env>\lib\runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Users\<user_name>\Miniconda3\envs\<conda_env>\lib\runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\__main__.py", line 29, in <module>
        from pip._internal.cli.main import main as _main
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
        from pip._internal.cli.autocompletion import autocomplete
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
        from pip._internal.cli.main_parser import create_main_parser
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
        from pip._internal.cli import cmdoptions
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 24, in <module>
        from pip._internal.cli.parser import ConfigOptionParser
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\_internal\cli\parser.py", line 12, in <module>
        from pip._internal.configuration import Configuration, ConfigurationError
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\_internal\configuration.py", line 24, in <module>
        from pip._internal.utils import appdirs
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
        from pip._vendor import platformdirs as _appdirs
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 42, in <module>
        PlatformDirs = _set_platform_dir_class()  #: Currently active platform
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 21, in _set_platform_dir_class
        from pip._vendor.platformdirs.windows import Windows as Result
      File "C:\Users\<user_name>\.cache\pre-commit\repo_3uqkk65\py_env-python3.10\lib\site-packages\pip\_vendor\platformdirs\windows.py", line 3, in <module>
        import ctypes
      File "C:\Users\<user_name>\Miniconda3\envs\<conda_env>\lib\ctypes\__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: DLL load failed while importing _ctypes: The specified module could not be found.

Check the log at C:\Users\<user_name>\.cache\pre-commit\pre-commit.log
```

Python 3.10 has additionaly those packages:
* bzip2
* libffi
* tk
* xz
* zlib

**Comment by asottile** [comment]
that's different, that's conda's problem
