### ISSUE TITLE
Shebang generation code incorrectly prefers system python over virtualenv python

### ISSUE THREAD

**Issue by lg-kialo** [pre-commit/pre-commit#1693]
**Operating system**: Ubuntu 20.04

### Steps to reproduce
1. Install Python 3.8.0 using `pyenv` and set the global Python version to 3.8.0 (`pyenv global 3.8.0`).
After this, in my `$PATH` I have `python`, `python3`, `python3.8` which all run the same executable `/home/user/.pyenv/versions/3.8.0/bin/python3`.
2. Crate a git repository.
3. Inside the repository, create a virtual environment with `python -m venv venv`.
4. Activate the virtual environment with `source venv/bin/activate`.
At this point in my `$PATH` I have: `python` and `python3` pointing to the virtualenv python, and `python3.8` which points to the global one (`venv` doesn't create the alias).
5. Install `pre-commit` and `black` with `pip install pre-commit black`
6. Add the following python-script hook as `hook.py`:
```python
#!/usr/bin/env python3
import black
```
7. Make the script executable with `chmod +x hook.py`.
8. Add the following `.pre-commit-config.yaml`
```yaml
repos:
-   repo: local
    hooks:
    -   id: my-hook
        name: my hook
        language: script
        entry: hook.py
        always_run: true
        verbose: true
```
9. Stage the new files and commit them.
10. Install the `pre-commit` script and the hooks with `pre-commit install --install-hooks`
11. Add a new file, stage it and commit it.
12. **Bug:** the hook fails due to `ModuleNotFoundError`
```
my hook..................................................................Failed
- hook id: my-hook
- duration: 0.02s
- exit code: 1

Traceback (most recent call last):
  File "/home/user/test/hook.py", line 2, in <module>
    import black
ModuleNotFoundError: No module named 'black
```

So, what is happening here?
Running `./hook.py` works as expected. Same for `python hook.py` and simply running `pre-commit`.
The problem, I think, is in the shebang generation code: https://github.com/pre-commit/pre-commit/blob/8f32c5b929ca99e4d396d27b993017f821f6670a/pre_commit/commands/install_uninstall.py#L56-L73

The code looks first for `python3.8` in my `$PATH`, and it finds the global one which doesn't have the module `black` installed, and uses it. This is confirmed by looking at `.git/hooks/pre-commit`, which has the shebang `#!/usr/bin/env python3.8`.
This means that git runs the hook using system python, which is not what I'd like.

But still it doesn't explain why `pre-commit` is running my `hook.py` using the system python. Looking at `.git/hooks/pre-commit` I find `INSTALL_PYTHON = '/home/user/test/venv/bin/python'`, which means in turn that `CMD` contains the virtualenv python.
I verified this by raising an exception before `os.execvp(CMD[0], CMD)` and `CMD` is the following
```python
['/home/user/test/venv/bin/python', '-mpre_commit', 'hook-impl', '--config=.pre-commit-config.yaml', '--hook-type=pre-commit', '--hook-dir', '/home/user/test/.git/hooks', '--']
```
Moreover, running
```
/home/user/test/venv/bin/python -mpre_commit hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit --hook-dir /home/user/test/.git/hooks --
```
works just fine.

So my assumption is that the shebang in `.git/hooks/pre-commit` which points to the system python is influencing anyway which interpreter gets chosen to execute the python script hooks.
In fact, changing the shebang in `.git/hooks/pre-commit` to `#!/usr/bin/env python3`, which resolves to the virtualenv python, makes everything work as expected. The problem is, of course, that every time the hooks are reinstalled the shebang is reset to the system python.

I would appreciate your feedback about the issue.

**Comment by asottile** [comment]
I can't reproduce, the hook script (`.git/hooks/pre-commit`) has nothing to do with this -- it's just a way to run the original application:

```
$ babi hook.py
$ chmod +x !$
chmod +x hook.py
$ babi .pre-commit-config.yaml
$ pre-commit install
pre-commit installed at .git/hooks/pre-commit
$ touch t.py
$ virtualenv venv
. created virtual environment CPython3.8.5.final.0-64 in 171ms
  creator CPython3Posix(dest=/tmp/x/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/asottile/.local/share/virtualenv)
    added seed packages: pip==20.1.1, setuptools==50.2.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ . venv/bin/activate
(venv) $ pip install black
Processing /home/asottile/.cache/pip/wheels/95/a4/59/10cd5378d52f92cdb45025f040e4686e10ae5217961c25fd66/black-20.8b1-py3-none-any.whl
Collecting toml>=0.10.1
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting typed-ast>=1.4.0
  Using cached typed_ast-1.4.1-cp38-cp38-manylinux1_x86_64.whl (768 kB)
Collecting pathspec<1,>=0.6
  Downloading pathspec-0.8.1-py2.py3-none-any.whl (28 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting regex>=2020.1.8
  Downloading regex-2020.10.28-cp38-cp38-manylinux2014_x86_64.whl (736 kB)
     |████████████████████████████████| 736 kB 4.0 MB/s 
Collecting click>=7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Installing collected packages: toml, appdirs, mypy-extensions, typed-ast, pathspec, typing-extensions, regex, click, black
Successfully installed appdirs-1.4.4 black-20.8b1 click-7.1.2 mypy-extensions-0.4.3 pathspec-0.8.1 regex-2020.10.28 toml-0.10.2 typed-ast-1.4.1 typing-extensions-3.7.4.3
WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.
You should consider upgrading via the '/tmp/x/venv/bin/python -m pip install --upgrade pip' command.
(venv) $ git status
On branch master

No commits yet

Untracked files:
	.pre-commit-config.yaml
	hook.py
	t.py

nothing added to commit but untracked files present
(venv) $ git add .
(venv) $ pre-commit  run --all-files
my hook..................................................................Passed
- hook id: my-hook
- duration: 0.24s
(venv) $ deactivate 
$ pre-commit run --all-files
my hook..................................................................Failed
- hook id: my-hook
- duration: 0.02s
- exit code: 1

Traceback (most recent call last):
  File "/tmp/x/hook.py", line 2, in <module>
    import black
ModuleNotFoundError: No module named 'black'

```

and using the git machinery (which is irrelevant, it works the same as `pre-commit run`):

```console
(venv) $ pre-commit install
pre-commit installed at .git/hooks/pre-commit
(venv) $ git commit
my hook..................................................................Passed
- hook id: my-hook
- duration: 0.17s
Aborting commit due to empty commit message.
(venv) $ deactivate 
$ git commit
my hook..................................................................Failed
- hook id: my-hook
- duration: 0.02s
- exit code: 1

Traceback (most recent call last):
  File "/tmp/x/hook.py", line 2, in <module>
    import black
ModuleNotFoundError: No module named 'black'

```

you must have deactivated your virtualenv between steps 4 and 12

when using `language: system` or `language: script` it is up to you to have the expected things on the `PATH` -- those two languages are the escape hatch and are **not recommended**, use https://github.com/psf/black instead, or use `language: python` with `additional_dependencies`

**Comment by asottile** [comment]
it's certainly possible that pyenv is bamboozling you and adjusting `PATH` in its shim scripts -- that would be particularly naughty of them

I don't use pyenv due to other bad choices made there, but if they do that as well it wouldn't be surprising

that said, if your hooks depend on state not managed by pre-commit you've kinda missed the point of the framework in the first place :)

**Comment by lg-kialo** [comment]
> you must have deactivated your virtualenv between steps 4 and 12

No, I didn't.

Again:
```
❯ cd ~
❯ mkdir test
❯ cd test
❯ python -c 'import sys; print(sys.executable)'                                                                                                                                                                                                                                             
/home/lg/.pyenv/versions/3.8.2/bin/python
❯ python3 -c 'import sys; print(sys.executable)'                                                                                                                                                                                                                                            
/home/lg/.pyenv/versions/3.8.2/bin/python3
❯ python3.8 -c 'import sys; print(sys.executable)'                                                                                                                                                                                                                                          
/home/lg/.pyenv/versions/3.8.2/bin/python3.8
❯ git init                                                                                                                                                                                                                                                                                  
Initialized empty Git repository in /home/lg/test/.git/
❯ python -m venv venv
❯ source venv/bin/activate
❯ python -c 'import sys; print(sys.executable)'                                                                                                                                                                                                                                             
/home/lg/test/venv/bin/python
❯ python3 -c 'import sys; print(sys.executable)'                                                                                                                                                                                                                                            
/home/lg/test/venv/bin/python3
❯ python3.8 -c 'import sys; print(sys.executable)'                                                                                                                                                                                                                                          
/home/lg/.pyenv/versions/3.8.2/bin/python3.8
❯ pip install pre-commit black                                                                                                                                                                                                                                                              
Collecting pre-commit                                                                                                                                                                                                                                                                       
  Using cached https://files.pythonhosted.org/packages/27/ef/f03c234bc38db078dc820a3ba457bb0414f4d38ae88de7c5e2686010ed65/pre_commit-2.8.2-py2.py3-none-any.whl                                                                                                                             
Collecting black                                                                                                                                                                                                                                                                            
Collecting toml (from pre-commit)                                                                                                                                                                                                                                                           
  Using cached https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl                                                                                                                                  
Collecting identify>=1.0.0 (from pre-commit)                                                                                                                                                                                                                                                
  Using cached https://files.pythonhosted.org/packages/ba/cf/6c277857c1dc50bd7e773f8c012ed5717e0ed41a9a9f40e63098580479cf/identify-1.5.9-py2.py3-none-any.whl                                                                                                                               
Collecting cfgv>=2.0.0 (from pre-commit)                                                                                                                                                                                                                                                    
  Using cached https://files.pythonhosted.org/packages/45/cd/3878c9248e59e5e2ebd0dc741ab984b18d86e7283ae9b127b05fc287d239/cfgv-3.2.0-py2.py3-none-any.whl                                                                                                                                   
Collecting nodeenv>=0.11.1 (from pre-commit)                                                                                                                                                                                                                                                
  Using cached https://files.pythonhosted.org/packages/ae/d0/efdf54539948315cc76e5a66b709212963101d002822c3b54369dbf9b5e0/nodeenv-1.5.0-py2.py3-none-any.whl                                                                                                                                
Collecting virtualenv>=20.0.8 (from pre-commit)                                                                                                                                                                                                                                             
  Using cached https://files.pythonhosted.org/packages/97/f3/c064343ac58d1a54c393a3f66483a29500f644a5918deeb935d28673edd9/virtualenv-20.1.0-py2.py3-none-any.whl                                                                                                                            
Collecting pyyaml>=5.1 (from pre-commit)                                                                                                                                                                                                                                                    
  Using cached https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz                                                                                                                                               
Collecting click>=7.1.2 (from black)                                                                                                                                                                                                                                                        
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl                                                                                                                                  
Collecting appdirs (from black)                                                                                                                                                                                                                                                             
  Using cached https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl                                                                                                                                
Collecting regex>=2020.1.8 (from black)                                                                                                                                                                                                                                                     
  Using cached https://files.pythonhosted.org/packages/4a/ee/bffdd2c5d8983ddfa365ee5bb619d81a74cadd5ef2bc75ec4e73a9c254f6/regex-2020.10.28-cp38-cp38-manylinux2010_x86_64.whl                                                                                                               
Collecting pathspec<1,>=0.6 (from black)                                                                                                                                                                                                                                                    
  Using cached https://files.pythonhosted.org/packages/29/29/a465741a3d97ea3c17d21eaad4c64205428bde56742360876c4391f930d4/pathspec-0.8.1-py2.py3-none-any.whl                                                                                                                               
Collecting typing-extensions>=3.7.4 (from black)                                                                                                                                                                                                                                            
  Using cached https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl                                                                                                                        
Collecting mypy-extensions>=0.4.3 (from black)                                                                                                                                                                                                                                              
  Using cached https://files.pythonhosted.org/packages/5c/eb/975c7c080f3223a5cdaff09612f3a5221e4ba534f7039db34c35d95fa6a5/mypy_extensions-0.4.3-py2.py3-none-any.whl                                                                                                                        
Collecting typed-ast>=1.4.0 (from black)                                                                                                                                                                                                                                                    
  Using cached https://files.pythonhosted.org/packages/77/49/51308e8c529e14bb2399ff6d22998583aa9ae189ec191e6f7cbb4679f7d5/typed_ast-1.4.1-cp38-cp38-manylinux1_x86_64.whl                                                                                                                   
Collecting distlib<1,>=0.3.1 (from virtualenv>=20.0.8->pre-commit)                                                                                                                                                                                                                          
  Using cached https://files.pythonhosted.org/packages/f5/0a/490fa011d699bb5a5f3a0cf57de82237f52a6db9d40f33c53b2736c9a1f9/distlib-0.3.1-py2.py3-none-any.whl                                                                                                                                
Collecting six<2,>=1.9.0 (from virtualenv>=20.0.8->pre-commit)                                                                                                                                                                                                                              
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl                                                                                                                                   
Collecting filelock<4,>=3.0.0 (from virtualenv>=20.0.8->pre-commit)                                                                                                                                                                                                                         
  Using cached https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl                                                                                                                                  
Installing collected packages: toml, identify, cfgv, nodeenv, distlib, appdirs, six, filelock, virtualenv, pyyaml, pre-commit, click, regex, pathspec, typing-extensions, mypy-extensions, typed-ast, black                                                                                 
  Running setup.py install for pyyaml ... done                                                                                                                                                                                                                                              
Successfully installed appdirs-1.4.4 black-20.8b1 cfgv-3.2.0 click-7.1.2 distlib-0.3.1 filelock-3.0.12 identify-1.5.9 mypy-extensions-0.4.3 nodeenv-1.5.0 pathspec-0.8.1 pre-commit-2.8.2 pyyaml-5.3.1 regex-2020.10.28 six-1.15.0 toml-0.10.2 typed-ast-1.4.1 typing-extensions-3.7.4.3 vir
tualenv-20.1.0
WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
❯ cat > hook.py <<EOF
#!/usr/bin/env python3
import black
EOF
❯ cat > .pre-commit-config.yaml <<EOF
repos:
-   repo: local
    hooks:
    -   id: my-hook
        name: my hook
        language: script
        entry: hook.py
        always_run: true
        verbose: true
EOF
❯ chmod +x hook.py
❯ git add .
❯ gc -m 'init'                                                                    
[master (root-commit) 3237fe0] init
 2 files changed, 11 insertions(+)
 create mode 100644 .pre-commit-config.yaml
 create mode 100755 hook.py
❯ pre-commit install --install-hooks                    
pre-commit installed at .git/hooks/pre-commit
❯ touch a
❯ gc -am 'another file'
my hook..................................................................Failed
- hook id: my-hook
- duration: 0.02s
- exit code: 1

Traceback (most recent call last):
  File "/home/lg/test/hook.py", line 2, in <module>
    import black
ModuleNotFoundError: No module named 'black'
❯ pre-commit           
my hook..................................................................Passed
- hook id: my-hook
- duration: 0.09s
❯ head -n 1 .git/hooks/pre-commit 
#!/usr/bin/env python3.8
```

Moreover:

> the hook script (.git/hooks/pre-commit) has nothing to do with this -- it's just a way to run the original application:

that's a pretty bold claim, given that this works just fine:
```
❯ NEW_SHEBANG="#\!\/usr\/bin\/env python3"; sed -i "1s/.*/$NEW_SHEBANG/" .git/hooks/pre-commit
❯ head -n 1 .git/hooks/pre-commit 
#!/usr/bin/env python3
❯ gc -m 'another file'
my hook..................................................................Passed
- hook id: my-hook
- duration: 0.08s
[master 01e82ac] another file
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 a
```

> when using language: system or language: script it is up to you to have the expected things on the PATH -- those two languages are the escape hatch and are not recommended, use https://github.com/psf/black instead, or use language: python with additional_dependencies

Didn't know about this, thanks for noting it. Will look into `language: python`.

**Comment by asottile** [comment]
yeah no surprise, this is pyenv doing [bad things](https://github.com/pyenv/pyenv/blob/806b30d6ce5b263a765648fbcdd68266833b7289/libexec/pyenv-exec#L45-L46)

**Comment by asottile** [comment]
you can confirm it's pyenv's fault by doing `python3 -c 'import os; print(os.environ["PATH"])'` and `python3.8 -c 'import os; print(os.environ["PATH"])'` compare that with `env | grep '^PATH='` (they should all be the same, if it weren't for pyenv's bad choices)

**Comment by lg-kialo** [comment]
Yes, figured that out just now.
