### ISSUE TITLE
PermissionError when running `pre-commit install`

### ISSUE THREAD

**Issue by anupamsingh24** [pre-commit/pre-commit#1732]
Trying to run the pre-commit utility but getting an Exception of PermissionError when executing `pre-commit install`
FYI, all the dirs have the executable permission in the .git/ path 

This is the stack trace

```
Traceback (most recent call last):
  File "/home/anupam/.local/lib/python3.8/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/anupam/.local/lib/python3.8/site-packages/pre_commit/main.py", line 357, in main
    return install(
  File "/home/anupam/.local/lib/python3.8/site-packages/pre_commit/commands/install_uninstall.py", line 139, in install
    _install_hook_script(
  File "/home/anupam/.local/lib/python3.8/site-packages/pre_commit/commands/install_uninstall.py", line 117, in _install_hook_script
    make_executable(hook_path)
  File "/home/anupam/.local/lib/python3.8/site-packages/pre_commit/util.py", line 86, in make_executable
    os.chmod(filename, new_mode)
PermissionError: [Errno 1] Operation not permitted: '.git/hooks/pre-commit'

```

**Comment by asottile** [comment]
can you show `ls -al . .git .git/hooks .git/hooks/pre-commit` -- my guess is one of those is owned by root because you ran `sudo ...` something? (you should never need sudo while using pre-commit)

**Comment by asottile** [comment]
please also include the error log, the whole thing, you've left out some of the most important information
