### ISSUE TITLE
An unexpected error has occurred: OSError: [Errno 8] Exec format

### ISSUE THREAD

**Issue by smart-patrol** [pre-commit/pre-commit#1736]
I am getting the following error when trying to run precommit.

```
pre-commit version: 2.9.3
sys.version:
    3.8.5 (default, Sep  4 2020, 02:22:02) 
    [Clang 10.0.0 ]
sys.executable: /usr/local/anaconda3/bin/python
os.name: posix
sys.platform: darwin
```
### error information

```
An unexpected error has occurred: OSError: [Errno 8] Exec format error: 'package/.git/hooks/pre-commit.legacy'


Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pre_commit/main.py", line 347, in main
    return hook_impl(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pre_commit/commands/hook_impl.py", line 211, in hook_impl
    retv, stdin = _run_legacy(hook_type, hook_dir, args)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pre_commit/commands/hook_impl.py", line 43, in _run_legacy
    return subprocess.run(cmd, input=stdin).returncode, stdin
  File "/usr/local/anaconda3/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'package/.git/hooks/pre-commit.legacy'
```

**Comment by asottile** [comment]
`pre-commit.legacy` is whatever script was at `.git/hooks/pre-commit` when you ran `pre-commit install` (pre-commit moves it aside to enable a ["migration mode"](https://pre-commit.com/#running-in-migration-mode))

it looks to me like it's not a valid executable -- you can run `pre-commit install --force` to remove it (though I'm curious what it is and how it got there, and why it's not a valid executable)

**Comment by smart-patrol** [comment]
Thanks, this was what was throwing the error:

```
if [ -z "`git config --local user.name`" ]; then
  echo "fatal: user.name is not set locally"
  exit 1
fi
if [ -z "`git config --local user.email`" ]; then
  echo "fatal: user.email is not set locally"
  exit 1
fi
```
Removing it using `pre-commit install -f` fixed it.
