### ISSUE TITLE
Bad sys.prefix when running per-commit on M1 Mac

### ISSUE THREAD

**Issue by jeromepin** [pre-commit/pre-commit#1797]
With a fresh install of pre-commit on a M1 Mac, I'm getting the following error. However, it may be a virtualenv issue.

### version information

```
pre-commit version: 1.21.0
sys.version:
    3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:44:01)
    [Clang 12.0.0 (clang-1200.0.32.27)]
sys.executable: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9', '-mvirtualenv', '/Users/jerome/.cache/pre-commit/repobdo53y9s/py_env-python3.9', '-p', '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9')
return code: 100
expected return code: 0
stdout:
    Already using interpreter /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
    Using base prefix '/Library/Frameworks/Python.framework/Versions/3.9'
    New python executable in /Users/jerome/.cache/pre-commit/repobdo53y9s/py_env-python3.9/bin/python3.9
    Also creating executable in /Users/jerome/.cache/pre-commit/repobdo53y9s/py_env-python3.9/bin/python
    ERROR: The executable /Users/jerome/.cache/pre-commit/repobdo53y9s/py_env-python3.9/bin/python3.9 is not functioning
    ERROR: It thinks sys.prefix is '/' (should be '/Users/jerome/.cache/pre-commit/repobdo53y9s/py_env-python3.9')
    ERROR: virtualenv is not compatible with this system or executable

stderr: (none)
```

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pre_commit/error_handler.py", line 72, in error_handler
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pre_commit/main.py", line 344, in main
    return run(args.config, store, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pre_commit/commands/run.py", line 292, in run
    install_hook_envs(hooks, store)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pre_commit/repository.py", line 220, in install_hook_envs
    hook.install()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pre_commit/repository.py", line 97, in install
    lang.install_environment(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pre_commit/languages/python.py", line 169, in install_environment
    _make_venv(env_dir, python)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pre_commit/languages/python.py", line 181, in make_venv
    cmd_output_b(*cmd, env=env, cwd='/')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pre_commit/util.py", line 141, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9', '-mvirtualenv', '/Users/jerome/.cache/pre-commit/repobdo53y9s/py_env-python3.9', '-p', '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9')
return code: 100
expected return code: 0
stdout:
    Already using interpreter /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
    Using base prefix '/Library/Frameworks/Python.framework/Versions/3.9'
    New python executable in /Users/jerome/.cache/pre-commit/repobdo53y9s/py_env-python3.9/bin/python3.9
    Also creating executable in /Users/jerome/.cache/pre-commit/repobdo53y9s/py_env-python3.9/bin/python
    ERROR: The executable /Users/jerome/.cache/pre-commit/repobdo53y9s/py_env-python3.9/bin/python3.9 is not functioning
    ERROR: It thinks sys.prefix is '/' (should be '/Users/jerome/.cache/pre-commit/repobdo53y9s/py_env-python3.9')
    ERROR: virtualenv is not compatible with this system or executable

stderr: (none)

```

The pre-commit hooks & config work great on any other system (MacOS Intel of Linux)

**Comment by asottile** [comment]
pre-commit 1.21.0 is very very old, as is the version of virtualenv you're using (it looks like the `<20.x` variant)

upgrade both of those

**Comment by jeromepin** [comment]
Oh I'm sorry. I installed pre-commit a few days ago and thought it was a recent version. But I had a version lock in the requirements.txt... I didn't even check the obvious answer... Sorry for bothering you, everything works fine ! Thanks
