### ISSUE TITLE
aspy.yaml not found during pre-commit install

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit#180]
```
pre-commit install
Traceback (most recent call last):
 File "/Users/****/.virtualenvs/****/bin/pre-commit", line 9, in <module>
   load_entry_point('pre-commit==0.3.2', 'console_scripts', 'pre-commit')()
 File "/Users/****/.virtualenvs/****/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
   return get_distribution(dist).load_entry_point(group, name)
 File "/Users/****/.virtualenvs/****/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
   return ep.load()
 File "/Users/****/.virtualenvs/****/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
   entry = __import__(self.module_name, globals(),globals(), ['__name__'])
 File "/Users/****/.virtualenvs/****/lib/python2.7/site-packages/pre_commit-0.3.2-py2.7.egg/pre_commit/main.py", line 8, in <module>
   from pre_commit.commands.autoupdate import autoupdate
 File "/Users/****/.virtualenvs/****/lib/python2.7/site-packages/pre_commit-0.3.2-py2.7.egg/pre_commit/commands/autoupdate.py", line 6, in <module>
   from aspy.yaml import ordered_dump
ImportError: No module named aspy.yaml
```

However...

```
» pip install aspy.yaml
Requirement already satisfied (use --upgrade to upgrade): aspy.yaml in /Users/****/.virtualenvs/****/lib/python2.7/site-packages/aspy.yaml-0.2.0-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): ordereddict in /Users/****/.virtualenvs/****/lib/python2.7/site-packages/ordereddict-1.1-py2.7.egg (from aspy.yaml)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /Users/****/.virtualenvs/****/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.9-intel.egg (from aspy.yaml)
```

Is there anything obvious going wrong here?

**Comment by asottile** [comment]
I believe I've actually fixed this here: https://github.com/asottile/aspy.yaml/pull/2 / https://github.com/asottile/aspy.yaml/pull/3

**Comment by guykisel** [comment]
Nice, thanks!
