### ISSUE TITLE
Pre-commit looking for a virtualenv that does not exist

### ISSUE THREAD

**Issue by ehontoria** [pre-commit/pre-commit#1801]
Hi folks! Throwing a bug report your way - not quite sure what is happening here.

# Setup and Problem statement
`Pipenv` virtual environment using python version 3.7.7 coupled with `Pyenv` in order to install different python versions. Attempting to run `pre-commit` version `2.10.0` in that environment. 
Very simple pre-commit setup just using `mdformat`:
```
repos:
-    repo: https://github.com/executablebooks/mdformat
     rev: 0.5.6
     hooks:
         -    id: mdformat
              args: [--check]
```

The problem:
When pre-commit goes to install the hooks in it's own virtual environment it runs into the following:
```
(eng-handbook) emily.hontoria@EmilyHontoriaMBP eng-handbook % pre-commit run --all-files
[INFO] Installing environment for https://github.com/executablebooks/mdformat.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/bin/python', '-mvirtualenv', '/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.7m', '-p', 'python3.7m')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7m'

stderr: (none)
Check the log at /Users/emily.hontoria/.cache/pre-commit/pre-commit.log
```

Now I did a little bit of digging and it turns out `/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.7m` doesn't exist. But `/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.7` does.

As a point of additional information: `python3.7m` _is_ in my path. It is set up through `/Users/emily.hontoria/.pyenv/shims`.

# pre-commit.log
```
sys.version:
    3.7.7 (default, Mar 17 2020, 14:09:11)
    [Clang 11.0.0 (clang-1100.0.33.17)]
sys.executable: /Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/bin/python', '-mvirtualenv', '/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.7m', '-p', 'python3.7m')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7m'

stderr: (none)
```

```
Traceback (most recent call last):
  File "/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/lib/python3.7/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/lib/python3.7/site-packages/pre_commit/main.py", line 378, in main
    return run(args.config, store, args)
  File "/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/lib/python3.7/site-packages/pre_commit/commands/run.py", line 403, in run
    install_hook_envs(hooks, store)
  File "/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/lib/python3.7/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/lib/python3.7/site-packages/pre_commit/repository.py", line 83, in _hook_install
    hook.prefix, hook.language_version, hook.additional_dependencies,
  File "/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/lib/python3.7/site-packages/pre_commit/languages/python.py", line 202, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/lib/python3.7/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/bin/python', '-mvirtualenv', '/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.7m', '-p', 'python3.7m')
return code: 1
expected return code: 0
```

**Comment by asottile** [comment]
can you show the following:

```bash
python -c 'import sys; print(sys.executable)`
python -c 'import os.path, sys; print(os.path.realpath(sys.executable))'
which python3.7m
```

your python appears to be reporting that it's executable is `python3.7m` *and* that `python3.7m` is available on your `PATH` -- this is causing pre-commit to choose it as the default executable

however, it looks like `virtualenv` is not picking that up -- it probably should be able to if it can be resolved via `which`

**Comment by ehontoria** [comment]
Output:
```
(eng-handbook) emily.hontoria@EmilyHontoriaMBP eng-handbook % python -c 'import sys; print(sys.executable)'
/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/bin/python
(eng-handbook) emily.hontoria@EmilyHontoriaMBP eng-handbook % python -c 'import os.path, sys; print(os.path.realpath(sys.executable))'
/Users/emily.hontoria/.pyenv/versions/3.7.7/bin/python3.7m
(eng-handbook) emily.hontoria@EmilyHontoriaMBP eng-handbook % which python3.7m
/Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/bin/python3.7m
```

**Comment by asottile** [comment]
how about `cd / && python3.7m --version --version`

**Comment by ehontoria** [comment]
Output (ran `--version` once just to make sure to show the version is correct there):
```
(eng-handbook) emily.hontoria@EmilyHontoriaMBP eng-handbook % cd / && python3.7m --version
Python 3.7.7
(eng-handbook) emily.hontoria@EmilyHontoriaMBP / % cd / && python3.7m --version --version
Python 3.7.7 (default, Mar 17 2020, 14:09:11)
[Clang 11.0.0 (clang-1100.0.33.17)]
```

**Comment by asottile** [comment]
how about `virtualenv --version && virtualenv venv -p python3.7m` (probably from the directory where you were running pre-commit before)

**Comment by ehontoria** [comment]
Output:
```
(eng-handbook) emily.hontoria@EmilyHontoriaMBP eng-handbook % virtualenv --version && virtualenv venv -p python3.7m
virtualenv 20.4.2 from /Users/emily.hontoria/.local/share/virtualenvs/eng-handbook-munAcKkw/lib/python3.7/site-packages/virtualenv/__init__.py
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7m'
```

But running `python3.7m` in the same directory starts up just fine.
```
(eng-handbook) emily.hontoria@EmilyHontoriaMBP eng-handbook % python3.7m
Python 3.7.7 (default, Mar 17 2020, 14:09:11)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by asottile** [comment]
looks like a bug in [virtualenv](https://github.com/pypa/virtualenv) then -- they'll ask you to produce an output with `virtualenv --with-traceback` there 👍 

thanks for the quality report and hope it gets resolved from their end

oddly enough `virtualenv -p python3.7m` works fine on my linux machine 🤷

**Comment by ehontoria** [comment]
Thank you so much for all the help! I'll link to this issue in the `virtualenv` report since I think these outputs will probably be useful.
