### ISSUE TITLE
pre-commit fails to find setup.py for isort

### ISSUE THREAD

**Issue by manelbdcosta** [pre-commit/pre-commit#1806]
Hey there! 

So I'm running pre-commit as a script on Travis CI: 

.travis.yml
```
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
 
(...)

jobs:
  include:
    - stage: lint
      name: Code quality checks
      install:
        - pip install pre-commit
        - pyenv global 3.7.1
      script:
        - pre-commit run --all-files
```

And here is my .pre-commit-config.yaml
```
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black"]
        language_version: python3.7
```

My travis job fails this way:
```
resolvconf
git.checkout
0.46s$ git clone --depth=50 --branch=feature/Issue-20_DevTools https://github.com/manelbdcosta/pytexit.git manelbdcosta/pytexit
0.01s0.00s$ source ~/virtualenv/python2.7/bin/activate
$ python --version
Python 2.7.15
$ pip --version
pip 20.1.1 from /home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pip (python 2.7)
install.1
2.06s$ pip install pre-commit
install.2
0.02s$ pyenv global 3.7.1
11.68s$ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/timothycrosley/isort.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/timothycrosley/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/travis/.cache/pre-commit/repoU43qyv/py_env-python3.7/bin/python3.7', u'/home/travis/.cache/pre-commit/repoU43qyv/py_env-python3.7/bin/pip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/travis/.cache/pre-commit/repoU43qyv
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/home/travis/.cache/pre-commit/repoU43qyv/py_env-python3.7/lib/python3.7/tokenize.py", line 447, in open
            buffer = _builtin_open(filename, 'rb')
        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-2izol7ne/setup.py'
        
        ----------------------------------------
    
stderr:
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-2izol7ne/
    
Check the log at /home/travis/.cache/pre-commit/pre-commit.log
The command "pre-commit run --all-files" exited with 1.
```

This issue is specific to python2.7 and does not occur if it is removed from .travis.yml. It seems that pre-commit is not being able to find isort's setup.py.. Any help with this would be very appreciated! 

Thanks!

**Comment by asottile** [comment]
python2 is dead, you're using a version of pre-commit which is very old.  you're also using a version of `virtualenv` which is very old -- this leads to very old pip inside the virtualenv which does not understand pyproject.toml-only builds

**Comment by manelbdcosta** [comment]
Thanks for your answer @asottile! 🙂
