### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'C:\\Users\\...'

### ISSUE THREAD

**Issue by CircleOnCircles** [pre-commit/pre-commit#1830]
brand new install python on windows via wondows store, got this error, I ran from powershell.

This is install via pip.

<details>
<summary>Details</summary>

### version information

```
pre-commit version: 2.11.0
sys.version:
    3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
sys.executable: C:\Users\n2\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: OSError: [Errno 22] Invalid argument: 'C:\\Users\\n2\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe'
```

```
Traceback (most recent call last):
  File "C:\Users\n2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pre_commit\error_handler.py", line 65, in error_handler
    yield
  File "C:\Users\n2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pre_commit\main.py", line 385, in main
    return run(args.config, store, args)
  File "C:\Users\n2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pre_commit\commands\run.py", line 406, in run
    install_hook_envs(hooks, store)
  File "C:\Users\n2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pre_commit\repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\n2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pre_commit\repository.py", line 82, in _hook_install
    lang.install_environment(
  File "C:\Users\n2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pre_commit\languages\python.py", line 202, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "C:\Users\n2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pre_commit\util.py", line 141, in cmd_output_b
    cmd = parse_shebang.normalize_cmd(cmd)
  File "C:\Users\n2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pre_commit\parse_shebang.py", line 79, in normalize_cmd
    cmd = parse_filename(exe) + (exe,) + cmd[1:]
  File "C:\Users\n2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pre_commit\parse_shebang.py", line 22, in parse_filename
    return parse_shebang_from_file(filename)
  File "C:\Users\n2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\identify\identify.py", line 208, in parse_shebang_from_file
    with open(path, 'rb') as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\n2\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe'
```

</details>

**Comment by asottile** [comment]
iirc this is a limitation of the windows store python -- does it work if you install pre-commit into a virtualenv? or with the python.org installers?

the windows store pythons are pretty fragile in general, I wouldn't recommend them

**Comment by CircleOnCircles** [comment]
I will check with other type of installation.

**Comment by asottile** [comment]
alternatively, if you upgrade identify to `>=2.1.1` it should work around this windows store python shortcoming

thanks again for the issue!
