### ISSUE TITLE
Tags without "v" prefix not supported

### ISSUE THREAD

**Issue by kenorb** [pre-commit/pre-commit#1859]
### `.pre-commit-config.yaml`

```
---
repos:

  - repo: https://github.com/motet-a/jinjalint
    rev: "0.5"
    hooks:
      - id: jinjalint
```

Above file fails on `pre-commit run -a` with:

> An error has occurred: InvalidManifestError:

### Traceback

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/lib/python3.9/site-packages/pre_commit/main.py", line 385, in main
    return run(args.config, store, args)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/commands/run.py", line 395, in run
    for hook in all_hooks(config, store)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 228, in all_hooks
    return tuple(
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 231, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 206, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 173, in _cloned_repository_hooks
    by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
  File "/usr/local/lib/python3.9/site-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/usr/local/lib/python3.9/site-packages/cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} does not exist')
pre_commit.clientlib.InvalidManifestError:
```

### Problem

The [jinjalint repo](https://github.com/motet-a/jinjalint) has tag named `0.5`. So:

- When specifying `v0.5`, the tag doesn't exist.
- When specifying `0.5` or `!!str 0.5`, it complains it's a float (Expected string got float).
- When specifying `"0.5"`, it crashes as above.
- When specifying `master`, it gives warnings (appears to be a mutable reference).

I'm using pre-commit 2.11.1.

How to specify the tag correctly?

**Comment by asottile** [comment]
your title is false, they work [just fine](https://github.com/pre-commit/pre-commit/blob/e431b2b89862213a7538c850338d1d24c1582eea/.pre-commit-config.yaml#L15)

you'll notice the error message (which you cut off the useful information from!) says `.pre-commit-hooks.yaml does not exist` -- and if you navigate to the repository at that tag: https://github.com/motet-a/jinjalint/tree/0.5  you'll see that there definitely is not a `.pre-commit-hooks.yaml`

it looks like no tagged release has been made since the configuration was added so you'll want to use a revision directly -- for example `rev: 01e0a4d8`

A tip for the future and for reporting issues in general (not just open source), paste **the entire output that you see**, if you don't understand why you're receiving an error message you probably don't understand which parts of it are important and should leave the whole thing there!

**Comment by AIGeneratedUsername** [comment]
I am debugging exactly the same problem, so I will try to make less noise with duplicate issues.

The thing is that `InvalidManifestError` in a log file does not include which repository fails. From all closed issues I learned that `InvalidManifestError` may be due to one of two reasons:
1. Cache may be corrupted.
2. A problem in one of hooks.

**I have an enhancement proposal:** can we include in `InvalidManifestError` more information like which exactly hook failed? At this moment I look at the log file and it is a bit useless because it only gives `InvalidManifestError` traceback.  E.g. there are not debug messages to say which hooks were valid, which hook failed, or maybe nothing worked because failed to open/read cache. I believe this also may reduce questions from "pre-commit" users.
Thanks.

**Comment by asottile** [comment]
it says the repo name right before installing

but also your comment is off topic please don't do that
