### ISSUE TITLE
UnicodeEncodeError when hooks print unicode characters on Windows

### ISSUE THREAD

**Issue by domdfcoding** [pre-commit/pre-commit#1862]
The error comes from a hook but installing the hook with pip and running it directly works fine, so I think this issue is related to pre-commit's wrapped stdout.
When running python directly the stdout encoding is UTF-8, but the wrapped stdout the hook sees has an encoding of cp1252.
`locale.getpreferredencoding()` gives "cp1252".
So it seems the stdout wrapper isn't inheriting the encoding and so python falls back to the default.

I can reproduce this using the `dep_checker` hook on the https://github.com/domdfcoding/domdf_python_tools/ repository.

The traceback is as follows.

```python traceback

(venv) PS > pre-commit run --all-files dep_checker
Check dependencies.......................................................Failed
- hook id: dep_checker
- exit code: 1

Traceback (most recent call last):
  File "c:\users\dom13\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dom13\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\Scripts\dep-checker.EXE\__main__.py", line 7, in <module>
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\dep_checker\__main__.py", line 87, in main
    ret = check_imports(
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\dep_checker\__init__.py", line 372, in check_imports
    click.echo(Fore.GREEN(item.format_error()), color=colour)
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\click\utils.py", line 273, in echo
    file.write(message)
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\dom13\.cache\pre-commit\repo_9xg_8dl\py_env-python3.9\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\dom13\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2714' in position 0: character maps to <undefined>
```

**Comment by asottile** [comment]
this is just a problem with python on windows in general -- you should be able to reproduce your problem without pre-commit

for example:

```console
C:\Users\Anthony>python -c "print('\u2603')" | cat
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2603' in position 0: character maps to <undefined>
```

here's a recommended fix: https://github.com/pre-commit/pre-commit-hooks/pull/571/files

one day [utf-8 mode](https://www.python.org/dev/peps/pep-0540/) will make this problem disappear -- but today is not that day

**Comment by ashb** [comment]
>  When running python directly the stdout encoding is UTF-8, but the wrapped stdout the hook sees has an encoding of cp1252.

Sorry to resurrect an old issue, but I've just run in to this as well. (From black)

Given when run directly the encoding is correctly set to `utf-8`.

Here is a minimal reproduction:

.pre-commit-config.yaml:

```
repos:
      - id: test
        name: emoji-test
        language: system
        entry: py foo.py
        types: [python]
        pass_filenames: false
```

foo.py
```
import sys

print(sys.stdout.encoding)
print("All done! ✨ 🍰 ✨")
```


When run directly:

```
$ py foo.py
utf-8
All done! ✨ 🍰 ✨
```

When run via pre-commit:

```
$ pre-commit run test
test.....................................................................Failed
- hook id: test
- exit code: 1

cp1252
Traceback (most recent call last):
  File "C:\Users\Ash\code\tmp\foo.py", line 4, in <module>
    print("All done! \u2728 \U0001f370 \u2728")
  File "C:\Users\Ash\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 10: character maps to <undefined>
```

Pre-commit is changing the "environment" (in loose sense, not strictest sense) that a hook runs in. That feels like a bug to me.

**Comment by asottile** [comment]
@ashb please read the comment directly above yours
