### ISSUE TITLE
Missing hook manifest, but upstream has it

### ISSUE THREAD

**Issue by ibLeDy** [pre-commit/pre-commit#1902]
When running `pre-commit autoupdate` I get this output for one of the hooks ([`rstcheck`](https://github.com/myint/rstcheck)).

```console
Updating https://github.com/myint/rstcheck ... [INFO] Initializing environment for https://github.com/myint/rstcheck.

=====> C:\Users\bLeDy\.cache\pre-commit\repok4cmzvex\.pre-commit-hooks.yaml does not exist
```

Then if I try to run pre-commit I get an `InvalidManifestError`:

```console
$ pre-commit run --all-files
An error has occurred: InvalidManifestError:
=====> C:\Users\bLeDy\.cache\pre-commit\repok4cmzvex\.pre-commit-hooks.yaml does not exist
Check the log at C:\Users\bLeDy\.cache\pre-commit\pre-commit.log
```

<details>
	<summary>When checking the repo's cache folder I can confirm that the file does not exist</summary>

```console
$ pwd
/c/Users/bLeDy/.cache/pre-commit/repok4cmzvex

$ ls -la
total 77K
drwxr-xr-x 1 bLeDy 197609    0 May  9 13:32 .
drwxr-xr-x 1 bLeDy 197609    0 May  9 13:32 ..
drwxr-xr-x 1 bLeDy 197609    0 May  9 13:32 .git
drwxr-xr-x 1 bLeDy 197609    0 May  9 13:32 examples
-rw-r--r-- 1 bLeDy 197609   81 May  9 13:32 .gitignore
-rw-r--r-- 1 bLeDy 197609  571 May  9 13:32 .travis.yml
-rw-r--r-- 1 bLeDy 197609  382 May  9 13:32 AUTHORS.rst
-rw-r--r-- 1 bLeDy 197609 1.1K May  9 13:32 LICENSE
-rw-r--r-- 1 bLeDy 197609  597 May  9 13:32 Makefile
-rw-r--r-- 1 bLeDy 197609  151 May  9 13:32 MANIFEST.in
-rw-r--r-- 1 bLeDy 197609 6.6K May  9 13:32 README.rst
-rwxr-xr-x 1 bLeDy 197609  30K May  9 13:32 rstcheck.py
-rwxr-xr-x 1 bLeDy 197609 1.4K May  9 13:32 setup.py
-rwxr-xr-x 1 bLeDy 197609 1.7K May  9 13:32 test.bash
-rwxr-xr-x 1 bLeDy 197609 7.7K May  9 13:32 test_rstcheck.py
```
</details>

<details>
	<summary>This is the content of <code>pre-commit.log</code></summary>

### version information

```
pre-commit version: 2.10.1
sys.version:
    3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
sys.executable: c:\users\bledy\appdata\local\programs\python\python39\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An error has occurred: InvalidManifestError:
=====> C:\Users\bLeDy\.cache\pre-commit\repok4cmzvex\.pre-commit-hooks.yaml does not exist
```

```
Traceback (most recent call last):
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\cfgv.py", line 40, in reraise_as
    yield
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} does not exist')
cfgv.ValidationError:
=====> C:\Users\bLeDy\.cache\pre-commit\repok4cmzvex\.pre-commit-hooks.yaml does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\pre_commit\error_handler.py", line 65, in error_handler
    yield
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\pre_commit\main.py", line 378, in main
    return run(args.config, store, args)
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\pre_commit\commands\run.py", line 392, in run
    for hook in all_hooks(config, store)
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\pre_commit\repository.py", line 228, in all_hooks
    return tuple(
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\pre_commit\repository.py", line 231, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\pre_commit\repository.py", line 206, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\pre_commit\repository.py", line 173, in _cloned_repository_hooks
    by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb)
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\cfgv.py", line 40, in reraise_as
    yield
  File "c:\users\bledy\appdata\local\programs\python\python39\lib\site-packages\cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} does not exist')
pre_commit.clientlib.InvalidManifestError:
=====> C:\Users\bLeDy\.cache\pre-commit\repok4cmzvex\.pre-commit-hooks.yaml does not exist
```

</details>

I only tried this on Windows `(version 20H2, build 19042.906)`

**Comment by asottile** [comment]
you have `rev: v3.3.1`, these are the files [at that revision](https://github.com/myint/rstcheck/tree/v3.3.1)
