### ISSUE TITLE
Conda installation with Windows not working 

### ISSUE THREAD

**Issue by sarthakpati** [pre-commit/pre-commit#1920]
Hi,

I am trying to install a pre-commit hook for black but I am getting the following error when trying to commit:

```python-traceback
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
Traceback (most recent call last):
  File "c:\projects\gandlf\venv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\projects\gandlf\venv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\projects\gandlf\venv\lib\site-packages\pre_commit\__main__.py", line 1, in <module>
    from pre_commit.main import main
  File "c:\projects\gandlf\venv\lib\site-packages\pre_commit\main.py", line 13, in <module>
    from pre_commit.commands.autoupdate import autoupdate
  File "c:\projects\gandlf\venv\lib\site-packages\pre_commit\commands\autoupdate.py", line 20, in <module>
    from pre_commit.store import Store
  File "c:\projects\gandlf\venv\lib\site-packages\pre_commit\store.py", line 4, in <module>
    import sqlite3
  File "c:\projects\gandlf\venv\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "c:\projects\gandlf\venv\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified module could not be found.
```

I am working off a virtual environment (which is activate) and this import seems to be working correctly:

```powershell
(C:\Projects\GANDLF\venv) PS C:\Projects\GANDLF> python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> from _sqlite3 import *
>>> exit()
```

Any idea how to proceed? Thank you!

**Comment by sarthakpati** [comment]
I have followed the following steps:

1. ```pip install pre-commit```
2. Add black hook:
```yaml
repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
```
3. ```pre-commit install```

**Comment by sarthakpati** [comment]
PS: I found a bunch of issues related to this but no concrete answer that worked for me, hence the new post.

**Comment by asottile** [comment]
this is the duplicate issue, I don't know if someone has made a thing on the conda side to finish this out: https://github.com/pre-commit/pre-commit/issues/1329

I'd suggest following up with conda
