### ISSUE TITLE
Ruby hook not working without ruby installation

### ISSUE THREAD

**Issue by IngoMeyer441** [pre-commit/pre-commit#1930]
Hey and thanks for this very useful project. I run some tests and I think I found a bug: The doc says that

> ruby hooks work without any system-level dependencies.

but in my tests I needed to install `ruby` and `gem` first in the official Python 3 docker image (which is based on Debian buster). These are the steps to reproduce it:

1. Run the `python:3` docker image (`docker` can be replaced with `podman`):
    ```bash
    docker run -it python:3 /bin/bash
    ```
2. Install `pre-commit`:
    ```bash
    pip install pre-commit
    ```
3. Create a fresh Git repository with a `.pre-commit-config.yaml` (in this case using the `mdl` linter):
    ```bash
    mkdir test
    cd test
    git init
    ```
    and the file `.pre-commit-config.yaml`:
    ```yaml
    repos:
    - repo: https://github.com/markdownlint/markdownlint
      rev: v0.11.0
      hooks:
      - id: markdownlint
    ```
4. Run `pre-commit`:
    ```bash
    pre-commit run --all-files
    ```

I get the following output:
```text
[INFO] Initializing environment for https://github.com/markdownlint/markdownlint.
[INFO] Installing environment for https://github.com/markdownlint/markdownlint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('gem', 'build', 'mdl.gemspec')
return code: 1
expected return code: 0
stdout:
    Executable `gem` not found
stderr: (none)
Check the log at /root/.cache/pre-commit/pre-commit.log
```

Log file:

### version information

```
pre-commit version: 2.13.0
sys.version:
    3.9.5 (default, May 12 2021, 15:26:36)
    [GCC 8.3.0]
sys.executable: /usr/local/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('gem', 'build', 'mdl.gemspec')
return code: 1
expected return code: 0
stdout:
    Executable `gem` not found
stderr: (none)
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/lib/python3.9/site-packages/pre_commit/main.py", line 385, in main
    return run(args.config, store, args)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/commands/run.py", line 408, in run
    install_hook_envs(to_install, store)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/usr/local/lib/python3.9/site-packages/pre_commit/languages/ruby.py", line 132, in install_environment
    helpers.run_setup_cmd(
  File "/usr/local/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('gem', 'build', 'mdl.gemspec')
return code: 1
expected return code: 0
stdout:
    Executable `gem` not found
stderr: (none)
```

**Comment by asottile** [comment]
yes, `ruby` defaults to using your system installation (for speed, and for windows), but you can use `language_version` to get a suitable interpreter otherwise

**Comment by IngoMeyer441** [comment]
Ah, thanks, I found it in the code as well: https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/ruby.py#L97

So I could put
```yaml
default_language_version:
  ruby: 2.7.3
```
at the top of the config file and it should just work?

**Comment by asottile** [comment]
yep! `2.7.2` might be ~slightly faster since there are [prebuilt binaries](http://rvm.io/binaries/ubuntu/20.04/x86_64/)

**Comment by IngoMeyer441** [comment]
Thanks for the tip! I can confirm that
```yaml
default_language_version:
  ruby: 2.7.2
repos:
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.11.0
  hooks:
  - id: markdownlint
```
works smoothly without any additional dependencies installed in the Docker container. Thanks for the quick help!
