### ISSUE TITLE
After Updating to pre-commit 2.13.0; CalledProcess Error and no py_env-python3

### ISSUE THREAD

**Issue by BenArtes** [pre-commit/pre-commit#1935]
I was pinned at 2.9.3 for a while because of some language: script / additional_dependency issues. Finally had time to try clearing the issue up and now can't seem to get pre-commit to work at all.

After updating, whenever I run `pre-commit run -a` I get:

```bash
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/terminus/.cache/pre-commit/repoxgho4gd8/py_env-python3')
return code: 1
expected return code: 0
stdout:
    StopIteration: 
    
stderr: (none)
Check the log at /home/terminus/.cache/pre-commit/pre-commit.log
```

LOG:
`
### version information

```
pre-commit version: 2.13.0
sys.version:
    3.6.9 (default, Jan 26 2021, 15:33:00) 
    [GCC 8.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/terminus/.cache/pre-commit/repoxgho4gd8/py_env-python3')
return code: 1
expected return code: 0
stdout:
    StopIteration: 
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "/home/terminus/.local/lib/python3.6/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/terminus/.local/lib/python3.6/site-packages/pre_commit/main.py", line 385, in main
    return run(args.config, store, args)
  File "/home/terminus/.local/lib/python3.6/site-packages/pre_commit/commands/run.py", line 408, in run
    install_hook_envs(to_install, store)
  File "/home/terminus/.local/lib/python3.6/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/home/terminus/.local/lib/python3.6/site-packages/pre_commit/repository.py", line 83, in _hook_install
    hook.prefix, hook.language_version, hook.additional_dependencies,
  File "/home/terminus/.local/lib/python3.6/site-packages/pre_commit/languages/python.py", line 202, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/home/terminus/.local/lib/python3.6/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/terminus/.cache/pre-commit/repoxgho4gd8/py_env-python3')
return code: 1
expected return code: 0
stdout:
    StopIteration: 
    
stderr: (none)
```
`

Looking in `/home/terminus/.cache/pre-commit/repoxgho4gd8/` (which is the installed pre-commit/pre-commit-hooks folder) I don't see what I imagine should be a folder called `py_env-python2`.

I've tried clearing the `.cache/pre-commit` folder and re-installing hoping the correct files get generated, and lots of other version shuffling (dowgrade virtualenv etc). 

This same setup, repository, and pre-commit-config.yaml files are used in a docker container that gets built nightly and is currently working, so it definitely seems like an issue with my system configuration, but I can't figure out what's causing it.

Other Info:
System: Ubuntu18.04
Installed via `pip3 install pre-commit`

**Comment by asottile** [comment]
that error is coming from `virtualenv` -- please report it upstream

**Comment by asottile** [comment]
by the way, you should be able to reproduce the same issue by running `/usr/bin/python3 -mvirtualenv somevenv` -- upstream is going to ask you to `--with-traceback` as well
