### ISSUE TITLE
Using mypy mirror, `pre-commit autoupdate` fails with `update target is missing these hooks`

### ISSUE THREAD

**Issue by danseely** [pre-commit/pre-commit#1945]
I can't find any other references to this issue that I'm seeing.

My config:

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit
    rev: v0.902
    hooks:
      - id: mypy
```

Attempting `pre-commit autoupdate`

```sh
$ pre-commit autoupdate   
Updating https://github.com/psf/black ... already up to date.
Updating https://github.com/pre-commit/pre-commit ... Cannot update because the update target is missing these hooks:
mypy
```

Attempting a commit

```
$ git commit -m "feat: test pre commit hook"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to <home-dir>/.cache/pre-commit/patch1624028680-83505.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit.
[INFO] Restored changes from <home-dir>/.cache/pre-commit/patch1624028680-83505.
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/Cellar/git/2.32.0/libexec/git-core/git', 'checkout', 'v0.902')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'v0.902' did not match any file(s) known to git

Check the log at <home-dir>/.cache/pre-commit/pre-commit.log
```

If I use a sha instead of a tag, I get the same error on `pre-commit autoupdate` and a slightly different error on a commit attempt

```
$ git commit -m "feat: test pre commit hook"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to <home-dir>/.cache/pre-commit/patch1624029168-83794.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit.
[INFO] Restored changes from <home-dir>/.cache/pre-commit/patch1624029168-83794.
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/Cellar/git/2.32.0/libexec/git-core/git', 'checkout', '8254732e2eec9747094eff37f7e3450e67eff349')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: reference is not a tree: 8254732e2eec9747094eff37f7e3450e67eff349

Check the log at <home-dir>/.cache/pre-commit/pre-commit.log
```

Here's a dump of the `pre-commit.log` file (I cleared it & re-attempted the commit)

```
### version information


pre-commit version: 2.13.0
sys.version:
    3.8.2 (default, Jun  8 2021, 13:48:06) 
    [Clang 12.0.5 (clang-1205.0.22.9)]
sys.executable: <my-path>/python/<my-repo>/.venv/bin/python
os.name: posix
sys.platform: darwin


### error information


An unexpected error has occurred: CalledProcessError: command: ('/usr/local/Cellar/git/2.32.0/libexec/git-core/git', 'checkout', 'v0.902')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'v0.902' did not match any file(s) known to git
    



Traceback (most recent call last):
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/store.py", line 183, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/store.py", line 165, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/store.py", line 180, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/Cellar/git/2.32.0/libexec/git-core/git', '-c', 'protocol.version=2', 'fetch', 'origin', 'v0.902', '--depth=1')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: couldn't find remote ref v0.902
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/main.py", line 357, in main
    return hook_impl(
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/commands/hook_impl.py", line 227, in hook_impl
    return retv | run(config, store, ns)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 395, in run
    for hook in all_hooks(config, store)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/repository.py", line 228, in all_hooks
    return tuple(
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/repository.py", line 231, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/repository.py", line 206, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/repository.py", line 172, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/store.py", line 187, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/store.py", line 144, in _new_repo
    make_strategy(directory)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/store.py", line 185, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/store.py", line 158, in _complete_clone
    git_cmd('checkout', ref)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/store.py", line 180, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "<my-path>/python/<my-repo>/.venv/lib/python3.8/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/Cellar/git/2.32.0/libexec/git-core/git', 'checkout', 'v0.902')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'v0.902' did not match any file(s) known to git
```

**Comment by asottile** [comment]
you've written this:

```
  - repo: https://github.com/pre-commit/pre-commit
```

**Comment by danseely** [comment]
@asottile 🤦‍♂️  thanks!
