### ISSUE TITLE
error while trying to run pre-commit

### ISSUE THREAD

**Issue by rock420** [pre-commit/pre-commit#1967]
Hi, I am facing some errors while running pre-commit hooks. I am new to pre-commit and not getting why it is going wrong.

### version information
```
pre-commit version: 2.12.1
sys.version:
    3.9.5 (default, May 18 2021, 19:34:48) 
    [GCC 7.3.0]
sys.executable: /home/ayan/anaconda3/envs/bugbug/bin/python
os.name: posix
sys.platform: linux
```

### cmd output
```
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/ayan/.cache/pre-commit/repol0_4qe6i/node_env-default/bin/node', '/home/ayan/.cache/pre-commit/repol0_4qe6i/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
    npm ERR! obj[key].join is not a function
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/ayan/.npm/_logs/2021-07-03T09_31_30_656Z-debug.log
    
```

### error information
```
Traceback (most recent call last):
  File "/home/ayan/anaconda3/envs/bugbug/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/ayan/anaconda3/envs/bugbug/lib/python3.9/site-packages/pre_commit/main.py", line 385, in main
    return run(args.config, store, args)
  File "/home/ayan/anaconda3/envs/bugbug/lib/python3.9/site-packages/pre_commit/commands/run.py", line 408, in run
    install_hook_envs(to_install, store)
  File "/home/ayan/anaconda3/envs/bugbug/lib/python3.9/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/home/ayan/anaconda3/envs/bugbug/lib/python3.9/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/home/ayan/anaconda3/envs/bugbug/lib/python3.9/site-packages/pre_commit/languages/node.py", line 107, in install_environment
    helpers.run_setup_cmd(prefix, local_install_cmd)
  File "/home/ayan/anaconda3/envs/bugbug/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir)
  File "/home/ayan/anaconda3/envs/bugbug/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/ayan/.cache/pre-commit/repol0_4qe6i/node_env-default/bin/node', '/home/ayan/.cache/pre-commit/repol0_4qe6i/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
    npm ERR! obj[key].join is not a function
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/ayan/.npm/_logs/2021-07-03T09_31_30_656Z-debug.log
```

**Comment by asottile** [comment]
looks like a bug with npm itself (check the npm log and report it to them)
