### ISSUE TITLE
Pre-commit don't work with Gitpod and Pipenv

### ISSUE THREAD

**Issue by jefer94** [pre-commit/pre-commit#1985]
```bash
[INFO] Restored changes from /home/gitpod/.cache/pre-commit/patch1626779319-12649.
An unexpected error has occurred: CalledProcessError: command: ('/home/gitpod/.cache/pre-commit/reponkw94t64/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
    
Check the log at /home/gitpod/.cache/pre-commit/pre-commit.log
```

```log
### version information

pre-commit version: 2.13.0
sys.version:
    3.9.6 (default, Jul  3 2021, 16:40:50) 
    [GCC 9.3.0]
sys.executable: /workspace/apiv2/.venv/bin/python
os.name: posix
sys.platform: linux

### error information

An unexpected error has occurred: CalledProcessError: command: ('/home/gitpod/.cache/pre-commit/reponkw94t64/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
    
Traceback (most recent call last):
  File "/workspace/apiv2/.venv/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/workspace/apiv2/.venv/lib/python3.9/site-packages/pre_commit/main.py", line 385, in main
    return run(args.config, store, args)
  File "/workspace/apiv2/.venv/lib/python3.9/site-packages/pre_commit/commands/run.py", line 408, in run
    install_hook_envs(to_install, store)
  File "/workspace/apiv2/.venv/lib/python3.9/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/workspace/apiv2/.venv/lib/python3.9/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/workspace/apiv2/.venv/lib/python3.9/site-packages/pre_commit/languages/python.py", line 204, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/workspace/apiv2/.venv/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir)
  File "/workspace/apiv2/.venv/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/gitpod/.cache/pre-commit/reponkw94t64/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

**Comment by asottile** [comment]
it should work fine, but I suspect a bad `pip` configuration -- try the triage in this issue: https://github.com/pre-commit/pre-commit/issues/1420

**Comment by jefer94** [comment]
Maybe, but i can't find that `pip.conf`, gitpod is like a visual studio mount inside a docker and it run online, it mount a lot of configurations like pyenv, if the error is a `pip.conf` y should path the docker image to solve this issue

```bash
gitpod /workspace/apiv2 $ cat /etc/pip.conf
cat: /etc/pip.conf: No such file or directory

gitpod /workspace/apiv2 $ cat ~/.pip.conf
cat: /home/gitpod/.pip.conf: No such file or directory

gitpod /workspace/apiv2 $ which pip 
/home/gitpod/.pyenv/shims/pip

gitpod /workspace/apiv2 $ echo $PATH
/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/workspace/.cargo/bin:/workspace/.pip-modules/bin:/workspace/.rvm/bin:/home/gitpod/.sdkman/candidates/maven/current/bin:/home/gitpod/.sdkman/candidates/java/current/bin:/home/gitpod/.sdkman/candidates/gradle/current/bin:/home/gitpod/.rvm/gems/ruby-2.7.3/bin:/home/gitpod/.rvm/gems/ruby-2.7.3@global/bin:/home/gitpod/.rvm/rubies/ruby-2.7.3/bin:/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/workspace/.cargo/bin:/workspace/.pip-modules/bin:/workspace/.rvm/bin:/ide/bin:/home/gitpod/.pyenv/bin:/home/gitpod/.pyenv/shims:/workspace/go/bin:/home/gitpod/go/bin:/home/gitpod/go-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:/home/gitpod/.nvm/versions/node/v14.17.3/bin:/home/gitpod/.cargo/bin:/usr/games:/usr/games:/usr/lib/postgresql/12/bin:/home/gitpod/.pg_ctl/bin:/home/gitpod/.nvm/versions/node/v14.17.3/bin:/home/gitpod/.rvm/bin:/home/gitpod/.nvm/versions/node/v14.17.3/bin:/home/gitpod/.nvm/versions/node/v14.17.3/bin
```

**Comment by asottile** [comment]
try `pip config --list`? something is misconfiguring pip somewhere

**Comment by jefer94** [comment]
The output show it, the difference with the configs in my local machine is `:env:.user='yes'` i think i should try to remove it

```bash
gitpod /workspace/apiv2 $ pip config --list

Usage:   
  pip config [<file-option>] list
  pip config [<file-option>] [--editor <editor-path>] edit
  
  pip config [<file-option>] get name
  pip config [<file-option>] set name value
  pip config [<file-option>] unset name
  pip config [<file-option>] debug
  

no such option: --list

gitpod /workspace/apiv2 $ pip config list
:env:.user='yes'

gitpod /workspace/apiv2 $ pipenv shell
Loading .env environment variables...
Launching subshell in virtual environment...
 . /workspace/apiv2/.venv/bin/activate

gitpod /workspace/apiv2 $  . /workspace/apiv2/.venv/bin/activate

(apiv2) gitpod /workspace/apiv2 $ pip config list
:env:.disable-pip-version-check='1'
:env:.python-path='/home/gitpod/.pyenv/versions/3.8.11/bin/python3'
:env:.user='yes'
```

**Comment by asottile** [comment]
then you have an errant environment variable, probably `PIP_USER=1` or something of the sort (as I suggested [here](https://github.com/pre-commit/pre-commit/issues/1420#issuecomment-621264179))

**Comment by jefer94** [comment]
The solution was add to the end of gitpod dockerfile this line to remove the `PIP_USER=yes`

```dockerfile
FROM gitpod/workspace-postgres

RUN sudo apt-get update \
    && sudo apt-get update \
    && sudo apt-get install -y redis-server \
    && sudo apt-get clean \
    && sudo rm -rf /var/cache/apt/* /var/lib/apt/lists/* /tmp/*

RUN pyenv update && pyenv install 3.9.6 && pyenv global 3.9.6
RUN pip install pipenv

# remove PIP_USER environment
USER gitpod
RUN if ! grep -q "export PIP_USER=no" "$HOME/.bashrc"; then printf '%s\n' "export PIP_USER=no" >> "$HOME/.bashrc"; fi
```

**Comment by asottile** [comment]
you can probably use `/etc/environment` as well -- though I would recommend reporting the issue to gitpod since `PIP_USER=1` is a very bad default
