### ISSUE TITLE
ValueError: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by Ezra-Yu** [pre-commit/pre-commit#1987]
(base) SENSETIME\yuzhaohui@cn0614008791l:~/mmcls-collections/docker$ pre-commit run --all-files
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.git.
[INFO] Initializing environment for https://github.com/asottile/seed-isort-config.
[INFO] Initializing environment for https://github.com/timothycrosley/isort.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-yapf.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/jumanjihouse/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/myint/docformatter.
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/bin/python', '-mpip', 'install', '.')
return code: 2
expected return code: 0
stdout:
    Processing /home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa
    
stderr:
      DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
       pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    ERROR: Exception:
    Traceback (most recent call last):
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
        status = self.run(options, args)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
        return func(self, options, args)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 319, in run
        reqs, check_supported_wheels=not options.target_dir
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 128, in resolve
        requirements, max_rounds=try_to_avoid_resolution_too_deep
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
        state = resolution.resolve(requirements, max_rounds=max_rounds)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 367, in resolve
        failure_causes = self._attempt_to_pin_criterion(name)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
        criteria = self._get_criteria_to_update(candidate)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 203, in _get_criteria_to_update
        name, crit = self._merge_into_criterion(r, parent=candidate)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _merge_into_criterion
        if not criterion.candidates:
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 139, in __bool__
        return bool(self._sequence)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
        return any(self)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 129, in <genexpr>
        return (c for c in iterator if id(c) not in self._incompatible_ids)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 30, in _iter_built
        for version, func in infos:
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 272, in iter_index_candidate_infos
        hashes=hashes,
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 879, in find_best_candidate
        candidates = self.find_all_candidates(project_name)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 824, in find_all_candidates
        page_candidates = list(page_candidates_it)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index/sources.py", line 134, in page_candidates
        yield from self._candidates_from_page(self._link)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 783, in process_project_url
        html_page = self._link_collector.fetch_page(project_url)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 512, in fetch_page
        return _get_html_page(location, session=self.session)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 422, in _get_html_page
        resp = _get_html_response(url, session=session)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 137, in _get_html_response
        "Cache-Control": "max-age=0",
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 555, in get
        return self.request('GET', url, **kwargs)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_internal/network/session.py", line 449, in request
        return super().request(method, url, *args, **kwargs)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 53, in send
        resp = super(CacheControlAdapter, self).send(request, **kw)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 696, in urlopen
        self._prepare_proxy(conn)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 964, in _prepare_proxy
        conn.connect()
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 359, in connect
        conn = self._connect_tls_proxy(hostname, conn)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 506, in _connect_tls_proxy
        ssl_context=ssl_context,
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 432, in ssl_wrap_socket
        ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
      File "/home/SENSETIME/yuzhaohui/.cache/pre-commit/repoh9lh97wa/py_env-python3.7/lib/python3.7/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 474, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock)
      File "/home/SENSETIME/yuzhaohui/anaconda3/lib/python3.7/ssl.py", line 423, in wrap_socket
        session=session
      File "/home/SENSETIME/yuzhaohui/anaconda3/lib/python3.7/ssl.py", line 827, in _create
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname
    
Check the log at /home/SENSETIME/yuzhaohui/.cache/pre-commit/pre-commit.log

**Comment by Ezra-Yu** [comment]
when I run pre-commit, get this error.
the pip in my base conda envirment is OK.

**Comment by asottile** [comment]
your ssl module is broken

**Comment by Ezra-Yu** [comment]
How can I slove it?

**Comment by asottile** [comment]
I don't know, but it's not a problem with pre-commit so unfortunately I can't provide free support to diagnose your broken environment

**Comment by Ezra-Yu** [comment]
Yesterday, the pre-commit work fine, And I remove some dirs in .cache. then it become this way.
I have reinstall my python, But it still exist.

i see it breaks when running pip, but i can install any package using pip fine in my own base environment.
