### ISSUE TITLE
Problems with local `pre_commit_hooks` dir

### ISSUE THREAD

**Issue by MaxymVlasov** [pre-commit/pre-commit#2018]
Hi, I try to run pre-commit hooks but got unusual errors.

Looks like [`pre-commit`](https://github.com/pre-commit/pre-commit) try to solve internal deps in the local `pre_commit_hooks` folder than check hooks from [`pre-commit/pre-commit-hooks`](https://github.com/pre-commit/pre-commit-hooks) default system location

## System details
* [`.pre-commit-config.yaml` here](https://github.com/antonbabenko/pre-commit-terraform/blob/c7d6d002ed510c1a3e63af6d0e132e8abf2448d4/.pre-commit-config.yaml)
* OS: Win10 with Ubuntu 20.04 on WSL2 (`uname -a`: `Linux DESKTOP-C7315EF 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* python version (default distr): 3.8.5
* pre-commit version: 2.14.0. Installed via [`asdf`](https://github.com/asdf-vm/asdf)
* PATH: `/home/vm/.asdf/shims:/home/vm/.asdf/bin:/home/vm/.local/bin:/home/vm/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/home/vm/.fzf/bin:/usr/local/go/bin`

On macOS (`pre-commit` installed by `brew`) all works fine. If I rename `pre_commit_hooks` dir - problem gone too. 

In not sure is it bug, or feature request like "please,check default hooks location if it not found in local `pre_commit_hooks`"

<details><summary><h2><code>pre-commit run --all</code> output</h2> </summary>

```bash
➜ pre-commit run --all             
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/jumanjihouse/pre-commit-hooks.
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-yaml", line 5, in <module>
    from pre_commit_hooks.check_yaml import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_yaml'

Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1

Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/end-of-file-fixer", line 5, in <module>
    from pre_commit_hooks.end_of_file_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.end_of_file_fixer'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/end-of-file-fixer", line 5, in <module>
    from pre_commit_hooks.end_of_file_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.end_of_file_fixer'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/end-of-file-fixer", line 5, in <module>
    from pre_commit_hooks.end_of_file_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.end_of_file_fixer'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/end-of-file-fixer", line 5, in <module>
    from pre_commit_hooks.end_of_file_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.end_of_file_fixer'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/end-of-file-fixer", line 5, in <module>
    from pre_commit_hooks.end_of_file_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.end_of_file_fixer'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/end-of-file-fixer", line 5, in <module>
    from pre_commit_hooks.end_of_file_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.end_of_file_fixer'

Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1

Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/trailing-whitespace-fixer", line 5, in <module>
    from pre_commit_hooks.trailing_whitespace_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.trailing_whitespace_fixer'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/trailing-whitespace-fixer", line 5, in <module>
    from pre_commit_hooks.trailing_whitespace_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.trailing_whitespace_fixer'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/trailing-whitespace-fixer", line 5, in <module>
    from pre_commit_hooks.trailing_whitespace_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.trailing_whitespace_fixer'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/trailing-whitespace-fixer", line 5, in <module>
    from pre_commit_hooks.trailing_whitespace_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.trailing_whitespace_fixer'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/trailing-whitespace-fixer", line 5, in <module>
    from pre_commit_hooks.trailing_whitespace_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.trailing_whitespace_fixer'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/trailing-whitespace-fixer", line 5, in <module>
    from pre_commit_hooks.trailing_whitespace_fixer import main
ModuleNotFoundError: No module named 'pre_commit_hooks.trailing_whitespace_fixer'

Check for case conflicts.................................................Failed
- hook id: check-case-conflict
- exit code: 1

Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-case-conflict", line 5, in <module>
    from pre_commit_hooks.check_case_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_case_conflict'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-case-conflict", line 5, in <module>
    from pre_commit_hooks.check_case_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_case_conflict'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-case-conflict", line 5, in <module>
    from pre_commit_hooks.check_case_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_case_conflict'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-case-conflict", line 5, in <module>
    from pre_commit_hooks.check_case_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_case_conflict'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-case-conflict", line 5, in <module>
    from pre_commit_hooks.check_case_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_case_conflict'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-case-conflict", line 5, in <module>
    from pre_commit_hooks.check_case_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_case_conflict'

Check for merge conflicts................................................Failed
- hook id: check-merge-conflict
- exit code: 1

Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-merge-conflict", line 5, in <module>
    from pre_commit_hooks.check_merge_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_merge_conflict'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-merge-conflict", line 5, in <module>
    from pre_commit_hooks.check_merge_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_merge_conflict'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-merge-conflict", line 5, in <module>
    from pre_commit_hooks.check_merge_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_merge_conflict'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-merge-conflict", line 5, in <module>
    from pre_commit_hooks.check_merge_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_merge_conflict'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-merge-conflict", line 5, in <module>
    from pre_commit_hooks.check_merge_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_merge_conflict'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-merge-conflict", line 5, in <module>
    from pre_commit_hooks.check_merge_conflict import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_merge_conflict'

Check that executables have shebangs.....................................Failed
- hook id: check-executables-have-shebangs
- exit code: 1

Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-executables-have-shebangs", line 5, in <module>
    from pre_commit_hooks.check_executables_have_shebangs import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_executables_have_shebangs'
Traceback (most recent call last):
  File "/home/vm/.cache/pre-commit/repoqpq0_bj7/py_env-python3.8/bin/check-executables-have-shebangs", line 5, in <module>
    from pre_commit_hooks.check_executables_have_shebangs import main
ModuleNotFoundError: No module named 'pre_commit_hooks.check_executables_have_shebangs'

Check shell style with shfmt.............................................Passed
```
</details>

## Steps to reproduce

```bash 
git clone git@github.com:antonbabenko/pre-commit-terraform.git
cd pre-commit-terraform
git checkout c7d6d002ed510c1a3e63af6d0e132e8abf2448d4 # latest commit in master when I open this issue
pre-commit run --all
```

**Comment by asottile** [comment]
pre-commit/pre-commit-hooks has ["the rights"](https://pypi.org/p/pre-commit-hooks) to the `pre_commit_hooks` namespace -- anything else should use a different namespace

you should rename your module since you are infringing on that namespace
