### ISSUE TITLE
Crash when /tmp is on a different device

### ISSUE THREAD

**Issue by campaul** [pre-commit/pre-commit#203]
```
Traceback (most recent call last):
  File "/home/cameron/Workspace/hack16-llvm-lang/venv/bin/pre-commit", line 9, in <module>
    load_entry_point('pre-commit==0.4.0', 'console_scripts', 'pre-commit')()
  File "/home/cameron/Workspace/hack16-llvm-lang/venv/lib/python3.4/site-packages/pre_commit/main.py", line 136, in main
    'Command {0} failed to exit with a returncode'.format(args.command)
  File "/usr/lib64/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/cameron/Workspace/hack16-llvm-lang/venv/lib/python3.4/site-packages/pre_commit/error_handler.py", line 41, in error_handler
    traceback.format_exc(),
  File "/home/cameron/Workspace/hack16-llvm-lang/venv/lib/python3.4/site-packages/pre_commit/error_handler.py", line 24, in _log_and_exit
    store.require_created()
  File "/home/cameron/Workspace/hack16-llvm-lang/venv/lib/python3.4/site-packages/pre_commit/store.py", line 97, in require_created
    self._create()
  File "/home/cameron/Workspace/hack16-llvm-lang/venv/lib/python3.4/site-packages/pre_commit/store.py", line 90, in _create
    self._write_sqlite_db()
  File "/home/cameron/Workspace/hack16-llvm-lang/venv/lib/python3.4/site-packages/pre_commit/store.py", line 82, in _write_sqlite_db
    os.rename(tmpfile, self.db_path)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpz1pkyqsm' -> '/home/cameron/.pre-commit/db.db'
```

**Comment by asottile** [comment]
Seems your tempfs is on a different device and os.rename derps on that.  Thanks python!  Should be easy enough to fix :)
