### ISSUE TITLE
Pre-commit giving error when initialising

### ISSUE THREAD

**Issue by Divkix** [pre-commit/pre-commit#2037]
### version information

```
pre-commit version: 2.14.1
sys.version:
    3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
sys.executable: C:\Users\Divkix\Envs\Alita_Robot-main\Scripts\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Divkix\\.cache\\pre-commit\\repo6ntlzin2\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\users\divkix\.cache\pre-commit\repo6ntlzin2
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'error'
    
stderr:
      DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
       pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
        ERROR: Command errored out with exit status 1:
         command: 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\Scripts\python.EXE' 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Divkix\AppData\Local\Temp\tmpo0qtjsj5'
             cwd: C:\Users\Divkix\AppData\Local\Temp\pip-req-build-q9cfalap
        Complete output (46 lines):
        C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\git.py:88: UserWarning: "C:\Users\Divkix\AppData\Local\Temp\pip-req-build-q9cfalap" is shallow and may cause errors
          warnings.warn(f'"{wd.path}" is shallow and may cause errors')
        Traceback (most recent call last):
          File "C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
            main()
          File "C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 151, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\build_meta.py", line 166, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 48, in <module>
            setup(
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
          File "C:\Users\Divkix\scoop\apps\python\3.9.7\lib\distutils\core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\dist.py", line 455, in __init__
            _Distribution.__init__(self, {
          File "C:\Users\Divkix\scoop\apps\python\3.9.7\lib\distutils\dist.py", line 292, in __init__
            self.finalize_options()
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\dist.py", line 807, in finalize_options
            ep(self)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\dist.py", line 814, in _finalize_setup_keywords
            ep.load()(self, ep.name, value)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\integration.py", line 24, in version_keyword
            dist.metadata.version = _get_version(config)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 173, in _get_version
            parsed_version = _do_parse(config)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 127, in _do_parse
            version = _version_from_entrypoints(config) or _version_from_entrypoints(
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 65, in _version_from_entrypoints
            version = _call_entrypoint_fn(root, config, ep.load())
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 46, in _call_entrypoint_fn
            return fn(root, config=config)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\git.py", line 127, in parse
            node_date = wd.get_head_date() or date.today()
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\git.py", line 67, in get_head_date
            return datetime.strptime(date_part, r"%Y-%m-%d").date()
          File "C:\Users\Divkix\scoop\apps\python\3.9.7\lib\_strptime.py", line 568, in _strptime_datetime
            tt, fraction, gmtoff_fraction = _strptime(data_string, format)
          File "C:\Users\Divkix\scoop\apps\python\3.9.7\lib\_strptime.py", line 349, in _strptime
            raise ValueError("time data %r does not match format %r" %
        ValueError: time data 'gpg: Signature made Mon May 31 19:55:54 2021 IS' does not match format '%Y-%m-%d'
        ----------------------------------------
    WARNING: Discarding file:///C:/Users/Divkix/.cache/pre-commit/repo6ntlzin2. Command errored out with exit status 1: 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\Scripts\python.EXE' 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Divkix\AppData\Local\Temp\tmpo0qtjsj5' Check the logs for full command output.
    ERROR: Command errored out with exit status 1: 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\Scripts\python.EXE' 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Divkix\AppData\Local\Temp\tmpo0qtjsj5' Check the logs for full command output.
    
```

```
Traceback (most recent call last):
  File "C:\Users\Divkix\Envs\Alita_Robot-main\lib\site-packages\pre_commit\error_handler.py", line 65, in error_handler
    yield
  File "C:\Users\Divkix\Envs\Alita_Robot-main\lib\site-packages\pre_commit\main.py", line 388, in main
    return run(args.config, store, args)
  File "C:\Users\Divkix\Envs\Alita_Robot-main\lib\site-packages\pre_commit\commands\run.py", line 412, in run
    install_hook_envs(to_install, store)
  File "C:\Users\Divkix\Envs\Alita_Robot-main\lib\site-packages\pre_commit\repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\Divkix\Envs\Alita_Robot-main\lib\site-packages\pre_commit\repository.py", line 82, in _hook_install
    lang.install_environment(
  File "C:\Users\Divkix\Envs\Alita_Robot-main\lib\site-packages\pre_commit\languages\python.py", line 204, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "C:\Users\Divkix\Envs\Alita_Robot-main\lib\site-packages\pre_commit\languages\helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir)
  File "C:\Users\Divkix\Envs\Alita_Robot-main\lib\site-packages\pre_commit\util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\Divkix\\.cache\\pre-commit\\repo6ntlzin2\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\users\divkix\.cache\pre-commit\repo6ntlzin2
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'error'
    
stderr:
      DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
       pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
        ERROR: Command errored out with exit status 1:
         command: 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\Scripts\python.EXE' 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Divkix\AppData\Local\Temp\tmpo0qtjsj5'
             cwd: C:\Users\Divkix\AppData\Local\Temp\pip-req-build-q9cfalap
        Complete output (46 lines):
        C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\git.py:88: UserWarning: "C:\Users\Divkix\AppData\Local\Temp\pip-req-build-q9cfalap" is shallow and may cause errors
          warnings.warn(f'"{wd.path}" is shallow and may cause errors')
        Traceback (most recent call last):
          File "C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
            main()
          File "C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 151, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\build_meta.py", line 166, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 48, in <module>
            setup(
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
          File "C:\Users\Divkix\scoop\apps\python\3.9.7\lib\distutils\core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\dist.py", line 455, in __init__
            _Distribution.__init__(self, {
          File "C:\Users\Divkix\scoop\apps\python\3.9.7\lib\distutils\dist.py", line 292, in __init__
            self.finalize_options()
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\dist.py", line 807, in finalize_options
            ep(self)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools\dist.py", line 814, in _finalize_setup_keywords
            ep.load()(self, ep.name, value)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\integration.py", line 24, in version_keyword
            dist.metadata.version = _get_version(config)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 173, in _get_version
            parsed_version = _do_parse(config)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 127, in _do_parse
            version = _version_from_entrypoints(config) or _version_from_entrypoints(
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 65, in _version_from_entrypoints
            version = _call_entrypoint_fn(root, config, ep.load())
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 46, in _call_entrypoint_fn
            return fn(root, config=config)
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\git.py", line 127, in parse
            node_date = wd.get_head_date() or date.today()
          File "C:\Users\Divkix\AppData\Local\Temp\pip-build-env-18sw899g\overlay\Lib\site-packages\setuptools_scm\git.py", line 67, in get_head_date
            return datetime.strptime(date_part, r"%Y-%m-%d").date()
          File "C:\Users\Divkix\scoop\apps\python\3.9.7\lib\_strptime.py", line 568, in _strptime_datetime
            tt, fraction, gmtoff_fraction = _strptime(data_string, format)
          File "C:\Users\Divkix\scoop\apps\python\3.9.7\lib\_strptime.py", line 349, in _strptime
            raise ValueError("time data %r does not match format %r" %
        ValueError: time data 'gpg: Signature made Mon May 31 19:55:54 2021 IS' does not match format '%Y-%m-%d'
        ----------------------------------------
    WARNING: Discarding file:///C:/Users/Divkix/.cache/pre-commit/repo6ntlzin2. Command errored out with exit status 1: 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\Scripts\python.EXE' 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Divkix\AppData\Local\Temp\tmpo0qtjsj5' Check the logs for full command output.
    ERROR: Command errored out with exit status 1: 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\Scripts\python.EXE' 'C:\Users\Divkix\.cache\pre-commit\repo6ntlzin2\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Divkix\AppData\Local\Temp\tmpo0qtjsj5' Check the logs for full command output.
```

**Comment by Divkix** [comment]
Only facing this when using https://github.com/psf/black

**Comment by asottile** [comment]
please report this to setuptools-scm
