### ISSUE TITLE
Dead lock with pika library

### ISSUE THREAD

**Issue by LorhanSohaky** [pre-commit/pre-commit#2048]
### describe your issue

In a project with [pika library](https://pypi.org/project/pika/) the pylint goes into dead lock state.

### pre-commit --version

pre-commit version: 2.13.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ['--errors-only', '--rcfile', '.pylintrc']
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
Interrupted (^C): KeyboardInterrupt: 
```

```
Traceback (most recent call last):
  File "/home/user/project/venv/lib/python3.8/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/user/project/venv/lib/python3.8/site-packages/pre_commit/main.py", line 385, in main
    return run(args.config, store, args)
  File "/home/user/project/venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 410, in run
    return _run_hooks(config, hooks, skips, args, environ)
  File "/home/user/project/venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 286, in _run_hooks
    current_retval, prior_diff = _run_single_hook(
  File "/home/user/project/venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 194, in _run_single_hook
    retcode, out = language.run_hook(hook, filenames, use_color)
  File "/home/user/project/venv/lib/python3.8/site-packages/pre_commit/languages/system.py", line 19, in run_hook
    return helpers.run_xargs(hook, hook.cmd, file_args, color=color)
  File "/home/user/project/venv/lib/python3.8/site-packages/pre_commit/languages/helpers.py", line 136, in run_xargs
    return xargs(cmd, file_args, **kwargs)
  File "/home/user/project/venv/lib/python3.8/site-packages/pre_commit/xargs.py", line 165, in xargs
    for proc_retcode, proc_out, _ in results:
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    self._condition.wait(timeout)
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

### Configuration

```ini
[MASTER]
init-hook='import sys; sys.path.append(".")'
load-plugins=pylint_pytest
extension-pkg-whitelist=pydantic
```

### Pylint version

```shell
pylint 2.9.6
astroid 2.6.6
Python 3.8.10 (default, May 25 2021, 17:15:44) 
[GCC 10.2.0]
```

### OS / Environment

Manjaro

### Additional dependencies

pika==1.2.0

**Comment by asottile** [comment]
this is not a bug with pre-commit, please report it upstream

**Comment by LorhanSohaky** [comment]
@asottile , upstream?

**Comment by asottile** [comment]
pre-commit just calls tools, whatever tool you're calling is deadlocking not pre-commit -- report your bug to that tool

**Comment by asottile** [comment]
also in the future, please follow the issue template exactly -- it has prompts for a reason and you've bypassed them
