### ISSUE TITLE
Possible dead lock

### ISSUE THREAD

**Issue by LorhanSohaky** [pre-commit/pre-commit#2049]
### describe your issue

@asottile, I reported on pylint, but it doesn't seem to be a problem there. When I run manually it works.
Here the [issue](https://github.com/PyCQA/pylint/issues/4918).

When I run on command line
```shel
> pylint --rcfile .pylintrc --errors-only .
> echo $status
0
```

When I run on pre-commit
```shell
> pre-commit run --all-files
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
flake8...................................................................Passed
isort....................................................................Passed
pylint...................................................................

```

### pre-commit --version

pre-commit version: 2.13.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ['--errors-only', '--rcfile', '.pylintrc']
```

### version information

```
pre-commit version: 2.13.0
sys.version:
    3.8.10 (default, May 25 2021, 17:15:44) 
    [GCC 10.2.0]
sys.executable: /home/user/repo/venv/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
Interrupted (^C): KeyboardInterrupt: 
```

```
Traceback (most recent call last):
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/xargs.py", line 114, in _thread_mapper
    yield ex.map
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/xargs.py", line 165, in xargs
    for proc_retcode, proc_out, _ in results:
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    self._condition.wait(timeout)
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/main.py", line 385, in main
    return run(args.config, store, args)
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 410, in run
    return _run_hooks(config, hooks, skips, args, environ)
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 286, in _run_hooks
    current_retval, prior_diff = _run_single_hook(
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 194, in _run_single_hook
    retcode, out = language.run_hook(hook, filenames, use_color)
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/languages/system.py", line 19, in run_hook
    return helpers.run_xargs(hook, hook.cmd, file_args, color=color)
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/languages/helpers.py", line 136, in run_xargs
    return xargs(cmd, file_args, **kwargs)
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/xargs.py", line 167, in xargs
    stdout += proc_out
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/repo/venv/lib/python3.8/site-packages/pre_commit/xargs.py", line 114, in _thread_mapper
    yield ex.map
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/concurrent/futures/_base.py", line 644, in __exit__
    self.shutdown(wait=True)
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/concurrent/futures/thread.py", line 236, in shutdown
    t.join()
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/user/.asdf/installs/python/3.8.10/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by asottile** [comment]
`pylint .` is not the command it's running

the ~rough equivalent command is something like `pylint $(git ls-files -- '*.py')` or `git ls-files -- '*.py' | xargs -P $(nproc) pylint`

 we are not a debugging service please do not reopen another issue.  `language: system` is "at your own support"
