### ISSUE TITLE
Adding tox stalls pre-commit

### ISSUE THREAD

**Issue by JulianOrteil** [pre-commit/pre-commit#2069]
### describe your issue

Messing around with pre-commit lead me down the rabbit hole of adding my own hooks to the utility. Following the documentation [here](https://pre-commit.com/#new-hooks) and using the `.pre-commit-hooks.yaml` file located in your sister `pre-commit-hooks` repo, I constructed my own `.pre-commit-hooks.yaml` file for the tox repository.

Because all of my testing configurations are within the `tox.ini` file, I thought it would be a relatively simple task to incorporate it as another hook to run since I just need pre-commit to call `tox`. But, this was not the case. I successfully configured a `.pre-commit-hooks.yaml` file for tox and I am able to get it to run. I can see that it runs, because I am also using `pytest-cov`, `pytest-xdist` and `pytest-qt` with pytest (executed by tox) and temporary files associated with those plugins are created. However, pre-commit never seems to move on from the tox call.

**tox.ini**:
```ini
# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

# pytest-qt is likely to fail after installation due to library files missing
# or are otherwise misplaced. Before running any tox command below, it is
# recommended to first run `sudo apt-get install --reinstall libxcb-xinerama0`
# to (re)install these missing library files.

[tox]
envlist = py39
skipsdist=True

[testenv]
deps =
    -r envs/development.txt
    pytest
passenv = *
commands =
    pytest tests --cov-report xml:coverage.xml --cov -vv -l -s -n auto
changedir = {toxinidir}

[flake8]
max-line-length = 100
```

**.pre-commit-hooks.yaml** (in the tox repo in .cache/<tox_with_random_repo_name>):
```yaml
-   id: tox
    name: tox
    description: Run `tox` against the current working directory.
    entry: tox
    pass_filenames: false
    language: python
    require_serial: true

```

Any help with this would be appreciated! :)

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/tox-dev/tox
    rev: 3.23.1
    hooks:
    -   id: tox
        name: tox
        entry: tox
        verbose: true
        pass_filenames: false
        description: Automated tests using tox
```

### version information

```
pre-commit version: 2.15.0
sys.version:
    3.9.7 (default, Sep 16 2021, 13:09:58) 
    [GCC 7.5.0]
sys.executable: /media/mypc/DevDrive/linux_envs/app/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
Interrupted (^C): KeyboardInterrupt: 
```

```
Traceback (most recent call last):
  File "/media/mypc/DevDrive/linux_envs/appapp/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/media/mypc/DevDrive/linux_envs/app/lib/python3.9/site-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/media/mypc/DevDrive/linux_envs/app/lib/python3.9/site-packages/pre_commit/commands/run.py", line 419, in run
    return _run_hooks(config, hooks, skips, args, environ)
  File "/media/mypc/DevDrive/linux_envs/app/lib/python3.9/site-packages/pre_commit/commands/run.py", line 288, in _run_hooks
    current_retval, prior_diff = _run_single_hook(
  File "/media/mypc/DevDrive/linux_envs/app/lib/python3.9/site-packages/pre_commit/commands/run.py", line 194, in _run_single_hook
    retcode, out = language.run_hook(hook, filenames, use_color)
  File "/media/mypc/DevDrive/linux_envs/app/lib/python3.9/site-packages/pre_commit/languages/python.py", line 214, in run_hook
    return helpers.run_xargs(hook, hook.cmd, file_args, color=color)
  File "/media/mypc/DevDrive/linux_envs/app/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 136, in run_xargs
    return xargs(cmd, file_args, **kwargs)
  File "/media/mypc/DevDrive/linux_envs/app/lib/python3.9/site-packages/pre_commit/xargs.py", line 165, in xargs
    for proc_retcode, proc_out, _ in results:
  File "/media/mypc/DevDrive/linux_envs/app/lib/python3.9/site-packages/pre_commit/xargs.py", line 157, in run_cmd_partition
    return cmd_fn(
  File "/media/mypc/DevDrive/linux_envs/app/lib/python3.9/site-packages/pre_commit/util.py", line 232, in cmd_output_p
    bts = os.read(pty.r, 4096)
KeyboardInterrupt
```

**Comment by JulianOrteil** [comment]
These tests take a maximum of 30-45 seconds to complete. The `KeyboardInterrupt` was issued after 5 minutes of no movement.

**Comment by asottile** [comment]
it doesn't make sense to have `tox` as a pre-commit hook -- they should be fast checks

your configuration also doesn't work, there's no `.pre-commit-hooks.yaml` in tox-dev/tox@3.23.1:

```console
$ pre-commit  run --all-files
[INFO] Initializing environment for https://github.com/tox-dev/tox.
An error has occurred: InvalidManifestError: 
=====> /home/asottile/.cache/pre-commit/repoi3rjq0vb/.pre-commit-hooks.yaml is not a file
Check the log at /home/asottile/.cache/pre-commit/pre-commit.log
```

that said, if you put your `.pre-commit-hooks.yaml` in tox, it does work:

```console
$ TOXENV=py36 pre-commit  try-repo ../tox/ --all-files --verbose
[WARNING] Creating temporary repo with uncommitted changes...
[INFO] Initializing environment for /tmp/tmp0qylw4a8/shadow-repo.
===============================================================================
Using config:
===============================================================================
repos:
-   repo: /tmp/tmp0qylw4a8/shadow-repo
    rev: 38bc1a02f089a9d380901338e560b6286938a9d5
    hooks:
    -   id: tox
===============================================================================
[INFO] Installing environment for /tmp/tmp0qylw4a8/shadow-repo.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
tox......................................................................Passed
- hook id: tox
- duration: 7.61s

GLOB sdist-make: /tmp/y/astpretty/setup.py
py36 recreate: /tmp/y/astpretty/.tox/py36
py36 installdeps: -rrequirements-dev.txt
py36 inst: /tmp/y/astpretty/.tox/.tmp/package/1/astpretty-2.1.0.zip
py36 installed: astpretty @ file:///tmp/y/astpretty/.tox/.tmp/package/1/astpretty-2.1.0.zip,attrs==21.2.0,covdefaults==1.2.0,coverage==5.5,importlib-metadata==4.8.1,iniconfig==1.1.1,packaging==21.0,pluggy==1.0.0,py==1.10.0,pyparsing==2.4.7,pytest==6.2.5,toml==0.10.2,typed-ast==1.4.3,typing-extensions==3.10.0.2,zipp==3.6.0
py36 run-test-pre: PYTHONHASHSEED='505535848'
py36 run-test: commands[0] | coverage erase
py36 run-test: commands[1] | coverage run -m pytest tests
============================= test session starts ==============================
platform linux -- Python 3.6.15, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
cachedir: .tox/py36/.pytest_cache
rootdir: /tmp/y/astpretty
collected 28 items                                                             

tests/astpretty_test.py ...........................x                     [100%]

======================== 27 passed, 1 xfailed in 0.11s =========================
py36 run-test: commands[2] | coverage report --fail-under 100
Name    Stmts   Miss Branch BrPart  Cover   Missing
---------------------------------------------------
---------------------------------------------------
TOTAL     193      0     36      0   100%

3 files skipped due to complete coverage.
___________________________________ summary ____________________________________
  py36: commands succeeded
  congratulations :)

```

but tox should not have a `.pre-commit-hooks.yaml` (I'm a tox dev)

**Comment by JulianOrteil** [comment]
Indeed. I discovered one of my environment variables was incorrectly configured (probably set it temporarily for whatever reason and forgot to reset it after). Thanks for looking into it.

However, isn't `it doesn't make sense to have tox as a pre-commit hook -- they should be fast checks` a bit "narrow-minded" (for a lack of a better word)? Considering the official [cookbook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) states the following: 

`[pre-commit is] used to inspect the snapshot that’s about to be committed, to see if you’ve forgotten something, **to make sure tests run**, or to examine whatever you need to inspect in the code.`

I would think `pre-commit`'s philosophy to also follow that of intention of the official docs--but maybe there is an excellent reason why you and the other contributors of this awesome project decided to limit its official use to just quick checks?

Thanks again for your help :+1:

**Comment by asottile** [comment]
our official recommendation is to use quick checks -- anything that's slow will wear down on users and encourage them to `--no-verify` / `SKIP` / blame the framework which hurts adoption and isn't productive.  slow checks shifts the value trade off from being helpful to being a burden

if you're waiting 35 seconds for a commit that's absolutely going to cause your contributors to turn it off

**Comment by JulianOrteil** [comment]
Fair point. Thanks for the clarification.
