### ISSUE TITLE
`--config` doesn't accept VFS files

### ISSUE THREAD

**Issue by ljmf00** [pre-commit/pre-commit#2075]
### describe your issue

I ran the following on bash:

```bash
pre-commit run --config <(cat .pre-commit-config.yaml <(echo "fail_fast: true"))
```

I expected this to be valid since `<()` creates a temporary file descriptor on `vfs` and expose it normally on `devfs` as `/dev/fd/<fd identifier>` and `cat` will append to the created temporary file descriptor the configuration file and the `fail_fast: true`.

Although this is reproducible in bash, this bug can be expanded if anyone wants to pipe a file descriptor to a child process using `procfs` since `devfs` and `procfs` are both virtual file systems.

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
# Pretty much any configuration
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
```

### version information

```
pre-commit version: 2.15.0
sys.version:
    3.9.7 (default, Aug 31 2021, 13:28:12) 
    [GCC 11.1.0]
sys.executable: /home/luis/Workspace/Programming/Repos/tempcollab/github/pre-commit/pre-commit/env/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An error has occurred: InvalidConfigError: 
=====> ../../../../../../../../../dev/fd/63 is not a file
```

```
Traceback (most recent call last):
  File "/home/luis/Workspace/Programming/Repos/tempcollab/github/pre-commit/pre-commit/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/luis/Workspace/Programming/Repos/tempcollab/github/pre-commit/pre-commit/pre_commit/main.py", line 400, in main
    return run(args.config, store, args)
  File "/home/luis/Workspace/Programming/Repos/tempcollab/github/pre-commit/pre-commit/pre_commit/commands/run.py", line 401, in run
    config = load_config(config_file)
  File "/home/luis/Workspace/Programming/Repos/tempcollab/github/pre-commit/pre-commit/env/lib/python3.9/site-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/luis/Workspace/Programming/Repos/tempcollab/github/pre-commit/pre-commit/env/lib/python3.9/site-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "/home/luis/Workspace/Programming/Repos/tempcollab/github/pre-commit/pre-commit/env/lib/python3.9/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/home/luis/Workspace/Programming/Repos/tempcollab/github/pre-commit/pre-commit/env/lib/python3.9/site-packages/cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} is not a file')
pre_commit.clientlib.InvalidConfigError: 
=====> ../../../../../../../../../dev/fd/63 is not a file
```

**Comment by asottile** [comment]
it fails `os.path.isfile` -- so the error message is correct:

```console
$ python3 -c 'import os.path, sys; print(os.path.isfile(sys.argv[1]))' <(cat /dev/null)
False
```

**Comment by ljmf00** [comment]
> it fails `os.path.isfile` -- so the error message is correct:
> 
> ```
> $ python3 -c 'import os.path, sys; print(os.path.isfile(sys.argv[1]))' <(cat /dev/null)
> False
> ```

A `vfs` file is considered a FIFO (pipe) and therefore is not considered a "regular file". You should evaluate that using something like:

```python
stat.S_ISFIFO(os.stat("/proc/self/fd/63").st_mode) # True
```

This should be considered since piping files is a common practice in UNIX environments.

**Comment by asottile** [comment]
just use a normal file instead

**Comment by ljmf00** [comment]
> just use a normal file instead

This is not ideal. A user to use a temporary configuration file doesn't need to use I/O or have `tmpfs` mounted. Writing to disk to read it right after is a workaround to how a UNIX-based system should work.

**Comment by asottile** [comment]
pre-commit needs a normal, writable file -- a FIFO is not an acceptable substitute
