### ISSUE TITLE
Permission denied error in attempting to create files during pre-commit

### ISSUE THREAD

**Issue by marksweb** [pre-commit/pre-commit#2077]
I've setup pre-commit to see how it might help my projects and ran it against all files to get an idea of what configs I might need to look at so that it works for me.

So I ran the following;

```
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.2.2
  hooks:
    - id: python-safety-dependencies-check

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    - id: flake8
      additional_dependencies: [
          "flake8-bugbear",
          "flake8-comprehensions",
          "flake8-mutable",
          "flake8-print",
          "flake8-simplify",
      ]
```

After looking over what was changed, I reverted those files in order to park the pre-commit setup & return to it when I have more time. Changes spanned python files, `.scss` files, etc.

However I now can't commit, or reset and I'm not sure why. So I'm here, at a loss 😬 because something in this process seems to have changed the permissions leaving them inaccessible to my user.

The error I get out of a commit suggests that it's trying to recreate those files I've reverted and now being allowed;

```
### version information

pre-commit version: 2.15.0
sys.version:
    3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) 
    [Clang 6.0 (clang-600.0.57)]
sys.executable: /Users/mwalker/Sites/consoles/.venv/bin/python
os.name: posix
sys.platform: darwin

### error information

An unexpected error has occurred: CalledProcessError: command: ('/Library/Developer/CommandLineTools/usr/libexec/git-core/git', 'checkout', '--', '.')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    warning: unable to access 'apps/console/src/sass/libs/bootstrap/.gitattributes': Permission denied
    error: unable to create file apps/console/src/sass/libs/bootstrap/_alerts.scss: Permission denied
    ...
    error: unable to create file apps/console/src/sass/libs/bootstrap/_wells.scss: Permission denied
    fatal: cannot create directory at 'apps/console/src/sass/libs/bootstrap/mixins': Permission denied
    
Traceback (most recent call last):
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/pre_commit/main.py", line 368, in main
    return hook_impl(
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 399, in run
    exit_stack.enter_context(staged_files_only(store.directory))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 425, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/pre_commit/staged_files_only.py", line 92, in staged_files_only
    with _intent_to_add_cleared(), _unstaged_changes_cleared(patch_dir):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/pre_commit/staged_files_only.py", line 61, in _unstaged_changes_cleared
    cmd_output_b('git', 'checkout', '--', '.', env=no_checkout_env)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Library/Developer/CommandLineTools/usr/libexec/git-core/git', 'checkout', '--', '.')
```

Trying to reset is much the same;

```
% git reset --hard
warning: unable to access 'apps/console/src/sass/libs/bootstrap/.gitattributes': Permission denied
error: unable to create file apps/console/src/sass/libs/bootstrap/_alerts.scss: Permission denied
...
```

Given these errors, I've checked the permissions on that directory;

```
mwalker@CH-Mac075 libs % ls -al 
total 16
drwxr-xr-x   5 mwalker  staff   160 Oct  4 11:02 .
drwxr-xr-x  10 mwalker  staff   320 Oct  4 12:36 ..
-rwxr-xr-x   1 mwalker  staff   292 Oct  4 11:02 _bootstrap-custom.scss
-rwxr-xr-x   1 mwalker  staff  1486 Oct  4 11:02 _bootstrap.scss
drw-r--r--  43 mwalker  staff  1376 Sep 17 01:40 bootstrap
```

There's another directory which stores fonts which appears to be in a similar state;

```
% ls -al
total 0
drwxr-xr-x   7 mwalker  staff  224 Oct  1  2020 .
drwxr-xr-x   4 mwalker  staff  128 Oct  4 12:42 ..
drwxr-xr-x   4 mwalker  staff  128 Sep 27 17:32 css
drw-r--r--  22 mwalker  staff  704 Sep 30  2020 fonts
drwxr-xr-x   3 mwalker  staff   96 Sep 30  2020 img
drwxr-xr-x  15 mwalker  staff  480 Sep 27 17:32 js
drwxr-xr-x   3 mwalker  staff   96 Sep 30  2020 lib
```

Upon changing the permissions back to something sensible, I can access these folders and see that the files do still exist.

```
drwxr-xr-x  22 mwalker  staff   704 Sep 30  2020 fonts
```

**Comment by asottile** [comment]
please use the issue template, it is there for a reason

___

the error suggests that you ran `chmod -x` at some point in an over-zealous fashion -- pre-commit wouldn't have done that but the errors are the result of you breaking your git repo by doing that

**Comment by marksweb** [comment]
I'd have used the issue template if I'd been raising a bug report, but I was 99% sure this was an issue on my machine, so I chose the other option...

<img width="344" alt="Screenshot 2021-10-04 at 20 05 59" src="https://user-images.githubusercontent.com/1461191/135909589-3c741d65-2eaa-49e9-a89e-fc27eab0d657.png">

Perhaps change the template name to suggest that it's for all issues.

Thanks for your help though (I wasn't suggesting that pre-commit would have done this). I haven't changed permissions or ran `chmod` in a very long time, certainly not since creating this particular repo.

I generally don't change permissions & have from time to time ran macOS permissions fixes across my machine.
