### ISSUE TITLE
using existing rbenv / ruby versions (MacOS / M1)

### ISSUE THREAD

**Issue by dramalho** [pre-commit/pre-commit#2084]
I may has missed a trick here but is there a way to run ruby based hooks with existing rbenv environment, instead of either:

*  using system (which is falling back to the OS ruby version) 
*  or by setting the ruby version via `default_language_version` which seems to trigger a separate `ruby-build` install - which needs some tweaks to install correctly on my M1, all of which I had resolved previously.

I would love to use my local shims as all the nastiness of installing things has been sorted :) - again, I might be missing an easy trick here

thanks :)

**Comment by asottile** [comment]
`language_version: system` _is_ whatever `ruby` is already around -- there isn't anything beyond that

**Comment by dramalho** [comment]
Yeah, that was my expectaction

```bash
$ ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]

$ which ruby
/Users/dramalho/.rbenv/shims/ruby
```

but then

```bash
$ pre-commit
(yada yada yada)
Patch-level verification for bundler.....................................Failed
- hook id: bundler-audit
- exit code: 1

Traceback (most recent call last):
	12: from /Users/dramalho/.cache/pre-commit/repo42xu1ove/rbenv-system/gems/bin/run-bundle-audit:23:in `<main>'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'bundler' (2.2.3) required by your /Users/dramalho/workspace/personal/raging-nexus/raging-nexus-next/Gemfile.lock. (Gem::MissingSpecVersionError)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.2.3`
```

which is the ruby version bundled in MacOS

```bash
$ /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
```

I don't want to take much of your time, but you might be very quick in assessing this. Thank you either way , pre-commit looks great :)

**Comment by asottile** [comment]
that's very strange 🤔 

I'm not sure why the versions mismatch -- perhaps because shim executables are dependent on location?

this also seems relevant for the actual error: https://github.com/jumanjihouse/pre-commit-hooks/issues/39

**Comment by dramalho** [comment]
The shims do depend on `rbenv` running, in this case reading off a
`.ruby-version` file and setting up the right final path.

I did try being explicit about what ruby version I wanted - in this case it
would match the existing one I was running the repo in - thinking that at
least I could benefit from having rbenv pre loaded with that version, but
pre-commit went on to run `ruby-build` separately and try to install ruby
again - which is also kinda odd (at a distance of course)

I'll check out that issue, although I think the ruby runtime is a separate
issue

**Comment by dramalho** [comment]
Fair. I've just left my computer but I'll try to figure some useful
information - maybe this was never a problem for people and I'm bringing
some specific problem here (I did install rbenv recently on this computer
and pretty much the standard way)

I assume this is the file that matters here, right?
https://github.com/pre-commit/pre-commit/blob/master/pre_commit/languages/ruby.py

**Comment by thiagowfx** [comment]
(long shot) @dramalho did you ever manage to resolve this?

I got a similar issue with:

```
  - repo: https://github.com/rubocop/rubocop
    rev: v1.64.1
    hooks:
      - id: rubocop
```

on M2.

```
% pre-commit run --all-files rubocop
[INFO] Locking pre-commit directory
[INFO] Installing environment for https://github.com/rubocop/rubocop.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/bin/bash', '/Users/thiago.perrotta/.rbenv/shims/gem', 'install', '--no-document', '--no-format-executable', '--no-user-install', '--install-dir', '/Users/thiago.perrotta/.cache/pre-commit/repog_uybwq2/rbenv-default/gems', '--bindir', '/Users/thiago.perrotta/.cache/pre-commit/repog_uybwq2/rbenv-default/gems/bin', 'rubocop-1.64.1.gem')
return code: 1
stdout:
    Successfully installed unicode-display_width-2.5.0
    Successfully installed ruby-progressbar-1.13.0
    Building native extensions. This could take a while...
    Successfully installed racc-1.8.0
    Successfully installed ast-2.4.2
    Successfully installed parser-3.3.2.0
stderr:
    ERROR:  Error installing rubocop-1.64.1.gem:
    	rubocop-ast requires Ruby version >= 2.7.0. The current ruby version is 2.6.10.210.
Check the log at /Users/thiago.perrotta/.cache/pre-commit/pre-commit.log
pre-commit run --all-files rubocop  14.16s user 0.73s system 18% cpu 1:22.46 total
```

For some reason, `pre-commit` keeps trying to use the system-default `ruby` instead of the shim one:

```
thiago.perrotta@thiagoperrotta-MacBook-Pro ~/Tulip/mulch (git)-[thiagowfx/rubocop]
% which ruby
/Users/thiago.perrotta/.rbenv/shims/ruby
thiago.perrotta@thiagoperrotta-MacBook-Pro ~/Tulip/mulch (git)-[thiagowfx/rubocop]
% /Users/thiago.perrotta/.rbenv/shims/ruby --version
ruby 3.2.4 (2024-04-23 revision af471c0e01) [arm64-darwin23]
thiago.perrotta@thiagoperrotta-MacBook-Pro ~/Tulip/mulch (git)-[thiagowfx/rubocop]
% /usr/bin/ruby --version
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
```

Happy to file a new bug and/or provide more logs as needed.

**Comment by asottile** [comment]
pre-commit cannot use shims because they are a moving target
