### ISSUE TITLE
pre-commit hangs when running pylint during run --all-files

### ISSUE THREAD

**Issue by nlarusstone** [pre-commit/pre-commit#2105]
### describe your issue

When I run `pre-commit` using the git hook, everything works fine. It takes ~1 min for changing 10 files. However, when I try to run `pre-commit run --all-files`, it hangs when trying to run `pylint`. I've left it for over an hour and it never completes:

```
platform ❯ pre-commit run --all-files                                130
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
isort....................................................................Passed
- hook id: isort
- duration: 0.23s

Skipped 24 files

yapf.....................................................................Passed
- hook id: yapf
- duration: 27.77s
mypy.....................................................................Passed
- hook id: mypy
- duration: 1.78s

Success: no issues found in 90 source files


pylint...................................................................
```

Seems to be the inverse of https://github.com/pre-commit/pre-commit/issues/1562. Wondering if you have any advice on how to debug this.

A few more version numbers that might be helpful:
- `Python 3.9.5`
- `pylint==2.9.6`

### pre-commit --version

pre-commit 2.11.1

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: "5.7.0"
    hooks:
    - id: isort
      verbose: true
      args: [--filter-files]
-   repo: git@github.com:pre-commit/mirrors-yapf.git
    rev: v0.30.0
    hooks:
    - id: yapf
      verbose: true
      args: ['--style=.style.yapf', '--parallel', '--in-place']
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        verbose: true
        entry: mypy platform_app/
        language: system
        pass_filenames: false
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        verbose: true
        types: [python]
        args: ['-d', 'C,R', '--rcfile=.pylintrc']
```

### ~/.cache/pre-commit/pre-commit.log (if present)

(This is after I interrupted it when it hung for an hour)

### version information

```
pre-commit version: 2.11.1
sys.version:
    3.9.2 (default, Mar 26 2021, 15:28:17) 
    [Clang 12.0.0 (clang-1200.0.32.29)]
sys.executable: /opt/homebrew/Cellar/pre-commit/2.11.1/libexec/bin/python3.9
os.name: posix
sys.platform: darwin
```

### error information

```
Interrupted (^C): KeyboardInterrupt: 
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/xargs.py", line 114, in _thread_mapper
    yield ex.map
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/xargs.py", line 163, in xargs
    for proc_retcode, proc_out, _ in results:
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 435, in result
    self._condition.wait(timeout)
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/main.py", line 385, in main
    return run(args.config, store, args)
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/commands/run.py", line 408, in run
    return _run_hooks(config, hooks, args, environ)
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/commands/run.py", line 286, in _run_hooks
    current_retval, prior_diff = _run_single_hook(
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/commands/run.py", line 194, in _run_single_hook
    retcode, out = language.run_hook(hook, filenames, use_color)
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/languages/system.py", line 19, in run_hook
    return helpers.run_xargs(hook, hook.cmd, file_args, color=color)
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 136, in run_xargs
    return xargs(cmd, file_args, **kwargs)
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/xargs.py", line 165, in xargs
    stdout += proc_out
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/homebrew/Cellar/pre-commit/2.11.1/libexec/lib/python3.9/site-packages/pre_commit/xargs.py", line 114, in _thread_mapper
    yield ex.map
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 628, in __exit__
    self.shutdown(wait=True)
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 229, in shutdown
    t.join()
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1033, in join
    self._wait_for_tstate_lock()
  File "/opt/homebrew/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1049, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by Johnlon** [comment]
why was this closed as there is no resolution..
I see same problem years later
any clues?

**Comment by asottile** [comment]
yeah try the comment right above yours
