### ISSUE TITLE
Having trouble running on Travis-CI

### ISSUE THREAD

**Issue by quentindemetz** [pre-commit/pre-commit#212]
I'd like to run my hooks (jshint, etc) on Travis to force my devs to use the hooks correctly. I'm encountering issues with that, my .travis.yml contains the following:
```
- sudo pip install -U pip
- sudo pip install pre-commit==0.4.2
- pre-commit run --all-files
```

It seems like the installation is going fine, but I'm getting many line of similar output when pre-commit is actually running (and failing the hooks):
```
Check Yaml...............................................................Failed
hookid: check-yaml
Traceback (most recent call last):
  File "/home/travis/.pre-commit/repoVWA7rL/py_env/bin/check-yaml", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/travis/.pre-commit/repoVWA7rL/py_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/home/travis/.pre-commit/repoVWA7rL/py_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/travis/.pre-commit/repoVWA7rL/py_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/travis/.pre-commit/repoVWA7rL/py_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pep8<1.6,>=1.5.7
```

Any idea ?

**Comment by asottile** [comment]
This was fixed here: https://github.com/pre-commit/pre-commit-hooks/commit/4078cbedf0360dce2b7cd02cb2812fc50b76b98d

Bumping to a newer version of that repo will fix. (v0.4.1 is tagged I believe)

**Comment by quentindemetz** [comment]
Right, but I've explicitly installed 0.4.2, isn't that enough?

**Comment by asottile** [comment]
The hook is erroring, not the tool.  You'll need to update .pre-commit-config.yaml

**Comment by quentindemetz** [comment]
Understood, thanks
