### ISSUE TITLE
try-repo fails due to "/tmp/tmp2fv85ecw/repo18pkus5m/.pre-commit-hooks.yaml is not a file"

### ISSUE THREAD

**Issue by zioalex** [pre-commit/pre-commit#2126]
### describe your issue
I try to test a new hook I wrote.

I run 
```re-commit try-repo ../pre-commit export_tf_vars --verbose --all-files```

and I expect to have my hook run.

But I got the follow error:
```
 pre-commit try-repo ../pre-commit export_tf_vars --verbose --all-files
[WARNING] Creating temporary repo with uncommitted changes...
===============================================================================
Using config:
===============================================================================
repos:
-   repo: /tmp/tmp2fv85ecw/shadow-repo
    rev: 54931c0071c55c77292d97a4de9c66b4b8df09e1
    hooks:
    -   id: export_tf_vars
===============================================================================
[INFO] Initializing environment for /tmp/tmp2fv85ecw/shadow-repo.
An error has occurred: InvalidManifestError: 
=====> /tmp/tmp2fv85ecw/repo18pkus5m/.pre-commit-hooks.yaml is not a file
Check the log at /home/s0vp8h/.cache/pre-commit/pre-commit.log`
```
The temporary config is not created though I have access to the /tmp

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: /tmp/tmp2fv85ecw/shadow-repo
    rev: 54931c0071c55c77292d97a4de9c66b4b8df09e1
    hooks:
    -   id: export_tf_vars
```

### version information

```
pre-commit version: 2.15.0
sys.version:
    3.8.10 (default, Sep 28 2021, 16:10:42)
    [GCC 9.3.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An error has occurred: InvalidManifestError:
=====> /tmp/tmpkaqpt8du/repo_ni5km7m/.pre-commit-hooks.yaml is not a file
```

```
Traceback (most recent call last):
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/pre_commit/main.py", line 400, in main
    return try_repo(args)
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/pre_commit/commands/try_repo.py", line 77, in try_repo
    return run(config_filename, store, args)
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/pre_commit/commands/run.py", line 404, in run
    for hook in all_hooks(config, store)
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 228, in all_hooks
    return tuple(
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 231, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 206, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 173, in _cloned_repository_hooks
    by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/home/s0vp8h/.local/lib/python3.8/site-packages/cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} is not a file')
pre_commit.clientlib.InvalidManifestError:
=====> /tmp/tmpkaqpt8du/repo_ni5km7m/.pre-commit-hooks.yaml is not a file
```

**Comment by asottile** [comment]
sounds like you don't have an indexed hooks config in your test repo? what does `git -C ../pre-commit status` give you?

**Comment by zioalex** [comment]
Hi @asottile, here is what I get:

    git -C ../pre-commit status 
    On branch master
    nothing to commit, working tree clean

How to index the hook?

**Comment by asottile** [comment]
then the error message is correct, you have not written the pre-commit metadata (.pre-commit-hooks.yaml) providing your hook

**Comment by zioalex** [comment]
@asottile  I don't get it. I understood that the try-repo option do not need it. Isn't it?

**Comment by asottile** [comment]
you don't need a `.pre-commit-`**`config`**`.yaml` but your repository which provides hooks does need a `.pre-commit-`**`hooks`**`.yaml`

**Comment by zioalex** [comment]
Hi, I created the .pre-commit-config.yaml file in the pre-commit dir:
```
vscode ➜ /workspaces/DevOpsInfra/ota-linux-vm-packer (master) $ ls -al ../pre-commit/
total 0
drwxr-xr-x 1 vscode vscode 4096 Nov 19 14:55 .
drwxrwxrwx 1 vscode vscode 4096 Nov 19 11:03 ..
-rwxr-xr-x 1 vscode vscode  420 Nov 12 15:30 export_tf_vars
drwxr-xr-x 1 vscode vscode 4096 Nov 19 14:58 .git
-rw-r--r-- 1 vscode vscode   52 Nov 19 14:54 .pre-commit-config.yaml
```

And committed the change to the local repo.

And now when I run it something different happens:
```
$ pre-commit try-repo ../pre-commit export_tf_vars --verbose --all-files 
===============================================================================
Using config:
===============================================================================
repos:
-   repo: ../pre-commit
    rev: e58ba0322a986acc33d9df0b0341406168ee45ea
    hooks:
    -   id: export_tf_vars
===============================================================================
[INFO] Initializing environment for ../pre-commit.
An error has occurred: InvalidManifestError: 
=====> /tmp/tmpdzjw5625/repotxsego6l/.pre-commit-hooks.yaml is not a file
Check the log at /home/vscode/.cache/pre-commit/pre-commit.log

$ more /home/vscode/.cache/pre-commit/pre-commit.log
### version information


pre-commit version: 2.15.0
sys.version:
    3.8.10 (default, Sep 28 2021, 16:10:42) 
    [GCC 9.3.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information


An error has occurred: InvalidManifestError: 
=====> /tmp/tmpdzjw5625/repotxsego6l/.pre-commit-hooks.yaml is not a file



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/main.py", line 400, in main
    return try_repo(args)
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/commands/try_repo.py", line 77, in try_repo
    return run(config_filename, store, args)
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/commands/run.py", line 404, in run
    for hook in all_hooks(config, store)
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/repository.py", line 228, in all_hooks
    return tuple(
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/repository.py", line 231, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/repository.py", line 206, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/usr/local/lib/python3.8/dist-packages/pre_commit/repository.py", line 173, in _cloned_repository_hooks
    by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
  File "/usr/local/lib/python3.8/dist-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "/usr/local/lib/python3.8/dist-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/usr/local/lib/python3.8/dist-packages/cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} is not a file')
pre_commit.clientlib.InvalidManifestError: 
=====> /tmp/tmpdzjw5625/repotxsego6l/.pre-commit-hooks.yaml is not a file
```

Bit still fails.

**Comment by asottile** [comment]
read closely, there are two different files and you have the wrong one

**Comment by zioalex** [comment]
Okay! I see. Thanks @asottile .
Now I managed to make it to work with the follow files:
```
ls -al ../pre-commit/
total 0
drwxr-xr-x 1 vscode vscode 4096 Nov 23 13:59 .
drwxrwxrwx 1 vscode vscode 4096 Nov 23 13:42 ..
-rwxr-xr-x 1 vscode vscode  423 Nov 23 13:56 export_tf_vars.sh
drwxr-xr-x 1 vscode vscode 4096 Nov 23 13:53 .git
-rw-r--r-- 1 vscode vscode   52 Nov 19 15:08 .pre-commit-config.yaml
-rw-r--r-- 1 vscode vscode  183 Nov 23 13:59 .pre-commit-hooks.yaml
```

Is this documented? I didn't find it.

**Comment by asottile** [comment]
yes there is extensive documentation about creating new hooks: https://pre-commit.com/#new-hooks

you don't need a `.pre-commit-config.yaml` to export hooks by the way

**Comment by zioalex** [comment]
HI Anthony,
yep sure.
It wasn't clear to me that it was needed also for the "try-out" option.

**Comment by asottile** [comment]
ok well, I can't possibly see how you would expect pre-commit to pick up hook information that's necessary to run tools when it didn't exist
