### ISSUE TITLE
pre-commit fail to restore unstaged files

### ISSUE THREAD

**Issue by MaxymVlasov** [pre-commit/pre-commit#2127]
### describe your issue

1. I work with a project, make some changes to code, README, etc.
2. It has a frontend component that needed `npm run build` (`react-app-rewired build`) to generate some static.
3. That static is generated in a docker container and populated as `root:root` to dir that also has `root:root` in the repo.
4. In normal cases, `static` located in `.gitignore` but that is not your way `:harold:`, so that files still counting in `git status`
(To make happy `git status` I should do things like `sudo rm static/js/2.ed4c987b.chunk.js` and `sudo git restore static/js/2.71286571.chunk.js`, without `sudo` it does not work.) I do not cleanup them, otherwise, we don't see the issue.
5. I `git add README` when, i.e. `dockerignore` not added.
6. `git commit`
...
pre-commit fail, diff not restored.

<details><summary>Here is simple instructions to repeat error</summary>

```bash
mkdir pre-commit-bug
cd pre-commit-bug/
git init
echo "
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
" > .pre-commit-config.yaml

mkdir subfolder
touch 1 2 subfolder/file-for-delete
sudo chown -R root:root subfolder
git add -A
git commit -m "Init"
echo "changes for 1" >> 1
echo "changes for 2" >> 2
sudo rm subfolder/file-for-delete
git add 1
git status
git commit -m "changes"
git status
```

</details>

<details><summary>Same instructions, but with outputs</summary>

```bash

$ mkdir pre-commit-bug
$ cd pre-commit-bug/
$ git init
Initialized empty Git repository in /tmp/pre-commit-bug/.git/
$ echo "
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
" > .pre-commit-config.yaml

$ mkdir subfolder
$ touch 1 2 subfolder/file-for-delete
$ sudo chown -R root:root subfolder
$ git add -A
$ git commit -m "Init" 
Trim Trailing Whitespace.................................................Passed
[main (root-commit) 8e14a7d] Init
 4 files changed, 7 insertions(+)
 create mode 100644 .pre-commit-config.yaml
 create mode 100644 1
 create mode 100644 2
 create mode 100644 subfolder/file-for-delete
$ echo "changes for 1" >> 1
$ echo "changes for 2" >> 2
$ sudo rm subfolder/file-for-delete
$ git add 1
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   1

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   2
        deleted:    subfolder/file-for-delete
$ git commit -m "changes"
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/vm/.cache/pre-commit/patch1636757903-16906.
An unexpected error has occurred: CalledProcessError: command: ('/usr/lib/git-core/git', 'checkout', '--', '.')
return code: 255
expected return code: 0
stdout: (none)
stderr:
    error: unable to create file subfolder/file-for-delete: Permission denied

Check the log at /home/vm/.cache/pre-commit/pre-commit.log
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   1

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    subfolder/file-for-delete

$

```
</details>

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
```

### version information

```
pre-commit version: 2.15.0
sys.version:
    3.8.5 (default, Jul 28 2020, 12:59:40) 
    [GCC 9.3.0]
sys.executable: /usr/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/lib/git-core/git', 'checkout', '--', '.')
return code: 255
expected return code: 0
stdout: (none)
stderr:
    error: unable to create file subfolder/file-for-delete: Permission denied
    
```

```
Traceback (most recent call last):
  File "/home/vm/.local/lib/python3.8/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/vm/.local/lib/python3.8/site-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/home/vm/.local/lib/python3.8/site-packages/pre_commit/commands/run.py", line 399, in run
    exit_stack.enter_context(staged_files_only(store.directory))
  File "/usr/lib/python3.8/contextlib.py", line 425, in enter_context
    result = _cm_type.__enter__(cm)
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/vm/.local/lib/python3.8/site-packages/pre_commit/staged_files_only.py", line 92, in staged_files_only
    with _intent_to_add_cleared(), _unstaged_changes_cleared(patch_dir):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/vm/.local/lib/python3.8/site-packages/pre_commit/staged_files_only.py", line 61, in _unstaged_changes_cleared
    cmd_output_b('git', 'checkout', '--', '.', env=no_checkout_env)
  File "/home/vm/.local/lib/python3.8/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/lib/git-core/git', 'checkout', '--', '.')
return code: 255
expected return code: 0
stdout: (none)
stderr:
    error: unable to create file subfolder/file-for-delete: Permission denied
```

**Comment by asottile** [comment]
yeah if you have files owned as root you can't really expect a non privileged user to manage those properly

**Comment by MaxymVlasov** [comment]
Okay, checks failed, during priveledges error, but why pre-commit can't restore files?

All what needed - force skip error to files. Files changed as root  will not changed but user files will restored

**Comment by asottile** [comment]
there's just not permissions to do that -- ideally you shouldn't use `git` as root and especially shouldn't have mixed permissions on a repo
