### ISSUE TITLE
Environment installation failing on python 3.10

### ISSUE THREAD

**Issue by ianhi** [pre-commit/pre-commit#2139]
### describe your issue

If I make a fresh conda environment wiht python 3.10:
```bash
mamba create -n test -c conda-forge python
conda activate test
pre-commit run --all-files
```
 then the environment installation fails as the version of python seems to be parsed as 3.1:

```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/ian/mambaforge/envs/pre-c-test/bin/python3.1', '-mvirtualenv', '/home/ian/.cache/pre-commit/repom866zdkl/py_env-python3.1', '-p', 'python3.1')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.1'
    
stderr: (none)
Check the log at /home/ian/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

pre-commit 2.15.0

### .pre-commit-config.yaml

```yaml
ci:
  autoupdate_schedule: 'quarterly'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.7.0]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--ignore-init-module-imports", "--remove-unused-variables"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
```

### version information

```
pre-commit version: 2.15.0
sys.version:
    3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0]
sys.executable: /home/ian/mambaforge/envs/pre-c-test/bin/python3.1
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/ian/mambaforge/envs/pre-c-test/bin/python3.1', '-mvirtualenv', '/home/ian/.cache/pre-commit/repom866zdkl/py_env-python3.1', '-p', 'python3.1')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.1'
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "/home/ian/mambaforge/envs/pre-c-test/lib/python3.10/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/ian/mambaforge/envs/pre-c-test/lib/python3.10/site-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/home/ian/mambaforge/envs/pre-c-test/lib/python3.10/site-packages/pre_commit/commands/run.py", line 417, in run
    install_hook_envs(to_install, store)
  File "/home/ian/mambaforge/envs/pre-c-test/lib/python3.10/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/home/ian/mambaforge/envs/pre-c-test/lib/python3.10/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/home/ian/mambaforge/envs/pre-c-test/lib/python3.10/site-packages/pre_commit/languages/python.py", line 203, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/home/ian/mambaforge/envs/pre-c-test/lib/python3.10/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/ian/mambaforge/envs/pre-c-test/bin/python3.1', '-mvirtualenv', '/home/ian/.cache/pre-commit/repom866zdkl/py_env-python3.1', '-p', 'python3.1')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.1'
    
stderr: (none)
```

**Comment by ianhi** [comment]
Interestingly running the following in a script:

```python
import pre_commit.languages.python as pre_c_py
print(pre_c_py.get_default_version())
```

gives a different result than when running in ipython:

![image](https://user-images.githubusercontent.com/10111092/143293413-0d5dd3a5-1d82-40f6-bbda-1ff5295cf979.png)

**Comment by ianhi** [comment]
Looking in the bin folder I find that `python3.1` is a link to `python3.10`

```
lrwxrwxrwx  1 ian ian   10 Nov 24 12:56 python3.1 -> python3.10
lrwxrwxrwx  1 ian ian   10 Nov 24 12:56 python3 -> python3.10
lrwxrwxrwx  1 ian ian   10 Nov 24 12:56 python -> python3.10
lrwxrwxrwx  1 ian ian    9 Nov 24 12:56 pydoc3 -> pydoc3.10
lrwxrwxrwx  1 ian ian    9 Nov 24 12:56 pydoc -> pydoc3.10
lrwxrwxrwx  1 ian ian    8 Nov 24 12:56 idle3 -> idle3.10
lrwxrwxrwx  1 ian ian    9 Nov 24 12:56 2to3 -> 2to3-3.10
```

not really sure what to make of that, I guess that depending on the context in which these commands are run that is either interpreted as a symlink or not?

**Comment by asottile** [comment]
your version of `virtualenv` is too old -- I've fixed this in `virtualenv` a few years ago

**Comment by asottile** [comment]
actually, this is a bug in `conda` it seems -- either way the bug is not here but there

**Comment by ianhi** [comment]
I'm not exactly clear what the bug to report to conda (or maybe mamba? where best to report?) is?

Is it that that it should not be a link? Or is simply that `sys.executable` should fully follow the link?

**Comment by asottile** [comment]
if your executable is named `python3.1` I'd start with whatever thing erroneously created that executable
