### ISSUE TITLE
Not stashing changes before installing

### ISSUE THREAD

**Issue by quentindemetz** [pre-commit/pre-commit#214]
Hi,

I'm regularly running into this situation: I have pending changes, I run `git commit -a`, and pre-commit tries to install its hooks:
```
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
An unexpected error has occurred: CalledProcessError: Command: ['git', 'checkout', 'd3db0385825d4c082bc7117c090ac16cb4840f3e']
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    error: Your local changes to the following files would be overwritten by checkout:
        .pre-commit-config.yaml
        .travis.yml
        CHANGELOG
        README.md
        hooks.yaml
        pre_commit_hooks/autopep8_wrapper.py
        pre_commit_hooks/check_json.py
        pre_commit_hooks/check_yaml.py
        pre_commit_hooks/debug_statement_hook.py
        pre_commit_hooks/end_of_file_fixer.py
        pre_commit_hooks/tests_should_end_in_test.py
        pre_commit_hooks/trailing_whitespace_fixer.py
        pre_commit_hooks/util.py
        pylintrc
        requirements-dev.txt
        setup.py
        testing/util.py
        tests/autopep8_wrapper_test.py
        tests/debug_statement_hook_test.py
        tests/end_of_file_fixer_test.py
        tests/tests_should_end_in_test_test.py
        tests/trailing_whitespace_fixer_test.py
        tests/util_test.py
        tox.ini
    Please, commit your changes or stash them before you can switch branches.
    Aborting
    

Check the log at ~/.pre-commit/pre-commit.log
```

The log contents are 
```
An unexpected error has occurred: CalledProcessError: Command: ['git', 'checkout', 'd3db0385825d4c082bc7117c090ac16cb4840f3e']
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    error: Your local changes to the following files would be overwritten by checkout:
    	.pre-commit-config.yaml
    	.travis.yml
    	CHANGELOG
    	README.md
    	hooks.yaml
    	pre_commit_hooks/autopep8_wrapper.py
    	pre_commit_hooks/check_json.py
    	pre_commit_hooks/check_yaml.py
    	pre_commit_hooks/debug_statement_hook.py
    	pre_commit_hooks/end_of_file_fixer.py
    	pre_commit_hooks/tests_should_end_in_test.py
    	pre_commit_hooks/trailing_whitespace_fixer.py
    	pre_commit_hooks/util.py
    	pylintrc
    	requirements-dev.txt
    	setup.py
    	testing/util.py
    	tests/autopep8_wrapper_test.py
    	tests/debug_statement_hook_test.py
    	tests/end_of_file_fixer_test.py
    	tests/tests_should_end_in_test_test.py
    	tests/trailing_whitespace_fixer_test.py
    	tests/util_test.py
    	tox.ini
    Please, commit your changes or stash them before you can switch branches.
    Aborting
    

Traceback (most recent call last):
  File "/home/qdm/workspace/web/pre-commit/pre_commit/error_handler.py", line 34, in error_handler
    yield
  File "/home/qdm/workspace/web/pre-commit/pre_commit/main.py", line 129, in main
    return run(runner, args)
  File "/home/qdm/workspace/web/pre-commit/pre_commit/commands/run.py", line 165, in run
    return _run_hooks(runner, args, write=write, environ=environ)
  File "/home/qdm/workspace/web/pre-commit/pre_commit/commands/run.py", line 115, in _run_hooks
    for repo in runner.repositories:
  File "/usr/lib/python3.4/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/qdm/workspace/web/pre-commit/pre_commit/runner.py", line 43, in repositories
    repository.require_installed()
  File "/home/qdm/workspace/web/pre-commit/pre_commit/repository.py", line 64, in require_installed
    self.install()
  File "/home/qdm/workspace/web/pre-commit/pre_commit/repository.py", line 78, in install
    for language_name, _ in self.languages
  File "/usr/lib/python3.4/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/qdm/workspace/web/pre-commit/pre_commit/repository.py", line 41, in languages
    for _, hook in self.hooks
  File "/usr/lib/python3.4/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/qdm/workspace/web/pre-commit/pre_commit/repository.py", line 49, in hooks
    for hook in self.repo_config['hooks']
  File "/home/qdm/workspace/web/pre-commit/pre_commit/repository.py", line 49, in <genexpr>
    for hook in self.repo_config['hooks']
  File "/usr/lib/python3.4/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/qdm/workspace/web/pre-commit/pre_commit/manifest.py", line 24, in hooks
    return dict((hook['id'], hook) for hook in self.manifest_contents)
  File "/usr/lib/python3.4/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/qdm/workspace/web/pre-commit/pre_commit/manifest.py", line 18, in manifest_contents
    self.repo_path_getter.repo_path, C.MANIFEST_FILE,
  File "/usr/lib/python3.4/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/qdm/workspace/web/pre-commit/pre_commit/store.py", line 46, in repo_path
    return self._store.clone(self._repo, self._sha)
  File "/home/qdm/workspace/web/pre-commit/pre_commit/store.py", line 119, in clone
    cmd_output('git', 'checkout', sha)
  File "/home/qdm/workspace/web/pre-commit/pre_commit/util.py", line 160, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ['git', 'checkout', 'd3db0385825d4c082bc7117c090ac16cb4840f3e']
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    error: Your local changes to the following files would be overwritten by checkout:
    	.pre-commit-config.yaml
    	.travis.yml
    	CHANGELOG
    	README.md
    	hooks.yaml
    	pre_commit_hooks/autopep8_wrapper.py
    	pre_commit_hooks/check_json.py
    	pre_commit_hooks/check_yaml.py
    	pre_commit_hooks/debug_statement_hook.py
    	pre_commit_hooks/end_of_file_fixer.py
    	pre_commit_hooks/tests_should_end_in_test.py
    	pre_commit_hooks/trailing_whitespace_fixer.py
    	pre_commit_hooks/util.py
    	pylintrc
    	requirements-dev.txt
    	setup.py
    	testing/util.py
    	tests/autopep8_wrapper_test.py
    	tests/debug_statement_hook_test.py
    	tests/end_of_file_fixer_test.py
    	tests/tests_should_end_in_test_test.py
    	tests/trailing_whitespace_fixer_test.py
    	tests/util_test.py
    	tox.ini
    Please, commit your changes or stash them before you can switch branches.
    Aborting
```

I think this is a regression from a previous version, it was more seamless then.

**Comment by asottile** [comment]
Hmmm that is odd!

Can you supply the following:

```
$ git --version
$ pre-commit --version
```

And potentially can you cd to that directory and see what `git status` is?  (The directory might be hard to find... hmm...)

You can find it by doing the following:

```
$ sqlite3 ~/.pre-commit/db.db 'SELECT path FROM repos WHERE repo = "git url for repo" AND ref = "sha you are using"'
```

Also I'm curious if `pre-commit clean` will fix it (obviously not a solution as I'd like to prevent getting into this situation).

I have some ideas on how to fix it if it's just that git changed how `--no-checkout` + `checkout` works

**Comment by quentindemetz** [comment]
```
$ git --version
git version 2.3.3
hub version 2.2.0
$ pre-commit --version
pre-commit 0.4.2
```
`pre-commit clean` does not fix it.
My `~/.pre-commit/db.db` file has no repos…

**Comment by asottile** [comment]
Currently building git from source, I imagine this is a git change :/

**Comment by quentindemetz** [comment]
Sounds like a good place to look, after a short investigation, my teammates who are on git 2.3 have encountered this issue.

**Comment by asottile** [comment]
Can you cat `/etc/gitconfig` and `~/.gitconfig` ?

**Comment by quentindemetz** [comment]
`/etc/gitconfig` does not exist.
`~/.gitconfig` contents:
```
[user]
        name = Quentin de Metz
        email = quentin.de-metz@pricematch.travel
[credential]
        helper = cache --timeout=3600
[push]
        default = current
[help]
        autocorrect = 1
[branch]
        autosetuprebase = never
[color]
  branch = auto
  diff = auto
  status = auto

[color "branch"]
  current = yellow reverse
  local = yellow
  remote = green

[color "diff"]
  meta = yellow bold
  frag = magenta bold
  old = red bold
  new = green bold

[color "status"]
  added = yellow
  changed = green
  untracked = cyan
[tag]
        sort = version:refname
```

**Comment by asottile** [comment]
Quite strange!  I'm still having trouble reproducing, I imagine it might be whatever `hub 2.2.0` is that's making this different.  Lemme make a shotgun-debugging branch that might fix the issue?

Can you try with this branch: reset_instead_of_checkout (just pushed to origin)

**Comment by quentindemetz** [comment]
Sure, but how do I replace the pre-commit I installed with pip by this branch ?

**Comment by quentindemetz** [comment]
Looking good, congratulations! Thanks!

**Comment by asottile** [comment]
Version 0.4.3 contains this fix

**Comment by quentindemetz** [comment]
Fantastic!

**Comment by quentindemetz** [comment]
:/
Now running into the following issue:
```
[INFO] Initializing environment for git://github.com/pricematch/pricematch-pre-commit-hooks.
An unexpected error has occurred: CalledProcessError: Command: ['git', 'reset', 'dd2447ada6d23bb9338d074f9453261924a26a77', '--hard']
Return code: 128
Expected return code: 0
Output: (none)
Errors:
    fatal: Could not parse object 'dd2447ada6d23bb9338d074f9453261924a26a77'.
```

My .pre-commit-config.yaml references `git://github.com/pricematch/pricematch-pre-commit-hooks` at SHA `dd2447ada6d23bb9338d074f9453261924a26a77` (which exists).

**Comment by quentindemetz** [comment]
I can work around this by stashing, running `pre-commit run --all-files` (which forces the installation), and unstashing.

**Comment by asottile** [comment]
This makes almost no sense,  why does a fresh checkout have a dirty working directory? What is changed inside that directory when you're stashing?

These are the commands that are being run, can you try them in another directory? 

```
git clone ... --no-checkout repo
cd repo
git status # should show all deleted
git reset ... --hard

```

**Comment by asottile** [comment]
Can you also `which git`

**Comment by quentindemetz** [comment]
I'm unable to reproduce… The output of these commands is as expected.
```
$ which git
/usr/bin/git
```
I'll let you know if something comes up

**Comment by asottile** [comment]
```ls -l `which git```` might be useful as well

**Comment by quentindemetz** [comment]
```
-rwxr-xr-x 3 root root 1711528 Mar 14 17:37 /usr/bin/git
```
