### ISSUE TITLE
Using log_file in hooks causes error if files parent directories don't exist

### ISSUE THREAD

**Issue by GlenNicholls** [pre-commit/pre-commit#2190]
### describe your issue

I added the following to my `.pre-commit-config.yaml`:

```
repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        log_file: build/pre-commit/black.log
        language_version: python3
```

`build/pre-commit/` does not exist, so i got the following error:

```
bash-4.4$ pre-commit run --all-files -v
black....................................................................Passed
- hook id: black
- duration: 0.19s

An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: 'build/pre-commit/black.log'
Check the log at /.../.cache/pre-commit/pre-commit.log
```

### pre-commit --version

2.16.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        log_file: build/pre-commit/black.log
        language_version: python3
```

### version information

```
pre-commit version: 2.16.0
sys.version:
    3.6.8 (default, Sep 10 2021, 09:13:53)
    [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
sys.executable: /usr/bin/python3.6
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: 'build/pre-commit/black.log'
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/lib/python3.6/site-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/usr/local/lib/python3.6/site-packages/pre_commit/commands/run.py", line 419, in run
    return _run_hooks(config, hooks, skips, args, environ)
  File "/usr/local/lib/python3.6/site-packages/pre_commit/commands/run.py", line 290, in _run_hooks
    verbose=args.verbose, use_color=args.color,
  File "/usr/local/lib/python3.6/site-packages/pre_commit/commands/run.py", line 225, in _run_single_hook
    output.write_line_b(out.strip(), logfile_name=hook.log_file)
  File "/usr/local/lib/python3.6/site-packages/pre_commit/output.py", line 21, in write_line_b
    stream = exit_stack.enter_context(open(logfile_name, 'ab'))
FileNotFoundError: [Errno 2] No such file or directory: 'build/pre-commit/black.log'
```

**Comment by asottile** [comment]
yep -- you'll need to make sure the log directory exists before execution
