### ISSUE TITLE
legacy_hook, ExecutableNotFoundError: on Windows

### ISSUE THREAD

**Issue by alekssamos** [pre-commit/pre-commit#2196]
I already had the hooks set up in the files `.git/hooks`
I installed pre-commit, it did the migration and now they don't work.
`git push`
```
vAn unexpected error has occurred: ExecutableNotFoundError: Executable `/bin/sh` not found
Check the log at ...cache\pre-commit\pre-commit.log
```
Previously, when I manually added hooks, everything worked fine, everything was fine. Please fix it
### version information

```
pre-commit version: 2.16.0
sys.version:
    3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
sys.executable: ...\AppData\Local\Programs\Python\Python39\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: ExecutableNotFoundError: Executable `/bin/sh` not found
```

```
Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\pre_commit\error_handler.py", line 65, in error_handler
    yield
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\pre_commit\main.py", line 368, in main
    return hook_impl(
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\pre_commit\commands\hook_impl.py", line 231, in hook_impl
    retv, stdin = _run_legacy(hook_type, hook_dir, args)
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\pre_commit\commands\hook_impl.py", line 42, in _run_legacy
    cmd = normalize_cmd((legacy_hook, *args))
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\pre_commit\parse_shebang.py", line 82, in normalize_cmd
    exe = normexe(cmd[0])
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\pre_commit\parse_shebang.py", line 61, in normexe
    _error('not found')
  File "...\AppData\Local\Programs\Python\Python39\lib\site-packages\pre_commit\parse_shebang.py", line 51, in _error
    raise ExecutableNotFoundError(f'Executable `{orig}` {msg}')
pre_commit.parse_shebang.ExecutableNotFoundError: Executable `/bin/sh` not found
```

**Comment by asottile** [comment]
also don't skip the issue template, it is there for a reason
