### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by JaGarRod** [pre-commit/pre-commit#2197]
### describe your issue

I was trying to use pre-commit in a fresh installation in a conda environment. It seems it cannot pip install because it cannot find the right certificate. My company enforces a specific certificate, how can I tell pre-commit where it is?
`
pre-commit run --all-files
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/PyCQA/isort.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /Users/garciaja/.cache/pre-commit/repocd2phk9a
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
    
stderr:
      DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
       pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
      ERROR: Command errored out with exit status 1:
       command: /Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-standalone-pip-edz4n6ny/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-build-env-cvkk345i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel
           cwd: None
      Complete output (8 lines):
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      Could not fetch URL https://pypi.org/simple/setuptools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/setuptools/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
      ERROR: Could not find a version that satisfies the requirement setuptools>=45.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=45.0
      ----------------------------------------
    WARNING: Discarding file:///Users/garciaja/.cache/pre-commit/repocd2phk9a. Command errored out with exit status 1: /Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-standalone-pip-edz4n6ny/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-build-env-cvkk345i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output.
    ERROR: Command errored out with exit status 1: /Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-standalone-pip-edz4n6ny/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-build-env-cvkk345i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output.
    
Check the log at /Users/garciaja/.cache/pre-commit/pre-commit.log
`

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: \.py$
        language_version: python3.9

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
        language_version: python3.9
      - id: check-yaml
```

### version information

```
pre-commit version: 2.16.0
sys.version:
    3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35) 
    [Clang 11.1.0 ]
sys.executable: /Users/garciaja/apps/miniconda3/envs/sim_cap_optimizer/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /Users/garciaja/.cache/pre-commit/repocd2phk9a
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
    
stderr:
      DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
       pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
      ERROR: Command errored out with exit status 1:
       command: /Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-standalone-pip-edz4n6ny/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-build-env-cvkk345i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel
           cwd: None
      Complete output (8 lines):
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      Could not fetch URL https://pypi.org/simple/setuptools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/setuptools/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
      ERROR: Could not find a version that satisfies the requirement setuptools>=45.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=45.0
      ----------------------------------------
    WARNING: Discarding file:///Users/garciaja/.cache/pre-commit/repocd2phk9a. Command errored out with exit status 1: /Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-standalone-pip-edz4n6ny/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-build-env-cvkk345i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output.
    ERROR: Command errored out with exit status 1: /Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-standalone-pip-edz4n6ny/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-build-env-cvkk345i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output.
    
```

```
Traceback (most recent call last):
  File "/Users/garciaja/apps/miniconda3/envs/sim_cap_optimizer/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/Users/garciaja/apps/miniconda3/envs/sim_cap_optimizer/lib/python3.9/site-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/Users/garciaja/apps/miniconda3/envs/sim_cap_optimizer/lib/python3.9/site-packages/pre_commit/commands/run.py", line 417, in run
    install_hook_envs(to_install, store)
  File "/Users/garciaja/apps/miniconda3/envs/sim_cap_optimizer/lib/python3.9/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/Users/garciaja/apps/miniconda3/envs/sim_cap_optimizer/lib/python3.9/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/Users/garciaja/apps/miniconda3/envs/sim_cap_optimizer/lib/python3.9/site-packages/pre_commit/languages/python.py", line 205, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/Users/garciaja/apps/miniconda3/envs/sim_cap_optimizer/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/Users/garciaja/apps/miniconda3/envs/sim_cap_optimizer/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /Users/garciaja/.cache/pre-commit/repocd2phk9a
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
    
stderr:
      DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
       pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
      ERROR: Command errored out with exit status 1:
       command: /Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-standalone-pip-edz4n6ny/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-build-env-cvkk345i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel
           cwd: None
      Complete output (8 lines):
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/setuptools/
      Could not fetch URL https://pypi.org/simple/setuptools/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/setuptools/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
      ERROR: Could not find a version that satisfies the requirement setuptools>=45.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=45.0
      ----------------------------------------
    WARNING: Discarding file:///Users/garciaja/.cache/pre-commit/repocd2phk9a. Command errored out with exit status 1: /Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-standalone-pip-edz4n6ny/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-build-env-cvkk345i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output.
    ERROR: Command errored out with exit status 1: /Users/garciaja/.cache/pre-commit/repocd2phk9a/py_env-python3.9/bin/python /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-standalone-pip-edz4n6ny/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/f6/rdw8wpvx51189yryc1h89_y80000gp/T/pip-build-env-cvkk345i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output.
```

**Comment by asottile** [comment]
this isn't a problem with pre-commit but with your company's certificate setup

if you'd like enterprise support please reach out to me privately

**Comment by JaGarRod** [comment]
what do you mean? I have a certificate. I just want to configure pre-commit or whatever it uses to use that specific certificate. Usually a tool that needs SSL encryption offers this configuration. Is it not possible to tell pre-commit to use a spefic SSL certificate in its connections? If you would tell me what pip pre-commit is using I could just configure that pip to use my certificate
