### ISSUE TITLE
pre-commit checks get failed with "reorder_python_imports" traceback

### ISSUE THREAD

**Issue by devendra104** [pre-commit/pre-commit#2199]
### describe your issue

We are hitting the pre-commit check failure issue since last week, earlier it was working fine with the same configuration, one suspicious change I observed between the sussessull pre-commit check and failed pre-commit-check and that was missing caching inside the github action **"/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/5f5502f9-7ba5-4ad1-9899-fbe8a96a2862/cache.tzst -P -C /home/runner/work/satellite6-upgrade/satellite6-upgrade"** 

Can someone please look into that?

**Current failure pre-commit action log**
```
Run pre-commit/action@v2.0.0
install pre-commit
/opt/hostedtoolcache/Python/3.8.12/x64/bin/pre-commit run --show-diff-on-failure --color=always --all-files
[INFO] Initializing environment for https://github.com/asottile/reorder_python_imports.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/asottile/reorder_python_imports.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Reorder python imports...................................................Failed
- hook id: reorder-python-imports
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo0x_564a0/py_env-python3.8/bin/reorder-python-imports", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repo0x_564a0/py_env-python3.8/lib/python3.8/site-packages/reorder_python_imports.py", line 907, in main
    retv |= _fix_file(filename, args)
  File "/home/runner/.cache/pre-commit/repo0x_564a0/py_env-python3.8/lib/python3.8/site-packages/reorder_python_imports.py", line 475, in _fix_file
    new_contents = fix_file_contents(
  File "/home/runner/.cache/pre-commit/repo0x_564a0/py_env-python3.8/lib/python3.8/site-packages/reorder_python_imports.py", line 456, in fix_file_contents
    partitioned = step(partitioned)
  File "/home/runner/.cache/pre-commit/repo0x_564a0/py_env-python3.8/lib/python3.8/site-packages/reorder_python_imports.py", line 366, in apply_import_sorting
    sorted_blocks = sort(import_obj_to_partition.keys(), **sort_kwargs)
  File "/home/runner/.cache/pre-commit/repo0x_564a0/py_env-python3.8/lib/python3.8/site-packages/aspy/refactor_imports/sort.py", line 96, in sort
    imports_partitioned[classify_func(import_obj)].append(import_obj)
  File "/home/runner/.cache/pre-commit/repo0x_564a0/py_env-python3.8/lib/python3.8/site-packages/aspy/refactor_imports/sort.py", line 73, in classify_func
    return classify_import(obj.import_statement.module, **kwargs)
  File "/home/runner/.cache/pre-commit/repo0x_564a0/py_env-python3.8/lib/python3.8/site-packages/aspy/refactor_imports/classify.py", line 138, in classify_import
    found, module_path, is_builtin = _get_module_info(
  File "/home/runner/.cache/pre-commit/repo0x_564a0/py_env-python3.8/lib/python3.8/site-packages/aspy/refactor_imports/classify.py", line 103, in _get_module_info
    assert spec.submodule_search_locations is not None
AssertionError
```

**Last successful pre-commit action log:**

```
Run pre-commit/action@v2.0.0
install pre-commit
Cache Size: ~12 MB (12082881 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/5f5502f9-7ba5-4ad1-9899-fbe8a96a2862/cache.tzst -P -C /home/runner/work/satellite6-upgrade/satellite6-upgrade
/opt/hostedtoolcache/Python/3.8.12/x64/bin/pre-commit run --show-diff-on-failure --color=always --all-files
Reorder python imports...................................................Passed
flake8...................................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Debug Statements (Python)................................................Passed
```

### pre-commit --version
pre-commit==2.16.0

pre-commit/action@v2.0.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
```

**Comment by asottile** [comment]
check the issue tracker of that tool, not here

there's a resolved duplicate with workarounds and root cause listed there
