### ISSUE TITLE
`pre-commit try-repo` -> `fatal: reference is not a tree`

### ISSUE THREAD

**Issue by tdegeus** [pre-commit/pre-commit#2209]
### describe your issue

I have added `~/tmp/latexindent.pl/.pre-commit-hooks.yaml`
```yaml
- id: latexindent-conda
  name: latexindent.pl
  description: Run latexindent.pl using Conda
  minimum_pre_commit_version: 2.1.0
  entry: latexindent.pl -s -w
  args: []
  language: conda
  types: [tex]
- id: latexindent-cpan
  name: latexindent.pl
  description: Run latexindent.pl, get dependencies using CPAN
  minimum_pre_commit_version: 2.1.0
  entry: latexindent.pl -s -w
  args: []
  language: perl
  types: [tex]
```
and `~/tmp/latexindent.pl/environment.yml`
```yaml
channels:
- conda-forge
dependencies:
- latexindent.pl
```

Now I am running
```
cd ~/new
pre-commit try-repo ~/tmp/latexindent.pl latexindent-conda --verbose --all-files
```
and am getting 
```
===============================================================================
Using config:
===============================================================================
repos:
-   repo: ../tmp/latexindent.pl
    rev: 3bd8f7c34260c035aa2acc573702e4dcfadd8420
    hooks:
    -   id: latexindent-perl
===============================================================================
[INFO] Initializing environment for ../tmp/latexindent.pl.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '3bd8f7c34260c035aa2acc573702e4dcfadd8420')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: reference is not a tree: 3bd8f7c34260c035aa2acc573702e4dcfadd8420

Check the log at /home/tdegeus/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
repos:
 - repo: https://github.com/cmhughes/latexindent.pl
   rev: 3.13.5
   hooks:
   - id: latexindent-conda
     args: [-l]
```

### version information

```
pre-commit version: 2.16.0
sys.version:
    3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17)
    [GCC 9.4.0]
sys.executable: /home/tdegeus/miniforge3/envs/stable/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '3bd8f7c34260c035aa2acc573702e4dcfadd8420')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: reference is not a tree: 3bd8f7c34260c035aa2acc573702e4dcfadd8420

```

```
Traceback (most recent call last):
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/store.py", line 183, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/store.py", line 165, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/store.py", line 180, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'protocol.version=2', 'fetch', 'origin', '3bd8f7c34260c035aa2acc573702e4dcfadd8420', '--depth=1')
return code: 1
expected return code: 0
stdout: (none)
stderr: (none)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/main.py", line 400, in main
    return try_repo(args)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/commands/try_repo.py", line 77, in try_repo
    return run(config_filename, store, args)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/commands/run.py", line 404, in run
    for hook in all_hooks(config, store)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/repository.py", line 228, in all_hooks
    return tuple(
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/repository.py", line 231, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/repository.py", line 206, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/repository.py", line 172, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/store.py", line 187, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/store.py", line 144, in _new_repo
    make_strategy(directory)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/store.py", line 185, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/store.py", line 158, in _complete_clone
    git_cmd('checkout', ref)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/store.py", line 180, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/tdegeus/miniforge3/envs/stable/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'checkout', '3bd8f7c34260c035aa2acc573702e4dcfadd8420')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: reference is not a tree: 3bd8f7c34260c035aa2acc573702e4dcfadd8420
```

**Comment by asottile** [comment]
what version of `git` are you using and what is `git status` in your temporary repo?

**Comment by tdegeus** [comment]
```
$ git --version
git version 1.8.3.1
```

```
$ git status
# On branch main
nothing to commit, working directory clean
```

**Comment by asottile** [comment]
you're using a 10+ year old version of git, there was a bug in git that was fixed 8 years ago which fixes try-repo -- upgrade your git version

**Comment by tdegeus** [comment]
I was naively taking the system's default git. Indeed take a modern one solves the issue. Thanks!
