### ISSUE TITLE
ImportError: cannot import name 'html5lib' in Python 3.10

### ISSUE THREAD

**Issue by Garrett-R** [pre-commit/pre-commit#2211]
### describe your issue

When I try to use `pre-commit` with a very similar config file with Python 3.10.2 on Ubuntu 20.04, I get this error:

```python
$ git commit -am "DNM: space"
[WARNING] normalizing pre-commit configuration to a top-level map.  support for top level list will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/runpy.py", line 198, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib/python3.10/runpy.py", line 88, in _run_code
        exec(code, run_globals)
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__main__.py", line 19, in <module>
        sys.exit(_main())
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 73, in main
        command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
        module = importlib.import_module(module_path)
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 24, in <module>
        from pip._internal.cli.req_command import RequirementCommand
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 15, in <module>
        from pip._internal.index.package_finder import PackageFinder
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
        from pip._internal.index.collector import parse_links
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 12, in <module>
        from pip._vendor import html5lib, requests
    ImportError: cannot import name 'html5lib' from 'pip._vendor' (/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_vendor/__init__.py)
    
Check the log at /home/garrett/.cache/pre-commit/pre-commit.log
```

I had encountered elsewhere while migrating to Python 3.10 and the fix was to get on the latest `pip` (as per [this answer](https://stackoverflow.com/questions/70431655/importerror-cannot-import-name-html5lib-from-pip-vendor-usr-lib-python3)).  I have changed my system `pip` to be the latest, but it seems `pre-commit` is using some other `pip` version which I'm speculating is not up-to-date.  

I wanted to go just update it `/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip`, but this folder must cleaned up because it no longer exist after my failed `pre-commit` attempt.

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-ast
```

### version information

```
pre-commit version: 2.16.0
sys.version:
    3.10.2 (main, Jan 15 2022, 18:02:07) [GCC 9.3.0]
sys.executable: /usr/bin/python3.10
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    code=<code object <module> at 0x7fc1541350b0, file "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__main__.py", line 1>, run_globals={'__name__': '__main__', '__doc__': None, '__package__': 'pip', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fc1540faaa0>, '__spec__': ModuleSpec(name='pip.__main__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc1540faaa0>, origin='/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__main__.py'), '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__main__.py', '__cached__': '/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__pycache__/__main__.cpython-310.pyc'}
    
stderr:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/runpy.py", line 198, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib/python3.10/runpy.py", line 88, in _run_code
        exec(code, run_globals)
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__main__.py", line 19, in <module>
        sys.exit(_main())
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 73, in main
        command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
        module = importlib.import_module(module_path)
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 24, in <module>
        from pip._internal.cli.req_command import RequirementCommand
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 15, in <module>
        from pip._internal.index.package_finder import PackageFinder
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
        from pip._internal.index.collector import parse_links
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 12, in <module>
        from pip._vendor import html5lib, requests
    ImportError: cannot import name 'html5lib' from 'pip._vendor' (/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_vendor/__init__.py)
    
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/main.py", line 368, in main
    return hook_impl(
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/commands/run.py", line 417, in run
    install_hook_envs(to_install, store)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/languages/python.py", line 205, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/languages/helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    code=<code object <module> at 0x7fc1541350b0, file "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__main__.py", line 1>, run_globals={'__name__': '__main__', '__doc__': None, '__package__': 'pip', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fc1540faaa0>, '__spec__': ModuleSpec(name='pip.__main__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fc1540faaa0>, origin='/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__main__.py'), '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__main__.py', '__cached__': '/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__pycache__/__main__.cpython-310.pyc'}
    
stderr:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/runpy.py", line 198, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib/python3.10/runpy.py", line 88, in _run_code
        exec(code, run_globals)
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/__main__.py", line 19, in <module>
        sys.exit(_main())
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 73, in main
        command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
        module = importlib.import_module(module_path)
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 24, in <module>
        from pip._internal.cli.req_command import RequirementCommand
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 15, in <module>
        from pip._internal.index.package_finder import PackageFinder
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
        from pip._internal.index.collector import parse_links
      File "/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 12, in <module>
        from pip._vendor import html5lib, requests
    ImportError: cannot import name 'html5lib' from 'pip._vendor' (/home/garrett/.cache/pre-commit/repo3d8p_zte/py_env-python3.10/lib/python3.10/site-packages/pip/_vendor/__init__.py)
```

**Comment by asottile** [comment]
the version of `virtualenv` on ubuntu 20.04 contains debian's incorrect devendoring (fixed in newer packagings of `virtualenv`)

I would recommend **not** using debian's `virtualenv` or `pip` personally: https://youtu.be/O390_abzo08

but since this isn't a pre-commit issue but an issue with `virtualenv` / `pip` there's nothing I can really do

**Comment by Garrett-R** [comment]
Thanks, you're right, it's an outdated version of `virtualenv` and actually doing this does fix it: 

```bash
sudo python3.10 -m pip install -U virtualenv
```

But watched the video, and I agree.  Didn't realize they also modify the virtualenv, that's undesirable.  Will switch to using that, thanks!
