### ISSUE TITLE
An unexpected error has occurred: CalledProcessErrorv (git, submodule, ...)

### ISSUE THREAD

**Issue by quoidautre** [pre-commit/pre-commit#2213]
### describe your issue

Hello,

I'm working on a django + drf project, on Windows 10 using WSL. I write a simple _.pre-commit-config.yaml_ file .

But, when I do `pre-commit run`, I see some errors, that I don't understand, because the file in error is completely out of my project ! : 
```
$ pre-commit run
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/MY/.cache/pre-commit/patch1642406225-19170.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Restored changes from /home/fpestre/.cache/pre-commit/patch1642406225-19170.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'submodule', 'update', '--init', '--recursive')
return code: 2
expected return code: 0
stdout: (none)
stderr:
: not foundb/git-core/git-submodule: 18: /mnt/c/Users/MY/mes-documents/tools/_IDE_/OpenCobolIDE/GnuCOBOL/bin/gettext.sh:
    /usr/lib/git-core/git-submodule: 47: /mnt/c/Users/MY/mes-documents/tools/_IDE_/OpenCobolIDE/GnuCOBOL/bin/gettext.sh: Syntax error: word unexpected (expecting "in")
```

And if I have some files in the stagged area or not, it's the same.

Can ou help me please ?

F.

### pre-commit --version

pre-commit 2.16.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
```

### version information

```
pre-commit version: 2.16.0
sys.version:
    3.9.2 (default, Feb 28 2021, 17:03:44)
    [GCC 10.2.1 20210110]
sys.executable: /home/MY/.local/share/virtualenvs/my-project-lAQueVvV/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'submodule', 'update', '--init', '--recursive')
return code: 2
expected return code: 0
stdout: (none)
stderr:
: not foundb/git-core/git-submodule: 18: /mnt/c/Users/MY/mes-documents/tools/_IDE_/OpenCobolIDE/GnuCOBOL/bin/gettext.sh:
    /usr/lib/git-core/git-submodule: 47: /mnt/c/Users/MY/mes-documents/tools/_IDE_/OpenCobolIDE/GnuCOBOL/bin/gettext.sh: Syntax error: word unexpected (expecting "in")

```

```
Traceback (most recent call last):
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/store.py", line 183, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/store.py", line 167, in _shallow_clone
    git_cmd(
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/store.py", line 180, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'protocol.version=2', 'submodule', 'update', '--init', '--recursive', '--depth=1')
return code: 2
expected return code: 0
stdout: (none)
stderr:
: not foundb/git-core/git-submodule: 18: /mnt/c/Users/MY/mes-documents/tools/_IDE_/OpenCobolIDE/GnuCOBOL/bin/gettext.sh:
    /usr/lib/git-core/git-submodule: 47: /mnt/c/Users/MY/mes-documents/tools/_IDE_/OpenCobolIDE/GnuCOBOL/bin/gettext.sh: Syntax error: word unexpected (expecting "in")


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/commands/run.py", line 404, in run
    for hook in all_hooks(config, store)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/repository.py", line 228, in all_hooks
    return tuple(
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/repository.py", line 231, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/repository.py", line 206, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/repository.py", line 172, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/store.py", line 187, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/store.py", line 144, in _new_repo
    make_strategy(directory)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/store.py", line 185, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/store.py", line 159, in _complete_clone
    git_cmd('submodule', 'update', '--init', '--recursive')
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/store.py", line 180, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/MY/.local/share/virtualenvs/my-project-lAQueVvV/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'submodule', 'update', '--init', '--recursive')
return code: 2
expected return code: 0
stdout: (none)
stderr:
: not foundb/git-core/git-submodule: 18: /mnt/c/Users/MY/mes-documents/tools/_IDE_/OpenCobolIDE/GnuCOBOL/bin/gettext.sh:
    /usr/lib/git-core/git-submodule: 47: /mnt/c/Users/MY/mes-documents/tools/_IDE_/OpenCobolIDE/GnuCOBOL/bin/gettext.sh: Syntax error: word unexpected (expecting "in")

**Comment by quoidautre** [comment]
If I run the demo repo, I've the same errors :-(

**Comment by asottile** [comment]
this looks like your `git` installation is corrupted -- it's trying to utilize `gettext` inside git and finding some unrelated `gettext.sh`

if you run `git submodule update --init` outside of `pre-commit` you'll see the same thing

closing since this isn't a pre-commit problem

**Comment by quoidautre** [comment]
Thanks :)
