### ISSUE TITLE
File not found error when running pre-commit under py3.10

### ISSUE THREAD

**Issue by Greedquest** [pre-commit/pre-commit#2225]
### describe your issue

I have pre-commit installed in a conda environment `gitkraken` which I just upgraded from python3.9 -> 3.10

Upon running `pre-commit run --all` in one of my repos already working with pre-commit, I got an error.

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        args: [--line-length=88,]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
```

#### version information

```
pre-commit version: 2.17.0
git --version: git version 2.33.1.windows.1
sys.version:
    3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)]
sys.executable: C:\Users\[username]\anaconda3\envs\gitkraken\python.exe
os.name: nt
sys.platform: win32
```

#### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\[username]\\.cache\\pre-commit\\repob60u4mod\\py_env-default\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "C:\Users\[username]\anaconda3\envs\gitkraken\lib\runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Users\[username]\anaconda3\envs\gitkraken\lib\runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\__main__.py", line 31, in <module>
        sys.exit(_main())
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_internal\cli\main.py", line 56, in main
        cmd_name, cmd_args = parse_command(args)
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_internal\cli\main_parser.py", line 60, in parse_command
        general_options, args_else = parser.parse_args(args)
      File "C:\Users\[username]\anaconda3\envs\gitkraken\lib\optparse.py", line 1371, in parse_args
        values = self.get_default_values()
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_internal\cli\parser.py", line 289, in get_default_values
        self.config.load()
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_internal\configuration.py", line 134, in load
        self._load_config_files()
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_internal\configuration.py", line 256, in _load_config_files
        config_files = dict(self.iter_config_files())
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_internal\configuration.py", line 359, in iter_config_files
        config_files = get_configuration_files()
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_internal\configuration.py", line 75, in get_configuration_files
        for path in appdirs.site_config_dirs('pip')
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_internal\utils\appdirs.py", line 34, in site_config_dirs
        dirval = _appdirs.site_config_dir(appname, appauthor=False, multipath=True)
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_vendor\appdirs.py", line 243, in site_config_dir
        path = site_data_dir(appname, appauthor)
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_vendor\appdirs.py", line 138, in site_data_dir
        path = os.path.normpath(_get_win_folder("CSIDL_COMMON_APPDATA"))
      File "C:\Users\[username]\.cache\pre-commit\repob60u4mod\py_env-default\lib\site-packages\pip\_vendor\appdirs.py", line 486, in _get_win_folder_from_registry
        dir, type = _winreg.QueryValueEx(key, shell_folder_name)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    
```

**Comment by asottile** [comment]
this is either:
- an appdirs bug
- a pip bug
- a conda bug

but not a pre-commit bug, please report it to those

**Comment by Greedquest** [comment]
Just trying to figure this out; that folder

 > `C:\Users\[username]\.cache\pre-commit\repob60u4mod`

does not contain a sub-folder `py_env-default`,  whereas lots of the other folders inside `~\.cache\pre-commit\` do have that sub folder.

Who is responsible for putting that subfolder there do you know? Is it pre-commit or something pre-commit calls - since that seems to be the root of this error.

**Comment by michaelosthege** [comment]
I had the same problem in one environment, but not in another one. Same project, same computer, same `pre-commit --version`.
The one that didn't work was older, so it's probably a problem with an outdated dependency.
For whoever finds this in the future: Try recreating your conda environment.
