### ISSUE TITLE
[Help] Error While Running from VSCode Devcontainer

### ISSUE THREAD

**Issue by jabertuhin** [pre-commit/pre-commit#2229]
Recently, I am working with VSCode devcontainer for local development. Here is my [repository](https://github.com/jabertuhin/dvdrental-backend). After creating the container, I couldn't commit properly because of the following error. I am not quite sure of the reason, as I have worked in multiple projects with the same setup. I have manually ran `pre-commit install --hook-type pre-commit --hook-type pre-push` this command and then tried to commit a change.

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.20.1
sys.version:
    3.8.12 (default, Dec 21 2021, 11:05:26) 
    [GCC 8.3.0]
sys.executable: /usr/local/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/vscode/.cache/pre-commit/repog5wip0x7/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/vscode/.cache/pre-commit/repog5wip0x7
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
    
stderr:
      ERROR: Command errored out with exit status 1:
       command: /home/vscode/.cache/pre-commit/repog5wip0x7/py_env-python3/bin/python /tmp/pip-standalone-pip-ez6as4qb/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ybcyqzmh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel
           cwd: None
      Complete output (14 lines):
      Collecting setuptools>=45.0
        Using cached setuptools-60.6.0-py3-none-any.whl (953 kB)
      Collecting setuptools_scm[toml]>=6.3.1
        Using cached setuptools_scm-6.4.2-py3-none-any.whl (37 kB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting tomli>=1.0.0
        Using cached tomli-2.0.0-py3-none-any.whl (12 kB)
      Collecting packaging>=20.0
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
      Installing collected packages: pyparsing, tomli, setuptools, packaging, setuptools-scm, wheel
      ERROR: Cannot set --home and --prefix together
      ----------------------------------------
    WARNING: Discarding file:///home/vscode/.cache/pre-commit/repog5wip0x7. Command errored out with exit status 1: /home/vscode/.cache/pre-commit/repog5wip0x7/py_env-python3/bin/python /tmp/pip-standalone-pip-ez6as4qb/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ybcyqzmh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output.
    ERROR: Command errored out with exit status 1: /home/vscode/.cache/pre-commit/repog5wip0x7/py_env-python3/bin/python /tmp/pip-standalone-pip-ez6as4qb/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ybcyqzmh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output.
    
```

```
Traceback (most recent call last):
  File "/usr/local/pip-global/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/usr/local/pip-global/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/usr/local/pip-global/pre_commit/commands/run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "/usr/local/pip-global/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/pip-global/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/usr/local/pip-global/pre_commit/languages/python.py", line 205, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/usr/local/pip-global/pre_commit/languages/helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/usr/local/pip-global/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/vscode/.cache/pre-commit/repog5wip0x7/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/vscode/.cache/pre-commit/repog5wip0x7
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
    
stderr:
      ERROR: Command errored out with exit status 1:
       command: /home/vscode/.cache/pre-commit/repog5wip0x7/py_env-python3/bin/python /tmp/pip-standalone-pip-ez6as4qb/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ybcyqzmh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel
           cwd: None
      Complete output (14 lines):
      Collecting setuptools>=45.0
        Using cached setuptools-60.6.0-py3-none-any.whl (953 kB)
      Collecting setuptools_scm[toml]>=6.3.1
        Using cached setuptools_scm-6.4.2-py3-none-any.whl (37 kB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting tomli>=1.0.0
        Using cached tomli-2.0.0-py3-none-any.whl (12 kB)
      Collecting packaging>=20.0
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
      Installing collected packages: pyparsing, tomli, setuptools, packaging, setuptools-scm, wheel
      ERROR: Cannot set --home and --prefix together
      ----------------------------------------
    WARNING: Discarding file:///home/vscode/.cache/pre-commit/repog5wip0x7. Command errored out with exit status 1: /home/vscode/.cache/pre-commit/repog5wip0x7/py_env-python3/bin/python /tmp/pip-standalone-pip-ez6as4qb/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ybcyqzmh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output.
    ERROR: Command errored out with exit status 1: /home/vscode/.cache/pre-commit/repog5wip0x7/py_env-python3/bin/python /tmp/pip-standalone-pip-ez6as4qb/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ybcyqzmh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=45.0' 'setuptools_scm[toml]>=6.3.1' wheel Check the logs for full command output.
```

**Comment by asottile** [comment]
you're [misconfiguring pip](https://github.com/jabertuhin/dvdrental-backend/blob/1c02fad9365d2ed032ef27d71060c99037c52022/.devcontainer/Dockerfile#L9)

**Comment by jabertuhin** [comment]
@asottile  Thanks for the quick reply. I think I have solved the issue.
