### ISSUE TITLE
Paths containing braces are causing problems

### ISSUE THREAD

**Issue by SafetyDog** [pre-commit/pre-commit#2234]
### describe your issue

I am trying to use pre-commit on a Windows 10 VPC.

Unfortunately, all my files on this VPC are created in a directories like C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin
The brackets in the file path are causing a problem for pre-commit when it tries to install python libraries for the hooks I specified.

The pre-commit.log contains the following:
```
File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 260, in subst_vars
    raise ValueError(f"invalid variable {var}")
ValueError: invalid variable '8e399ec3-0000-0000-0000-100000000000'
```

I tried getting around this by setting the PRE_COMMIT_HOME environment variable.  This setting is effective, but doesn't solve the problem for me.  When I set PRE_COMMIT_HOME to C:\Users\corbin\git\pre-commit, pre-commit's installation processes see it as C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\

I am able to manage my own python virtual environments and install python libraries to them on this VPC.  As a test, I installed the python libraries referenced by my pre-commit hooks without a problem to a separate virtual environment. 

I'm not sure why pre-commit's python environment is working differently.  I haven't tried reproducing this problem on other operating systems by creating a path with brackets in it.  

Thanks in advance for your time looking at this problem.

### pre-commit --version

pre-commit 2.10.1

### .pre-commit-config.yaml

```yaml
exclude: ^app_dir/static/pio-cts/lib/|^app_dir/static/ckeditor/|^app_dir/static/select2-autocomplete/|^.*.min.js|^.*\b(migrations)\b.*$
repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black.exe
      language: python
      language_version: python3.8
      types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: mixed-line-ending
      types_or: [python, html, css, javascript]

  - repo: local
    hooks:
    - id: remove-tabs
      args: [ '--whitespaces-count', '4' ]
      name: Remove Tabs
      entry: python pre_commit_hooks/remove_tabs.py
      language: python
      types_or: [python, html, css, javascript]
   
  - repo: local
    hooks:
    - id: js-beautify
      name: js-beautify
      entry: js-beautify.exe
      language: python
      types: [javascript]
      args: [
          '--replace',
          '--end-with-newline',
          '--indent-size=2',
          '--indent-char= ',
          '--max-preserve-newlines=2'
        ]

  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort.exe
      language: python
      types: [python]
      args: [
          '--profile',
          'black'
        ]
```

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.34.1.windows.1
sys.version:
    3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
sys.executable: C:\users\corbin\git\fhcrc-loe\venv38\scripts\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\SnapVolumesTemp\\MountPoints\\{8e399ec3-0000-0000-0000-100000000000}\\SVROOT\\Users\\corbin\\git\\pre-commit\\repo_2uvt5po\\py_env-python3.8\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\snapvolumestemp\mountpoints\{8e399ec3-0000-0000-0000-100000000000}\svroot\users\corbin\git\pre-commit\repo_2uvt5po
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting pathspec<1,>=0.6
      Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
    Collecting typing-extensions>=3.7.4
      Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
    Collecting click>=7.1.2
      Using cached click-8.0.3-py3-none-any.whl (97 kB)
    Collecting typed-ast>=1.4.0
      Using cached typed_ast-1.5.2-cp38-cp38-win_amd64.whl (164 kB)
    Collecting toml>=0.10.1
      Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
    Collecting mypy-extensions>=0.4.3
      Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
    Collecting appdirs
      Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
    Collecting regex>=2020.1.8
      Using cached regex-2022.1.18-cp38-cp38-win_amd64.whl (273 kB)
    Collecting colorama
      Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
    Building wheels for collected packages: black
      Building wheel for black (pyproject.toml): started
      Building wheel for black (pyproject.toml): finished with status 'error'
    Failed to build black
    
stderr:
      ERROR: Command errored out with exit status 1:
       command: 'C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po\py_env-python3.8\Scripts\python.EXE' 'C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po\py_env-python3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\corbin\AppData\Local\Temp\tmpdrm5qb2y'
           cwd: C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po
      Complete output (86 lines):
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      copying src\_black_version.py -> build\lib
      creating build\lib\blackd
      copying src\blackd\__init__.py -> build\lib\blackd
      creating build\lib\black
      copying src\black\__init__.py -> build\lib\black
      copying src\black\__main__.py -> build\lib\black
      creating build\lib\blib2to3
      copying src\blib2to3\pygram.py -> build\lib\blib2to3
      copying src\blib2to3\pytree.py -> build\lib\blib2to3
      copying src\blib2to3\__init__.py -> build\lib\blib2to3
      creating build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\conv.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\driver.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\grammar.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\literals.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\parse.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\pgen.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\token.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\tokenize.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\__init__.py -> build\lib\blib2to3\pgen2
      C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools_scm\git.py:105: UserWarning: "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po" is shallow and may cause errors
        warnings.warn(f'"{wd.path}" is shallow and may cause errors')
      package init file 'src\black_primer\__init__.py' not found (or not a regular file)
      creating build\lib\black_primer
      copying src\black_primer\cli.py -> build\lib\black_primer
      copying src\black_primer\lib.py -> build\lib\black_primer
      copying src\black\py.typed -> build\lib\black
      copying src\blib2to3\Grammar.txt -> build\lib\blib2to3
      copying src\blib2to3\PatternGrammar.txt -> build\lib\blib2to3
      running install
      Traceback (most recent call last):
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 258, in subst_vars
          return _subst_compat(s).format_map(lookup)
      KeyError: '8e399ec3-0000-0000-0000-100000000000'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po\py_env-python3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po\py_env-python3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po\py_env-python3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 48, in <module>
          setup(
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 985, in run_command
          cmd_obj.ensure_finalized()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\command\install.py", line 45, in finalize_options
          orig.install.finalize_options(self)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\command\install.py", line 422, in finalize_options
          self.expand_basedirs()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\command\install.py", line 594, in expand_basedirs
          self._expand_attrs(['install_base', 'install_platbase', 'root'])
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\command\install.py", line 588, in _expand_attrs
          val = subst_vars(val, self.config_vars)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 260, in subst_vars
          raise ValueError(f"invalid variable {var}")
      ValueError: invalid variable '8e399ec3-0000-0000-0000-100000000000'
      ----------------------------------------
      ERROR: Failed building wheel for black
    ERROR: Could not build wheels for black, which is required to install pyproject.toml-based projects
    
```

```
Traceback (most recent call last):
  File "C:\users\corbin\git\fhcrc-loe\venv38\lib\site-packages\pre_commit\error_handler.py", line 70, in error_handler
    yield
  File "C:\users\corbin\git\fhcrc-loe\venv38\lib\site-packages\pre_commit\main.py", line 368, in main
    return hook_impl(
  File "C:\users\corbin\git\fhcrc-loe\venv38\lib\site-packages\pre_commit\commands\hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "C:\users\corbin\git\fhcrc-loe\venv38\lib\site-packages\pre_commit\commands\run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "C:\users\corbin\git\fhcrc-loe\venv38\lib\site-packages\pre_commit\repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "C:\users\corbin\git\fhcrc-loe\venv38\lib\site-packages\pre_commit\repository.py", line 82, in _hook_install
    lang.install_environment(
  File "C:\users\corbin\git\fhcrc-loe\venv38\lib\site-packages\pre_commit\languages\python.py", line 205, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "C:\users\corbin\git\fhcrc-loe\venv38\lib\site-packages\pre_commit\languages\helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\users\corbin\git\fhcrc-loe\venv38\lib\site-packages\pre_commit\util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\SnapVolumesTemp\\MountPoints\\{8e399ec3-0000-0000-0000-100000000000}\\SVROOT\\Users\\corbin\\git\\pre-commit\\repo_2uvt5po\\py_env-python3.8\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\snapvolumestemp\mountpoints\{8e399ec3-0000-0000-0000-100000000000}\svroot\users\corbin\git\pre-commit\repo_2uvt5po
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
    Collecting pathspec<1,>=0.6
      Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
    Collecting typing-extensions>=3.7.4
      Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
    Collecting click>=7.1.2
      Using cached click-8.0.3-py3-none-any.whl (97 kB)
    Collecting typed-ast>=1.4.0
      Using cached typed_ast-1.5.2-cp38-cp38-win_amd64.whl (164 kB)
    Collecting toml>=0.10.1
      Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
    Collecting mypy-extensions>=0.4.3
      Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
    Collecting appdirs
      Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
    Collecting regex>=2020.1.8
      Using cached regex-2022.1.18-cp38-cp38-win_amd64.whl (273 kB)
    Collecting colorama
      Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
    Building wheels for collected packages: black
      Building wheel for black (pyproject.toml): started
      Building wheel for black (pyproject.toml): finished with status 'error'
    Failed to build black
    
stderr:
      ERROR: Command errored out with exit status 1:
       command: 'C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po\py_env-python3.8\Scripts\python.EXE' 'C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po\py_env-python3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\corbin\AppData\Local\Temp\tmpdrm5qb2y'
           cwd: C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po
      Complete output (86 lines):
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      copying src\_black_version.py -> build\lib
      creating build\lib\blackd
      copying src\blackd\__init__.py -> build\lib\blackd
      creating build\lib\black
      copying src\black\__init__.py -> build\lib\black
      copying src\black\__main__.py -> build\lib\black
      creating build\lib\blib2to3
      copying src\blib2to3\pygram.py -> build\lib\blib2to3
      copying src\blib2to3\pytree.py -> build\lib\blib2to3
      copying src\blib2to3\__init__.py -> build\lib\blib2to3
      creating build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\conv.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\driver.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\grammar.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\literals.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\parse.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\pgen.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\token.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\tokenize.py -> build\lib\blib2to3\pgen2
      copying src\blib2to3\pgen2\__init__.py -> build\lib\blib2to3\pgen2
      C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools_scm\git.py:105: UserWarning: "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po" is shallow and may cause errors
        warnings.warn(f'"{wd.path}" is shallow and may cause errors')
      package init file 'src\black_primer\__init__.py' not found (or not a regular file)
      creating build\lib\black_primer
      copying src\black_primer\cli.py -> build\lib\black_primer
      copying src\black_primer\lib.py -> build\lib\black_primer
      copying src\black\py.typed -> build\lib\black
      copying src\blib2to3\Grammar.txt -> build\lib\blib2to3
      copying src\blib2to3\PatternGrammar.txt -> build\lib\blib2to3
      running install
      Traceback (most recent call last):
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 258, in subst_vars
          return _subst_compat(s).format_map(lookup)
      KeyError: '8e399ec3-0000-0000-0000-100000000000'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po\py_env-python3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po\py_env-python3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\git\pre-commit\repo_2uvt5po\py_env-python3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 48, in <module>
          setup(
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 985, in run_command
          cmd_obj.ensure_finalized()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\command\install.py", line 45, in finalize_options
          orig.install.finalize_options(self)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\command\install.py", line 422, in finalize_options
          self.expand_basedirs()
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\command\install.py", line 594, in expand_basedirs
          self._expand_attrs(['install_base', 'install_platbase', 'root'])
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\command\install.py", line 588, in _expand_attrs
          val = subst_vars(val, self.config_vars)
        File "C:\SnapVolumesTemp\MountPoints\{8e399ec3-0000-0000-0000-100000000000}\SVROOT\Users\corbin\AppData\Local\Temp\pip-build-env-oixjbukm\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 260, in subst_vars
          raise ValueError(f"invalid variable {var}")
      ValueError: invalid variable '8e399ec3-0000-0000-0000-100000000000'
      ----------------------------------------
      ERROR: Failed building wheel for black
    ERROR: Could not build wheels for black, which is required to install pyproject.toml-based projects
```

**Comment by asottile** [comment]
this is not a bug in pre-commit, please report it to the upstream (probably `setuptools` in this case)
