### ISSUE TITLE
Weird error even after chsh -s /bin/bash

### ISSUE THREAD

**Issue by justinpham-hs** [pre-commit/pre-commit#2246]
### describe your issue
So we use pre-commit in our org and when I'm attempting to `git commit -m` I get the following error message.  Our engineers are saying it's zsh and for me to uninstall or switch to bash but still no success.

An unexpected error has occurred: CalledProcessError: command: ('/usr/local/opt/python@3.9/bin/python3.9', '-mvirtualenv', '/Users/<user>/.cache/pre-commit/repo8ez31w25/py_env-python3.9')
return code: 1
expected return code: 0
stdout:
    ModuleNotFoundError: No module named 'virtualenv.activation.xonsh'
    
stderr: (none)
Check the log at /Users/<user>/.cache/pre-commit/pre-commit.log

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: autopep8-wrapper
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
```

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.35.1
sys.version:
    3.9.10 (main, Jan 15 2022, 11:48:00) 
    [Clang 13.0.0 (clang-1300.0.29.3)]
sys.executable: /usr/local/opt/python@3.9/bin/python3.9
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/opt/python@3.9/bin/python3.9', '-mvirtualenv', '/Users/<user>/.cache/pre-commit/repo8ez31w25/py_env-python3.9')
return code: 1
expected return code: 0
stdout:
    ModuleNotFoundError: No module named 'virtualenv.activation.xonsh'
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/usr/local/lib/python3.9/site-packages/pre_commit/main.py", line 368, in main
    return hook_impl(
  File "/usr/local/lib/python3.9/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/commands/run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/usr/local/lib/python3.9/site-packages/pre_commit/languages/python.py", line 203, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/usr/local/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/opt/python@3.9/bin/python3.9', '-mvirtualenv', '/Users/<user>/.cache/pre-commit/repo8ez31w25/py_env-python3.9')
return code: 1
expected return code: 0
stdout:
    ModuleNotFoundError: No module named 'virtualenv.activation.xonsh'
    
stderr: (none)
```

**Comment by asottile** [comment]
seems to be a bug in virtualenv -- perhaps due to two versions installed at once?  either way -- probably best to report there https://github.com/pypa/virtualenv
