### ISSUE TITLE
Not able to run the hooks on python locally using pre-commit try-repo

### ISSUE THREAD

**Issue by Gagan92** [pre-commit/pre-commit#2248]
### describe your issue

I wanted to test out the local repository hooks that was mentioned in pre-commit-config.yaml but had to commit everytime to check how it runs. Then i came across pre-commit try-repo and tried it. But it looks i need to have pre-commit-hooks.yaml in order to have it working. So i added the contents of the config.yaml to hooks.yaml

pre-commit-hooks.yaml

```
-   id: pylint
    name: pylint
    entry: pylint
    language: python
    types: [python]
    require_serial: true
    additional_dependencies: ['pylint']
    exclude: |
      (?x)^(
          ppmpro/tests/git_test.py|
          utilities/hook_scripts/check_constants.py
      )$
-   id: check_constant_python
    name: check_constant_python
    entry: python ./utilities/hook_scripts/check_constants.py
    language: python
    language_version: python3
    types: [ yaml ]
    verbose: true
```
So when i try to run locally pre-commit try-repo <path to repo> check_constant_python, initially i faced the error saying

```
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmprvc16fwa/repofu5vhxk7/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

But then i added the dummy setup.py, then on running the same command, it says

```
[INFO] This may take a few minutes...
[INFO] Restored changes from /var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmpi7dc9hjj/patch1645037599-97109.
An unexpected error has occurred: CalledProcessError: command: ('/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmpi7dc9hjj/repos87h9o0q/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /private/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmpi7dc9hjj/repos87h9o0q
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    
stderr:
    ERROR: No .egg-info directory found in /private/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/pip-pip-egg-info-mfuxyq1u
    
Check the log at /Users/gaganbg/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
            -   id: check-yaml
    -   repo: local
        hooks:
            - id: pylint
              name: pylint
              entry: pylint
              language: python
              types: [ python ]
              require_serial: true
              additional_dependencies: [ 'pylint' ]
              exclude: |
                  (?x)^(
                      ppmpro/tests/git_test.py|
                      utilities/hook_scripts/check_constants.py
                  )$
            - id: check_constant_python
              name: check_constant_python
              entry: python ./utilities/hook_scripts/check_constants.py
              language: python
              types: [ yaml ]
              verbose: true
```

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.30.0
sys.version:
    3.9.1 (default, Jan  6 2021, 06:02:35) 
    [Clang 11.0.0 (clang-1100.0.33.17)]
sys.executable: /Users/gaganbg/venv_3.8/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmphg_1ti4u/repo3taq0m2j/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /private/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmphg_1ti4u/repo3taq0m2j
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    
stderr:
    ERROR: No .egg-info directory found in /private/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/pip-pip-egg-info-fxi2tx9i
    
```

```
Traceback (most recent call last):
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/main.py", line 400, in main
    return try_repo(args)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/commands/try_repo.py", line 77, in try_repo
    return run(config_filename, store, args)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/commands/run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/languages/python.py", line 205, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmphg_1ti4u/repo3taq0m2j/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /private/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmphg_1ti4u/repo3taq0m2j
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    
stderr:
    ERROR: No .egg-info directory found in /private/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/pip-pip-egg-info-fxi2tx9i
```
(venv_3.8) LC02XF15LJG5J:automation gaganbg$ pre-commit --version
pre-commit 2.17.0
(venv_3.8) LC02XF15LJG5J:automation gaganbg$ cat  /Users/gaganbg/.cache/pre-commit/pre-commit.log
### version information

```
pre-commit version: 2.17.0
git --version: git version 2.30.0
sys.version:
    3.9.1 (default, Jan  6 2021, 06:02:35) 
    [Clang 11.0.0 (clang-1100.0.33.17)]
sys.executable: /Users/gaganbg/venv_3.8/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmpi7dc9hjj/repos87h9o0q/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /private/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmpi7dc9hjj/repos87h9o0q
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    
stderr:
    ERROR: No .egg-info directory found in /private/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/pip-pip-egg-info-mfuxyq1u
    
```

```
Traceback (most recent call last):
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/main.py", line 400, in main
    return try_repo(args)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/commands/try_repo.py", line 77, in try_repo
    return run(config_filename, store, args)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/commands/run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/languages/python.py", line 205, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/Users/gaganbg/venv_3.8/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmpi7dc9hjj/repos87h9o0q/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /private/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/tmpi7dc9hjj/repos87h9o0q
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    
stderr:
    ERROR: No .egg-info directory found in /private/var/folders/ql/3c_2jkfs6vx31w0rcpyfgtv40000gn/T/pip-pip-egg-info-mfuxyq1u
```

**Comment by asottile** [comment]
so `try-repo` is for developing distributable hooks (through `.pre-commit-hooks.yaml`) -- and for those you need to have an [installable](https://pre-commit.com/#python) piece of software (an empty `setup.py` is **not** installable)

but since you're just hacking on `repo: local` hooks you don't need `try-repo` at all.  you can just `pre-commit run {hookid} --all-files` directly

**Comment by Gagan92** [comment]
So in order to test my hooks locally, i need to commit file everytime and see how it behaves, is it?

**Comment by asottile** [comment]
no, read the last part of my message
