### ISSUE TITLE
Running autoupdate hangs for about 5-10 minutes for each repo

### ISSUE THREAD

**Issue by jlnbuiles** [pre-commit/pre-commit#2265]
### describe your issue

I am configuring a small pre-commit file with these 2 repos:

- SwiftLint
- SwiftFormat

And when I'm trying to update the versions on these repos the command line just hangs for a long time for each repo consistently. 

I manually interrupted it using 'Control + C', because i thought it had gotten stuck and after trying it a few times it ran when i left it open for a long time.

I pinged the repos via this:
git ls-remote <repo URL> 
and i received a response right away from the repos, so they don't seem to be the issue.

Is this normal behavior? does it take 5-10 minutes to search for updates for each repo?

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.49.2
    hooks:
    -   id: swiftformat
-   repo: https://github.com/realm/SwiftLint
    rev: 0.46.3
    hooks:
    -   id: swiftlint
```

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.32.0 (Apple Git-132)
sys.version:
    3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
sys.executable: /opt/homebrew/Cellar/pre-commit/2.17.0/libexec/bin/python3.10
os.name: posix
sys.platform: darwin
```

### error information

```
Interrupted (^C): KeyboardInterrupt: 
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/main.py", line 357, in main
    return autoupdate(
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/commands/autoupdate.py", line 169, in autoupdate
    new_info = info.update(tags_only=tags_only, freeze=freeze)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/commands/autoupdate.py", line 54, in update
    cmd_output_b(
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/util.py", line 150, in cmd_output_b
    stdout_b, stderr_b = proc.communicate()
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1149, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 2000, in _communicate
    ready = selector.select(timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
    with validate_context(f'File {filename}'):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 410, in load_from_filename
    validate(data, schema)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 242, in check
    with validate_context(context):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 73, in _check_required
    _check_optional(self, dct)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 53, in _check_optional
    with validate_context(f'At key: {self.key}'):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 79, in check_fn
    validate(val, self.schema)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 272, in check
    validate(val, self.of)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 242, in check
    with validate_context(context):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 106, in _check_conditional
    inner(self, dct)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 73, in _check_required
    _check_optional(self, dct)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 53, in _check_optional
    with validate_context(f'At key: {self.key}'):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 79, in check_fn
    validate(val, self.schema)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 272, in check
    validate(val, self.of)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 242, in check
    with validate_context(context):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 72, in _check_required
    _require_key(self, dct)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/cfgv.py", line 68, in _require_key
    raise ValidationError(f'Missing required key: {self.key}')
pre_commit.clientlib.InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/nicklockwood/SwiftFormat')
==> At key: hooks
==> At Hook(id=MISSING)
=====> Missing required key: id
```

**Comment by asottile** [comment]
**your log file seems edited -- please don't redact important information**

___

both of those repos are very large, if your network connection is slow then yes

you can reproduce the exact commands pre-commit uses with:

```bash
git init repo
git -C repo remote add origin https://github.com/nicklockwood/SwiftFormat
time git -C repo fetch origin HEAD --tags
```

with gigabit internet the last command takes 30 seconds -- I assume with a poor internet connection it will take longer

**Comment by jlnbuiles** [comment]
Thanks so much for the fast response.

I was trying to get a verbose, or more detailed run of the command but was unable to do it by appending the `--verbose` command after the `pre-commit` command and also failed after the `autoupdate` command. so i had no visibility.

It'd be nice to maybe give a little more insight into what is happening after the command starts running.

will try those commands, really appreciate it!

**Comment by jlnbuiles** [comment]
As a complement to this discussion maybe even outputting the very same text that i'm getting while i'm running this command you sent me:

```time git -C repo fetch origin HEAD --tags``` 

would be super super helpful. not sure if this is something you'd like to consider adding to the `autoupdate` command, but i'd love that!

I'm getting a live feed of the activity courtesy of `git` (i believe) of the status of the download/update in my command line. 

and after seeing it run, i see what you mean regarding the size of the repos. they are quite large. I had no idea!!!

**Comment by asottile** [comment]
no thanks, I'd like to keep commands as quiet as possible

if you need to debug them, use a debugger

**Comment by jlnbuiles** [comment]
I'm not very proficient with the command line, so I didn't know how to do this. 

Is there a specific debugger that you recommend I could look into? or is there a way to activate the `--verbose` command for the autoupdate command?

**Comment by asottile** [comment]
at a start I'd recommend learning at least about:

- [debugging python](https://youtu.be/0LPuG825eAk)
- [pstree](https://youtu.be/Omu4tXtlULU)
- `strace`
