### ISSUE TITLE
BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment

### ISSUE THREAD

**Issue by nschloe** [pre-commit/pre-commit#2276]
### describe your issue

I updated to Python 3.10, now I'm getting
```
 BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```
when trying to commit. I tried re-installing pre-commit
```
pre-commit install
```
and reinstalled all checkers
```
pip install --force flake8 black isort
```
I'm unhappy with the fact that the error messages gives no indication of what might be wrong (actual exception message, offending package etc.)

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
```

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.34.1
sys.version:
    3.10.2 (main, Feb 26 2022, 08:21:15) [GCC 11.2.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

```
Traceback (most recent call last):
  File "/home/nschloe/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/home/nschloe/.local/lib/python3.10/site-packages/pre_commit/main.py", line 368, in main
    return hook_impl(
  File "/home/nschloe/.local/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "/home/nschloe/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "/home/nschloe/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/home/nschloe/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 86, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

**Comment by asottile** [comment]
I suspect this is the same as #2270 -- can you try the commands in there?

**Comment by nschloe** [comment]
Closing as duplicate.
