### ISSUE TITLE
Pre-commit tries to use python 3.9 instead of 3.10

### ISSUE THREAD

**Issue by ShaiAvr** [pre-commit/pre-commit#2286]
### describe your issue

I was developing a project with python 3.9 initially and I installed `pre-commit` in a virtual environment. It went quite well. I recently upgraded to python 3.10 and uninstalled the old 3.9 version. I recreated the environment using `poetry` and it all went well. I ran `pre-commit install` with no issue but when I tried to test it using `pre-commit run --all-files`, it crashed and from the error message it seems like it's trying to use python 3.9, but I don't know why:
```
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/pycqa/isort.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/flakeheaven/flakeheaven.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('D:\\dev\\python\\PhysiScript\\.venv\\Scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\shai\\.cache\\pre-commit\\repox33guo1z\\py_env-python3.9', '-p', 'python3.9')
return code: 1
expected return code: 0
stdout:
    PEP-514 violation in Windows Registry at HKEY_CURRENT_USER/PythonCore/3.9/InstallPath error: missing
    PEP-514 violation in Windows Registry at HKEY_LOCAL_MACHINE/PythonCore/2.7/InstallPath error: missing
    PEP-514 violation in Windows Registry at HKEY_LOCAL_MACHINE/PythonCore/3.7/InstallPath error: missing
    PEP-514 violation in Windows Registry at HKEY_LOCAL_MACHINE/PythonCore/3.8/InstallPath error: missing
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.9'

stderr: (none)
Check the log at C:\Users\shai\.cache\pre-commit\pre-commit.log
```

I tried deleting the `.cache`  folder, deleting the virtual environment, and recreating it, but I get the same error. Is there any old configuration file that tries to use python 3.9 somewhere?

Here are the relevant parts of the `pyproject.toml` file:
```toml
[tool.poetry]
name = "physiscript"
version = "0.1.0"
description = ""
authors = ["Shai Avraham <shaia1112011@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ShaiAvr/PhysiScript"

[tool.poetry.dependencies]
python = "^3.10"  # Set this after installing 3.10 and uninstalling 3.9
numpy = "^1.22.2"

[tool.poetry.dev-dependencies]
ipython = "^8.1.1"
black = "^22.1.0"
mypy = "^0.931"
pre-commit = "^2.17.0"  # Note it is installed in a virtual environment. pre-commit is not installed globally
isort = "^5.10.1"
flakeheaven = "^0.11.1"

# Flake8 plugins
flake8-type-checking = "^1.3.2"
flake8-bugbear = "^22.1.11"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.8.0"
flake8-simplify = "^0.18.1"

[tool.flakeheaven]
format = "grouped"
show_source = true
max_line_length = 88
max_complexity = 18
exclude = [".git", ".venv", "__pycache__", "docs/source/conf.py", "old", "build", "dist"]

[tool.flakeheaven.plugins]
"flake8-*" = ["+*"]
mccabe = ["+*"]
pycodestyle = ["+*"]
pyflakes = ["+*"]

[tool.black]
extend-exclude = "__pycache__"
target-version = ["py310"]

[tool.isort]
profile = "black"
py_version = 310
line_length = 88

[tool.mypy]
python_version = 3.10
show_error_context = true
show_error_codes = true
show_column_numbers = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
plugins = "numpy.typing.mypy_plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.940
    hooks:
      - id: mypy
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 0.11.0
    hooks:
      - id: flakeheaven
```

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.23.0.windows.1
sys.version:
    3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
sys.executable: D:\dev\python\PhysiScript\.venv\Scripts\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('D:\\dev\\python\\PhysiScript\\.venv\\Scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\shai\\.cache\\pre-commit\\repox33guo1z\\py_env-python3.9', '-p', 'python3.9')
return code: 1
expected return code: 0
stdout:
    PEP-514 violation in Windows Registry at HKEY_CURRENT_USER/PythonCore/3.9/InstallPath error: missing
    PEP-514 violation in Windows Registry at HKEY_LOCAL_MACHINE/PythonCore/2.7/InstallPath error: missing
    PEP-514 violation in Windows Registry at HKEY_LOCAL_MACHINE/PythonCore/3.7/InstallPath error: missing
    PEP-514 violation in Windows Registry at HKEY_LOCAL_MACHINE/PythonCore/3.8/InstallPath error: missing
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.9'
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "D:\dev\python\PhysiScript\.venv\lib\site-packages\pre_commit\error_handler.py", line 70, in error_handler
    yield
  File "D:\dev\python\PhysiScript\.venv\lib\site-packages\pre_commit\main.py", line 396, in main
    return run(args.config, store, args)
  File "D:\dev\python\PhysiScript\.venv\lib\site-packages\pre_commit\commands\run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "D:\dev\python\PhysiScript\.venv\lib\site-packages\pre_commit\repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "D:\dev\python\PhysiScript\.venv\lib\site-packages\pre_commit\repository.py", line 82, in _hook_install
    lang.install_environment(
  File "D:\dev\python\PhysiScript\.venv\lib\site-packages\pre_commit\languages\python.py", line 203, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "D:\dev\python\PhysiScript\.venv\lib\site-packages\pre_commit\util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('D:\\dev\\python\\PhysiScript\\.venv\\Scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\shai\\.cache\\pre-commit\\repox33guo1z\\py_env-python3.9', '-p', 'python3.9')
return code: 1
expected return code: 0
stdout:
    PEP-514 violation in Windows Registry at HKEY_CURRENT_USER/PythonCore/3.9/InstallPath error: missing
    PEP-514 violation in Windows Registry at HKEY_LOCAL_MACHINE/PythonCore/2.7/InstallPath error: missing
    PEP-514 violation in Windows Registry at HKEY_LOCAL_MACHINE/PythonCore/3.7/InstallPath error: missing
    PEP-514 violation in Windows Registry at HKEY_LOCAL_MACHINE/PythonCore/3.8/InstallPath error: missing
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.9'
    
stderr: (none)
```

**Comment by asottile** [comment]
lol try reading your config maybe?

**Comment by ShaiAvr** [comment]
Ok... That's slightly embarrassing. This drove me insane yesterday. Thank you.

**Comment by B-Whitt** [comment]
@ShaiAvr so what was the solution?

**Comment by asottile** [comment]
@B-Whitt if you ^F their config for 3.9 it should be pretty clear
