### ISSUE TITLE
pre-commit requires system-installed dotnet

### ISSUE THREAD

**Issue by Walluce** [pre-commit/pre-commit#2314]
### describe your issue

I was trying to write a commit-msg hook in dotnet and got this error:
```
AssertionError: For now, pre-commit requires system-installed dotnet
```

### pre-commit --version

 2.17.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: c:\Dev\checkov\hook\my-hook
    rev: v1.0.1
    hooks:
    -   id: my-hook
        stages: [commit-msg]

default_language_version:
    dotnet: dotnet

default_stages: [commit, push, post-merge, post-checkout]
#fail_fast: true
```

### Execution:
```
pre-commit run --verbose --commit-msg-filename .\msg.txt --hook-stage commit-msg my-hook
``` 

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.29.0.windows.1
sys.version:
    3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 13:07:40) [MSC v.1929 64 bit (AMD64)]
sys.executable: C:\Users\user1p\AppData\Local\Programs\Python\Python310\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: AssertionError: For now, pre-commit requires system-installed dotnet
```

```
Traceback (most recent call last):
  File "C:\Users\user1p\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\error_handler.py", line 70, in error_handler
    yield
  File "C:\Users\user1p\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\main.py", line 396, in main
    return run(args.config, store, args)
  File "C:\Users\user1p\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\commands\run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "C:\Users\user1p\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\user1p\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\repository.py", line 82, in _hook_install
    lang.install_environment(
  File "C:\Users\user1p\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\languages\dotnet.py", line 42, in install_environment
    helpers.assert_version_default('dotnet', version)
  File "C:\Users\user1p\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\languages\helpers.py", line 70, in assert_version_default
    raise AssertionError(
AssertionError: For now, pre-commit requires system-installed dotnet
```

**Comment by asottile** [comment]
the message is not wrong? is there something you don't understand about it?

**Comment by Walluce** [comment]
I don't know what system-installed dotnet means. I don't mind installing it, but IMHO we need more information here as to what this means.

**Comment by asottile** [comment]
do you have dotnet installed on your system?

**Comment by Walluce** [comment]
What is system-installed? Is there another option, e.g. local install? How do I make sure it's system-installed?

**Comment by Walluce** [comment]
> fill out the issue template?
Apologies, I thought I did?

**Comment by Walluce** [comment]
I didn't think it mattered, since I was testing only my new hook?

This is it:
```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: c:\Dev\checkov\hook\my-hook
    rev: v1.0.1
    hooks:
    -   id: my-hook
        stages: [commit-msg]

default_language_version:
    dotnet: dotnet

default_stages: [commit, push, post-merge, post-checkout]
#fail_fast: true

```

**Comment by asottile** [comment]
ok why do you have `default_language_version:` ?

**Comment by asottile** [comment]
which example?

**Comment by Walluce** [comment]
It was this example:
```yaml
default_language_version:
    python: python3.7
```
It referred to python and not dotnet, but was thinking that maybe I could specify dotnet3.1 or dotnet6 or something, although I didn't see much in the documentation about what the valid options were

**Comment by asottile** [comment]
yeah there are no such valid values for `dotnet` -- that's what the error message is for

**Comment by Walluce** [comment]
Ok, thanks for solving my problem, but the error just isn't very clear, IMHO

**Comment by asottile** [comment]
yeah I guess it's just weird that you would have reached for an option you didn't need to solve a problem you didn't have -- I've added the selected values in #2315
