### ISSUE TITLE
golang not installed when installing gitleaks

### ISSUE THREAD

**Issue by ericatlastmile** [pre-commit/pre-commit#2334]
### describe your issue

> pre-commit is specifically designed to not require root access. If one of your developers doesn’t have node installed but modifies a JavaScript file, pre-commit automatically handles downloading and building node to run eslint without root.

I am assuming the same should be true for Golang to run gitleaks but it is not the behavior I am seeing on both Ubuntu 21.10 Impish and Mac OS 12.3.1

Example on Ubuntu:
```shell
$ mkvirtualenv --python=python3.9 gitleakstest 
$ pip install pre-commit
...
Successfully installed cfgv-3.3.1 distlib-0.3.4 filelock-3.6.0 identify-2.4.12 nodeenv-1.6.0 platformdirs-2.5.1 pre-commit-2.18.1 pyyaml-6.0 six-1.16.0 toml-0.10.2 virtualenv-20.14.0
$ mkdir a_test_repo
$ cd a_test_repo/
$ vi .pre-commit-config.yaml
$ cat .pre-commit-config.yaml 
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.6.1
    hooks:
      - id: gitleaks

$ git init
Initialized empty Git repository in /home/eric/repos/a_test_repo/.git/
$ git add .pre-commit-config.yaml
$ git commit -am "Adds pre-commit config."
[master (root-commit) d0cf24c] Adds pre-commit config.
 1 file changed, 6 insertions(+)
 create mode 100644 .pre-commit-config.yaml
$ pre-commit --version
pre-commit 2.18.1
$ pre-commit clean
Cleaned /home/eric/.cache/pre-commit.
$ pre-commit install --install-hooks
pre-commit installed at .git/hooks/pre-commit
[INFO] Initializing environment for https://github.com/zricethezav/gitleaks.
[INFO] Installing environment for https://github.com/zricethezav/gitleaks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('go', 'install', './...')
return code: 1
expected return code: 0
stdout:
    Executable `go` not found
stderr: (none)
Check the log at /home/eric/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.6.1
    hooks:
      - id: gitleaks
```

### version information

```
pre-commit version: 2.18.1
git --version: git version 2.32.0
sys.version:
    3.9.7 (default, Sep 10 2021, 14:59:43) 
    [GCC 11.2.0]
sys.executable: /home/eric/.virtualenvs/gitleakstest/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('go', 'install', './...')
return code: 1
expected return code: 0
stdout:
    Executable `go` not found
stderr: (none)
```

```
Traceback (most recent call last):
  File "/home/eric/.virtualenvs/gitleakstest/lib/python3.9/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/eric/.virtualenvs/gitleakstest/lib/python3.9/site-packages/pre_commit/main.py", line 353, in main
    return install(
  File "/home/eric/.virtualenvs/gitleakstest/lib/python3.9/site-packages/pre_commit/commands/install_uninstall.py", line 140, in install
    install_hooks(config_file, store)
  File "/home/eric/.virtualenvs/gitleakstest/lib/python3.9/site-packages/pre_commit/commands/install_uninstall.py", line 146, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/home/eric/.virtualenvs/gitleakstest/lib/python3.9/site-packages/pre_commit/repository.py", line 221, in install_hook_envs
    _hook_install(hook)
  File "/home/eric/.virtualenvs/gitleakstest/lib/python3.9/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/home/eric/.virtualenvs/gitleakstest/lib/python3.9/site-packages/pre_commit/languages/golang.py", line 83, in install_environment
    cmd_output_b('go', 'install', './...', cwd=repo_src_dir, env=env)
  File "/home/eric/.virtualenvs/gitleakstest/lib/python3.9/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('go', 'install', './...')
return code: 1
expected return code: 0
stdout:
    Executable `go` not found
stderr: (none)
```

**Comment by asottile** [comment]
https://pre-commit.com/#golang

> Support: golang hooks are known to work on any system which has go installed.
