### ISSUE TITLE
Error installing environment

### ISSUE THREAD

**Issue by he110** [pre-commit/pre-commit#2350]
### describe your issue

I guess it happened after doing `brew upgrade`... Do not get how to solve it.

```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
Check the log at ~/.cache/pre-commit/pre-commit.log
```

MacOS 11.6.2

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
```

### version information

```
pre-commit version: 2.18.1
git --version: git version 2.28.0
sys.version:
    3.10.2 (main, Feb  2 2022, 08:42:42) [Clang 13.0.0 (clang-1300.0.29.3)]
sys.executable: /usr/local/Cellar/pre-commit/2.18.1/libexec/bin/python3
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/main.py", line 343, in main
    return hook_impl(
  File "/usr/local/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "/usr/local/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/usr/local/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 221, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 83, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

**Comment by asottile** [comment]
I suspect this is a duplicate of #2270 -- can you try the commands there and see if it's the same problem?

**Comment by he110** [comment]
Thanks a lot! It helped.

A little summary of how to solve:

1. I've checked python and virtualenv
```
/usr/local/Cellar/pre-commit/2.18.1/libexec/bin/python3.10 --version --version
/usr/local/Cellar/pre-commit/2.18.1/libexec/bin/python3.10 -m virtualenv vvv
vvv/bin/python3 --version --version
cat vvv/pyvenv.cfg


Python 3.10.2 (main, Feb  2 2022, 08:42:42) [Clang 13.0.0 (clang-1300.0.29.3)]
FileNotFoundError: [Errno 2] No such file or directory
zsh: no such file or directory: vvv/bin/python3
cat: vvv/pyvenv.cfg: No such file or directory
```

2. There is no vEnv directory, so trying to reset it 
```
cd /usr/local/Cellar/pre-commit/2.18.1/libexec/bin/
virtualenv --reset-app-data vvv -vvvv --without-pip --clear

zsh: command not found: virtualenv
```

3. Here's where the problem was. So just installing virtualenv
```
brew install virtualenv
```
