### ISSUE TITLE
Flake8 --per-file-ignores critical error in pre-commit #757

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [pre-commit/pre-commit#2361]
### describe your issue

A follow up to https://github.com/pre-commit/pre-commit-hooks/issues/757 in the correct place

I have added the space after the colon however I get a different error that prevents me from running pre-commit 

```
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://gitlab.com/PyCQA/flake8')
==> At key: hooks
==> At Hook(id='flake8')
==> At key: args
==> At index 0
=====> Expected string got dict
```

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
---
repos:
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=nd,reacher,thist,ths
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --pre-file-ignores="*/__init__.py: F401"
          - --ignore=E203,E741,W503,E302,E704
          - --max-complexity=30
          - --max-line-length=456
          - --show-source
          - --statistics
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        # TODO: remove `--keep-runtime-typing` option
        args: ["--py37-plus", "--keep-runtime-typing"]
```

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.35.1
sys.version:
    3.9.7 (default, Sep 16 2021, 08:50:36) 
    [Clang 10.0.0 ]
sys.executable: /Users/marktowers/opt/anaconda3/envs/gym/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://gitlab.com/PyCQA/flake8')
==> At key: hooks
==> At Hook(id='flake8')
==> At key: args
==> At index 0
=====> Expected string got dict
```

```
Traceback (most recent call last):
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/pre_commit/commands/run.py", line 400, in run
    config = load_config(config_file)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 410, in load_from_filename
    validate(data, schema)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 73, in _check_required
    _check_optional(self, dct)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 79, in check_fn
    validate(val, self.schema)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 272, in check
    validate(val, self.of)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 106, in _check_conditional
    inner(self, dct)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 73, in _check_required
    _check_optional(self, dct)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 79, in check_fn
    validate(val, self.schema)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 272, in check
    validate(val, self.of)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/Users/marktowers/opt/anaconda3/envs/gym/lib/python3.9/site-packages/cfgv.py", line 325, in check_type_fn
    raise ValidationError(
pre_commit.clientlib.InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://gitlab.com/PyCQA/flake8')
==> At key: hooks
==> At Hook(id='flake8')
==> At key: args
==> At index 0
=====> Expected string got dict
```

**Comment by asottile** [comment]
the error is not wrong, if you look at the zeroth element of args:

```yaml
          - --pre-file-ignores="*/__init__.py: F401"
```

that is a yaml dictionary looking like `{'--pre-file-ignores="*/__init__.py': 'F401"'}`

**Comment by pseudo-rnd-thoughts** [comment]
It is throwing a new error
`'{--pre-file-ignores="*/__init__.py": "F401"}'` 
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 2

usage: flake8 [options] file file ...
flake8: error: unrecognized arguments: gym/envs/mujoco/reacher.py tests/vector/test_spaces.py gym/spaces/multi_discrete.py gym/envs/mujoco/humanoidstandup.py gym/wrappers/time_aware_observation.py gym/envs/classic_control/acrobot.py gym/envs/mujoco/inverted_pendulum.py gym/wrappers/transform_reward.py tests/__init__.py gym/wrappers/monitoring/__init__.py gym/envs/mujoco/half_cheetah_v3.py tests/envs/test_mujoco_v2_to_v3_conversion.py gym/envs/mujoco/half_cheetah.py gym/envs/classic_control/continuous_mountain_car.py gym/vector/vector_env.py gym/vector/async_vector_env.py gym/wrappers/record_video.py gym/utils/env_checker.py gym/wrappers/normalize.py gym/vector/utils/__init__.py tests/wrappers/test_record_video.py tests/wrappers/test_clip_action.py gym/wrappers/rescale_action.py tests/utils/__init__.py tests/envs/test_determinism.py gym/envs/toy_text/frozen_lake.py tests/wrappers/test_order_enforcing.py gym/utils/ezpickle.py tests/wrappers/test_resize_observation.py tests/wrappers/__init__.py gym/envs/classic_control/mountain_car.py gym/wrappers/monitoring/video_recorder.py tests/vector/__init__.py tests/vector/test_vector_env.py tests/wrappers/flatten_test.py gym/utils/seeding.py gym/envs/mujoco/swimmer.py gym/envs/mujoco/ant.py tests/spaces/test_utils.py gym/envs/mujoco/ant_v3.py gym/wrappers/time_limit.py gym/core.py tests/envs/spec_list.py tests/vector/test_vector_env_wrapper.py gym/envs/toy_text/blackjack.py tests/wrappers/test_rescale_action.py gym/wrappers/order_enforcing.py gym/envs/mujoco/walker2d.py tests/wrappers/test_frame_stack.py tests/wrappers/nested_dict_test.py tests/envs/test_registration.py tests/vector/test_sync_vector_env.py tests/utils/test_play.py gym/wrappers/autoreset.py gym/spaces/box.py gym/envs/toy_text/utils.py gym/vector/utils/shared_memory.py tests/envs/test_action_dim_check.py gym/utils/colorize.py tests/spaces/__init__.py gym/wrappers/gray_scale_observation.py gym/vector/__init__.py gym/version.py gym/envs/classic_control/pendulum.py gym/wrappers/transform_observation.py tests/vector/test_async_vector_env.py gym/envs/toy_text/taxi.py gym/utils/play.py gym/envs/mujoco/__init__.py tests/wrappers/test_transform_observation.py tests/wrappers/test_pixel_observation.py gym/wrappers/filter_observation.py tests/envs/test_envs.py gym/envs/mujoco/humanoid_v3.py tests/envs/test_atari_legacy_env_specs.py gym/envs/box2d/__init__.py gym/envs/toy_text/cliffwalking.py tests/wrappers/test_time_aware_observation.py gym/wrappers/__init__.py tests/wrappers/test_normalize.py tests/wrappers/test_atari_preprocessing.py tests/wrappers/test_record_episode_statistics.py gym/envs/__relocated__.py tests/envs/test_frozenlake_dfs.py gym/wrappers/frame_stack.py gym/wrappers/flatten_observation.py gym/logger.py gym/wrappers/atari_preprocessing.py gym/wrappers/record_episode_statistics.py tests/wrappers/test_flatten_observation.py tests/envs/test_lunar_lander.py tests/utils/test_env_checker.py tests/wrappers/test_video_recorder.py gym/spaces/discrete.py gym/spaces/space.py gym/envs/classic_control/__init__.py gym/envs/mujoco/pusher.py tests/envs/__init__.py gym/__init__.py tests/wrappers/test_gray_scale_observation.py gym/vector/utils/numpy_utils.py gym/envs/mujoco/inverted_double_pendulum.py gym/vector/utils/spaces.py gym/envs/mujoco/mujoco_env.py gym/envs/box2d/car_racing.py gym/envs/__init__.py gym/wrappers/clip_action.py setup.py gym/envs/toy_text/__init__.py gym/envs/box2d/car_dynamics.py tests/vector/utils.py gym/envs/box2d/bipedal_walker.py gym/spaces/dict.py gym/envs/mujoco/swimmer_v3.py tests/wrappers/test_time_limit.py tests/spaces/test_spaces.py gym/vector/utils/misc.py tests/vector/test_shared_memory.py gym/spaces/tuple.py gym/error.py gym/envs/classic_control/cartpole.py gym/spaces/multi_binary.py gym/envs/box2d/lunar_lander.py gym/spaces/__init__.py gym/spaces/utils.py gym/envs/mujoco/walker2d_v3.py tests/utils/test_seeding.py gym/envs/mujoco/hopper_v3.py tests/wrappers/test_transform_reward.py tests/vector/test_numpy_utils.py gym/envs/mujoco/hopper.py gym/envs/mujoco/humanoid.py tests/test_core.py gym/envs/registration.py gym/vector/sync_vector_env.py tests/wrappers/test_filter_observation.py gym/wrappers/resize_observation.py gym/wrappers/pixel_observation.py gym/utils/__init__.py tests/wrappers/test_autoreset.py
```

**Comment by asottile** [comment]
no, now you've gone even further in the wrong direction.  you have a typo in your option name and the curly braces are not what you want --  I was just showing you how your yaml is parsed which you're doing incorrectly

you *probably* want:

```yaml
        - '--per-file-ignores=*/__init__.py:F401'
```

**Comment by pseudo-rnd-thoughts** [comment]
Thanks, I hadn't seen your message on the previous issue. It all works now
