### ISSUE TITLE
new pyflakes causes exceptions on clean run

### ISSUE THREAD

**Issue by arahayrabedian** [pre-commit/pre-commit#237]
Originally accidentally opened this on the pre-commit-hooks repo, closed that and opened here as I think that makes more sense:

Hey, had just forked pre-commit-hooks and was pulling my hair out wondering what I broke while I was testing a hook I wrote, turns out pyflakes just released [0.9.0](https://github.com/pyflakes/pyflakes/releases/tag/0.9.0), which causes me to get the below when trying to run any of my hooks when running fresh.

```
Traceback (most recent call last):
  File "/home/user/.pre-commit/repoHJDFOT/py_env-default/bin/trailing-whitespace-fixer", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/user/.pre-commit/repoHJDFOT/py_env-default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/home/user/.pre-commit/repoHJDFOT/py_env-default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3060, in _call_aside
    f(*args, **kwargs)
  File "/home/user/.pre-commit/repoHJDFOT/py_env-default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/user/.pre-commit/repoHJDFOT/py_env-default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 647, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/user/.pre-commit/repoHJDFOT/py_env-default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 660, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/user/.pre-commit/repoHJDFOT/py_env-default/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 838, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyflakes 0.9.0 (/home/user/.pre-commit/repoHJDFOT/py_env-default/lib/python2.7/site-packages), Requirement.parse('pyflakes<0.9,>=0.8.1'), set(['flake8']))
```

not sure who would need to tackle this so picking on the thing closest first. lemme know if i need to raise this with someone else.

Temporarily resolved this by manually installing pyflakes 0.8.1 in the pre-commit virtualenv.

**Comment by asottile** [comment]
https://github.com/pre-commit/pre-commit-hooks/issues/59
