### ISSUE TITLE
Support for `.yml` file extension

### ISSUE THREAD

**Issue by adam-grant-hendry** [pre-commit/pre-commit#2372]
### describe your issue

Both `*.yml` and `*.yaml` are valid YAML file extensions. However, running

```posh
> pre-commit run --all-files
```

with a `.pre-commit-config.yml` file yields the error

```posh
An error has occurred: InvalidConfigError:  
=====> .pre-commit-config.yml is not a file
Check the log at C:\Users\hendra11\.cache\pre-commit\pre-commit.log
```

[pre-commit.log](https://github.com/pre-commit/pre-commit/files/8617701/pre-commit.log)

### pre-commit --version

pre-commit 2.18.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [
        "flake8-black==0.3.2",
        "flake8-isort==4.1.1",
        "flake8-quotes==3.3.1",
      ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    - id: codespell
      args: [
        "docs emmy tests",
        "*.py *.rst *.md",
      ]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    - id: pydocstyle
      additional_dependencies: [toml==0.10.2]
      files: ^(pyvista/|other/)
      exclude: ^pyvista/ext/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        exclude: ^(doc/|tests/|examples/|pyvista/ext/)
        additional_dependencies: [
          "mypy-extensions==0.4.3",
          "toml==0.10.2",
          "typing-extensions==4.1.1",
        ]

  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
    - id: shell-lint
      args: [--format=json]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-ast
    - id: check-docstring-first
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: name-tests-test
    - id: no-commit-to-branch
    - id: trailing-whitespace
      args: [--branch, main]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.14.3
    hooks:
      - id: check-gitlab-ci
      - id: check-readthedocs

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint emmy/
        language: system
        always_run: true
        pass_filenames: false
      - id: create requirements
        name: create requirements
        entry: sh write_requirements.sh
        language: system
        always_run: true
        pass_filenames: false
```

### version information

```
pre-commit version: 2.18.1
git --version: git version 2.36.0.windows.1
sys.version:
    3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
sys.executable: c:\users\hendra11\code\emmy\.venv\scripts\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An error has occurred: InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
```

```
Traceback (most recent call last):
  File "c:\users\hendra11\code\emmy\.venv\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "c:\users\hendra11\code\emmy\.venv\lib\site-packages\pre_commit\main.py", line 371, in main
    return run(args.config, store, args)
  File "c:\users\hendra11\code\emmy\.venv\lib\site-packages\pre_commit\commands\run.py", line 398, in run
    config = load_config(config_file)
  File "c:\users\hendra11\code\emmy\.venv\lib\site-packages\cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "C:\Program Files\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\hendra11\code\emmy\.venv\lib\site-packages\cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "c:\users\hendra11\code\emmy\.venv\lib\site-packages\cfgv.py", line 40, in reraise_as
    yield
  File "c:\users\hendra11\code\emmy\.venv\lib\site-packages\cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} is not a file')
pre_commit.clientlib.InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
```

**Comment by asottile** [comment]
please search the issue tracker

**Comment by adam-grant-hendry** [comment]
> please search the issue tracker

Is this a dup?

**Comment by VeckoTheGecko** [comment]
Duplicate of #702
