### ISSUE TITLE
pre-commit errors on libsonnet, tf and tfvars files.

### ISSUE THREAD

**Issue by BeyondEvil** [pre-commit/pre-commit#2373]
### describe your issue

Setting `types` for local `binaries` fails with:

```
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='local')
==> At key: hooks
==> At Hook(id='tk')
==> At key: types_or
==> At index 0
=====> Type tag 'libsonnet' is not recognized.  Try upgrading identify and pre-commit?
```

`tk` is the tanka binary (which, among other things, formats jsonnet and libsonnet files).

Note that I'm using the zipapp. Which btw doesn't seem to support `--version`:

```
❯ pre-commit --version
shellcheck...........................................(no files to check)Skipped
shfmt................................................(no files to check)Skipped
```

### pre-commit --version

2.18.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:

      - id: shellcheck
        name: shellcheck
        entry: shellcheck --external-source --shell=bash
        language: system
        types_or: [sh, shell, bash]

      - id: shfmt
        name: shfmt
        entry: shfmt -bn -ci -sr -i 2
        language: system
        types_or: [sh, shell, bash]

      - id: tk
        name: tk
        entry: tk fmt --test
        language: system
        types_or: [libsonnet, jsonnet]

      - id: terraform
        name: terraform
        entry: terraform fmt -check -diff
        verbose: true
        language: system
        types_or: [tf, tfvars]
```

### version information

```
pre-commit version: 2.18.0
git --version: git version 2.32.0 (Apple Git-132)
sys.version:
    3.9.12 (main, Mar 26 2022, 15:44:31) 
    [Clang 13.1.6 (clang-1316.0.21.2)]
sys.executable: /Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/python
os.name: posix
sys.platform: darwin
```

### error information

```
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='local')
==> At key: hooks
==> At Hook(id='tk')
==> At key: types_or
==> At index 0
=====> Type tag 'libsonnet' is not recognized.  Try upgrading identify and pre-commit?
```

```
Traceback (most recent call last):
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/pre_commit-2.18.0-py2.py3-none-any.whl/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/pre_commit-2.18.0-py2.py3-none-any.whl/pre_commit/main.py", line 371, in main
    return run(args.config, store, args)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/pre_commit-2.18.0-py2.py3-none-any.whl/pre_commit/commands/run.py", line 398, in run
    config = load_config(config_file)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 40, in reraise_as
    yield
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 31, in validate_context
    yield
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 410, in load_from_filename
    validate(data, schema)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 244, in check
    item.check(v)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 31, in validate_context
    yield
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 73, in _check_required
    _check_optional(self, dct)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 31, in validate_context
    yield
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 79, in check_fn
    validate(val, self.schema)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 272, in check
    validate(val, self.of)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 244, in check
    item.check(v)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 31, in validate_context
    yield
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 106, in _check_conditional
    inner(self, dct)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 73, in _check_required
    _check_optional(self, dct)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 31, in validate_context
    yield
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 79, in check_fn
    validate(val, self.schema)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 272, in check
    validate(val, self.of)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 244, in check
    item.check(v)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 31, in validate_context
    yield
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 31, in validate_context
    yield
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 31, in validate_context
    yield
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/cfgv-3.3.1-py2.py3-none-any.whl/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/Users/jimbrannlund/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/wheels/pre_commit-2.18.0-py2.py3-none-any.whl/pre_commit/clientlib.py", line 30, in check_type_tag
    raise cfgv.ValidationError(
pre_commit.clientlib.InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='local')
==> At key: hooks
==> At Hook(id='tk')
==> At key: types_or
==> At index 0
=====> Type tag 'libsonnet' is not recognized.  Try upgrading identify and pre-commit?
```

**Comment by BeyondEvil** [comment]
> as the error message says (it's not wrong!) that type tag does not exist -- https://github.com/pre-commit/identify is the file identification library

Maybe I'm misunderstanding then, but they're enumerated here:

https://github.com/pre-commit/identify/blob/main/identify/extensions.py#L112
https://github.com/pre-commit/identify/blob/main/identify/extensions.py#L200-L201

> not sure what's up with your zipapp though -- I suspect you've got a wrapper which is gobbling those args?
> 
> ```
> $ ./pre-commit-2.18.0.pyz --version
> pre-commit 2.18.0
> ```

Damn, yes, you're right. Sorry about that.

**Comment by asottile** [comment]
ah yeah, the version of identify ships with the zipapp

I just realized I didn't upload one for 2.18.1 so I can do that now which will have a newer identify version

**Comment by asottile** [comment]
should be available now -- that one will contain identify==2.5.0

**Comment by BeyondEvil** [comment]
> should be available now -- that one will contain identify==2.5.0

Thanks, will try right away! 🙇

**Comment by BeyondEvil** [comment]
Same issue. :(

```
> pre-commit --version
pre-commit 2.18.1
```

Am I doing something wrong in the config?

Both binaries are available on the path.

```
❯ tk --version              
tk version v0.19.0

❯ terraform --version       
Terraform v1.1.6
on darwin_arm64
```

**Comment by asottile** [comment]
works fine for me?
```
$ cat .pre-commit-config.yaml 
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
        types_or: [terraform, jsonnet]
$ ./pre-commit-2.18.1.pyz run --files README.md 
trim trailing whitespace.............................(no files to check)Skipped
```

**Comment by asottile** [comment]
you can use the `meta` `identity` hook to see the exact command

> As I read the docs, each hook gets called once per modified file.

your reading of the docs is incorrect -- one call per file would be exceedingly wasteful and slow, pre-commit passes filenames as positional arguments to tools

**Comment by BeyondEvil** [comment]
> you can use the `meta` `identity` hook to see the exact command
> 

Thanks! 👍 

> > As I read the docs, each hook gets called once per modified file.
> 
> your reading of the docs is incorrect -- one call per file would be exceedingly wasteful and slow, pre-commit passes filenames as positional arguments to tools

Good! 😅 

Got it all working now, thanks for all your help. Much appreciated! 🙇 

```yaml
      - id: tk
        name: tk
        entry: tk fmt --test
        language: system
        types_or: [jsonnet]

      - id: terraform
        name: terraform
        entry: terraform fmt -recursive -check -diff
        args: ['tf/']
        pass_filenames: false
        language: system
        types_or: [terraform]
```
