### ISSUE TITLE
expected environment for python to be healthy() immediately after install

### ISSUE THREAD

**Issue by ignacionf** [pre-commit/pre-commit#2374]
### describe your issue

After update debian package python3 3.9.x to 3.10.x i get this error in every git commit.
I make a new env, clean my env, delete ~/.local, etc. i still get this error.

### pre-commit --version

2.18.1

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
```

### version information

```
pre-commit version: 2.18.1
git --version: git version 2.35.1
sys.version:
    3.10.4 (main, Mar 24 2022, 13:07:27) [GCC 11.2.0]
sys.executable: /tmp/e2/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

```
Traceback (most recent call last):
  File "/tmp/e2/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/tmp/e2/lib/python3.10/site-packages/pre_commit/main.py", line 371, in main
    return run(args.config, store, args)
  File "/tmp/e2/lib/python3.10/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/tmp/e2/lib/python3.10/site-packages/pre_commit/repository.py", line 221, in install_hook_envs
    _hook_install(hook)
  File "/tmp/e2/lib/python3.10/site-packages/pre_commit/repository.py", line 83, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

**Comment by asottile** [comment]
please search the issue tracker #2336 #2299
