### ISSUE TITLE
AssertionError: BUG: expected environment for python to be healthy() immediately after install.

### ISSUE THREAD

**Issue by MahdiJafari1** [pre-commit/pre-commit#2385]
### search tried in the issue tracker

pre-commit

### describe your issue

I am developing a Django project on ubuntu 22.04. I faced this issue when I wanted to commit my changes.

`(blog) ➜  blog git:(main) ✗ pre-commit run
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
Check the log at /home/mahdi/.cache/pre-commit/pre-commit.log`

`### version information

```
pre-commit version: 2.18.1
git --version: git version 2.34.1
sys.version:
    3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
sys.executable: /home/mahdi/.local/share/virtualenvs/blog-qatotdDy/bin/python
os.name: posix
sys.platform: linux
```

### pre-commit --version

2.18.1

### .pre-commit-config.yaml

```yaml
exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
```

### version information

```
pre-commit version: 2.18.1
git --version: git version 2.34.1
sys.version:
    3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
sys.executable: /home/mahdi/.local/share/virtualenvs/blog-qatotdDy/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

```
Traceback (most recent call last):
  File "/home/mahdi/.local/share/virtualenvs/blog-qatotdDy/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/mahdi/.local/share/virtualenvs/blog-qatotdDy/lib/python3.10/site-packages/pre_commit/main.py", line 371, in main
    return run(args.config, store, args)
  File "/home/mahdi/.local/share/virtualenvs/blog-qatotdDy/lib/python3.10/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/home/mahdi/.local/share/virtualenvs/blog-qatotdDy/lib/python3.10/site-packages/pre_commit/repository.py", line 221, in install_hook_envs
    _hook_install(hook)
  File "/home/mahdi/.local/share/virtualenvs/blog-qatotdDy/lib/python3.10/site-packages/pre_commit/repository.py", line 83, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

**Comment by asottile** [comment]
you searched "pre-commit" in the issue tracker? jfc put some effort in

**Comment by latkinso42** [comment]
So, what is the solution? I still have the same issue. Ubuntu 22.04; Python 3.10.4; pre-commit 2.17.0.

**Comment by asottile** [comment]
@latkinso42 search the issue tracker, find the duplicate, the answer is in there
