### ISSUE TITLE
Node/Npm hooks still fails in Windows

### ISSUE THREAD

**Issue by cristianmatache** [pre-commit/pre-commit#2402]
### search tried in the issue tracker

2351

### describe your issue

On Windows I am still experiencing an issue similar to #2351 . I tried https://stackoverflow.com/questions/71939099/bitbucket-pipeline-error-installing-pre-commit-ts-lint but setting any version still fails with the same error.

I was running this from:
cmd as well as Git Bash, in a conda environment

I also tried using the system node (with node 16.3.0 and 18.2.0) too but then it complains about:
```
D:\workspace\cookiecutter-alpha-build-polyrepo-py>pre-commit run --all-files
[WARNING] The 'rev' field of repo 'https://github.com/maximevast/pre-commit-tslint' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.
[INFO] Installing environment for https://github.com/maximevast/pre-commit-tslint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('d:\\miniconda3\\python.exe', '-mnodeenv', '--prebuilt', '--clean-src', '\\\\?\\C:\\Users\\Cristian Matache\\.cache\\pre-commit\\repov2e2zaal\\node_env-system', '-n', 'system')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Installing system node.js on win32 is not supported!

Check the log at C:\Users\Cristian Matache\.cache\pre-commit\pre-commit.log
```

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/maximevast/pre-commit-tslint
    rev: ''
    hooks:
    -   id: tslint
        language_version: 16.3.0
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.31.0.windows.1
sys.version:
    3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
sys.executable: d:\miniconda3\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Cristian Matache\\.cache\\pre-commit\\repov2e2zaal\\node_env-16.3.0\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout:

    up to date, audited 1 package in 3s

    found 0 vulnerabilities

stderr:
    The system cannot find the path specified.
    The system cannot find the path specified.
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.

```

```
Traceback (most recent call last):
  File "d:\miniconda3\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "d:\miniconda3\lib\site-packages\pre_commit\main.py", line 389, in main
    return run(args.config, store, args)
  File "d:\miniconda3\lib\site-packages\pre_commit\commands\run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "d:\miniconda3\lib\site-packages\pre_commit\repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "d:\miniconda3\lib\site-packages\pre_commit\repository.py", line 79, in _hook_install
    lang.install_environment(
  File "d:\miniconda3\lib\site-packages\pre_commit\languages\node.py", line 111, in install_environment
    helpers.run_setup_cmd(prefix, local_install_cmd)
  File "d:\miniconda3\lib\site-packages\pre_commit\languages\helpers.py", line 51, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "d:\miniconda3\lib\site-packages\pre_commit\util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\Cristian Matache\\.cache\\pre-commit\\repov2e2zaal\\node_env-16.3.0\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout:

    up to date, audited 1 package in 3s

    found 0 vulnerabilities

stderr:
    The system cannot find the path specified.
    The system cannot find the path specified.
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
```

**Comment by asottile** [comment]
the error you linked is unrelated -- that's specifically a problem on linux

my _guess_ is there's something about `npm` which does not like the spaces in your username -- but I don't really know

you could try using `PRE_COMMIT_HOME` to point the cache at a directory that doesn't contain spaces to convirm, or rename your username to not contain spaces

**Comment by cristianmatache** [comment]
thanks @asottile 

I tried that too. With prettier this time (it doesn't really matter since anything that comes from `npm` behaves similarly)

```
$ pre-commit run --all-files
[WARNING] The 'rev' field of repo 'https://github.com/pre-commit/mirrors-prettier' appears to be a mutable reference (moving tag / branch).  Mutable references are never upda
ted after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often f
ixes this.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.                           
[INFO] This may take a few minutes...                                            
An unexpected error has occurred: CalledProcessError: command: ('D:\\workspace\\repo1r0n45ii\\node_env-16.3.0\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prep
ublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout:

    up to date, audited 1 package in 590ms

    found 0 vulnerabilities

stderr:
    The system cannot find the path specified.
    The system cannot find the path specified.
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.

Check the log at D:\workspace\pre-commit.log
```

**Comment by asottile** [comment]
do you have an antivirus that might be deleting the `.exe` file? that's the only way I'm able to get your output

**Comment by cristianmatache** [comment]
No, no antivirus, no corporate firewall. 
As you can see we get the `--dev` `npm` warning so `npm` is there. I can use any other pre-commit hook with no problems. Just the `npm` ones have this issue.

**Comment by asottile** [comment]
yeah I think it's running your globally installed `npm` and not the isolated one (that's why there's the "up to date" message) -- that's where the "The system cannot find the path specified." message comes from

**Comment by asottile** [comment]
what version of windows are you using?

**Comment by cristianmatache** [comment]
Windows 10 Home, 21H1.

I uninstalled node and npm.

```
(sqlattrs) Cristian Matache@Cristian-XPS13 /d/workspace/cookiecutter-alpha-build-polyrepo-py (main)
$ rm -rf ~/.cache/pre-commit/
(sqlattrs) Cristian Matache@Cristian-XPS13 /d/workspace/cookiecutter-alpha-build-polyrepo-py (main)
$ command -v node                                                                                  
(sqlattrs) Cristian Matache@Cristian-XPS13 /d/workspace/cookiecutter-alpha-build-polyrepo-py (main)
$ command -v npm
(sqlattrs) Cristian Matache@Cristian-XPS13 /d/workspace/cookiecutter-alpha-build-polyrepo-py (main)
$ pre-commit run --all-files                                                                                                                                                  
[WARNING] The 'rev' field of repo 'https://github.com/pre-commit/mirrors-prettier' appears to be a mutable reference (moving tag / branch).  Mutable references are never upda
ted after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often f
ixes this.
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.                           
[INFO] This may take a few minutes...                                            
An unexpected error has occurred: CalledProcessError: command: ('D:\\workspace\\repo1r0n45ii\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-pre
publish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout:
    
    up to date, audited 1 package in 448ms

    found 0 vulnerabilities

stderr:
    The system cannot find the path specified.
    The system cannot find the path specified.
    npm WARN config dev Please use --include=dev instead.
    npm WARN config production Use `--omit=dev` instead.

Check the log at D:\workspace\pre-commit.log
```

**Comment by asottile** [comment]
I think this is the same as https://github.com/pre-commit/mirrors-prettier/issues/18 of which I've been unable to reproduce -- something about your system is causing this to not work

**Comment by cristianmatache** [comment]
Yes, it's the same, i had this issue on 2 windows machines (all that tried).

**Comment by asottile** [comment]
my only other guess would be long paths

**Comment by cristianmatache** [comment]
I have that enabled and the issue persists.
```
(sqlattrs) Cristian Matache@Cristian-XPS13 /d/workspace/cookiecutter-alpha-build-polyrepo-py (main)
$ cat /c/Program\ Files/Git/etc/gitconfig
[diff "astextplain"]
        textconv = astextplain
[filter "lfs"]
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
        required = true
[http]
        sslBackend = openssl
        sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
[core]
        autocrlf = true
        fscache = true
        symlinks = false
        longpaths = true
[pull]
        rebase = false
[credential]
        helper = manager-core
[credential "https://dev.azure.com"]
        useHttpPath = true
[init]
        defaultBranch = master
```

**Comment by asottile** [comment]
it's not a git setting, it's an operating-system level setting

**Comment by cristianmatache** [comment]
Changed it in the os as well and it still fails. I think I'm onto something:

```
(sqlattrs) Cristian Matache@Cristian-XPS13 /d/workspace/mirrors-prettier (main)
$ nodeenv nenv
 * Install prebuilt node (18.2.0) ..... done.
The system cannot find the path specified.
symbolic link created for nenv\Scripts\nodejs.exe <<===>> node.exe
The system cannot find the path specified.
symbolic link created for nenv\Scripts\nodejs.exe <<===>> node.exe
Error: Failed to create nodejs.exe link
```

**Comment by asottile** [comment]
that's fairly normal -- the symlink isn't needed

**Comment by cristianmatache** [comment]
Thanks. I solved it.

`conda` writes the AutoRun thing in the registry.
See: https://localcoder.org/node-js-npm-error-message-system-cannot-find-the-path-specified
and this: https://stackoverflow.com/questions/6637922/the-system-cannot-find-the-path-specified-when-starting-ruby-and-rails-command-p

**Comment by asottile** [comment]
wtf wow, I am speechless -- thanks for figuring that out

**Comment by cristianmatache** [comment]
@asottile yeah, really strange. Thank you a lot for your swift replies.

**Comment by YouJiacheng** [comment]
Wow, you save my day.
Actually `AutoRun` just broke my vscode-remote-ssh few days ago, and it broke my pyright pre-commit. I don't know `conda` will change it! Thanks!!!
