### ISSUE TITLE
Docker Image based hook fails cache creation

### ISSUE THREAD

**Issue by torkelrogstad** [pre-commit/pre-commit#2408]
### search tried in the issue tracker

yes

### describe your issue

I'm trying to run a [Docker based](https://github.com/torkelrogstad/pre-commit-buf-lint/blob/master/.pre-commit-hooks.yaml) hook. 

I've installed it in my `.pre-commit-config.yaml` file: 

```yaml
  - repo: https://github.com/torkelrogstad/pre-commit-buf-lint
    rev: eb427852962a19e450216f4b0bbae7c0c9b0268f
    hooks:
      - id: buf-lint
```

When I run it, it fails because it tries to create a cache dir (in a place I wouldn't expect a cache dir to be created): 

```
❮ pre-commit run buf-lint --verbose

[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/torkel/.cache/pre-commit/patch1653841144-17421.
Lint Protobuf files......................................................Failed
- hook id: buf-lint
- duration: 1.27s
- exit code: 1

Failure: mkdir /.cache: permission denied

[INFO] Restored changes from /Users/torkel/.cache/pre-commit/patch1653841144-17421.
```

Based on some cursory glancing, it appears this line is failing: 

https://github.com/pre-commit/pre-commit/blob/e1ce4c0bf32f905a93dd22f0bd9be26c2561ab6a/pre_commit/languages/docker.py#L106

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: go-mod-tidy
      - id: golangci-lint
  - repo: https://github.com/torkelrogstad/pre-commit-buf-lint
    rev: eb427852962a19e450216f4b0bbae7c0c9b0268f
    hooks:
      - id: buf-lint
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.36.1
sys.version:
    3.10.4 (main, Apr 26 2022, 19:42:59) [Clang 13.1.6 (clang-1316.0.21.2)]
sys.executable: /usr/local/Cellar/pre-commit/2.19.0/libexec/bin/python3.10
os.name: posix
sys.platform: darwin
```

### error information

```
Interrupted (^C): KeyboardInterrupt: 
```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/main.py", line 389, in main
    return run(args.config, store, args)
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 416, in run
    return _run_hooks(config, hooks, skips, args)
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 285, in _run_hooks
    current_retval, prior_diff = _run_single_hook(
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 192, in _run_single_hook
    retcode, out = language.run_hook(hook, filenames, use_color)
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/languages/docker_image.py", line 21, in run_hook
    return helpers.run_xargs(hook, cmd, file_args, color=color)
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/languages/helpers.py", line 137, in run_xargs
    return xargs(cmd, file_args, **kwargs)
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/xargs.py", line 164, in xargs
    for proc_retcode, proc_out, _ in results:
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/xargs.py", line 156, in run_cmd_partition
    return cmd_fn(
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/util.py", line 224, in cmd_output_p
    bts = os.read(pty.r, 4096)
KeyboardInterrupt
```

**Comment by asottile** [comment]
nope, that would lead to a stacktrace outside the container

what's happening is your image is trying to make a `/.cache` dir *inside* the container (presumably it assumes home is /)

this isn't an issue with pre-commit, but with the image

**Comment by torkelrogstad** [comment]
Aha, I understand. Sorry for the confused bug report!
