### ISSUE TITLE
virtualenv python version did not match created version (MacOS)

### ISSUE THREAD

**Issue by mhyousefi** [pre-commit/pre-commit#2409]
### search tried in the issue tracker

virtualenv python version did not match created version

### describe your issue

I'm trying to hook things up in my repo using `pre-commit` and face the following issue when creating a new commit after upgrading to python 3.10 and creating a new `venv`. I have looked through previous issues here with no luck in fixing my problem.

Here's what I do:
1. Install Python`3.10.4` and pre-commit `2.19.0` using Homebrew.
2. Create a virtualenv for my project and set things up.
```bash
python3.10 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt
```
3. Run pre-commit commands.
```bash
pre-commit clean
pre-commit install
pre-commit run
```

Here's when I encounter the following error logs recorded at `~/.cache/pre-commit/pre-commit.log`.

I dont understand why pre-commit is looking for a Python executable at `~/.cache/pre-commit/repojhm_6app/py_env-python3.10/bin/python` and why it does not exist. I appreciate some assistance.

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
        args:
          - --line-length=120
          - --include='\.pyi?$'
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""
        language_version: python3.10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=E203,E266,E501,W503,F403,F401,E402,E701,W503,W291,E203,E722,E126,W605,F405,C901,F821,E711"
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.32.1 (Apple Git-133)
sys.version:
    3.10.4 (main, Apr 26 2022, 19:42:59) [Clang 13.1.6 (clang-1316.0.21.2)]
sys.executable: /usr/local/Cellar/pre-commit/2.19.0/libexec/bin/python3.10
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /Users/XYZ/.cache/pre-commit/repojhm_6app/py_env-python3.10/bin/python>>
- expected version: 3.10.4.final.0

```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/main.py", line 389, in main
    return run(args.config, store, args)
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 84, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /Users/XYZ/.cache/pre-commit/repojhm_6app/py_env-python3.10/bin/python>>
- expected version: 3.10.4.final.0
```

**Comment by asottile** [comment]
I think this is a bug with homebrew itself, I'd recommend reporting it there -- here's the previous occurrence of this: #2350

the tl;dr is homebrew's bundled `virtualenv` is creating an invalid virtualenv structure (as can be seen from the error output)

**Comment by mhyousefi** [comment]
Thank you @asottile for the quick response.

I removed `virtualenv` using Homebrew and installed it using `pip3` only to encounter the same error. Still think the most probable culprit is my virtualenv installation?

```bash
brew uninstall virtualenv
pip3 install virtualenv
virtualenv venv
source venv
pip3 install pre-commit
pre-commit clean
pre-commit uninstall
pre-commit install
pre-commit run
```

**Comment by asottile** [comment]
probably, yes -- note you'll need `hash -r` to clear your shell's hash cache usually

**Comment by miigotu** [comment]
This will fix your issue, you have to recreate your venv after.
`virtualenv --reset-app-data venv -vvvv`

https://github.com/pypa/virtualenv/issues/2319

**Comment by spidermila** [comment]
Had the same problem 

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.34.1
sys.version:
    3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
sys.executable: /home/milan/scripts/dungeon/venv/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/milan/.cache/pre-commit/repoam8vllab/py_env-python3.10/bin/python>>
- expected version: 3.10.6.final.0

```

```
Traceback (most recent call last):
  File "/home/milan/scripts/dungeon/venv/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/milan/scripts/dungeon/venv/lib/python3.10/site-packages/pre_commit/main.py", line 386, in main
    return run(args.config, store, args)
  File "/home/milan/scripts/dungeon/venv/lib/python3.10/site-packages/pre_commit/commands/run.py", line 424, in run
    install_hook_envs(to_install, store)
  File "/home/milan/scripts/dungeon/venv/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/home/milan/scripts/dungeon/venv/lib/python3.10/site-packages/pre_commit/repository.py", line 84, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/milan/.cache/pre-commit/repoam8vllab/py_env-python3.10/bin/python>>
- expected version: 3.10.6.final.0
```


on
```
$ uname -a
Linux nas 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

It was resolved by
``virtualenv --reset-app-data venv``

**Comment by asottile** [comment]
title says "macos" -- you do not have the same problem -- but there are many other duplicates with solutions -- please search for those
