### ISSUE TITLE
install-local.py is failing with `DistributionNotFound: No distributions at all found for wheel`

### ISSUE THREAD

**Issue by lukas-b** [pre-commit/pre-commit#241]
Non Administrative Installation (`curl http://pre-commit.com/install-local.py | python` via http://pre-commit.com/#install) is failing with `DistributionNotFound: No distributions at all found for wheel`:

```python
No distributions at all found for wheel
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/virtualenv_support/pip-1.5.5-py2.py3-none-any.whl/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/virtualenv_support/pip-1.5.5-py2.py3-none-any.whl/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.6/dist-packages/virtualenv_support/pip-1.5.5-py2.py3-none-any.whl/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.6/dist-packages/virtualenv_support/pip-1.5.5-py2.py3-none-any.whl/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for wheel
```

Looks like virtualenv issue.

**Comment by lukas-b** [comment]
Moved to https://github.com/pre-commit/pre-commit.github.io/issues/52
