### ISSUE TITLE
unstaged stashed files not applied, thinks there is a new file

### ISSUE THREAD

**Issue by willjhenry** [pre-commit/pre-commit#2414]
### search tried in the issue tracker

already exists in working directory

### describe your issue

Tried to commit a file. Had the error below, then reapplied the patch after removing the part of the patch that wanted to add requirements-dev.in.  Then tried to unstage a file (see below), same error. Going to work on fixing the patch and then applying it. Seems to think requirements-dev.in is an unstaged file it is trying to apply. But it already exists and has no change to commit.

```
(base) williamhenry@willh elate_app % git restore --staged dispatch.yaml
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/williamhenry/.cache/pre-commit/patch1654551135-24727.
check virtualenv against requirements.txt using pip-sync.......................Passed
[WARNING] Stashed changes conflicted with hook auto-fixes... Rolling back fixes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/git/libexec/git-core/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/williamhenry/.cache/pre-commit/patch1654551135-24727')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: requirements-dev.in: already exists in working directory
    
Check the log at /Users/williamhenry/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

2.18.1

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, post-checkout, post-merge]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: check-added-large-files
        stages: [commit]
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.6.2
    hooks:
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [requirements-dev.in]
        files: ^requirements-dev\.(in|txt)$
        stages: [commit]
      - id: pip-compile
        name: pip-compile requirements.txt
        args: [requirements.in]
        files: ^requirements\.(in|txt)$
        stages: [commit]
  - repo: local
    hooks:
      - id: check_venv
        name: check virtualenv against requirements.txt using pip-sync
        entry: bash .githooks/check_venv.sh
        language: system
        stages: [post-checkout, post-merge]
        always_run: true
        pass_filenames: false
```

### version information

```
pre-commit version: 2.18.1
git --version: git version 2.23.0
sys.version:
    3.9.12 (main, Apr  5 2022, 01:53:17) 
    [Clang 12.0.0 ]
sys.executable: /Users/williamhenry/Documents/Elate_App/app_envs/elate_app/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/git/libexec/git-core/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/williamhenry/.cache/pre-commit/patch1654551135-24727')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: requirements-dev.in: already exists in working directory
    
```

```
Traceback (most recent call last):
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 28, in _git_apply
    cmd_output_b('git', *args)
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/git/libexec/git-core/git', 'apply', '--whitespace=nowarn', '/Users/williamhenry/.cache/pre-commit/patch1654551135-24727')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: requirements-dev.in: already exists in working directory
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 76, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 31, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/git/libexec/git-core/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/williamhenry/.cache/pre-commit/patch1654551135-24727')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: requirements-dev.in: already exists in working directory
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 28, in _git_apply
    cmd_output_b('git', *args)
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/git/libexec/git-core/git', 'apply', '--whitespace=nowarn', '/Users/williamhenry/.cache/pre-commit/patch1654551135-24727')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: requirements-dev.in: already exists in working directory
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/main.py", line 343, in main
    return hook_impl(
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/commands/run.py", line 416, in run
    return _run_hooks(config, hooks, skips, args)
  File "/Users/williamhenry/opt/anaconda3/envs/python3.9/lib/python3.9/contextlib.py", line 532, in __exit__
    raise exc_details[1]
  File "/Users/williamhenry/opt/anaconda3/envs/python3.9/lib/python3.9/contextlib.py", line 517, in __exit__
    if cb(*exc_details):
  File "/Users/williamhenry/opt/anaconda3/envs/python3.9/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 101, in staged_files_only
    yield
  File "/Users/williamhenry/opt/anaconda3/envs/python3.9/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 86, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 31, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "/Users/williamhenry/Documents/Elate_App/app_envs/elate_app/lib/python3.9/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/git/libexec/git-core/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/williamhenry/.cache/pre-commit/patch1654551135-24727')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: requirements-dev.in: already exists in working directory
```

**Comment by asottile** [comment]
can you provide steps to reproduce?  you haven't provided enough information in your issue since I can't see your scripts

**Comment by willjhenry** [comment]
I am not sure exactly, but I think it started when I was trying to add a yaml file. Below is not the same error, but this was occurring, and I was trying to fix it and then the reported issue occurred.

(base) williamhenry@willh elate_app % git add dispatch.yaml 
(base) williamhenry@willh elate_app % git commit -m 'add demo.elatemcd.com/employee_app to dispatch.yaml'
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/williamhenry/.cache/pre-commit/patch1654549021-20939.
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing dispatch.yaml

fix end of files.........................................................Passed
check yaml...............................................................Passed
check for added large files..............................................Passed
pip-compile requirements-dev.in......................(no files to check)Skipped
pip-compile requirements.txt.........................(no files to check)Skipped
[INFO] Restored changes from /Users/williamhenry/.cache/pre-commit/patch1654549021-20939.
(base) williamhenry@willh elate_app % git status

**Comment by asottile** [comment]
please surround your markdown in braces -- here's a tutorial: https://youtu.be/1UodxuXj5Ao

can you share your `.gitattributes` and the contents of `.githooks/check_venv.sh`

**Comment by willjhenry** [comment]
Do you mean to surround markdown with three backticks? or braces as in parenthesis 

I don't seem to have a ```.gitattributes``` file

```.githooks/check_venv.sh```
```
if [[ "$OSTYPE" == "darwin"* ]]; then
    scriptdir="$(dirname "$0")"
else
    scriptdir="$(dirname "${BASH_SOURCE[0]}")"
fi

pipsyncout=$(echo $(pip-sync $scriptdir/../requirements.txt $scriptdir/../requirements-dev.txt -qn) | awk '{print tolower($0)}')
# if pipsyncout is not empty then exit with error code 1 else exit with 0
if [ -n "$pipsyncout" ]; then
    echo "pip-sync failed with the following output:"
    echo "$pipsyncout"
    exit 1
else
    exit 0
fi
# [[ $pipsyncout ]]

# (echo "This environment is not synced with the requirements.txt and requirements-dev.txt \
# files for this branch. Please consider running 'pip-sync requirements.txt dev-requirements-dev.txt'"
# echo "Running pip-sync" $pipsyncout)                                     
```

**Comment by asottile** [comment]
very strange -- the output in your second comment looks normal, but I'm not sure where the requirements-dev.in is coming from

the only way I could imagine this happening is if some other git process caused that file to be deleted?

**Comment by asottile** [comment]
can you try and make an open source reproduction of this?  otherwise I can't really fix anything

**Comment by willjhenry** [comment]
I am not really sure how to reproduce it either. If this occurs again, hopefully I will recognize it sooner and have a better idea of what happened and what the steps to reproduce are. I guess, close the issue for now?

**Comment by asottile** [comment]
sounds good -- looking forward to it!
