### ISSUE TITLE
Cannot commit on windows, some kind of python error

### ISSUE THREAD

**Issue by wolfboyft** [pre-commit/pre-commit#2415]
### search tried in the issue tracker

commit windows 

### describe your issue

I managed to get pre-commit running on Windows, but when I try to actually commit, I receive: https://www.toptal.com/developers/hastebin/samirapezi.txt

The repository is a clone of https://github.com/wolfboyft/scripts/, which is a fork.

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
ci:
  autofix_prs: false
  autoupdate_schedule: monthly
repos:
# shared across repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-xml
    - id: check-yaml
    - id: destroyed-symlinks
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: trailing-whitespace
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.16.0
  hooks:
    - id: check-github-workflows
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.2.0
  hooks:
    - id: forbid-tabs
      exclude_types:
        - json
    - id: remove-tabs
      exclude_types:
        - json
# specific to scripts:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: forbid-new-submodules
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.36.1.windows.1
sys.version:
    3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
sys.executable: C:\Users\Tachytaenius\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Tachytaenius\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe', '-mvirtualenv', 'C:\\Users\\Tachytaenius\\.cache\\pre-commit\\repotcuptfc4\\py_env-python3.10')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to build image setuptools because:
    Traceback (most recent call last):
      File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
        installer.install(creator.interpreter.version_info)
      File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 35, in install
        self._uninstall_previous_version()
      File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 151, in _uninstall_previous_version
        dist_name = self._dist_info.stem.split("-")[0]
      File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 115, in _dist_info
        raise RuntimeError(msg)  # pragma: no cover
    RuntimeError: no .dist-info at C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\setuptools-62.2.0-py3-none-any, has distutils-precedence.pth, pkg_resources, setuptools, _distutils_hack
    
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pre_commit\main.py", line 361, in main
    return hook_impl(
  File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pre_commit\commands\hook_impl.py", line 238, in hook_impl
    return retv | run(config, store, ns)
  File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pre_commit\commands\run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pre_commit\repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pre_commit\repository.py", line 79, in _hook_install
    lang.install_environment(
  File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pre_commit\languages\python.py", line 219, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pre_commit\util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\Tachytaenius\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe', '-mvirtualenv', 'C:\\Users\\Tachytaenius\\.cache\\pre-commit\\repotcuptfc4\\py_env-python3.10')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to build image setuptools because:
    Traceback (most recent call last):
      File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
        installer.install(creator.interpreter.version_info)
      File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 35, in install
        self._uninstall_previous_version()
      File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 151, in _uninstall_previous_version
        dist_name = self._dist_info.stem.split("-")[0]
      File "C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 115, in _dist_info
        raise RuntimeError(msg)  # pragma: no cover
    RuntimeError: no .dist-info at C:\Users\Tachytaenius\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv\wheel\3.10\image\1\CopyPipInstall\setuptools-62.2.0-py3-none-any, has distutils-precedence.pth, pkg_resources, setuptools, _distutils_hack
    
    
stderr: (none)
```

**Comment by wolfboyft** [comment]
Hopefully I won't be told to report back here lol

**Comment by asottile** [comment]
almost certainly not, heh -- pre-commit just calls virtualenv and that's what's crashing here
