### ISSUE TITLE
"DLL load failed while importing _ctypes" conda with python 3.10

### ISSUE THREAD

**Issue by Mara-Li** [pre-commit/pre-commit#2417]
### search tried in the issue tracker

- `DLL load failed while importing _ctypes`
- `conda`
- `CalledProcessError: command:`

### describe your issue

I create a `.pre-commit-config.yml`.

I run : 
- `pre-commit clean` 
- `pre-commit autoupdate`
- `pre-commit install`
- `pre-commit run --all-files`

My conda file : 
```yml
name: Publish
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.4.26=haa95532_0
  - libffi=3.4.2=hd77b12b_4
  - openssl=1.1.1o=h2bbff1b_0
  - pip=21.2.4=py310haa95532_0
  - python=3.10.4=hbb2ffb3_0
  - sqlite=3.38.3=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tzdata=2022a=hda174b7_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.5=h8cc25b3_1
  - zlib=1.2.12=h8cc25b3_2
  - pip:
    - astor==0.8.1
    - attrs==21.4.0
    - autoflake==1.4
    - autopep8==1.6.0
    - bandit==1.7.4
    - beautifulsoup4==4.10.0
    - bracex==2.2.1
    - certifi==2021.10.8
    - cfgv==3.3.1
    - charset-normalizer==2.0.12
    - click==8.1.3
    - clipboard==0.0.4
    - colorama==0.4.4
    - commonmark==0.9.1
    - darglint==1.8.1
    - dataclasses==0.6
    - distlib==0.3.4
    - docformatter==1.4
    - docutils==0.18.1
    - editorconfig==0.12.3
    - eradicate==2.1.0
    - filelock==3.7.1
    - flake8==4.0.1
    - flake8-bandit==3.0.0
    - flake8-broken-line==0.4.0
    - flake8-bugbear==22.4.25
    - flake8-commas==2.1.0
    - flake8-comprehensions==3.10.0
    - flake8-debugger==4.1.2
    - flake8-docstrings==1.6.0
    - flake8-eradicate==1.2.1
    - flake8-isort==4.1.1
    - flake8-polyfill==1.0.2
    - flake8-quotes==3.3.1
    - flake8-rst-docstrings==0.2.6
    - flake8-string-format==0.3.0
    - ghp-import==2.0.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - identify==2.5.1
    - idna==3.3
    - importlib-metadata==4.11.3
    - isort==5.10.1
    - jinja2==3.0.3
    - jsbeautifier==1.14.0
    - markdown==3.3.6
    - markupsafe==2.1.1
    - mccabe==0.6.1
    - mdx-breakless-lists==1.0.1
    - mdx-wikilink-plus==1.4.0
    - mergedeep==1.3.4
    - mkdocs==1.3.0
    - mkdocs-awesome-pages-plugin==2.7.0
    - mkdocs-custom-fences==0.0.1
    - mkdocs-ezlinked-plugin==0.1.18
    - mkdocs-material==8.2.6
    - mkdocs-material-extensions==1.0.3
    - mkdocs-mermaid2-plugin==0.5.2
    - mypy-extensions==0.4.3
    - nodeenv==1.6.0
    - obs2mk==3.3.1
    - packaging==21.3
    - pathspec==0.9.0
    - pbr==5.9.0
    - pep8-naming==0.12.1
    - platformdirs==2.5.2
    - pre-commit==2.19.0
    - pycodestyle==2.8.0
    - pydocstyle==6.1.1
    - pyflakes==2.4.0
    - pyformat==0.7
    - pygments==2.12.0
    - pygtrie==2.4.2
    - pymdown-extensions==9.3
    - pyparsing==3.0.7
    - pyperclip==1.8.2
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - python-frontmatter==1.0.0
    - pyyaml==6.0
    - pyyaml-env-tag==0.1
    - requests==2.27.1
    - restructuredtext-lint==1.4.0
    - rich==12.4.4
    - setuptools==62.3.3
    - six==1.16.0
    - smmap==5.0.0
    - snowballstemmer==2.2.0
    - soupsieve==2.3.1
    - stevedore==3.5.0
    - testfixtures==6.18.5
    - tomli==2.0.1
    - typing-extensions==4.2.0
    - unidecode==1.3.4
    - unify==0.5
    - untokenize==0.1.1
    - urllib3==1.26.9
    - virtualenv==20.14.1
    - watchdog==2.1.6
    - wcmatch==8.3
    - wemake-python-styleguide==0.16.1
    - zipp==3.7.0
```

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.6.0
  hooks:
    - id: autopep8
      entry: autopep8 -i
      types : [ "python" ]
- repo: https://github.com/PyCQA/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      entry: autoflake --i
      types: ["python"]
- repo: https://github.com/PyCQA/docformatter
  rev: v1.4
  hooks :
    - id: docformatter
      entry: docformatter -i
      types : ["python"]
- repo: https://github.com/myint/unify
  rev: v0.5
  hooks :
    - id: unify
      entry: unify -i
      types: ["python"]
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.35.1.windows.2
sys.version:
    3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)]
sys.executable: C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Lili\\.cache\\pre-commit\\repoa9y3heub\\py_env-python3.10\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\__main__.py", line 29, in <module>
        from pip._internal.cli.main import main as _main
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
        from pip._internal.cli.autocompletion import autocomplete
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
        from pip._internal.cli.main_parser import create_main_parser
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
        from pip._internal.cli import cmdoptions
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 23, in <module>
        from pip._internal.cli.parser import ConfigOptionParser
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\_internal\cli\parser.py", line 12, in <module>
        from pip._internal.configuration import Configuration, ConfigurationError
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\_internal\configuration.py", line 24, in <module>
        from pip._internal.utils import appdirs
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
        from pip._vendor import platformdirs as _appdirs
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 33, in <module>
        PlatformDirs = _set_platform_dir_class()  #: Currently active platform
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 29, in _set_platform_dir_class
        result: type[PlatformDirsABC] = getattr(importlib.import_module(module), name)
      File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "C:\Users\Lili\.cache\pre-commit\repoa9y3heub\py_env-python3.10\lib\site-packages\pip\_vendor\platformdirs\windows.py", line 3, in <module>
        import ctypes
      File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\ctypes\__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: DLL load failed while importing _ctypes: Le module spécifié est introuvable.
    
```

```
Traceback (most recent call last):
  File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\site-packages\pre_commit\main.py", line 389, in main
    return run(args.config, store, args)
  File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\site-packages\pre_commit\commands\run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\site-packages\pre_commit\repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\site-packages\pre_commit\repository.py", line 79, in _hook_install
    lang.install_environment(
  File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\site-packages\pre_commit\languages\python.py", line 221, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\site-packages\pre_commit\languages\helpers.py", line 51, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Users\Lili\AppData\Local\Anaconda3\envs\Publish\lib\site-packages\pre_commit\util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: <unprintable CalledProcessError object>
```

**Comment by asottile** [comment]
yeah sorry can't help, this looks like your installation is broken

**Comment by Mara-Li** [comment]
Well, it's strange because my environment work without problem and it run fine with the base ?
