### ISSUE TITLE
Problem running after installing, FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by gbirka-r7** [pre-commit/pre-commit#2419]
### search tried in the issue tracker

FileNotFoundError

### describe your issue

I upgraded to a new macbook pro (m1 pro chip). I used pre-commit on my old macbook (pro with intel chip) with no issues. I installed pre-commit using brew, then used the pre-commit command on the root directory and got this error. (see log message below)

I tried re-installing python, pre-commit (even using pip). I use pyenv so I tried disabling it, and reinstalling, noting works and I get the same errors. 

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
        exclude: ^tests/data/
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        args: ['--ignore=E501,W504']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
        exclude: ^infra/database/dataclasses
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.30.1 (Apple Git-130)
sys.version:
    3.10.4 (main, Apr 26 2022, 19:36:29) [Clang 13.1.6 (clang-1316.0.21.2)]
sys.executable: /opt/homebrew/Cellar/pre-commit/2.19.0/libexec/bin/python3.10
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/bin/python3.10', '-mvirtualenv', '/Users/gbirka/.cache/pre-commit/repok3gld2y9/py_env-python3.10')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to build image setuptools, pip because:
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 56, in _install
        installer.build_image()
      File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 50, in build_image
        with zipfile.ZipFile(str(self._wheel)) as zip_ref:
      File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1249, in __init__
        self.fp = io.open(file, filemode)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/gbirka/Library/Application Support/virtualenv/wheel/house/setuptools-62.2.0-py3-none-any.whl'
    
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 56, in _install
        installer.build_image()
      File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 50, in build_image
        with zipfile.ZipFile(str(self._wheel)) as zip_ref:
      File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1249, in __init__
        self.fp = io.open(file, filemode)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/gbirka/Library/Application Support/virtualenv/wheel/house/pip-22.1.2-py3-none-any.whl'
    
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/main.py", line 389, in main
    return run(args.config, store, args)
  File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/languages/python.py", line 219, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/bin/python3.10', '-mvirtualenv', '/Users/gbirka/.cache/pre-commit/repok3gld2y9/py_env-python3.10')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to build image setuptools, pip because:
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 56, in _install
        installer.build_image()
      File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 50, in build_image
        with zipfile.ZipFile(str(self._wheel)) as zip_ref:
      File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1249, in __init__
        self.fp = io.open(file, filemode)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/gbirka/Library/Application Support/virtualenv/wheel/house/setuptools-62.2.0-py3-none-any.whl'
    
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 56, in _install
        installer.build_image()
      File "/opt/homebrew/Cellar/pre-commit/2.19.0/libexec/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 50, in build_image
        with zipfile.ZipFile(str(self._wheel)) as zip_ref:
      File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1249, in __init__
        self.fp = io.open(file, filemode)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/gbirka/Library/Application Support/virtualenv/wheel/house/pip-22.1.2-py3-none-any.whl'
    
    
stderr: (none)
```

**Comment by asottile** [comment]
dupe https://github.com/pre-commit/pre-commit/issues/2415
