### ISSUE TITLE
Installing hook environments fails

### ISSUE THREAD

**Issue by benthevining** [pre-commit/pre-commit#2428]
### search tried in the issue tracker

install

### describe your issue

When trying to run pre-commit, I keep getting `TypeError: expected string or bytes-like object`.

Here is the full output:
```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/opt/python@3.9/bin/python3.9', '-mvirtualenv', '/Users/benvining/.cache/pre-commit/repo3hff6t96/py_env-python3')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
        __import__(pkg_name)
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/__init__.py", line 3, in <module>
        from .run import cli_run, session_via_cli
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/run/__init__.py", line 14, in <module>
        from .plugin.creators import CreatorSelector
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/run/plugin/creators.py", line 6, in <module>
        from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
        from virtualenv.create.creator import Creator
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/create/creator.py", line 15, in <module>
        from virtualenv.discovery.cached_py_info import LogCmd
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/discovery/cached_py_info.py", line 23, in <module>
        _CACHE[Path(sys.executable)] = PythonInfo()
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/discovery/py_info.py", line 86, in __init__
        self.distutils_install = {u(k): u(v) for k, v in self._distutils_install().items()}
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/discovery/py_info.py", line 152, in _distutils_install
        d = dist.Distribution({"script_args": "--no-user-cfg"})  # conf files not parsed so they do not hijack paths
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 475, in __init__
        for ep in metadata.entry_points(group='distutils.setup_keywords'):
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
        return SelectableGroups.load(eps).select(**params)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
        ordered = sorted(eps, key=by_group)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 996, in <genexpr>
        eps = itertools.chain.from_iterable(
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
        k = key(element)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 931, in _normalized_name
        return self._name_from_stem(stem) or super()._normalized_name
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 600, in _normalized_name
        return Prepared.normalize(self.name)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 855, in normalize
        return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 210, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object
```

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
---
# editorconfig-checker-disable
# yamllint disable rule:line-length

default_language_version:
    python: python3

repos:
  # precommit configuration meta-checks
    - repo: meta
      hooks:
          - id: check-hooks-apply
            always_run: true
          - id: check-useless-excludes
            always_run: true

  # git
    # - repo: https://github.com/jorisroovers/gitlint
    #   rev: v0.17.0
    #   hooks:
    #       - id: gitlint
    #         always_run: true
    - repo: https://github.com/mattlqx/pre-commit-sign
      rev: v1.1.3
      hooks:
          - id: sign-commit

    - repo: local
      hooks:
          # update cmake-format config
          - id: update-cmakeformat-config
            name: Update CMakeFormat config
            entry: python3 scripts/update_cmakeformat_config.py --input=util/OrangesCMakeCommands.json
            language: system
            always_run: true
            pass_filenames: false

          # run cmake & update dependency graph & readme
          - id: run-cmake
            name: Run CMake
            entry: cmake --preset default
            language: system
            always_run: true
            pass_filenames: false

          - id: update-readme
            name: Update readme
            entry: cmake --build --preset readme
            language: system
            always_run: true
            pass_filenames: false

    # - repo: https://github.com/andreoliwa/nitpick
    #   rev: v0.32.0
    #   hooks:
    #       - id: nitpick

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: check-json
          - id: check-yaml
          - id: check-toml
          - id: pretty-format-json
            args: [--autofix]

      # general
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: end-of-file-fixer
            exclude_types: [cmake]
          - id: fix-byte-order-marker
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: trailing-whitespace

      # Python
          - id: check-ast
          - id: check-builtin-literals
          - id: debug-statements
          - id: fix-encoding-pragma

  # license header
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.13 # last known stable version is v1.1.13
      hooks:
          - id: insert-license
            name: Insert license header
            args: [--license-filepath=util/oranges_header.txt, --comment-style=#, --detect-license-in-X-top-lines=16]
            types_or: [cmake, python, shell]
            exclude: templates/FindModuleTemplate.cmake

  # text and typos
    - repo: https://github.com/sirosen/texthooks
      rev: 0.3.1
      hooks:
          - id: fix-ligatures
          - id: fix-smartquotes
          - id: forbid-bidi-controls
    - repo: https://github.com/crate-ci/typos
      rev: typos-dict-v0.8.2 # last known stable version is typos-dict-v0.8.2
      hooks:
          - id: typos
            args: [--write-changes]
            exclude: CHANGELOG.md|OrangesOptimizationFlags.cmake

  # CMake
    - repo: https://github.com/cheshirekow/cmake-format-precommit
      rev: v0.6.13
      hooks:
          - id: cmake-format
            args: [--in-place]
            exclude: templates/FindModuleTemplate.cmake
          #- id: cmake-lint

  # YAML
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt
            args: [--width, '200', --preserve-quotes]
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.26.3
      hooks:
          - id: yamllint
            #exclude: .clang-tidy
    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.14.3 # last known stable version is 0.14.3
      hooks:
          - id: check-github-workflows
          - id: check-jsonschema
            name: Validate CMake presets
            files: CMakePresets.json
            types: [json]
            args: [--schemafile, "https://cmake.org/cmake/help/latest/_downloads/3e2d73bff478d88a7de0de736ba5e361/schema.json"]

  # Markdown
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.31.1
      hooks:
          - id: markdownlint-fix
            exclude: CHANGELOG.md

  # TOML
    - repo: https://github.com/pappasam/toml-sort
      rev: v0.20.0
      hooks:
          - id: toml-sort
            args: [--in-place, --all]

  # shell scripts
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.8.0.4
      hooks:
          - id: shellcheck
    - repo: https://github.com/lovesegfault/beautysh
      rev: v6.2.1
      hooks:
          - id: beautysh
            args: [--tab]

  # Python
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.32.1
      hooks:
          - id: pyupgrade
    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
    - repo: https://github.com/pre-commit/mirrors-yapf
      rev: v0.32.0
      hooks:
          - id: yapf
            args: [-i]
    - repo: https://github.com/PyCQA/pylint
      rev: v2.13.8 # last known stable version is v2.13.8
      hooks:
          - id: pylint
            args: [--disable=bad-indentation, --disable=line-too-long, --disable=duplicate-code, --check-quote-consistency=yes, --max-args=5, --max-branches=15, --max-statements=55, --good-names=f]
    - repo: https://github.com/PyCQA/docformatter
      rev: v1.4
      hooks:
          - id: docformatter
            args: [--in-place, --recursive, --wrap-summaries, '150', --wrap-descriptions, '150', --pre-summary-newline, --make-summary-multi-line]

  # check editorconfig rules
    - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
      rev: 2.4.0
      hooks:
          - id: editorconfig-checker
            exclude: oranges_header.txt|LICENSE|index.rst|Doxyfile|standard_header.h|platform_header.h

ci:
    skip: [check-jsonschema, pylint, run-cmake, update-readme]
    autofix_commit_msg: 'style: pre-commit autofixes [skip ci]'
    autoupdate_commit_msg: 'chore: pre-commit autoupdate [skip ci]'
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.36.1
sys.version:
    3.9.13 (main, May 24 2022, 21:13:51) 
    [Clang 13.1.6 (clang-1316.0.21.2)]
sys.executable: /opt/homebrew/opt/python@3.9/bin/python3.9
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/opt/python@3.9/bin/python3.9', '-mvirtualenv', '/Users/benvining/.cache/pre-commit/repo3hff6t96/py_env-python3')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
        __import__(pkg_name)
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/__init__.py", line 3, in <module>
        from .run import cli_run, session_via_cli
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/run/__init__.py", line 14, in <module>
        from .plugin.creators import CreatorSelector
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/run/plugin/creators.py", line 6, in <module>
        from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
        from virtualenv.create.creator import Creator
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/create/creator.py", line 15, in <module>
        from virtualenv.discovery.cached_py_info import LogCmd
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/discovery/cached_py_info.py", line 23, in <module>
        _CACHE[Path(sys.executable)] = PythonInfo()
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/discovery/py_info.py", line 86, in __init__
        self.distutils_install = {u(k): u(v) for k, v in self._distutils_install().items()}
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/discovery/py_info.py", line 152, in _distutils_install
        d = dist.Distribution({"script_args": "--no-user-cfg"})  # conf files not parsed so they do not hijack paths
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 475, in __init__
        for ep in metadata.entry_points(group='distutils.setup_keywords'):
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
        return SelectableGroups.load(eps).select(**params)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
        ordered = sorted(eps, key=by_group)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 996, in <genexpr>
        eps = itertools.chain.from_iterable(
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
        k = key(element)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 931, in _normalized_name
        return self._name_from_stem(stem) or super()._normalized_name
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 600, in _normalized_name
        return Prepared.normalize(self.name)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 855, in normalize
        return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 210, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object
    
```

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/lib/python3.9/site-packages/pre_commit/main.py", line 389, in main
    return run(args.config, store, args)
  File "/opt/homebrew/lib/python3.9/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/lib/python3.9/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/lib/python3.9/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/lib/python3.9/site-packages/pre_commit/languages/python.py", line 219, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/opt/homebrew/lib/python3.9/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/opt/python@3.9/bin/python3.9', '-mvirtualenv', '/Users/benvining/.cache/pre-commit/repo3hff6t96/py_env-python3')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
        __import__(pkg_name)
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/__init__.py", line 3, in <module>
        from .run import cli_run, session_via_cli
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/run/__init__.py", line 14, in <module>
        from .plugin.creators import CreatorSelector
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/run/plugin/creators.py", line 6, in <module>
        from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
        from virtualenv.create.creator import Creator
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/create/creator.py", line 15, in <module>
        from virtualenv.discovery.cached_py_info import LogCmd
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/discovery/cached_py_info.py", line 23, in <module>
        _CACHE[Path(sys.executable)] = PythonInfo()
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/discovery/py_info.py", line 86, in __init__
        self.distutils_install = {u(k): u(v) for k, v in self._distutils_install().items()}
      File "/opt/homebrew/lib/python3.9/site-packages/virtualenv/discovery/py_info.py", line 152, in _distutils_install
        d = dist.Distribution({"script_args": "--no-user-cfg"})  # conf files not parsed so they do not hijack paths
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 475, in __init__
        for ep in metadata.entry_points(group='distutils.setup_keywords'):
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
        return SelectableGroups.load(eps).select(**params)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
        ordered = sorted(eps, key=by_group)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 996, in <genexpr>
        eps = itertools.chain.from_iterable(
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
        k = key(element)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 931, in _normalized_name
        return self._name_from_stem(stem) or super()._normalized_name
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 600, in _normalized_name
        return Prepared.normalize(self.name)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 855, in normalize
        return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
      File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 210, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object

**Comment by asottile** [comment]
this is a bug in either virtualenv, setuptools, or importlib_metadata and is not a pre-commit issue

**Comment by benthevining** [comment]
Thanks for the info. Do you have any idea where to start looking for possible solutions?

**Comment by asottile** [comment]
maybe -- but it looks like it's actually `importlib_metadata` -- my guess is you could probably reproduce without virtualenv -- it looks like an egg-info where there's a `None` name

**Comment by benthevining** [comment]
This command fixed the issue:
```
pip install --force-reinstall setuptools==40.8.0
```

It seems it was a setuptools bug.
