### ISSUE TITLE
Bad UX when patch can not be reapplied after stash

### ISSUE THREAD

**Issue by iainsmith** [pre-commit/pre-commit#2435]
### search tried in the issue tracker

176

### describe your issue

I'm using pre-commit with `git-format-staged` which can result in a stash that can no longer be applied cleanly, resulting in the attached error from the log. I was able to apply the patch using git apply --rejected ./path-to-patch-in-cache

IMO, this seems related to #176

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
    -   id: shellcheck
-   repo: local
    hooks:
    -   id: swiftformat
        name: run swift format on staged
        language: system
        entry: ./bin/format-staged
        types: [swift]
-   repo: https://github.com/realm/SwiftLint
    rev: 0.47.1
    hooks:
    -   id: swiftlint
        args: [--strict]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.36.1
sys.version:
    3.10.4 (main, Apr 26 2022, 19:36:29) [Clang 13.1.6 (clang-1316.0.21.2)]
sys.executable: /Users/iain/.local/pipx/venvs/pre-commit/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/Cellar/git/2.36.1/libexec/git-core/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/iain/.cache/pre-commit/patch1656680547-72435')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: patch failed: Redacted.swift:1
    error: Redacted.swift: patch does not apply
    
```

```
Traceback (most recent call last):
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 28, in _git_apply
    cmd_output_b('git', *args)
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/git/2.36.1/libexec/git-core/git', 'apply', '--whitespace=nowarn', '/Users/iain/.cache/pre-commit/patch1656680547-72435')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: patch failed: Redacted.swift:1
    error: Redacted.swift: patch does not apply
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 76, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 31, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/git/2.36.1/libexec/git-core/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/iain/.cache/pre-commit/patch1656680547-72435')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: patch failed: Redacted.swift:1
    error:Redacted.swift: patch does not apply
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 28, in _git_apply
    cmd_output_b('git', *args)
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/git/2.36.1/libexec/git-core/git', 'apply', '--whitespace=nowarn', '/Users/iain/.cache/pre-commit/patch1656680547-72435')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: patch failed: Redacted.swift:1
    error: Redacted.swift: patch does not apply
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/main.py", line 361, in main
    return hook_impl(
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 238, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/commands/run.py", line 394, in run
    with contextlib.ExitStack() as exit_stack:
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 576, in __exit__
    raise exc_details[1]
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 561, in __exit__
    if cb(*exc_details):
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 100, in staged_files_only
    with _intent_to_add_cleared(), _unstaged_changes_cleared(patch_dir):
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 86, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 31, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "/Users/iain/.local/pipx/venvs/pre-commit/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/git/2.36.1/libexec/git-core/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/iain/.cache/pre-commit/patch1656680547-72435')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: patch failed: Redacted.swift:1
    error: Redacted.swift: patch does not apply
```

**Comment by asottile** [comment]
modifying the staging area as part of a git hook is not supported -- it's the whole reason it is not supported because it is an unsafe operation

**Comment by iainsmith** [comment]
IMO, there are a couple of options to improve the UX

1. tell users the patch couldn't be applied, and tell them the command to reapply the patch with conflicts
2. auto apply the patch, with conflicts and let users sort it out.

IMO, the current UX, your change is missing, isn't great for users.

**Comment by asottile** [comment]
- the patch file is printed at the beginning so it is always recoverable
- git will not partially apply so there's nothing really that can be done there

usually if hooks don't misbehave, the conflicts are rolled back and then the original contents are re-applied -- it's only when things (unsupportedly) modify the staging area that you'll end up in the situation you're stuck in
