### ISSUE TITLE
pre-commit run An unexpected error has occurred:  CalledProcessError

### ISSUE THREAD

**Issue by Activity00** [pre-commit/pre-commit#2436]
### search tried in the issue tracker

An unexpected error has occurred

### describe your issue

pre-commit run

[INFO] Stashing unstaged files to /Users/bixin/.cache/pre-commit/patch1656773432-28888.
[INFO] Installing environment for https://github.com/golangci/golangci-lint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /Users/bixin/.cache/pre-commit/patch1656773432-28888.
An unexpected error has occurred: CalledProcessError: command: ('/Users/bixin/gosdk/go1.16.5/bin/go', 'install', './...')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    go: github.com/Antonboom/errname@v0.1.5 requires
        golang.org/x/sys@v0.0.0-20210915083310-ed5796bab164: missing go.sum entry; to add it:
        go mod download golang.org/x/sys
    
Check the log at /Users/bixin/.cache/pre-commit/pre-commit.log

### pre-commit --version

v2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.46.2 # the current latest version
    hooks:
      - id: golangci-lint
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/languages/golang.py", line 82, in install_environment
    cmd_output_b('go', 'install', './...', cwd=repo_src_dir, env=env)
  File "/opt/homebrew/Cellar/pre-commit/2.17.0/libexec/lib/python3.10/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/bixin/gosdk/go1.16.5/bin/go', 'install', './...')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    go: github.com/Antonboom/errname@v0.1.5 requires
        golang.org/x/sys@v0.0.0-20210915083310-ed5796bab164: missing go.sum entry; to add it:
        go mod download golang.org/x/sys
```

**Comment by Activity00** [comment]
I have try to execute  go mod download golang.org/x/sys  but the same error show.

**Comment by asottile** [comment]
this isn't an issue with pre-commit but with the underlying tool -- you can reproduce by cloning the repository at the revision stated and running `go install ./...`
