### ISSUE TITLE
Empty .git/hooks/pre-commit.legacy File causes OSError 

### ISSUE THREAD

**Issue by BigTuna94** [pre-commit/pre-commit#2448]
### search tried in the issue tracker

is:issue is:open OSError

### describe your issue

In the latest version (2.19.0) `pre-commit install` appears to create an empty .git/hooks/pre-commit.legacy file. This causes an OSError when git (version 2.31.1) attempts to run the actual pre-commit hook.

Actual reported error:
```
$ git commit -m "dummy commit"
An unexpected error has occurred: OSError: [Errno 8] Exec format error: '/<repo path>/.git/hooks/pre-commit.legacy'
```

This appears to be the same core issue as: https://github.com/pre-commit/pre-commit/issues/1350
If I manually modify the empty file and add a shebang, the error subsides. However, the real solution is probably to avoid the creation of the empty file altogether. 

### pre-commit --version

pre-commit 2.19.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: local
    hooks:
    -   id: clang-format
        name: Enforce code style format
        language: system
        entry: make format-check-staged-silent
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.31.1
sys.version:
    3.9.7 (default, Sep 21 2021, 00:13:39) 
    [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
sys.executable: /root/.local/pipx/venvs/pre-commit/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: OSError: [Errno 8] Exec format error: '/<repo path>/.git/hooks/pre-commit.legacy'
```

```
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/pre-commit/lib64/python3.9/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/root/.local/pipx/venvs/pre-commit/lib64/python3.9/site-packages/pre_commit/main.py", line 361, in main
    return hook_impl(
  File "/root/.local/pipx/venvs/pre-commit/lib64/python3.9/site-packages/pre_commit/commands/hook_impl.py", line 232, in hook_impl
    retv, stdin = _run_legacy(hook_type, hook_dir, args)
  File "/root/.local/pipx/venvs/pre-commit/lib64/python3.9/site-packages/pre_commit/commands/hook_impl.py", line 43, in _run_legacy
    return subprocess.run(cmd, input=stdin).returncode, stdin
  File "/usr/lib64/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/<repo path>/.git/hooks/pre-commit.legacy'
```

**Comment by asottile** [comment]
how did that file get there to begin with?  do you have reproduction steps?

**Comment by asottile** [comment]
I can't reproduce -- the only way that would happen is if you already had created an (invalid) empty `.git/hooks/pre-commit` file

**Comment by jtlz2** [comment]
If this is a user error, does anyone have a solution? Thanks!

**Comment by asottile** [comment]
delete the empty file
