### ISSUE TITLE
.git/hooks/pre-commit points to a dead symlink in a non-writeable directory => IOError

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#246]
```
$ pre-commit install -f --install-hooks
An unexpected error has occurred: IOError: [Errno 13] Permission denied: '/home/.../.git/hooks/pre-commit'
$ cat ~/.pre-commit/pre-commit.log
An unexpected error has occurred: IOError: [Errno 13] Permission denied: '/home.../.git/hooks/pre-commit'
Traceback (most recent call last):
  File "/home/.../.tox/pre-commit/lib/python2.6/site-packages/pre_commit/error_handler.py", line 34, in error_handler
    yield
  File "/home/.../.tox/pre-commit/lib/python2.6/site-packages/pre_commit/main.py", line 135, in main
    hook_type=args.hook_type,
  File "/home/.../.tox/pre-commit/lib/python2.6/site-packages/pre_commit/commands/install_uninstall.py", line 73, in install
    with io.open(hook_path, 'w') as pre_commit_file_obj:
  File "/usr/lib64/python2.6/io.py", line 231, in open
    closefd)
  File "/usr/lib64/python2.6/io.py", line 631, in __init__
    _fileio._FileIO.__init__(self, name, mode, closefd)
IOError: [Errno 13] Permission denied: '/home/.../.git/hooks/pre-commit'
```

The fix is to use `lexists` here:

https://github.com/pre-commit/pre-commit/blob/a97cb38b9a8bf72e55489d5ba3f038722491bd1d/pre_commit/commands/install_uninstall.py#L56

A workaround is to manually rm the dead symlink

CC @dkunitsk

**Comment by asottile** [comment]
Fixed via #247
