### ISSUE TITLE
Stashed changes lost after `git add` while `pre-commit` was running

### ISSUE THREAD

**Issue by janosh** [pre-commit/pre-commit#2473]
### search tried in the issue tracker

Stashed changes conflicted with hook auto-fixes... Rolling back fixes... An unexpected error has occurred: CalledProcessError: command

### describe your issue

I ran `git add pymatgen/io/lammps/inputs.py` while `pre-commit` was in the process of checking a commit ended up being rejected. Restoring the patch afterwards failed and changes in about 30 files stashed while `pre-commit` ran appear to be lost.

I found #1787 which has a similar error but different cause.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
exclude: ^(docs|.*test_files|cmd_line|dev_scripts)

ci:
  autoupdate_schedule: monthly
  skip: [flake8, mypy, pylint]

repos:

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
          - --ignore-init-module-imports

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        exclude: pymatgen/analysis/vesta_cutoffs.yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        args: [-sn, --rcfile=pylintrc]
        additional_dependencies: [pylint]
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.36.1
sys.version:
    3.10.5 (main, Jun 23 2022, 17:14:57) [Clang 13.1.6 (clang-1316.0.21.2.5)]
sys.executable: /Users/janosh/.venv/py310/bin/python3.10
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/Cellar/git/2.36.1/libexec/git-core/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/janosh/.cache/pre-commit/patch1659212948-18379')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: patch failed: pymatgen/io/lammps/inputs.py:126
    error: pymatgen/io/lammps/inputs.py: patch does not apply
    
```

```
Traceback (most recent call last):
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 28, in _git_apply
    cmd_output_b('git', *args)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/git/2.36.1/libexec/git-core/git', 'apply', '--whitespace=nowarn', '/Users/janosh/.cache/pre-commit/patch1659212948-18379')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: patch failed: pymatgen/io/lammps/inputs.py:126
    error: pymatgen/io/lammps/inputs.py: patch does not apply
    error: patch failed: pymatgen/io/template.py:7
    error: pymatgen/io/template.py: patch does not apply
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 76, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 31, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/git/2.36.1/libexec/git-core/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/janosh/.cache/pre-commit/patch1659212948-18379')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: patch failed: pymatgen/io/lammps/inputs.py:126
    error: pymatgen/io/lammps/inputs.py: patch does not apply
    error: patch failed: pymatgen/io/template.py:7
    error: pymatgen/io/template.py: patch does not apply
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 28, in _git_apply
    cmd_output_b('git', *args)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/git/2.36.1/libexec/git-core/git', 'apply', '--whitespace=nowarn', '/Users/janosh/.cache/pre-commit/patch1659212948-18379')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: patch failed: pymatgen/io/lammps/inputs.py:126
    error: pymatgen/io/lammps/inputs.py: patch does not apply
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/main.py", line 358, in main
    return hook_impl(
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 254, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/commands/run.py", line 404, in run
    with contextlib.ExitStack() as exit_stack:
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 576, in __exit__
    raise exc_details[1]
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 561, in __exit__
    if cb(*exc_details):
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 100, in staged_files_only
    with _intent_to_add_cleared(), _unstaged_changes_cleared(patch_dir):
  File "/opt/homebrew/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 86, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/staged_files_only.py", line 31, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "/Users/janosh/.venv/py310/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/git/2.36.1/libexec/git-core/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/janosh/.cache/pre-commit/patch1659212948-18379')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: patch failed: pymatgen/io/lammps/inputs.py:126
    error: pymatgen/io/lammps/inputs.py: patch does not apply
```

**Comment by asottile** [comment]
yeah there's generally nothing that can be done against a user interfering with the process while it is running or changing the staging area -- fortunately things aren't "lost" -- the patch is shown at the beginning of your execution

**Comment by janosh** [comment]
Oh good. Just for later reference, had to add the `--reject` flag to apply the patch:

```py
git apply --reject ~/.cache/pre-commit/patch1659212948-18379
```

**Comment by janosh** [comment]
@asottile How to recover the changes was not obvious to me. Maybe `pre-commit` could show a hint when encountering this error?

> Use `git apply --reject ~/.cache/pre-commit/patch1659212948-18379` to recover the conflicting patch.
