### ISSUE TITLE
pre-commit autoupdate fails on psf/black update

### ISSUE THREAD

**Issue by philipsd6** [pre-commit/pre-commit#2491]
### search tried in the issue tracker

yes

### describe your issue

I'm running `pre-commit autoupdate` and when it gets to updating https://github.com/psf/black I get an unexpected error.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.37.1
sys.version:
    3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', 'stable  22.6.0')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'stable  22.6.0' did not match any file(s) known to git
    
```

```
Traceback (most recent call last):
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/store.py", line 182, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/store.py", line 164, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/store.py", line 179, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'protocol.version=2', 'fetch', 'origin', 'stable  22.6.0', '--depth=1')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: invalid refspec 'stable  22.6.0'
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/main.py", line 347, in main
    return autoupdate(
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/commands/autoupdate.py", line 172, in autoupdate
    _check_hooks_still_exist_at_rev(repo_config, new_info, store)
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/commands/autoupdate.py", line 85, in _check_hooks_still_exist_at_rev
    path = store.clone(repo_config['repo'], info.rev)
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/store.py", line 186, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/store.py", line 143, in _new_repo
    make_strategy(directory)
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/store.py", line 184, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/store.py", line 157, in _complete_clone
    git_cmd('checkout', ref)
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/store.py", line 179, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/philipsd6/.local/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'checkout', 'stable  22.6.0')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'stable  22.6.0' did not match any file(s) known to git
```

**Comment by asottile** [comment]
can you share your git config?

**Comment by asottile** [comment]
closing due to inactivity
