### ISSUE TITLE
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7m'

### ISSUE THREAD

**Issue by varian97** [pre-commit/pre-commit#2496]
### search tried in the issue tracker

RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7m'

### describe your issue

I already read the issue at https://github.com/pre-commit/pre-commit/issues/1375

I have checked the `.pre-commit-config.yaml` file and the `language_version` there is already 3.7, but I still got the error:
`RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7m'`

Changing it to `language_version: python3` doesn't help either

### pre-commit --version

2.19.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--ignore=E501']
  - repo: https://github.com/pre-commit/pre-commit
    rev: v1.21.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
      - id: reorder-python-imports
        language_version: python3.7
  - repo: meta
    hooks:
      - id: check-useless-excludes
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.17.1
sys.version:
    3.7.12 (default, Jul 24 2022, 17:03:09) 
    [GCC 7.5.0]
sys.executable: /home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/bin/python', '-mvirtualenv', '/home/varian97/.cache/pre-commit/repoepfwor4c/py_env-python3.7m', '-p', 'python3.7m')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7m'
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "/home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/lib/python3.7/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/lib/python3.7/site-packages/pre_commit/main.py", line 368, in main
    args=args.rest[1:],
  File "/home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/lib/python3.7/site-packages/pre_commit/commands/hook_impl.py", line 238, in hook_impl
    return retv | run(config, store, ns)
  File "/home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/lib/python3.7/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/lib/python3.7/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/lib/python3.7/site-packages/pre_commit/repository.py", line 80, in _hook_install
    hook.prefix, hook.language_version, hook.additional_dependencies,
  File "/home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/lib/python3.7/site-packages/pre_commit/languages/python.py", line 219, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/lib/python3.7/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/varian97/.local/share/virtualenvs/f1-chitauri-seWOygKn/bin/python', '-mvirtualenv', '/home/varian97/.cache/pre-commit/repoepfwor4c/py_env-python3.7m', '-p', 'python3.7m')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7m'
    
stderr: (none)
```

**Comment by asottile** [comment]
this isn't a pre-commit issue -- just as the one you found is not a pre-commit issue
