### ISSUE TITLE
Does autoupdate respect the language version, or will it update to an incompatible rev?

### ISSUE THREAD

**Issue by giasemidis** [pre-commit/pre-commit#2500]
### search tried in the issue tracker

yes

### describe your issue

Installed pre-commit 2.17 which is compatible with Python 3.6. While autopdating the hooks, the following error occurred.

It turned out that the auto-update of hooks updated the pre-commit version to a later version, not compatible to Python 3.6.

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/<removed>/.cache/pre-commit/repox65_201_/py_env-python3.6/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Looking in indexes: <removed>, https://pypi.python.org/simple
    Processing /Users/<removed>/.cache/pre-commit/repox65_201_
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'

stderr:
      ERROR: Command errored out with exit status 1:
       command: /Users/<removed>/.cache/pre-commit/repox65_201_/py_env-python3.6/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/<removed>/.cache/pre-commit/repox65_201_/setup.py'"'"'; __file__='"'"'/Users/georgios.giasemid-cg<removed>/.cache/pre-commit/repox65_201_/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/4l/s1vcts951czg_jgtjldn7jt8kg47dl/T/pip-pip-egg-info-2l93wpu9
           cwd: /Users/<removed>.cache/pre-commit/repox65_201_/
      Complete output (6 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/Users/<removed>/.cache/pre-commit/repox65_201_/setup.py", line 1
          from __future__ import annotations
          ^
      SyntaxError: future feature annotations is not defined
      ----------------------------------------
    WARNING: Discarding file:///Users/<removed>/.cache/pre-commit/repox65_201_. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Check the log at /Users/<removed>/.cache/pre-commit/pre-commit.log

Traceback (most recent call last):
  File "/var/folders/4l/s1vcts951czg_jgtjldn7jt8kg47dl/T/tmp90r_ahbu.py", line 291, in <module>
    main()
  File "/var/folders/4l/s1vcts951czg_jgtjldn7jt8kg47dl/T/tmp90r_ahbu.py", line 287, in main
    setup_git()
  File "/var/folders/4l/s1vcts951czg_jgtjldn7jt8kg47dl/T/tmp90r_ahbu.py", line 276, in setup_git
    install_precommit()
  File "/var/folders/4l/s1vcts951czg_jgtjldn7jt8kg47dl/T/tmp90r_ahbu.py", line 202, in install_precommit
    _run_conda_command([
  File "/var/folders/4l/s1vcts951czg_jgtjldn7jt8kg47dl/T/tmp90r_ahbu.py", line 61, in _run_conda_command
    _run_command(command, shell=True, **kwargs)
  File "/var/folders/4l/s1vcts951czg_jgtjldn7jt8kg47dl/T/tmp90r_ahbu.py", line 31, in _run_command
    process.check_returncode()
  File "/Users/georgios.giasemid-cg/opt/anaconda3/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '. $(conda info --base)/bin/activate <removed> && pre-commit autoupdate && pre-commit install --install-hooks' returned non-zero exit status 3.
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3.6
default_stages:
  - commit
  - push
fail_fast: false  # See every failure, not just first.
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--config=.flake8]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: check-nbstripout-installed
        name: check-nbstripout-installed
        entry: nbstripout --is-installed
        language: system
        types: [jupyter]
```

**Comment by asottile** [comment]
it's trivial to answer your question by _just trying it_
