### ISSUE TITLE
Bug during installing environment

### ISSUE THREAD

**Issue by cawoon** [pre-commit/pre-commit#2503]
### search tried in the issue tracker

Looked for all similar issues with CalledProcessError, tried changing virtualenv version a lot of times, doesn't help

### describe your issue

Trying to run pre-commit after I updated to python3.10, having this issue

```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /home/cawoon/.cache/pre-commit/patch1661510071-33086.
An unexpected error has occurred: CalledProcessError: command: ('python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Executable `python` not found
stderr: (none)
Check the log at /home/cawoon/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: ["--line-length=99"]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--gitignore", "--line-length=99", "--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          '-e', 'git+https://github.com/pycqa/pyflakes#egg=pyflakes',
          '-e', 'git+https://github.com/pycqa/pycodestyle#egg=pycodestyle',
        ]
        args: ["--max-line-length=99"]
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.34.1
sys.version:
    3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
sys.executable: /usr/bin/python3.10
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Executable `python` not found
stderr: (none)
```
```
Traceback (most recent call last):
  File "/home/cawoon/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/cawoon/.local/lib/python3.10/site-packages/pre_commit/main.py", line 386, in main
    return run(args.config, store, args)
  File "/home/cawoon/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 424, in run
    install_hook_envs(to_install, store)
  File "/home/cawoon/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/home/cawoon/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/home/cawoon/.local/lib/python3.10/site-packages/pre_commit/languages/python.py", line 221, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/home/cawoon/.local/lib/python3.10/site-packages/pre_commit/languages/helpers.py", line 48, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/cawoon/.local/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Executable `python` not found
stderr: (none)
```

**Comment by cawoon** [comment]
Searched more and found the answer here: https://github.com/pre-commit/pre-commit/issues/2299
