### ISSUE TITLE
An unexpected error has occurred: OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by lyp9624** [pre-commit/pre-commit#2504]
### search tried in the issue tracker

Errno 22

### describe your issue

I run pre-commit clean and then run pre-commit run --all-files, but got errno22 error. 
I  got this error with python3.9. and then upgrade to python3.10, but still got this error.
the os is mac OS monterey 12.2.1
I have 'git' installed. the git version is 2.20.X, when I got the error then tried to upgrade the git to  version 2.37.2, but still got the error.

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3
default_install_hook_types:
  - pre-commit
  - pre-merge-commit
  - pre-push
  - prepare-commit-msg
  - commit-msg
  - post-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
  - hooks:
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.

    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
  - hooks:
      - id: go-build
      - id: go-unit-tests
    repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
  - hooks:
      - id: golangci-lint
    repo: https://github.com/golangci/golangci-lint
    rev: v1.46.0
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.24.0
```

### version information

```
pre-commit version: 2.20.0
git --version: Executable `git` not found
sys.version:
    3.10.6 (main, Aug 11 2022, 13:49:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
sys.executable: /usr/local/Cellar/pre-commit/2.20.0/libexec/bin/python3.10
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: OSError: [Errno 22] Invalid argument
```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/2.20.0/libexec/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/2.20.0/libexec/lib/python3.10/site-packages/pre_commit/main.py", line 386, in main
    return run(args.config, store, args)
  File "/usr/local/Cellar/pre-commit/2.20.0/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 424, in run
    install_hook_envs(to_install, store)
  File "/usr/local/Cellar/pre-commit/2.20.0/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/Cellar/pre-commit/2.20.0/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/usr/local/Cellar/pre-commit/2.20.0/libexec/lib/python3.10/site-packages/pre_commit/languages/python.py", line 220, in install_environment
    with in_env(prefix, version):
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/local/Cellar/pre-commit/2.20.0/libexec/lib/python3.10/site-packages/pre_commit/languages/python.py", line 162, in in_env
    with envcontext(get_env_patch(envdir)):
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/local/Cellar/pre-commit/2.20.0/libexec/lib/python3.10/site-packages/pre_commit/envcontext.py", line 62, in envcontext
    env.clear()
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_collections_abc.py", line 982, in clear
    self.popitem()
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_collections_abc.py", line 975, in popitem
    del self[key]
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 690, in __delitem__
    unsetenv(encodedkey)
OSError: [Errno 22] Invalid argument
```

**Comment by asottile** [comment]
what happens if you run this?

```python
import os
os.environ.clear()
```

**Comment by asottile** [comment]
closing due to inactivity -- please answer the question and I'll reopen
