### ISSUE TITLE
 Executable `python` not found when committing new file

### ISSUE THREAD

**Issue by swiss-knight** [pre-commit/pre-commit#2525]
### search tried in the issue tracker

Executable `python` not found

### System information
Ubuntu 22.04.1
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
git version 2.34.1
pre-commit 2.20.0

Running this basic git command:
```
$ git add foo.py
$ git commit -m "Update foo.py"
```

leads to the error log hereunder. 

Please, also notice that `python` is no more a valid command on Ubuntu 22,04:
```
$ python
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
  
$ which python3
/usr/bin/python3
```

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10

repos:

  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: "22.8.0"
    hooks:
      - id: black
        language_version: python3.10
```

### ~/.cache/pre-commit/pre-commit.log (if present)

$ cat /home/username/.cache/pre-commit/pre-commit.log

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.34.1
sys.version:
    3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Executable `python` not found
stderr: (none)
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/main.py", line 358, in main
    return hook_impl(
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/commands/hook_impl.py", line 254, in hook_impl
    return retv | run(config, store, ns)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/commands/run.py", line 424, in run
    install_hook_envs(to_install, store)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/languages/python.py", line 221, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/languages/helpers.py", line 48, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Executable `python` not found
stderr: (none)
```

**Comment by asottile** [comment]
I tried your search and found at least two exact duplicates -- https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+%22Executable+python+not+found%22+is%3Aclosed+

**Comment by swiss-knight** [comment]
Hmm, I simply forgot to remove the back-tick in the search bar, sorry about that ;) 

I had no luck with:
```
$ cd my-project
$ virtualenv venv
$ venv/bin/python --version
bash: venv/bin/python: No such file or directory
```
from: https://github.com/pre-commit/pre-commit/issues/2299#issuecomment-1074697903

It seems python is located at `venv/local/bin/python` (notice the `local`):

```
$ venv/local/bin/python --version
Python 3.10.4
```
The error on committing didn't change.

I also tried to:
```
# ln -s /usr/bin/python3.10 /usr/local/bin/python
```

But then:

```
$ git commit -m "Update foo.py"
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/username/.cache/pre-commit/repombg_52en/py_env-python3.10/bin/python>>
- expected version: 3.10.4.final.0

Check the log at /home/username/.cache/pre-commit/pre-commit.log
```

Traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/main.py", line 358, in main
    return hook_impl(
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/commands/hook_impl.py", line 254, in hook_impl
    return retv | run(config, store, ns)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/commands/run.py", line 424, in run
    install_hook_envs(to_install, store)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/repository.py", line 84, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/username/.cache/pre-commit/repombg_52en/py_env-python3.10/bin/python>>
- expected version: 3.10.4.final.0
```

**Comment by asottile** [comment]
none of the workaround involve making a bad symlink -- read the threads and do what they say to do
