### ISSUE TITLE
get_remote_url not compatible with new version of Git ?

### ISSUE THREAD

**Issue by tarrade** [pre-commit/pre-commit#2540]
### search you tried in the issue tracker

get_remote_url

### describe your issue

When using pre-commit hook https://github.com/zricethezav/gitleaks, I faced an issue during the creation of the env [issue](https://github.com/zricethezav/gitleaks/issues/994).

I am using :
```
git --version
git version 2.37.3
```

It seems that with the recent version of git, the path to the config need to be set:
` git config -f .git/config --get remote.origin.url`

https://github.com/pre-commit/pre-commit/blob/028efcbd879ccdac7514ea4334462841bb0ca2c0/pre_commit/git.py#L96

I did a test and the following fix the issue:
```
def get_remote_url(git_root: str) -> str:
    _, out, _ = cmd_output('git', 'config', '-f', git_root+'/.git/config', 'remote.origin.url', cwd=git_root)
    return out.strip()
```

I am sure there is a better way to fix this issue. Any idea ?

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3.10

default_stages: [commit, push]


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: .*ipynb
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown"]
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-ast
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: name-tests-test
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.13.0
    hooks:
      - id: gitleaks
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
pre-commit version: 2.20.0
git --version: git version 2.37.3
sys.version:
    3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
sys.executable: /opt/conda/envs/jupyter-notebook/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'config', 'remote.origin.url')
return code: 1
expected return code: 0
stdout: (none)
stderr: (none)
```

```
Traceback (most recent call last):
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/main.py", line 386, in main
    return run(args.config, store, args)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/commands/run.py", line 424, in run
    install_hook_envs(to_install, store)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/languages/golang.py", line 69, in install_environment
    remote = git.get_remote_url(prefix.prefix_dir)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/git.py", line 97, in get_remote_url
    _, out, _ = cmd_output('git', 'config', 'remote.origin.url', cwd=git_root)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/util.py", line 152, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
  File "/opt/conda/envs/jupyter-notebook/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'config', 'remote.origin.url')
return code: 1
expected return code: 0
stdout: (none)
stderr: (none)
```

**Comment by tarrade** [comment]
here the content of `~/.gitconfig`

```
[http "https://github.company.com"]
        proxy =
        sslVerify = false

[https "https://github.company.com"]
        proxy =
        sslVerify = false

[http "https://github.com"]
    proxy = http://proxy:8080

[https "https://github.com"]
    proxy = http://proxy:8080

[credential]
        helper = store

[core]
        autocrlf = false
        filemode = false

[pull]
        rebase = false

[alias]
        push-tag-build = !git push && git push --tags && bash $1

[diff "jupyternotebook"]
        command = git-nbdiffdriver diff

[merge "jupyternotebook"]
        driver = git-nbmergedriver merge %O %A %B %L %P
        name = jupyter notebook merge driver

[difftool "nbdime"]
        cmd = git-nbdifftool diff \"$LOCAL\" \"$REMOTE\" \"$BASE\"

[difftool]
        prompt = false

[mergetool "nbdime"]
        cmd = git-nbmergetool merge \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"

[mergetool]
        prompt = false
[pager]
        branch = false
[user]
        email = email@company.com
        name = Name
```

the content of `/.cache/pre-commit/repoa8g_h873/.git/config` 
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/zricethezav/gitleaks
        fetch = +refs/heads/*:refs/remotes/origin/*
```

what is `env` for you ?
In my case, I set GIT_CONFIG to point to my gitconfig (it seems things change recently in git)
`export GIT_CONFIG=/home/jupyter/.gitconfig`

**Comment by asottile** [comment]
yeah `export GIT_CONFIG=...` is the problem -- why do you have that?

**Comment by tarrade** [comment]
Right it seems to be problematic. I did a test without before but I should have done something wrong since the issue was still present. I also misunderstood the git doc. OK, I will clean my setup and try again to be 100% sure and then close this ticket.
Thanks for the help.

**Comment by tarrade** [comment]
@asottile unfortunately from a fresh VM the issue is still there (no GIT_CONFIG env variable)

```
(jupyter-notebook)jupyter@:~/.cache/pre-commit/repodxujvbpg$echo $GIT_CONFIG 

(jupyter-notebook)jupyter@:~/.cache/pre-commit/repodxujvbpg$git config remote.origin.url
(jupyter-notebook)jupyter@:~/.cache/pre-commit/repodxujvbpg$git config -f .git/config remote.origin.url
https://github.com/zricethezav/gitleaks
```

it seems to be related that now the path need to be given. From the code:
https://github.com/git/git/blob/4bb9eb5f91102f1df4f5d47cf7d78ed67307f144/Documentation/git-config.txt#L146-L152
```

-f config-file::
--file config-file::

For reading options: read only from the specified file rather than from all available files.
```

**Comment by asottile** [comment]
can you show the full contents of `env` when running that?  I cannot reproduce

**Comment by asottile** [comment]
and or any other relevant settings in that vm?

probably these `git config --list --show-origin` and `env | grep GIT`

**Comment by tarrade** [comment]
@asottile you are right. Thanks for checking.

`export GIT_CONFIG=` is not enough. The variable still exist but is empty. Until now it was always working.
Doing it the right way `unset GIT_CONFIG` seems to work. I think now it should be good. I will start again but now I am confident that my issue is understood and fixed. Let see

**Comment by tarrade** [comment]
ok, problem fixed. GIT_CONFIG should no be defined at all, having an empty value will create the issue as well. Closing
