### ISSUE TITLE
Pre-commit fail after update ubuntu from 22.04 to 22.10

### ISSUE THREAD

**Issue by imitsho** [pre-commit/pre-commit#2557]
### search you tried in the issue tracker

Pre-commit fail after update ubuntu from 22.04 to 22.10

### describe your issue

I was doing commit:
```
$ git commit -m "test_commit"
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/vvv/.cache/pre-commit/repozlijtjf9/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/vvv/.cache/pre-commit/repozlijtjf9
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    
stderr:
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))': /simple/ruamel-yaml/
    ERROR: Could not find a version that satisfies the requirement ruamel.yaml>=0.15 (from pre-commit-hooks) (from versions: none)
    ERROR: No matching distribution found for ruamel.yaml>=0.15
    
Check the log at /home/vvv/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: detect-private-key
      - id: check-ast
      - id: check-toml
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-blind-except
          - flake8-builtins
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-pytest-style
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--py=39", "--line-length=120", "--multi-line=0", "--lai=2",
               "--use-parentheses", "--filter-files"]
  - repo: 'https://github.com/pre-commit/pre-commit'
    rev: v2.20.0
    hooks:
      - id: validate_manifest
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.37.2
sys.version:
    3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/vvv/.cache/pre-commit/repo8jrmrvxw/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/vvv/.cache/pre-commit/repo8jrmrvxw
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'

stderr:
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or director>
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or director>
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or director>
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or director>
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or director>
    ERROR: Could not find a version that satisfies the requirement ruamel.yaml>=0.15 (from pre-commit-hooks) (from versions: none)
    ERROR: No matching distribution found for ruamel.yaml>=0.15

```

```
Traceback (most recent call last):
  File "/home/vvv/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/vvv/.local/lib/python3.10/site-packages/pre_commit/main.py", line 358, in main
    return hook_impl(
  File "/home/vvv/.local/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 254, in hook_impl
    return retv | run(config, store, ns)
  File "/home/vvv/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 424, in run
    install_hook_envs(to_install, store)
  File "/home/vvv/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/home/vvv/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/home/vvv/.local/lib/python3.10/site-packages/pre_commit/languages/python.py", line 221, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/home/vvv/.local/lib/python3.10/site-packages/pre_commit/languages/helpers.py", line 48, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/vvv/.local/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/vvv/.cache/pre-commit/repo8jrmrvxw/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/vvv/.cache/pre-commit/repo8jrmrvxw
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'

stderr:
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or director>
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or director>
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or director>
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or director>
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or director>
    ERROR: Could not find a version that satisfies the requirement ruamel.yaml>=0.15 (from pre-commit-hooks) (from versions: none)
    ERROR: No matching distribution found for ruamel.yaml>=0.15
```

**Comment by asottile** [comment]
your python's ssl support is broken, this isn't a pre-commit issue

**Comment by imitsho** [comment]
I reinstall pre commit and now when i do pre-commit i get this:
```
(venv) $ git commit -m "test_commit"
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/vvv/.cache/pre-commit/repo8jrmrvxw/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/vvv/.cache/pre-commit/repo8jrmrvxw
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [1 lines of output]
          ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /home/vvv/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
probably means your `virtualenv` is broken?
