### ISSUE TITLE
question (feature?): how to report a summary of hooks and languages for a given project?

### ISSUE THREAD

**Issue by kratsg** [pre-commit/pre-commit#2559]
Hi (I love pre-commit). One minor frustration I had today was due to having to work with lots of differently-maintained machines and sometimes running into slightly unhelpful errors like this upon a pre-commit run:

### version information

pre-commit version: 2.20.0
git --version: git version 1.8.3.1
sys.version:
    3.8.15 (default, Oct 25 2022, 15:42:11) 
    [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
sys.executable: /home/kbai/module-qc-tools/venv/bin/python
os.name: posix
sys.platform: linux

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node', '/home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node)
    /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node)
    /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node)
    /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node)
    /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node)
    /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node)
    
```

```
Traceback (most recent call last):
  File "/home/kbai/module-qc-tools/venv/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/kbai/module-qc-tools/venv/lib/python3.8/site-packages/pre_commit/main.py", line 386, in main
    return run(args.config, store, args)
  File "/home/kbai/module-qc-tools/venv/lib/python3.8/site-packages/pre_commit/commands/run.py", line 424, in run 
    install_hook_envs(to_install, store)
  File "/home/kbai/module-qc-tools/venv/lib/python3.8/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/home/kbai/module-qc-tools/venv/lib/python3.8/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/home/kbai/module-qc-tools/venv/lib/python3.8/site-packages/pre_commit/languages/node.py", line 111, in install_environment
    helpers.run_setup_cmd(prefix, local_install_cmd)
  File "/home/kbai/module-qc-tools/venv/lib/python3.8/site-packages/pre_commit/languages/helpers.py", line 48, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/kbai/module-qc-tools/venv/lib/python3.8/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/node', '/home/kbai/.cache/pre-commit/repotpj7dit1/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
```

Now, certainly, this tells me two things

- there's a problem with `node`
- it's likely a problem that `pre-commit` is installing a hook that uses a newer version of `node` that the machine can't support

This is fine. But then now I have to essentially (as I have very bad memory) go to each repository one-by-one and look at the `hooks.yaml` to determine the language and figure out which of my hooks is using `node` (in this case, it was `mirrors-prettier`), and then specify the language version to downgrade `node` so that it works fine. The somewhat frustrating part was a lack of documentation or tooling to easily figure out which hook is the issue.

Suggestions? Thoughts? I hope this doesn't come off as too-complainy.

**Comment by asottile** [comment]
sounds like you're prescribing a solution when actually your problem doesn't need one (XY)

the output **shows the specific hook right before it fails**:

```console
$ pre-commit  install-hooks
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks:crash-for-me-plz.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/asottile/.cache/pre-commit/repocw60a_l7/py_env-python3.8/bin/python', '-mpip', 'install', '.', 'crash-for-me-plz')
return code: 1
expected return code: 0
stdout:
    Processing /home/asottile/.cache/pre-commit/repocw60a_l7
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    
stderr:
    ERROR: Could not find a version that satisfies the requirement crash-for-me-plz (from versions: none)
    ERROR: No matching distribution found for crash-for-me-plz
    
Check the log at /home/asottile/.cache/pre-commit/pre-commit.log
```

but what you actually probably want is [default_language_version](https://pre-commit.com/#top_level-default_language_version)

**Comment by kratsg** [comment]
Thanks! I need to double-check if I ever saw the hook (issue is that it "installs fine" but crashes during runtime) and I was never able to figure out which hook crashed from the output, so it might have just been something I overlooked...

**Comment by asottile** [comment]
the output you've got above is during install -- if it failed at runtime it'd show `- hook id: ...` in the output as well
