### ISSUE TITLE
Cannot run with python 11

### ISSUE THREAD

**Issue by huss3in** [pre-commit/pre-commit#2563]
I got this error while running ` pre-commit run --all-files` 
`
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\$DLS000-RTK7I4J9LMEC\\.cache\\pre-commit\\repoa66cgebi\\py_env-python3.11\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\users\$dls000-rtk7i4j9lmec\.cache\pre-commit\repoa66cgebi
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting ruamel.yaml>=0.15
      Using cached ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
    Collecting toml
      Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
    Building wheels for collected packages: pre-commit-hooks
      Building wheel for pre-commit-hooks (setup.py): started
      Building wheel for pre-commit-hooks (setup.py): finished with status 'error'
      Running setup.py clean for pre-commit-hooks
    Failed to build pre-commit-hooks
    Installing collected packages: toml, ruamel.yaml, pre-commit-hooks
      Running setup.py install for pre-commit-hooks: started
      Running setup.py install for pre-commit-hooks: finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error

      python setup.py bdist_wheel did not run successfully.
      exit code: 1

      [95 lines of output]
      C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_added_large_files.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_ast.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_builtin_literals.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_byte_order_marker.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_case_conflict.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_docstring_first.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_executables_have_shebangs.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_json.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_merge_conflict.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_symlinks.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_toml.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_vcs_permalinks.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_xml.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\check_yaml.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\debug_statement_hook.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\destroyed_symlinks.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\detect_aws_credentials.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\detect_private_key.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\end_of_file_fixer.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\file_contents_sorter.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\fix_byte_order_marker.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\fix_encoding_pragma.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\forbid_new_submodules.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\mixed_line_ending.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\no_commit_to_branch.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\pretty_format_json.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\removed.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\requirements_txt_fixer.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\sort_simple_yaml.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\string_fixer.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\tests_should_end_in_test.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\trailing_whitespace_fixer.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\util.py -> build\lib\pre_commit_hooks
      copying pre_commit_hooks\__init__.py -> build\lib\pre_commit_hooks
      C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build\bdist.win-amd64\wheel
      running install
      Traceback (most recent call last):
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\util.py", line 212, in subst_vars
          return _subst_compat(s).format_map(lookup)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      KeyError: 'DLS000'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\setup.py", line 2, in <module>
          setup()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\wheel\bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.ensure_finalized()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\cmd.py", line 109, in ensure_finalized
          self.finalize_options()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\command\install.py", line 45, in finalize_options
          orig.install.finalize_options(self)
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\command\install.py", line 440, in finalize_options
          self.expand_basedirs()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\command\install.py", line 620, in expand_basedirs
          self._expand_attrs(['install_base', 'install_platbase', 'root'])
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\command\install.py", line 614, in _expand_attrs
          val = subst_vars(val, self.config_vars)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\util.py", line 214, in subst_vars
          raise ValueError(f"invalid variable {var}")
      ValueError: invalid variable 'DLS000'
      [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for pre-commit-hooks
      error: subprocess-exited-with-error

      Running setup.py install for pre-commit-hooks did not run successfully.
      exit code: 1

      [46 lines of output]
      C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running install
      C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      Traceback (most recent call last):
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\util.py", line 212, in subst_vars
          return _subst_compat(s).format_map(lookup)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      KeyError: 'DLS000'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\setup.py", line 2, in <module>
          setup()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.ensure_finalized()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\cmd.py", line 109, in ensure_finalized
          self.finalize_options()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\command\install.py", line 45, in finalize_options
          orig.install.finalize_options(self)
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\command\install.py", line 440, in finalize_options
          self.expand_basedirs()
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\command\install.py", line 620, in expand_basedirs
          self._expand_attrs(['install_base', 'install_platbase', 'root'])
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\command\install.py", line 614, in _expand_attrs
          val = subst_vars(val, self.config_vars)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\$DLS000-RTK7I4J9LMEC\.cache\pre-commit\repoa66cgebi\py_env-python3.11\Lib\site-packages\setuptools\_distutils\util.py", line 214, in subst_vars
          raise ValueError(f"invalid variable {var}")
      ValueError: invalid variable 'DLS000'
      [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure

    Encountered error while trying to install package.

    pre-commit-hooks

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for output from the failure.

`
Can you advice please?

**Comment by asottile** [comment]
see the library where the error is from? report the bug there
