### ISSUE TITLE
Pre-commit with flake8 hook fails when run on Python 3.7

### ISSUE THREAD

**Issue by enikonovad** [pre-commit/pre-commit#2587]
### search you tried in the issue tracker

Python 3.7, flake8

### describe your issue

I use pre-commit in Github workflows. Recently, `pre-commit run flake8 --all-files` on Python 3.7 started to fail with the following stack trace:

```
pre-commit autoupdate
Updating https://github.com/pre-commit/mirrors-yapf ... already up to date.
Updating https://gitlab.com/pycqa/flake8 ... already up to date.
Updating https://github.com/executablebooks/mdformat ... already up to date.
pre-commit run flake8 --all-files
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repohodq5jtu/py_env-python3.7/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repohodq5jtu/py_env-python3.7/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/runner/.cache/pre-commit/repohodq5jtu/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/runner/.cache/pre-commit/repohodq5jtu/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/home/runner/.cache/pre-commit/repohodq5jtu/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "/home/runner/.cache/pre-commit/repohodq5jtu/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
  File "/home/runner/.cache/pre-commit/repohodq5jtu/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
    self.namespace, local_plugins=local_plugins
  File "/home/runner/.cache/pre-commit/repohodq5jtu/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "/home/runner/.cache/pre-commit/repohodq5jtu/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'
```

Please note that this only happens in Python 3.7. Whereas in python 3.8 and 3.9 there is no issue.

I noticed that in `setup.cfg` you have this line:
> importlib-metadata;python_version<"3.8"

Which installs the latest `importlib_metadata` and causes flake8 to fail.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [--in-place, --parallel, --recursive, --style, .yapf-config]
        exclude: "(oscal|third_party)"
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--extend-ignore, "P1,C812,C813,C814,C815,C816,W503,W605"]
        additional_dependencies:
          [
            flake8-2020,
            flake8-broken-line,
            flake8-bugbear,
            flake8-builtins,
            flake8-commas,
            flake8-comprehensions,
            flake8-docstrings,
            flake8-eradicate,
            flake8-import-order,
            flake8-mutable,
            flake8-pep3101,
            flake8-print,
            flake8-quotes,
            flake8-string-format,
            flake8-use-fstring,
            pep8-naming,
          ]
        exclude: "(oscal|third_party)"
        stages: [commit]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-tables
      - mdformat-config
      - mdformat-frontmatter
```

**Comment by asottile** [comment]
not a pre-commit nor flake8 problem, please Google search your error message

**Comment by aasimbana** [comment]
How did you solve it?
