### ISSUE TITLE
pre-commit fails to install flake8 hook

### ISSUE THREAD

**Issue by cbrown1234** [pre-commit/pre-commit#2596]
### search you tried in the issue tracker

is:issue flake8 github

### describe your issue

pre-commit fails to install flake8 hook, with github auth issues:
```
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
Username for 'https://gitlab.com':
Password for 'https://gitlab.com':

Username for 'https://gitlab.com': Password for 'https://gitlab.com':
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.com/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
    fatal: Authentication failed for 'https://gitlab.com/pycqa/flake8.git/'

Check the log at /home/chris/.cache/pre-commit/pre-commit.log
```
or in CI:
```
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: could not read Username for 'https://gitlab.com'/: No such device or address
```

I was able to clone the flake8 repo just using git though:
```
git clone https://github.com/PyCQA/flake8.git
Cloning into 'flake8'...
remote: Enumerating objects: 12166, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 12166 (delta 29), reused 38 (delta 20), pack-reused 12081
Receiving objects: 100% (12166/12166), 3.33 MiB | 4.45 MiB/s, done.
Resolving deltas: 100% (7723/7723), done.
```
So seems to be an issue with pre-commit

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.25.1
sys.version:
    3.8.12 (default, Sep  3 2021, 11:59:44)
    [GCC 9.3.0]
sys.executable: /home/chris/.local/pipx/venvs/pre-commit/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.com/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-d
enied
    fatal: Authentication failed for 'https://gitlab.com/pycqa/flake8.git/'

```

```
Traceback (most recent call last):
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/store.py", line 182, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/store.py", line 164, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/store.py", line 179, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'protocol.version=2', 'fetch', 'origin', '5.0.4', '--depth=1')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.com/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
    fatal: Authentication failed for 'https://gitlab.com/pycqa/flake8.git/'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/main.py", line 382, in main
    return install_hooks(args.config, store)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/commands/install_uninstall.py", line 146, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/repository.py", line 227, in all_hooks
    return tuple(
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/repository.py", line 230, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/repository.py", line 205, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/repository.py", line 171, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/store.py", line 186, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/store.py", line 143, in _new_repo
    make_strategy(directory)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/store.py", line 184, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/store.py", line 156, in _complete_clone
    git_cmd('fetch', 'origin', '--tags')
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/store.py", line 179, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/chris/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.com/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
    fatal: Authentication failed for 'https://gitlab.com/pycqa/flake8.git/'
```

**Comment by asottile** [comment]
https://github.com/PyCQA/flake8/issues/1737
