### ISSUE TITLE
pre-commit fails in pyproject.toml for pydocstyle on Ubuntu but not Mac

### ISSUE THREAD

**Issue by richtong** [pre-commit/pre-commit#2614]
OK, this is a strange one I have what i think are identical configurations on Ubuntu 20.04 and MacOS Venture on an M1 Macbook Pro, but when I try to run pre-commit, I get this error processing of all things the pyproject.toml inside one of the venv in ~/.cache/precommit/repo...

Here is the error that I'm getting when processing the pyproject.toml (which I checked is identical on the Mac and Ubuntu). The strangest thing about this is that when I look  at the location of the error, it is refering not to my pipenv installation but the asdf installation of python, so maybe I don't quite understand how the system finds its python. I thought it would use the python that is active where I called pre-commit but how does this actually work?

```
[tool.black]
line-length = 79
target-version = ['py36']
skip-string-normalization = true

[tool.isort]
profile = "black"
src_paths = ["src/pydocstyle"]
line_length = 79

```

And here is the error log, I'm not qutie sure how I debug this I tried to uninstall pre-commit (I'm using the brew version for both Ubuntu and MacOS). I also did a pre-commit clean and also deleted the entire ~/.cache directory and I'm using pipenv so the python is in a virtyual directory but its the same version 3.9.15 on both

```
### error information

An unexpected error has occurred: CalledProcessError: command: ('/home/rich/.cache/pre-commit/repormw7bus9/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/rich/.cache/pre-commit/repormw7bus9
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [64 lines of output]
          running dist_info
          creating /tmp/pip-modern-metadata-4z87kidj/pydocstyle.egg-info
          writing /tmp/pip-modern-metadata-4z87kidj/pydocstyle.egg-info/PKG-INFO
          writing dependency_links to /tmp/pip-modern-metadata-4z87kidj/pydocstyle.egg-info/dependency_links.txt
          writing entry points to /tmp/pip-modern-metadata-4z87kidj/pydocstyle.egg-info/entry_points.txt
          writing requirements to /tmp/pip-modern-metadata-4z87kidj/pydocstyle.egg-info/requires.txt
          writing top-level names to /tmp/pip-modern-metadata-4z87kidj/pydocstyle.egg-info/top_level.txt
          writing manifest file '/tmp/pip-modern-metadata-4z87kidj/pydocstyle.egg-info/SOURCES.txt'
          reading manifest file '/tmp/pip-modern-metadata-4z87kidj/pydocstyle.egg-info/SOURCES.txt'
          reading manifest template 'MANIFEST.in'
          adding license file 'LICENSE-MIT'
          writing manifest file '/tmp/pip-modern-metadata-4z87kidj/pydocstyle.egg-info/SOURCES.txt'
          creating '/tmp/pip-modern-metadata-4z87kidj/pydocstyle-6.1.1.dist-info'
   Traceback (most recent call last):
            File "/home/rich/.cache/pre-commit/repormw7bus9/py_env-python3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "/home/rich/.cache/pre-commit/repormw7bus9/py_env-python3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/rich/.cache/pre-commit/repormw7bus9/py_env-python3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
              self.run_setup()
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
              super(_BuildMetaLegacyBackend,
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
              exec(code, locals())
            File "<string>", line 15, in <module>
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
              return distutils.core.setup(**attrs)
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
              return run_commands(dist)
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
              dist.run_commands()
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
              self.run_command(cmd)
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
              super().run_command(command)
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
              cmd_obj.run()
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 101, in run
              bdist_wheel = self.get_finalized_command('bdist_wheel')
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
              cmd_obj = self.distribution.get_command_obj(command, create)
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
              klass = self.get_command_class(command)
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 953, in get_command_class
              self.cmdclass[command] = cmdclass = ep.load()
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
              module = import_module(match.group('module'))
            File "/home/rich/.asdf/installs/python/3.9.15/lib/python3.9/importlib/__init__.py", line 127, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
            File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
            File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
            File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
            File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
            File "<frozen importlib._bootstrap_external>", line 850, in exec_module
            File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 28, in <module>
              from .macosx_libfile import calculate_macosx_platform_tag
            File "/tmp/pip-build-env-cqauom98/overlay/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 43, in <module>
              import ctypes
            File "/home/rich/.asdf/installs/python/3.9.15/lib/python3.9/ctypes/__init__.py", line 8, in <module>
              from _ctypes import Union, Structure, Array
          ModuleNotFoundError: No module named '_ctypes'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

```

**Comment by asottile** [comment]
this isn't a pre-commit problem. your asdf-based python is poorly compiled (if you `python -c 'import ctypes'` you'll see the same issue)
