### ISSUE TITLE
Cannot run pre-commit run --all-files

### ISSUE THREAD

**Issue by anindya-vedant** [pre-commit/pre-commit#2626]
### search you tried in the issue tracker

An error has occurred: InvalidConfigError:  =====> .pre-commit-config.yaml is not a file

### describe your issue

I am setting up pre-commit for my new project, I installed pre-commit in my virtual env and then configured (mentioned below) the pre-commit-config.yaml file also, installed the pre-commit but when I ran the pre-commit run --all-files I get and InvalidConfigError

### pre-commit --version

2.20.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict
        exclude: .github/.pre-commit-config.yml
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        args: [--line-length=200]
        exclude: .github/.pre-commit-config.yml
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.34.1.windows.1
sys.version:
    3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
sys.executable: D:\Anaconda3-2021\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An error has occurred: InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
```

```
Traceback (most recent call last):
  File "D:\Anaconda3-2021\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "D:\Anaconda3-2021\lib\site-packages\pre_commit\main.py", line 386, in main
    return run(args.config, store, args)
  File "D:\Anaconda3-2021\lib\site-packages\pre_commit\commands\run.py", line 408, in run
    config = load_config(config_file)
  File "D:\Anaconda3-2021\lib\site-packages\cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "D:\Anaconda3-2021\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Anaconda3-2021\lib\site-packages\cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "D:\Anaconda3-2021\lib\site-packages\cfgv.py", line 40, in reraise_as
    yield
  File "D:\Anaconda3-2021\lib\site-packages\cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} is not a file')
pre_commit.clientlib.InvalidConfigError: 
=====> .pre-commit-config.yaml is not a file
```

**Comment by asottile** [comment]
I assume you realized the error message is in fact *not* lying and you created the correct file and it went away?

**Comment by asottile** [comment]
and if you searched your error message you would have found https://github.com/pre-commit/pre-commit/issues/2401 who had the same problem
