### ISSUE TITLE
install for https://github.com/pycqa/flake8 hangs

### ISSUE THREAD

**Issue by acdha** [pre-commit/pre-commit#2647]
### search you tried in the issue tracker

hang, flake8

### describe your issue

I ran `pre-commit autoupdate` and `pre-commit install-hooks` hung (30+ minutes) with no information:

```
[INFO] Installing environment for https://github.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

I suspect this is due to some issue installing flake8 6.0.0 because that release is recent changing the version to 5.0.4 fixes this but that's a guess since nothing is logged anywhere. If I had to hazard a guess, one of the plugins I have in the config is not yet compatible with that so I'll check them but I was thinking that this seems like something where pre-commit could help make this easier to report either by looking for specific log messages or at least including some of the tool output in the log file.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
---
exclude: ".*/vendor/.*"
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - l
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-logging-format
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.39.0
sys.version:
    3.11.0 (main, Oct 26 2022, 19:06:18) [Clang 14.0.0 (clang-1400.0.29.202)]
sys.executable: /opt/homebrew/Cellar/pre-commit/2.20.0_1/libexec/bin/python3.11
os.name: posix
sys.platform: darwin
```

### error information

```
Interrupted (^C): KeyboardInterrupt: 
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/2.20.0_1/libexec/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.20.0_1/libexec/lib/python3.11/site-packages/pre_commit/main.py", line 382, in main
    return install_hooks(args.config, store)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/2.20.0_1/libexec/lib/python3.11/site-packages/pre_commit/commands/install_uninstall.py", line 146, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/opt/homebrew/Cellar/pre-commit/2.20.0_1/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/2.20.0_1/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/2.20.0_1/libexec/lib/python3.11/site-packages/pre_commit/languages/python.py", line 221, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/opt/homebrew/Cellar/pre-commit/2.20.0_1/libexec/lib/python3.11/site-packages/pre_commit/languages/helpers.py", line 48, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/opt/homebrew/Cellar/pre-commit/2.20.0_1/libexec/lib/python3.11/site-packages/pre_commit/util.py", line 142, in cmd_output_b
    stdout_b, stderr_b = proc.communicate()
                         ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

**Comment by asottile** [comment]
it's trivial to replicate without `pre-commit` -- your plugins are conflicting and so `pip` is trying every combination under the sun to resolve:

```console
$ pip install flake8==6.0.0 l flake8-bugbear flake8-builtins flake8-comprehensions flake8-eradicate flake8-logging-format
Collecting flake8==6.0.0
  Downloading flake8-6.0.0-py2.py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 kB 4.8 MB/s eta 0:00:00
Collecting l
  Downloading l-0.11.0.zip (10 kB)
  Preparing metadata (setup.py) ... done
Collecting flake8-bugbear
  Downloading flake8_bugbear-22.12.6-py3-none-any.whl (23 kB)
Collecting flake8-builtins
  Downloading flake8_builtins-2.0.1-py3-none-any.whl (13 kB)
Collecting flake8-comprehensions
  Downloading flake8_comprehensions-3.10.1-py3-none-any.whl (7.3 kB)
Collecting flake8-eradicate
  Downloading flake8_eradicate-1.4.0-py3-none-any.whl (5.2 kB)
Collecting flake8-logging-format
  Downloading flake8-logging-format-0.9.0.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting pycodestyle<2.11.0,>=2.10.0
  Downloading pycodestyle-2.10.0-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 28.1 MB/s eta 0:00:00
Collecting mccabe<0.8.0,>=0.7.0
  Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting pyflakes<3.1.0,>=3.0.0
  Downloading pyflakes-3.0.1-py2.py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 38.3 MB/s eta 0:00:00
Collecting betterpath
  Downloading betterpath-0.2.2.tar.gz (38 kB)
  Preparing metadata (setup.py) ... done
Collecting click
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 56.3 MB/s eta 0:00:00
Collecting attrs>=19.2.0
  Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 39.5 MB/s eta 0:00:00
Collecting flake8-eradicate
  Downloading flake8_eradicate-1.3.0-py3-none-any.whl (5.1 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (from flake8-eradicate) (65.5.0)
  Downloading flake8_eradicate-1.2.1-py3-none-any.whl (5.1 kB)
  Downloading flake8_eradicate-1.2.0-py3-none-any.whl (5.1 kB)
  Downloading flake8_eradicate-1.1.0-py3-none-any.whl (5.1 kB)
  Downloading flake8_eradicate-1.0.0-py3-none-any.whl (5.0 kB)
  Downloading flake8_eradicate-0.4.0-py3-none-any.whl (4.7 kB)
Collecting eradicate<2.0,>=1.0
  Downloading eradicate-1.0.tar.gz (4.6 kB)
  Preparing metadata (setup.py) ... done
Collecting flake8-eradicate
  Downloading flake8_eradicate-0.3.0-py3-none-any.whl (4.7 kB)
  Downloading flake8_eradicate-0.2.4-py3-none-any.whl (4.7 kB)
  Downloading flake8_eradicate-0.2.3-py3-none-any.whl (6.2 kB)
  Downloading flake8_eradicate-0.2.2-py3-none-any.whl (6.3 kB)
  Downloading flake8_eradicate-0.2.1-py3-none-any.whl (6.4 kB)
  Downloading flake8_eradicate-0.2.0-py3-none-any.whl (6.6 kB)
  Downloading flake8_eradicate-0.1.1-py3-none-any.whl (5.6 kB)
Collecting eradicate<0.3.0,>=0.2.1
  Downloading eradicate-0.2.1.tar.gz (4.4 kB)
  Preparing metadata (setup.py) ... done
Collecting flake8-eradicate
  Downloading flake8_eradicate-0.1.0-py3-none-any.whl (5.3 kB)
INFO: pip is looking at multiple versions of flake8-comprehensions to determine which version is compatible with other requirements. This could take a while.
Collecting flake8-comprehensions
  Downloading flake8_comprehensions-3.10.0-py3-none-any.whl (7.3 kB)
  Downloading flake8_comprehensions-3.9.0-py3-none-any.whl (6.6 kB)
  Downloading flake8_comprehensions-3.8.0-py3-none-any.whl (6.6 kB)
  Downloading flake8_comprehensions-3.7.0-py3-none-any.whl (6.7 kB)
  Downloading flake8_comprehensions-3.6.1-py3-none-any.whl (6.7 kB)
  Downloading flake8_comprehensions-3.6.0-py3-none-any.whl (6.8 kB)
  Downloading flake8_comprehensions-3.5.0-py3-none-any.whl (6.4 kB)
  Downloading flake8_comprehensions-3.4.0-py3-none-any.whl (6.4 kB)
  Downloading flake8_comprehensions-3.3.1-py3-none-any.whl (7.0 kB)
  Downloading flake8_comprehensions-3.3.0-py3-none-any.whl (7.2 kB)
  Downloading flake8_comprehensions-3.2.3-py3-none-any.whl (6.8 kB)
  Downloading flake8_comprehensions-3.2.2-py3-none-any.whl (8.2 kB)
  Downloading flake8_comprehensions-3.2.1-py3-none-any.whl (8.2 kB)
  Downloading flake8_comprehensions-3.2.0-py3-none-any.whl (8.2 kB)
  Downloading flake8_comprehensions-3.1.4-py3-none-any.whl (7.9 kB)
  Downloading flake8_comprehensions-3.1.3-py3-none-any.whl (8.0 kB)
  Downloading flake8_comprehensions-3.1.2-py3-none-any.whl (8.0 kB)
  Downloading flake8_comprehensions-3.1.1-py3-none-any.whl (7.9 kB)
  Downloading flake8_comprehensions-3.1.0-py3-none-any.whl (7.9 kB)
  Downloading flake8_comprehensions-3.0.1-py3-none-any.whl (6.3 kB)
  Downloading flake8_comprehensions-3.0.0-py3-none-any.whl (6.3 kB)
  Downloading flake8_comprehensions-2.3.0-py3-none-any.whl (6.3 kB)
Collecting cached-property<2.0.0,>=1.0.0
  Downloading cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting flake8-comprehensions
  Downloading flake8_comprehensions-2.2.0-py3-none-any.whl (5.8 kB)
  Downloading flake8_comprehensions-2.1.0-py3-none-any.whl (5.6 kB)
  Downloading flake8_comprehensions-2.0.0-py3-none-any.whl (5.5 kB)
INFO: pip is looking at multiple versions of flake8-comprehensions to determine which version is compatible with other requirements. This could take a while.
  Downloading flake8_comprehensions-1.4.1-py2.py3-none-any.whl (7.9 kB)
  Downloading flake8_comprehensions-1.4.0-py2.py3-none-any.whl (7.7 kB)
  Downloading flake8_comprehensions-1.3.0-py2.py3-none-any.whl (6.6 kB)
  Downloading flake8_comprehensions-1.2.1-py2.py3-none-any.whl (5.8 kB)
  Downloading flake8_comprehensions-1.2.0-py2.py3-none-any.whl (5.6 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading flake8_comprehensions-1.1.1-py2.py3-none-any.whl (5.2 kB)
  Downloading flake8_comprehensions-1.1.0-py2.py3-none-any.whl (5.2 kB)
  Downloading flake8_comprehensions-1.0.0-py2.py3-none-any.whl (4.7 kB)
INFO: pip is looking at multiple versions of flake8-builtins to determine which version is compatible with other requirements. This could take a while.
Collecting flake8-builtins
  Downloading flake8_builtins-2.0.0-py3-none-any.whl (13 kB)
  Downloading flake8_builtins-1.5.3-py2.py3-none-any.whl (12 kB)
  Downloading flake8_builtins-1.5.2-py2.py3-none-any.whl (13 kB)
  Downloading flake8_builtins-1.5.1-py2.py3-none-any.whl (13 kB)
  Downloading flake8_builtins-1.5.0-py2.py3-none-any.whl (13 kB)
  Downloading flake8_builtins-1.4.2-py2.py3-none-any.whl (13 kB)
  Downloading flake8_builtins-1.4.1-py2.py3-none-any.whl (8.9 kB)
INFO: pip is looking at multiple versions of flake8-builtins to determine which version is compatible with other requirements. This could take a while.
  Downloading flake8_builtins-1.4.0-py2.py3-none-any.whl (8.8 kB)
  Downloading flake8_builtins-1.3.1-py2.py3-none-any.whl (8.5 kB)
  Downloading flake8_builtins-1.3.0-py2.py3-none-any.whl (5.4 kB)
  Downloading flake8_builtins-1.2.3-py2.py3-none-any.whl (8.3 kB)
  Downloading flake8_builtins-1.2.2-py2.py3-none-any.whl (8.1 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading flake8_builtins-1.2.1-py2.py3-none-any.whl (8.1 kB)
  Downloading flake8_builtins-1.2-py2.py3-none-any.whl (8.0 kB)
  Downloading flake8_builtins-1.1.1-py2.py3-none-any.whl (7.2 kB)
  Downloading flake8_builtins-1.1.0-py2.py3-none-any.whl (7.0 kB)
  Downloading flake8_builtins-1.0.post0-py2.py3-none-any.whl (6.8 kB)
  Downloading flake8_builtins-1.0-py2.py3-none-any.whl (6.6 kB)
  Downloading flake8_builtins-0.4-py2.py3-none-any.whl (6.3 kB)
  Downloading flake8_builtins-0.3.1.post0-py2.py3-none-any.whl (6.2 kB)
  Downloading flake8-builtins-0.3.1.tar.gz (15 kB)
  Preparing metadata (setup.py) ... done
  Downloading flake8-builtins-0.3.tar.gz (15 kB)
  Preparing metadata (setup.py) ... done
  Downloading flake8-builtins-0.2.tar.gz (15 kB)
  Preparing metadata (setup.py) ... done
  Downloading flake8-builtins-0.1.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of flake8-bugbear to determine which version is compatible with other requirements. This could take a while.
Collecting flake8-bugbear
  Downloading flake8_bugbear-22.10.27-py3-none-any.whl (23 kB)
  Downloading flake8_bugbear-22.10.25-py3-none-any.whl (22 kB)
  Downloading flake8_bugbear-22.9.23-py3-none-any.whl (22 kB)
  Downloading flake8_bugbear-22.9.11-py3-none-any.whl (21 kB)
...
```

note also `- l` looks like a typo -- you probably don't mean to install https://pypi.org/p/l I would imagine

**Comment by acdha** [comment]
Oh, yes, that’s flake8-asserts in my actual file. 

The main thing I was thinking is that it’d be useful to have pre-commit show something useful in this situation so it’s more obvious than all of our CI jobs hanging.

**Comment by asottile** [comment]
pre-commit tells you what environment is installing -- that should be enough for you to debug and figure out what's wrong right?  I don't want to add noise to the output
