### ISSUE TITLE
pre-commit tries to install the wrong version of flake8

### ISSUE THREAD

**Issue by danhje** [pre-commit/pre-commit#2676]
### search you tried in the issue tracker

wrong version, "Using cached"

### describe your issue

```
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - pyflakes
          - pycodestyle
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-mutable
          - flake8-simplify
          - flake8-builtins
```

Fails with 

```
    The conflict is caused by:
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.7.0 depends on flake8!=3.2.0, <5 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.6.1 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.6.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.5.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.4.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.3.1 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.3.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.2.3 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.2.2 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.2.1 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.2.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.1.4 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.1.3 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.1.2 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.1.1 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.1.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.0.1 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.0.0 depends on flake8!=3.2.0, <4 and >=3.0
    
    To fix this you could try to:
    1. loosen the range of package versions you've specified
    2. remove package versions to allow pip attempt to solve the dependency conflict
    
    
stderr:
    ERROR: Cannot install flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic), flake8-bugbear==16.4.2, flake8-comprehensions==3.0.0, flake8-comprehensions==3.0.1, flake8-comprehensions==3.1.0, flake8-comprehensions==3.1.1, flake8-comprehensions==3.1.2, flake8-comprehensions==3.1.3, flake8-comprehensions==3.1.4, flake8-comprehensions==3.2.0, flake8-comprehensions==3.2.1, flake8-comprehensions==3.2.2, flake8-comprehensions==3.2.3, flake8-comprehensions==3.3.0, flake8-comprehensions==3.3.1, flake8-comprehensions==3.4.0, flake8-comprehensions==3.5.0, flake8-comprehensions==3.6.0, flake8-comprehensions==3.6.1 and flake8-comprehensions==3.7.0 because these package versions have conflicting dependencies.
    ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

So it's trying to install 6.0.0 even though I've asked for 5.0.4. I'd previously specified flake8 6.0.0. I've tried deleting ~/.cache/pre-commit.

### pre-commit --version

2.21.0

### .pre-commit-config.yaml

```yaml
---
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
      - id: pycln
        args: [--all]
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - pyflakes
          - pycodestyle
          - flake8-bugbear
          - flake8-comprehensions=3.10.1
          - flake8-eradicate
          - flake8-mutable
          - flake8-simplify
          - flake8-builtins
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [-ll, -ii, --exclude, ./.venv/*, --recursive, .]
        pass_filenames: false
        always_run: true
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
Traceback (most recent call last):
  File "/home/danielhj/.cache/pypoetry/virtualenvs/my-project-pn2qB-Tr-py3.10/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/danielhj/.cache/pypoetry/virtualenvs/my-project-pn2qB-Tr-py3.10/lib/python3.10/site-packages/pre_commit/main.py", line 394, in main
    return run(args.config, store, args)
  File "/home/danielhj/.cache/pypoetry/virtualenvs/my-project-pn2qB-Tr-py3.10/lib/python3.10/site-packages/pre_commit/commands/run.py", line 428, in run
    install_hook_envs(to_install, store)
  File "/home/danielhj/.cache/pypoetry/virtualenvs/my-project-pn2qB-Tr-py3.10/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/home/danielhj/.cache/pypoetry/virtualenvs/my-project-pn2qB-Tr-py3.10/lib/python3.10/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/home/danielhj/.cache/pypoetry/virtualenvs/my-project-pn2qB-Tr-py3.10/lib/python3.10/site-packages/pre_commit/languages/python.py", line 221, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/home/danielhj/.cache/pypoetry/virtualenvs/my-project-pn2qB-Tr-py3.10/lib/python3.10/site-packages/pre_commit/languages/helpers.py", line 48, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/danielhj/.cache/pypoetry/virtualenvs/my-project-pn2qB-Tr-py3.10/lib/python3.10/site-packages/pre_commit/util.py", line 143, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/danielhj/.cache/pre-commit/repo4sy1mdic/py_env-python3/bin/python', '-mpip', 'install', '.', 'pyflakes', 'pycodestyle', 'flake8-bugbear', 'flake8-comprehensions', 'flake8-eradicate', 'flake8-mutable', 'flake8-simplify', 'flake8-builtins')
return code: 1
stdout:
    Processing /home/danielhj/.cache/pre-commit/repo4sy1mdic
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting pyflakes
      Using cached pyflakes-3.0.1-py2.py3-none-any.whl (62 kB)
    Collecting pycodestyle
      Using cached pycodestyle-2.10.0-py2.py3-none-any.whl (41 kB)
    Collecting flake8-bugbear
      Using cached flake8_bugbear-22.12.6-py3-none-any.whl (23 kB)
    Collecting flake8-comprehensions
      Using cached flake8_comprehensions-3.10.1-py3-none-any.whl (7.3 kB)
    Collecting flake8-eradicate
      Using cached flake8_eradicate-1.4.0-py3-none-any.whl (5.2 kB)
    Collecting flake8-mutable
      Using cached flake8_mutable-1.2.0-py3-none-any.whl
    Collecting flake8-simplify
      Using cached flake8_simplify-0.19.3-py3-none-any.whl (26 kB)
    Collecting flake8-builtins
      Using cached flake8_builtins-2.1.0-py3-none-any.whl (13 kB)
    Collecting mccabe<0.8.0,>=0.7.0
      Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
    Collecting attrs>=19.2.0
      Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
    Collecting flake8-eradicate
      Using cached flake8_eradicate-1.3.0-py3-none-any.whl (5.1 kB)
      Using cached flake8_eradicate-1.2.1-py3-none-any.whl (5.1 kB)
    Collecting eradicate<3.0,>=2.0
      Using cached eradicate-2.1.0-py3-none-any.whl (6.9 kB)
    Collecting flake8-eradicate
      Using cached flake8_eradicate-1.2.0-py3-none-any.whl (5.1 kB)
      Using cached flake8_eradicate-1.1.0-py3-none-any.whl (5.1 kB)
      Using cached flake8_eradicate-1.0.0-py3-none-any.whl (5.0 kB)
      Using cached flake8_eradicate-0.4.0-py3-none-any.whl (4.7 kB)
      Using cached flake8_eradicate-0.3.0-py3-none-any.whl (4.7 kB)
      Using cached flake8_eradicate-0.2.4-py3-none-any.whl (4.7 kB)
      Using cached flake8_eradicate-0.2.3-py3-none-any.whl (6.2 kB)
      Using cached flake8_eradicate-0.2.2-py3-none-any.whl (6.3 kB)
      Using cached flake8_eradicate-0.2.1-py3-none-any.whl (6.4 kB)
      Using cached flake8_eradicate-0.2.0-py3-none-any.whl (6.6 kB)
      Using cached flake8_eradicate-0.1.1-py3-none-any.whl (5.6 kB)
    Collecting eradicate<0.3.0,>=0.2.1
      Using cached eradicate-0.2.1.tar.gz (4.4 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting flake8-eradicate
      Using cached flake8_eradicate-0.1.0-py3-none-any.whl (5.3 kB)
    INFO: pip is looking at multiple versions of flake8-comprehensions to determine which version is compatible with other requirements. This could take a while.
    Collecting flake8-comprehensions
      Using cached flake8_comprehensions-3.10.0-py3-none-any.whl (7.3 kB)
      Using cached flake8_comprehensions-3.9.0-py3-none-any.whl (6.6 kB)
      Using cached flake8_comprehensions-3.8.0-py3-none-any.whl (6.6 kB)
      Using cached flake8_comprehensions-3.7.0-py3-none-any.whl (6.7 kB)
      Using cached flake8_comprehensions-3.6.1-py3-none-any.whl (6.7 kB)
      Using cached flake8_comprehensions-3.6.0-py3-none-any.whl (6.8 kB)
      Using cached flake8_comprehensions-3.5.0-py3-none-any.whl (6.4 kB)
      Using cached flake8_comprehensions-3.4.0-py3-none-any.whl (6.4 kB)
      Using cached flake8_comprehensions-3.3.1-py3-none-any.whl (7.0 kB)
      Using cached flake8_comprehensions-3.3.0-py3-none-any.whl (7.2 kB)
      Using cached flake8_comprehensions-3.2.3-py3-none-any.whl (6.8 kB)
      Using cached flake8_comprehensions-3.2.2-py3-none-any.whl (8.2 kB)
      Using cached flake8_comprehensions-3.2.1-py3-none-any.whl (8.2 kB)
      Using cached flake8_comprehensions-3.2.0-py3-none-any.whl (8.2 kB)
      Using cached flake8_comprehensions-3.1.4-py3-none-any.whl (7.9 kB)
      Using cached flake8_comprehensions-3.1.3-py3-none-any.whl (8.0 kB)
      Using cached flake8_comprehensions-3.1.2-py3-none-any.whl (8.0 kB)
      Using cached flake8_comprehensions-3.1.1-py3-none-any.whl (7.9 kB)
      Using cached flake8_comprehensions-3.1.0-py3-none-any.whl (7.9 kB)
      Using cached flake8_comprehensions-3.0.1-py3-none-any.whl (6.3 kB)
      Using cached flake8_comprehensions-3.0.0-py3-none-any.whl (6.3 kB)
      Using cached flake8_comprehensions-2.3.0-py3-none-any.whl (6.3 kB)
    Collecting cached-property<2.0.0,>=1.0.0
      Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
    Collecting flake8-comprehensions
      Using cached flake8_comprehensions-2.2.0-py3-none-any.whl (5.8 kB)
      Using cached flake8_comprehensions-2.1.0-py3-none-any.whl (5.6 kB)
      Using cached flake8_comprehensions-2.0.0-py3-none-any.whl (5.5 kB)
    INFO: pip is looking at multiple versions of flake8-comprehensions to determine which version is compatible with other requirements. This could take a while.
      Using cached flake8_comprehensions-1.4.1-py2.py3-none-any.whl (7.9 kB)
      Using cached flake8_comprehensions-1.4.0-py2.py3-none-any.whl (7.7 kB)
      Using cached flake8_comprehensions-1.3.0-py2.py3-none-any.whl (6.6 kB)
      Using cached flake8_comprehensions-1.2.1-py2.py3-none-any.whl (5.8 kB)
      Using cached flake8_comprehensions-1.2.0-py2.py3-none-any.whl (5.6 kB)
    INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
      Using cached flake8_comprehensions-1.1.1-py2.py3-none-any.whl (5.2 kB)
      Using cached flake8_comprehensions-1.1.0-py2.py3-none-any.whl (5.2 kB)
      Using cached flake8_comprehensions-1.0.0-py2.py3-none-any.whl (4.7 kB)
    INFO: pip is looking at multiple versions of flake8-bugbear to determine which version is compatible with other requirements. This could take a while.
    Collecting flake8-bugbear
      Using cached flake8_bugbear-22.10.27-py3-none-any.whl (23 kB)
      Using cached flake8_bugbear-22.10.25-py3-none-any.whl (22 kB)
      Using cached flake8_bugbear-22.9.23-py3-none-any.whl (22 kB)
      Using cached flake8_bugbear-22.9.11-py3-none-any.whl (21 kB)
      Using cached flake8_bugbear-22.8.23-py3-none-any.whl (21 kB)
      Using cached flake8_bugbear-22.7.1-py3-none-any.whl (21 kB)
      Using cached flake8_bugbear-22.6.22-py3-none-any.whl (19 kB)
    INFO: pip is looking at multiple versions of flake8-bugbear to determine which version is compatible with other requirements. This could take a while.
      Using cached flake8_bugbear-22.4.25-py3-none-any.whl (19 kB)
      Using cached flake8_bugbear-22.3.23-py3-none-any.whl (19 kB)
      Using cached flake8_bugbear-22.3.20-py3-none-any.whl (19 kB)
      Using cached flake8_bugbear-22.1.11-py3-none-any.whl (18 kB)
      Using cached flake8_bugbear-21.11.29-py36.py37.py38-none-any.whl (17 kB)
    INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
      Using cached flake8_bugbear-21.9.2-py36.py37.py38-none-any.whl (16 kB)
      Using cached flake8_bugbear-21.9.1-py36.py37.py38-none-any.whl (16 kB)
      Using cached flake8_bugbear-21.4.3-py36.py37.py38-none-any.whl (17 kB)
      Using cached flake8_bugbear-21.4.2-py36.py37.py38-none-any.whl (17 kB)
      Using cached flake8_bugbear-21.4.1-py36.py37.py38-none-any.whl (17 kB)
      Using cached flake8_bugbear-21.3.2-py36.py37.py38-none-any.whl (16 kB)
      Using cached flake8_bugbear-21.3.1-py36.py37.py38-none-any.whl (16 kB)
      Using cached flake8_bugbear-20.11.1-py36.py37.py38-none-any.whl (16 kB)
      Using cached flake8_bugbear-20.1.4-py36.py37.py38-none-any.whl (15 kB)
      Using cached flake8_bugbear-20.1.3-py36.py37.py38-none-any.whl (15 kB)
      Using cached flake8_bugbear-20.1.2-py36.py37.py38-none-any.whl (15 kB)
      Using cached flake8_bugbear-20.1.1-py36.py37.py38-none-any.whl (15 kB)
      Using cached flake8_bugbear-20.1.0-py36.py37.py38-none-any.whl (14 kB)
      Using cached flake8_bugbear-19.8.0-py35.py36.py37-none-any.whl (14 kB)
      Using cached flake8_bugbear-19.3.0-py35.py36.py37-none-any.whl (13 kB)
      Using cached flake8_bugbear-18.8.0-py35.py36.py37-none-any.whl (13 kB)
      Using cached flake8_bugbear-18.2.0-py35.py36-none-any.whl (18 kB)
      Using cached flake8_bugbear-17.12.0-py35.py36-none-any.whl (18 kB)
      Using cached flake8_bugbear-17.4.0-py35.py36-none-any.whl (17 kB)
      Using cached flake8_bugbear-17.3.0-py35.py36-none-any.whl (17 kB)
      Using cached flake8_bugbear-17.2.0-py35.py36-none-any.whl (16 kB)
      Using cached flake8_bugbear-16.12.2-py35.py36-none-any.whl (15 kB)
      Using cached flake8_bugbear-16.12.1-py35.py36-none-any.whl (14 kB)
      Using cached flake8_bugbear-16.12.0-py35.py36-none-any.whl (14 kB)
      Using cached flake8-bugbear-16.11.1.tar.gz (11 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
      Using cached flake8-bugbear-16.11.0.tar.gz (9.7 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
      Using cached flake8-bugbear-16.10.1.tar.gz (9.7 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
      Using cached flake8-bugbear-16.10.0.tar.gz (9.6 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
      Using cached flake8-bugbear-16.9.0.tar.gz (7.8 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
      Using cached flake8-bugbear-16.7.1.tar.gz (7.5 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
      Using cached flake8-bugbear-16.7.0.tar.gz (7.3 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
      Using cached flake8-bugbear-16.6.1.tar.gz (7.1 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
      Using cached flake8-bugbear-16.6.0.tar.gz (6.9 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
      Using cached flake8-bugbear-16.4.2.tar.gz (4.7 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    INFO: pip is looking at multiple versions of pycodestyle to determine which version is compatible with other requirements. This could take a while.
    INFO: pip is looking at multiple versions of pyflakes to determine which version is compatible with other requirements. This could take a while.
    Collecting pyflakes
      Using cached pyflakes-3.0.0-py2.py3-none-any.whl (62 kB)
    INFO: pip is looking at multiple versions of pycodestyle to determine which version is compatible with other requirements. This could take a while.
    INFO: pip is looking at multiple versions of pyflakes to determine which version is compatible with other requirements. This could take a while.
    INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
    INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
    INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
    INFO: pip is looking at multiple versions of flake8 to determine which version is compatible with other requirements. This could take a while.
    
    The conflict is caused by:
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.7.0 depends on flake8!=3.2.0, <5 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.6.1 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.6.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.5.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.4.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.3.1 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.3.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.2.3 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.2.2 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.2.1 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.2.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.1.4 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.1.3 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.1.2 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.1.1 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.1.0 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.0.1 depends on flake8!=3.2.0, <4 and >=3.0
        The user requested flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic)
        flake8-bugbear 16.4.2 depends on flake8
        flake8-comprehensions 3.0.0 depends on flake8!=3.2.0, <4 and >=3.0
    
    To fix this you could try to:
    1. loosen the range of package versions you've specified
    2. remove package versions to allow pip attempt to solve the dependency conflict
    
    
stderr:
    ERROR: Cannot install flake8 6.0.0 (from /home/danielhj/.cache/pre-commit/repo4sy1mdic), flake8-bugbear==16.4.2, flake8-comprehensions==3.0.0, flake8-comprehensions==3.0.1, flake8-comprehensions==3.1.0, flake8-comprehensions==3.1.1, flake8-comprehensions==3.1.2, flake8-comprehensions==3.1.3, flake8-comprehensions==3.1.4, flake8-comprehensions==3.2.0, flake8-comprehensions==3.2.1, flake8-comprehensions==3.2.2, flake8-comprehensions==3.2.3, flake8-comprehensions==3.3.0, flake8-comprehensions==3.3.1, flake8-comprehensions==3.4.0, flake8-comprehensions==3.5.0, flake8-comprehensions==3.6.0, flake8-comprehensions==3.6.1 and flake8-comprehensions==3.7.0 because these package versions have conflicting dependencies.
    ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by asottile** [comment]
I can't reproduce -- that output is only possible from `rev: 6.0.0`

**Comment by asottile** [comment]
also your log file is doctored -- please paste the actual contents and not your edited version

**Comment by asottile** [comment]
and your config is doctored too, `flake8-comprehensions=3.10.1` is invalid syntax

please don't waste my time

**Comment by danhje** [comment]
> please don't waste my time

That's not very nice. I made a mistake and pasted a version of .pre-commit-confit where I was trying something I saw somewhere (pinning the version of flake8-comprehensions). My mistake. I've corrected that. The log is pasted without modification.

**Comment by asottile** [comment]
> The log is pasted without modification.

I guarantee it's not -- the log contains a bunch of information at the top

**Comment by asottile** [comment]
start over, try again -- and show the exact contents of the config file you're using, the output you see, and the contents of the log file
