### ISSUE TITLE
When i try to add gitleaks

### ISSUE THREAD

**Issue by 88srzh** [pre-commit/pre-commit#2683]
### search you tried in the issue tracker

gitleaks

### describe your issue

when i try to add gitleaks to .pre-commit-config.yaml in project:

>   - repo: https://github.com/zricethezav/gitleaks
>     rev: v8.12.0
>     hooks:
>       - id: gitleaks 
>         name: Detect hardcoded secrets
>         description: Detect hardcoded secrets using Gitleaks
>         entry: gitleaks protect --verbose --redact --staged
>         language: dart
>         pass_filenames: false

 i get an error:

> An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/home/srzh/.cache/pre-commit/repobleewbf2/pubspec.yaml'

### pre-commit --version

2.21.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.31.0"
    hooks:
      - id: eslint
        files: \.dart
        types: [file]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.3.1"
    hooks:
      - id: remove-crlf
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: "0.0.2"
    hooks:
      - id: stylelint
        additional_dependencies:
          ["stylelint@13.2.1", "stylelint-config-standard@20.0.0"]
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.2"
    hooks:
      - id: codespell
        files: ^.*\.(py|c|h|md|rst|yml|dart)$
        args: ["--ignore-words-list"]
  - repo: https://github.com/Cretezy/flutter-format-pre-commit
    rev: "4a1df675bb74dea371c17934933e257e46f8dd98"
    hooks:
      - id: flutter-format
        files: lib/*
        exclude: lib/src/avatar.dart
  - repo: https://github.com/Cretezy/dart-format-pre-commit
    rev: "fa83c73f40014f9e268bd0e62374eaa581fe3540"
    hooks:
      - id: dart-format
        files: lib/*
        exclude: lib/src/utils.dart
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "0bfdb7415bb2d02794a884bf2b763a92772001eb"
    hooks:
      - id: flutter-analyze
  - repo: https://github.com/fluttercommunity/import_sorter
    rev: "f350497a11b1285c695595049e95a420068e7a9f"
    hooks:
      - id: dart-import-sorter
      - id: flutter-import-sorter
  - repo: https://github.com/guid-empty/flutter-dependency-validation-pre-commit
    rev: "4663b743f807eaa0ee1309016f5a6d20b9bb1b13"
    hooks:
      - id: flutter-dependency-validation
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.12.0
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        entry: gitleaks protect --verbose --redact --staged
        language: dart
        pass_filenames: false
```

### version information

```
pre-commit version: 2.21.0
git --version: git version 2.34.1
sys.version:
    3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/home/srzh/.cache/pre-commit/repobleewbf2/pubspec.yaml'
```

```
Traceback (most recent call last):
  File "/home/srzh/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/srzh/.local/lib/python3.10/site-packages/pre_commit/main.py", line 366, in main
    return hook_impl(
  File "/home/srzh/.local/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 254, in hook_impl
    return retv | run(config, store, ns)
  File "/home/srzh/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 428, in run
    install_hook_envs(to_install, store)
  File "/home/srzh/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/home/srzh/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/home/srzh/.local/lib/python3.10/site-packages/pre_commit/languages/dart.py", line 74, in install_environment
    _install_dir(prefix, tmp)
  File "/home/srzh/.local/lib/python3.10/site-packages/pre_commit/languages/dart.py", line 54, in _install_dir
    with open(prefix_p.path('pubspec.yaml')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/srzh/.cache/pre-commit/repobleewbf2/pubspec.yaml'
```

**Comment by asottile** [comment]
where did you copy paste that configuration from? it's completely wrong

**Comment by 88srzh** [comment]
https://github.com/zricethezav/gitleaks/blob/master/.pre-commit-hooks.yaml

**Comment by asottile** [comment]
(1) that's not the same as what you have (and would have worked, but would have been unnecessary -- you changed it after copy pasting it *breaking it*) and (2) that's not how pre-commit works -- you didn't do that for any of your other configurations so why this one? (3) the gitleaks readme shows you the right thing why didn't you do that?

**Comment by 88srzh** [comment]
if i do:
```
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.12.0
    hooks:
      - id: gitleaks
```
i have error:
```
[INFO] Installing environment for https://github.com/zricethezav/gitleaks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('go', 'install', './...')
return code: 1
stdout:
    Executable `go` not found
stderr: (none)
```

**Comment by asottile** [comment]
go is currently a 2nd class language requiring the language to be installed to use tools written in it

**Comment by 88srzh** [comment]
can i use this tool with dart?

**Comment by asottile** [comment]
yes, gitleaks works for any programming language but it is implemented in go

**Comment by 88srzh** [comment]
thx your answer very fast

**Comment by maxschulz-COL** [comment]
@asottile hey! I am also trying to do this but I have a similar problem. Am I correct in saying that in order to use gitleaks as a pre-commit hook I need either:
- `go` installed
- a working docker setup

both fail for me if I do not set them up explicitly.

The reason I am struggling is that I would like this to work out-of-the box for my team. Any hints/experience on how this could be achieved?
