### ISSUE TITLE
Unstaged changes lost after CTRL+C spam

### ISSUE THREAD

**Issue by Gracecr** [pre-commit/pre-commit#2694]
### search you tried in the issue tracker

Interrupt

### describe your issue

I was running `git commit --amend --no-edit` to modify my last commit got a small change. I realized I made a mistake and pressed CTRL+C a bunch of times. Perhaps I should cut back on the caffeine.

I was met with a large error message:

<details>
  <summary>Error Log</summary>

  ```
  C:\[REDACTED]\work\[REDACTED]\client\python>git commit --amend --no-edit
  [WARNING] Unstaged files detected.
  [INFO] Stashing unstaged files to C:\[REDACTED]\.cache\pre-commit\patch1673551180-19704.

  C:\[REDACTED]\work\[REDACTED]\client\python>Traceback (most recent call last):
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\staged_files_only.py", line 71, in _unstaged_changes_cleared
      cmd_output_b(*_CHECKOUT_CMD, env=no_checkout_env)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\util.py", line 139, in cmd_output_b
      stdout_b, stderr_b = proc.communicate()
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\subprocess.py", line 1152, in communicate
      stdout, stderr = self._communicate(input, endtime, timeout)
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\subprocess.py", line 1526, in _communicate
      self.stdout_thread.join(self._remaining_time(endtime))
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\threading.py", line 1096, in join
      self._wait_for_tstate_lock()
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\threading.py", line 1116, in _wait_for_tstate_lock
      if lock.acquire(block, timeout):
  KeyboardInterrupt

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\staged_files_only.py", line 28, in _git_apply
      cmd_output_b('git', *args)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\util.py", line 143, in cmd_output_b
      raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
  pre_commit.util.CalledProcessError: command: ('C:/Users/[REDACTED]/AppData/Local/Programs/Git/mingw64/libexec/git-core\\git.EXE', 'apply', '--whitespace=nowarn', 'C:\\Users\\[REDACTED]\\.cache\\pre-commit\\patch1673551180-19704')
  return code: 1
  stdout: (none)
  stderr:
      error: patch failed: [REDACTED]:1
      error: [REDACTED]: patch does not apply
      error: patch failed: [REDACTED]:421
      error: [REDACTED]: patch does not apply


  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\staged_files_only.py", line 76, in _unstaged_changes_cleared
      _git_apply(patch_filename)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\staged_files_only.py", line 31, in _git_apply
      cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\util.py", line 143, in cmd_output_b
      raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
  pre_commit.util.CalledProcessError: command: ('C:/Users/[REDACTED]/AppData/Local/Programs/Git/mingw64/libexec/git-core\\git.EXE', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', 'C:\\Users\\[REDACTED]\\.cache\\pre-commit\\patch1673551180-19704')
  return code: 1
  stdout: (none)
  stderr:
      error: patch failed: [REDACTED]:1
      error: [REDACTED]: patch does not apply
      error: patch failed: [REDACTED]:421
      error: [REDACTED]: patch does not apply


  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
      yield
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\main.py", line 366, in main
      return hook_impl(
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\commands\hook_impl.py", line 254, in hook_impl
      return retv | run(config, store, ns)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\commands\run.py", line 406, in run
      exit_stack.enter_context(staged_files_only(store.directory))
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\contextlib.py", line 492, in enter_context
      result = _cm_type.__enter__(cm)
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\contextlib.py", line 135, in __enter__
      return next(self.gen)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\staged_files_only.py", line 100, in staged_files_only
      with _intent_to_add_cleared(), _unstaged_changes_cleared(patch_dir):
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\contextlib.py", line 135, in __enter__
      return next(self.gen)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\staged_files_only.py", line 78, in _unstaged_changes_cleared
      logger.warning(
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\logging\__init__.py", line 1489, in warning
      self._log(WARNING, msg, args, **kwargs)
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\logging\__init__.py", line 1624, in _log
      self.handle(record)
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\logging\__init__.py", line 1634, in handle
      self.callHandlers(record)
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\logging\__init__.py", line 1696, in callHandlers
      hdlr.handle(record)
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\logging\__init__.py", line 968, in handle
      self.emit(record)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\logging_handler.py", line 31, in emit
      output.write_line(f'{level_msg} {record.getMessage()}')
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\output.py", line 33, in write_line
      write_line_b(s.encode() if s is not None else s, **kwargs)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\output.py", line 29, in write_line_b
      output_stream.flush()
  OSError: [Errno 22] Invalid argument

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\__main__.py", line 7, in <module>
      raise SystemExit(main())
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\main.py", line 345, in main
      with error_handler(), logging_handler(args.color):
    File "C:\[REDACTED]\.pyenv\pyenv-win\versions\3.10.5\lib\contextlib.py", line 153, in __exit__
      self.gen.throw(typ, value, traceback)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\error_handler.py", line 81, in error_handler
      _log_and_exit(msg, ret_code, e, traceback.format_exc())
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\error_handler.py", line 26, in _log_and_exit
      output.write_line_b(error_msg)
    File "C:\[REDACTED]\AppData\Local\hatch\env\virtual\[REDACTED]\ecbG0Wzl\[REDACTED]\lib\site-packages\pre_commit\output.py", line 29, in write_line_b
      output_stream.flush()
  OSError: [Errno 22] Invalid argument
  Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
  OSError: [Errno 22] Invalid argument
  ```
</details>

Not realizing that my unstaged changes were not restored, I made my change and successfully ran `git commit --amend --no-edit`.

I tried to restore the changes with `git stash apply`, but nothing was stashed.

I tried to restore the changes with the patch mention in the error log: `git stash apply patch1673551180-19704`. This contained a few changes, but most are still missing.

I don't see anything in `git reflog` that indicates where my changes may be stored.

Apologies for the paranoid redacting. If it's a problem, I can tone it down a bit. Any help would be appreciated.

### pre-commit --version

pre-commit 2.21.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
        exclude: ^mrsi_client/messages/__init__.py
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=client/python/pyproject.toml",
          ]
        exclude: |
          (?x)(
              ^client/python/tools/|
              ^client/python/tests/|
              ^client/python/[REDACTED]/messages/__init__.py|
              ^client/python/examples/
          )
```

**Comment by asottile** [comment]
please read the first line of your output -- the changes are never completely lost

**Comment by asottile** [comment]
(fwiw you're looking for `git apply`, not `git stash`)

**Comment by Gracecr** [comment]
Man you are fast!

I had a syntax error when I first posted this so half my message wasn't showing. If you don't mind refreshing and looking again, I'd appreciate it.

**Comment by asottile** [comment]
my answer is still the same -- this line shows where your changes are stored: `[INFO] Stashing unstaged files to C:\[REDACTED]\.cache\pre-commit\patch1673551180-19704.`

**Comment by Gracecr** [comment]
OK yeah you're totally right. If I had just opened the patch up in an editor I would have seen that all my changes are there.

The patch was failing to apply because I had already changed those files, so I needed `git apply --reject`. I only saw the errors and assumed that's all that was in the file.

Thanks a ton for the incredibly prompt and accurate response.
