### ISSUE TITLE
pre-commit and PYTHONHOME

### ISSUE THREAD

**Issue by dkoguciuk** [pre-commit/pre-commit#2714]
### search you tried in the issue tracker

pythonhome, pythonpath

### describe your issue

Hello,

I have this rare case when I have to use PYTHONHOME, but I've seen that you have hardcoded unsettling of PYTHONHOME env var, i.e. here:

https://github.com/pre-commit/pre-commit/blob/59ed51a309565dd999ea0af8cc1f0cecf1a9f04a/pre_commit/languages/python.py#L55-L61

Can I ask what the reason behind it? Do you know any way I can bypass it?

Best,
Daniel

### pre-commit --version

2.21.0

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    args: ['--maxkb=10000']
  - id: check-merge-conflict
  - id: check-json
```

### ~/.cache/pre-commit/pre-commit.log (if present)

root@49fd277cec0c:~/oa_dle# cat ~/.cache/pre-commit/pre-commit.log
### version information

```
pre-commit version: 2.21.0
git --version: git version 2.25.1
sys.version:
    3.9.5 (default, Nov 23 2021, 15:27:38) 
    [GCC 9.3.0]
sys.executable: /oa_venv/bin/python3.9
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/root/.cache/pre-commit/repogipb_rj8/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
stdout: (none)
stderr:
    Could not find platform independent libraries <prefix>
    Could not find platform dependent libraries <exec_prefix>
    Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
    Python path configuration:
      PYTHONHOME = (not set)
      PYTHONPATH = '/oa_venv/lib/python3.9/site-packages'
      program name = '/root/.cache/pre-commit/repogipb_rj8/py_env-python3.9/bin/python'
      isolated = 0
      environment = 1
      user site = 1
      import site = 1
      sys._base_executable = '/root/.cache/pre-commit/repogipb_rj8/py_env-python3.9/bin/python'
      sys.base_prefix = '/usr'
      sys.base_exec_prefix = '/usr'
      sys.platlibdir = 'lib'
      sys.executable = '/root/.cache/pre-commit/repogipb_rj8/py_env-python3.9/bin/python'
      sys.prefix = '/usr'
      sys.exec_prefix = '/usr'
      sys.path = [
        '/oa_venv/lib/python3.9/site-packages',
        '/usr/lib/python39.zip',
        '/usr/lib/python3.9',
        '/usr/lib/lib-dynload',
      ]
    Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
    Python runtime state: core initialized
    ModuleNotFoundError: No module named 'encodings'
    
    Current thread 0x00007f94fa8c9740 (most recent call first):
    <no Python frame>
    
```

```
Traceback (most recent call last):
  File "/oa_venv/lib/python3.9/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/oa_venv/lib/python3.9/site-packages/pre_commit/main.py", line 394, in main
    return run(args.config, store, args)
  File "/oa_venv/lib/python3.9/site-packages/pre_commit/commands/run.py", line 428, in run
    install_hook_envs(to_install, store)
  File "/oa_venv/lib/python3.9/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/oa_venv/lib/python3.9/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/oa_venv/lib/python3.9/site-packages/pre_commit/languages/python.py", line 221, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/oa_venv/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 48, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/oa_venv/lib/python3.9/site-packages/pre_commit/util.py", line 143, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/root/.cache/pre-commit/repogipb_rj8/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
stdout: (none)
stderr:
    Could not find platform independent libraries <prefix>
    Could not find platform dependent libraries <exec_prefix>
    Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
    Python path configuration:
      PYTHONHOME = (not set)
      PYTHONPATH = '/oa_venv/lib/python3.9/site-packages'
      program name = '/root/.cache/pre-commit/repogipb_rj8/py_env-python3.9/bin/python'
      isolated = 0
      environment = 1
      user site = 1
      import site = 1
      sys._base_executable = '/root/.cache/pre-commit/repogipb_rj8/py_env-python3.9/bin/python'
      sys.base_prefix = '/usr'
      sys.base_exec_prefix = '/usr'
      sys.platlibdir = 'lib'
      sys.executable = '/root/.cache/pre-commit/repogipb_rj8/py_env-python3.9/bin/python'
      sys.prefix = '/usr'
      sys.exec_prefix = '/usr'
      sys.path = [
        '/oa_venv/lib/python3.9/site-packages',
        '/usr/lib/python39.zip',
        '/usr/lib/python3.9',
        '/usr/lib/lib-dynload',
      ]
    Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
    Python runtime state: core initialized
    ModuleNotFoundError: No module named 'encodings'
    
    Current thread 0x00007f94fa8c9740 (most recent call first):
    <no Python frame>
```

**Comment by asottile** [comment]
https://github.com/pypa/virtualenv/blob/f355ddb90153652fa7952e643eeb8b1a3b7c2e62/src/virtualenv/activation/bash/activate.sh#L57-L61

**Comment by asottile** [comment]
if you "need" `PYTHONHOME` then your python setup is broken. you should work on fixing that -- it looks like you're _attempting_ to use a virtualenv, but my guess is you've not set that up properly (or relocated it after moving machines, etc.).  you're pretty far in unsupported territory in _python_ in general, so fix that first

**Comment by dkoguciuk** [comment]
> if you "need" PYTHONHOME then your python setup is broken

No, my python setup is not broken and this is intended.

> it looks like you're attempting to use a virtualenv

What do you mean? Virtualenv within `pre-commit`? I am not very familiar with the internal working of pre-commit TBH.

_____________________________________________________________________________


Can I ask what the reason behind unsettling PYTHONHOME? Do you know any way I can bypass it?

**Comment by asottile** [comment]
yes, your setup is broken.  `PYTHONHOME` should generally never be used.

if you want enterprise support for your custom, broken python setup please have your company contact me.
