### ISSUE TITLE
Cache directory doesn't work after being moved

### ISSUE THREAD

**Issue by maresb** [pre-commit/pre-commit#2724]
### search you tried in the issue tracker

cache relative

### describe your issue

I tried to do the following for a freshly-created user:

```bash
PRE_COMMIT_HOME=/tmp/pre-commit pre-commit install --install-hooks
mv /tmp/pre-commit ~/.cache/pre-commit
```
(For context I'm trying to pre-build the cache inside a Docker container for a user not yet specified at build-time.)

I was surprised that when I did `pre-commit run` and I got

```
An error has occurred: InvalidManifestError: 
=====> /tmp/pre-commit/repolidaf4aj/.pre-commit-hooks.yaml is not a file
```

The reason for this behavior is clear: the SQLite DB stores the [absolute path of the cached repo](https://github.com/pre-commit/pre-commit/blob/dd8e717ed6022209a2b0cecf5c75460eb60e548e/pre_commit/store.py#L161-L170). I would have expected that only the path relative from `Store.directory` should be recorded.

I could imagine that there may also be other rare situations where the mount path of a user's home is changed and they subsequently lose their pre-commit cache. It seems like storing the relative path would be better. Do you agree?

### pre-commit --version

pre-commit 3.0.1

### .pre-commit-config.yaml

```yaml
# generic example from the docs

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
```

### version information

```
pre-commit version: 3.0.1
git --version: git version 2.30.2
sys.version:
    3.11.1 (main, Jan 23 2023, 21:04:06) [GCC 10.2.1 20210110]
sys.executable: /usr/local/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An error has occurred: InvalidManifestError: 
=====> /tmp/pre-commit/repolidaf4aj/.pre-commit-hooks.yaml is not a file
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/lib/python3.11/site-packages/pre_commit/main.py", line 394, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pre_commit/commands/run.py", line 419, in run
    for hook in all_hooks(config, store)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pre_commit/repository.py", line 243, in all_hooks
    return tuple(
           ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pre_commit/repository.py", line 246, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pre_commit/repository.py", line 221, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pre_commit/repository.py", line 188, in _cloned_repository_hooks
    by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cfgv.py", line 394, in load_from_filename
    with reraise_as(exc_tp):
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "/usr/local/lib/python3.11/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/usr/local/lib/python3.11/site-packages/cfgv.py", line 396, in load_from_filename
    raise ValidationError(f'{filename} is not a file')
pre_commit.clientlib.InvalidManifestError: 
=====> /tmp/pre-commit/repolidaf4aj/.pre-commit-hooks.yaml is not a file
```

**Comment by asottile** [comment]
please search the issue tracker for duplicates, there are several

**Comment by maresb** [comment]
For the benefit of anyone who finds this and doesn't want to dig around on the issue tracker for an inordinate amount of time, it appears that the primary technical issue is simply that virtualenvs like to hard-code absolute paths, so moving them will break stuff, and thus pre-commit can't allow the cache directory to be moved.
