### ISSUE TITLE
Unable to run try-repo with hook from repository using submodules

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit#2755]
### search you tried in the issue tracker

submodules (several bugs but none seems related to this)

### describe your issue

While vendoring a dependency using a git submodule on a python project that also can used as a pre-commit hook, I observed that my internal hook testing starting to fail, basically because when pre-commit clones the repository, it does not do it with recursive option.

The hook test is done using the command below (using tox):
```
sh -c "mkdir -p .tox/x && cd .tox/x && git init && python3 -m pre_commit try-repo -v {toxinidir} ansible-lint"
```

I checked if there are additional options that I can feed `try-repo` in order to hint it to do the cloning using recursive submodules. Apparently there is no option for that.

I mention that locally the repository is cloned recursively and python is able to correctly do the packaging. I also enabled submodules for github actions in order to ensure it is fully cloned because otherwise it will fail with a ModuleNotFoundError error at runtime.

### pre-commit --version

pre-commit 3.0.2 

### .pre-commit-config.yaml

```yaml
# .pre-commit-hooks.yaml (as the config one is irrelevant for hook testing)
---
- id: ansible-lint
  name: Ansible-lint
  description: This hook runs ansible-lint.
  entry: python3 -m ansiblelint -v --force-color
  language: python
  pass_filenames: false
  always_run: true
  additional_dependencies:
    - .
    - ansible-core>=2.13.3
```

### ~/.cache/pre-commit/pre-commit.log (if present)

As the log file is not created when using try-repo, I pasted console output instead
```
$ tox -e hook
hook: commands[0]> sh -c 'mkdir -p .tox/x && cd .tox/x && git init && python3 -m pre_commit try-repo -v /Users/ssbarnea/c/a/ansible-lint ansible-lint'
Reinitialized existing Git repository in /Users/ssbarnea/c/a/ansible-lint/.tox/x/.git/
===============================================================================
Using config:
===============================================================================
repos:
-   repo: ../..
    rev: 1e9dbd056b2b8ce76405fc08da5f67f03b9eb672
    hooks:
    -   id: ansible-lint
===============================================================================
[INFO] Initializing environment for ../...
[INFO] Initializing environment for ../..:.,ansible-core>=2.13.3.
[INFO] Installing environment for ../...
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Ansible-lint.............................................................Failed
- hook id: ansible-lint
- duration: 1.29s
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/32/1xrphgzd4xv777syxjtkpdw80000gn/T/tmp9c0qw52x/repo03nnlqs_/py_env-python3/lib/python3.11/site-packages/ansiblelint/__main__.py", line 38, in <module>
    from ansiblelint import cli
  File "/var/folders/32/1xrphgzd4xv777syxjtkpdw80000gn/T/tmp9c0qw52x/repo03nnlqs_/py_env-python3/lib/python3.11/site-packages/ansiblelint/cli.py", line 26, in <module>
    from ansiblelint.yaml_utils import clean_json
  File "/var/folders/32/1xrphgzd4xv777syxjtkpdw80000gn/T/tmp9c0qw52x/repo03nnlqs_/py_env-python3/lib/python3.11/site-packages/ansiblelint/yaml_utils.py", line 44, in <module>
    from ansiblelint.utils import get_action_tasks, normalize_task
  File "/var/folders/32/1xrphgzd4xv777syxjtkpdw80000gn/T/tmp9c0qw52x/repo03nnlqs_/py_env-python3/lib/python3.11/site-packages/ansiblelint/utils.py", line 56, in <module>
    from ansiblelint.app import get_app
  File "/var/folders/32/1xrphgzd4xv777syxjtkpdw80000gn/T/tmp9c0qw52x/repo03nnlqs_/py_env-python3/lib/python3.11/site-packages/ansiblelint/app.py", line 15, in <module>
    from ansiblelint._vendor.ansible_compat.runtime import Runtime
ModuleNotFoundError: No module named 'ansiblelint._vendor.ansible_compat'

hook: exit 1 (14.85 seconds) /Users/ssbarnea/c/a/ansible-lint> sh -c 'mkdir -p .tox/x && cd .tox/x && git init && python3 -m pre_commit try-repo -v /Users/ssbarnea/c/a/ansible-lint ansible-lint' pid=28044
  hook: FAIL code 1 (14.85=setup[0.01]+cmd[14.85] seconds)
  evaluation failed :( (14.95 seconds)
tox -e hook  6.36s user 2.95s system 61% cpu 15.191 total
FAIL: 1
```

**Comment by ssbarnea** [comment]
For reference the WIP change that tries to add the submodule can be seen at https://github.com/ansible/ansible-lint/pull/2994 -- the command that fails is `tox -e hook` which is the one doing try-repo, with the scope of testing if the code does not break its use from pre-commit.

**Comment by asottile** [comment]
pre-commit is cloning the submodule (we have tests that show that) -- your `_vendor/__init__.py` is broken

```console
$ ls src/ansiblelint/_vendor/ -al
total 12
drwxr-xr-x 2 asottile asottile 4096 Feb  8 12:55 .
drwxr-xr-x 9 asottile asottile 4096 Feb  8 12:55 ..
lrwxrwxrwx 1 asottile asottile   52 Feb  8 12:55 ansible_compat -> ../../../.projects/ansible-compat/src/ansible_compat
-rw-r--r-- 1 asottile asottile 1965 Feb  8 12:55 __init__.py
$ ls src/ansiblelint/_vendor/ansible_compat
config.py     errors.py    loaders.py  prerun.py  runtime.py
constants.py  __init__.py  ports.py    py.typed   schema.py
```
