### ISSUE TITLE
pre-commit hook not working in local repository in both docker  interactive shell and cmd  when trying to git commit

### ISSUE THREAD

**Issue by HimanshuGarg47** [pre-commit/pre-commit#2783]
### search you tried in the issue tracker

An unexpected error has occurred: CalledProcessError: command: 

### describe your issue

I was doing git commit. But pre-commit hook giving error. I read all the same issue but none of them work for me. 
I had setup wagtail through [docker](https://github.com/wagtail/docker-wagtail-develop). 
I tried both ways 
1. Running docker containers , go to folder through interactive shell session within a Docker container where .git folder exits and run git commit through terminal, then error
was 
`pre-commit not found. Did you forget to activate your virtualenv?` 
2. Without interactive shell, i.e. direct go to folder and run git commit, now error is different
```

An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Himanshu Garg\\.cache\\pre-commit\\repolz3_4a0e\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\himanshu garg\.cache\pre-commit\repolz3_4a0e
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      so on.........................................(detail error log pasted below)
```

### pre-commit --version

pre-commit 3.1.0

### .pre-commit-config.yaml

```yaml
default_language_version:
  node: system
  python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: ['--target-version', 'py37']
  - repo: https://github.com/timothycrosley/isort
    # isort config is in setup.cfg
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    # flake8 config is in setup.cfg
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-comprehensions
          - flake8-assertive
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types_or: [css, scss, javascript, ts, tsx, json, yaml]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.8.0
    hooks:
      - id: eslint
        types: [file]
        files: \.(js|ts|tsx)$
        args: [--report-unused-disable-directives]
        additional_dependencies:
          - eslint@8.8.0
          - '@typescript-eslint/eslint-plugin@5.10.1'
          - '@typescript-eslint/parser@5.10.1'
          - '@wagtail/eslint-config-wagtail@0.4.0'
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.2.0
    hooks:
      - id: stylelint
        files: \.scss$
        additional_dependencies:
          - stylelint@14.2.0
          - '@wagtail/stylelint-config-wagtail@0.3.2'
  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        args: ['--parse-only']
  - repo: https://github.com/rtts/djhtml
    rev: v1.5.2
    hooks:
      - id: djhtml
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.3.0
    hooks:
      - id: semgrep
        args: ['--config', '.semgrep.yml', '--error']
```

### version information

```
pre-commit version: 3.1.0
git --version: git version 2.37.0.windows.1
sys.version:
    3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
sys.executable: C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Himanshu Garg\\.cache\\pre-commit\\repolz3_4a0e\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\himanshu garg\.cache\pre-commit\repolz3_4a0e
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      Preparing metadata (pyproject.toml) did not run successfully.
      exit code: 1
      
      [14 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\Himanshu Garg\AppData\Local\Temp\pip-build-env-uw5eaxlq\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 40, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "C:\Users\Himanshu Garg\AppData\Local\Temp\pip-build-env-uw5eaxlq\overlay\Lib\site-packages\poetry\core\factory.py", line 57, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
      
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    Encountered error while generating package metadata.
    
    See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

```
Traceback (most recent call last):
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\main.py", line 366, in main
    return hook_impl(
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\commands\hook_impl.py", line 254, in hook_impl
    return retv | run(config, store, ns)
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\commands\run.py", line 437, in run
    install_hook_envs(to_install, store)
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\languages\python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\lang_base.py", line 87, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\Himanshu Garg\\.cache\\pre-commit\\repolz3_4a0e\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\himanshu garg\.cache\pre-commit\repolz3_4a0e
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      Preparing metadata (pyproject.toml) did not run successfully.
      exit code: 1
      
      [14 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\Himanshu Garg\AppData\Local\Temp\pip-build-env-uw5eaxlq\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 40, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "C:\Users\Himanshu Garg\AppData\Local\Temp\pip-build-env-uw5eaxlq\overlay\Lib\site-packages\poetry\core\factory.py", line 57, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
      
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    Encountered error while generating package metadata.
    
    See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

**Comment by HimanshuGarg47** [comment]
Duplicate issue created by mistakenly
