### ISSUE TITLE
`check-ast` hook fails with  `language_version: python2.7`

### ISSUE THREAD

**Issue by seldon** [pre-commit/pre-commit#2797]
### search you tried in the issue tracker

from __future__ import annotations, Python 2.7

### describe your issue

Hi,
I have a legacy codebase written against **Python 2.7**, which I'd like to check with pre-commit's `check-ast` hook.

So I have:
- Installed `pre-commit` globally (via `pipx`; Python 3.8);
- Created a (Python 2.7) venv for my project;
- Activated the project's venv;
- Wrote a basic `.pre-commit-config.yaml` (see below);
- Ran `pre-commit install`;
- Ran `pre-commit run --all-files`, which ABORTED with the error msg attached below.

Now, I wonder if I made some mistake or it's a `pre-commit` issue (and if/how I can resolve it).

Thanks in advance for any help - and for creating this wonderful piece of software!

### pre-commit --version

3.1.1

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:    
    -   id: check-ast
        language_version: python2.7
```

### version information

```
pre-commit version: 3.1.1
git --version: git version 2.25.1
sys.version:
    3.8.10 (default, Nov 14 2022, 12:59:47) 
    [GCC 9.4.0]
sys.executable: /home/<removed>/.local/pipx/venvs/pre-commit/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/<removed>/.cache/pre-commit/repomyfji5p1/py_env-python2.7/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/<removed>/.cache/pre-commit/repomyfji5p1
stderr:
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
        ERROR: Command errored out with exit status 1:
         command: /home/<removed>/.cache/pre-commit/repomyfji5p1/py_env-python2.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-kx0lLb/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-kx0lLb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-Ymkiqm
             cwd: /tmp/pip-req-build-kx0lLb/
        Complete output (5 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-req-build-kx0lLb/setup.py", line 1
            from __future__ import annotations
        SyntaxError: future feature annotations is not defined
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

```
Traceback (most recent call last):
  File "/home/<removed>/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/<removed>/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/main.py", line 394, in main
    return run(args.config, store, args)
  File "/home/<removed>/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/commands/run.py", line 437, in run
    install_hook_envs(to_install, store)
  File "/home/<removed>/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/home/<removed>/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/home/<removed>/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/home/<removed>/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/lang_base.py", line 87, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/<removed>/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/<removed>/.cache/pre-commit/repomyfji5p1/py_env-python2.7/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/<removed>/.cache/pre-commit/repomyfji5p1
stderr:
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
        ERROR: Command errored out with exit status 1:
         command: /home/<removed>/.cache/pre-commit/repomyfji5p1/py_env-python2.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-kx0lLb/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-kx0lLb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-Ymkiqm
             cwd: /tmp/pip-req-build-kx0lLb/
        Complete output (5 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-req-build-kx0lLb/setup.py", line 1
            from __future__ import annotations
        SyntaxError: future feature annotations is not defined
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by asottile** [comment]
the output tells you the answer

**Comment by seldon** [comment]
@asottile Could you be a little more specific? 

If I had been able to get the answer to my question from the error msg, I wouldn't have taken the time to create this issue in the first place, don't you thinK?

**Comment by asottile** [comment]
> Python 2.7 reached the end of its life

**Comment by asottile** [comment]
but also this is the wrong repo -- this is the _framework_ repo and you have a problem with a particular tool
