### ISSUE TITLE
Setup in CI

### ISSUE THREAD

**Issue by elidupuis** [pre-commit/pre-commit#280]
I'm trying to run `pre-commit run --all-files` in continuous integration (using CircleCI). I've ensured that Python is available and run `pip install pre-commit` successfully:

```
pip install pre-commit
Requirement already satisfied (use --upgrade to upgrade): pre-commit in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): argparse in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): aspy.yaml in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): cached-property in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): jsonschema in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): nodeenv>=0.11.1 in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): ordereddict in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): simplejson in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): virtualenv in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from pre-commit)
Cleaning up...
```

However, when I actually try to run the `pre-commit run --all-files` I'm getting the following error:

```
pre-commit run --all-files
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.9/bin/pre-commit", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)

pkg_resources.DistributionNotFound: functools32 pre-commit run --all-files returned exit code 1
``` 

I've also tried running `pre-commit install` before the `run --all-files` command but I get the same error.

What am I missing here?

**Comment by asottile** [comment]
The issue is from jsonschema unfortunately :/

If you upgrade pip before installing pre-commit it should be fixed.

You can read more details here:

https://github.com/Julian/jsonschema/issues/233

**Comment by elidupuis** [comment]
Damn! Thanks for the speedy response. I've added `pip install --upgrade pip` to my CI configuration and pre-commit is initializing as we speak! :star2: 

Thanks again! :+1:

**Comment by asottile** [comment]
No problem, friend!  Glad to help :)
