### ISSUE TITLE
pre-commit can`t install environment

### ISSUE THREAD

**Issue by OleksiiHrutman** [pre-commit/pre-commit#2800]
### search you tried in the issue tracker

pre-commit can`t install environment

### describe your issue

I can`t execute `pre-commit run --all-files`

pre-commit==3.1.1
flake8==3.8.3
isort=5.12.0
pylint==2.16.3
black==23.1.0

### pre-commit --version

3.1.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-json
      - id: check-symlinks
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/ahonnecke/blacklist
    rev: v0.0.3
    hooks:
      - id: blacklist
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.3
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a3
    hooks:
      - id: pylint
#        exclude: tests/fixtures/
  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
pre-commit version: 3.1.1
git --version: git version 2.25.1
sys.version:
    3.10.10 (main, Feb  8 2023, 14:50:01) [GCC 9.4.0]
sys.executable: /home/aaaaaaa/work_projects/backend/.venv/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/aaaaaaa/.cache/pre-commit/repo_59xu78f/py_env-python3.10/bin/python>>
- expected version: 3.10.10.final.0

```

```
Traceback (most recent call last):
  File "/home/aaaaaaa/work_projects/backend/.venv/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/aaaaaaa/work_projects/backend/.venv/lib/python3.10/site-packages/pre_commit/main.py", line 394, in main
    return run(args.config, store, args)
  File "/home/aaaaaaa/work_projects/backend/.venv/lib/python3.10/site-packages/pre_commit/commands/run.py", line 437, in run
    install_hook_envs(to_install, store)
  File "/home/aaaaaaa/work_projects/backend/.venv/lib/python3.10/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/home/aaaaaaa/work_projects/backend/.venv/lib/python3.10/site-packages/pre_commit/repository.py", line 100, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /home/aaaaaaa/.cache/pre-commit/repo_59xu78f/py_env-python3.10/bin/python>>
- expected version: 3.10.10.final.0
```

**Comment by asottile** [comment]
please search the issue tracker, there are several duplicates
