### ISSUE TITLE
pre-commit skipping trailing-whitespace checks on all files

### ISSUE THREAD

**Issue by sandman** [pre-commit/pre-commit#2812]
### search you tried in the issue tracker

trailing whitespace hook not applied

### describe your issue

My pre-commit checker is not removing the trailing whitespaces on any file.

When I run `pre-commit run --all-files`, I always get:
`trim trailing whitespace.............................(no files to check)Skipped`

### pre-commit --version

pre-commit 3.0.3

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        exclude_types: [text] # exclude golden files
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"] # Instead of loading the files, simply parse them for syntax
      - id: mixed-line-ending
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/PyCQA/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
```

### version information

```
pre-commit version: 3.0.3
git --version: git version 2.25.1
sys.version:
    3.8.10 (default, Nov 14 2022, 12:59:47) 
    [GCC 9.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
Interrupted (^C): KeyboardInterrupt: 
```

```
Traceback (most recent call last):
  File "/home/sandip/.local/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/sandip/.local/lib/python3.8/site-packages/pre_commit/main.py", line 355, in main
    return autoupdate(
  File "/home/sandip/.local/lib/python3.8/site-packages/pre_commit/commands/autoupdate.py", line 170, in autoupdate
    new_info = info.update(tags_only=tags_only, freeze=freeze)
  File "/home/sandip/.local/lib/python3.8/site-packages/pre_commit/commands/autoupdate.py", line 52, in update
    cmd_output_b(
  File "/home/sandip/.local/lib/python3.8/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    stdout_b, stderr_b = proc.communicate()
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1868, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

**Comment by asottile** [comment]
what do you think `exclude_types: [text]` should do?

**Comment by sandman** [comment]
@asottile I commented out that line and ran pre-commit run trailing-whitespace --files <filename.py> with the same output:
`trim trailing whitespace.............................(no files to check)Skipped`

Is there something I need to do to apply the changes to the YAML config? Sorry if the question seems nooby - I am new to pre-commit.

**Comment by asottile** [comment]
show the exact command you ran and the full output and the exact contents of your configuration when you ran that?
