### ISSUE TITLE
SSLError when running `pre-commit` installed with conda on Windows 10

### ISSUE THREAD

**Issue by blazejdolicki** [pre-commit/pre-commit#2813]
### search you tried in the issue tracker

ssl certificate

### describe your issue

I tried installing pre-commit in a conda environment on Windows 10 according to https://pre-commit.com/#install and when running `pre-commit` in the console, I am getting the error shown in logs. Thank you in advance for help and please let me know if you need any more info.

Similar closed issues that didn't help:
* https://github.com/pre-commit/pre-commit/issues/2445 - I tried creating a new conda environment and install pre-commit with conda, the same error occurred
* https://github.com/pre-commit/pre-commit/issues/2197 - not applicable: I don't have any special certificate requirements
* https://github.com/pre-commit/pre-commit/issues/1283 - in my case running `pre-commit` doesn't even work in the console
* https://github.com/pre-commit/pre-commit/issues/701 - the issue is pretty old, the workaround to reinstall virtualenv in conda seems outdated

### pre-commit --version

3.1.1

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3.9
repos:
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: [--max-line-length=120, --extend-ignore=E203,E704, --per-file-ignores=__init__.py:F401]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [--line-length=120]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile=black, --line-length=120, --skip-gitignore, --project=aiosyn*]
```

### version information

```
pre-commit version: 3.1.1
git --version: git version 2.39.0.windows.1
sys.version:
    3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)]
sys.executable: C:\Users\BlazejDolicki\anaconda3\envs\precommit_conda\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\BlazejDolicki\\.cache\\pre-commit\\repokauxucf6\\py_env-python3.9\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\blazejdolicki\.cache\pre-commit\repokauxucf6
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Could not fetch URL https://pypi.org/simple/mccabe/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/mccabe/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
stderr:
    WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mccabe/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mccabe/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mccabe/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mccabe/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mccabe/
    ERROR: Could not find a version that satisfies the requirement mccabe<0.7.0,>=0.6.0 (from flake8) (from versions: none)
    ERROR: No matching distribution found for mccabe<0.7.0,>=0.6.0
```

```
Traceback (most recent call last):
  File "C:\Users\BlazejDolicki\anaconda3\envs\precommit_conda\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\BlazejDolicki\anaconda3\envs\precommit_conda\lib\site-packages\pre_commit\main.py", line 394, in main
    return run(args.config, store, args)
  File "C:\Users\BlazejDolicki\anaconda3\envs\precommit_conda\lib\site-packages\pre_commit\commands\run.py", line 437, in run
    install_hook_envs(to_install, store)
  File "C:\Users\BlazejDolicki\anaconda3\envs\precommit_conda\lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\BlazejDolicki\anaconda3\envs\precommit_conda\lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "C:\Users\BlazejDolicki\anaconda3\envs\precommit_conda\lib\site-packages\pre_commit\languages\python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "C:\Users\BlazejDolicki\anaconda3\envs\precommit_conda\lib\site-packages\pre_commit\lang_base.py", line 87, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Users\BlazejDolicki\anaconda3\envs\precommit_conda\lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\BlazejDolicki\\.cache\\pre-commit\\repokauxucf6\\py_env-python3.9\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\blazejdolicki\.cache\pre-commit\repokauxucf6
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Could not fetch URL https://pypi.org/simple/mccabe/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/mccabe/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
stderr:
    WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mccabe/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mccabe/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mccabe/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mccabe/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/mccabe/
    ERROR: Could not find a version that satisfies the requirement mccabe<0.7.0,>=0.6.0 (from flake8) (from versions: none)
    ERROR: No matching distribution found for mccabe<0.7.0,>=0.6.0
```

**Comment by asottile** [comment]
yeah sorry your python is broken -- this isn't a pre-commit issue

**Comment by blazejdolicki** [comment]
Thank you for your quick reply, can you elaborate on your response? Until this problem with pre-commit, I haven't had any issues with installing other packages with pip/conda before. If I manually try `pip install mccabe` it installs succesfully. If it is indeed a python problem, could you point me anyhow to a solution?

**Comment by asottile** [comment]
sorry I can't really help you with computer support. I don't recommend conda

**Comment by blazejdolicki** [comment]
After going through multiple posts where people were struggling with the same errors in pre-commit as I did, I found [this recent workaround](https://stackoverflow.com/a/74689913/9215579): it seems that pre-commit (with conda on Windows) only works on the `base` conda environment. This worked for me as well. I understand that providing support for conda is not a priority for you, but would it be possible to add a comment in the [installation guide](https://pre-commit.com/#install) about this limitation?

**Comment by johnkangw** [comment]
> After going through multiple posts where people were struggling with the same errors in pre-commit as I did, I found [this recent workaround](https://stackoverflow.com/a/74689913/9215579): it seems that pre-commit (with conda on Windows) only works on the `base` conda environment. This worked for me as well. I understand that providing support for conda is not a priority for you, but would it be possible to add a comment in the [installation guide](https://pre-commit.com/#install) about this limitation?

@blazejdolicki Thanks for sending those instructions. Even using the base conda did not work for me. So I created a new venv, and it works. For some reason, conda has issues with pre-commit...

**Comment by skupr-anaconda** [comment]
Use mccabe>=0.7.0,<0.8.0. It will works fine

**Comment by joshkyh** [comment]
I faced the same issue. However, I found that the error only occurs with Python 3.09, I was able to run `pre-commit run --all-files` successfully simply by switching to Python 3.11. Both environments are newly built conda environments.
