### ISSUE TITLE
An unexpected error has occurred: CalledProcessError: command: ('python', '-mpip', 'install', '.')

### ISSUE THREAD

**Issue by mirodil1** [pre-commit/pre-commit#2838]
### search you tried in the issue tracker

An unexpected error has occurred: CalledProcessError: command: ('python', '-mpip', 'install', '.')

### describe your issue

I am getting `pre_commit.util.CalledProcessError: command: ('python', '-mpip', 'install', '.')` while trying to `git commit` on local repo.

### pre-commit --version

pre-commit==3.2.2

### .pre-commit-config.yaml

```yaml
exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```python
Traceback (most recent call last):
  File "/home/mirodil/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/mirodil/.local/lib/python3.10/site-packages/pre_commit/main.py", line 381, in main
    return hook_impl(
  File "/home/mirodil/.local/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
  File "/home/mirodil/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/mirodil/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/home/mirodil/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/home/mirodil/.local/lib/python3.10/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/home/mirodil/.local/lib/python3.10/site-packages/pre_commit/lang_base.py", line 87, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/mirodil/.local/lib/python3.10/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('python', '-mpip', 'install', '.')
return code: 1
stdout:
    Executable `python` not found
stderr: (none)
```

**Comment by asottile** [comment]
try searching the error message
