### ISSUE TITLE
Pre-commit fails to run when typed_ast needs to be built.

### ISSUE THREAD

**Issue by MarcvdSluys** [pre-commit/pre-commit#2850]
### search you tried in the issue tracker

typed_ast  /  typed-ast  (open and closed)

### describe your issue

I ran pre-commit on an existing package/configuration.  Pre-commit updated some of its repos, and failed, in particular when trying to build typed_ast/typed-ast.  I updated to the latest pre-commit trough pip, removed my pre-commit cache, but keep getting the same issue:

[user@laptop PythonPackage]$ rm -rf /home/user/.cache/pre-commit/

[user@laptop PythonPackage]$ pre-commit run --all-files  # python-check-precommit

[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/user/.cache/pre-commit/repofrc0t6ql
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting mypy==0.812
      Using cached mypy-0.812-py3-none-any.whl (2.5 MB)
    Collecting typed-ast<1.5.0,>=1.4.0
      Using cached typed_ast-1.4.3.tar.gz (210 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting typing-extensions>=3.7.4
      Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
    Collecting mypy-extensions<0.5.0,>=0.4.3
      Using cached mypy_extensions-0.4.4-py2.py3-none-any.whl
    Building wheels for collected packages: pre-commit-dummy-package, typed-ast
      Building wheel for pre-commit-dummy-package (setup.py): started
      Building wheel for pre-commit-dummy-package (setup.py): finished with status 'done'
      Created wheel for pre-commit-dummy-package: filename=pre_commit_dummy_package-0.0.0-py3-none-any.whl size=1120 sha256=4547c41f0f29058ef033e7d07219e935d4c26669b484d711fc4a64fefa02032b
      Stored in directory: /tmp/pip-ephem-wheel-cache-ewqtr7iu/wheels/25/97/8b/d03bb1e840ecf3aff3ae553246a61fa9c51c0c51112208c502
      Building wheel for typed-ast (setup.py): started
      Building wheel for typed-ast (setup.py): finished with status 'error'
      Running setup.py clean for typed-ast
    Successfully built pre-commit-dummy-package
    Failed to build typed-ast
    Installing collected packages: typed-ast, typing-extensions, mypy-extensions, mypy, pre-commit-dummy-package
      Running setup.py install for typed-ast: started
      Running setup.py install for typed-ast: finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [26 lines of output]
          running bdist_wheel
          running build
          running build_py
          creating build
          creating build/lib.linux-x86_64-cpython-311
          creating build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/conversions.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast27.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast3.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/__init__.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          creating build/lib.linux-x86_64-cpython-311/typed_ast/tests
          copying ast3/tests/test_basics.py -> build/lib.linux-x86_64-cpython-311/typed_ast/tests
          running build_ext
          building '_ast27' extension
          creating build/temp.linux-x86_64-cpython-311
          creating build/temp.linux-x86_64-cpython-311/ast27
          creating build/temp.linux-x86_64-cpython-311/ast27/Custom
          creating build/temp.linux-x86_64-cpython-311/ast27/Parser
          creating build/temp.linux-x86_64-cpython-311/ast27/Python
          x86_64-pc-linux-gnu-gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fPIC -Iast27/Include -I/home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/include -I/usr/include/python3.11 -c ast27/Custom/typed_ast.c -o build/temp.linux-x86_64-cpython-311/ast27/Custom/typed_ast.o
          In file included from ast27/Custom/typed_ast.c:3:
          ast27/Custom/../Include/compile.h:5:10: fatal error: code.h: No such file or directory
              5 | #include "code.h"
                |          ^~~~~~~~
          compilation terminated.
          error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for typed-ast
      error: subprocess-exited-with-error
      
      × Running setup.py install for typed-ast did not run successfully.
      │ exit code: 1
      ╰─> [28 lines of output]
          running install
          /home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
            warnings.warn(
          running build
          running build_py
          creating build
          creating build/lib.linux-x86_64-cpython-311
          creating build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/conversions.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast27.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast3.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/__init__.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          creating build/lib.linux-x86_64-cpython-311/typed_ast/tests
          copying ast3/tests/test_basics.py -> build/lib.linux-x86_64-cpython-311/typed_ast/tests
          running build_ext
          building '_ast27' extension
          creating build/temp.linux-x86_64-cpython-311
          creating build/temp.linux-x86_64-cpython-311/ast27
          creating build/temp.linux-x86_64-cpython-311/ast27/Custom
          creating build/temp.linux-x86_64-cpython-311/ast27/Parser
          creating build/temp.linux-x86_64-cpython-311/ast27/Python
          x86_64-pc-linux-gnu-gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fPIC -Iast27/Include -I/home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/include -I/usr/include/python3.11 -c ast27/Custom/typed_ast.c -o build/temp.linux-x86_64-cpython-311/ast27/Custom/typed_ast.o
          In file included from ast27/Custom/typed_ast.c:3:
          ast27/Custom/../Include/compile.h:5:10: fatal error: code.h: No such file or directory
              5 | #include "code.h"
                |          ^~~~~~~~
          compilation terminated.
          error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure
    
    × Encountered error while trying to install package.
    ╰─> typed-ast
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for output from the failure.
Check the log at /home/user/.cache/pre-commit/pre-commit.log

### pre-commit --version

pre-commit 3.2.2

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files           # Prevent giant files from being committed 
    -   id: check-ast                         # Simply check whether the files parse as valid python
    -   id: check-byte-order-marker           # Forbid files which have a UTF-8 byte-order marker
    -   id: check-builtin-literals            # Require literal syntax when initializing empty or zero Python builtin types.
    -   id: check-case-conflict               # Check for files that would conflict in case-insensitive filesystems
    -   id: check-docstring-first             # Checks a common error of defining a docstring after code.
    -   id: check-executables-have-shebangs   # Ensures that (non-binary) executables have a shebang.
    -   id: check-merge-conflict              # Check for files that contain merge conflict strings.
    -   id: check-symlinks                    # Checks for symlinks which do not point to anything.
    -   id: check-toml                        # This hook checks toml files for parseable syntax.
    -   id: check-vcs-permalinks              # Ensures that links to vcs websites are permalinks.
    -   id: check-xml                         # This hook checks xml files for parseable syntax.
    -   id: check-yaml                        # This hook checks yaml files for parseable syntax.
    -   id: debug-statements                  # Check for debugger imports and py37+ `breakpoint()` calls in python source.
    -   id: destroyed-symlinks                # Detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
    # -   id: detect-aws-credentials            # Detects *your* aws credentials from the aws cli credentials file
    -   id: detect-private-key                # Detects the presence of private keys
    -   id: double-quote-string-fixer         # This hook replaces double quoted strings with single quoted strings
    -   id: end-of-file-fixer                 # Ensures that a file is either empty, or ends with one newline.
    -   id: fix-byte-order-marker             # Removes UTF-8 byte order marker
    -   id: fix-encoding-pragma               # Add # -*- coding: utf-8 -*- to the top of python files
    -   id: forbid-new-submodules             # Prevent addition of new git submodules
    -   id: mixed-line-ending                 # Replaces or checks mixed line ending
    -   id: name-tests-test                   # This verifies that test files are named correctly
    -   id: requirements-txt-fixer            # Sorts entries in requirements.txt
    -   id: sort-simple-yaml                  # Sorts simple YAML files which consist only of top-level keys, preserving comments and blocks.
    # -   id: trailing-whitespace               # This hook trims trailing whitespace.
# -   repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: 'v1.5.7'  # Use the sha / tag you want to point at
#     hooks:
#     -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
# -   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#     rev: v1.2.1
#     hooks:
#     -   id: python-safety-dependencies-check
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8                            # a command-line utility for enforcing style consistency across Python projects
```

### version information

```
pre-commit version: 3.2.2
git --version: git version 2.39.2
sys.version:
    3.11.2 (main, Mar 26 2023, 21:15:26) [GCC 11.3.1 20230120]
sys.executable: /usr/bin/python3.11
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/user/.cache/pre-commit/repofrc0t6ql
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting mypy==0.812
      Using cached mypy-0.812-py3-none-any.whl (2.5 MB)
    Collecting typed-ast<1.5.0,>=1.4.0
      Using cached typed_ast-1.4.3.tar.gz (210 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting typing-extensions>=3.7.4
      Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
    Collecting mypy-extensions<0.5.0,>=0.4.3
      Using cached mypy_extensions-0.4.4-py2.py3-none-any.whl
    Building wheels for collected packages: pre-commit-dummy-package, typed-ast
      Building wheel for pre-commit-dummy-package (setup.py): started
      Building wheel for pre-commit-dummy-package (setup.py): finished with status 'done'
      Created wheel for pre-commit-dummy-package: filename=pre_commit_dummy_package-0.0.0-py3-none-any.whl size=1120 sha256=4547c41f0f29058ef033e7d07219e935d4c26669b484d711fc4a64fefa02032b
      Stored in directory: /tmp/pip-ephem-wheel-cache-ewqtr7iu/wheels/25/97/8b/d03bb1e840ecf3aff3ae553246a61fa9c51c0c51112208c502
      Building wheel for typed-ast (setup.py): started
      Building wheel for typed-ast (setup.py): finished with status 'error'
      Running setup.py clean for typed-ast
    Successfully built pre-commit-dummy-package
    Failed to build typed-ast
    Installing collected packages: typed-ast, typing-extensions, mypy-extensions, mypy, pre-commit-dummy-package
      Running setup.py install for typed-ast: started
      Running setup.py install for typed-ast: finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [26 lines of output]
          running bdist_wheel
          running build
          running build_py
          creating build
          creating build/lib.linux-x86_64-cpython-311
          creating build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/conversions.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast27.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast3.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/__init__.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          creating build/lib.linux-x86_64-cpython-311/typed_ast/tests
          copying ast3/tests/test_basics.py -> build/lib.linux-x86_64-cpython-311/typed_ast/tests
          running build_ext
          building '_ast27' extension
          creating build/temp.linux-x86_64-cpython-311
          creating build/temp.linux-x86_64-cpython-311/ast27
          creating build/temp.linux-x86_64-cpython-311/ast27/Custom
          creating build/temp.linux-x86_64-cpython-311/ast27/Parser
          creating build/temp.linux-x86_64-cpython-311/ast27/Python
          x86_64-pc-linux-gnu-gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fPIC -Iast27/Include -I/home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/include -I/usr/include/python3.11 -c ast27/Custom/typed_ast.c -o build/temp.linux-x86_64-cpython-311/ast27/Custom/typed_ast.o
          In file included from ast27/Custom/typed_ast.c:3:
          ast27/Custom/../Include/compile.h:5:10: fatal error: code.h: No such file or directory
              5 | #include "code.h"
                |          ^~~~~~~~
          compilation terminated.
          error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for typed-ast
      error: subprocess-exited-with-error
      
      × Running setup.py install for typed-ast did not run successfully.
      │ exit code: 1
      ╰─> [28 lines of output]
          running install
          /home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
            warnings.warn(
          running build
          running build_py
          creating build
          creating build/lib.linux-x86_64-cpython-311
          creating build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/conversions.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast27.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast3.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/__init__.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          creating build/lib.linux-x86_64-cpython-311/typed_ast/tests
          copying ast3/tests/test_basics.py -> build/lib.linux-x86_64-cpython-311/typed_ast/tests
          running build_ext
          building '_ast27' extension
          creating build/temp.linux-x86_64-cpython-311
          creating build/temp.linux-x86_64-cpython-311/ast27
          creating build/temp.linux-x86_64-cpython-311/ast27/Custom
          creating build/temp.linux-x86_64-cpython-311/ast27/Parser
          creating build/temp.linux-x86_64-cpython-311/ast27/Python
          x86_64-pc-linux-gnu-gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fPIC -Iast27/Include -I/home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/include -I/usr/include/python3.11 -c ast27/Custom/typed_ast.c -o build/temp.linux-x86_64-cpython-311/ast27/Custom/typed_ast.o
          In file included from ast27/Custom/typed_ast.c:3:
          ast27/Custom/../Include/compile.h:5:10: fatal error: code.h: No such file or directory
              5 | #include "code.h"
                |          ^~~~~~~~
          compilation terminated.
          error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure
    
    × Encountered error while trying to install package.
    ╰─> typed-ast
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for output from the failure.
```

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/user/.local/lib/python3.11/site-packages/pre_commit/main.py", line 409, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/user/.local/lib/python3.11/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/home/user/.local/lib/python3.11/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/home/user/.local/lib/python3.11/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/home/user/.local/lib/python3.11/site-packages/pre_commit/lang_base.py", line 87, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/user/.local/lib/python3.11/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /home/user/.cache/pre-commit/repofrc0t6ql
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting mypy==0.812
      Using cached mypy-0.812-py3-none-any.whl (2.5 MB)
    Collecting typed-ast<1.5.0,>=1.4.0
      Using cached typed_ast-1.4.3.tar.gz (210 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting typing-extensions>=3.7.4
      Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
    Collecting mypy-extensions<0.5.0,>=0.4.3
      Using cached mypy_extensions-0.4.4-py2.py3-none-any.whl
    Building wheels for collected packages: pre-commit-dummy-package, typed-ast
      Building wheel for pre-commit-dummy-package (setup.py): started
      Building wheel for pre-commit-dummy-package (setup.py): finished with status 'done'
      Created wheel for pre-commit-dummy-package: filename=pre_commit_dummy_package-0.0.0-py3-none-any.whl size=1120 sha256=4547c41f0f29058ef033e7d07219e935d4c26669b484d711fc4a64fefa02032b
      Stored in directory: /tmp/pip-ephem-wheel-cache-ewqtr7iu/wheels/25/97/8b/d03bb1e840ecf3aff3ae553246a61fa9c51c0c51112208c502
      Building wheel for typed-ast (setup.py): started
      Building wheel for typed-ast (setup.py): finished with status 'error'
      Running setup.py clean for typed-ast
    Successfully built pre-commit-dummy-package
    Failed to build typed-ast
    Installing collected packages: typed-ast, typing-extensions, mypy-extensions, mypy, pre-commit-dummy-package
      Running setup.py install for typed-ast: started
      Running setup.py install for typed-ast: finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [26 lines of output]
          running bdist_wheel
          running build
          running build_py
          creating build
          creating build/lib.linux-x86_64-cpython-311
          creating build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/conversions.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast27.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast3.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/__init__.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          creating build/lib.linux-x86_64-cpython-311/typed_ast/tests
          copying ast3/tests/test_basics.py -> build/lib.linux-x86_64-cpython-311/typed_ast/tests
          running build_ext
          building '_ast27' extension
          creating build/temp.linux-x86_64-cpython-311
          creating build/temp.linux-x86_64-cpython-311/ast27
          creating build/temp.linux-x86_64-cpython-311/ast27/Custom
          creating build/temp.linux-x86_64-cpython-311/ast27/Parser
          creating build/temp.linux-x86_64-cpython-311/ast27/Python
          x86_64-pc-linux-gnu-gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fPIC -Iast27/Include -I/home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/include -I/usr/include/python3.11 -c ast27/Custom/typed_ast.c -o build/temp.linux-x86_64-cpython-311/ast27/Custom/typed_ast.o
          In file included from ast27/Custom/typed_ast.c:3:
          ast27/Custom/../Include/compile.h:5:10: fatal error: code.h: No such file or directory
              5 | #include "code.h"
                |          ^~~~~~~~
          compilation terminated.
          error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for typed-ast
      error: subprocess-exited-with-error
      
      × Running setup.py install for typed-ast did not run successfully.
      │ exit code: 1
      ╰─> [28 lines of output]
          running install
          /home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
            warnings.warn(
          running build
          running build_py
          creating build
          creating build/lib.linux-x86_64-cpython-311
          creating build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/conversions.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast27.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/ast3.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          copying typed_ast/__init__.py -> build/lib.linux-x86_64-cpython-311/typed_ast
          creating build/lib.linux-x86_64-cpython-311/typed_ast/tests
          copying ast3/tests/test_basics.py -> build/lib.linux-x86_64-cpython-311/typed_ast/tests
          running build_ext
          building '_ast27' extension
          creating build/temp.linux-x86_64-cpython-311
          creating build/temp.linux-x86_64-cpython-311/ast27
          creating build/temp.linux-x86_64-cpython-311/ast27/Custom
          creating build/temp.linux-x86_64-cpython-311/ast27/Parser
          creating build/temp.linux-x86_64-cpython-311/ast27/Python
          x86_64-pc-linux-gnu-gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fPIC -Iast27/Include -I/home/user/.cache/pre-commit/repofrc0t6ql/py_env-python3.11/include -I/usr/include/python3.11 -c ast27/Custom/typed_ast.c -o build/temp.linux-x86_64-cpython-311/ast27/Custom/typed_ast.o
          In file included from ast27/Custom/typed_ast.c:3:
          ast27/Custom/../Include/compile.h:5:10: fatal error: code.h: No such file or directory
              5 | #include "code.h"
                |          ^~~~~~~~
          compilation terminated.
          error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure
    
    × Encountered error while trying to install package.
    ╰─> typed-ast
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for output from the failure.
```

**Comment by MarcvdSluys** [comment]
I found that this is a `mypy` issue, and that I should have updated the line
```yaml
rev: 'v0.812'  # Use the sha / tag you want to point at
```
to the latest revision from https://github.com/pre-commit/mirrors-mypy (currently v1.2.0).

I apologise for wasting your time...

**Comment by ludwigschwardt** [comment]
> I apologise for wasting your time...

Thanks, you actually saved me time 😁
