### ISSUE TITLE
Failure from DeprecationWarning on 'pipes'

### ISSUE THREAD

**Issue by strongishllama** [pre-commit/pre-commit#2864]
### search you tried in the issue tracker

pipes

### describe your issue

When running the following command, it is failing with a deprecation warning about 'pipes'.

```
pre-commit install --install-hook
```

```
pre-commit installed at .git/hooks/pre-commit
[INFO] Initializing environment for https://github.com/alessandrojcm/commitlint-pre-commit-hook.
[INFO] Initializing environment for https://github.com/alessandrojcm/commitlint-pre-commit-hook:@commitlint/config-conventional.
[INFO] Initializing environment for https://github.com/zricethezav/gitleaks.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/alessandrojcm/commitlint-pre-commit-hook.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/Cellar/pre-commit/3.3.0/libexec/bin/python3.11', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/taliesin/.cache/pre-commit/repo41tk8fto/node_env-default')
return code: 1
stdout: (none)
stderr:
    /usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
      import pipes
     * Install prebuilt node (18) ...
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 1519, in <module>
        main()
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 1104, in main
        create_environment(env_dir, args)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 980, in create_environment
        install_node(env_dir, src_dir, args)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 739, in install_node
        install_node_wrapped(env_dir, src_dir, args)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 772, in install_node_wrapped
        copy_node_from_prebuilt(env_dir, src_dir, args.node)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 665, in copy_node_from_prebuilt
        src_folder, = glob.glob(src_folder_tpl)
        ^^^^^^^^^^^
    ValueError: not enough values to unpack (expected 1, got 0)
Check the log at /Users/taliesin/.cache/pre-commit/pre-commit.log
```

I could be wrong, but I believe it's related to `pre-commit` itself, but only is triggered when the `commitlint` hook is run. I've also tried a couple of different versions of `pre-commit` with no luck. Cheers!

### pre-commit --version

pre-commit 3.3.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: trailing-whitespace
      - id: end-of-file-fixer
```

### version information

```
pre-commit version: 3.3.0
git --version: git version 2.40.1
sys.version:
    3.11.3 (main, Apr  7 2023, 19:25:52) [Clang 14.0.0 (clang-1400.0.29.202)]
sys.executable: /usr/local/Cellar/pre-commit/3.3.0/libexec/bin/python3.11
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/Cellar/pre-commit/3.3.0/libexec/bin/python3.11', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/taliesin/.cache/pre-commit/repo41tk8fto/node_env-default')
return code: 1
stdout: (none)
stderr:
    /usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
      import pipes
     * Install prebuilt node (18) ...
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 1519, in <module>
        main()
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 1104, in main
        create_environment(env_dir, args)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 980, in create_environment
        install_node(env_dir, src_dir, args)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 739, in install_node
        install_node_wrapped(env_dir, src_dir, args)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 772, in install_node_wrapped
        copy_node_from_prebuilt(env_dir, src_dir, args.node)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 665, in copy_node_from_prebuilt
        src_folder, = glob.glob(src_folder_tpl)
        ^^^^^^^^^^^
    ValueError: not enough values to unpack (expected 1, got 0)
```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/main.py", line 396, in main
    return install(
           ^^^^^^^^
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/commands/install_uninstall.py", line 140, in install
    install_hooks(config_file, store)
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/commands/install_uninstall.py", line 146, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/languages/node.py", line 89, in install_environment
    cmd_output_b(*cmd)
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/Cellar/pre-commit/3.3.0/libexec/bin/python3.11', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/taliesin/.cache/pre-commit/repo41tk8fto/node_env-default')
return code: 1
stdout: (none)
stderr:
    /usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
      import pipes
     * Install prebuilt node (18) ...
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 1519, in <module>
        main()
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 1104, in main
        create_environment(env_dir, args)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 980, in create_environment
        install_node(env_dir, src_dir, args)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 739, in install_node
        install_node_wrapped(env_dir, src_dir, args)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 772, in install_node_wrapped
        copy_node_from_prebuilt(env_dir, src_dir, args.node)
      File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/nodeenv.py", line 665, in copy_node_from_prebuilt
        src_folder, = glob.glob(src_folder_tpl)
        ^^^^^^^^^^^
    ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by asottile** [comment]
this isn't a pre-commit issue -- the warning is unrelated as well.  the problem is in nodeenv
