### ISSUE TITLE
pre-commit timeout for 

### ISSUE THREAD

**Issue by karmingc** [pre-commit/pre-commit#2867]
### search you tried in the issue tracker

yes

### describe your issue

crossposting from https://github.com/returntocorp/semgrep/issues/7716

I'm having issues installing semgrep's hook albeit being the only hook while past issues related to resolving conflicting dependencies such as https://github.com/pre-commit/pre-commit/issues/2647.

I'm not too sure where to go from here and would like some advice on debugging this if possible.

### pre-commit --version

3.3.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/returntocorp/semgrep
    rev: "v1.20.0"
    hooks:
      - id: semgrep-docker
        # See semgrep.dev/rulesets to select a ruleset and copy its URL
        args: ["--config", "auto", "--error", "--skip-unknown-extensions"]
```

### version information

```
pre-commit version: 3.3.0
git --version: git version 2.40.0
sys.version:
    3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)]
sys.executable: /usr/local/Cellar/pre-commit/3.3.0/libexec/bin/python3.11
os.name: posix
sys.platform: darwin
```

### error information

```
Interrupted (^C): KeyboardInterrupt:
```

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/commands/run.py", line 425, in run
    for hook in all_hooks(config, store)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 252, in all_hooks
    return tuple(
           ^^^^^^
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 255, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 230, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 196, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/store.py", line 206, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/store.py", line 163, in _new_repo
    make_strategy(directory)
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/store.py", line 202, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/store.py", line 186, in _shallow_clone
    git_cmd(
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/store.py", line 199, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/usr/local/Cellar/pre-commit/3.3.0/libexec/lib/python3.11/site-packages/pre_commit/util.py", line 106, in cmd_output_b
    stdout_b, stderr_b = proc.communicate()
                         ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1207, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 2075, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

**Comment by asottile** [comment]
"yes" is not a search term -- this isn't a pre-commit problem -- you ^C'd while it was cloning so be more patient

**Comment by karmingc** [comment]
@asottile, updated the search term, I misread that part.

As for cloning, it keeps prompting me for my passphrase, is that a normal behaviour? I'm assuming that its continuous prompt is an indication of reaching a timeout. Maybe I'm not understand this correctly?

**Comment by asottile** [comment]
it is not -- that's an https clone asking for ssh credentials so you've probably misconfigured your git.  I am unfortunately not a free debugging service but you've probably done something wrong with your gitconfig, probably with `insteadOf` somewhere

**Comment by asottile** [comment]
also next time show your actual output instead of hiding it -- wastes everyone's time if you don't share what you're seeing
