### ISSUE TITLE
'NoneType' object has no attribute 'split' in parse_version

### ISSUE THREAD

**Issue by zivkovic** [pre-commit/pre-commit#2874]
### search you tried in the issue tracker

is:issue 'NoneType' object has no attribute 'split'

### describe your issue

I updated to pre-commit 3.3.1 and tried to commit the changes. Reverting to 3.3.0 makes it work again.

### pre-commit --version

pre-commit 3.3.1

### .pre-commit-config.yaml

```yaml
exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$

-   repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
```

### version information

```
pre-commit version: None
git --version: git version 2.40.0
sys.version:
    3.11.2 (main, Mar 11 2023, 18:30:36) [GCC 12.2.1 20230201]
sys.executable: /home/<project_folder>/venv/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AttributeError: 'NoneType' object has no attribute 'split'
```

```
Traceback (most recent call last):
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/main.py", line 386, in main
    return hook_impl(
           ^^^^^^^^^^
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/commands/hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/commands/run.py", line 425, in run
    for hook in all_hooks(config, store)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/repository.py", line 252, in all_hooks
    return tuple(
           ^^^^^^
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/repository.py", line 255, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/repository.py", line 230, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/repository.py", line 208, in _cloned_repository_hooks
    hook_dcts = [
                ^
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/repository.py", line 209, in <listcomp>
    _hook(by_id[hook['id']], hook, root_config=root_config)
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/repository.py", line 128, in _hook
    if parse_version(version) > parse_version(C.VERSION):
                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<project_folder>/venv/lib/python3.11/site-packages/pre_commit/clientlib.py", line 50, in parse_version
    return tuple(int(p) for p in s.split('.'))
                                 ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by asottile** [comment]
your installation is corrupted in don't way -- you should reinstall

**Comment by zivkovic** [comment]
Seems like this was really it. Had to manually delete files, otherwise it did not work. Thank you.
