### ISSUE TITLE
CalledProcessError during installation of environment 

### ISSUE THREAD

**Issue by AlcuZan** [pre-commit/pre-commit#2877]
### search you tried in the issue tracker

An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Manuel(Z)-CarbonFree\\.cache\\pre-commit\\repo0rxcuxqe\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save') 

### describe your issue

When trying to make a commit after installing pre-commit, I get a CalledProcessError that tells me a command was either misspelled or  could not be found (in German because my system language is German). I suspect that this might have something to do with my user folder name containing `()` ? I can't change that because it's a company account.

### pre-commit --version

pre-commit 3.3.1

### .pre-commit-config.yaml

```yaml
default_stages: [commit]
repos:
  - repo: https://github.com/milin/giticket
    rev: v1.3
    hooks:
      - id: giticket
        args: ['--mode=regex_match', '--regex=(?:\D|^)(\d+)(?=\D*$)', '--format={commit_msg} (#{ticket})']
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet dotnet-format --include
  - repo: local
    hooks:
      - id: swagger-gen
        name: swagger-codegen
        language: system
        pass_filenames: false
        entry: npm run run:codegen --prefix src/Web/Client/
```

### version information

```
pre-commit version: 3.3.1
git --version: git version 2.39.0.windows.2
sys.version:
    3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
sys.executable: C:\Python311\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Manuel(Z)-CarbonFree\\.cache\\pre-commit\\repo0rxcuxqe\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
stdout: (none)
stderr:
    Der Befehl "C:\Users\Manuel" ist entweder falsch geschrieben oder
    konnte nicht gefunden werden.
```

```
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Python311\Lib\site-packages\pre_commit\main.py", line 386, in main
    return hook_impl(
           ^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pre_commit\commands\hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pre_commit\commands\run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:\Python311\Lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "C:\Python311\Lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "C:\Python311\Lib\site-packages\pre_commit\languages\node.py", line 99, in install_environment
    lang_base.setup_cmd(prefix, local_install_cmd)
  File "C:\Python311\Lib\site-packages\pre_commit\lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Python311\Lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\Manuel(Z)-CarbonFree\\.cache\\pre-commit\\repo0rxcuxqe\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
stdout: (none)
stderr:
    Der Befehl "C:\Users\Manuel" ist entweder falsch geschrieben oder
    konnte nicht gefunden werden.
```

**Comment by asottile** [comment]
yeah I would strongly suggest not having weird characters in paths on windows.  npm does not handle that well and there's nothing pre-commit can do about it

**Comment by AlcuZan** [comment]
I understand, thanks for the quick response. I will talk to our admin and see if renaming is possible.

**Comment by AlcuZan** [comment]
So I asked our admin and renaming is not possible. Can I change the location of the .cache folder? I think that would fix it. 
Unfortunately I don't understand this description: https://pre-commit.com/#managing-ci-caches

Where do I need to set PRE_COMMIT_HOME ?

**Comment by AlcuZan** [comment]
I fixed it by changing the location of the .cache folder.
