### ISSUE TITLE
pre-commit autoupdate fails for git version 2.20.1

### ISSUE THREAD

**Issue by rr-manoj-dobbali** [pre-commit/pre-commit#2898]
### search you tried in the issue tracker

auto update, partial clone

### describe your issue

I updated `pre-commit` to `3.3.2` and `pre-commit autoupdate` started failing with the following message. 

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', '-c', 'core.useBuiltinFSMonitor=false', '-C', '/tmp/tmpcqmn44vq', 'fetch', 'origin', 'HEAD', '--quiet', '--filter=blob:none', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: --filter can only be used with the remote configured in core.partialClone
Check the log at /home/sagemaker-user/.cache/pre-commit/pre-commit.log
```

This could be because partialclone feature has been introduced with git version 2.40.1 but I am using git version 2.20.1 which cannot be upgraded. 

### pre-commit --version

pre-commit 3.3.2

### .pre-commit-config.yaml

```yaml
default_stages: [push]
exclude: ^research/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: check-merge-conflict
        stages: [commit]
      - id: no-commit-to-branch
        args: [-b, main]
      - id: detect-private-key
        stages: [commit]


  - repo: local
    hooks:
      - id: commitizen
        name: commitizen
        stages: [commit-msg]
        language: system
        entry: poetry run cz check --commit-msg-file
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
### version information


pre-commit version: 3.3.2
git --version: git version 2.20.1
sys.version:
    3.8.8 (default, Mar 31 2021, 12:29:49) 
    [GCC 8.3.0]
sys.executable: /home/sagemaker-user/text-classifier/venv/text-classifier-wQJB482L-py3.8/bin/python
os.name: posix
sys.platform: linux


### error information


An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', '-c', 'core.useBuiltinFSMonitor=false', '-C', '/tmp/tmpcqmn44vq', 'fetch', 'origin', 'HEAD', '--quiet', '--filter=blob:none', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: --filter can only be used with the remote configured in core.partialClone


Traceback (most recent call last):
  File "/home/sagemaker-user/text-classifier/venv/text-classifier-wQJB482L-py3.8/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/sagemaker-user/text-classifier/venv/text-classifier-wQJB482L-py3.8/lib/python3.8/site-packages/pre_commit/main.py", line 374, in main
    return autoupdate(
  File "/home/sagemaker-user/text-classifier/venv/text-classifier-wQJB482L-py3.8/lib/python3.8/site-packages/pre_commit/commands/autoupdate.py", line 194, in autoupdate
    i, old, new = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sagemaker-user/text-classifier/venv/text-classifier-wQJB482L-py3.8/lib/python3.8/site-packages/pre_commit/commands/autoupdate.py", line 111, in _update_one
    new = old.update(tags_only=tags_only, freeze=freeze)
  File "/home/sagemaker-user/text-classifier/venv/text-classifier-wQJB482L-py3.8/lib/python3.8/site-packages/pre_commit/commands/autoupdate.py", line 50, in update
    cmd_output_b(
  File "/home/sagemaker-user/text-classifier/venv/text-classifier-wQJB482L-py3.8/lib/python3.8/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'core.useBuiltinFSMonitor=false', '-C', '/tmp/tmpcqmn44vq', 'fetch', 'origin', 'HEAD', '--quiet', '--filter=blob:none', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: --filter can only be used with the remote configured in core.partialClone
```

**Comment by asottile** [comment]
it should work all the way back to 2.17 -- there must be something else to this.  it definitely doesn't require 2.40 because I'm using 2.34

**Comment by rr-manoj-dobbali** [comment]
I tried to use other version of `pre-commit` too with git version at 2.20.1. `pre-commit` versions until `3.2.2` do not throw this error. [This change of blobless clone for faster autoupdate ](https://github.com/pre-commit/pre-commit/pull/2859/files) in 3.3.0 seem to be creating the problem

**Comment by asottile** [comment]
yes obviously that is the change -- but you probably need to look into why your version of git is broken and/or if there's a way around it.  2.20 is fairly old (5+ years) fwiw

**Comment by rr-manoj-dobbali** [comment]
I understand that git 2.20 is old and using updated version of git with pre-commit 3.3.2 works. 

> it should work all the way back to 2.17

I don't think this is the case since latest version is not working with git 2.20

**Comment by asottile** [comment]
ok to be clear I don't care about 5 year old git and if you do either figure out how to make it work send send a patch or use an older version

**Comment by exhuma** [comment]
I ran into this as well on an older machine. For anyone running into this issue, here's a simple workaround if you have access to docker: Run the image with the project mounted as volume and run the command inside the container:

```bash 
# Setting the user is needed to ensure that we have proper permissions when modifying the files.
# We add "--rm" because we don't need to keep the container around
docker run --rm -it -u $(id -u) -v $(pwd):/workspace python:3.11 bash
```

Inside the container:

```bash
cd /workspace/
python3 -m venv /tmp/env
/tmp/env/bin/pip install pre-commit
# The default HOME is "/" for this image and that won't work with a non-root user-id.
# As this is a throwaway-container, we can safely set it to "/tmp".
HOME=/tmp /tmp/env/bin/pre-commit autoupdate
```
