### ISSUE TITLE
darker pre-commit hook seems to ignore configuration in pyproject.toml

### ISSUE THREAD

**Issue by dwt** [pre-commit/pre-commit#2909]
### search you tried in the issue tracker

darker pyproject.toml, black pyproject.toml, pyproject.toml

### describe your issue

I have configuration for a darker hook like this:

```yaml
  - repo: https://github.com/akaihola/darker
    rev: 1.7.1
    hooks:
      - id: darker
        args: [ --skip-string-normalization ]

```

and a pyproject.toml like this:

```toml
[tool.darker]
line-length = 120
skip-string-normalization = true
```

However running `pre-commit` it did not honor the line length setting in `pyproject.toml`.

Reading the documentation and other bug reports here, it seems this ought to work.

Is this an issue in `pre-commit`, perhaps something to do with the fact that the pre-commit hook acts directly on the files that are part of the commit and therefore ignores the `pyproject.toml`?

Or is this a bug in darker that I need to file there?

Changing the pre-commit hook to include the setting does seem to be a workaround. I.e.:

```yaml
  - repo: https://github.com/akaihola/darker
    rev: 1.7.1
    hooks:
      - id: darker
        args: [ --skip-string-normalization , --line-length=120 ]
```

### pre-commit --version

3.3.3

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: check-added-large-files

  - repo: https://github.com/akaihola/darker
    rev: 1.7.1
    hooks:
      - id: darker
        args: [ --skip-string-normalization , --line-length=120 ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.274"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
```

### version information

```
pre-commit version: 2.18.1
git --version: git version 2.32.0 (Apple Git-132)
sys.version:
    3.10.4 (main, Apr 26 2022, 19:36:29) [Clang 13.1.6 (clang-1316.0.21.2)]
sys.executable: /opt/homebrew/Cellar/pre-commit/2.18.1/libexec/bin/python3.10
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/Cellar/pre-commit/2.18.1/libexec/bin/python3.10', '-mvirtualenv', '/Users/dwt/.cache/pre-commit/repoz4zot7kc/py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/main.py", line 371, in main
    return run(args.config, store, args)
  File "/opt/homebrew/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 221, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/languages/python.py", line 202, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/opt/homebrew/Cellar/pre-commit/2.18.1/libexec/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/pre-commit/2.18.1/libexec/bin/python3.10', '-mvirtualenv', '/Users/dwt/.cache/pre-commit/repoz4zot7kc/py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)
```

**Comment by dwt** [comment]
Not sure what the error log is about, it may be around from some earlier error?

**Comment by asottile** [comment]
pre-commit just runs tools, this isn't a pre-commit problem

**Comment by dwt** [comment]
@asottile So you would agree that this should work?

**Comment by asottile** [comment]
I have no idea. I don't use or maintain darker. I just know this isn't a pre-commit problem
