### ISSUE TITLE
Error while running pre-commit hook

### ISSUE THREAD

**Issue by KarishmaDamania** [pre-commit/pre-commit#2926]
### search you tried in the issue tracker

database

### describe your issue

This for creating a python cdk project and hence the pre-commit is running within a virtual environment. All the requirements including pre-commit have been installed within the virtual environment

Getting this error:
An unexpected error has occurred: OperationalError: unable to open database file
Failed to write to log at /Users/pguindon/.cache/pre-commit/pre-commit.log
### version information
```
pre-commit version: 2.16.0
sys.version:
  3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]
sys.executable: /Users/pguindon/Documents/test_cdk_python/test/.venv/bin/python3.11
os.name: posix
sys.platform: darwin
```
### error information
```
An unexpected error has occurred: OperationalError: unable to open database file
```
```
Traceback (most recent call last):
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/error_handler.py", line 65, in error_handler
  yield
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/main.py", line 368, in main
  return hook_impl(
      ^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
  return retv | run(config, store, ns)
         ^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/commands/run.py", line 404, in run
  for hook in all_hooks(config, store)
        ^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/repository.py", line 228, in all_hooks
  return tuple(
      ^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/repository.py", line 231, in <genexpr>
  for hook in _repository_hooks(repo, store, root_config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/repository.py", line 206, in _repository_hooks
  return _cloned_repository_hooks(repo_config, store, root_config)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/repository.py", line 172, in _cloned_repository_hooks
  manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
                 ^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/store.py", line 187, in clone
  return self._new_repo(repo, ref, deps, clone_strategy)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/store.py", line 131, in _new_repo
  result = _get_result()
       ^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/store.py", line 124, in _get_result
  with self.connect() as db:
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
  return next(self.gen)
      ^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test/.venv/lib/python3.11/site-packages/pre_commit/store.py", line 101, in connect
  with contextlib.closing(sqlite3.connect(db_path)) as db:
              ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
```

### pre-commit --version

pre-commit v3.3.3

### .pre-commit-config.yaml

```yaml
default_stages: [commit, manual]
exclude: '^node_modules/'
repos:
  # -------------------------------- SECURITY --------------------------------

  - repo: https://github.com/bridgecrewio/checkov
    rev: "2.3.289"
    hooks:
      - id: checkov
        name: Checkov
        description: This hook runs checkov.
        entry: checkov -d . --config-file checkov.yaml
        pass_filenames: false
        always_run: false
        files: \.json$
        require_serial: true

  # Scans Python code for potential security issues.
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit

  # Scans for secrets, such as API keys, in the codebase.
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: .*/tests/.*

  # -------------------------------- FORMATTING & MISC --------------------------------

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Checks JSON files for formatting issues.
      - id: check-json
      # Checks for filename case conflicts on case-insensitive filesystems.
      - id: check-case-conflict
      # Ensures there are no trailing whitespaces in files.
      - id: trailing-whitespace
      # Fixes mixed line endings and enforces LF line endings.
      - id: mixed-line-ending
        args: [--fix=lf]
      # Fixes byte order marker (BOM) in files.
      - id: fix-byte-order-marker
      # Prevents accidental commit of merge conflicts.
      - id: check-merge-conflict
      # Detects the presence of private keys in the repository.
      - id: detect-private-key
      # Detects AWS credentials in files.
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials



  # Formats YAML, JSON, and Markdown files using Prettier.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        files: .*\.(ya?ml|json|md)$
        exclude: (?x)^(
          .*node_modules/.*|
          .pre-commit-config.yaml|
          mkdocs.yml|
          cdk.json |
          README.md
          )$


  # -------------------------------- PYTHON FORMATTING --------------------------------

  # Formats Python code using the black code style.
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--line-length=120"]


  # Performs static analysis and checks Python code against coding standards and guidelines.
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        args: ["--max-line-length=160", "--ignore=F401"]


  # Reorders Python imports to follow a consistent style.
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]

  # Upgrades Python syntax to newer versions.
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  # Adds trailing commas to Python code.
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  # Performs static type checking for Python code.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        verbose: true
        args:
          ["--install-types", "--non-interactive", "--ignore-missing-imports"]

  # -------------------------------- TESTING --------------------------------

  # Runs pytest before committing
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: copyright
        name: copyright
        entry: ./copyright.sh
        always_run: true
        language: system
        pass_filenames: true
        verbose: true
        exclude_types:
          - gitignore
        exclude: |
            (?x)^(
                .*/node_modules/\.$|
                .*\.json$|
                .*/__init__\.py$|
                .*\.DS_Store$|
                .gitdefender|
                checkov.yaml|
                requirements.in|
                requirements.txt|
                .nvmrc|
                .pre-commit-config.yaml|
                path/to/file2.py|
                path/to/file3.py
            )$
```

**Comment by asottile** [comment]
your error message mismatches the version from the `--version`  which is a little weird -- are you sure you don't have a really old broken install somewhere?

also what does ` ls -ald ~ ~/.cache ~/.cache/pre-commit ~/.cache/pre-commit/*` give you?

**Comment by KarishmaDamania** [comment]
Yes my mistake sorry! i was using pre-commit 2.16.0 when i received this

An unexpected error has occurred: OperationalError: unable to open database file
Failed to write to log at /Users/pguindon/.cache/pre-commit/pre-commit.log

this is part of the error

**Comment by asottile** [comment]
can you show the exact output of the command? and can you try upgrading whatever old pre-commit you have to see if that fixes it?

**Comment by KarishmaDamania** [comment]
installed the new version,

this is the output of the command:

An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '/Users/pguindon/.cache/pre-commit/.lock'
Failed to write to log at /Users/pguindon/.cache/pre-commit/pre-commit.log
### version information
```
pre-commit version: 2.16.0
sys.version:
  3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]
sys.executable: /Users/pguindon/Documents/test_cdk_python/test11/.venv/bin/python3.11
os.name: posix
sys.platform: darwin
```
### error information
```
An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '/Users/pguindon/.cache/pre-commit/.lock'
```
```
Traceback (most recent call last):
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/error_handler.py", line 65, in error_handler
  yield
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/main.py", line 368, in main
  return hook_impl(
      ^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/commands/hook_impl.py", line 237, in hook_impl
  return retv | run(config, store, ns)
         ^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/commands/run.py", line 404, in run
  for hook in all_hooks(config, store)
        ^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/repository.py", line 228, in all_hooks
  return tuple(
      ^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/repository.py", line 231, in <genexpr>
  for hook in _repository_hooks(repo, store, root_config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/repository.py", line 206, in _repository_hooks
  return _cloned_repository_hooks(repo_config, store, root_config)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/repository.py", line 172, in _cloned_repository_hooks
  manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
                 ^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/store.py", line 187, in clone
  return self._new_repo(repo, ref, deps, clone_strategy)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/store.py", line 134, in _new_repo
  with self.exclusive_lock():
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
  return next(self.gen)
      ^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/store.py", line 89, in exclusive_lock
  with file_lock.lock(os.path.join(self.directory, '.lock'), blocked_cb):
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
  return next(self.gen)
      ^^^^^^^^^^^^^^
 File "/Users/pguindon/Documents/test_cdk_python/test11/.venv/lib/python3.11/site-packages/pre_commit/file_lock.py", line 74, in lock
  with open(path, 'a+') as f:
     ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/Users/pguindon/.cache/pre-commit/.lock'
```
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
pguindon@b0be83459b62 test_cdk_python % ls -ald ~ ~/.cache ~/.cache/pre-commit ~/.cache/pre-commit/*
drwxr-x---+ 61 pguindon staff  1952 14 Jul 09:16 /Users/pguindon
drwxr-xr-x  3 root   staff   96 12 Jul 17:29 /Users/pguindon/.cache
drwxr-xr-x  5 root   staff  160 14 Jul 09:16 /Users/pguindon/.cache/pre-commit
-rw-r--r--  1 root   staff  109 12 Jul 17:29 /Users/pguindon/.cache/pre-commit/README
-rw-r--r--  1 root   staff 20480 14 Jul 09:16 /Users/pguindon/.cache/pre-commit/db.db

**Comment by asottile** [comment]
your home directory has a bunch of paths owned by `root` -- you must have run `sudo pre-commit` at some point which you should **NEVER** do.  randomly running things as root is how you break your machine

you need to clean up your mess, this isn't a pre-commit problem
