### ISSUE TITLE
Failed to write to log

### ISSUE THREAD

**Issue by dshengChen** [pre-commit/pre-commit#2944]
### search you tried in the issue tracker

Failed to write to log

### describe your issue

It`s my first time try to use pre-commit, and  detailed install information is:
```shell
(base) ➜  cmake_test git:(master) ✗ python --version
Python 3.8.12
(base) ➜  cmake_test git:(master) ✗ pre-commit --version
pre-commit 3.3.3
```

and my error infomation is:
```shell
(base) ➜  cmake_test git:(master) ✗ git commit -m "xx"
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/pocc/pre-commit-hooks')
==> At key: hooks
==> At Hook(id=MISSING)
=====> Missing required key: id
Failed to write to log at /Users/chendongsheng/.cache/pre-commit/pre-commit.log
### version information


pre-commit version: 3.3.3
git --version: git version 2.33.1
sys.version:
    3.8.12 (default, Oct 12 2021, 06:23:56) 
    [Clang 10.0.0 ]
sys.executable: /Users/chendongsheng/opt/anaconda3/bin/python
os.name: posix
sys.platform: darwin


### error information


An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/pocc/pre-commit-hooks')
==> At key: hooks
==> At Hook(id=MISSING)
=====> Missing required key: id


Traceback (most recent call last):
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/pre_commit/main.py", line 386, in main
    return hook_impl(
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/pre_commit/commands/hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/pre_commit/commands/run.py", line 422, in run
    config = load_config(config_file)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 410, in load_from_filename
    validate(data, schema)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 73, in _check_required
    _check_optional(self, dct)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 79, in check_fn
    validate(val, self.schema)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 272, in check
    validate(val, self.of)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 106, in _check_conditional
    inner(self, dct)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 73, in _check_required
    _check_optional(self, dct)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 79, in check_fn
    validate(val, self.schema)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 272, in check
    validate(val, self.of)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 72, in _check_required
    _require_key(self, dct)
  File "/Users/chendongsheng/opt/anaconda3/lib/python3.8/site-packages/cfgv.py", line 68, in _require_key
    raise ValidationError(f'Missing required key: {self.key}')
pre_commit.clientlib.InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/pocc/pre-commit-hooks')
==> At key: hooks
==> At Hook(id=MISSING)
=====> Missing required key: id
```

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - rev: v1.5.0  # Use the ref you want to point at
      - id: clang-format
        args: [--style=Google]
      - id: clang-tidy
      - id: oclint
      - id: uncrustify
      - id: cppcheck
      - id: cpplint
      - id: include-what-you-use
```

### ~/.cache/pre-commit/pre-commit.log (if present)

There is no such file.

**Comment by asottile** [comment]
it shows you the log directly if it failed to write it -- usually due to bad permissions.  try `ls -al ~ ~/.cache ~/.cache/pre-commit` and probably one of those is owned by root when it should not be.  you probably used `sudo` when you shouldn't have (you should never use it with `pre-commit` for instance)

**Comment by dshengChen** [comment]
@asottile 
Thanks a lot, I fixed it by deleting the whole folder.
