### ISSUE TITLE
Installing environment for black fails

### ISSUE THREAD

**Issue by fleimgruber** [pre-commit/pre-commit#2947]
### search you tried in the issue tracker

"object has no attribute 'startswith'"

### describe your issue

I ran

```
poetry run pre-commit run
```

I expected pre-commit hook results, but instead saw

```
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\user\\dev\\project\\.venv\\Scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\user\\.cache\\pre-commit\\repo2xj7w9wp\\py_env-python3.10')
return code: 1
stdout:
    AttributeError: 'NoneType' object has no attribute 'startswith'
stderr: (none)
Check the log at C:\Users\user\.cache\pre-commit\pre-commit.log
```

**Additional information**

Using pyenv-win for Python version management. Using Poetry for project management. Installed pre-commit with Poetry from activated venv:
```
pyenv local 3.10.9
python -m venv .venv
.\.venv\Scripts\Activate.ps1
poetry install
```

Since the error shows the argument `C:\\Users\\user\\.cache\\pre-commit\\repo2xj7w9wp\\py_env-python3.10` I checked to see its contents and found that it does not even exist, so maybe this has to do with using `pyenv`?

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        language_version: python3.10
```

### version information

```
pre-commit version: 3.3.3
git --version: git version 2.35.1.windows.2
sys.version:
    3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
sys.executable: C:\Users\user\dev\project\.venv\Scripts\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\user\\dev\\project\\.venv\\Scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\user\\.cache\\pre-commit\\repo2xj7w9wp\\py_env-python3.10')
return code: 1
stdout:
    AttributeError: 'NoneType' object has no attribute 'startswith'
stderr: (none)
```

```
Traceback (most recent call last):
  File "C:\Users\user\dev\project\.venv\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\user\dev\project\.venv\lib\site-packages\pre_commit\main.py", line 414, in main
    return run(args.config, store, args)
  File "C:\Users\user\dev\project\.venv\lib\site-packages\pre_commit\commands\run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:\Users\user\dev\project\.venv\lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\user\dev\project\.venv\lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "C:\Users\user\dev\project\.venv\lib\site-packages\pre_commit\languages\python.py", line 212, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "C:\Users\user\dev\project\.venv\lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\user\\dev\\project\\.venv\\Scripts\\python.exe', '-mvirtualenv', 'C:\\Users\\user\\.cache\\pre-commit\\repo2xj7w9wp\\py_env-python3.10')
return code: 1
stdout:
    AttributeError: 'NoneType' object has no attribute 'startswith'
stderr: (none)
```

**Comment by asottile** [comment]
please report it to virtualenv
