### ISSUE TITLE
Unable to find resource t64.exe in pip

### ISSUE THREAD

**Issue by Coni63** [pre-commit/pre-commit#2950]
### search you tried in the issue tracker

t64, pip, resource, distlib

### describe your issue

For a new project, I have:

- reinstalled python (3.11.4) completely
- updated pip with `get-pip.py` (23.2.1) + setuptools (68.0.0) + virtualenv (20.24.2)
- created a project and initiated a new git repo
- created a virtualenv (with and without poetry (1.5.1))
- installed pre-commit (3.3.3)
- made a minimal config `.pre-commit-config.yaml`
- run `pre-commit install` (OK)
- run `pre-commit run` (log attached)

I have tested several workaround such as removing poetry completely, downgrading pip (to 23.1.2), clean the cache from poetry, pip, pre-commit. Run from a virtual environment or not. I always have the issue. This was working few days ago on another project without trouble with the same versions. In the meantime, I've got a boot issue on my computer few days ago and I had to use a restore point. It may be linked however, with a full new installation, I continue to have the issue... 

I've found out that there is from time to time the exe files missing in the `/Lib/site-package/pip/_vendor/distlib` folder of the used environment using poetry (I don't get why) but it's OK with virtualenvs. When I've created a venv using poetry, I have added them manually. However, pre-commit uses poetry in the process and I think those files are also missing (hence the error message). Is there a way to check this ? or maybe another cache that I can clean (in case is uses cached corrupted `distlib` version) ?

Thanks for your support,

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
```

### version information

```
pre-commit version: 3.3.3
git --version: git version 2.33.1.windows.1
sys.version:
    3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
sys.executable: C:\Python311\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Nicolas\\.cache\\pre-commit\\reponz51pzta\\py_env-python3.11\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 2
stdout:
    Processing c:\users\nicolas\.cache\pre-commit\reponz51pzta
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting ruamel.yaml>=0.15 (from pre-commit-hooks==4.4.0)
      Obtaining dependency information for ruamel.yaml>=0.15 from https://files.pythonhosted.org/packages/d9/0e/2a05efa11ea33513fbdf4a2e2576fe94fd8fa5ad226dbb9c660886390974/ruamel.yaml-0.17.32-py3-none-any.whl.metadata
      Using cached ruamel.yaml-0.17.32-py3-none-any.whl.metadata (17 kB)
    Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml>=0.15->pre-commit-hooks==4.4.0)
      Using cached ruamel.yaml.clib-0.2.7-cp311-cp311-win_amd64.whl (101 kB)
    Using cached ruamel.yaml-0.17.32-py3-none-any.whl (112 kB)
    Building wheels for collected packages: pre-commit-hooks
      Building wheel for pre-commit-hooks (setup.py): started
      Building wheel for pre-commit-hooks (setup.py): finished with status 'done'
      Created wheel for pre-commit-hooks: filename=pre_commit_hooks-4.4.0-py2.py3-none-any.whl size=41291 sha256=fce4e6055e0674d373ffe66b29238eb26126cccb7a2da5888415386a5f55c637
      Stored in directory: G:\Temp\pip-ephem-wheel-cache-5n7hgddo\wheels\2c\16\d0\99f016047bdd8317e960cce6a53bf1e26a2754c06546c76675
    Successfully built pre-commit-hooks
    Installing collected packages: ruamel.yaml.clib, ruamel.yaml, pre-commit-hooks
stderr:
    ERROR: Exception:
    Traceback (most recent call last):
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
        status = run_func(*args)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
        return func(self, options, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\commands\install.py", line 452, in run
        installed = install_given_reqs(
                    ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\req\__init__.py", line 72, in install_given_reqs
        requirement.install(
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\req\req_install.py", line 807, in install
        install_wheel(
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 731, in install_wheel
        _install_wheel(
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 648, in _install_wheel
        generated_console_scripts = maker.make_multiple(scripts_to_generate)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_vendor\distlib\scripts.py", line 436, in make_multiple
        filenames.extend(self.make(specification, options))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 429, in make
        return super().make(specification, options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_vendor\distlib\scripts.py", line 425, in make
        self._make_script(entry, filenames, options=options)
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_vendor\distlib\scripts.py", line 325, in _make_script
        self._write_script(scriptnames, shebang, script, filenames, ext)
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_vendor\distlib\scripts.py", line 249, in _write_script
        launcher = self._get_launcher('t')
                   ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_vendor\distlib\scripts.py", line 404, in _get_launcher
        raise ValueError(msg)
    ValueError: Unable to find resource t64.exe in package pip._vendor.distlib
```

```
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Python311\Lib\site-packages\pre_commit\main.py", line 414, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pre_commit\commands\run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:\Python311\Lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "C:\Python311\Lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "C:\Python311\Lib\site-packages\pre_commit\languages\python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "C:\Python311\Lib\site-packages\pre_commit\lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Python311\Lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\Nicolas\\.cache\\pre-commit\\reponz51pzta\\py_env-python3.11\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 2
stdout:
    Processing c:\users\nicolas\.cache\pre-commit\reponz51pzta
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting ruamel.yaml>=0.15 (from pre-commit-hooks==4.4.0)
      Obtaining dependency information for ruamel.yaml>=0.15 from https://files.pythonhosted.org/packages/d9/0e/2a05efa11ea33513fbdf4a2e2576fe94fd8fa5ad226dbb9c660886390974/ruamel.yaml-0.17.32-py3-none-any.whl.metadata
      Using cached ruamel.yaml-0.17.32-py3-none-any.whl.metadata (17 kB)
    Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml>=0.15->pre-commit-hooks==4.4.0)
      Using cached ruamel.yaml.clib-0.2.7-cp311-cp311-win_amd64.whl (101 kB)
    Using cached ruamel.yaml-0.17.32-py3-none-any.whl (112 kB)
    Building wheels for collected packages: pre-commit-hooks
      Building wheel for pre-commit-hooks (setup.py): started
      Building wheel for pre-commit-hooks (setup.py): finished with status 'done'
      Created wheel for pre-commit-hooks: filename=pre_commit_hooks-4.4.0-py2.py3-none-any.whl size=41291 sha256=fce4e6055e0674d373ffe66b29238eb26126cccb7a2da5888415386a5f55c637
      Stored in directory: G:\Temp\pip-ephem-wheel-cache-5n7hgddo\wheels\2c\16\d0\99f016047bdd8317e960cce6a53bf1e26a2754c06546c76675
    Successfully built pre-commit-hooks
    Installing collected packages: ruamel.yaml.clib, ruamel.yaml, pre-commit-hooks
stderr:
    ERROR: Exception:
    Traceback (most recent call last):
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
        status = run_func(*args)
                 ^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
        return func(self, options, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\commands\install.py", line 452, in run
        installed = install_given_reqs(
                    ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\req\__init__.py", line 72, in install_given_reqs
        requirement.install(
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\req\req_install.py", line 807, in install
        install_wheel(
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 731, in install_wheel
        _install_wheel(
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 648, in _install_wheel
        generated_console_scripts = maker.make_multiple(scripts_to_generate)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_vendor\distlib\scripts.py", line 436, in make_multiple
        filenames.extend(self.make(specification, options))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 429, in make
        return super().make(specification, options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_vendor\distlib\scripts.py", line 425, in make
        self._make_script(entry, filenames, options=options)
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_vendor\distlib\scripts.py", line 325, in _make_script
        self._write_script(scriptnames, shebang, script, filenames, ext)
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_vendor\distlib\scripts.py", line 249, in _write_script
        launcher = self._get_launcher('t')
                   ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Nicolas\.cache\pre-commit\reponz51pzta\py_env-python3.11\Lib\site-packages\pip\_vendor\distlib\scripts.py", line 404, in _get_launcher
        raise ValueError(msg)
    ValueError: Unable to find resource t64.exe in package pip._vendor.distlib
```

**Comment by asottile** [comment]
please either pick stackoverflow or github issues -- not both
