### ISSUE TITLE
Preparing metadata (pyproject.toml): finished with status 'error'

### ISSUE THREAD

**Issue by lev-slinsen** [pre-commit/pre-commit#2953]
### search you tried in the issue tracker

Preparing metadata (pyproject.toml): finished with status 'error'

### describe your issue

First time running on this machine. Here's logs:
```
$ pre-commit run
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/username/.cache/pre-commit/patch1691546887-20998.
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /home/username/.cache/pre-commit/patch1691546887-20998.
An unexpected error has occurred: CalledProcessError: command: ('/home/username/.cache/pre-commit/repoza9rfi34/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/username/.cache/pre-commit/repoza9rfi34
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/username/.cache/pre-commit/repoza9rfi34/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
              main()
            File "/home/username/.cache/pre-commit/repoza9rfi34/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/username/.cache/pre-commit/repoza9rfi34/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-r1r8zk3d/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-r1r8zk3d/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 58, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /home/username/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
```

**Comment by asottile** [comment]
please search better. this is not a pre-commit problem
