### ISSUE TITLE
UNSAFE_LEGACY_RENEGOTIATION_DISABLED encountered during node environment setup

### ISSUE THREAD

**Issue by aclarknexient** [pre-commit/pre-commit#2956]
### search you tried in the issue tracker

I searched multiple times: node proxy, node environment, proxy ssl, node ssl, UNSAFE_LEGACY_RENEGOTIATION_DISABLED

### describe your issue

When running an eslint defined in package.json, we receive an error regarding UNSAFE_LEGACY_RENEGOTIATION_DISABLED during the nodeenv.py execution. We're using pre-commit via homebrew, and homebrew-supplied python as well.

Due to factors beyond my control, I've been asked to only enable the proxy during this hook setup/run. We're behind a corporate proxy, and if I add the standard ALL_PROXY/HTTPS_PROXY/https_proxy environment variables, then the node setup works, but then the rest of the (non pre-commit) developers tests and local environments fail.

Given the configuration where language = node, how do I add a proxy setting such that it is applied to nodeenv.py?

.pre-commit-hooks.yaml:
```yaml
-   id: lint-staged
    name: Lint Staged
    description: This hook lints the staged files.
    entry: lint-staged
    language: node
    types: [javascript]
    always_run: false
    require_serial: true
    additional_dependencies: ["lint-staged"]
    stages: [commit]
    verbose: true
```

Relevant section of package.json:
```
  "lint-staged": {
    "*.js": [
      "eslint --fix"
    ]
  },
```

Apologies for asking a question, I couldn't find a relevant answer in old/closed issues, nor in the documentation. My current thinking is to edit the .git/hooks/pre-commit file but I'm reluctant to do that because it will be overwritten during any upgrade.

### pre-commit --version

pre-commit 3.3.3

### .pre-commit-config.yaml

```yaml
repos:
- repo: https://github.com/REDACTED/Engage-Hooks
  rev: v1.9
  hooks:
  - id: lint-staged
default_install_hook_types:
  - pre-commit
  - post-commit
  - pre-push
  - commit-msg
```

### version information

```
pre-commit version: 3.3.3
git --version: git version 2.41.0
sys.version:
    3.11.4 (main, Jul 25 2023, 17:35:35) [Clang 14.0.0 (clang-1400.0.29.202)]
sys.executable: /opt/homebrew/Cellar/pre-commit/3.3.3/libexec/bin/python3.11
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/bin/python3.11', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/REDACTED/.cache/pre-commit/repolwn_zpmo/node_env-default')
return code: 1
stdout: (none)
stderr:
    /opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
      import pipes
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1286, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1332, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1281, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1041, in _send_output
        self.send(msg)
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 979, in send
        self.connect()
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1458, in connect
        self.sock = self._context.wrap_socket(self.sock,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
        return self.sslsocket_class._create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
        self.do_handshake()
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py", line 1540, in <module>
        main()
      File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py", line 1111, in main
        args.node = get_last_stable_node_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py", line 1044, in get_last_stable_node_version
        return _get_versions_json()[0]['version'].lstrip('v')
               ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py", line 1020, in _get_versions_json
        response = urlopen('%s/index.json' % src_base_url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py", line 640, in urlopen
        return urllib2.urlopen(req)
               ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
        response = self._open(req, data)
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
        result = func(*args)
                 ^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)>
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/pre_commit/main.py", line 386, in main
    return hook_impl(
           ^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/pre_commit/commands/hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/pre_commit/languages/node.py", line 89, in install_environment
    cmd_output_b(*cmd)
  File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/bin/python3.11', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/REDACTED/.cache/pre-commit/repolwn_zpmo/node_env-default')
return code: 1
stdout: (none)
stderr:
    /opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
      import pipes
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1286, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1332, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1281, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1041, in _send_output
        self.send(msg)
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 979, in send
        self.connect()
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1458, in connect
        self.sock = self._context.wrap_socket(self.sock,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
        return self.sslsocket_class._create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
        self.do_handshake()
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py", line 1540, in <module>
        main()
      File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py", line 1111, in main
        args.node = get_last_stable_node_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py", line 1044, in get_last_stable_node_version
        return _get_versions_json()[0]['version'].lstrip('v')
               ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py", line 1020, in _get_versions_json
        response = urlopen('%s/index.json' % src_base_url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/pre-commit/3.3.3/libexec/lib/python3.11/site-packages/nodeenv.py", line 640, in urlopen
        return urllib2.urlopen(req)
               ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
        response = self._open(req, data)
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
        result = func(*args)
                 ^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)>
```

**Comment by asottile** [comment]
sorry this isn't a pre-commit problem. if you want support for your corporate setup consider sett8ng up a support contact as I will not debug your work setup for free

**Comment by aclarknexient** [comment]
I wanted to say that I fully appreciate and respect your decision. My apologies for wasting your time.

I have a fix for this if you do encounter it again. It may be caused by a man-in-the-middle corporate proxy/firewall, or just old sites that don't support newer SSL libraries. I got this fix from: https://stackoverflow.com/a/72245418/2988388

1. First off you need to check what version of openssl your python install is using: `python3 -c 'import ssl; print(ssl.OPENSSL_VERSION)'`
2. Then compare that against openssl on your system: `openssl version` If they match, good.
3. Now determine where the openssl configuration is: `openssl version -d`
4. Now decide whether you want to edit the file referenced by the command in step 3.

### Editing the default openssl config file

Ensure that the following lines are present in the file, you may have to merge or add to sections that already exist.

```
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Options = UnsafeLegacyRenegotiation
```

### Creating a new openssl config file

Openssl relies on an environment variable to tell it which config to load. In the shell config file of your choice, add this:
```
export OPENSSL_CONF="$HOME/.local/etc/openssl.conf"
```

Now create that directory if it doesn't already exist: `mkdir -p ~/.local/etc`

Then edit `~/.local/etc/openssl.conf` and set its contents to the following:
```
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Options = UnsafeLegacyRenegotiation
```

Now close and reopen your terminals and/or IDEs, and the hooks should now work OK.

### Ansible Playbook

I created this Ansible playbook to install pre-commit and create the relevant openssl.conf:
```yaml
---
- name: Configure Basic Pre-Commit Environment
  hosts: localhost
  tasks:
    - name: Install pre-commit
      community.general.homebrew:
        name: pre-commit
        state: present

    - name: Run the pre-commit hook installer post-commit
      ansible.builtin.shell:
      args:
        executable: /bin/zsh
        cmd: pre-commit init-templatedir -t post-commit ~/.git-template
        creates: "{{ ansible_env.HOME }}/.git-template/hooks/post-commit"

    - name: Run the pre-commit hook installer pre-commit
      ansible.builtin.shell:
      args:
        executable: /bin/zsh
        cmd: pre-commit init-templatedir -t pre-commit ~/.git-template
        creates: "{{ ansible_env.HOME }}/.git-template/hooks/pre-commit"

    - name: Run the pre-commit hook installer pre-push
      ansible.builtin.shell:
      args:
        executable: /bin/zsh
        cmd: pre-commit init-templatedir -t pre-push ~/.git-template
        creates: "{{ ansible_env.HOME }}/.git-template/hooks/pre-push"

    - name: Run the pre-commit hook installer commit-msg
      ansible.builtin.shell:
      args:
        executable: /bin/zsh
        cmd: pre-commit init-templatedir -t commit-msg ~/.git-template
        creates: "{{ ansible_env.HOME }}/.git-template/hooks/commit-msg"

    # ZSHENV
    - name: Check that the .zshenv exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.zshenv"
      register: zshenv

    - name: Create zshenv, if it doesnt exist already
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.zshenv"
        owner: "{{ ansible_env.USER }}"
        group: "staff"
        mode: '0755'
        state: touch
      when: not zshenv.stat.exists

    - name: Export OPENSSL_CONF in zshenv
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshenv"
        line: 'export OPENSSL_CONF="$HOME/.local/etc/openssl.conf"'

    - name: Create ~/.local
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local"
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: "staff"
        mode: '0755'

    - name: Create ~/.local/etc
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/etc"
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: "staff"
        mode: '0755'

    - name: Create openssl.conf
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/etc/openssl.conf"
        owner: "{{ ansible_env.USER }}"
        group: "staff"
        mode: '0755'
        state: touch

    - name: Add lines to openssl.conf
      ansible.builtin.blockinfile:
        dest: "{{ ansible_env.HOME }}/.local/etc/openssl.conf"
        block: |
          openssl_conf = openssl_init

          [openssl_init]
          ssl_conf = ssl_sect

          [ssl_sect]
          system_default = system_default_sect

          [system_default_sect]
          Options = UnsafeLegacyRenegotiation

    # POTENTIALLY NOT NEEDED
    # - name: Upgrade requests and urllib3 via pip3
    #   ansible.builtin.pip:
    #     state: latest
    #     name:
    #       - requests
    #       - urllib3
```

I hope this helps someone in the future.
