### ISSUE TITLE
Failure when cloning private repository

### ISSUE THREAD

**Issue by Kmayikana** [pre-commit/pre-commit#2981]
### search you tried in the issue tracker

authenticating when cloning private repository

### describe your issue

Hi, I have some custom pre-commit hooks that reside in a central private repository that is part of my organisation. This is how part of my `pre-commit-config.yaml` looks like

```yaml
...
  - hooks:
      - args:
          - --input=metadata/metrics.yaml
        id: metrics-validate
    repo: https://github.com/ORGANISATION/hooks-repo.git
    # repo: git@github.com:ORGANISATION/hooks-repo.git  #<-- Alternative, if SSH cloning is preferred
    rev: master # hooks-repo doesn't provide tagged releases
```

When I run `pre-commit run --all-files` via `Makefile` command, I get this error when using `HTTPS`
```
[INFO] Initializing environment for https://github.com/ORGANISATION/hooks-repo.git.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: could not read Username for 'https://github.com/': No such device or address
Check the log at /mnt/jenkins-data/workspace/test/.cache/pre-commit/pre-commit.log
```
And this error when I use `SSH` I get this

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    No user exists for uid 1022
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
Check the log at /mnt/jenkins-data/workspace/test/.cache/pre-commit/pre-commit.log
```

I did try and set the `SSH_AUTH_SOCK` and `http_proxy https_proxy no_proxy` environment variables respectively but this did not really change the results. It is also worth noting that on my local machine this worked without issues, but when I try run `pre-commit` in Jenkins then I get issues.

What could I be missing, is it even possible to use private repositories for defining custom hooks?

### pre-commit --version

pre-commit 3.2.0

### .pre-commit-config.yaml

```yaml
default_language_version:
  python: python3
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0 # keep in sync with dev-requirements.in
    hooks:
      - id: isort
        args:
          - --resolve-all-configs
  - repo: https://github.com/psf/black
    rev: 22.3.0 # keep in sync with dev-requirements.in
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --ignore=E203,E501,W503
        additional_dependencies: [flake8-tidy-imports]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --no-strict-optional
        exclude: setup.py
        additional_dependencies:
          - types-mock
          - types-protobuf
          - types-retry
          - types-setuptools
          - types-tabulate
          - types-ujson
  - repo: https://github.com/nvuillam/npm-groovy-lint
    rev: v10.1.0
    hooks:
      - id: npm-groovy-lint
      - id: fix-npm-groovy-lint
      - id: format-npm-groovy-lint
  - hooks:
      - args:
          - --input=metadata/metrics.yaml
        id: mscli-validate
        verbose: true
    repo: https://github.com/ORGANISATION/hooks-repo.git
    # repo: git@github.com:ORGANISATION/hooks-repo.git  #<-- Alternative, if SSH cloning is preferred
    rev: master # hooks-repo doesn't provide tagged releases
```

### version information

```
pre-commit version: 3.3.3
git --version: git version 2.30.2
sys.version:
    3.8.15 (default, Dec  6 2022, 15:23:15) 
    [GCC 10.2.1 20210110]
sys.executable: /usr/local/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: could not read Username for 'https://github.com': No such device or address
```

```
Traceback (most recent call last):
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/store.py", line 202, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/store.py", line 184, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/store.py", line 199, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'protocol.version=2', 'fetch', 'origin', 'master', '--depth=1')
return code: 128
stdout: (none)
stderr:
    fatal: could not read Username for 'https://github.com': No such device or address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/commands/run.py", line 425, in run
    for hook in all_hooks(config, store)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 252, in all_hooks
    return tuple(
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 255, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 230, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 196, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/store.py", line 206, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/store.py", line 163, in _new_repo
    make_strategy(directory)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/store.py", line 204, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/store.py", line 176, in _complete_clone
    git_cmd('fetch', 'origin', '--tags')
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/store.py", line 199, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/mnt/jenkins-data/workspace/t-service_sd.ret-4112.pre-commit/.local/lib/python3.8/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: could not read Username for 'https://github.com': No such device or address
```

**Comment by asottile** [comment]
sorry but we don't provide corporate support for free -- there's nothing special pre-commit is doing here and you can debug by running `git clone {repo}` (use whatever you've set for `repo:` here) without `pre-commit` in your corporate CI setup
