### ISSUE TITLE
Windows es-lint not installable with generic error

### ISSUE THREAD

**Issue by GitRon** [pre-commit/pre-commit#2982]
### search you tried in the issue tracker

windows eslint

Found [this](https://github.com/pre-commit/pre-commit/issues/2402) and [this](https://github.com/pre-commit/pre-commit/issues/1681) issue but didn't help me solve the problem. 

### describe your issue

I try to install eslint:

```yml
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.48.0
    hooks:
      - id: eslint
        files: ^frontend/.*.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        args: [--config, ./frontend/.eslintrc.js, --ignore-path, ./frontend/.eslintignore]
        types: [file]
        stages: [push]
        additional_dependencies:
          - eslint@8.3.0
          - eslint-plugin-import@2.23.4
          - eslint-plugin-jsx-a11y@6.4.1
          - eslint-plugin-react@7.26.0
          - eslint-plugin-react-hooks@^4.3.0
          - eslint-plugin-simple-import-sort@^7.0.0
          - eslint-plugin-cypress@2.11.3
          - eslint-plugin-chai-friendly@0.7.1
          - "@typescript-eslint/eslint-plugin@4.33.0"
          - "@typescript-eslint/parser@4.33.0"
          - eslint-config-prettier@8.3.0
          - typescript@4.4.4
```

But I get always this error:

```bash
[INFO] Installing environment for https://github.com/pre-commit/mirrors-eslint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\ronny\\.cache\\pre-commit\\repomw36mp5r\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
stdout:

    up to date, audited 1 package in 3s

    found 0 vulnerabilities
stderr:
    npm WARN config dev Please use --include=dev instead.
    npm WARN config production Use `--omit=dev` instead.
Check the log at C:\Users\ronny\.cache\pre-commit\pre-commit.log
```

The `pre-commit.log` contains exactely the same errors. 

Other devs in my team can use the exact same setup with WSL, MacOS or UNIX.

I'm using latest PowerShell on Win11 64bit.

### pre-commit --version

3.3.3

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--check, --diff]
        stages: [push]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Update ruff version as well in .gitlab-ci.yml
    rev: 'v0.0.286'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.48.0
    hooks:
      - id: eslint
        files: ^frontend/.*.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        args: [--config, ./frontend/.eslintrc.js, --ignore-path, ./frontend/.eslintignore]
        types: [file]
        stages: [push]
        additional_dependencies:
          - eslint@8.3.0
          - eslint-plugin-import@2.23.4
          - eslint-plugin-jsx-a11y@6.4.1
          - eslint-plugin-react@7.26.0
          - eslint-plugin-react-hooks@^4.3.0
          - eslint-plugin-simple-import-sort@^7.0.0
          - eslint-plugin-cypress@2.11.3
          - eslint-plugin-chai-friendly@0.7.1
          - "@typescript-eslint/eslint-plugin@4.33.0"
          - "@typescript-eslint/parser@4.33.0"
          - eslint-config-prettier@8.3.0
          - typescript@4.4.4

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        files: ^(frontend|playwright-e2e)
        types_or: [javascript, jsx, ts, tsx, json, yaml]
        args: [--config, ./package.json, --ignore-path, .prettierignore]
        additional_dependencies:
          - prettier@2.8.8
        stages: [push]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: ['--pattern', '^^(?!(?:feature|hotfix|bugfix|refactor|merge)/[\w\d\-_#]+).*$']
        stages: [commit]
```

### version information

```
pre-commit version: 3.3.3
git --version: git version 2.42.0.windows.1
sys.version:
    3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
sys.executable: C:\Users\ronny\.virtualenvs\backend-EC29Mcw5\Scripts\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\ronny\\.cache\\pre-commit\\repomw36mp5r\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
stdout:
    
    up to date, audited 1 package in 3s
    
    found 0 vulnerabilities
stderr:
    npm WARN config dev Please use --include=dev instead.
    npm WARN config production Use `--omit=dev` instead.
```

```
Traceback (most recent call last):
  File "C:\Users\ronny\.virtualenvs\backend-EC29Mcw5\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\ronny\.virtualenvs\backend-EC29Mcw5\lib\site-packages\pre_commit\main.py", line 396, in main
    return install(
  File "C:\Users\ronny\.virtualenvs\backend-EC29Mcw5\lib\site-packages\pre_commit\commands\install_uninstall.py", line 140, in install
    install_hooks(config_file, store)
  File "C:\Users\ronny\.virtualenvs\backend-EC29Mcw5\lib\site-packages\pre_commit\commands\install_uninstall.py", line 146, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "C:\Users\ronny\.virtualenvs\backend-EC29Mcw5\lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\ronny\.virtualenvs\backend-EC29Mcw5\lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "C:\Users\ronny\.virtualenvs\backend-EC29Mcw5\lib\site-packages\pre_commit\languages\node.py", line 99, in install_environment
    lang_base.setup_cmd(prefix, local_install_cmd)
  File "C:\Users\ronny\.virtualenvs\backend-EC29Mcw5\lib\site-packages\pre_commit\lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Users\ronny\.virtualenvs\backend-EC29Mcw5\lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\ronny\\.cache\\pre-commit\\repomw36mp5r\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
stdout:
    
    up to date, audited 1 package in 3s
    
    found 0 vulnerabilities
stderr:
    npm WARN config dev Please use --include=dev instead.
    npm WARN config production Use `--omit=dev` instead.
```

**Comment by asottile** [comment]
probably this: https://github.com/pre-commit/pre-commit/issues/2402#issuecomment-1133662353

**Comment by GitRon** [comment]
I looked at that, but I'm not using conda - so I have no idea how that could be the reason 😕
