### ISSUE TITLE
local node hook: npm ERR! could not determine executable to run

### ISSUE THREAD

**Issue by iainelder** [pre-commit/pre-commit#2992]
### search you tried in the issue tracker

"could not determine executable to run"

### describe your issue

I'm trying to run an local node hook. It's not working for me. Maybe I've misunderstood how it is supposed to work.

All I can find in the docs is this:

> The hook repository must have a `package.json`. It will be installed via `npm install .`. The installed package will provide an executable that will match the [entry](https://pre-commit.com/#hooks-entry) – usually through bin in package.json.

I don't see pre-commit doing the `npm install .` part.

Here's my `package.json`:

```json
{
  "name": "test",
  "description": "test",
  "version": "1.0.0",
  "type": "module",
  "dependencies": {},
  "devDependencies": {
    "remark-cli": "^11.0.0"
  }
}
```

Here's how I test:

```console
$ pre-commit clean
Cleaned /home/isme/.cache/pre-commit.
$ pre-commit run --all-files
[INFO] Initializing environment for local.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
remark...................................................................Failed
- hook id: remark
- exit code: 1

npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in: /home/isme/.npm/_logs/2023-09-06T09_36_58_693Z-debug-0.log
```

npm run log:

```text
0 verbose cli /home/isme/.cache/pre-commit/repocitzsm83/node_env-default/bin/node /home/isme/.cache/pre-commit/repocitzsm83/node_env-default/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@9.8.1
2 info using node@v20.6.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/isme/.cache/pre-commit/repocitzsm83/node_env-default/lib/node_modules/npm/npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/isme/tmp/tmp.2023-09-06.WDFoz2E6/pre-commit-test/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/isme/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/isme/.cache/pre-commit/repocitzsm83/node_env-default/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 10ms
17 timing npm:load:configload Completed in 10ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm exec remark --quiet --frail doc.md
22 verbose argv "exec" "--" "remark" "--quiet" "--frail" "doc.md"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/home/isme/.npm/_logs/2023-09-06T09_36_58_693Z-
26 verbose logfile /home/isme/.npm/_logs/2023-09-06T09_36_58_693Z-debug-0.log
27 timing npm:load:logFile Completed in 6ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 31ms
31 silly logfile start cleaning logs, removing 1 files
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 1ms
34 http fetch GET 200 https://registry.npmjs.org/remark 808ms (cache revalidated)
35 timing command:exec Completed in 856ms
36 verbose stack Error: could not determine executable to run
36 verbose stack     at getBinFromManifest (/home/isme/.cache/pre-commit/repocitzsm83/node_env-default/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
36 verbose stack     at exec (/home/isme/.cache/pre-commit/repocitzsm83/node_env-default/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:188:15)
36 verbose stack     at async module.exports (/home/isme/.cache/pre-commit/repocitzsm83/node_env-default/lib/node_modules/npm/lib/cli-entry.js:61:5)
37 verbose pkgid remark@14.0.3
38 verbose cwd /home/isme/tmp/tmp.2023-09-06.WDFoz2E6/pre-commit-test
39 verbose Linux 5.15.0-82-generic
40 verbose node v20.6.0
41 verbose npm  v9.8.1
42 error could not determine executable to run
43 verbose exit 1
44 timing npm Completed in 1204ms
45 verbose code 1
46 error A complete log of this run can be found in: /home/isme/.npm/_logs/2023-09-06T09_36_58_693Z-debug-0.log
```

If I run npm install myself then it works.

```console
$ npm install .

added 183 packages, and audited 184 packages in 919ms

77 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ pre-commit clean
Cleaned /home/isme/.cache/pre-commit.
$ pre-commit run --all-files
[INFO] Initializing environment for local.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
remark...................................................................Passed
```

I don't think I'm supposed to have to run the `npm install .` command because one of the selling points of pre-commit is that it handles this for me.

> If one of your developers doesn’t have node installed but modifies a JavaScript file, pre-commit automatically handles downloading and building node to run eslint without root.

What am I missing?

In case it helps, I've shared an example on [my own GitHub profile](https://github.com/iainelder/pre-commit-test/actions/runs/6095141763). You can clone it or check the Actions history.

### pre-commit --version

pre-commit 3.4.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: remark
        name: remark
        entry: npx remark --quiet --frail
        language: node
        types: [markdown]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

`~/.cache/pre-commit/pre-commit.log` is not present.

```console
$ ls ~/.cache/pre-commit/
db.db  README  repoh44x2aj8
```

**Comment by asottile** [comment]
it doesn't install your repo, it installs the remote repo (and a placeholder for local repos). pre-commit never installs the repository under test

**Comment by asottile** [comment]
the placeholder repo is essentially empty so you can use `additional_dependencies` to install things -- https://pre-commit.com/#repository-local-hooks

**Comment by iainelder** [comment]
Thanks for pointing that out. The node section doesn't mention `additional_dependencies`.

I tried to adapt the `ruby` example that uses `scss`.

I tried writing it like this:

```yaml
repos:
  - repo: local
    hooks:
      - id: remark
        name: remark
        entry: npx remark --quiet --frail
        language: node
        types: [markdown]
        additional_dependencies: [remark-cli]
```

I let pre-commit run for about 5 minutes before cancelling.

```console
$ pre-commit run --all-files
[INFO] Initializing environment for local:remark.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
^CInterrupted (^C): KeyboardInterrupt: 
Check the log at /home/isme/.cache/pre-commit/pre-commit.log
```

The pre-commit.log:

    ### version information
    
    ```
    pre-commit version: 3.4.0
    git --version: git version 2.42.0
    sys.version:
        3.8.10 (default, May 26 2023, 14:05:08) 
        [GCC 9.4.0]
    sys.executable: /home/isme/.local/pipx/venvs/pre-commit/bin/python
    os.name: posix
    sys.platform: linux
    ```
    
    ### error information
    
    ```
    Interrupted (^C): KeyboardInterrupt: 
    ```
    
    ```
    Traceback (most recent call last):
      File "/home/isme/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
        yield
      File "/home/isme/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/main.py", line 414, in main
        return run(args.config, store, args)
      File "/home/isme/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/commands/run.py", line 442, in run
        install_hook_envs(to_install, store)
      File "/home/isme/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
        _hook_install(hook)
      File "/home/isme/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/repository.py", line 95, in _hook_install
        lang.install_environment(
      File "/home/isme/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/languages/node.py", line 89, in install_environment
        cmd_output_b(*cmd)
      File "/home/isme/.local/pipx/venvs/pre-commit/lib/python3.8/site-packages/pre_commit/util.py", line 106, in cmd_output_b
        stdout_b, stderr_b = proc.communicate()
      File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/usr/lib/python3.8/subprocess.py", line 1868, in _communicate
        ready = selector.select(timeout)
      File "/usr/lib/python3.8/selectors.py", line 415, in select
        fd_event_list = self._selector.poll(timeout)
    KeyboardInterrupt
    ```
    
Does node support `additional_dependencies`?

**Comment by asottile** [comment]
it does, you can reproduce the same thing by running `npm install remark-cli`

**Comment by iainelder** [comment]
> you can reproduce the same thing by running `npm install remark-cli`

I'm confused again. I can't reproduce it.

When I run `npm install remark-cli` before `pre-commit`, yes, it works. When I use the `additional_properties` syntax as I showed above, `pre-commit` hangs.

**Comment by asottile** [comment]
it runs it in an isolated nodeenv -- perhaps you can try with that?

**Comment by iainelder** [comment]
Today it works! Yesterday I may have had a network lag longer than my patience.

Here's how I proved it to work.

Use [this config](https://github.com/pre-commit/pre-commit/issues/2992#issuecomment-1708598736) again.

Terminal 1: My Bash pid is 625197.

Terminal 2: Run execsnoop.

```bash
sudo execsnoop-bpfcc -t | tee snoop.txt
```

Terminal 1: Run pre-commit.

```console
$ pre-commit clean
Cleaned /home/isme/.cache/pre-commit.
$ pre-commit run --all-files
[INFO] Initializing environment for local:remark-cli.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
remark...................................................................Passed
```

execsnoop shows that pre-commit does indeed execute the `npm install` commands in the temporary environment.

pre-commit took about 17 seconds to run the remark command. That's about the same amount of time it took for me to install remark outside of pre-commit.

```text
TIME(s) PCOMM            PID    PPID   RET ARGS
14.875  pre-commit       630279 625197   0 /home/isme/.local/bin/pre-commit clean
15.023  uname            630280 630279   0 /usr/bin/uname -p
20.649  pre-commit       630287 625197   0 /home/isme/.local/bin/pre-commit run --all-files
20.803  uname            630288 630287   0 /usr/bin/uname -p
20.848  git              630289 630287   0 /usr/bin/git rev-parse --show-cdup
20.851  git              630290 630287   0 /usr/bin/git rev-parse --is-inside-git-dir
20.880  python           630291 630287   0 /home/isme/.local/pipx/venvs/pre-commit/bin/python -mnodeenv --prebuilt --clean-src /home/isme/.cache/pre-commit/repock81futo/node_env-default
21.009  uname            630292 630291   0 /usr/bin/uname -p
34.228  node             630295 630287   0 /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/node /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/npm install --dev --prod --ignore-prepublish --no-progress --no-save
34.597  node             630310 630287   0 /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/node /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/npm pack
35.046  node             630326 630287   0 /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/node /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/npm install -g /home/isme/.cache/pre-commit/repock81futo/pre_commit_placeholder_package-0.0.0.tgz remark-cli
36.795  node             630376 630287   0 /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/node --version
36.800  git              630377 630287   0 /usr/bin/git ls-files -z
36.806  git              630378 630287   0 /usr/bin/git diff --no-ext-diff --no-textconv --ignore-submodules
36.811  node             630379 630287   0 /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/node /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/npx remark --quiet --frail doc.md
37.225  sh               630397 630379   0 /usr/bin/sh -c remark --quiet --frail doc.md
37.226  remark           630398 630397   0 /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/remark --quiet --frail doc.md
37.226  node             630398 630397   0 /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/node /home/isme/.cache/pre-commit/repock81futo/node_env-default/bin/remark --quiet --frail doc.md
37.590  git              630417 630287   0 /usr/bin/git diff --no-ext-diff --no-textconv --ignore-submodules
```

So that all makes sense now. Thanks!

A final note for anyone else who tries this. To pin a node package version you need to use the same syntax as the `npm install` command uses:

```yaml
additional_dependencies: ["remark-cli@11.0.0"]
```

**Comment by haroon2946** [comment]
![student 1](https://github.com/pre-commit/pre-commit/assets/159703511/c8899677-cc78-4419-b3db-173b6076a50e)
![student 2](https://github.com/pre-commit/pre-commit/assets/159703511/1eff940e-530d-4dd2-9b5d-e585febf3d66)
![student 3](https://github.com/pre-commit/pre-commit/assets/159703511/4ac8bed2-5799-4e1c-93a1-ec712708d481)
npm package successfully updated but command prompt its error showing
npx haroon25_student_management_system

**Comment by haroon2946** [comment]
please guide and help
