### ISSUE TITLE
When git commit inside a submodule, repo becomes corrupted

### ISSUE THREAD

**Issue by kuso800t** [pre-commit/pre-commit#3032]
### search you tried in the issue tracker

unable to set up work tree using invalid config

### describe your issue

I have two repositories:

1. https://github.com/kuso800t/precommit-bug.git
2. https://github.com/kuso800t/precommit-bug-parent.git

The second one (2) contains the first (1) as a submodule.

Inside repository 1, there's a code:

```python
from subprocess import check_call
from tempfile import TemporaryDirectory

def test0():
    with TemporaryDirectory() as tmpdir:
        def git(*args):
            check_call(("git", *args), cwd=tmpdir)
        git("init")
        git("add", ".")
```

When I do the following:

```sh
git clone https://github.com/kuso800t/precommit-bug.git
cd precommit-bug
pre-commit install
git commit -a -m -
```

I don't encounter any problems. However, when I do:

```sh
git clone --recurse-submodules https://github.com/kuso800t/precommit-bug-parent.git
cd precommit-bug-parent/precommit-bug
git checkout main
pre-commit install
git commit -a -m -
```

I get the error message:

```
stderr:
    warning: core.bare and core.worktree do not make sense
    fatal: unable to set up work tree using invalid config
```

After this, the submodule repository becomes corrupted.

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        files: '\.py$'
        always_run: true
        pass_filenames: false
```

### version information

```
pre-commit version: 3.4.0
git --version: git version 2.39.2 (Apple Git-143)
sys.version:
    3.9.6 (default, Mar 10 2023, 20:16:38) 
    [Clang 14.0.3 (clang-1403.0.22.14.1)]
sys.executable: /Library/Developer/CommandLineTools/usr/bin/python3
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'diff', '--no-ext-diff', '--ignore-submodules', '--diff-filter=A', '--name-only', '-z')
return code: 128
stdout: (none)
stderr:
    warning: core.bare and core.worktree do not make sense
    fatal: unable to set up work tree using invalid config
```

```
Traceback (most recent call last):
  File "/Users/h2/Library/Python/3.9/lib/python/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/h2/Library/Python/3.9/lib/python/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
  File "/Users/h2/Library/Python/3.9/lib/python/site-packages/pre_commit/commands/run.py", line 420, in run
    exit_stack.enter_context(staged_files_only(store.directory))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 429, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/h2/Library/Python/3.9/lib/python/site-packages/pre_commit/staged_files_only.py", line 107, in staged_files_only
    with _intent_to_add_cleared(), _unstaged_changes_cleared(patch_dir):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/h2/Library/Python/3.9/lib/python/site-packages/pre_commit/staged_files_only.py", line 37, in _intent_to_add_cleared
    intent_to_add = git.intent_to_add_files()
  File "/Users/h2/Library/Python/3.9/lib/python/site-packages/pre_commit/git.py", line 147, in intent_to_add_files
    _, stdout, _ = cmd_output(
  File "/Users/h2/Library/Python/3.9/lib/python/site-packages/pre_commit/util.py", line 116, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
  File "/Users/h2/Library/Python/3.9/lib/python/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'diff', '--no-ext-diff', '--ignore-submodules', '--diff-filter=A', '--name-only', '-z')
return code: 128
stdout: (none)
stderr:
    warning: core.bare and core.worktree do not make sense
    fatal: unable to set up work tree using invalid config
```

**Comment by kuso800t** [comment]
thank you
