### ISSUE TITLE
Installation fails with unquoted dependency

### ISSUE THREAD

**Issue by lbittarello** [pre-commit/pre-commit#3039]
### search you tried in the issue tracker

is:issue conda not found

### describe your issue

I wasn't able to install the `flake8` hook. It currently pins Python below 3.12, which is not quoted [here](https://github.com/pre-commit/pre-commit/blob/5f4ed54cfea8db31a118714427bed5a6043a466f/pre_commit/languages/conda.py#L75). `pre-commit` ends up running `conda ... python<3.12 ...`, which doesn't work (for me), instead of `conda ... "python<3.12" ...`, which does.

I'm not sure if `pre-commit` is to blame, but a dumb fix was to add the line
```python
additional_dependencies = [
    (f'"{dependency}"' if ("<" in dependency) or (">" in dependency) else dependency)
    for dependency in additional_dependencies
]
```

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
ci:
  autoupdate_schedule: monthly
  autoupdate_skip_repos:
    - https://github.com/Quantco/pre-commit-mirrors-black
repos:
 - repo: https://github.com/Quantco/pre-commit-mirrors-black
   rev: 22.12.0
   hooks:
     - id: black-conda
       args:
         - --safe
         - --target-version=py38
 - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
   rev: 6.1.0
   hooks:
    - id: flake8-conda
      additional_dependencies: [
        -c,
        conda-forge,
        python<3.12,
        flake8-bugbear,
        flake8-builtins,
        flake8-comprehensions,
        flake8-docstrings,
        flake8-rst-docstrings,
        flake8-print,
        pep8-naming,
      ]
 - repo: https://github.com/Quantco/pre-commit-mirrors-isort
   rev: 5.12.0
   hooks:
    - id: isort-conda
      additional_dependencies: [-c, conda-forge, toml]
      args: ["--profile", "black"]
 - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
   rev: 1.5.1
   hooks:
    - id: mypy-conda
      additional_dependencies: [-c, conda-forge, types-setuptools>=57.4.0]
      args:
        - --allow-redefinition
        - --explicit-package-bases
        - --ignore-missing-imports
        - --namespace-packages
        - --scripts-are-modules
 - repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
   rev: 3.13.0
   hooks:
    - id: pyupgrade-conda
      args:
        - --py38-plus
 - repo: https://github.com/Quantco/pre-commit-mirrors-pre-commit-hooks
   rev: 4.4.0
   hooks:
    - id: trailing-whitespace-conda
    - id: end-of-file-fixer-conda
```

### version information

```
pre-commit version: 3.5.0
git --version: git version 2.29.2.windows.2
sys.version:
    3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]
sys.executable: C:\Programs\Python\envs\dev\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Programs\\Python\\condabin\\conda.BAT', 'install', '-p', 'C:\\Users\\lucab\\.cache\\pre-commit\\repo8mftpal5\\conda-default', '-c', 'conda-forge', 'python<3.12', 'flake8-bugbear', 'flake8-builtins', 'flake8-comprehensions', 'flake8-docstrings', 'flake8-rst-docstrings', 'flake8-print', 'pep8-naming')
return code: 1
stdout: (none)
stderr:
    The system cannot find the file specified.
```

```
Traceback (most recent call last):
  File "C:\Programs\Python\envs\dev\Lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Programs\Python\envs\dev\Lib\site-packages\pre_commit\main.py", line 414, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Python\envs\dev\Lib\site-packages\pre_commit\commands\run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:\Programs\Python\envs\dev\Lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "C:\Programs\Python\envs\dev\Lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "C:\Programs\Python\envs\dev\Lib\site-packages\pre_commit\languages\conda.py", line 77, in install_environment
    cmd_output_b(
  File "C:\Programs\Python\envs\dev\Lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Programs\\Python\\condabin\\conda.BAT', 'install', '-p', 'C:\\Users\\lucab\\.cache\\pre-commit\\repo8mftpal5\\conda-default', '-c', 'conda-forge', 'python<3.12', 'flake8-bugbear', 'flake8-builtins', 'flake8-comprehensions', 'flake8-docstrings', 'flake8-rst-docstrings', 'flake8-print', 'pep8-naming')
return code: 1
stdout: (none)
stderr:
    The system cannot find the file specified.
```

**Comment by asottile** [comment]
please report to conda -- probably their security contact as they aren't handling arguments safely
