### ISSUE TITLE
Fails to run with Python 3.12

### ISSUE THREAD

**Issue by makermelissa** [pre-commit/pre-commit#3041]
### search you tried in the issue tracker

is:issue 3.12 is:closed 

### describe your issue

I noticed GitHub actions switched over to Python 3.12 today. I was also able to reproduce the error on my Mac.

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.2
    hooks:
      - id: reuse
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.4
    hooks:
      - id: pylint
        name: pylint (library code)
        types: [python]
        args:
          - --disable=consider-using-f-string
        exclude: "^(docs/|examples/|tests/|setup.py$)"
      - id: pylint
        name: pylint (example code)
        description: Run pylint rules on "examples/*.py" files
        types: [python]
        files: "^examples/"
        args:
          - --disable=missing-docstring,invalid-name,consider-using-f-string,duplicate-code
      - id: pylint
        name: pylint (test code)
        description: Run pylint rules on "tests/*.py" files
        types: [python]
        files: "^tests/"
        args:
          - --disable=missing-docstring,consider-using-f-string,duplicate-code
```

### version information

```
pre-commit version: 3.5.0
git --version: git version 2.42.0
sys.version:
    3.12.0 (main, Oct  5 2023, 15:52:37) [Clang 14.0.3 (clang-1403.0.22.14.1)]
sys.executable: /usr/local/opt/python@3.12/bin/python3.12
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/melissa/.cache/pre-commit/repo9jh8ewxl/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/melissa/.cache/pre-commit/repo9jh8ewxl
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'error'
stderr:
      error: subprocess-exited-with-error

      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> [33 lines of output]
          Traceback (most recent call last):
            File "/Users/melissa/.cache/pre-commit/repo9jh8ewxl/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/Users/melissa/.cache/pre-commit/repo9jh8ewxl/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/melissa/.cache/pre-commit/repo9jh8ewxl/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
              backend = _build_backend()
                        ^^^^^^^^^^^^^^^^
            File "/Users/melissa/.cache/pre-commit/repo9jh8ewxl/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
              obj = import_module(mod_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^
            File "/usr/local/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
            File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
            File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
            File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
            File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
            File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
            File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
            File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
            File "<frozen importlib._bootstrap_external>", line 994, in exec_module
            File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
            File "/private/var/folders/85/7p5j71px72dct4n9wjfc53fr0000gn/T/pip-build-env-zzdoyuj3/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
              import setuptools.version
            File "/private/var/folders/85/7p5j71px72dct4n9wjfc53fr0000gn/T/pip-build-env-zzdoyuj3/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
              import pkg_resources
            File "/private/var/folders/85/7p5j71px72dct4n9wjfc53fr0000gn/T/pip-build-env-zzdoyuj3/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
              register_finder(pkgutil.ImpImporter, find_on_path)
                              ^^^^^^^^^^^^^^^^^^^
          AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/lib/python3.12/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/usr/local/lib/python3.12/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/lib/python3.12/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/usr/local/lib/python3.12/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/usr/local/lib/python3.12/site-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/melissa/.cache/pre-commit/repo9jh8ewxl/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/melissa/.cache/pre-commit/repo9jh8ewxl
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'error'
stderr:
      error: subprocess-exited-with-error

      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> [33 lines of output]
          Traceback (most recent call last):
            File "/Users/melissa/.cache/pre-commit/repo9jh8ewxl/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/Users/melissa/.cache/pre-commit/repo9jh8ewxl/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/melissa/.cache/pre-commit/repo9jh8ewxl/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
              backend = _build_backend()
                        ^^^^^^^^^^^^^^^^
            File "/Users/melissa/.cache/pre-commit/repo9jh8ewxl/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
              obj = import_module(mod_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^
            File "/usr/local/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
            File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
            File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
            File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
            File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
            File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
            File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
            File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
            File "<frozen importlib._bootstrap_external>", line 994, in exec_module
            File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
            File "/private/var/folders/85/7p5j71px72dct4n9wjfc53fr0000gn/T/pip-build-env-zzdoyuj3/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
              import setuptools.version
            File "/private/var/folders/85/7p5j71px72dct4n9wjfc53fr0000gn/T/pip-build-env-zzdoyuj3/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
              import pkg_resources
            File "/private/var/folders/85/7p5j71px72dct4n9wjfc53fr0000gn/T/pip-build-env-zzdoyuj3/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
              register_finder(pkgutil.ImpImporter, find_on_path)
                              ^^^^^^^^^^^^^^^^^^^
          AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by asottile** [comment]
you have a too-old version of virtualenv which is pulling in an old setuptools which did not support 3.12

**Comment by jepler** [comment]
Here's how to see that this is a problem with pylint 2.17.x with python 3.12, and not a problem with pre-commit:
```
$ docker run -it python:3.12 /bin/bash
# pip install git+https://github.com/pycqa/pylint@v2.17.4
```

Trying to dignose the problem locally was complicated by the fact that `pip install pylint==2.17.4` (from pypi) works, just installing from git+https does not.
