### ISSUE TITLE
Python 3.13: `module 'importlib.resources' has no attribute 'read_text'`

### ISSUE THREAD

**Issue by FelixSchwarz** [pre-commit/pre-commit#3053]
### search you tried in the issue tracker

read_text

### describe your issue

When running `pre-commit install` in a Python 3.13.0a1 environment, I get an attribute error because Python 3.13 removed the previously deprecated `read_text` function: https://docs.python.org/3.13/whatsnew/3.13.html#importlib

Context: Fedora starts rebuilding all of its Python packages with Python 3.13. These are currently test-rebuilds but I think Python 3.13 will be added to Fedora 41 sometime in Q2 2024: https://discussion.fedoraproject.org/t/f41-change-proposal-python-3-13-system-wide/92897

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.287
  hooks:
    - id: ruff
```

### version information

```
pre-commit version: 3.5.0
git --version: git version 2.41.0
sys.version:
    3.13.0a1 (main, Oct 16 2023, 00:00:00) [GCC 13.2.1 20231011 (Red Hat 13.2.1-4)]
sys.executable: /home/dev/fedora/borgbackup/upstream.git/venv.py313/bin/python3.13
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AttributeError: module 'importlib.resources' has no attribute 'read_text'
```

```
Traceback (most recent call last):
  File "/home/dev/fedora/borgbackup/upstream.git/venv.py313/lib64/python3.13/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/dev/fedora/borgbackup/upstream.git/venv.py313/lib64/python3.13/site-packages/pre_commit/main.py", line 396, in main
    return install(
           ^^^^^^^^
  File "/home/dev/fedora/borgbackup/upstream.git/venv.py313/lib64/python3.13/site-packages/pre_commit/commands/install_uninstall.py", line 131, in install
    _install_hook_script(
  File "/home/dev/fedora/borgbackup/upstream.git/venv.py313/lib64/python3.13/site-packages/pre_commit/commands/install_uninstall.py", line 93, in _install_hook_script
    contents = resource_text('hook-tmpl')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dev/fedora/borgbackup/upstream.git/venv.py313/lib64/python3.13/site-packages/pre_commit/util.py", line 39, in resource_text
    return importlib.resources.read_text('pre_commit.resources', filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib.resources' has no attribute 'read_text'
```

**Comment by asottile** [comment]
already fixed
