### ISSUE TITLE
`module 'pkgutil' has no attribute 'ImpImporter'` -  Fails to run on python3.12 pipx 

### ISSUE THREAD

**Issue by EXHades** [pre-commit/pre-commit#3054]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues/3041

### describe your issue

```bash
brew install pipx
pipx install pre-commit
cd project && pre-commit run -a
```

I try Updated `pip、setuptools、virtualenv、wheel` to the latest, **but still not working**

```bash
$(brew --prefix pipx)/libexec/bin/python3.12 -m pip list
# Package     Version
# ----------- -------
# argcomplete 0.0.0
# click       8.1.7
# packaging   23.2
# pip         23.3.1
# pipx        1.2.1
# protobuf    4.25.0
# setuptools  68.2.2
# userpath    1.9.1
# wheel       0.41.3

cd …/pipx/venvs/pre-commit/bin && ./python3.12 -m pip list
# Package      Version
# ------------ -------
# cfgv         3.4.0
# distlib      0.3.7
# filelock     3.13.1
# identify     2.5.31
# nodeenv      1.8.0
# pip          23.3.1
# platformdirs 3.11.0
# pre-commit   3.5.0
# PyYAML       6.0.1
# setuptools   68.2.2
# virtualenv   20.24.6
# wheel        0.41.3
```

### pre-commit --version

pre-commit 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500", "--enforce-all"]
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-yaml
      - id: check-json
      - id: check-toml
```

### version information

```bash
pre-commit version: 3.5.0
git --version: git version 2.42.1
sys.version:
    3.12.0 (main, Oct  2 2023, 12:03:24) [Clang 15.0.0 (clang-1500.0.40.1)]
sys.executable: ~/.local/share/pipx/venvs/pre-commit/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```bash
An unexpected error has occurred: CalledProcessError: command: ('~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 2
stdout: (none)
stderr:
    ERROR: Exception:
    Traceback (most recent call last):
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
        status = run_func(*args)
                 ^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
        return func(self, options, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 345, in run
        session = self.get_default_session(options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
        self._session = self.enter_context(self._build_session(options))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
        session = PipSession(
                  ^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/network/session.py", line 343, in __init__
        self.headers["User-Agent"] = user_agent()
                                     ^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/network/session.py", line 175, in user_agent
        setuptools_dist = get_default_environment().get_distribution("setuptools")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 188, in get_distribution
        return next(matches, None)
               ^^^^^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 183, in <genexpr>
        matches = (
                  ^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
        for dist in self._iter_distributions():
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
        for dist in finder.find_eggs(location):
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
        yield from self._find_eggs_in_dir(location)
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 111, in _find_eggs_in_dir
        from pip._vendor.pkg_resources import find_distributions
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
        register_finder(pkgutil.ImpImporter, find_on_path)
                        ^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

```bash
Traceback (most recent call last):
  File "~/.local/share/pipx/venvs/pre-commit/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "~/.local/share/pipx/venvs/pre-commit/lib/python3.12/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/share/pipx/venvs/pre-commit/lib/python3.12/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "~/.local/share/pipx/venvs/pre-commit/lib/python3.12/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "~/.local/share/pipx/venvs/pre-commit/lib/python3.12/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "~/.local/share/pipx/venvs/pre-commit/lib/python3.12/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "~/.local/share/pipx/venvs/pre-commit/lib/python3.12/site-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "~/.local/share/pipx/venvs/pre-commit/lib/python3.12/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 2
stdout: (none)
stderr:
    ERROR: Exception:
    Traceback (most recent call last):
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
        status = run_func(*args)
                 ^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
        return func(self, options, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 345, in run
        session = self.get_default_session(options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
        self._session = self.enter_context(self._build_session(options))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
        session = PipSession(
                  ^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/network/session.py", line 343, in __init__
        self.headers["User-Agent"] = user_agent()
                                     ^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/network/session.py", line 175, in user_agent
        setuptools_dist = get_default_environment().get_distribution("setuptools")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 188, in get_distribution
        return next(matches, None)
               ^^^^^^^^^^^^^^^^^^^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 183, in <genexpr>
        matches = (
                  ^
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
        for dist in self._iter_distributions():
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
        for dist in finder.find_eggs(location):
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 144, in find_eggs
        yield from self._find_eggs_in_dir(location)
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 111, in _find_eggs_in_dir
        from pip._vendor.pkg_resources import find_distributions
      File "~/.cache/pre-commit/repozva5ecs4/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
        register_finder(pkgutil.ImpImporter, find_on_path)
                        ^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

**Comment by asottile** [comment]
you found the duplicate, so do what it says

this is not a support forum for pipx
