### ISSUE TITLE
InvalidManifestError for black (while the manifest is seemingly fine)

### ISSUE THREAD

**Issue by kratsg** [pre-commit/pre-commit#3068]
### search you tried in the issue tracker

InvalidManifestError

### describe your issue

I ran pre-commit and I ran into an `InvalidManifestError` for `psf/black` even though the manifest's hooks passes the `pre-commit validate-manifest`.

```
~/testprecommit (master)$ tree ~/.cache/pre-commit
/Users/kratsg/.cache/pre-commit
├── README
└── db.db

0 directories, 2 files
~/testprecommit (master)$ pre-commit install --install-hooks
pre-commit installed at .git/hooks/pre-commit
[INFO] Initializing environment for https://github.com/psf/black.
An error has occurred: InvalidManifestError:
==> File /Users/kratsg/.cache/pre-commit/repomkn_zpx7/.pre-commit-hooks.yaml
==> At Hook(id='black')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
Check the log at /Users/kratsg/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: "23.11.0"
    hooks:
      - id: black-jupyter
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.39.1
sys.version:
    3.8.6 (default, Oct 28 2020, 19:59:21)
    [Clang 10.0.1 (clang-1001.0.46.4)]
sys.executable: /Users/kratsg/.pyenv/versions/3.8.6/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An error has occurred: InvalidManifestError:
==> File /Users/kratsg/.cache/pre-commit/repomkn_zpx7/.pre-commit-hooks.yaml
==> At Hook(id='black')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
```

```
Traceback (most recent call last):
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pre_commit/main.py", line 368, in main
    return install(
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pre_commit/commands/install_uninstall.py", line 140, in install
    install_hooks(config_file, store)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pre_commit/commands/install_uninstall.py", line 146, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pre_commit/repository.py", line 227, in all_hooks
    return tuple(
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pre_commit/repository.py", line 230, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pre_commit/repository.py", line 205, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pre_commit/repository.py", line 172, in _cloned_repository_hooks
    by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 411, in load_from_filename
    return apply_defaults(data, schema)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 410, in load_from_filename
    validate(data, schema)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 272, in check
    validate(val, self.of)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 364, in check_array_fn
    inner_check(val)
  File "/Users/kratsg/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cfgv.py", line 342, in check_one_of_fn
    raise ValidationError(
pre_commit.clientlib.InvalidManifestError:
==> File /Users/kratsg/.cache/pre-commit/repomkn_zpx7/.pre-commit-hooks.yaml
==> At Hook(id='black')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
```

**Comment by asottile** [comment]
you're using a very old pre-commit which does not understand the new stages names
