### ISSUE TITLE
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'

### ISSUE THREAD

**Issue by abdullzz** [pre-commit/pre-commit#3081]
### search you tried in the issue tracker

virtualenv, CPython2macOsFramework

### describe your issue

```
(venv) abdul@DESKTOP-UBCRCM7:/mnt/x/Abdul-Projects/git/clipboard-master$ pre-commit --version
pre-commit 3.5.0
```
```
(venv) abdul@DESKTOP-UBCRCM7:/mnt/x/Abdul-Projects/git/clipboard-master$ pre-commit 
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/abdul/.cache/pre-commit/patch1701507159-8000.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /home/abdul/.cache/pre-commit/patch1701507159-8000.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/abdul/.cache/pre-commit/repo6vf0d4uu/py_env-python3')
return code: 1
stdout:
    AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'
stderr: (none)
Check the log at /home/abdul/.cache/pre-commit/pre-commit.log
```
```
(venv) abdul@DESKTOP-UBCRCM7:~/.cache/pre-commit$ cat pre-commit.log 
### version information
pre-commit version: 3.5.0
git --version: git version 2.25.1
sys.version:
    3.8.10 (default, May 26 2023, 14:05:08)
    [GCC 9.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux

### error information

An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/abdul/.cache/pre-commit/repo6vf0d4uu/py_env-python3')
return code: 1
stdout:
    AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'
stderr: (none)
```

```
Traceback (most recent call last):
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/languages/python.py", line 212, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/abdul/.cache/pre-commit/repo6vf0d4uu/py_env-python3')
return code: 1
stdout:
    AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'
stderr: (none)
```

i can't figure out what's the problem with this

### pre-commit --version

pre-commit version: 3.5.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: '^venv/'
    -   id: end-of-file-fixer
        exclude: '^venv/'
    -   id: check-yaml
        exclude: '^venv/'
    -   id: debug-statements
        exclude: '^venv/'
    -   id: double-quote-string-fixer
        exclude: '^venv/'
    -   id: name-tests-test
        exclude: '^venv/'
    -   id: requirements-txt-fixer
        exclude: '^venv/'
```

### version information

```
pre-commit version: 3.5.0
git --version: git version 2.25.1
sys.version:
    3.8.10 (default, May 26 2023, 14:05:08)
    [GCC 9.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/abdul/.cache/pre-commit/repo6vf0d4uu/py_env-python3')
return code: 1
stdout:
    AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'
stderr: (none)
```

```
Traceback (most recent call last):
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/repository.py", line 95, in _hook_install
    lang.install_environment(
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/languages/python.py", line 212, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/home/abdul/.local/lib/python3.8/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/abdul/.cache/pre-commit/repo6vf0d4uu/py_env-python3')
return code: 1
stdout:
    AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'
stderr: (none)

**Comment by abdullzz** [comment]
running pre-commit with or without venv seems broken

**Comment by abdullzz** [comment]
also tried upgrading my pip and venv, nothing working

**Comment by abdullzz** [comment]
```
abdul@DESKTOP-UBCRCM7:/mnt/x/Abdul-Projects/git/clipboard-master$ python3 --version
nstall --upgrade virtualenPython 3.8.10
abdul@DESKTOP-UBCRCM7:/mnt/x/Abdul-Projects/git/clipboard-master$ pip3 install --upgrade virtualenv
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: virtualenv in /home/abdul/.local/lib/python3.8/site-packages (20.25.0)
Requirement already satisfied: distlib<1,>=0.3.7 in /home/abdul/.local/lib/python3.8/site-packages (from virtualenv) (0.3.7)
Requirement already satisfied: filelock<4,>=3.12.2 in /home/abdul/.local/lib/python3.8/site-packages (from virtualenv) (3.13.1)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /home/abdul/.local/lib/python3.8/site-packages (from virtualenv) (4.0.0)
DEPRECATION: distro-info 0.23ubuntu1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: python-debian 0.1.36ubuntu1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of python-debian or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
abdul@DESKTOP-UBCRCM7:/mnt/x/Abdul-Projects/git/clipboard-master$ pre-commit clean
Cleaned /home/abdul/.cache/pre-commit.
abdul@DESKTOP-UBCRCM7:/mnt/x/Abdul-Projects/git/clipboard-master$ pre-commit
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/abdul/.cache/pre-commit/patch1701507922-9412.
[INFO] Initializing environment for https://github.com/asottile/reorder-python-imports.
[INFO] Initializing environment for https://github.com/asottile/add-trailing-comma.
[INFO] Initializing environment for https://github.com/hhatto/autopep8.
[INFO] Installing environment for https://github.com/asottile/reorder-python-imports.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /home/abdul/.cache/pre-commit/patch1701507922-9412.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mvirtualenv', '/home/abdul/.cache/pre-commit/repo9fqruu7y/py_env-python3')
return code: 1
stdout:
    AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'
stderr: (none)
Check the log at /home/abdul/.cache/pre-commit/pre-commit.log
abdul@DESKTOP-UBCRCM7:/mnt/x/Abdul-Projects/git/clipboard-master$ 
```
