### ISSUE TITLE
Non-ascii prints in error handler without tty cause stacktrace

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#309]
```
23:00:13 style runtests: commands[0] | pre-commit run --all-files
23:00:13 [INFO] Installing environment for git@git.yelpcorp.com:mirrors/pre-commit/mirrors-jshint.
23:00:13 [INFO] Once installed this environment will be reused.
23:00:13 [INFO] This may take a few minutes...
23:01:33 Traceback (most recent call last):
23:01:33   File ".tox/style/bin/pre-commit", line 11, in <module>
23:01:33     sys.exit(main())
23:01:33   File ".../.tox/style/local/lib/python2.7/site-packages/pre_commit/main.py", line 157, in main
23:01:33     'Command {0} failed to exit with a returncode'.format(args.command)
23:01:33   File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
23:01:33     self.gen.throw(type, value, traceback)
23:01:33   File ".../.tox/style/local/lib/python2.7/site-packages/pre_commit/error_handler.py", line 41, in error_handler
23:01:33     traceback.format_exc(),
23:01:33   File ".../.tox/style/local/lib/python2.7/site-packages/pre_commit/error_handler.py", line 21, in _log_and_exit
23:01:33     print_fn(error_msg)
23:01:33 UnicodeEncodeError: 'ascii' codec can't encode characters in position 735-737: ordinal not in range(128)
```

**Comment by asottile** [comment]
I found a separate bug about writing that same stacktrace to the logfile.  I'll be fixing both it seems!
