### ISSUE TITLE
pre-commit installation on MacOS via homebrew is incomplete

### ISSUE THREAD

**Issue by apacha** [pre-commit/pre-commit#3106]
### search you tried in the issue tracker

setuptools

### describe your issue

I installed pre-commit via `brew install pre-commit` on a fresh Mac computer. Upon using pre-commit, I got this error:
```
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/bin/python3.12', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/alex/.cache/pre-commit/repo6u99uraz/node_env-default')
return code: 1
stdout: (none)
stderr:
    /opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
      import pipes
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/nodeenv.py", line 48, in <module>
        from pkg_resources import parse_version
    ModuleNotFoundError: No module named 'pkg_resources'
Check the log at /Users/alex/.cache/pre-commit/pre-commit.log
```
which means that the standard python environment that was installed along with pre-commit is incomplete.

I 'fixed' it by installing the necessary setuptools manually:

```bash
cd /opt/homebrew/Cellar/pre-commit/3.6.0/bin 
./python -m pip install setuptools
```

### pre-commit --version

pre-commit 3.6.0

### .pre-commit-config.yaml

```yaml
files: ^(public|src|test)/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: 'xsd'
      - id: end-of-file-fixer
        exclude: 'xsd'
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
        args: ['--maxkb=31000']
      - id: pretty-format-json
        args: ['--autofix', '--indent=4']
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
```

### version information

```
pre-commit version: 3.6.0
git --version: git version 2.39.3 (Apple Git-145)
sys.version:
    3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.0.40.1)]
sys.executable: /opt/homebrew/Cellar/pre-commit/3.6.0/libexec/bin/python3.12
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/bin/python3.12', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/alex/.cache/pre-commit/repo6u99uraz/node_env-default')
return code: 1
stdout: (none)
stderr:
    /opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
      import pipes
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/nodeenv.py", line 48, in <module>
        from pkg_resources import parse_version
    ModuleNotFoundError: No module named 'pkg_resources'
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/pre_commit/main.py", line 386, in main
    return hook_impl(
           ^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/pre_commit/commands/hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 94, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/pre_commit/languages/node.py", line 89, in install_environment
    cmd_output_b(*cmd)
  File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/bin/python3.12', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/alex/.cache/pre-commit/repo6u99uraz/node_env-default')
return code: 1
stdout: (none)
stderr:
    /opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
      import pipes
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/opt/homebrew/Cellar/pre-commit/3.6.0/libexec/lib/python3.12/site-packages/nodeenv.py", line 48, in <module>
        from pkg_resources import parse_version
    ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by asottile** [comment]
please report to homebrew as I suggested to the several duplicates that you didn't do a good job finding by searching
