### ISSUE TITLE
--top-keys parameter to pretty-format-json errors out

### ISSUE THREAD

**Issue by barndawgie** [pre-commit/pre-commit#3119]
### search you tried in the issue tracker

is:issue "top-keys" 

### describe your issue

Specifying the --top-keys parameter to the pretty-format-json doesn't seem to work, and I can't find any examples showing how else I would specify it.

```
$ pre-commit run --all-files
check json...............................................................Passed
pretty format json.......................................................Failed
- hook id: pretty-format-json
- exit code: 1

Traceback (most recent call last):
  File "/home/jbarnard/.cache/pre-commit/repof8zekzir/py_env-python3/bin/pretty-format-json", line 8, in <module>
    sys.exit(main())
  File "/home/jbarnard/.cache/pre-commit/repof8zekzir/py_env-python3/lib/python3.10/site-packages/pre_commit_hooks/pretty_format_json.py", line 105, in main
    with open(json_file, encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '--top-keys name'
```

### pre-commit --version

pre-commit 3.6.0

### .pre-commit-config.yaml

```yaml
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args:
        - --top-keys name
```

### version information

```
pre-commit version: 3.6.0
git --version: git version 2.43.0
sys.version:
    3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An error has occurred: InvalidConfigError:
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/pre-commit/pre-commit-hooks')
==> At key: hooks
==> At Hook(id='pretty-format-json')
==> At key: args
=====> Expected array but got 'str'
```

```
Traceback (most recent call last):
  File "/home/jbarnard/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/jbarnard/.local/lib/python3.10/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 422, in run
    config = load_config(config_file)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 399, in load_from_filename
    with reraise_as(exc_tp):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 45, in reraise_as
    raise tp(e).with_traceback(tb) from None
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 42, in reraise_as
    yield
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 403, in load_from_filename
    with validate_context(f'File {display_filename}'):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 36, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 33, in validate_context
    yield
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 415, in load_from_filename
    validate(data, schema)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 378, in validate
    schema.check(v)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 244, in check
    with validate_context(context):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 36, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 33, in validate_context
    yield
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 246, in check
    item.check(v)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 75, in _check_required
    _check_optional(self, dct)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 55, in _check_optional
    with validate_context(f'At key: {self.key}'):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 36, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 33, in validate_context
    yield
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 56, in _check_optional
    self.check_fn(dct[self.key])
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 81, in check_fn
    validate(val, self.schema)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 378, in validate
    schema.check(v)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 274, in check
    validate(val, self.of)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 378, in validate
    schema.check(v)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 244, in check
    with validate_context(context):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 36, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 33, in validate_context
    yield
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 246, in check
    item.check(v)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 108, in _check_conditional
    inner(self, dct)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 75, in _check_required
    _check_optional(self, dct)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 55, in _check_optional
    with validate_context(f'At key: {self.key}'):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 36, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 33, in validate_context
    yield
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 56, in _check_optional
    self.check_fn(dct[self.key])
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 81, in check_fn
    validate(val, self.schema)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 378, in validate
    schema.check(v)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 274, in check
    validate(val, self.of)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 378, in validate
    schema.check(v)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 244, in check
    with validate_context(context):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 36, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 33, in validate_context
    yield
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 246, in check
    item.check(v)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 55, in _check_optional
    with validate_context(f'At key: {self.key}'):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 36, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb) from None
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 33, in validate_context
    yield
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 56, in _check_optional
    self.check_fn(dct[self.key])
  File "/home/jbarnard/.local/lib/python3.10/site-packages/cfgv.py", line 360, in check_array_fn
    raise ValidationError(
pre_commit.clientlib.InvalidConfigError:
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='https://github.com/pre-commit/pre-commit-hooks')
==> At key: hooks
==> At Hook(id='pretty-format-json')
==> At key: args
=====> Expected array but got 'str'
```

**Comment by asottile** [comment]
I'll start with a hint and see if you can figure it out: as written you're passing an argument with a space in it (like if you did `git checkout '-b foo'`)

**Comment by barndawgie** [comment]
Gotcha, so `--top-keys=name` does work. That said, there is no indication of that syntax in the documentation.

**Comment by asottile** [comment]
more natural is `args: [--top-keys, name]`

the docs do cover this, you're just confused about how to write yaml and how command line arguments in general work which is understandable but outside the scope of what the docs should cover
