### ISSUE TITLE
virtualenv python version did not match created version

### ISSUE THREAD

**Issue by kzhai** [pre-commit/pre-commit#3123]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues/2880, https://github.com/pre-commit/pre-commit/issues/2270

### describe your issue

```
[INFO] Stashing unstaged files to /Users/kezhai/.cache/pre-commit/patch1707344436-47033.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /Users/kezhai/.cache/pre-commit/patch1707344436-47033.
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /Users/kezhai/.cache/pre-commit/repoh_0wtpja/py_env-python3.11/bin/python>>
- expected version: 3.11.7.final.0
```
The python version used for virtualenv was consistent 3.11, not sure where the "expected 3.11.7.final.0" comes from. I was using `pipenv`.

### pre-commit --version

pre-commit 2.20.0

### .pre-commit-config.yaml

```yaml
repos:

  # black
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: # Arguments to configure black
          - --line-length=79
          - --include='\.pyi?$'

          # These folders won't be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""

        language: system
        #language_version: python3.11

  # flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: # Arguments to configure flake8
          # Making isort line length compatible with black
          - --max-line-length=79
          - --max-complexity=10
          # - --select=B,C,E,F,W,T4,B9

          # These are errors that will be ignored by flake8
          # Check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          # https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
          # - --ignore=E203,E266,E501,W503,F403,F401,E402
          - --ignore=E203,W503

        language: system

  ## isort
  #- repo: https://github.com/pycqa/isort
  #  rev: 5.10.1
  #  hooks:
  #    - id: isort
  #      args:
  #        - --line-length=79
  #        - --profile=black

  # pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed.
      - id: check-ast # Simply check whether the files parse as valid python.
      - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types.
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems.
      - id: check-docstring-first # Checks a common error of defining a docstring after code.
      - id: check-executables-have-shebangs # Ensures that (non-binary) executables have a shebang.
      - id: check-json # This hook checks json files for parseable syntax.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-shebang-scripts-are-executable # Ensures that (non-binary) files with a shebang are executable.
      - id: check-symlinks # Checks for symlinks which do not point to anything.
      - id: check-toml # This hook checks toml files for parseable syntax.
      - id: check-vcs-permalinks # Ensures that links to vcs websites are permalinks.
      - id: check-xml # This hook checks xml files for parseable syntax.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: destroyed-symlinks # Detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      - id: detect-aws-credentials # Detects *your* aws credentials from the aws cli credentials file.
      - id: detect-private-key # Detects the presence of private keys.
      # - id: double-quote-string-fixer # This hook replaces double quoted strings with single quoted strings.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: file-contents-sorter # Sort the lines in specified files (defaults to alphabetical). You must provide list of target files as input in your .pre-commit-config.yaml file.
      - id: fix-byte-order-marker # Removes UTF-8 byte order marker.
      - id: fix-encoding-pragma # Add # -*- coding: utf-8 -*- to the top of python files.
      - id: forbid-new-submodules # Prevent addition of new git submodules.
      - id: mixed-line-ending # Replaces or checks mixed line ending.
      - id: name-tests-test # This verifies that test files are named correctly.
      - id: no-commit-to-branch # Protect committing to specific branches by name or pattern. Branches `master` and `main` protected by default.
      - id: pretty-format-json # This hook sets a standard for formatting JSON files.
      - id: requirements-txt-fixer # Sorts entries in requirements.txt.
      - id: sort-simple-yaml # Sorts simple YAML files which consist only of top-level keys, preserving comments and blocks.
      - id: trailing-whitespace # This hook trims trailing whitespace.
```

### version information

```
pre-commit version: 2.20.0
git --version: git version 2.39.2 (Apple Git-144)
sys.version:
    3.11.7 (main, Jan 17 2024, 13:37:41) [Clang 14.0.0 (clang-1400.0.29.202)]
sys.executable: /Users/kezhai/.local/share/virtualenvs/breslin-gfdwY-UF/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /Users/kezhai/.cache/pre-commit/repoh_0wtpja/py_env-python3.11/bin/python>>
- expected version: 3.11.7.final.0

```

```
Traceback (most recent call last):
  File "/Users/kezhai/.local/share/virtualenvs/breslin-gfdwY-UF/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/kezhai/.local/share/virtualenvs/breslin-gfdwY-UF/lib/python3.11/site-packages/pre_commit/main.py", line 386, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kezhai/.local/share/virtualenvs/breslin-gfdwY-UF/lib/python3.11/site-packages/pre_commit/commands/run.py", line 424, in run
    install_hook_envs(to_install, store)
  File "/Users/kezhai/.local/share/virtualenvs/breslin-gfdwY-UF/lib/python3.11/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/Users/kezhai/.local/share/virtualenvs/breslin-gfdwY-UF/lib/python3.11/site-packages/pre_commit/repository.py", line 84, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /Users/kezhai/.cache/pre-commit/repoh_0wtpja/py_env-python3.11/bin/python>>
- expected version: 3.11.7.final.0
```

**Comment by kzhai** [comment]
```
✗ brew install python@3.11
Warning: python@3.11 3.11.7_1 is already installed and up-to-date.
To reinstall 3.11.7_1, run:
  brew reinstall python@3.11
✗ python3                 
Python 3.11.7 (main, Jan 17 2024, 13:37:41) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
✗ which python3.11
/opt/brew/bin/python3.11
✗ which python3
/opt/brew/bin/python3
✗ virtualenv --version
virtualenv 20.25.0 from /opt/brew/lib/python3.11/site-packages/virtualenv/__init__.py
✗ 
```

**Comment by asottile** [comment]
you're using an extremely old version of pre-commit.  please try on a more modern one (and while you're at it search the tracker for your error message, there's several duplicates)

**Comment by kzhai** [comment]
Thanks, @asottile . Problem persists after upgrade to a newer version. I have tried solutions from other two threads mentioned, but still not resolved. 
```
✗ pre-commit --version
pre-commit 3.6.0
✗ pre-commit run --file breslin/red_teaming.py      
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from /Users/kezhai/.cache/pre-commit/repo8i9gghb_/py_env-python3.11/bin/python>>
- expected version: 3.11.7.final.0

Check the log at /Users/kezhai/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
have you tried any of the debugging steps in the other duplicate issues?

**Comment by kzhai** [comment]
I tried them all, and finally got it working. Apparently the problem is pre-commit command creates a mapping to the virtualenv `pipenv` created, but failed to redirect to the right python version. I need to reset the `pre-commit` app data in the pre-commit directory, not the virtualenv directory that `pipenv` created.

**Comment by esseti** [comment]
can you explain how you did it? i've a similar problem and i can't figure it out
