### ISSUE TITLE
:args seems to break with {} in list.

### ISSUE THREAD

**Issue by marick** [pre-commit/pre-commit#314]
I am working on a repo with some hooks for my company: https://github.com/marick/pre-commit-hooks

There is a hook that works fine with this `.pre-commit-config.yaml`:

```yaml
-   repo: /Users/marick/src/pre-commit-hooks
    sha: d6dee96f56bf9290f7ebb852c4252c50b8f6215d
    stages: [commit, push]
    hooks:
    -   id: prohibit-suspicious-patterns
        args: ["AKIA[[:alnum]]", --]
```

However, it I change the first arg by adding `{1}`:

```yaml
        args: ["AKIA[[:alnum]]{1}", --]
```

... I get this:

```
prohibit suspicious patterns..................................................................
An unexpected error has occurred: IndexError: tuple index out of range
Check the log at ~/.pre-commit/pre-commit.log
```

The contents of `pre-commit.log`:

```
An unexpected error has occurred: IndexError: tuple index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pre_commit/error_handler.py", line 36, in error_handler
    yield
  File "/usr/local/lib/python2.7/site-packages/pre_commit/main.py", line 150, in main
    return run(runner, args)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/commands/run.py", line 212, in run
    return _run_hooks(repo_hooks, args, write, environ)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/commands/run.py", line 136, in _run_hooks
    retval |= _run_single_hook(hook, repo, args, write, skips)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/commands/run.py", line 89, in _run_single_hook
    retcode, stdout, stderr = repo.run_hook(hook, filenames)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/repository.py", line 145, in run_hook
    self.cmd_runner, hook, file_args,
  File "/usr/local/lib/python2.7/site-packages/pre_commit/languages/script.py", line 23, in run_hook
    encoding=None,
  File "/usr/local/lib/python2.7/site-packages/pre_commit/prefixed_command_runner.py", line 40, in run
    replaced_cmd = _replace_cmd(cmd, prefix=self.prefix_dir)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/prefixed_command_runner.py", line 11, in _replace_cmd
    return [part.format(**kwargs) for part in cmd]
IndexError: tuple index out of range

```

**Comment by asottile** [comment]
Ah dang, this has to do with the way we format in the prefix directory.

A workaround for now is to replace `{1}` with `{{1}}`.

I wonder if I should document this somewhere as whatever I choose for substitution it'll be difficult to accept all strings (For example if I use `%s` instead I'll need to look out for args with `%` symbols in them).  What are you suggestions?

**Comment by asottile** [comment]
Oh, I could instead use `.replace(...)` and use some sentinel value instead of `.format(`ting, lemme try that.

**Comment by asottile** [comment]
Yeah, I'm going to do that.  See #315

**Comment by asottile** [comment]
Install 0.6.8 to get this fix :)  Thanks again for the bug report!

**Comment by marick** [comment]
Thanks for your promptness. Very impressive.

**Comment by marick** [comment]
I'm not familiar with the python ecosystem. Does this mean I can use `pip` to get the new version?

**Comment by asottile** [comment]
Yeah, if it's already installed just `pip install pre-commit==0.6.8` or to grab the latest `pip install --upgrade pre-commit`
