### ISSUE TITLE
Add support for Python 3.12 + PEP632

### ISSUE THREAD

**Issue by PacificGilly** [pre-commit/pre-commit#3171]
### search you tried in the issue tracker

Python 3.12, 3.12, 12, PEP632, Distutils

### describe your issue

We've been upgrading our system to use PY3.12 built from a docker base image `python:3.12-bullseye`

When you run the following command:
```
pre-commit run --all-files
```
straight from the docker container (and also locally) you get the following error (see ~/.cache/pre-commit/pre-commit.log) :

This is caused by PEP632 taking effect in PY3.12 [0], which removes `distutils` from the stdlib and bundles it within `setuptools` instead. So the venv that pre-commit creates in PY3.12 doesn't take this into account, and when it tries to install the hooks, it fails.

A bit of a workaround is to use `language: system` to force pre-commit to use the system's venv and not spin up its own one, which is broken. This doesn't work for all pre-commits I've found (e.g. `pre-commit`'s hooks doesn't work doing this.)

Can this be investigated to see if we can fix the venv's created by pre-commit, please, to add support for PY3.12?

[0] https://peps.python.org/pep-0632/#migration-advice

### pre-commit --version

3.7.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        stages: [commit]
      - id: mypy
        name: mypy
        entry: mypy
        require_serial: true
        language: system
        types: [python]
        stages: [commit]
        # for the client mypy needs the deps to be installed so is best run by tox
        files: ^(src/|tests/)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
        exclude: \.snap$
      - id: check-merge-conflict
        stages: [commit]
  - repo: https://github.com/ducminh-phan/reformat-gherkin
    rev: v3.0.1
    hooks:
      - id: reformat-gherkin
        stages: [commit]
        files: ^.*\.feature$
```

### version information

```
pre-commit version: 3.7.0
git --version: git version 2.30.2
sys.version:
    3.12.0 (main, Nov 29 2023, 02:50:35) [GCC 10.2.1 20210110]
sys.executable: /home/lyst/venv/bin/python3.12
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 1
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/__main__.py", line 29, in <module>
        from pip._internal.cli.main import main as _main
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 9, in <module>
        from pip._internal.cli.autocompletion import autocomplete
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
        from pip._internal.cli.main_parser import create_main_parser
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
        from pip._internal.cli import cmdoptions
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
        from pip._internal.cli.parser import ConfigOptionParser
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
        from pip._internal.configuration import Configuration, ConfigurationError
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/configuration.py", line 26, in <module>
        from pip._internal.utils.logging import getLogger
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/utils/logging.py", line 29, in <module>
        from pip._internal.utils.misc import ensure_dir
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
        from pip._internal.locations import get_major_minor_version
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
        from . import _distutils, _sysconfig
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
        from distutils.cmd import Command as DistutilsCommand
    ModuleNotFoundError: No module named 'distutils'
```

```
Traceback (most recent call last):
  File "/home/lyst/venv/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/lyst/venv/lib/python3.12/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lyst/venv/lib/python3.12/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/lyst/venv/lib/python3.12/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/home/lyst/venv/lib/python3.12/site-packages/pre_commit/repository.py", line 94, in _hook_install
    lang.install_environment(
  File "/home/lyst/venv/lib/python3.12/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/home/lyst/venv/lib/python3.12/site-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/lyst/venv/lib/python3.12/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 1
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/__main__.py", line 29, in <module>
        from pip._internal.cli.main import main as _main
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 9, in <module>
        from pip._internal.cli.autocompletion import autocomplete
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
        from pip._internal.cli.main_parser import create_main_parser
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
        from pip._internal.cli import cmdoptions
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
        from pip._internal.cli.parser import ConfigOptionParser
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
        from pip._internal.configuration import Configuration, ConfigurationError
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/configuration.py", line 26, in <module>
        from pip._internal.utils.logging import getLogger
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/utils/logging.py", line 29, in <module>
        from pip._internal.utils.misc import ensure_dir
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
        from pip._internal.locations import get_major_minor_version
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
        from . import _distutils, _sysconfig
      File "/home/lyst/.cache/pre-commit/repo0x6p7j9n/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
        from distutils.cmd import Command as DistutilsCommand
    ModuleNotFoundError: No module named 'distutils'
```

**Comment by asottile** [comment]
this isn't a pre-commit problem. you've installed an incompatible version of virtualenv

**Comment by PacificGilly** [comment]
@asottile How have I installed an incompatible version? `pre-commit` is the one installing the py_env! We don't use that stuff!

Your `py_env` is installing an old `pip` == 22.1.2 which is not PEP632 compliant. Please can this be fixed or shown to be in more than 1 line where the issue is?

**Comment by asottile** [comment]
how did you install pre-commit?

**Comment by PacificGilly** [comment]
Using a venv and Poetry v1.4.2 on a base docker image `python:3.12-bullseye` using the python version provided by the docker. I've checked the version provided by the docker image and it's 23.1.2 (PEP632 compatible), but the one used in the pre-commit created `pyenv` is 22.1.2 (PEP632 non-compatible)

**Comment by asottile** [comment]
and what's in your lock file

**Comment by PacificGilly** [comment]
What package are you looking for (since they're typically massive with proprietary libraries)?

**Comment by asottile** [comment]
read my original response and take a guess

**Comment by PacificGilly** [comment]
virtualenv?

**Comment by PacificGilly** [comment]
If so, then this is still a bug with this package as this package sets the lower limits of the virtualenv library

**Comment by asottile** [comment]
I hope you learned something and will be a better listener and reporter next time
