### ISSUE TITLE
An unexpected error has occurred: CalledProcessError: command:

### ISSUE THREAD

**Issue by iamtodor** [pre-commit/pre-commit#3175]
### search you tried in the issue tracker

There are issues with Windows, anaconda, and installation, but I have not found anything related to MacOS and `pre-commit run`

### describe your issue

I created the `virtualenv` with Python 3.10.13 from `pyenv`. Installed `pre-commit`, run `pre-commit install`. 

Then I run `pre-commit run` and have the following error.

```
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'
stderr: (none)
```

I tried to:

- recreate the venv
- remove `rm -rf ~/.cache/pre-commit/`

Versions:

- `virtualenv   20.25.1`
- `MacOS 14.4.1`

### pre-commit --version

3.6.2

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "master"]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
        -   id: isort
            args: ["--line-length", "120", "--profile",  "black"]
-   repo: https://github.com/psf/black
    rev: 23.1a1
    hooks:
        -   id: black
            language_version: python3.8
            args: ["--preview", "--line-length", "120"]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
        -   id: flake8
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      args: ["-r", "-i", "--exclude", "path"]
```

### version information

```
pre-commit version: 3.6.2
git --version: git version 2.39.3 (Apple Git-146)
sys.version:
    3.10.13 (main, Mar 25 2024, 20:48:04) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.executable: /Users/usr/code/.venv/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/usr/code/.venv/bin/python', '-mvirtualenv', '/Users/usr/.cache/pre-commit/repoyv1ox_94/py_env-python3.8', '-p', 'python3.8')
return code: 1
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'
stderr: (none)
```

```
Traceback (most recent call last):
  File "/Users/usr/code/.venv/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/usr/code/.venv/lib/python3.10/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
  File "/Users/usr/code/.venv/lib/python3.10/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/Users/usr/code/.venv/lib/python3.10/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/Users/usr/code/.venv/lib/python3.10/site-packages/pre_commit/repository.py", line 94, in _hook_install
    lang.install_environment(
  File "/Users/usr/code/.venv/lib/python3.10/site-packages/pre_commit/languages/python.py", line 212, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/Users/usr/code/.venv/lib/python3.10/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/usr/code/.venv/bin/python', '-mvirtualenv', '/Users/usr/.cache/pre-commit/repoyv1ox_94/py_env-python3.8', '-p', 'python3.8')
return code: 1
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'
stderr: (none)
```

**Comment by asottile** [comment]
you asked pre-commit to use python 3.8 but you don't have python 3.8

there are several duplicates and they are all the same problem

**Comment by iamtodor** [comment]
@asottile I do have it as well: 

```
pyenv shims
/Users/usr/.pyenv/shims/2to3
/Users/usr/.pyenv/shims/2to3-3.10
/Users/usr/.pyenv/shims/2to3-3.8
/Users/usr/.pyenv/shims/identify-cli
/Users/usr/.pyenv/shims/idle
/Users/usr/.pyenv/shims/idle3
/Users/usr/.pyenv/shims/idle3.10
/Users/usr/.pyenv/shims/idle3.8
/Users/usr/.pyenv/shims/nodeenv
/Users/usr/.pyenv/shims/pip
/Users/usr/.pyenv/shims/pip3
/Users/usr/.pyenv/shims/pip3.10
/Users/usr/.pyenv/shims/pip3.8
/Users/usr/.pyenv/shims/pydoc
/Users/usr/.pyenv/shims/pydoc3
/Users/usr/.pyenv/shims/pydoc3.10
/Users/usr/.pyenv/shims/pydoc3.8
/Users/usr/.pyenv/shims/python
/Users/usr/.pyenv/shims/python-config
/Users/usr/.pyenv/shims/python3
/Users/usr/.pyenv/shims/python3-config
/Users/usr/.pyenv/shims/python3.10
/Users/usr/.pyenv/shims/python3.10-config
/Users/usr/.pyenv/shims/python3.10-gdb.py
/Users/usr/.pyenv/shims/python3.8
/Users/usr/.pyenv/shims/python3.8-config
/Users/usr/.pyenv/shims/python3.8-gdb.py
/Users/usr/.pyenv/shims/virtualenv
```

Could you please re-open the issue?

**Comment by asottile** [comment]
the error you're getting isn't in pre-commit so no, you'll have to debug why virtualenv doesn't find your python 3.8
