### ISSUE TITLE
Running pre-commit on windows yields in error

### ISSUE THREAD

**Issue by NtWriteCode** [pre-commit/pre-commit#3186]
### search you tried in the issue tracker

object has no attribute 'endswith'

### describe your issue

I was just trying to install my precommits that I've been already using on Linux. 

### pre-commit --version

pre-commit 3.7.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-ast
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: mixed-line-ending
    -   id: debug-statements
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML, types-requests, types-beautifulsoup4]
-   repo: https://github.com/asottile/dead
    rev: v1.5.2
    hooks:
    -   id: dead
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
    -   id: yamllint
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
    -   id: docker-compose-check
-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint
        stages: [commit]
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks
-   repo: https://github.com/hakancelikdev/unimport
    rev: 1.2.1
    hooks:
    -   id: unimport
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
    -   id: bandit
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
```

### version information

```
pre-commit version: 3.7.0
git --version: git version 2.44.0.windows.1
sys.version:
    3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
sys.executable: C:\Python311\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Python311\\python.exe', '-mvirtualenv', 'C:\\Users\\Undefined\\.cache\\pre-commit\\repoxjfc3w9d\\py_env-python3.11')
return code: 1
stdout:
    AttributeError: 'WindowsPath' object has no attribute 'endswith'
stderr: (none)
```

```
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Python311\Lib\site-packages\pre_commit\main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pre_commit\commands\run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:\Python311\Lib\site-packages\pre_commit\repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "C:\Python311\Lib\site-packages\pre_commit\repository.py", line 94, in _hook_install
    lang.install_environment(
  File "C:\Python311\Lib\site-packages\pre_commit\languages\python.py", line 212, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "C:\Python311\Lib\site-packages\pre_commit\util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Python311\\python.exe', '-mvirtualenv', 'C:\\Users\\Undefined\\.cache\\pre-commit\\repoxjfc3w9d\\py_env-python3.11')
return code: 1
stdout:
    AttributeError: 'WindowsPath' object has no attribute 'endswith'
stderr: (none)
```

**Comment by asottile** [comment]
that's virtualenv, please report an issue there instead
