### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils' on Ubuntu 24.04

### ISSUE THREAD

**Issue by sbrunner** [pre-commit/pre-commit#3203]
### search you tried in the issue tracker

ubuntu, distutils

### describe your issue

Unable to call `pre-commit run --all-files`

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
```

### version information

```
pre-commit version: 3.7.1
git --version: git version 2.43.0
sys.version:
    3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
sys.executable: /home/sbrunner/.venv/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 2
stdout:
    Processing /home/sbrunner/.cache/pre-commit/repom3_gzaij
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
stderr:
    ERROR: Exception:
    Traceback (most recent call last):
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
        status = run_func(*args)
                 ^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
        return func(self, options, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
        requirement_set = resolver.resolve(
                          ^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
        collected = self.factory.collect_root_requirements(root_reqs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 534, in collect_root_requirements
        reqs = list(
               ^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
        cand = self._make_base_candidate_from_link(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
        self._link_candidate_cache[link] = LinkCandidate(
                                           ^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
        super().__init__(
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
        self.dist = self._prepare()
                    ^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
        dist = self._prepare_distribution()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
        return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
        return self._prepare_linked_requirement(req, parallel_builds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
        dist = _get_prepared_distribution(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
        abstract_dist.prepare_distribution_metadata(
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 54, in prepare_distribution_metadata
        self._install_build_reqs(finder)
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 124, in _install_build_reqs
        build_reqs = self._get_build_requires_wheel()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 101, in _get_build_requires_wheel
        return backend.get_requires_for_build_wheel()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 745, in get_requires_for_build_wheel
        return super().get_requires_for_build_wheel(config_settings=cs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
        return self._call_hook('get_requires_for_build_wheel', {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
        raise BackendUnavailable(data.get('traceback', ''))
    pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
        obj = import_module(mod_path)
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/tmp/pip-build-env-ykjav7ys/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 9, in <module>
        import distutils.core
    ModuleNotFoundError: No module named 'distutils'
```

```
Traceback (most recent call last):
  File "/home/sbrunner/.venv/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/sbrunner/.venv/lib/python3.12/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sbrunner/.venv/lib/python3.12/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/sbrunner/.venv/lib/python3.12/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/home/sbrunner/.venv/lib/python3.12/site-packages/pre_commit/repository.py", line 94, in _hook_install
    lang.install_environment(
  File "/home/sbrunner/.venv/lib/python3.12/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/home/sbrunner/.venv/lib/python3.12/site-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/sbrunner/.venv/lib/python3.12/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/bin/python', '-mpip', 'install', '.')
return code: 2
stdout:
    Processing /home/sbrunner/.cache/pre-commit/repom3_gzaij
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
stderr:
    ERROR: Exception:
    Traceback (most recent call last):
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
        status = run_func(*args)
                 ^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
        return func(self, options, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
        requirement_set = resolver.resolve(
                          ^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
        collected = self.factory.collect_root_requirements(root_reqs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 534, in collect_root_requirements
        reqs = list(
               ^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
        cand = self._make_base_candidate_from_link(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
        self._link_candidate_cache[link] = LinkCandidate(
                                           ^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
        super().__init__(
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
        self.dist = self._prepare()
                    ^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
        dist = self._prepare_distribution()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
        return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
        return self._prepare_linked_requirement(req, parallel_builds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
        dist = _get_prepared_distribution(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
        abstract_dist.prepare_distribution_metadata(
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 54, in prepare_distribution_metadata
        self._install_build_reqs(finder)
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 124, in _install_build_reqs
        build_reqs = self._get_build_requires_wheel()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 101, in _get_build_requires_wheel
        return backend.get_requires_for_build_wheel()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 745, in get_requires_for_build_wheel
        return super().get_requires_for_build_wheel(config_settings=cs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
        return self._call_hook('get_requires_for_build_wheel', {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
        raise BackendUnavailable(data.get('traceback', ''))
    pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
      File "/home/sbrunner/.cache/pre-commit/repom3_gzaij/py_env-python3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
        obj = import_module(mod_path)
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/tmp/pip-build-env-ykjav7ys/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 9, in <module>
        import distutils.core
    ModuleNotFoundError: No module named 'distutils'
```

**Comment by sbrunner** [comment]
I see similar issue but witout any working solutions on my situation https://github.com/pre-commit/pre-commit/issues/3171

On Ubuntu 22.04 we should install all package on a vanv the I install pre-commit like that:
```bash
cd ~
python -m venv .venv
export PATH=${HOME}/.venv/bin/:${PATH}
pip install pre-commit
```

**Comment by asottile** [comment]
please search the issue tracker for duplicates.  this is not a pre-commit issue but an issue with your setup and the various duplicates show you how to fix your problem
