### ISSUE TITLE
perl hook environment not cleaned up

### ISSUE THREAD

**Issue by code-acrobat** [pre-commit/pre-commit#3213]
### search you tried in the issue tracker

is:issue perl blib cache

### describe your issue

When a perl hook is ordered before a python hook a pre-commit install-hooks fails. 
it succeeds to install when the order is reversed.

It suffices to have 2 empty script files noop(perl) and noop2(python).

The message suggests to tune py_modules but this is happening behind the scenes in a pre-commit cache directory.

### pre-commit --version

3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: noop
        name: noop
        files: .*
        language: perl
        entry: .pre-commit/noop
  - repo: local
    hooks:
      - id: noop2
        name: noop2
        files: .*
        language: python
        entry: .pre-commit/noop2
```

### version information

```
pre-commit version: 3.7.1
git --version: git version 2.34.1
sys.version:
    3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/root/.cache/pre-commit/repo41t25bfz/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /root/.cache/pre-commit/repo41t25bfz
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          error: Multiple top-level packages discovered in a flat-layout: ['renv', 'blib'].
          
          To avoid accidental inclusion of unwanted files or directories,
          setuptools will not proceed with this build.
          
          If you are trying to create a single distribution with multiple packages
          on purpose, you should not rely on automatic discovery.
          Instead, consider the following options:
          
          1. set up custom discovery (`find` directive with `include` or `exclude`)
          2. use a `src-layout`
          3. explicitly set `py_modules` or `packages` with a list of names
          
          To find more information, look for "package discovery" on setuptools docs.
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/main.py", line 413, in main
    return install_hooks(args.config, store)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/commands/install_uninstall.py", line 145, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/repository.py", line 94, in _hook_install
    lang.install_environment(
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/root/.cache/pre-commit/repo41t25bfz/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /root/.cache/pre-commit/repo41t25bfz
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          error: Multiple top-level packages discovered in a flat-layout: ['renv', 'blib'].
          
          To avoid accidental inclusion of unwanted files or directories,
          setuptools will not proceed with this build.
          
          If you are trying to create a single distribution with multiple packages
          on purpose, you should not rely on automatic discovery.
          Instead, consider the following options:
          
          1. set up custom discovery (`find` directive with `include` or `exclude`)
          2. use a `src-layout`
          3. explicitly set `py_modules` or `packages` with a list of names
          
          To find more information, look for "package discovery" on setuptools docs.
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

**Comment by asottile** [comment]
dupe #3208

**Comment by code-acrobat** [comment]
Sorry @asottile about the missing information in #3208 I would've commented there for more details but you blocked. IMHO you should be able to run perl and python hooks simply by pre-commit run --all-files without cleanup shenanigans in between.

**Comment by code-acrobat** [comment]
I can live without a fix. Just order the perl hooks at the end of the .pre-commit-config.yaml.
