### ISSUE TITLE
Extremely long timeout when hook repo is not reachable

### ISSUE THREAD

**Issue by AdrianFreundQC** [pre-commit/pre-commit#3216]
### search you tried in the issue tracker

timeout

### describe your issue

When downloading hook repos (including when running `pre-commit autoupdate` when a repo is not reachable (for example because it's only reachable using a proxy or vpn) pre-commit will wait ~20-30 minutes before aborting with an error.

```
$ pre-commit autoupdate  
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', '-c', 'core.useBuiltinFSMonitor=false', '-C', '/var/folders/7_/dz14xkq55qj4vpnc4187t5780000gn/T/tmp58a6nlm9', 'fetch', 'origin', 'HEAD', '--quiet', '--filter=blob:none', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: unable to access 'https://***.com/***/***.git/': Failed to connect to ***.com port 443 after 150005 ms: Couldn't connect to server
Check the log at /Users/***/.cache/pre-commit/pre-commit.log
```

Interestingly the stderr (error message generated by git) claims that the timeout took only 2.5 minutes. Manually running the fetch command with the non-reachable repo only waits for 2.5 minutes before timing out, as claimed by the output.
This seems to suggest that either pre-commit does multiple retries in the background, without informing the user or it waits on something else when an error occurs.

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
Contains sensitive information (URL to an internal git server)
```

### version information

```
pre-commit version: 3.7.1
git --version: git version 2.39.3 (Apple Git-146)
sys.version:
    3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.executable: /opt/homebrew/Cellar/pre-commit/3.7.1/libexec/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: unable to access 'https://***.com/***/***.git/': Failed to connect to ***.com port 443 after 150084 ms: Couldn't connect to server
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/store.py", line 202, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/store.py", line 184, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/store.py", line 199, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'protocol.version=2', 'fetch', 'origin', '0.6.1', '--depth=1')
return code: 128
stdout: (none)
stderr:
    fatal: unable to access 'https://***.com/***/***.git/': Failed to connect to ***.com port 443 after 150003 ms: Couldn't connect to server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/commands/run.py", line 425, in run
    for hook in all_hooks(config, store)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 242, in all_hooks
    return tuple(
           ^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 245, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 220, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 186, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/store.py", line 206, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/store.py", line 163, in _new_repo
    make_strategy(directory)
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/store.py", line 204, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/store.py", line 176, in _complete_clone
    git_cmd('fetch', 'origin', '--tags')
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/store.py", line 199, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: unable to access 'https://***.com/***/***.git/': Failed to connect to ***.com port 443 after 150084 ms: Couldn't connect to server
```

**Comment by asottile** [comment]
there's no retries here so it's however you've configured git
