### ISSUE TITLE
 No such file or directory: '/Users/xxx/.cache/pre-commit/repoun1c2d52/golangenv-system/.install_state_v1staging

### ISSUE THREAD

**Issue by yida-chen-uid** [pre-commit/pre-commit#3219]
### search you tried in the issue tracker

https://github.com/pre-commit/pre-commit/issues/1658

### describe your issue

There was an error when I tried to install a unit test hook.

$ pre-commit install-hooks
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxx/.cache/pre-commit/repoun1c2d52/golangenv-system/.install_state_v1staging'

### pre-commit --version

pre-commit version: 3.7.0

### .pre-commit-config.yaml

```yaml
default_stages: [push]
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: my-test
        name: unit test for local
        description: unit test for my-test project
        entry: |
          bash -c 'env RUNTIME_DIR=$(realpath tests/runtime) go test -tags without_faceme_console_sdk -v -p 1 ./coms/compose/impl/init_test.go'
        stages: [push]
        language: golang
        pass_filenames: false
```

### version information

```
pre-commit version: 3.7.0
git --version: git version 2.39.3 (Apple Git-146)
sys.version:
    3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.executable: /usr/local/opt/python@3.12/bin/python3.12
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/Users/yida.chen/.cache/pre-commit/repoun1c2d52/golangenv-system/.install_state_v1staging'
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/lib/python3.12/site-packages/pre_commit/main.py", line 413, in main
    return install_hooks(args.config, store)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pre_commit/commands/install_uninstall.py", line 145, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/usr/local/lib/python3.12/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/lib/python3.12/site-packages/pre_commit/repository.py", line 110, in _hook_install
    with open(staging, 'w') as state_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yida.chen/.cache/pre-commit/repoun1c2d52/golangenv-system/.install_state_v1staging'
```

**Comment by asottile** [comment]
can you show me `env | grep GO`?

**Comment by yida-chen-uid** [comment]
Nothing is output, but I actually have the go environment installed.
```
$ env | grep GO
$ go version   
go version go1.22.3 darwin/amd64
```

**Comment by asottile** [comment]
actually, looking at your configuration why are you using `language: golang` in the first place? you're not installing anything into the managed environment

**Comment by yida-chen-uid** [comment]
Because I am currently using golang language for development, and I see that you also support golang, so I choose golang.

**Comment by yida-chen-uid** [comment]
Do you have any better suggestions?

**Comment by asottile** [comment]
your hook doesn't use any of the useful parts of pre-commit, you want `system`
