### ISSUE TITLE
can run on Mac osx dir

### ISSUE THREAD

**Issue by themakunga** [pre-commit/pre-commit#3223]
### search you tried in the issue tracker

pre commit install and run

### describe your issue

all my packages are updated and when I try to test it on a new repo I got this

### pre-commit --version

pre-commit version: 3.6.2

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
```

### version information

```
pre-commit version: 3.6.2
git --version: git version 2.45.2
sys.version:
    3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.executable: /opt/homebrew/opt/python@3.11/bin/python3.11
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/opt/python@3.11/bin/python3.11', '-mvirtualenv', '/Users/nicolas/.cache/pre-commit/repo4mc9mc5c/py_env-python3.11')
return code: 1
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "<frozen runpy>", line 189, in _run_module_as_main
      File "<frozen runpy>", line 148, in _get_module_details
      File "<frozen runpy>", line 112, in _get_module_details
      File "/opt/homebrew/lib/python3.11/site-packages/virtualenv/__init__.py", line 3, in <module>
        from .run import cli_run, session_via_cli
      File "/opt/homebrew/lib/python3.11/site-packages/virtualenv/run/__init__.py", line 7, in <module>
        from virtualenv.app_data import make_app_data
      File "/opt/homebrew/lib/python3.11/site-packages/virtualenv/app_data/__init__.py", line 8, in <module>
        from platformdirs import user_data_dir
    ModuleNotFoundError: No module named 'platformdirs'
```

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/lib/python3.11/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/lib/python3.11/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/lib/python3.11/site-packages/pre_commit/repository.py", line 94, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/lib/python3.11/site-packages/pre_commit/languages/python.py", line 212, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/opt/homebrew/lib/python3.11/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/opt/homebrew/opt/python@3.11/bin/python3.11', '-mvirtualenv', '/Users/nicolas/.cache/pre-commit/repo4mc9mc5c/py_env-python3.11')
return code: 1
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "<frozen runpy>", line 189, in _run_module_as_main
      File "<frozen runpy>", line 148, in _get_module_details
      File "<frozen runpy>", line 112, in _get_module_details
      File "/opt/homebrew/lib/python3.11/site-packages/virtualenv/__init__.py", line 3, in <module>
        from .run import cli_run, session_via_cli
      File "/opt/homebrew/lib/python3.11/site-packages/virtualenv/run/__init__.py", line 7, in <module>
        from virtualenv.app_data import make_app_data
      File "/opt/homebrew/lib/python3.11/site-packages/virtualenv/app_data/__init__.py", line 8, in <module>
        from platformdirs import user_data_dir
    ModuleNotFoundError: No module named 'platformdirs'
```

**Comment by asottile** [comment]
your homebrew install is corrupted, we don't maintain the Homebrew integration you'll need to take it up with them

**Comment by themakunga** [comment]
<img width="1064" alt="image" src="https://github.com/pre-commit/pre-commit/assets/235083/bf69fc94-9c7c-4444-a3b9-25c1a2083ca7">
