### ISSUE TITLE
Python 3.9.19 `TypeError` from `virtualenv`

### ISSUE THREAD

**Issue by chrisguidry** [pre-commit/pre-commit#3229]
### search you tried in the issue tracker

3.9.19, TypeError

### describe your issue

We run `pre-commit --all-files` in our Github CI, and we have been doing it with our lowest supported python version, 3.9.  The `setup-python` GH action bumped to 3.9.19 today and we started seeing this error:

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/hostedtoolcache/Python/3.9.19/x64/bin/python', '-mvirtualenv', '/home/runner/.cache/pre-commit/repody5s055m/py_env-python3')
return code: 1
stdout:
    RuntimeError: failed to build image pip, wheel, setuptools because:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 54, in _install
        with parent.non_reentrant_lock_for_key(wheel_img.name):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/util/lock.py", line 142, in non_reentrant_lock_for_key
        with _CountedFileLock(str(self.path / f"{name}.lock")):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/util/lock.py", line [22](https://github.com/PrefectHQ/prefect/actions/runs/9488171990/job/26146480222?pr=13973#step:8:23), in __init__
        super().__init__(lock_file)
    TypeError: object.__init__() takes exactly one argument (the instance to initialize)
    
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 54, in _install
        with parent.non_reentrant_lock_for_key(wheel_img.name):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/util/lock.py", line 142, in non_reentrant_lock_for_key
        with _CountedFileLock(str(self.path / f"{name}.lock")):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/util/lock.py", line 22, in __init__
        super().__init__(lock_file)
    TypeError: object.__init__() takes exactly one argument (the instance to initialize)
    
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 54, in _install
        with parent.non_reentrant_lock_for_key(wheel_img.name):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/util/lock.py", line 142, in non_reentrant_lock_for_key
        with _CountedFileLock(str(self.path / f"{name}.lock")):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/util/lock.py", line 22, in __init__
        super().__init__(lock_file)
    TypeError: object.__init__() takes exactly one argument (the instance to initialize)
stderr:
    Exception ignored in: <function BaseFileLock.__del__ at 0x7f8995febee0>
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/filelock/_api.py", line 365, in __del__
        self.release(force=True)
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/util/lock.py", line [34](https://github.com/PrefectHQ/prefect/actions/runs/9488171990/job/26146480222?pr=13973#step:8:35), in release
        with self.thread_safe:
    AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
    Exception ignored in: <function BaseFileLock.__del__ at 0x7f8995febee0>
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/filelock/_api.py", line [36](https://github.com/PrefectHQ/prefect/actions/runs/9488171990/job/26146480222?pr=13973#step:8:37)5, in __del__
        self.release(force=True)
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/util/lock.py", line 34, in release
        with self.thread_safe:
    AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
    Exception ignored in: <function BaseFileLock.__del__ at 0x7f8995febee0>
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/filelock/_api.py", line 365, in __del__
        self.release(force=True)
      File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/util/lock.py", line 34, in release
        with self.thread_safe:
    AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
```

Pinning back down to Python 3.9.18 resolves it, so I think there must have been a small breaking change for `pre-commit` in `virtualenv`.

### pre-commit --version

3.7.1

### .pre-commit-config.yaml

```yaml
n/a
```

### ~/.cache/pre-commit/pre-commit.log (if present)

n/a

**Comment by asottile** [comment]
you'll notice that the error does not come from pre-commit.  please report it to the proper project
