### ISSUE TITLE
Installation issue on msys2 / mingw64

### ISSUE THREAD

**Issue by RobinMaub** [pre-commit/pre-commit#3234]
### search you tried in the issue tracker

msys2, mingw64

### describe your issue

Hello support team,

I am a pre-commit user on Linux and I'd like to use it on Windows with msys2/mingw64. I installed it using `pacman -S mingw-w64-x86_64-python-pre-commit`, which goes fine. But at run, it is not working:
```
$ pre-commit run
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/XYZ/.cache/pre-commit/repogzwwsprl/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.9.final.0

Check the log at C:/Users/XYZ/.cache/pre-commit/pre-commit.log
```

and the log shows:
**version information**
```
pre-commit version: 3.7.0
git --version: git version 2.45.1
sys.version:
    3.11.9 (main, Apr 12 2024, 09:55:31)  [GCC 13.2.0 64 bit (AMD64)]
sys.executable: C:/msys64/mingw64/bin/python.exe
os.name: nt
sys.platform: win32
```

**error information**
```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/robin.maubert.ch2/.cache/pre-commit/repogzwwsprl/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.9.final.0
```

```
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "C:/msys64/mingw64/lib/python3.11/site-packages/pre_commit/repository.py", line 99, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/XYZ/.cache/pre-commit/repogzwwsprl/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.9.final.0
```

A guy answered that there is an issue in the package itself. The whole discussions is [here](https://stackoverflow.com/questions/78615923/pre-commit-version-did-not-match-created-version-on-msys2)

Any idea on the root cause / issue ?

### pre-commit --version

3.7.0

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.6
    hooks:
    -   id: clang-format
```

**Comment by asottile** [comment]
yes I said to report it to the maintainer of the mingw package not here

**Comment by sdegrande** [comment]
I had the same issue, fixed with this patch (virtualenv on msys2 uses the same directories structure than on Linux)

```diff
diff --git a/pre_commit/languages/python.py b/pre_commit/languages/python.py
index 0c4bb62..cb09f61 100644
--- a/pre_commit/languages/python.py
+++ b/pre_commit/languages/python.py
@@ -4,6 +4,7 @@ import contextlib
 import functools
 import os
 import sys
+import sysconfig
 from collections.abc import Generator
 from collections.abc import Sequence
 
@@ -48,7 +49,7 @@ def _read_pyvenv_cfg(filename: str) -> dict[str, str]:
 
 def bin_dir(venv: str) -> str:
     """On windows there's a different directory for the virtualenv"""
-    bin_part = 'Scripts' if sys.platform == 'win32' else 'bin'
+    bin_part = 'Scripts' if sys.platform == 'win32' and not "mingw" in sysconfig.get_platform() else 'bin'
     return os.path.join(venv, bin_part)
```

**Comment by asottile** [comment]
you have a mix of windows and msys binaries then which is unsupported

**Comment by sdegrande** [comment]
A patch to the mingw package has been merged (https://github.com/msys2/MINGW-packages/commit/f1c501e769ad8fb2df59c35453f92ab1fe790bf9).

However a msys maintainer suggested a solution that may be called 'universal'. It no more implies to 'officially' support msys, and so you could possibly accept it ? (an upstream fix is better than a msys specific patch, as you may understand)

```diff
diff --git a/pre_commit/languages/python.py b/pre_commit/languages/python.py
index 0c4bb62..0513641 100644
--- a/pre_commit/languages/python.py
+++ b/pre_commit/languages/python.py
@@ -4,6 +4,7 @@ import contextlib
 import functools
 import os
 import sys
+import sysconfig
 from collections.abc import Generator
 from collections.abc import Sequence
 
@@ -47,8 +48,8 @@ def _read_pyvenv_cfg(filename: str) -> dict[str, str]:
 
 
 def bin_dir(venv: str) -> str:
-    """On windows there's a different directory for the virtualenv"""
-    bin_part = 'Scripts' if sys.platform == 'win32' else 'bin'
+    """Extract the dirname from the scripts installation path"""
+    bin_part = os.path.basename(sysconfig.get_path('scripts'))
     return os.path.join(venv, bin_part)
 
 ```

**Comment by RobinMaub** [comment]
Yes sure :) Good idea. How can we move forward on that ?

**Comment by sdegrande** [comment]
up to @asottile to accept or reject the proposal...
