### ISSUE TITLE
perltidy hook fails in container

### ISSUE THREAD

**Issue by rehsack** [pre-commit/pre-commit#3238]
### search you tried in the issue tracker

Several times, different people

### describe your issue

I am trying to get a new hook installed for our local githooks additions but run (only in container) into:
```
$ pre-commit install --install-hooks
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/Yelp/detect-secrets.
[INFO] Initializing environment for https://github.com/executablebooks/mdformat.
[INFO] Initializing environment for https://github.com/executablebooks/mdformat:mdformat-gfm.
[INFO] Initializing environment for https://github.com/shellcheck-py/shellcheck-py.
[INFO] Initializing environment for https://github.com/perltidy/perltidy.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/Yelp/detect-secrets.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/executablebooks/mdformat.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/shellcheck-py/shellcheck-py.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/perltidy/perltidy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/cache/pre-commit/repozcvcq7j5/perl_env-default/.install_state_v1staging'
Check the log at /cache/pre-commit/pre-commit.log
```

I tried it on my MBP and my Ubuntu based Linux compile machine - not reproducible.
Unfortunately it fails in any Docker container we run.

```
$ ls -l /cache/pre-commit/
total 56
-rw-------  1 runner runner 20480 Jun 18 08:30 db.db
-rw-r--r--  1 runner runner  1438 Jun 18 08:30 pre-commit.log
drwx------  5 runner runner  4096 Jun 18 08:24 repo2m2b_pi8
drwx------  5 runner runner  4096 Jun 18 08:30 repo8f9jj274
drwx------ 13 runner runner  4096 Jun 18 08:24 repo8hdp6lo_
drwx------  8 runner runner  4096 Jun 18 08:24 repocfo4ebfa
drwx------ 10 runner runner  4096 Jun 18 08:24 repoledzgh3k
drwx------  8 runner runner  4096 Jun 18 08:24 reporlelnbki
drwx------ 10 runner runner  4096 Jun 18 08:24 repow52o_3mr
drwx------ 11 runner runner  4096 Jun 18 08:30 repozcvcq7j5
$ ls -l /cache/pre-commit/repozcvcq7j5/
total 344
-rw-r--r-- 1 runner runner    919 Jun 18 08:24 BUGS.md
-rw-r--r-- 1 runner runner 206027 Jun 18 08:24 CHANGES.md
-rw-r--r-- 1 runner runner  18092 Jun 18 08:24 COPYING
-rw-r--r-- 1 runner runner  14108 Jun 18 08:24 INSTALL.md
-rw-r--r-- 1 runner runner   1851 Jun 18 08:24 MANIFEST
-rw-r--r-- 1 runner runner   2366 Jun 18 08:24 MANIFEST.SKIP
-rw-r--r-- 1 runner runner   1245 Jun 18 08:30 MYMETA.json
-rw-r--r-- 1 runner runner    702 Jun 18 08:30 MYMETA.yml
-rw-r--r-- 1 runner runner  30856 Jun 18 08:30 Makefile
-rw-r--r-- 1 runner runner   1602 Jun 18 08:24 Makefile.PL
-rw-r--r-- 1 runner runner    769 Jun 18 08:24 README.md
-rw-r--r-- 1 runner runner     26 Jun 18 08:24 _config.yml
drwxr-xr-x 2 runner runner   4096 Jun 18 08:24 bin
drwxr-xr-x 2 runner runner   4096 Jun 18 08:24 dev-bin
drwxr-xr-x 2 runner runner   4096 Jun 18 08:24 docs
drwxr-xr-x 2 runner runner   4096 Jun 18 08:24 examples
drwxr-xr-x 3 runner runner   4096 Jun 18 08:24 lib
drwxr-xr-x 2 runner runner   4096 Jun 18 08:24 local-docs
-rw-r--r-- 1 runner runner   1067 Jun 18 08:24 perltidyrc
-rwxr-xr-x 1 runner runner   4445 Jun 18 08:24 pm2pl
drwxr-xr-x 3 runner runner   4096 Jun 18 08:24 t
```

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args:
          - --pattern
          - '^(?!((feature|hotfix|release|gh-readonly-queue)\/[a-zA-Z0-9\-\/]+)|main$).*'
          - --branch
          - ""
      - id: trailing-whitespace
        exclude: t/demo-commit-msg/6642e90-invalid-whitespace.msg
      - id: mixed-line-ending
        args:
          - --fix=lf
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
        args:
          - "--wrap=120"
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/perltidy/perltidy
    rev: "20240511.03"
    hooks:
      - id: perltidy
```

### version information

```
pre-commit version: 3.7.1
git --version: git version 2.34.1
sys.version:
    3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/cache/pre-commit/repozcvcq7j5/perl_env-default/.install_state_v1staging'
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/main.py", line 399, in main
    return install(
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/commands/install_uninstall.py", line 139, in install
    install_hooks(config_file, store)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/commands/install_uninstall.py", line 145, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/usr/local/lib/python3.10/dist-packages/pre_commit/repository.py", line 110, in _hook_install
    with open(staging, 'w') as state_file:
FileNotFoundError: [Errno 2] No such file or directory: '/cache/pre-commit/repozcvcq7j5/perl_env-default/.install_state_v1staging'
```

**Comment by shockrifleut** [comment]
I'm the maintainer of said Docker image. It's a rather simple image based on `debian:stable-slim` and essentially just installs git, python, pip and virtualenv using apt. Afterwards pre-commit is installed into the system using pip:

```dockerfile
FROM debian:stable-slim

ARG WORKSPACE_DIR="/workspace"
ARG PRE_COMMIT_HOME="/cache/pre-commit"

# Install all required OS packages and generate the system locale
RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt/lists \
    export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install --no-install-recommends --yes \
        git \
        python3 \
        python3-pip \
        python3-virtualenv \
        openssh-client

# pre-commit version to install
ARG PRE_COMMIT_VERSION="3.7.1"

RUN pip install --no-cache-dir --disable-pip-version-check --root-user-action ignore --break-system-packages \
        "pre-commit==${PRE_COMMIT_VERSION}" \
    && mkdir -vp \
        "${WORKSPACE_DIR}" \
        "${PRE_COMMIT_HOME}"

# create pre-commit cache and project directories
ENV PRE_COMMIT_HOME="${PRE_COMMIT_HOME}"
ENV WORKSPACE_DIR="${WORKSPACE_DIR}"
```

Using `ubuntu:22.04` as base for the image yields the same result.

**Comment by rehsack** [comment]
> sounds like you're missing the perl packaging tools?

That was also my first idea.

```
$ docker run --rm --interactive --tty --entrypoint /bin/bash -v ${PWD}:/home/runner/project -v${HOME}/.ssh:/home/runner/.ssh custom/plsw-linux-tools-pre-commit-docker:latest
runner@251fcfb2c89e:/$ cd ~/project/
runner@251fcfb2c89e:~/project$ which perl
/usr/bin/perl
runner@251fcfb2c89e:~/project$ which cpan
/usr/bin/cpan
runner@251fcfb2c89e:~/project$ perl -v

This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-gnu-thread-multi
(with 60 registered patches, see perl -V for more detail)

Copyright 1987-2021, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

runner@251fcfb2c89e:~/project$ cat /etc/issue
Ubuntu 22.04.4 LTS \n \l
runner@251fcfb2c89e:~/project$
```

I agree, something is not as `pre-commit` expects it. But I had earlier a problem with a _broken perl environment_ and there was a clear report in `pre-commit.log` was went wrong.

**Comment by asottile** [comment]
I notice you have `runner` as your user but that's not in your "reproduction" so there's at least something you've not shown

**Comment by rehsack** [comment]
Yes, don't know why @shockrifleut didn't add the 2nd part of the Dockerfile.

```
RUN mkdir -vp \
    "${PRE_COMMIT_HOME}" \
    "${WORKSPACE_DIR}"

# create local user to use in container
# override USER_UID and / or USER_GID according to your needs if required.
ARG USER_UID="1000"
ARG USER_GID="1000"
ARG USER_NAME="pre-commit"
ARG USER_GROUP_NAME="${USER_NAME}"

RUN ( \
        getent group "${USER_GROUP_NAME}" > /dev/null 2>&1 \
        || groupadd --gid "${USER_GID}" "${USER_GROUP_NAME}" \
    ) \
    && useradd \
        --comment "Primary container user" \
        --uid "${USER_UID}" \
        --gid "${USER_GID}" \
        --create-home \
        --shell "/bin/bash" \
        --groups sudo \
        "${USER_NAME}"

RUN chown -hR ${USER_UID}:${USER_GID} \
    "${PRE_COMMIT_HOME}" \
    "${WORKSPACE_DIR}"

USER ${USER_NAME}

# entrypoint script for the container
COPY "resources/entrypoint.sh" "/usr/local/bin/entrypoint"
ENTRYPOINT [ "/usr/local/bin/entrypoint" ]
```

**Comment by asottile** [comment]
I'm not exactly a free debugging service but I do know that this works elsewhere such as in https://github.com/pre-commit-ci/runner-image so you'll need to work out a minimal reproduction and figure out why your image doesn't work

**Comment by asottile** [comment]
so... debug a bit and figure it out?

start with something actually minimal?

use a `breakpoint()` ?

**Comment by rehsack** [comment]
I really thought about a log or failure report in `pre-commit.log` ;)

You might agree that the error 

```
FileNotFoundError: [Errno 2] No such file or directory: '/cache/pre-commit/repozcvcq7j5/perl_env-default/.install_state_v1staging'
```
isn't that helpful.

Something like
```
Running command '/usr/bin/perl' '/usr/bin/cpan' ... didn't succeed with 
<STDERR>
```
Would help more.

Unfortunately I am very poor working with python at all (which is also not your problem). I ask kindly anyway to get in a future version an improved error message when such a call fails. Would that be possible?

**Comment by shockrifleut** [comment]
> Yes, don't know why @shockrifleut didn't add the 2nd part of the Dockerfile.
> 
> ```dockerfile
> RUN mkdir -vp \
>     "${PRE_COMMIT_HOME}" \
>     "${WORKSPACE_DIR}"
> 
> # create local user to use in container
> # override USER_UID and / or USER_GID according to your needs if required.
> ARG USER_UID="1000"
> ARG USER_GID="1000"
> ARG USER_NAME="runner"
> ARG USER_GROUP_NAME="${USER_NAME}"
> 
> RUN ( \
>         getent group "${USER_GROUP_NAME}" > /dev/null 2>&1 \
>         || groupadd --gid "${USER_GID}" "${USER_GROUP_NAME}" \
>     ) \
>     && useradd \
>         --comment "Primary container user" \
>         --uid "${USER_UID}" \
>         --gid "${USER_GID}" \
>         --create-home \
>         --shell "/bin/bash" \
>         --groups sudo \
>         "${USER_NAME}"
> 
> RUN chown -hR ${USER_UID}:${USER_GID} \
>     "${PRE_COMMIT_HOME}" \
>     "${WORKSPACE_DIR}"
> 
> USER ${USER_NAME}
> 
> # entrypoint script for the container
> COPY "resources/entrypoint.sh" "/usr/local/bin/entrypoint"
> ENTRYPOINT [ "/usr/local/bin/entrypoint" ]
> ```

I just wanted to keep it simple, but yes, I silently omitted the user part from the Dockerfile. 😉The pre-commit-ci image sounds like a good starting point for further investigation though.

**Comment by asottile** [comment]
the error isn't really wrong and I don't there's much that could be improved with it: pre-commit expected the perl installation to make a directory structure and it... didn't.  there was no error from perl itself

**Comment by rehsack** [comment]
I currently struggle to reproduce a former error on my MBP, where `pre-commit` kept the erroneous run of `cpan` in `~/.cache/pre-commit/pre-commit.log`. 
What could be done (I am thinking loud): Either the output of the command is captured and added to the log like:
```
FileNotFoundError: [Errno 2] No such file or directory: '/cache/pre-commit/repozcvcq7j5/perl_env-default/.install_state_v1staging'
Previous command was: ...
Command output: ...
```

Or:
```
FileNotFoundError: [Errno 2] No such file or directory: '/cache/pre-commit/repozcvcq7j5/perl_env-default/.install_state_v1staging'
Executed command was: [...] using environment $venv 
```

Or even simpler:
```
FileNotFoundError: [Errno 2] No such file or directory: '/cache/pre-commit/repozcvcq7j5/perl_env-default/.install_state_v1staging'
Setting up $lang failed. Please check manually.
```

To be honest - I realised by this discussion that `pre-commit` tried to create `/cache/pre-commit/repogitfs1dy/perl_env-default/` as a venv. Being more explicit for non-insiders ;)

Because the hint: _Something with your perl environment seems broken_ (not using these words but that's what I understood) lead me to `echo "" | cpan` which complains regarding missing `make` utility.

**Comment by asottile** [comment]
what you're suggesting is basically impossible.  please just debug your problem and still trying to solutioneer
