### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/run/wrappers/bin/op' on NixOS

### ISSUE THREAD

**Issue by aRustyDev** [pre-commit/pre-commit#3252]
### search you tried in the issue tracker

is:issue permissionerror

### describe your issue

I'm trying to get pre-commit to run as a subcommand of 1Password-cli via their `op run --` syntax like `op run -- git commit...`

I'm running this on a NixOS system so I'm managing install/version of `git`, `op`, & `pre-commit` via the Nix config

I'm not sure if this is a pre-commit sourced error or a 1Password-cli error, but since a similar issue related to a database appeared in the issues I'm guessing this could be a Pre-Commit issue. 

From what I can tell the git-hook isn't able to run the `op` binary, but what makes me confused is that I can run this same code from my macOS w/o any issues. Which makes it entirely plausible that NixOS is the root of the issue, and that I just haven't included the right configs to make this work. 

## Error
`ggshield (pre-commit)....................................................An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '/run/wrappers/bin/op'`

### `/etc/nixos/configuration.nix`
```nix
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Bootloader.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";
  boot.loader.grub.useOSProber = true;

  networking.hostName = "nixos"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "America/New_York";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable the GNOME Desktop Environment.
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;

  # Configure keymap in X11
  services.xserver = {
    layout = "us";
    xkbVariant = "";
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound with pipewire.
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # If you want to use JACK applications, uncomment this
    #jack.enable = true;

    # use the example session manager (no others are packaged yet so this is enabled by default,
    # no need to redefine it in your config for now)
    #media-session.enable = true;
  };

  # Enable touchpad support (enabled default in most desktopManager).
  # services.xserver.libinput.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.adam = {
    isNormalUser = true;
    description = "adam";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [
    #  thunderbird
    ];
  };

  # Enable automatic login for the user.
  services.xserver.displayManager.autoLogin.enable = true;
  services.xserver.displayManager.autoLogin.user = "adam";

  # Workaround for GNOME autologin: https://github.com/NixOS/nixpkgs/issues/103746#issuecomment-945091229
  systemd.services."getty@tty1".enable = false;
  systemd.services."autovt@tty1".enable = false;

  # Install firefox.
  programs.firefox.enable = true;

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
  #  vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
  #  wget
    git
    vim
    _1password
    _1password-gui
    pre-commit
    python3
  ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
   programs._1password.enable = true;
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "24.05"; # Did you read the comment?

}
```

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
#      - id: detect-aws-credentials
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.29.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
        entry: op run --env-file="./op.env" -- ggshield secret scan pre-commit
```

### version information

```
pre-commit version: 3.7.1
git --version: git version 2.44.1
sys.version:
    3.11.9 (main, Apr  2 2024, 08:25:04) [GCC 13.2.0]
sys.executable: /nix/store/4rf5qybw37b4lh1g0xczlv14sqdbmnpm-python3-3.11.9/bin/python3.11
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '/run/wrappers/bin/op'
```

```
Traceback (most recent call last):
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/main.py", line 389, in main
    return hook_impl(
           ^^^^^^^^^^
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/commands/hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/commands/run.py", line 444, in run
    return _run_hooks(config, hooks, skips, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/commands/run.py", line 296, in _run_hooks
    current_retval, prior_diff = _run_single_hook(
                                 ^^^^^^^^^^^^^^^^^
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/commands/run.py", line 193, in _run_single_hook
    retcode, out = language.run_hook(
                   ^^^^^^^^^^^^^^^^^^
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/lang_base.py", line 187, in basic_run_hook
    return run_xargs(
           ^^^^^^^^^^
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/lang_base.py", line 170, in run_xargs
    return xargs.xargs(cmd, file_args, target_concurrency=jobs, color=color)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/xargs.py", line 151, in xargs
    cmd = parse_shebang.normalize_cmd(cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/parse_shebang.py", line 80, in normalize_cmd
    cmd = parse_filename(exe) + (exe,) + cmd[1:]
          ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1v97z47ckf2kv0fb2r4z2ggv3ls7jb86-pre-commit-3.7.1/lib/python3.11/site-packages/pre_commit/parse_shebang.py", line 19, in parse_filename
    return parse_shebang_from_file(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/47bqjsx4ig7hbmhiw0yyz7bigydhqwlf-python3.11-identify-2.5.36/lib/python3.11/site-packages/identify/identify.py", line 213, in parse_shebang_from_file
    with open(path, 'rb') as f:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/run/wrappers/bin/op'
```

**Comment by asottile** [comment]
nix is "at your own support" as they do very unconventional things to make stuff "work"

**Comment by aRustyDev** [comment]
Even if its not supported, I ended up finding a solution. 
It seems that NixOS stores the `op` bin in a weird way that changes the permissions on it? (still not entirely clear on this part)

But my solution ended up being to do the following in my `.pre-commit-config.yaml`
```yaml
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.29.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
        entry: bash -c 'op run --env-file="./op.env" -- ggshield secret scan pre-commit'
```

It might also have been that when pre-commit runs it tries to start a shell from python, so that might have funked up the permissions? Either way, spinning up the new shell fixed my errors.
