### ISSUE TITLE
AssertionError: BUG: expected environment for python to be healthy() immediately after install (Ubuntu 22)

### ISSUE THREAD

**Issue by kut2rng** [pre-commit/pre-commit#3256]
### search you tried in the issue tracker

AssertionError: BUG: expected environment for python to be healthy() immediately after install

### describe your issue

Running `pre-commit run --all-files` results in the following error:

```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
Check the log at /home/kut2rng/.cache/pre-commit/pre-commit.log
```

Browsing through some closed issues, they either seem to have the same message on MacOS, so the debugging instructions in replies do not apply, or a different message on Ubuntu regarding mismatched venv versions, which I do not have.

This used to work previously and seems to have popped up after I installed `conda 23.7.4`, but I am not actively in a conda venv while running the check, nor is a venv even installed for my repo.

I am on a managed PC with Ubuntu 22.04 which had `Python 3.10.12` already installed, and I installed pre-commit with:

```
pip install pre-commit
pre-commit install
``` 

### pre-commit --version

pre-commit 2.17.0

### .pre-commit-config.yaml

```yaml
repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude_types: [rst]
      - id: fix-byte-order-marker

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length=120"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      args: ["--extend-ignore=E501"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.2
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
      - id: check-github-actions
        args: ["--verbose"]
      - id: check-dependabot
        args: ["--verbose"]
```

### ~/.cache/pre-commit/pre-commit.log (if present)

```
### version information

pre-commit version: 2.17.0
git --version: git version 2.34.1
sys.version:
    3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux


### error information

An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/usr/lib/python3/dist-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/usr/lib/python3/dist-packages/pre_commit/commands/run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "/usr/lib/python3/dist-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/usr/lib/python3/dist-packages/pre_commit/repository.py", line 86, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
```

**Comment by asottile** [comment]
there are quite a few about Ubuntu 22.04 and the fixes for them -- please search around!
