### ISSUE TITLE
"virtualenv python version did not match created version" error on Windows

### ISSUE THREAD

**Issue by beiju** [pre-commit/pre-commit#3277]
### search you tried in the issue tracker

virtualenv python version did not match created version

### describe your issue

When trying to use pre-commit for the first time, I ran into the "virtualenv python version did not match created version" error. I checked every existing issue for this error message and none of them solved my problem. I'm using Windows 11 (no WSL) and I have an existing `venv` environment for my project. All the commands were run within git-bash, but I also tried `pre-commit install` through powershell with the same result.

Steps I took (all within the existing `venv` environment):
1. Add `pre-commit` to `requirements.txt` and run `pip install -r requirements.txt` (Successful)
2. `pre-commit install` (Successful)
3. `pre-commit install` (Fails with the error below)

```
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/[username redacted]/.cache/pre-commit/repojx7syx7y/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.7.final.0

Check the log at C:/Users/[username redacted]/.cache/pre-commit/pre-commit.log
```

In other issues I saw that problems with the `virtualenv` package had caused this problem. I tested `virtualenv` on my system (again, within the `venv` environment) and it seems fine:
```
$ python --version --version
Python 3.11.7 (main, Dec  7 2023, 09:07:50)  [GCC 13.2.0 64 bit (AMD64)]
$ python -m virtualenv vvv
created virtual environment CPython3.11.7.final.0-64 in 697ms
  creator CPython3Windows(dest=C:/[project path redacted]/python-preview/vvv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:/Users/[username redacted]/AppData/Local/pypa/virtualenv)
    added seed packages: pip==24.1.2, setuptools==70.3.0, wheel==0.43.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
(python-preview-venv)
$ vvv/bin/python --version --version
Python 3.11.7 (main, Dec  7 2023, 09:07:50)  [GCC 13.2.0 64 bit (AMD64)]
$ cat vvv/pyvenv.cfg
home = C:/msys64/mingw64/bin
implementation = CPython
version_info = 3.11.7.final.0
virtualenv = 20.26.3
include-system-site-packages = false
base-prefix = C:/msys64/mingw64
base-exec-prefix = C:/msys64/mingw64
base-executable = C:/msys64/mingw64/bin/python3.11.exe
```

I noticed that the path pre-commit says it's looking for Python at doesn't exist because there's no `py_env-python3.11` folder:
```
$ ls /C/Users/[username redacted]/.cache/pre-commit/repojx7syx7y/
AUTHORS.md    CONTRIBUTING.md  README.md    action.yml  gallery/    pyproject.toml  test_requirements.txt
CHANGES.md    Dockerfile       SECURITY.md  autoload/   plugin/     scripts/        tests/
CITATION.cff  LICENSE          action/      docs/       profiling/  src/            tox.ini
```

### pre-commit --version

pre-commit 3.8.0

### .pre-commit-config.yaml

```yaml
default_language_version:
    python: python3.11
repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
```

### version information

```
pre-commit version: 3.8.0
git --version: git version 2.45.1.windows.1
sys.version:
    3.11.7 (main, Dec  7 2023, 09:07:50)  [GCC 13.2.0 64 bit (AMD64)]
sys.executable: C:/[project path redacted]/python-preview-venv/bin/python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/[username redacted]/.cache/pre-commit/repojx7syx7y/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.7.final.0

```

```
Traceback (most recent call last):
  File "C:/[project path redacted]/python-preview-venv/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "C:/proj/[project path redacted]/python-preview-venv/lib/python3.11/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/proj/[project path redacted]/python-preview-venv/lib/python3.11/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:/[project path redacted]/python-preview-venv/lib/python3.11/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "C:/[project path redacted]/python-preview-venv/lib/python3.11/site-packages/pre_commit/repository.py", line 99, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: <<error retrieving version from C:/Users/[username redacted]/.cache/pre-commit/repojx7syx7y/py_env-python3.11/Scripts/python.exe>>
- expected version: 3.11.7.final.0

**Comment by asottile** [comment]
you're using an msys python which is not supported

**Comment by beiju** [comment]
Ah, sounds like yet another instance of windows being nonstandard. Thanks for your time.
