### ISSUE TITLE
Failed to read dockerfile: open Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by ToshY** [pre-commit/pre-commit#3285]
### search you tried in the issue tracker

 ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

### describe your issue

I was setting up pre-commit to use `language: docker` and when running it shows an error when building the image:

`$ pre-commit run --all-files`
```shell
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/docker', 'build', '--tag', 'pre-commit-127442fa054a012ed6fde555bb6385ba', '--label', 'PRE_COMMIT', '--pull', '.')
return code: 1
stdout: (none)
stderr:
    #0 building with "default" instance using docker driver

    #1 [internal] load build definition from Dockerfile
    #1 transferring dockerfile: 2B done
    #1 DONE 0.0s
    ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
Check the log at /home/user/.cache/pre-commit/pre-commit.log
```

Running the command separately (from above trace) in terminal `docker build --tag pre-commit-127442fa054a012ed6fde555bb6385ba --label PRE_COMMIT --pull .` gives no issues and builds correctly.

---

Directory structure as follows.

```text
/project/
├── src/
│   └── test.php
├── vendor/
│   └── bin/
│       └── php-cs-fixer
├── .pre-commit-config.yaml
├── .php-cs-fixer.dist.php
└── Dockerfile
```

Dockerfile

```Dockerfile
FROM php:8.1-cli

WORKDIR /app

RUN apt-get update && apt-get install -y \
        git \
        unzip \
        libicu-dev \
        libzip-dev \
    && docker-php-ext-install zip intl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2.5 /usr/bin/composer /usr/bin/composer

COPY . .
```

### pre-commit --version

pre-commit 3.8.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: phpcsfixer
        name: PHP-CS-Fixer
        entry: vendor/bin/php-cs-fixer
        args: ['fix', '--path-mode=intersection', '--config=.php-cs-fixer.dist.php']
        language: docker
        files: \.php$
```

### version information

```
pre-commit version: 3.8.0
git --version: git version 2.34.1
sys.version:
    3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/docker', 'build', '--tag', 'pre-commit-127442fa054a012ed6fde555bb6385ba', '--label', 'PRE_COMMIT', '--pull', '.')
return code: 1
stdout: (none)
stderr:
    #0 building with "default" instance using docker driver

    #1 [internal] load build definition from Dockerfile
    #1 transferring dockerfile: 2B done
    #1 DONE 0.0s
    ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/user/.local/lib/python3.10/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
  File "/home/user/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/user/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/home/user/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 94, in _hook_install
    lang.install_environment(
  File "/home/user/.local/lib/python3.10/site-packages/pre_commit/languages/docker.py", line 100, in install_environment
    build_docker_image(prefix, pull=True)
  File "/home/user/.local/lib/python3.10/site-packages/pre_commit/languages/docker.py", line 87, in build_docker_image
    lang_base.setup_cmd(prefix, cmd)
  File "/home/user/.local/lib/python3.10/site-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/docker', 'build', '--tag', 'pre-commit-127442fa054a012ed6fde555bb6385ba', '--label', 'PRE_COMMIT', '--pull', '.')
return code: 1
stdout: (none)
stderr:
    #0 building with "default" instance using docker driver

    #1 [internal] load build definition from Dockerfile
    #1 transferring dockerfile: 2B done
    #1 DONE 0.0s
    ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```

**Comment by asottile** [comment]
pre-commit never installs from the app under test
