### ISSUE TITLE
KeyboardInterrupt'ed pre-commit resulted in rollback of unstaged files. 

### ISSUE THREAD

**Issue by blue-hexagon** [pre-commit/pre-commit#3305]
### search you tried in the issue tracker

pre-commit rollback

### describe your issue

I accidentially comitted with unstaged files and did a Ctrl+C KeyboardInterrupt to stop pre-commit - this made multiple unstaged files roll back to the previous commit, deleting serveral unstaged changes.

This is the terminal output - see also pre-commit.log.
---
(cthulhu-py3.11) PS C:\Users\username\Desktop\DevProjects\Cthulhu> git commit -m "a"                 
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to C:\Users\username\.cache\pre-commit\patch1726833940-96964.
(cthulhu-py3.11) PS C:\Users\username\Desktop\DevProjects\Cthulhu> [WARNING] Stashed changes conflicted with hook auto-fixes... Rolling back fixes...
An unexpected error has occurred: CalledProcessError: command: ('C:/Program Files/Git/mingw64/libexec/git-core\\git.EXE', '-c', 'submodule.recurse=0', 'checkout', '--', '.')
return code: 255
stdout: (none)
stderr:
    error: unable to unlink old 'app_log.txt': Invalid argument
Check the log at C:\Users\username\.cache\pre-commit\pre-commit.log

### pre-commit --version

3.8.0

### .pre-commit-config.yaml

```yaml
repos:
  - repo: local
    hooks:
      - id: todo-finder
        name: Find TODOs, FIXMEs etc.
        entry: find_todos
        language: system
        types: [ python ]
        args:
          - '--match'
          - 'TODO'
          - 'IMPLEMENT'
          - 'FIXME'
          - 'HACK'
          - 'NOTE'
          - 'WORKAROUND'
          - "--use-staged-files"
      - id: python-check-blanket-noqa
        name: check blanket noqa
        description: 'Enforce that `noqa` annotations always occur with specific codes. Sample annotations: `# noqa: F401`, `# noqa: F401,W203`'
        entry: '(?i)# noqa(?!: )'
        language: pygrep
        types: [ python ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [ "--line-length", "140","--exclude","\\.git|\\.docs|\\.idea|\\.mypy_cache|\\.pytest_cache|deploy|in|logs|out|dist|build|_build", "--target-version", "py311" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        types: [ python ]
        args: [ "--profile", "black", "--filter-files" ]
```

### version information

```
pre-commit version: 3.8.0
git --version: git version 2.45.1.windows.1
sys.version:
    3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
sys.executable: C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Scripts\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:/Program Files/Git/mingw64/libexec/git-core\\git.EXE', '-c', 'submodule.recurse=0', 'checkout', '--', '.')
return code: 255
stdout: (none)
stderr:
    error: unable to unlink old 'app_log.txt': Invalid argument
```

```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\staged_files_only.py", line 81, in _unstaged_changes_cleared
    cmd_output_b(*_CHECKOUT_CMD, env=no_checkout_env)
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\util.py", line 107, in cmd_output_b
    stdout_b, stderr_b = proc.communicate()
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1628, in _communicate
    self.stdout_thread.join(self._remaining_time(endtime))
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1119, in join
    self._wait_for_tstate_lock()
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1139, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\staged_files_only.py", line 29, in _git_apply
    cmd_output_b('git', *args)
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:/Program Files/Git/mingw64/libexec/git-core\\git.EXE', 'apply', '--whitespace=nowarn', 'C:\\Users\\username\\.cache\\pre-commit\\patch1726833940-96964')
return code: 1
stdout: (none)
stderr:
    error: patch failed: app_log.txt:18282
    error: app_log.txt: patch does not apply
    error: patch failed: src/cli/parser.py:1
    error: src/cli/parser.py: patch does not apply
    error: patch failed: src/cli/terminal/custom_logger/codes.py:15
    error: src/cli/terminal/custom_logger/codes.py: patch does not apply
    error: patch failed: src/conf/playbook_parser/app_log.txt:0
    error: src/conf/playbook_parser/app_log.txt: patch does not apply
    error: patch failed: src/conf/playbook_parser/playbook_parser.py:50
    error: src/conf/playbook_parser/playbook_parser.py: patch does not apply
    error: patch failed: src/conf/playbook_parser/playbook_validator.py:1
    error: src/conf/playbook_parser/playbook_validator.py: patch does not apply
    error: patch failed: src/data_distributor/payload_distributor.py:152
    error: src/data_distributor/payload_distributor.py: patch does not apply

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\staged_files_only.py", line 86, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\staged_files_only.py", line 32, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:/Program Files/Git/mingw64/libexec/git-core\\git.EXE', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', 'C:\\Users\\username\\.cache\\pre-commit\\patch1726833940-96964')
return code: 1
stdout: (none)
stderr:
    error: patch failed: app_log.txt:18282
    error: app_log.txt: patch does not apply
    error: patch failed: src/cli/parser.py:1
    error: src/cli/parser.py: patch does not apply
    error: patch failed: src/cli/terminal/custom_logger/codes.py:15
    error: src/cli/terminal/custom_logger/codes.py: patch does not apply
    error: patch failed: src/conf/playbook_parser/app_log.txt:0
    error: src/conf/playbook_parser/app_log.txt: patch does not apply
    error: patch failed: src/conf/playbook_parser/playbook_parser.py:50
    error: src/conf/playbook_parser/playbook_parser.py: patch does not apply
    error: patch failed: src/conf/playbook_parser/playbook_validator.py:1
    error: src/conf/playbook_parser/playbook_validator.py: patch does not apply
    error: patch failed: src/data_distributor/payload_distributor.py:152
    error: src/data_distributor/payload_distributor.py: patch does not apply

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\main.py", line 389, in main
    return hook_impl(
           ^^^^^^^^^^
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\commands\hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\commands\run.py", line 420, in run
    exit_stack.enter_context(staged_files_only(store.directory))
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 517, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\staged_files_only.py", line 112, in staged_files_only
    with _intent_to_add_cleared(), _unstaged_changes_cleared(patch_dir):
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\staged_files_only.py", line 95, in _unstaged_changes_cleared
    cmd_output_b(*_CHECKOUT_CMD, env=no_checkout_env)
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\cthulhu-c7C9JFLT-py3.11\Lib\site-packages\pre_commit\util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:/Program Files/Git/mingw64/libexec/git-core\\git.EXE', '-c', 'submodule.recurse=0', 'checkout', '--', '.')
return code: 255
stdout: (none)
stderr:
    error: unable to unlink old 'app_log.txt': Invalid argument
```

**Comment by asottile** [comment]
if you ^C twice this is kind of unavoidable -- fortunately the changes are never lost (see the first line of your output)
