### ISSUE TITLE
Wrong version of pep8 installed

### ISSUE THREAD

**Issue by ustun** [pre-commit/pre-commit#331]
I ran the instructions on the website and got the following error:

```
Traceback (most recent call last):
  File "/Users/ustun/.pre-commit/repopKP6LH/py_env-default/bin/check-added-large-files", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/ustun/.pre-commit/repopKP6LH/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/Users/ustun/.pre-commit/repopKP6LH/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/Users/ustun/.pre-commit/repopKP6LH/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/ustun/.pre-commit/repopKP6LH/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/ustun/.pre-commit/repopKP6LH/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/ustun/.pre-commit/repopKP6LH/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pep8 1.6.2 (/usr/local/Cellar/pre-commit/0.6.2/libexec/vendor/lib/python2.7/site-packages), Requirement.parse('pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7'), set(['flake8']))

```

Seems like pep8 1.6.2 is being installed somehow, which flake8 doesn't like.

**Comment by ustun** [comment]
It is probably autopep8 pulling pep8 1.6.2, I'm investigating further.

**Comment by ustun** [comment]
I will close and reopen in the correct repository: https://github.com/pre-commit/pre-commit-hooks

**Comment by asottile** [comment]
Ah yep, I never updated the refs there after fixing the problem in the hooks repo.

You should be able to fix this with `pre-commit autoupdate`, I'll fix the examples on the website :)

**Comment by asottile** [comment]
Should be fixed here: https://github.com/pre-commit/pre-commit.github.io/commit/c3b90a958d7d2ad448b9996eee6cf930782b1bae

**Comment by asottile** [comment]
The website should be up-to-date now

**Comment by asottile** [comment]
@ustun does the new example work correctly for you?

**Comment by ustun** [comment]
Thanks, seems to work, though it might be that I ran autoupdate and then deleted the tool, and then reinstalled it, not sure which fixed it, but it works now :)
--
Ustun Ozgur

Founder, Ustun Ozgur Software


http://ustunozgur.com
https://twitter.com/UstunOzgur
https://tr.linkedin.com/in/ustunozgur

Skype: ustunozgur
