### ISSUE TITLE
Not easy to install locally maintained dependencies in Python hook

### ISSUE THREAD

**Issue by sakurai-youhei** [pre-commit/pre-commit#3329]
### search you tried in the issue tracker

Yes

### describe your issue

Let's say I maintain one custom flake8 plugin in one project for some project-specific style checks.

However, integrating the custom flake8 plugin with pre-commit is challenging because pre-commit runs pip in a location other than the project path, which doesn't allow dependencies to be installed through relative paths.

The following are possible workarounds:

1. Specify the full path to the dependency, such as `/full/path/to/project/locally-maintained-flake8-plugin`.
2. Specify the VCS path to the dependency, such as `git+https://url/to/project.git#egg=locally-maintained-flake8-plugin&subdirectory=locally-maintained-flake8-plugin`.
3. Publish the dependency somewhere to allow pip to install it with its bare package name.

### pre-commit --version

pre-commit 4.0.1 (main branch)

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        additional_dependencies:
        -   -e
        -   locally-maintained-flake8-plugin
```

### version information

```
pre-commit version: 4.0.1
git --version: git version 2.46.0
sys.version:
    3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
sys.executable: /usr/bin/python3
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/sakurai/.cache/pre-commit/repotfbw004w/py_env-python3/bin/python', '-mpip', 'install', '.', '-e', 'locally-maintained-flake8-plugin')
return code: 1
stdout: (none)
stderr:
    ERROR: locally-maintained-flake8-plugin is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```

```
Traceback (most recent call last):
  File "/home/sakurai/.local/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/sakurai/.local/lib/python3.10/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
  File "/home/sakurai/.local/lib/python3.10/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/sakurai/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 229, in install_hook_envs
    _hook_install(hook)
  File "/home/sakurai/.local/lib/python3.10/site-packages/pre_commit/repository.py", line 85, in _hook_install
    lang.install_environment(
  File "/home/sakurai/.local/lib/python3.10/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "/home/sakurai/.local/lib/python3.10/site-packages/pre_commit/lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/sakurai/.local/lib/python3.10/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/sakurai/.cache/pre-commit/repotfbw004w/py_env-python3/bin/python', '-mpip', 'install', '.', '-e', 'locally-maintained-flake8-plugin')
return code: 1
stdout: (none)
stderr:
    ERROR: locally-maintained-flake8-plugin is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```

**Comment by asottile** [comment]
yes is not a search term.  there are tens of duplicates please actually search next time
