### ISSUE TITLE
Python 3.13 SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by TimKnight-DWP** [pre-commit/pre-commit#3330]
### search you tried in the issue tracker

yes

### describe your issue

I have upgraded to pre-commit 4.0.1 via Brew and now I am getting a lot of errors related to python 3.13:

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/bin/python', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/tim.knight1/.cache/pre-commit/repo0bu4bxkj/node_env-default')
return code: 1
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1319, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
        ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  encode_chunked=req.has_header('Transfer-encoding'))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1336, in request
        self._send_request(method, url, body, headers, encode_chunked)
        ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1382, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1331, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1091, in _send_output
        self.send(msg)
        ~~~~~~~~~^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1035, in send
        self.connect()
        ~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1477, in connect
        self.sock = self._context.wrap_socket(self.sock,
                    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
                                              server_hostname=server_hostname)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 455, in wrap_socket
        return self.sslsocket_class._create(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
            sock=sock,
            ^^^^^^^^^^
        ...<5 lines>...
            session=session
            ^^^^^^^^^^^^^^^
        )
        ^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1076, in _create
        self.do_handshake()
        ~~~~~~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1372, in do_handshake
        self._sslobj.do_handshake()
        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1548, in <module>
        main()
        ~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1119, in main
        args.node = get_last_stable_node_version()
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1052, in get_last_stable_node_version
        return _get_versions_json()[0]['version'].lstrip('v')
               ~~~~~~~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1028, in _get_versions_json
        response = urlopen('%s/index.json' % src_base_url)
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 652, in urlopen
        return urllib2.urlopen(req)
               ~~~~~~~~~~~~~~~^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 189, in urlopen
        return opener.open(url, data, timeout)
               ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 489, in open
        response = self._open(req, data)
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 506, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
                                  '_open', req)
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 466, in _call_chain
        result = func(*args)
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1367, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            context=self._context)
                            ^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1322, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)>
Check the log at /Users/tim.knight1/.cache/pre-commit/pre-commit.log
```

### pre-commit --version

pre-commit 4.0.1

### .pre-commit-config.yaml

```yaml
%YAML 1.2
# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
---
default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
  - commit-msg
  - post-commit
  - pre-push

default_language_version:
  # force all unspecified python hooks to run python3.12 (most do not yet support 3.13)
  python: python3.12

default_stages:
  - pre-commit

fail_fast: true

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        args:
          - --extends="@commitlint/config-conventional"
        stages:
          - commit-msg
        additional_dependencies:
          - "@commitlint/config-conventional@19.5.0"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        stages:
          - pre-commit
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        stages:
          - pre-commit
      - id: check-shebang-scripts-are-executable
        stages:
          - pre-commit
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args:
          - --unsafe
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
        stages:
          - pre-commit
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/DavidAnson/markdownlint-cli2/
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
        additional_dependencies:
          - markdownlint-rule-titlecase
          - markdownlint-cli2-formatter-codequality

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.3.3

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.15.1
    hooks:
      - id: cspell
        args:
          - --dot
          - --gitignore
          - --no-must-find-files
          - --no-progress
          - --no-summary
        additional_dependencies:
          - "@cspell/dict-en-gb@4.1.49"
        stages:
          - pre-commit
          - commit-msg
        exclude: |
          (?x)^(
            .gitlab/CODEOWNERS
          )$

  - repo: https://gitlab.com/adam-moss/pre-commit-trailer
    rev: v1.1.0
    hooks:
      - id: add-pre-commit-config-trailer
      - id: add-pre-commit-user-skipped-trailer

  - repo: https://gitlab.com/adam-moss/pre-commit-ssh-git-signing-key
    rev: v1.0.0
    hooks:
      - id: add-ssh-git-signing-key
      - id: remove-ssh-git-signing-key

  - repo: https://gitlab.com/repo-hooks/pre-commit-community-health
    rev: v1.0.0-alpha
    hooks:
      - id: block-commit-no-verify
      - id: block-push-skip-ci

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-gitlab-ci
      - id: check-renovate
      - id: check-jsonschema
        files: .*\.apko\.yaml$
        args:
          [
            "--schemafile",
            "https://raw.githubusercontent.com/chainguard-dev/apko/main/pkg/build/types/schema.json",
          ]

  - repo: git@gitlab.com:dwp/secure-development/images/conftest-project-metadata
    rev: v1.2.2
    hooks:
      - id: project-metadata

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.20.1
    hooks:
      - id: gitleaks
        stages:
          - pre-commit
      - id: gitleaks
        stages:
          - manual
        entry: gitleaks detect --redact --verbose
```

### version information

```
pre-commit version: 4.0.1
git --version: git version 2.39.3 (Apple Git-146)
sys.version:
    3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.executable: /Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/bin/python', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/tim.knight1/.cache/pre-commit/repo0bu4bxkj/node_env-default')
return code: 1
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1319, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
        ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  encode_chunked=req.has_header('Transfer-encoding'))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1336, in request
        self._send_request(method, url, body, headers, encode_chunked)
        ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1382, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1331, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1091, in _send_output
        self.send(msg)
        ~~~~~~~~~^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1035, in send
        self.connect()
        ~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1477, in connect
        self.sock = self._context.wrap_socket(self.sock,
                    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
                                              server_hostname=server_hostname)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 455, in wrap_socket
        return self.sslsocket_class._create(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
            sock=sock,
            ^^^^^^^^^^
        ...<5 lines>...
            session=session
            ^^^^^^^^^^^^^^^
        )
        ^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1076, in _create
        self.do_handshake()
        ~~~~~~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1372, in do_handshake
        self._sslobj.do_handshake()
        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1548, in <module>
        main()
        ~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1119, in main
        args.node = get_last_stable_node_version()
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1052, in get_last_stable_node_version
        return _get_versions_json()[0]['version'].lstrip('v')
               ~~~~~~~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1028, in _get_versions_json
        response = urlopen('%s/index.json' % src_base_url)
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 652, in urlopen
        return urllib2.urlopen(req)
               ~~~~~~~~~~~~~~~^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 189, in urlopen
        return opener.open(url, data, timeout)
               ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 489, in open
        response = self._open(req, data)
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 506, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
                                  '_open', req)
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 466, in _call_chain
        result = func(*args)
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1367, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            context=self._context)
                            ^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1322, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)>
```

```
Traceback (most recent call last):
  File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/pre_commit/main.py", line 389, in main
    return hook_impl(
        store,
    ...<5 lines>...
        args=args.rest[1:],
    )
  File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/pre_commit/commands/hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
                  ~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/pre_commit/repository.py", line 229, in install_hook_envs
    _hook_install(hook)
    ~~~~~~~~~~~~~^^^^^^
  File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/pre_commit/repository.py", line 85, in _hook_install
    lang.install_environment(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        hook.prefix, hook.language_version, hook.additional_dependencies,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/pre_commit/languages/node.py", line 89, in install_environment
    cmd_output_b(*cmd)
    ~~~~~~~~~~~~^^^^^^
  File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/bin/python', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/tim.knight1/.cache/pre-commit/repo0bu4bxkj/node_env-default')
return code: 1
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1319, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
        ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  encode_chunked=req.has_header('Transfer-encoding'))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1336, in request
        self._send_request(method, url, body, headers, encode_chunked)
        ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1382, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1331, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1091, in _send_output
        self.send(msg)
        ~~~~~~~~~^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1035, in send
        self.connect()
        ~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/client.py", line 1477, in connect
        self.sock = self._context.wrap_socket(self.sock,
                    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
                                              server_hostname=server_hostname)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 455, in wrap_socket
        return self.sslsocket_class._create(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
            sock=sock,
            ^^^^^^^^^^
        ...<5 lines>...
            session=session
            ^^^^^^^^^^^^^^^
        )
        ^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1076, in _create
        self.do_handshake()
        ~~~~~~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 1372, in do_handshake
        self._sslobj.do_handshake()
        ~~~~~~~~~~~~~~~~~~~~~~~~~^^
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1548, in <module>
        main()
        ~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1119, in main
        args.node = get_last_stable_node_version()
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1052, in get_last_stable_node_version
        return _get_versions_json()[0]['version'].lstrip('v')
               ~~~~~~~~~~~~~~~~~~^^
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 1028, in _get_versions_json
        response = urlopen('%s/index.json' % src_base_url)
      File "/Users/tim.knight1/.homebrew/Cellar/pre-commit/4.0.1/libexec/lib/python3.13/site-packages/nodeenv.py", line 652, in urlopen
        return urllib2.urlopen(req)
               ~~~~~~~~~~~~~~~^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 189, in urlopen
        return opener.open(url, data, timeout)
               ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 489, in open
        response = self._open(req, data)
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 506, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
                                  '_open', req)
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 466, in _call_chain
        result = func(*args)
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1367, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            context=self._context)
                            ^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tim.knight1/.homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 1322, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)>

**Comment by TimKnight-DWP** [comment]
Things I have tried:
- Installing Certifi
- Reinstalling Openssl through Brew
- Making sure my cert DIRs are exported
```
export SSL_CERT_DIR=/etc/ssl/certs
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certs.pem
export SSL_CERT_FILE=${REQUESTS_CA_BUNDLE}
export CERT_PATH=${REQUESTS_CA_BUNDLE}
export NODE_EXTRA_CA_CERTS=${REQUESTS_CA_BUNDLE}
export CA_BUNDLE_PATH="${SSL_CERT_DIR}/ca-certificates.crt"
```

**Comment by TimKnight-DWP** [comment]
I suspect it is something daft with the fact our machines have a proxy instaled on them, and it's causing some conflict, but would appreciate any pointers

**Comment by asottile** [comment]
this isn't a pre-commit problem.  if you want corporate support you can reach out to me directly to set up a support contract
