### ISSUE TITLE
Node hook error: Support for loading ES Module in require() is an experimental feature and might change at any time

### ISSUE THREAD

**Issue by kevinchhay-tylertech** [pre-commit/pre-commit#3336]
### search you tried in the issue tracker

es module

### describe your issue

Trying to run a sample node hook, but got the following error:

```
(node:79193) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm error Invalid package, must have name and version
```

```
// .pre-commit-hooks

- id: asdf
  name: asdf
  description: asdf
  entry: index.js
  language: node
  verbose: true
```

```
// package.json

{
    "bin": {
        "asdf": "./index.js"
    }
}
```

node script
```
// index.js

console.log("hello");
```

expected to run the script without issues and print "hello".

### pre-commit --version

pre-commit 3.7.1

### .pre-commit-config.yaml

```yaml
repos:
  - repo: https://github.com/asdf/git-hooks.git
    rev: v1.0.0
    hooks:
      - id: asdf
        stages: [pre-commit, post-merge]
        always_run: true

default_install_hook_types: [pre-commit, post-merge]
```

### version information

```
pre-commit version: 3.7.1
git --version: git version 2.39.3 (Apple Git-146)
sys.version:
    3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
sys.executable: /opt/homebrew/Cellar/pre-commit/3.7.1/libexec/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/kevinchhay/.cache/pre-commit/repo0t0vyv47/node_env-default/bin/node', '/Users/kevinchhay/.cache/pre-commit/repo0t0vyv47/node_env-default/bin/npm', 'pack')
return code: 1
stdout: (none)
stderr:
    (node:79193) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    npm error Invalid package, must have name and version
    npm error A complete log of this run can be found in: /Users/kevinchhay/.npm/_logs/2024-10-16T18_25_02_283Z-debug-0.log
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 238, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/repository.py", line 94, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/languages/node.py", line 101, in install_environment
    _, pkg, _ = cmd_output('npm', 'pack', cwd=prefix.prefix_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/util.py", line 117, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.7.1/libexec/lib/python3.12/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/kevinchhay/.cache/pre-commit/repo0t0vyv47/node_env-default/bin/node', '/Users/kevinchhay/.cache/pre-commit/repo0t0vyv47/node_env-default/bin/npm', 'pack')
return code: 1
stdout: (none)
stderr:
    (node:79193) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    npm error Invalid package, must have name and version
    npm error A complete log of this run can be found in: /Users/kevinchhay/.npm/_logs/2024-10-16T18_25_02_283Z-debug-0.log
```

**Comment by asottile** [comment]
search better there's an exact duplicate and it's not a pre-commit problem
