### ISSUE TITLE
node installed via nvm is not found/ignored

### ISSUE THREAD

**Issue by mschoettle** [pre-commit/pre-commit#3341]
### search you tried in the issue tracker

node system default latest

### describe your issue

After running `pre-commit clean` and running `pre-commit` I got the error in the log below.

Running `which node` gives me:

```shell
$ which node
/Users/mschoettle/.nvm/versions/node/v20.17.0/bin/node
```

The complete log shows that node 23.0.0 is used:

```text
1 info using npm@10.9.0
2 info using node@v23.0.0
```

I did some digging and found that `lang_base.exe_exists` returns `False` for `node` due to the following condition:

https://github.com/pre-commit/pre-commit/blob/cc4a52241565440ce200666799eef70626457488/pre_commit/lang_base.py#L80

Would it be possible to allow the `nvm` installed node (or removing this condition if that is acceptable)?

### pre-commit --version

pre-commit 4.0.1

### .pre-commit-config.yaml

```yaml
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.14.0
  hooks:
  - id: markdownlint-cli2
```

### version information

```
pre-commit version: 4.0.1
git --version: git version 2.47.0
sys.version:
    3.10.15 (main, Sep  7 2024, 00:20:06) [Clang 15.0.0 (clang-1500.1.0.2.5)]
sys.executable: /Users/mschoettle/myproject/.venv/bin/python3.10
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/mschoettle/.cache/pre-commit/repoj8aih6p3/node_env-default/bin/node', '/Users/mschoettle/.cache/pre-commit/repoj8aih6p3/node_env-default/bin/npm', 'pack')
return code: 254
stdout: (none)
stderr:
    (node:25885) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    npm warn tarball tarball data for file:/Users/mschoettle/.cache/pre-commit/repoj8aih6p3/ (null) seems to be corrupted. Trying again.
    npm warn tarball tarball data for file:/Users/mschoettle/.cache/pre-commit/repoj8aih6p3/ (null) seems to be corrupted. Trying again.
    npm error code ENOENT
    npm error syscall lstat
    npm error path /Users/mschoettle/.cache/pre-commit/repoj8aih6p3/arsers/jsonc-parse.js
    npm error errno -2
    npm error enoent ENOENT: no such file or directory, lstat '/Users/mschoettle/.cache/pre-commit/repoj8aih6p3/arsers/jsonc-parse.js'
    npm error enoent This is related to npm not being able to find a file.
    npm error enoent
    npm error A complete log of this run can be found in: /Users/mschoettle/.npm/_logs/2024-10-18T16_52_54_770Z-debug-0.log
```

```
Traceback (most recent call last):
  File "/Users/mschoettle/myproject/.venv/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/mschoettle/myproject/.venv/lib/python3.10/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
  File "/Users/mschoettle/myproject/.venv/lib/python3.10/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/Users/mschoettle/myproject/.venv/lib/python3.10/site-packages/pre_commit/repository.py", line 229, in install_hook_envs
    _hook_install(hook)
  File "/Users/mschoettle/myproject/.venv/lib/python3.10/site-packages/pre_commit/repository.py", line 85, in _hook_install
    lang.install_environment(
  File "/Users/mschoettle/myproject/.venv/lib/python3.10/site-packages/pre_commit/languages/node.py", line 104, in install_environment
    _, pkg, _ = cmd_output('npm', 'pack', cwd=prefix.prefix_dir)
  File "/Users/mschoettle/myproject/.venv/lib/python3.10/site-packages/pre_commit/util.py", line 117, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
  File "/Users/mschoettle/myproject/.venv/lib/python3.10/site-packages/pre_commit/util.py", line 111, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/mschoettle/.cache/pre-commit/repoj8aih6p3/node_env-default/bin/node', '/Users/mschoettle/.cache/pre-commit/repoj8aih6p3/node_env-default/bin/npm', 'pack')
return code: 254
stdout: (none)
stderr:
    (node:25885) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    npm warn tarball tarball data for file:/Users/mschoettle/.cache/pre-commit/repoj8aih6p3/ (null) seems to be corrupted. Trying again.
    npm warn tarball tarball data for file:/Users/mschoettle/.cache/pre-commit/repoj8aih6p3/ (null) seems to be corrupted. Trying again.
    npm error code ENOENT
    npm error syscall lstat
    npm error path /Users/mschoettle/.cache/pre-commit/repoj8aih6p3/arsers/jsonc-parse.js
    npm error errno -2
    npm error enoent ENOENT: no such file or directory, lstat '/Users/mschoettle/.cache/pre-commit/repoj8aih6p3/arsers/jsonc-parse.js'
    npm error enoent This is related to npm not being able to find a file.
    npm error enoent
    npm error A complete log of this run can be found in: /Users/mschoettle/.npm/_logs/2024-10-18T16_52_54_770Z-debug-0.log
```

**Comment by asottile** [comment]
as you can see from the code (which you found!) this is very intentional.  if you look at the relevant prs and discussion in duplicate issues you can also find out why.  please next time search a little more!
