### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by Sean-Brown** [pre-commit/pre-commit#336]
I'm on Windows 7. 
I installed pre-git (npm install pre-git) --save-dev.
From package.json:
"config": {
  "pre-git": {
    "pre-commit": ["npm test"]
  }
}
I try to git commit and I get the following:
(function (exports, require, module, __filename, __dirname) { "$basedir/../pre-git/bin/pre-commit.js"   "$@"
                                                                                                        ^^^^

SyntaxError: Unexpected string
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by Sean-Brown** [comment]
Looks like I'm not the only one with this problem...

**Comment by asottile** [comment]
I think you're confusing this with another project? Ours is a python package: http://pre-commit.com
