### ISSUE TITLE
Please make the health check for python version in venv less sensitive

### ISSUE THREAD

**Issue by demizer** [pre-commit/pre-commit#3371]
### search you tried in the issue tracker

AssertionError: BUG: expected environment for python to be healthy immediately after install

### describe your actual problem

Had to rebuild my hatch envs today and it pulled in 3.12.8 from https://github.com/astral-sh/python-build-standalone/releases/tag/20241205

Then I got smashed with:

```
cmd [1] | pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/henryiii/validate-pyproject-schema-store.
[INFO] Initializing environment for https://github.com/henryiii/validate-pyproject-schema-store:validate-pyproject[all].
[INFO] Initializing environment for https://github.com/astral-sh/ruff-pre-commit.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: 3.12.8.final.0
- expected version: 3.12.3.final.0

Check the log at /home/jesusa/.cache/pre-commit/pre-commit.log
```

Somehow, the `pyvenv.cfg` is getting the wrong version:

```
$ cat /home/jesusa/.cache/pre-commit/reporz1flufx/py_env-python3.12/pyvenv.cfg
home = /home/jesusa/.local/share/hatch/env/pip-compile/.pythons/3.12/python/bin
implementation = CPython
version_info = 3.12.3.final.0
virtualenv = 20.27.0
include-system-site-packages = false
base-prefix = /home/jesusa/.local/share/hatch/env/pip-compile/.pythons/3.12/python
base-exec-prefix = /home/jesusa/.local/share/hatch/env/pip-compile/.pythons/3.12/python
base-executable = /home/jesusa/.local/share/hatch/env/pip-compile/.pythons/3.12/python/bin/python3.12
```
**THE ASK**: does it have to be so strict on the version comparison? I feel like any 3.12.x version should be good. The workaround here is to comment out the health check in pre-commit, or change the python version to "external" in hatch:

```
[tool.hatch.envs.hatchpy12dev]
description = "Used for local development, including relative checkout of nv-common-util"
template = "dev"
python = "3.12"
# python-sources = ["internal"]
python-sources = ["external"]

```

Thank you!!

Output from `pre-commit.log`

### version information

```
pre-commit version: 4.0.1
git --version: git version 2.47.1
sys.version:
    3.12.8 (main, Dec  6 2024, 19:36:15) [Clang 18.1.8 ]
sys.executable: /home/jesusa/.local/share/hatch/env/pip-compile/rhsignr/5REn8xMO/hatchpy12dev/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: 3.12.8.final.0
- expected version: 3.12.3.final.0

```

```
Traceback (most recent call last):
  File "/home/jesusa/.local/share/hatch/env/pip-compile/rhsignr/5REn8xMO/hatchpy12dev/lib/python3.12/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/jesusa/.local/share/hatch/env/pip-compile/rhsignr/5REn8xMO/hatchpy12dev/lib/python3.12/site-packages/pre_commit/main.py", line 417, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jesusa/.local/share/hatch/env/pip-compile/rhsignr/5REn8xMO/hatchpy12dev/lib/python3.12/site-packages/pre_commit/commands/run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "/home/jesusa/.local/share/hatch/env/pip-compile/rhsignr/5REn8xMO/hatchpy12dev/lib/python3.12/site-packages/pre_commit/repository.py", line 229, in install_hook_envs
    _hook_install(hook)
  File "/home/jesusa/.local/share/hatch/env/pip-compile/rhsignr/5REn8xMO/hatchpy12dev/lib/python3.12/site-packages/pre_commit/repository.py", line 90, in _hook_install
    raise AssertionError(
AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: 3.12.8.final.0
- expected version: 3.12.3.final.0
```

### pre-commit --version

pre-commit 4.0.1

**Comment by asottile** [comment]
if it is being created with 3.12.8 and the virtualenv ends up at a different version then something's wrong with virtualenv and it is correct to reject that environment
