### ISSUE TITLE
pre-commit initialization fails on setuptools

### ISSUE THREAD

**Issue by cdl** [pre-commit/pre-commit#349]
For some reason, our `pre-commit` setup on CI appears to be failing to initialize. When trying to do an initial run of `pre-commit run --all-files`, this is what happens (output of `~/.pre-commit/pre-commit.log`):

```
An unexpected error has occurred: CalledProcessError: Command: ['/home/ubuntu/virtualenvs/venv-2.7.9/bin/python2.7', '-m', 'virtualenv', '/home/ubuntu/.pre-commit/repob698TI/py_env-default']
Return code: 1
Expected return code: 0
Output: 
    Using real prefix '/home/ubuntu/.pyenv/versions/2.7.9'
    New python executable in /home/ubuntu/.pre-commit/repob698TI/py_env-default/bin/python2.7
    Also creating executable in /home/ubuntu/.pre-commit/repob698TI/py_env-default/bin/python
    Installing setuptools, pip, wheel...
      Complete output from command /home/ubuntu/.pre-co...efault/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
      Collecting setuptools
      Could not fetch URL https://pypi.python.org/simple/setuptools/: There was a problem confirming the ssl certificate: [Errno 20] Not a directory - skipping
    Collecting pip
    Exception:
    Traceback (most recent call last):
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/basecommand.py", line 209, in main
        status = self.run(options, args)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/commands/install.py", line 299, in run
        requirement_set.prepare_files(finder)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 359, in prepare_files
        ignore_dependencies=self.ignore_dependencies))
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 576, in _prepare_file
        session=self.session, hashes=hashes)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 809, in unpack_url
        hashes=hashes
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 648, in unpack_http_url
        hashes)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 841, in _download_http_url
        stream=True,
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 480, in get
        return self.request('GET', url, **kwargs)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 377, in request
        return super(PipSession, self).request(method, url, *args, **kwargs)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 468, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 576, in send
        r = adapter.send(request, **kwargs)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/cachecontrol/adapter.py", line 46, in send
        resp = super(CacheControlAdapter, self).send(request, **kw)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/adapters.py", line 447, in send
        raise SSLError(e, request=request)
    SSLError: [Errno 20] Not a directory
    ----------------------------------------
    ...Installing setuptools, pip, wheel...done.
    
Errors: 
    Traceback (most recent call last):
      File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 2284, in <module>
        main()
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 703, in main
        symlink=options.symlink)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 904, in create_environment
        download=download,
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 861, in install_wheel
        call_subprocess(cmd, show_stdout=False, extra_env=env)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 781, in call_subprocess
        % (cmd_desc, proc.returncode))
    OSError: Command /home/ubuntu/.pre-co...efault/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2
    

Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pre_commit/main.py", line 147, in main
    return run(runner, args)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pre_commit/commands/run.py", line 195, in run
    repo_hooks = list(get_repo_hooks(runner))
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pre_commit/commands/run.py", line 141, in get_repo_hooks
    for repo in runner.repositories:
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pre_commit/runner.py", line 47, in repositories
    repository.require_installed()
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pre_commit/repository.py", line 115, in require_installed
    self.install()
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pre_commit/repository.py", line 185, in install
    self.additional_dependencies[language_name][language_version],
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pre_commit/languages/python.py", line 71, in install_environment
    repo_cmd_runner.run(venv_cmd)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pre_commit/prefixed_command_runner.py", line 39, in run
    return cmd_output(*replaced_cmd, __popen=self.__popen, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pre_commit/util.py", line 194, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
CalledProcessError: Command: ['/home/ubuntu/virtualenvs/venv-2.7.9/bin/python2.7', '-m', 'virtualenv', '/home/ubuntu/.pre-commit/repob698TI/py_env-default']
Return code: 1
Expected return code: 0
Output: 
    Using real prefix '/home/ubuntu/.pyenv/versions/2.7.9'
    New python executable in /home/ubuntu/.pre-commit/repob698TI/py_env-default/bin/python2.7
    Also creating executable in /home/ubuntu/.pre-commit/repob698TI/py_env-default/bin/python
    Installing setuptools, pip, wheel...
      Complete output from command /home/ubuntu/.pre-co...efault/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
      Collecting setuptools
      Could not fetch URL https://pypi.python.org/simple/setuptools/: There was a problem confirming the ssl certificate: [Errno 20] Not a directory - skipping
    Collecting pip
    Exception:
    Traceback (most recent call last):
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/basecommand.py", line 209, in main
        status = self.run(options, args)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/commands/install.py", line 299, in run
        requirement_set.prepare_files(finder)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 359, in prepare_files
        ignore_dependencies=self.ignore_dependencies))
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 576, in _prepare_file
        session=self.session, hashes=hashes)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 809, in unpack_url
        hashes=hashes
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 648, in unpack_http_url
        hashes)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 841, in _download_http_url
        stream=True,
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 480, in get
        return self.request('GET', url, **kwargs)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 377, in request
        return super(PipSession, self).request(method, url, *args, **kwargs)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 468, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/sessions.py", line 576, in send
        r = adapter.send(request, **kwargs)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/cachecontrol/adapter.py", line 46, in send
        resp = super(CacheControlAdapter, self).send(request, **kw)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/requests/adapters.py", line 447, in send
        raise SSLError(e, request=request)
    SSLError: [Errno 20] Not a directory
    ----------------------------------------
    ...Installing setuptools, pip, wheel...done.
    
Errors: 
    Traceback (most recent call last):
      File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 2284, in <module>
        main()
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 703, in main
        symlink=options.symlink)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 904, in create_environment
        download=download,
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 861, in install_wheel
        call_subprocess(cmd, show_stdout=False, extra_env=env)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 781, in call_subprocess
        % (cmd_desc, proc.returncode))
    OSError: Command /home/ubuntu/.pre-co...efault/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2
```

We're using `python 2.7.9`, with `pre-commit 0.7.6`. It also looks like if we tear down the environment completely (rather than letting our CI setup cache the pre-commit install) and reinstall it from scratch, it'll work.

**Comment by asottile** [comment]
This is caused by a broken version of virtualenv, let me see if I can find the version (we ran into this with our CI build also): 

https://github.com/pre-commit/pre-commit/commit/b0797b4c6eef64c494be9b567524d2844fd59504
https://github.com/pre-commit/pre-commit/commit/139744582b1c8425d73f11a5896a4865dee84c5f
https://github.com/pypa/pip/issues/3461

Perhaps ping that ticket?

**Comment by asottile** [comment]
I had to rm -rf ~/.pip/cache and `pre-commit clean` to remove all the remnants of the bug after upgrading to a newer version of virtualenv

**Comment by asottile** [comment]
@cdl what version of virtualenv are you using? I think 14.0.5 is the bad one in question

**Comment by asottile** [comment]
going to mark this one as closed -- I believe the issue is the one I listed above (pip)
