### ISSUE TITLE
Support cygwin on windows

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#353]
Continuing from #352, here's an additional issue that I'm running into on my machine  (though I'm using a pretty old cygwin):

```
$ pre-commit run
An unexpected error has occurred: WindowsError: [Error 3] The system cannot find the path specified: u'/tmp/foo'
Check the log at ~/.pre-commit/pre-commit.log
$ cat ~/.pre-commit/pre-commit.log
An unexpected error has occurred: WindowsError: [Error 3] The system cannot find the path specified: u'/tmp/foo'
Traceback (most recent call last):
  File "d:\tools\cygwin64\tmp\venv\lib\site-packages\pre_commit\error_handler.py", line 47, in error_handler
    yield
  File "d:\tools\cygwin64\tmp\venv\lib\site-packages\pre_commit\main.py", line 133, in main
    runner = Runner.create()
  File "d:\tools\cygwin64\tmp\venv\lib\site-packages\pre_commit\runner.py", line 30, in create
    os.chdir(root)
WindowsError: [Error 3] The system cannot find the path specified: u'/tmp/foo'
```

**Comment by asottile** [comment]
This was caused by the following:

- I was using python from C:/Python27/python.exe (windows) instead of /usr/bin/python (cygwin)
- I was using git from /usr/bin/git (cygwin)

I'm not sure it's worth supporting this usecase (cygwin git + windows python)?
