### ISSUE TITLE
Creating repositories fails in parallel

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#363]
Each process races to set up its virtualenv in the same place.

Probably needs more flock -- but how to make it work cross platform?

@chriskuehl  hits this a lot.
@ymilki just hit this as well

Workaround is to run once not-in-parallel and then it'll _just work_

Stacktraces vary, some complain of directories already existing `An unexpected error has occurred: OSError: [Errno 39] Directory not empty: '.../.pre-commit/repop35TZY/py_env-default'`

**Comment by asottile** [comment]
Collecting some of the stacktraces I'm seeing while writing a fix for this:

```
Traceback (most recent call last):
  File "/home/asottile/workspace/pre-commit/pre_commit/error_handler.py", line 48, in error_handler
    yield
  File "/home/asottile/workspace/pre-commit/pre_commit/main.py", line 221, in main
    return run(runner, args)
  File "/home/asottile/workspace/pre-commit/pre_commit/commands/run.py", line 247, in run
    repo_hooks = list(get_repo_hooks(runner))
  File "/home/asottile/workspace/pre-commit/pre_commit/commands/run.py", line 197, in get_repo_hooks
    for repo in runner.repositories:
  File "/home/asottile/workspace/pre-commit/venv/lib/python3.6/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/asottile/workspace/pre-commit/pre_commit/runner.py", line 46, in repositories
    repository.require_installed()
  File "/home/asottile/workspace/pre-commit/pre_commit/repository.py", line 177, in require_installed
    _install_all(self._venvs, self.repo_config['repo'])
  File "/home/asottile/workspace/pre-commit/venv/lib/python3.6/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/asottile/workspace/pre-commit/pre_commit/repository.py", line 166, in _venvs
    for _, hook in self.hooks:
  File "/home/asottile/workspace/pre-commit/venv/lib/python3.6/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/asottile/workspace/pre-commit/pre_commit/repository.py", line 146, in hooks
    if hook['id'] not in self.manifest.hooks:
  File "/home/asottile/workspace/pre-commit/venv/lib/python3.6/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/asottile/workspace/pre-commit/pre_commit/repository.py", line 141, in manifest
    return Manifest(self._repo_path, self.repo_config['repo'])
  File "/home/asottile/workspace/pre-commit/venv/lib/python3.6/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/asottile/workspace/pre-commit/pre_commit/repository.py", line 129, in _repo_path
    self.repo_config['repo'], self.repo_config['sha'],
  File "/home/asottile/workspace/pre-commit/pre_commit/store.py", line 131, in clone
    return self._new_repo(repo, ref, clone_strategy)
  File "/home/asottile/workspace/pre-commit/pre_commit/store.py", line 113, in _new_repo
    [repo, ref, directory],
sqlite3.IntegrityError: UNIQUE constraint failed: repos.repo, repos.ref
```

```
An unexpected error has occurred: CalledProcessError: Command: ('/home/asottile/workspace/pre-commit/venv/bin/python3.6', '-m', 'virtualenv', '/tmp/tmp.GxLgYG5f6L/repo6g4vit05/py_env-python3.6', '-p', 'python3.6')
Return code: 1
Expected return code: 0
Output: 
    Already using interpreter /home/asottile/workspace/pre-commit/venv/bin/python3.6
    Using real prefix '/usr'
    Path not in prefix '/home/asottile/workspace/pre-commit/venv/include/python3.6m' '/usr'
    New python executable in /tmp/tmp.GxLgYG5f6L/repo6g4vit05/py_env-python3.6/bin/python3.6
    
Errors: 
    Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/asottile/workspace/pre-commit/venv/lib/python3.6/site-packages/virtualenv.py", line 2328, in <module>
        main()
      File "/home/asottile/workspace/pre-commit/venv/lib/python3.6/site-packages/virtualenv.py", line 713, in main
        symlink=options.symlink)
      File "/home/asottile/workspace/pre-commit/venv/lib/python3.6/site-packages/virtualenv.py", line 925, in create_environment
        site_packages=site_packages, clear=clear, symlink=symlink))
      File "/home/asottile/workspace/pre-commit/venv/lib/python3.6/site-packages/virtualenv.py", line 1231, in install_python
        shutil.copyfile(executable, py_executable)
      File "/home/asottile/workspace/pre-commit/venv/lib/python3.6/shutil.py", line 121, in copyfile
        with open(dst, 'wb') as fdst:
    OSError: [Errno 26] Text file busy: '/tmp/tmp.GxLgYG5f6L/repo6g4vit05/py_env-python3.6/bin/python3.6'
```

**Comment by asottile** [comment]
via #594
