### ISSUE TITLE
fatal: ambiguous argument '': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by gretel** [pre-commit/pre-commit#366]
fresh install, tried running `pre-commit clean`, no change:

```
$ pip install pre-commit
Collecting pre-commit
  Using cached pre_commit-0.8.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): aspy.yaml in /Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): virtualenv in /Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): jsonschema in /Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): pyterminalsize in /Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): cached-property in /Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): nodeenv>=0.11.1 in /Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): functools32 in /Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages (from jsonschema->pre-commit)
Installing collected packages: pre-commit
Successfully installed pre-commit-0.8.0
$ pre-commit autoupdate                                          500ms
Updating git://github.com/pre-commit/pre-commit-hooks...An unexpected error has occurred: CalledProcessError: Command: ('/usr/local/bin/git', 'reset', '', '--hard')
Return code: 128
Expected return code: 0
Output: (none)
Errors:
    fatal: ambiguous argument '': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'


Check the log at ~/.pre-commit/pre-commit.log
```
```
Traceback (most recent call last):
  File "/Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages/pre_commit/main.py", line 155, in main
    return autoupdate(runner)
  File "/Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages/pre_commit/commands/autoupdate.py", line 77, in autoupdate
    new_repo_config = _update_repository(repo_config, runner)
  File "/Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages/pre_commit/commands/autoupdate.py", line 34, in _update_repository
    with cwd(repo.repo_path_getter.repo_path):
  File "/Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages/pre_commit/store.py", line 47, in repo_path
    return self._store.clone(self._repo, self._sha)
  File "/Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages/pre_commit/store.py", line 122, in clone
    cmd_output('git', 'reset', sha, '--hard', env=no_git_env())
  File "/Users/gretel/.pyenv/versions/2.7.11/envs/taxigirl-2.7.11/lib/python2.7/site-packages/pre_commit/util.py", line 197, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
CalledProcessError: Command: ('/usr/local/bin/git', 'reset', '', '--hard')
Return code: 128
Expected return code: 0
Output: (none)
Errors:
    fatal: ambiguous argument '': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'
```

**Comment by gretel** [comment]
ah, had to be explicit on `sha`:

```
---
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: HEAD
  hooks:
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-docstring-first
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: flake8
  - id: pretty-format-json
  - id: requirements-txt-fixer
  - id: trailing-whitespace
```
works fine now. maybe i was confused by the documentation.

**Comment by asottile** [comment]
You won't want to use HEAD / master, you can read more about why here: https://github.com/pre-commit/pre-commit/issues/158#issuecomment-54103765

**Comment by asottile** [comment]
The documentation on pre-commit/pre-commit-hooks has this in the README:

```yaml
    sha: ''  # Use the sha you want to point at
```

Is there a place that this should be updated that doesn't have this documentation?

**Comment by gretel** [comment]
now it gets circular. i opened an issue because '' does not work.

**Comment by asottile** [comment]
What was meant by that comment is `''` won't work and you need to pick a sha.  Perhaps you could suggest an improved comment which indicates that better?

**Comment by gretel** [comment]
let me try:

The value of `sha` should *not* be `master` or `HEAD` - both will only match the latest version at install time, and will prevent updates subsequently.
On GitHub, the id of the most recent commit can be looked up easily (i.e. [commit/master](https://github.com/pre-commit/pre-commit/commit/master)).
Alternatively, setting `sha` to `HEAD` and running `pre-commit autoupdate` before anything else will effectively update the configuration file and therefore allow updates:

```
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-docstring-first
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: pretty-format-json
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: master
    hooks:
    -   id: pylint
```
