### ISSUE TITLE
pre-commit bug when invoking eslint via npm

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit#379]
Bug reproduction:

```shell
mkdir tmp && cd tmp
git init && pre-commit install
cat <<EOF >.pre-commit-config.yaml
-   repo: local
    hooks:
    -   id: validate-js
        name: validate-js
        language: system
        entry: sh -c 'npm run validate-js'
        files: .js$
EOF
cat <<EOF >package.json
{
  "devDependencies": {
    "eslint": "2.2.0"
  },
  "scripts": {
    "validate-js": "eslint broken.js"
  }
}
EOF
echo 'foo {' >broken.js
git add .pre-commit-config.yaml package.json broken.js
npm install && pre-commit run
```

The execution then hangs.
There is the stacktrace following a `CTRL+C` :
```
Traceback (most recent call last):
  File "/home/lucas_cimon/.local/share/virtualenvs/pre-commit-bug/bin/pre-commit", line 11, in <module>
    sys.exit(main())
  File "/home/lucas_cimon/.local/share/virtualenvs/pre-commit-bug/lib/python3.4/site-packages/pre_commit/main.py", line 157, in main
    return run(runner, args)
  File "/home/lucas_cimon/.local/share/virtualenvs/pre-commit-bug/lib/python3.4/site-packages/pre_commit/commands/run.py", line 212, in run
    return _run_hooks(repo_hooks, args, write, environ)
  File "/home/lucas_cimon/.local/share/virtualenvs/pre-commit-bug/lib/python3.4/site-packages/pre_commit/commands/run.py", line 136, in _run_hooks
    retval |= _run_single_hook(hook, repo, args, write, skips)
  File "/home/lucas_cimon/.local/share/virtualenvs/pre-commit-bug/lib/python3.4/site-packages/pre_commit/commands/run.py", line 89, in _run_single_hook
    retcode, stdout, stderr = repo.run_hook(hook, tuple(filenames))
  File "/home/lucas_cimon/.local/share/virtualenvs/pre-commit-bug/lib/python3.4/site-packages/pre_commit/repository.py", line 199, in run_hook
    self.cmd_runner, hook, file_args,
  File "/home/lucas_cimon/.local/share/virtualenvs/pre-commit-bug/lib/python3.4/site-packages/pre_commit/languages/system.py", line 23, in run_hook
    tuple(shlex.split(hook['entry'])) + tuple(hook['args']), file_args,
  File "/home/lucas_cimon/.local/share/virtualenvs/pre-commit-bug/lib/python3.4/site-packages/pre_commit/xargs.py", line 58, in xargs
    *run_cmd, encoding=None, retcode=None
  File "/home/lucas_cimon/.local/share/virtualenvs/pre-commit-bug/lib/python3.4/site-packages/pre_commit/util.py", line 194, in cmd_output
    stdout, stderr = proc.communicate()
  File "/usr/lib/python3.4/subprocess.py", line 960, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.4/subprocess.py", line 1617, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.4/selectors.py", line 367, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

I'm using `pre-commit` version `0.8.2`.

I found out a fix: adding `shell=True` to `popen_kwargs` in [`util.py:cmd_output`](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/util.py#L190).

Now I can submit a pull request, but the question is :
- should we let the user configure "manually" a `system` hook with `shell=True` in `.pre-commit-config.yaml` (this is my preference, but this is a quite obscure setting option we should document clearly)
- should `util.py:cmd_output` detect automagically that we are using a shell and set this flag itself (a bit dodgy maybe)
- should we add a new type of "shell" hook, very similar to "system" with only this little difference (IMHO: probably overkill and a lotta more code to add)

What do you think ?

**Comment by asottile** [comment]
`shell=True` is almost always never the answer (unless the question is "why was there a CVE", heh).

This should actually work as written, there's a test which tries the same thing:

```yaml
-   id: system-hook-with-spaces
    name: System hook with spaces
    entry: bash -c 'echo "Hello World"'
    language: system
    files: \.sh$
```

I wonder where this goes differently -- I'll investigate when at a terminal

**Comment by asottile** [comment]
I also cannot reproduce from your above paste.

Here's the things I run into in order:

I paste your above thing:

```
...
$ npm install && pre-commit run
npm ERR! addLocal Could not install .
npm ERR! Error: No name provided
npm ERR!     at needName (/usr/share/npm/lib/cache.js:1232:37)
npm ERR!     at /usr/share/npm/lib/cache.js:1111:10
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:50:40
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:317:17)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:296:57
npm ERR!     at fs.js:207:20
npm ERR!     at OpenReq.Req.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:135:5)
npm ERR!     at OpenReq.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:64:22)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-71-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /tmp/foo/tmp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/foo/tmp/npm-debug.log
npm ERR! not ok code 0
```

Alright, fix that up by adding `"name": "dummy" and "version": "0.0.0"` to `package.json` and try again:

```
$ npm install
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/dummy'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/dummy']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/dummy',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/dummy',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/nodejs/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/lib/nodejs/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
...
```

derp, well I'm not running it as admin so let's move to nodeenv:

```
virtualenv ../venv
../venv/bin/pip install pre-commit
../venv/bin/nodeenv nenv --prebuilt
. nenv/bin/activate
npm install -g
```

Aaaaand run: 

```
$ ../venv/bin/pre-commit run --all-files
validate-js..............................................................Failed
hookid: validate-js

> dummy@0.0.0 validate-js /tmp/foo/tmp
> eslint broken.js
sh: 1: eslint: not found

npm ERR! Linux 3.16.0-71-generic
npm ERR! argv "/tmp/foo/tmp/nenv/bin/node" "/tmp/foo/tmp/nenv/bin/npm" "run" "validate-js"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! dummy@0.0.0 validate-js: `eslint broken.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the dummy@0.0.0 validate-js script 'eslint broken.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dummy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint broken.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dummy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dummy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/foo/tmp/npm-debug.log
```

*sigh* `npm install -g eslint`

```
$ ../venv/bin/pre-commit run --all-files
validate-js..............................................................Failed
hookid: validate-js

> dummy@0.0.0 validate-js /tmp/foo/tmp
> eslint broken.js


/tmp/foo/tmp/broken.js
  1:5  error  Parsing error: Unexpected token {

✖ 1 problem (1 error, 0 warnings)
npm ERR! Linux 3.16.0-71-generic
npm ERR! argv "/tmp/foo/tmp/nenv/bin/node" "/tmp/foo/tmp/nenv/bin/npm" "run" "validate-js"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! dummy@0.0.0 validate-js: `eslint broken.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dummy@0.0.0 validate-js script 'eslint broken.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dummy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint broken.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dummy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dummy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/foo/tmp/npm-debug.log
```

Looks in working order to me!

**Comment by Lucas-C** [comment]
Sorry for the unclear reproduction steps.
- I'm using `node` version `v0.12.2` and `npm` version `3.8.7` : maybe this version is more tolerant to missing fields in `package.json`
- you shouldn't have to install `eslint` globally

Sadly this test case is a bit convoluted (`pre-commit` -> `sh` -> `npm run` -> `eslint`)
I agree `shell=True` is probably a bad idea. Im going to try to figure out what's happening there.

**Comment by Lucas-C** [comment]
Really strange, I get the "hanging" behaviour when using `npm run` only, not when invoking `eslint` directly:
```shell
$ python -c "from pre_commit import util; util.cmd_output('/tmp/pre-commit-bug-repro/node_modules/.bin/eslint', 'broken.js')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lucas_cimon/.local/share/virtualenvs/tmp/lib/python3.4/site-packages/pre_commit/util.py", line 200, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/bin/sh', '/tmp/pre-commit-bug-repro/node_modules/.bin/eslint', 'broken.js')
Return code: 1
Expected return code: 0
Output:

    G:\devhome\tools\cygwin\tmp\pre-commit-bug-repro\broken.js
      1:5  error  Parsing error: Unexpected token {

    ✖ 1 problem (1 error, 0 warnings)

    ActiveRequests [ { oncomplete: [Function: afterWrite], async: true, bytes: 146 } ]
    Wait for the stdout buffer to drain
    process.exit(exitCode=1)

Errors: (none)
```

```shell
$ python -c "from pre_commit import util; util.cmd_output('npm', 'run', 'validate-broken-js')"
```

**Comment by Lucas-C** [comment]
Note that with [`sh`][https://github.com/amoffat/sh], things works fine :
```shell
python -c "import sh; sh.npm('run', 'validate-broken-js')"
```

I also found out that, only when the execution is hanging, this `eslint` source code line does not get executed : https://github.com/eslint/eslint/blob/master/bin/eslint.js#L90

**Comment by asottile** [comment]
Oh this is windows, that probably changes everything.

Even with the npm / node versions listed above I can't for the life of me reproduce the bug on linux:

```
>>> from pre_commit.util import cmd_output
>>> cmd_output('npm', 'run', 'validate-js')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/foo/venv/local/lib/python2.7/site-packages/pre_commit/util.py", line 200, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/tmp/foo/nenv/bin/node', '/tmp/foo/nenv/bin/npm', 'run', 'validate-js')
Return code: 1
Expected return code: 0
Output: 
    
    > dummy@0.0.0 validate-js /tmp/foo/tmp
    > eslint broken.js
    
    
    /tmp/foo/tmp/broken.js
      1:5  error  Parsing error: Unexpected token {
    
    ✖ 1 problem (1 error, 0 warnings)
    
    
Errors: 
    
    npm ERR! Linux 3.16.0-71-generic
    npm ERR! argv "/tmp/foo/nenv/bin/node" "/tmp/foo/nenv/bin/npm" "run" "validate-js"
    npm ERR! node v0.12.2
    npm ERR! npm  v3.8.7
    npm ERR! code ELIFECYCLE
    npm ERR! dummy@0.0.0 validate-js: `eslint broken.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the dummy@0.0.0 validate-js script 'eslint broken.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the dummy package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     eslint broken.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs dummy
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls dummy
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /tmp/foo/tmp/npm-debug.log
```

- What are your versions of:
    - eslint
    - cygwin
    - python
- are you using msysgit or cygwin?
- are you using cygwin's X or non-cygwin's X: (usually they have to match for things to work nicely)
    - python
    - nodejs
    - npm

**Comment by Lucas-C** [comment]
I reproduced it again on another computer at home, with :
```
$ echo $BASH_VERSION
4.3.42(4)-release
$ uname -s
CYGWIN_NT-6.0
$ npm --version
2.15.5
$ node --version
v4.4.5
$ python --version
Python 3.4.3
$ pre-commit --version
pre-commit 0.8.2
$ $(npm bin)/eslint --version
v2.2.0
```

I don't have time to dwelve into it right now, but I'll try to investigate more on Monday.

**Comment by Lucas-C** [comment]
I went one step further:
```
 python -c "import subprocess; subprocess.Popen(['node', r'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js', 'run', 'validate-broken-js']).communicate()"
```
is OK
```
 python -c "import subprocess; subprocess.Popen(['node', r'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js', 'run', 'validate-broken-js'], stdout=subprocess.PIPE).communicate()"
```
is KO (it hangs)

**Comment by Lucas-C** [comment]
This issue only appears when using a pipe (if `stdout` is a file descriptor, no problem).
It also doesn't appear when using a true Windows terminal, not Cygwin (like Cmder).

I tried to solve the issue on the NodeJS side (in `eslint` source code), but flushing/closing and blocking/non-blocking behaviours for NodeJS streams are really messy, especially under Windows where libUV seems to behave differently :
- https://github.com/nodejs/node-v0.x-archive/issues/3479
- https://github.com/nodejs/node-v0.x-archive/issues/3584
- https://github.com/nodejs/node-v0.x-archive/issues/8329
- https://github.com/nodejs/node/issues/6456 (latest issue on the subject, still unresolved)

I'm going to give up at this point.
The fix definitively should be on `eslint` side, but I can't figure out the solution, and anyway `npm` is explicitely not supported with Cygwin.

**Comment by Lucas-C** [comment]
Also: a simple workaround is to invoke `eslint` directly from _.pre-commit-config.yaml_, without passing through `npm / _package.json_.
