### ISSUE TITLE
OSErrno 13 Permission Denied

### ISSUE THREAD

**Issue by brendanw** [pre-commit/pre-commit#413]
When trying to run a bash script as part of a pre-commit hook, I run into the below error:

```
An unexpected error has occurred: OSError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/0.9.1/libexec/lib/python2.7/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/0.9.1/libexec/lib/python2.7/site-packages/pre_commit/main.py", line 157, in main
    return run(runner, args)
  File "/usr/local/Cellar/pre-commit/0.9.1/libexec/lib/python2.7/site-packages/pre_commit/commands/run.py", line 212, in run
    return _run_hooks(repo_hooks, args, write, environ)
  File "/usr/local/Cellar/pre-commit/0.9.1/libexec/lib/python2.7/site-packages/pre_commit/commands/run.py", line 136, in _run_hooks
    retval |= _run_single_hook(hook, repo, args, write, skips)
  File "/usr/local/Cellar/pre-commit/0.9.1/libexec/lib/python2.7/site-packages/pre_commit/commands/run.py", line 89, in _run_single_hook
    retcode, stdout, stderr = repo.run_hook(hook, tuple(filenames))
  File "/usr/local/Cellar/pre-commit/0.9.1/libexec/lib/python2.7/site-packages/pre_commit/repository.py", line 201, in run_hook
    self.cmd_runner, hook, file_args,
  File "/usr/local/Cellar/pre-commit/0.9.1/libexec/lib/python2.7/site-packages/pre_commit/languages/script.py", line 21, in run_hook
    file_args,
  File "/usr/local/Cellar/pre-commit/0.9.1/libexec/lib/python2.7/site-packages/pre_commit/xargs.py", line 57, in xargs
    *run_cmd, encoding=None, retcode=None
  File "/usr/local/Cellar/pre-commit/0.9.1/libexec/lib/python2.7/site-packages/pre_commit/util.py", line 179, in cmd_output
    proc = __popen(cmd, **popen_kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by chriskuehl** [comment]
Is the script executable? That would be my guess. What does `ls -l <path to script>` print?

Can you post your `hooks.yaml` or `.pre-commit-config.yaml`?

**Comment by brendanw** [comment]
ah, yup, duh. chmod +x for the file did the trick. thanks!

**Comment by khughitt** [comment]
FYI - I also encountered a similar error message attempting to use `#!/usr/bin/sh` instead of `#!/usr/bin/bash`.

**Comment by asottile** [comment]
fwiw usually the shebang for `sh` is either `#!/bin/sh` or `#!/usr/bin/env sh` (and for bash `#!/bin/bash` or `#!/usr/bin/env bash`)

**Comment by khughitt** [comment]
Ah, good to know. I usually use `#!/bin/env sh`, but I've run into issues using that version on other versions of linux, and so I figured maybe it was just an Arch thing..
