### ISSUE TITLE
Not working on macOS Sierra?

### ISSUE THREAD

**Issue by amcgregor** [pre-commit/pre-commit#419]
Attempting to utilize a collection of hooks from the default repo, I get the following:

```
An unexpected error has occurred: CalledProcessError: Command: ('/Users/amcgregor/Projects/marrow/.venv/bin/python3', '-m', 'virtualenv', '/Users/amcgregor/.pre-commit/repofu57ylaa/py_env-default')
Return code: 100
Expected return code: 0
Output: 
    Using base prefix '/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.5'
    New python executable in /Users/amcgregor/.pre-commit/repofu57ylaa/py_env-default/bin/python3
    Also creating executable in /Users/amcgregor/.pre-commit/repofu57ylaa/py_env-default/bin/python
    ERROR: The executable /Users/amcgregor/.pre-commit/repofu57ylaa/py_env-default/bin/python3 is not functioning
    ERROR: It thinks sys.prefix is '/Library/Frameworks/Python.framework/Versions/3.5' (should be '/Users/amcgregor/.pre-commit/repofu57ylaa/py_env-default')
    ERROR: virtualenv is not compatible with this system or executable
    
Errors: (none)

Traceback (most recent call last):
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/main.py", line 157, in main
    return run(runner, args)
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/commands/run.py", line 212, in run
    return _run_hooks(repo_hooks, args, write, environ)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/staged_files_only.py", line 63, in staged_files_only
    yield
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/commands/run.py", line 195, in run
    repo_hooks = list(get_repo_hooks(runner))
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/commands/run.py", line 141, in get_repo_hooks
    for repo in runner.repositories:
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/runner.py", line 47, in repositories
    repository.require_installed()
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/repository.py", line 117, in require_installed
    self.install()
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/repository.py", line 187, in install
    self.additional_dependencies[language_name][language_version],
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/languages/python.py", line 78, in install_environment
    ('pip', 'install', '.') + additional_dependencies,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/util.py", line 58, in clean_path_on_failure
    yield
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/languages/python.py", line 74, in install_environment
    repo_cmd_runner.run(venv_cmd)
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/prefixed_command_runner.py", line 39, in run
    return cmd_output(*replaced_cmd, __popen=self.__popen, **kwargs)
  File "/Users/amcgregor/Projects/marrow/.venv/lib/python3.5/site-packages/pre_commit/util.py", line 189, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/Users/amcgregor/Projects/marrow/.venv/bin/python3', '-m', 'virtualenv', '/Users/amcgregor/.pre-commit/repofu57ylaa/py_env-default')
Return code: 100
Expected return code: 0
Output: 
    Using base prefix '/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.5'
    New python executable in /Users/amcgregor/.pre-commit/repofu57ylaa/py_env-default/bin/python3
    Also creating executable in /Users/amcgregor/.pre-commit/repofu57ylaa/py_env-default/bin/python
    ERROR: The executable /Users/amcgregor/.pre-commit/repofu57ylaa/py_env-default/bin/python3 is not functioning
    ERROR: It thinks sys.prefix is '/Library/Frameworks/Python.framework/Versions/3.5' (should be '/Users/amcgregor/.pre-commit/repofu57ylaa/py_env-default')
    ERROR: virtualenv is not compatible with this system or executable
    
Errors: (none)
```

Using the Python.org-provided Python 3.5 installer package.  I'm already within a virtual environment at the point of execution.

**Comment by asottile** [comment]
Thanks for the report! 

Does `virtualenv venv` give the same error message? What version of virtualenv do you have installed alongside pre-commit?

**Comment by asottile** [comment]
Ahah! I am able to reproduce this outside pre-commit, though I think I can fix it inside pre-commit.  I'll cook up a feature branch!

**Comment by amcgregor** [comment]
Awesome, thanks!  Apologies for not noticing your initial reply (got lost in a bunch of Travis traffic after I pushed updates to way, way too many repos and branches at the same time…)

With a virtualenv installed system-wide (`/usr/local/bin/virtualenv`, 15.0.3, running under macOS-provided Python 2.7) and virtualenv installed within my venv (`$VIRTUAL_ENV/bin/virtualenv`, 15.0.3, running under venv-provided 3.5.2 from official Python.org `.pkg`) running `virtualenv foo` does, in fact, explode gloriously.

**Comment by asottile** [comment]
Makes sense! I recognize you from contributions on dahlia/libsass-python :)

**Comment by amcgregor** [comment]
^_^ Guilty as charged. There's something about having `@include` be serviceable by the Python side that was just too darned useful in conjunction with a Python CMS…

So, as an experiment after `pip install`'ing pre-commit within the venv I then `pip uninstall virtualenv` to delete the nested install.  Now within my venv I can successfully execute `virtualenv foo` (giving me the same Python 2.7 default) and also execute it with the specific Python 3.5 version, however the mechanism pre-commit uses to try to utilize `virtualenv` (issuing a call to the interpreter + `-m virtualenv`) obviously fails.  If instead you made a shell invocation to `virtualenv` without a path to virtualenv, but with an explicit `--python` version (but not full path), it would.

**Comment by asottile** [comment]
This is available in 0.9.2 \o/

**Comment by amcgregor** [comment]
Frickin' awesome sauce.  Now to pin `develop_requires` versions in over 100 projects… T_T

**Comment by asottile** [comment]
lol I know that feel <3

at work I've checked out all of our repos and have some scripts to automate bump + test + merge, wish I could share them but they're a slight bit too proprietary :S

**Comment by amcgregor** [comment]
```
awk '/tests_require \+ ['pre-commit']/ { print "\t\t\t'development': tests_require + ['pre-commit'],  # Development requirements are the testing requirements."; next }1'
```

That should do the vast majority of my projects that avoid declaring additional (non-test) development requirements.  I use a similar `awk` approach in my venv construction shell function to patch the activate script.  ;)
