### ISSUE TITLE
how to use http proxy when do pre-commit run

### ISSUE THREAD

**Issue by lovemyliwu** [pre-commit/pre-commit#429]
as title said

**Comment by asottile** [comment]
Is this for pip to use an http proxy or a specific executable or ?

**Comment by lovemyliwu** [comment]
i get some issue when `[INFO] Installing environment for git://github.com/pre-commit/mirrors-jshint`, GFW blocked some resources.

**Comment by asottile** [comment]
Can you paste more output?

**Comment by lovemyliwu** [comment]
sorry, i lost the output, retry then always hanging.

**Comment by asottile** [comment]
Here's some stuff that might help
- git clone through a proxy: http://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy
- npm install from proxy: http://stackoverflow.com/questions/7559648/is-there-a-way-to-make-npm-install-the-command-to-work-behind-proxy
- pip install from proxy: http://stackoverflow.com/questions/14149422/using-pip-behind-a-proxy

**Comment by rlinke** [comment]
I have the same or maybe a similar issue. 

Is there a way to tell pre-commit to use `https://` prefix instead of `git://`? I think git protocol is blocked and I can only access through http or https connection.

Below some information, if you have any suggestions or need further info please let me know.

**execute command:**
```
(<myenv>) [...]>pre-commit run --all-files
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Program Files\\Git\\cmd\\git.exe', 'clone', '--no-checkout', 'git://github.com/pre-commit/pre-commit-hooks', 'C:\\Users\\<myuser>/.cache\\pre-commit\\repoacxr3zdu')
Return code: 128
Expected return code: 0
Output: (none)
Errors:
    Cloning into 'C:\Users\<myuser>/.cache\pre-commit\repoacxr3zdu'...
    fatal: Unable to look up github.com (port 9418) (No such host is known. )

Check the log at C:\Users\<myuser>/.cache\pre-commit\pre-commit.log

```



**log content**
```
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Program Files\\Git\\cmd\\git.exe', 'clone', '--no-checkout', 'git://github.com/pre-commit/pre-commit-hooks', 'C:\\Users\\<myuser>/.cache\\pre-commit\\repoy3wik3mv')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    Cloning into 'C:\Users\<myuser>/.cache\pre-commit\repoy3wik3mv'...
    fatal: Unable to look up github.com (port 9418) (No such host is known. )
    

Traceback (most recent call last):
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\pre_commit\error_handler.py", line 47, in error_handler
    yield
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\pre_commit\main.py", line 261, in main
    return run(runner, store, args)
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\pre_commit\commands\run.py", line 256, in run
    for _, hook in repo.hooks:
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\pre_commit\repository.py", line 162, in hooks
    if hook['id'] not in self.manifest_hooks:
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\pre_commit\repository.py", line 155, in manifest_hooks
    repo_path = self.store.clone(repo, rev)
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\pre_commit\store.py", line 150, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\pre_commit\store.py", line 126, in _new_repo
    make_strategy(directory)
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\pre_commit\store.py", line 142, in clone_strategy
    cmd_output(*cmd, env=env)
  File "C:\Users\<myuser>\AppData\Local\conda\conda\envs\<myenv>\lib\site-packages\pre_commit\util.py", line 177, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('C:\\Program Files\\Git\\cmd\\git.exe', 'clone', '--no-checkout', 'git://github.com/pre-commit/pre-commit-hooks', 'C:\\Users\\<myuser>/.cache\\pre-commit\\repoy3wik3mv')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    Cloning into 'C:\Users\<myuser>/.cache\pre-commit\repoy3wik3mv'...
    fatal: Unable to look up github.com (port 9418) (No such host is known. )
```


**note**
git clone xy **does** work in the console. I set the http.proxy variable in my global git config.

**Comment by asottile** [comment]
@rlinke `pre-commit` will use whatever protocol you've set in your `.pre-commit-config.yaml` when cloning.  I'd suggest replacing `git://` with `https://` there anyway (at least for `github` https is faster anyway!)

Alternatively, if you don't have control over that you can use [`.insteadOf`](https://stackoverflow.com/a/11383587/812183) when configuring `git`

**Comment by rlinke** [comment]
@asottile setting the correct protocol in the `.yaml` file works like a charm. Thank you for the quick help.

**Comment by asottile** [comment]
> @asottile setting the correct protocol in the `.yaml` file works like a charm. Thank you for the quick help.

Happy to help!
