### ISSUE TITLE
The 'pyyaml' distribution was not found and is required by pre-commit-hooks

### ISSUE THREAD

**Issue by awebdeveloper** [pre-commit/pre-commit#495]
Check for broken symlinks................................................Failed
hookid: check-symlinks

Check for merge conflicts................................................Failed
hookid: check-merge-conflict

```
Traceback (most recent call last):
  File "/Users/shettypr/.pre-commit/repo9VWDox/py_env-default/bin/check-symlinks", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/shettypr/.pre-commit/repo9VWDox/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3013, in <module>
    @_call_aside
  File "/Users/shettypr/.pre-commit/repo9VWDox/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2999, in _call_aside
    f(*args, **kwargs)
  File "/Users/shettypr/.pre-commit/repo9VWDox/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3026, in _initialize_m
aster_working_set
    working_set = WorkingSet._build_master()
  File "/Users/shettypr/.pre-commit/repo9VWDox/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/Users/shettypr/.pre-commit/repo9VWDox/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/shettypr/.pre-commit/repo9VWDox/py_env-default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyyaml' distribution was not found and is required by pre-commit-hooks
```

**Comment by asottile** [comment]
Can you show the last few commands that led to this state and/or a reproduction that starts with `pre-commit clean` as well as the version (`pre-commit --version`) you're using and your `.pre-commit-config.yaml` contents?

As far as I know, this state should no longer be achievable.

**Comment by asottile** [comment]
@awebdeveloper any updates on this?

**Comment by awebdeveloper** [comment]
```
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
An unexpected error has occurred: CalledProcessError: Command: ('/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git', 'clone', '--no
-checkout', 'git://github.com/pre-commit/pre-commit-hooks', '/Users/pr/.pre-commit/repoABDXQu')
Return code: 128
Expected return code: 0
Output: (none)
Errors:
    Cloning into '/Users/pr/.pre-commit/repoABDXQu'...
    fatal: unable to connect to github.com:
    github.com[0: 192.30.253.113]: errno=Connection refused
    github.com[1: 192.30.253.112]: errno=Connection refused



Check the log at ~/.pre-commit/pre-commit.log
```


pre-commit --version
`pre-commit 0.13.2`


cat .pre-commit-config.yaml
```
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 52582865ab7ed8f41734253190844c854ddd9a9e
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: pretty-format-json
        args: ['--indent', '2', '--no-sort-keys']
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-json
-   repo: https://github.com/pre-commit/mirrors-eslint
    sha: 3f5585a65eeec878e779a5630628db158ba3dab1
    hooks:
    -   id: eslint
        additional_dependencies: ['eslint@3.12.2', 'eslint-config-google@0.7.1']

```


Both the below commands give empty

env | grep -i virtualenv

env | grep -i pip
