### ISSUE TITLE
pkg_resources.DistributionNotFound: pre-commit on Python 2.6.6

### ISSUE THREAD

**Issue by patsevanton** [pre-commit/pre-commit#543]
**cat /etc/redhat-release** 
`CentOS release 6.9 (Final)`
**yum info python**
```
Name: python
Version: 2.6.6
```
Try install pre-commit
```
curl https://bootstrap.pypa.io/get-pip.py | sudo python - pre-commit
cd /var/opt/gitlab/git-data/repositories/test-group/test-project.git/
```
**pre-commit install**
```
Traceback (most recent call last):
  File "/usr/bin/pre-commit", line 7, in <module>
    from pre_commit.main import main
  File "/usr/lib/python2.6/site-packages/pre_commit/main.py", line 8, in <module>
    import pre_commit.constants as C
  File "/usr/lib/python2.6/site-packages/pre_commit/constants.py", line 23, in <module>
    VERSION = pkg_resources.get_distribution('pre-commit').version
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 292, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 176, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pre-commit
```

**Comment by asottile** [comment]
This appears to be a number of things:
- The version of setuptools is too old to support "wheel" distribution information
- pre-commit>=0.9.0 [no longer supports python2.6](https://github.com/pre-commit/pre-commit/blob/844c839067b530e7598e6c6afd59b565b091e19c/CHANGELOG.md#090)
- pre-commit's dependency (at 0.8.1 (but [no longer](https://github.com/pre-commit/pre-commit/blob/3874636f8f71aed8c2ab472db828475a549d1479/CHANGELOG.md#0134)!)) jsonschema [no longer supports python2.6](https://github.com/Julian/jsonschema/blob/master/CHANGELOG.rst#v260)

That said, I was able to get this to hobble along by doing the following things (note: upgrading packages managed by the system package manager aren't usually a good idea -- so don't necessarily do what I do!)

```dockerfile
FROM centos:6.9

RUN yum install -y git
WORKDIR /repo
RUN git init /repo
RUN curl https://bootstrap.pypa.io/get-pip.py | python && \
    # Need to do this in a separate command before installing pre-commit as
    # pre-commit has non-wheeled dependencies that require setuptools to
    # build from source.
    # Also need to install a sufficiently new setuptools from pip instead of
    # using the `python-setuptools` package through yum (which is at version
    # 0.6rc11: released in 2009: https://pypi.python.org/pypi/setuptools/0.6c11)
    pip install setuptools && \
    # Note, jsonschema is a dependency of pre-commit which has also dropped
    # python2.6 support, so we need to limit to a version that will install
    # there as well.
    pip install 'jsonschema<=2.5.999' 'pre-commit<=0.8.999'
CMD ["pre-commit", "install"]
```

Output:

```console
$ docker run -ti test
pre-commit installed at /repo/.git/hooks/pre-commit
```

So in several different ways, python2.6 (and centos6) are just too old to work.

**Comment by asottile** [comment]
Note that in centos7 things run much more smoothly (I can use the packaged setuptools, system python is 2.7, no weird limiting of dependencies):

```dockerfile
FROM centos:7

RUN yum install -y git python-setuptools
WORKDIR /repo
RUN git init /repo
RUN curl https://bootstrap.pypa.io/get-pip.py | python - pre-commit
CMD ["pre-commit", "install"]
```

```console
$ docker run -ti test
pre-commit installed at /repo/.git/hooks/pre-commit
```

**Comment by patsevanton** [comment]
Ok. Thanks.
I will think about used docker for pre-commit.

**Comment by asottile** [comment]
Oh I wasn't  necessarily suggesting using docker, that's just the easiest way for me to try things against centos
