### ISSUE TITLE
Homebrew test block fails for 0.16.0

### ISSUE THREAD

**Issue by ilovezfs** [pre-commit/pre-commit#576]
```
  test do
    testpath.cd do
      system "git", "init"
      (testpath/".pre-commit-config.yaml").write <<-EOF.undent
      -   repo: https://github.com/pre-commit/pre-commit-hooks
          sha: 5541a6a046b7a0feab73a21612ab5d94a6d3f6f0
          hooks:
          -   id: trailing-whitespace
      EOF
      system bin/"pre-commit", "install"
      system bin/"pre-commit", "run", "--all-files"
    end
  end
```
fails with
```
iMac-TMP:~ joe$ brew test -vd pre-commit
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb
Testing pre-commit
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170801-77789-v2c52c.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb -vd
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb
==> git init
Initialized empty Git repository in /private/tmp/pre-commit-test-20170801-77790-em7fx9/.git/
==> /usr/local/Cellar/pre-commit/0.16.0/bin/pre-commit install
pre-commit installed at /private/tmp/pre-commit-test-20170801-77790-em7fx9/.git/hooks/pre-commit
==> /usr/local/Cellar/pre-commit/0.16.0/bin/pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
An error has occurred: InvalidManifestError: 
=====> /tmp/pre-commit-test-20170801-77790-em7fx9/.pre-commit/repoPToFpd/.pre-commit-hooks.yaml does not exist
Check the log at ~/.pre-commit/pre-commit.log
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: /usr/local/Cellar/pre-commit/0.16.0/bin/pre-commit run --all-files
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.
bash-3.2$ cat ~/.pre-commit/pre-commit.log
An error has occurred: InvalidManifestError: 
=====> /tmp/pre-commit-test-20170801-77790-em7fx9/.pre-commit/repoPToFpd/.pre-commit-hooks.yaml does not exist
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/error_handler.py", line 48, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/main.py", line 231, in main
    return run(runner, args)
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/commands/run.py", line 256, in run
    repo_hooks = list(get_repo_hooks(runner))
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/commands/run.py", line 197, in get_repo_hooks
    for repo in runner.repositories:
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/runner.py", line 46, in repositories
    repository.require_installed()
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/repository.py", line 177, in require_installed
    _install_all(self._venvs, self.repo_config['repo'])
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/repository.py", line 166, in _venvs
    for _, hook in self.hooks:
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/repository.py", line 146, in hooks
    if hook['id'] not in self.manifest.hooks:
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/manifest.py", line 28, in hooks
    for hook in self.manifest_contents:
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/manifest.py", line 23, in manifest_contents
    return load_manifest(os.path.join(self.repo_path, C.MANIFEST_FILE))
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/schema.py", line 279, in load_from_filename
    return apply_defaults(data, schema)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/schema.py", line 49, in reraise_as
    six.reraise(tp, tp(e), tb)
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/schema.py", line 46, in reraise_as
    yield
  File "/usr/local/Cellar/pre-commit/0.16.0/libexec/lib/python2.7/site-packages/pre_commit/schema.py", line 267, in load_from_filename
    raise ValidationError('{} does not exist'.format(filename))
InvalidManifestError: 
=====> /tmp/pre-commit-test-20170801-77790-em7fx9/.pre-commit/repoPToFpd/.pre-commit-hooks.yaml does not exist

bash-3.2$
```

**Comment by chriskuehl** [comment]
If you apply this patch to your test, it will probably fix it:

```patch
--- a	2017-08-01 23:55:42.552878701 -0700
+++ b	2017-08-01 23:55:57.341148895 -0700
@@ -3,7 +3,7 @@
       system "git", "init"
       (testpath/".pre-commit-config.yaml").write <<-EOF.undent
       -   repo: https://github.com/pre-commit/pre-commit-hooks
-          sha: 5541a6a046b7a0feab73a21612ab5d94a6d3f6f0
+          sha: v0.9.1
           hooks:
           -   id: trailing-whitespace
       EOF
```

**Comment by ilovezfs** [comment]
@chriskuehl yes, looks good:
```
iMac-TMP:homebrew-core joe$ brew test -vd pre-commit
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb
Testing pre-commit
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170802-1293-vvtu78.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb -vd
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb
==> git init
Initialized empty Git repository in /private/tmp/pre-commit-test-20170802-1294-1dtdxot/.git/
==> /usr/local/Cellar/pre-commit/0.16.0/bin/pre-commit install
pre-commit installed at /private/tmp/pre-commit-test-20170802-1294-1dtdxot/.git/hooks/pre-commit
==> /usr/local/Cellar/pre-commit/0.16.0/bin/pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Trim Trailing Whitespace.............................(no files to check)Skipped
iMac-TMP:homebrew-core joe$ echo $?
0
```

**Comment by ilovezfs** [comment]
Thanks!

**Comment by asottile** [comment]
no, @ilovezfs thank you for maintaining the homebrew installation :)

**Comment by ilovezfs** [comment]
@asottile you're welcome!
