### ISSUE TITLE
Git For Windows support

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit#620]
Hi.

Is [Git For Windows](https://git-for-windows.github.io) supported ?

In doubt, I'm reporting 2 issues I have with the latest version (2.14.1) and the latest Python For Windows version (3.6.2) :
- when I try `install-local.py` :
```
$ curl http://pre-commit.com/install-local.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2590  100  2590    0     0   2590      0  0:00:01 --:--:--  0:00:01  8274
Using base prefix 'D:\\devhome\\tools\\Python36'
New python executable in C:\Users\lucas_cimon\.pre-commit-venv\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Downloading https://pypi.python.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
Done.
Traceback (most recent call last):
  File "<stdin>", line 103, in <module>
  File "<stdin>", line 80, in main
  File "D:\devhome\tools\Python36\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "D:\devhome\tools\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\devhome\tools\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "D:\devhome\tools\Python36\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```
- when I install `pre-commit` through `pip`, and try to run it:
```
$ pre-commit run
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to C:\Users\lucas_cimon/.cache\pre-commit\patch1505684784.
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lucas_cimon/.cache\\pre-commit\\patch1505684784'
Check the log at C:\Users\lucas_cimon/.cache\pre-commit\pre-commit.log
$ cat ~/.cache/pre-commit/pre-commit.log
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lucas_cimon/.cache\\pre-commit\\patch1505684784'
Traceback (most recent call last):
  File "C:\Users\lucas_cimon\AppData\Roaming\Python\Python36\site-packages\pre_commit\error_handler.py", line 44, in error_handler
    yield
  File "C:\Users\lucas_cimon\AppData\Roaming\Python\Python36\site-packages\pre_commit\main.py", line 231, in main
    return run(runner, args)
  File "C:\Users\lucas_cimon\AppData\Roaming\Python\Python36\site-packages\pre_commit\commands\run.py", line 249, in run
    with ctx:
  File "d:\devhome\tools\python36\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\lucas_cimon\AppData\Roaming\Python\Python36\site-packages\pre_commit\staged_files_only.py", line 46, in staged_files_only
    with io.open(patch_filename, 'wb') as patch_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lucas_cimon/.cache\\pre-commit\\patch1505684784'
```

**Comment by asottile** [comment]
I use git-for-windows, I doubt `install-local.py` will work as it relies on [`ln -s`](https://github.com/pre-commit/pre-commit.github.io/blob/721b6a1c1f7cb9d2b77cdc44f20f8666ac565569/install-local.py#L90-L94).  The specific failure you're hitting is where it attempts to call [`pip`](https://github.com/pre-commit/pre-commit.github.io/blob/721b6a1c1f7cb9d2b77cdc44f20f8666ac565569/install-local.py#L79-L81).  On windows (for whatever reason) virtualenvs use the `Scripts` directory instead of `bin` for executables.

The latter seems quite strange!  Let me see if I can reproduce that (it appears to be first-time run with unstaged changes, should reproduce on linux as well):

```
$ pre-commit run
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/asottile/.cache/pre-commit/patch1505686307.
An unexpected error has occurred: IOError: [Errno 2] No such file or directory: '/home/asottile/.cache/pre-commit/patch1505686307'
Check the log at /home/asottile/.cache/pre-commit/pre-commit.log
```

I'll spin that off into another ticket!

Here's the action items from this:

- https://github.com/pre-commit/pre-commit.github.io/issues/131
- https://github.com/pre-commit/pre-commit/issues/621 

Thanks again for the issues! :D

**Comment by asottile** [comment]
The fix for the bug is now available in [v1.1.1](https://github.com/pre-commit/pre-commit/releases/tag/v1.1.1)!

**Comment by Lucas-C** [comment]
Thank you very much !

**Comment by Lucas-C** [comment]
I wonder why the AppVeyor CI checks did not catch this ?
https://github.com/pre-commit/pre-commit/blob/master/appveyor.yml

**Comment by asottile** [comment]
It was a bug in all platforms, just an edge case that wasn't tested :)

**Comment by Lucas-C** [comment]
Ok, thanks

**Comment by Lucas-C** [comment]
FYI, I just tested it with Windows 10 Ubuntu bash, and it works like a charm !
