### ISSUE TITLE
Windows git performance issues

### ISSUE THREAD

**Issue by 1oglop1** [pre-commit/pre-commit#636]
Hi I'm having performance issues on windows machines

`git version 2.14.2.windows.2`
`pyhon version: 3.6.2`
`pre-commit 1.3.0`

The download of hooks is super slow. 

I also had issues on second computer using `git` links, see log file from second pc

```
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Program Files\\Git\\cmd\\git.exe', 'clone', '--no-checkout', 'git://github.com/pre-commit/pre-commit-hooks', 'C:\\Users\\uadmin/.cache\\pre-commit\\repob8zvaud7')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    Cloning into 'C:\Users\uadmin/.cache\pre-commit\repob8zvaud7'...
    fatal: unable to connect to github.com:
    github.com[0: 192.30.253.113]: errno=Invalid argument
    github.com[1: 192.30.253.112]: errno=Invalid argument
    
    

Traceback (most recent call last):
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\error_handler.py", line 47, in error_handler
    yield
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\main.py", line 252, in main
    return run(runner, args)
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\commands\run.py", line 248, in run
    repo_hooks = list(get_repo_hooks(runner))
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\commands\run.py", line 201, in get_repo_hooks
    for repo in runner.repositories:
  File "c:\users\uadmin\envs\testenv\lib\site-packages\cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\runner.py", line 51, in repositories
    repo.require_installed()
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\repository.py", line 185, in require_installed
    _install_all(self._venvs, self.repo_config['repo'], self.store)
  File "c:\users\uadmin\envs\testenv\lib\site-packages\cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\repository.py", line 174, in _venvs
    for _, hook in self.hooks:
  File "c:\users\uadmin\envs\testenv\lib\site-packages\cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\repository.py", line 154, in hooks
    if hook['id'] not in self.manifest.hooks:
  File "c:\users\uadmin\envs\testenv\lib\site-packages\cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\repository.py", line 149, in manifest
    return Manifest(self._repo_path)
  File "c:\users\uadmin\envs\testenv\lib\site-packages\cached_property.py", line 26, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\repository.py", line 137, in _repo_path
    self.repo_config['repo'], self.repo_config['sha'],
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\store.py", line 154, in clone
    return self._new_repo(repo, ref, clone_strategy)
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\store.py", line 130, in _new_repo
    make_strategy(directory)
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\store.py", line 145, in clone_strategy
    env=no_git_env(),
  File "c:\users\uadmin\envs\testenv\lib\site-packages\pre_commit\util.py", line 187, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('C:\\Program Files\\Git\\cmd\\git.exe', 'clone', '--no-checkout', 'git://github.com/pre-commit/pre-commit-hooks', 'C:\\Users\\uadmin/.cache\\pre-commit\\repob8zvaud7')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    Cloning into 'C:\Users\uadmin/.cache\pre-commit\repob8zvaud7'...
    fatal: unable to connect to github.com:
    github.com[0: 192.30.253.113]: errno=Invalid argument
    github.com[1: 192.30.253.112]: errno=Invalid argument
```

**Comment by asottile** [comment]
my guess looking at that error is you're having connectivity issues with github.  Can you see if `git clone git://github.com/pre-commit/pre-commit-hooks` is having similar issues?  (If so, it's likely not our code and just your internet connection / git installation)

**Comment by asottile** [comment]
I don't think there's anything actionable from our front here -- if you think otherwise, feel free to reopen!
