### ISSUE TITLE
fix-lint failing on Windows

### ISSUE THREAD

**Issue by jurko-gospodnetic** [pre-commit/pre-commit#668]
Running 'tox -e fix-lint` fails on my Windows 10 machine and I'm creating an issue for it as suggested by @asottile at https://github.com/tox-dev/tox/pull/686#issuecomment-348535756.

Here's a clean environment I have set up to reproduce the issue:
- Windows 10
- Python 3.6.1
- `Z:\` folder containing a clean `tox` checkout
- virtual env created running `py3 -m venv venvZ`
- installed tox into the virtual env: `pip install -e .`
- list of installed pip packages:
```
(venvZ) Z:\>pip list --format=columns
Package    Version              Location
---------- -------------------- --------
pip        9.0.1
pluggy     0.6.0
py         1.5.2
setuptools 28.8.0
six        1.11.0
tox        2.9.2.dev29+g3f122e4 z:\
virtualenv 15.1.0
```
- no `~\.cache folder
- the output I get for a clean fix-lint run:
```
(venvZ) Z:\>tox -e fix-lint
GLOB sdist-make: Z:\setup.py
fix-lint create: Z:\.tox\fix-lint
fix-lint installdeps: flake8 == 3.4.1, flake8-bugbear == 17.4.0, pre-commit == 1.3.0
fix-lint inst: Z:\.tox\dist\tox-2.9.2.dev29+g3f122e4.zip
ERROR: invocation failed (exit code 2), logfile: Z:\.tox\fix-lint\log\fix-lint-2.log
ERROR: actionid: fix-lint
msg: installpkg
cmdargs: ['Z:\\.tox\\fix-lint\\Scripts\\pip.EXE', 'install', 'Z:\\.tox\\dist\\tox-2.9.2.dev29+g3f122e4.zip']

Processing z:\.tox\dist\tox-2.9.2.dev29+g3f122e4.zip
Collecting py>=1.4.17 (from tox==2.9.2.dev29+g3f122e4)
  Using cached py-1.5.2-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.3.0 (from tox==2.9.2.dev29+g3f122e4)
Requirement already satisfied: six in z:\.tox\fix-lint\lib\site-packages (from tox==2.9.2.dev29+g3f122e4)
Requirement already satisfied: virtualenv>=1.11.2 in z:\.tox\fix-lint\lib\site-packages (from tox==2.9.2.dev29+g3f122e4)
Building wheels for collected packages: tox
  Running setup.py bdist_wheel for tox: started
  Running setup.py bdist_wheel for tox: finished with status 'done'
  Stored in directory: C:\Users\Jurko\AppData\Local\pip\Cache\wheels\55\12\0f\ed05d5baf3ba6de876854d1f4e1b59ba30bfd3c2bc37999a31
Exception:
Traceback (most recent call last):
  File "z:\.tox\fix-lint\lib\shutil.py", line 374, in _rmtree_unsafe
    names = os.listdir(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Jurko\\AppData\\Local\\Temp\\pip-xnmv5q_t-build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "z:\.tox\fix-lint\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "z:\.tox\fix-lint\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "z:\.tox\fix-lint\lib\site-packages\pip\wheel.py", line 825, in build
    req.remove_temporary_source()
  File "z:\.tox\fix-lint\lib\site-packages\pip\req\req_install.py", line 980, in remove_temporary_source
    rmtree(self._temp_build_dir)
  File "z:\.tox\fix-lint\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "z:\.tox\fix-lint\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "z:\.tox\fix-lint\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "z:\.tox\fix-lint\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "z:\.tox\fix-lint\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "z:\.tox\fix-lint\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "z:\.tox\fix-lint\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "z:\.tox\fix-lint\lib\shutil.py", line 376, in _rmtree_unsafe
    onerror(os.listdir, path, sys.exc_info())
  File "z:\.tox\fix-lint\lib\site-packages\pip\utils\__init__.py", line 110, in rmtree_errorhandler
    if os.stat(path).st_mode & stat.S_IREAD:
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Jurko\\AppData\\Local\\Temp\\pip-xnmv5q_t-build'

fix-lint installed: aspy.yaml==1.0.0,attrs==17.3.0,cached-property==1.3.1,flake8==3.4.1,flake8-bugbear==17.4.0,identify==1.0.7,mccabe==0.6.1,nodeenv==1.2.0,pre-commit==1.3.0,pycodestyle==2.3.1,pyflakes==1.5.0,PyYAML==3.12,six==1.11.0,virtualenv==15.1.0
______________________________________________________ summary _______________________________________________________
ERROR:   fix-lint: InvocationError: Z:\.tox\fix-lint\Scripts\pip.EXE install Z:\.tox\dist\tox-2.9.2.dev29+g3f122e4.zip (see Z:\.tox\fix-lint\log\fix-lint-2.log)
```
- `Z:\.tox\fix-lint\log\fix-lint-2.log` log file content:
```
actionid: fix-lint
msg: installpkg
cmdargs: ['Z:\\.tox\\fix-lint\\Scripts\\pip.EXE', 'install', 'Z:\\.tox\\dist\\tox-2.9.2.dev29+g3f122e4.zip']

Processing z:\.tox\dist\tox-2.9.2.dev29+g3f122e4.zip
Collecting py>=1.4.17 (from tox==2.9.2.dev29+g3f122e4)
  Using cached py-1.5.2-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.3.0 (from tox==2.9.2.dev29+g3f122e4)
Requirement already satisfied: six in z:\.tox\fix-lint\lib\site-packages (from tox==2.9.2.dev29+g3f122e4)
Requirement already satisfied: virtualenv>=1.11.2 in z:\.tox\fix-lint\lib\site-packages (from tox==2.9.2.dev29+g3f122e4)
Building wheels for collected packages: tox
  Running setup.py bdist_wheel for tox: started
  Running setup.py bdist_wheel for tox: finished with status 'done'
  Stored in directory: C:\Users\Jurko\AppData\Local\pip\Cache\wheels\55\12\0f\ed05d5baf3ba6de876854d1f4e1b59ba30bfd3c2bc37999a31
Exception:
Traceback (most recent call last):
  File "z:\.tox\fix-lint\lib\shutil.py", line 374, in _rmtree_unsafe
    names = os.listdir(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Jurko\\AppData\\Local\\Temp\\pip-xnmv5q_t-build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "z:\.tox\fix-lint\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "z:\.tox\fix-lint\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "z:\.tox\fix-lint\lib\site-packages\pip\wheel.py", line 825, in build
    req.remove_temporary_source()
  File "z:\.tox\fix-lint\lib\site-packages\pip\req\req_install.py", line 980, in remove_temporary_source
    rmtree(self._temp_build_dir)
  File "z:\.tox\fix-lint\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "z:\.tox\fix-lint\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "z:\.tox\fix-lint\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "z:\.tox\fix-lint\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "z:\.tox\fix-lint\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "z:\.tox\fix-lint\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "z:\.tox\fix-lint\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "z:\.tox\fix-lint\lib\shutil.py", line 376, in _rmtree_unsafe
    onerror(os.listdir, path, sys.exc_info())
  File "z:\.tox\fix-lint\lib\site-packages\pip\utils\__init__.py", line 110, in rmtree_errorhandler
    if os.stat(path).st_mode & stat.S_IREAD:
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Jurko\\AppData\\Local\\Temp\\pip-xnmv5q_t-build'
```

**Comment by jurko-gospodnetic** [comment]
Issue seems to be a race condition in what I assume are different packages attempting to remove some temporary folder.

After many repeated attempts with similar errors, it succeeded once.

Then it was still failing but I could get it to work every time by changing the `_rmtree_unsafe()` function in `z:\.tox\fix-lint\lib\shutil.py`  to add `except FileNotFoundError` error handling:
```
# version vulnerable to race conditions
def _rmtree_unsafe(path, onerror):
    try:
        print('zzz: path exists:{}'.format(os.path.exists(path)))
        if os.path.islink(path):
            # symlinks to directories are forbidden, see bug #1669
            raise OSError("Cannot call rmtree on a symbolic link")
    except FileNotFoundError:
        return
    except OSError:
        onerror(os.path.islink, path, sys.exc_info())
        # can't continue even if onerror hook returns
        return
    names = []
    try:
        names = os.listdir(path)
    except FileNotFoundError:
        return
    except OSError:
        onerror(os.listdir, path, sys.exc_info())
    for name in names:
        fullname = os.path.join(path, name)
        try:
            mode = os.lstat(fullname).st_mode
        except OSError:
            mode = 0
        if stat.S_ISDIR(mode):
            _rmtree_unsafe(fullname, onerror)
        else:
            try:
                os.unlink(fullname)
            except FileNotFoundError:
                return
            except OSError:
                onerror(os.unlink, fullname, sys.exc_info())
    try:
        os.rmdir(path)
    except FileNotFoundError:
        return
    except OSError:
        onerror(os.rmdir, path, sys.exc_info())
```

**Comment by asottile** [comment]
Interesting that it is a race -- do you have some sort of aggressive temporary file cleanup procedure?  I'd be surprised if *any* `pip install` commands work in that case.

**Comment by asottile** [comment]
Oh actually your pasted trace confirms that *all* pip installs on your machine are subject to this race (the one you pasted doens't actually involve pre-commit at all!)

**Comment by asottile** [comment]
Or maybe you're out of disk space so the OS is cleaning it up?

Either way, now that we can see above that it's not even getting to the part where pre-commit is running that it's unrelated to this project

**Comment by jurko-gospodnetic** [comment]
playing around with it now to see what else I can find there... but there is no external temp file cleanup going on there

**Comment by asottile** [comment]
Closing this given there's a failure that doesn't actually involve this project.  Guess we're back to the tox-dev/tox thread :)
