### ISSUE TITLE
Implement `pre-commit exec` or similar?

### ISSUE THREAD

**Issue by tdeo** [pre-commit/pre-commit#735]
Hi,

I regularly find myself in the use case that I want to troubleshoot or run a specific command for one of pre commit hook. A typical use-case would be running `rubocop --auto-gen-config` after upgrading version. The first times I've tried just editing my `.pre-commit-config.yaml` to add this argument, but for this command it doesn't work with the batching pre-commit does because of command length limits, since rubocop expects to scan all the repo at once to know all wrong offenses and generate the file.

Right now I'm manually finding the local repo with something like `find ~/.cache/pre-commit/ -iname "rubocop*.gemspec"` and then having to manually `. rbenv-default/bin/activate` from there, exporting a few environment variables, and finally being able to run my commands with the virtual env all setup.

This is a bit tedious, and I was wondering if `pre-commit exec rubocop <args>` (like `docker exec ...`) would be a suitable PR idea. Happy to work on that

**Comment by asottile** [comment]
The command-length splitting behaviour is covered in https://github.com/pre-commit/pre-commit/issues/691#issuecomment-360224845 -- there's some code hints on how to "fix" it on posix platforms, just needs some implementation!  Currently it is overly timid to account for the limitations on windows, but could be made much more permissive on platforms which provide `SC_MAX_ARG`.

Note that although there's an `activate` file written for the `rbenv`, it was [invented by pre-commit](https://github.com/pre-commit/pre-commit/blob/834ed0f229a39c986b241374f6d338632e003b5f/pre_commit/languages/ruby.py#L68-L84) and although it used to be used, it hasn't been used since [0.8.0](https://github.com/pre-commit/pre-commit/commit/a5b56bd9e3062582f8e133999a7ffae7258d8cae) and is likely broken in subtle ways.  I've been trying to factor this out to a general purpose, cross-platform, reusable ruby virtual environment helper -- though I've been too busy so development has mostly stalled on that: https://github.com/asottile/rubyvenv/blob/master/rubyvenv.py.

A few questions here, since I think we can solve this without turning `pre-commit` into a general purpose shell :) (which I'd like to avoid).

- What command are you running specifically?
- Does the newly added `stages: [manual]` and/or `pass_filenames: false` help you out here?
- If we do this (big IF) how do we discourage (ab)use of it (it sounds too close to `run` right now (a similar confusion that beginners have with `docker`!)).  The abuse I'm describing is commands which would either break or invalidate the pre-commit metadata (think things like `pip uninstall` / `pip install` / etc.)

**Comment by tdeo** [comment]
Thanks for all those explanations.

To give a bit more context, what I'm trying to do is run `rubocop --auto-gen-config` on my repo (it's a feature of rubocop that scans the whole repo and generates a configuration file that matches the current state). I've been trying to set it up using `stages` and `pass_filenames` which would definitely possible, and what I tried was:
```yaml
repos:
  - &rubocop
    id: rubocop
    name: rubocop
    language: ruby
    entry: rubocop
    additional_dependencies:
    - rubocop:0.54.0
    - rubocop-rspec:1.25.0
    - rubocop-thread_safety:0.3.4
    exclude: (?x)^(
      db/migrate/201\d/|
      lib/.*\.pb\.rb)
    args:
    - --color
    - --auto-correct
    - --require
    - rubocop-rspec
    - --require
    - rubocop-thread_safety
  - <<: *rubocop
    id: rubocop_todo
    name: Generating rubocop_todo file
    stages: [manual]
    pass_filenames: false
    args:
    - --color
    - --auto-gen-config
    - --require
    - rubocop-rspec
    - --require
    - rubocop-thread_safety
```

To avoid copy-pasting versions of the dependencies. Unfortunately I'm running into the following issue:
```
=====> could not determine a constructor for the tag 'tag:yaml.org,2002:merge'
  in "<unicode string>", line 117, column 5
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/usr/local/lib/python2.7/site-packages/pre_commit/main.py", line 259, in main
    return run(runner, args)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/commands/run.py", line 255, in run
    for repo in runner.repositories:
  File "/usr/local/lib/python2.7/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/runner.py", line 48, in repositories
    repos = self.config['repos']
  File "/usr/local/lib/python2.7/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/site-packages/pre_commit/runner.py", line 43, in config
    return load_config(self.config_file_path)
  File "/usr/local/lib/python2.7/site-packages/cfgv.py", line 351, in load_from_filename
    return apply_defaults(data, schema)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/cfgv.py", line 49, in reraise_as
    six.reraise(tp, tp(e), tb)
  File "/usr/local/lib/python2.7/site-packages/cfgv.py", line 46, in reraise_as
    yield
  File "/usr/local/lib/python2.7/site-packages/cfgv.py", line 351, in load_from_filename
    return apply_defaults(data, schema)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/cfgv.py", line 40, in validate_context
    six.reraise(ValidationError, ValidationError(e, ctx=msg), tb)
  File "/usr/local/lib/python2.7/site-packages/cfgv.py", line 37, in validate_context
    yield
  File "/usr/local/lib/python2.7/site-packages/cfgv.py", line 348, in load_from_filename
    raise ValidationError(str(e))
InvalidConfigError:
==> File /Users/tdeo/git_tree/pricematch/admin/.pre-commit-config.yaml
=====> could not determine a constructor for the tag 'tag:yaml.org,2002:merge'
```



In the mean time, I can for sure accept some copy-pasting and run `rubocop --auto-gen-config` by `pre-commit-run --hook-stage manual rubocop_todo`.

Finally, for the last point about abuse, what if we would overriding the hook's `args` similarly as the `--files` option ? To fit my use-case, it would also require a `--without-files` that mimics `pass_filenames: false`.

**Comment by asottile** [comment]
Hmmm, that error is quite odd.  I can load that configuration just fine with vanilla yaml, I suspect something strange with our custom ordered loading -- I'll open an issue there https://github.com/asottile/aspy.yaml/issues/14

```pycon
>>> aspy.yaml.ordered_load('x: &y\n  a: b\nz:\n  <<: *y\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/test/venv/lib/python3.6/site-packages/aspy/yaml/__init__.py", line 39, in ordered_load
    return yaml.load(stream, Loader=OrderedLoader)
  File "/private/tmp/test/venv/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/private/tmp/test/venv/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/private/tmp/test/venv/lib/python3.6/site-packages/yaml/constructor.py", line 41, in construct_document
    data = self.construct_object(node)
  File "/private/tmp/test/venv/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/private/tmp/test/venv/lib/python3.6/site-packages/aspy/yaml/__init__.py", line 17, in <lambda>
    lambda loader, node: OrderedDict(loader.construct_pairs(node)),
  File "/private/tmp/test/venv/lib/python3.6/site-packages/yaml/constructor.py", line 141, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/private/tmp/test/venv/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/private/tmp/test/venv/lib/python3.6/site-packages/aspy/yaml/__init__.py", line 17, in <lambda>
    lambda loader, node: OrderedDict(loader.construct_pairs(node)),
  File "/private/tmp/test/venv/lib/python3.6/site-packages/yaml/constructor.py", line 140, in construct_pairs
    key = self.construct_object(key_node, deep=deep)
  File "/private/tmp/test/venv/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/private/tmp/test/venv/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:merge'
  in "<unicode string>", line 4, column 3
>>> import yaml
>>> yaml.load('x: &y\n  a: b\nz:\n  <<: *y\n')
{'x': {'a': 'b'}, 'z': {'a': 'b'}}
```

**Comment by asottile** [comment]
If you upgrade to `aspy.yaml>=1.1.0` you should be able to load the merge syntax

**Comment by tdeo** [comment]
Perfect, that solves my use-case, thanks for your help

**Comment by asottile** [comment]
Awesome, thanks again for the issue!
