### ISSUE TITLE
Crashes with UnicodeDecodeError when running legacy hooks

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [pre-commit/pre-commit#743]
```
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 167, in <module>
    exit(main())
  File ".git/hooks/pre-commit", line 155, in main
    retv, stdin = _run_legacy()
  File ".git/hooks/pre-commit", line 57, in _run_legacy
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE if stdin else None)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 18: ordinal not in range(128)
```

This is most likely due to the repo being in `/home/Lin-Buo-Ren/工作空間/個人專案/用於 GNU Bash 專案的 Git 提交版本前掛勾程式(Git Pre-commit Hook for GNU Bash Projects)`, and again, Python 2 (sigh).

**Comment by Lin-Buo-Ren** [comment]
Just for the sake of anyone having the same issue.
