### ISSUE TITLE
InvalidConfigError occurred in Travis CI but not in local

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [pre-commit/pre-commit#748]
Refer the [build log](https://travis-ci.com/Lin-Buo-Ren/yamllint-configuration-templates/builds/72923810), `InvalidConfigError` occurrs with `found incompatible YAML document` with my [.pre-commit-config.yaml](https://github.com/Lin-Buo-Ren/yamllint-configuration-templates/blob/a11eb7318871edd327aaa705f56b8e67286e26ef/.pre-commit-config.yaml) but it can't be reproduced on my end.

```
$ git diff-tree -z --no-commit-id --name-only -r HEAD | xargs --null pre-commit run --files || true
An error has occurred: InvalidConfigError: 
==> File /home/travis/build/Lin-Buo-Ren/yamllint-configuration-templates/.pre-commit-config.yaml
=====> found incompatible YAML document
  in "<unicode string>", line 1, column 1
Check the log at /home/travis/.cache/pre-commit/pre-commit.log
before_script.2
0.01s

$ cat /home/travis/.cache/pre-commit/pre-commit.log
An error has occurred: InvalidConfigError: 
==> File /home/travis/build/Lin-Buo-Ren/yamllint-configuration-templates/.pre-commit-config.yaml
=====> found incompatible YAML document
  in "<unicode string>", line 1, column 1
Traceback (most recent call last):
  File "/home/travis/.local/lib/python2.7/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/home/travis/.local/lib/python2.7/site-packages/pre_commit/main.py", line 259, in main
    return run(runner, args)
  File "/home/travis/.local/lib/python2.7/site-packages/pre_commit/commands/run.py", line 255, in run
    for repo in runner.repositories:
  File "/home/travis/.local/lib/python2.7/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/travis/.local/lib/python2.7/site-packages/pre_commit/runner.py", line 48, in repositories
    repos = self.config['repos']
  File "/home/travis/.local/lib/python2.7/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/travis/.local/lib/python2.7/site-packages/pre_commit/runner.py", line 43, in config
    return load_config(self.config_file_path)
  File "/home/travis/.local/lib/python2.7/site-packages/cfgv.py", line 351, in load_from_filename
    return apply_defaults(data, schema)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/.local/lib/python2.7/site-packages/cfgv.py", line 49, in reraise_as
    six.reraise(tp, tp(e), tb)
  File "/home/travis/.local/lib/python2.7/site-packages/cfgv.py", line 46, in reraise_as
    yield
  File "/home/travis/.local/lib/python2.7/site-packages/cfgv.py", line 351, in load_from_filename
    return apply_defaults(data, schema)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/.local/lib/python2.7/site-packages/cfgv.py", line 40, in validate_context
    six.reraise(ValidationError, ValidationError(e, ctx=msg), tb)
  File "/home/travis/.local/lib/python2.7/site-packages/cfgv.py", line 37, in validate_context
    yield
  File "/home/travis/.local/lib/python2.7/site-packages/cfgv.py", line 348, in load_from_filename
    raise ValidationError(str(e))
InvalidConfigError: 
==> File /home/travis/build/Lin-Buo-Ren/yamllint-configuration-templates/.pre-commit-config.yaml
=====> found incompatible YAML document
  in "<unicode string>", line 1, column 1
```

```
localhost $ git diff-tree -z --no-commit-id --name-only -r HEAD | xargs --null pre-commit run --files
yamllint.................................................................Passed
```

**Comment by Lin-Buo-Ren** [comment]
I found that downgrading the YAML directive from 1.2 to 1.1 fixes the problem.  This is likely due to the different Python runtime being used on Travis CI (which is 2.x and on my local pre-commit venv it is 3.x)

**Comment by asottile** [comment]
Ah I think this is because Travis has an old pyyaml installed. pre-commit should maybe set a lower bound on that version (3.12 is the latest). I can probably reproduce your trace by downgrading pyyaml when I'm at a computer :)

You can probably work around by explicitly lower bounding pyyaml when you install :+1:

```
pip install 'pyyaml>=3.12' pre-commit
```

**Comment by keivanzavari** [comment]
Getting back to this closed issue, I am also experiencing it with pre-commit 1.18.3 and pyyaml 5.3.

**Comment by asottile** [comment]
@keivanzavari can you share your configuration? can't help otherwise

**Comment by keivanzavari** [comment]
@asottile Thanks for the reply. It seems that the error is really about my config file. And those lines and columns are about a mistake in my config file.
the args written there was wrong. it was something like `args:[-v, , -i]`. So an extra comma.

**Comment by asottile** [comment]
ok so not actually this issue at all :) glad you figured it out!
