### ISSUE TITLE
pre-commit install invalid syntax

### ISSUE THREAD

**Issue by wxrdaniel** [pre-commit/pre-commit#766]
When I run `pre-commit install --config .pre-commit-config.yaml`, I got this:

```shell
[14:21:11] > pre-commit install --config .pre-commit-config.yaml 
Traceback (most recent call last):
  File "/usr/bin/pre-commit", line 7, in <module>
    from pre_commit.main import main
  File "/usr/lib/python2.7/site-packages/pre_commit/main.py", line 11, in <module>
    from pre_commit import git
  File "/usr/lib/python2.7/site-packages/pre_commit/git.py", line 7, in <module>
    from pre_commit.error_handler import FatalError
  File "/usr/lib/python2.7/site-packages/pre_commit/error_handler.py", line 13, in <module>
    from pre_commit.store import Store
  File "/usr/lib/python2.7/site-packages/pre_commit/store.py", line 10, in <module>
    from cached_property import cached_property
  File "/usr/lib/python2.7/site-packages/cached_property.py", line 12, in <module>
    import asyncio
  File "/usr/lib/python2.7/site-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/lib/python2.7/site-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

Here is my config file:
```yaml
-   repo: ssh://[forked-repo]
    hooks:
        - id: check-json-syntax
```
Python version: 2.7.5

Anyone have any idea of why?

**Comment by asottile** [comment]
Seems like you've mistakenly installed `asyncio` in python2 -- try `pip uninstall asyncio`?

**Comment by wxrdaniel** [comment]
Do you know why would the asyncio libarary impact this?

**Comment by asottile** [comment]
`cached_property` conditionally imports `asyncio` but does not capture `SyntaxError` (because `asyncio` shouldn't even be installed in python2!)

**Comment by asottile** [comment]
I made a PR against cached-property with a "fix": https://github.com/pydanny/cached-property/pull/103

**Comment by asottile** [comment]
Apparently you can also `pip install cached-property<1.4'` to get the pre-`asyncio` behaviour

**Comment by wxrdaniel** [comment]
The `pip isntall 'cached-property<1.4'` solved the issue.

**Comment by asottile** [comment]
You can also `pip install 'cached-property>=1.4.3'` now as well
