### ISSUE TITLE
Fatal: unable to access 'https://github.com/ambv/black.git/': server certificate verification failed. CAfile: none CRLfile: none

### ISSUE THREAD

**Issue by amirouche** [pre-commit/pre-commit#820]
```
An unexpected error has occurred: CalledProcessError: Command: ('/home/amirouche/.guix-profile/bin/git', 'clone', '--no-checkout', 'https://github.com/ambv/black.git', '/home/amirouche/.cache/pre-commit/repo0zpk0ncw')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    Cloning into '/home/amirouche/.cache/pre-commit/repo0zpk0ncw'...
    fatal: unable to access 'https://github.com/ambv/black.git/': server certificate verification failed. CAfile: none CRLfile: none
    

Traceback (most recent call last):
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/pre_commit/main.py", line 261, in main
    return run(runner, store, args)
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/pre_commit/commands/run.py", line 256, in run
    for _, hook in repo.hooks:
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/pre_commit/repository.py", line 161, in hooks
    if hook['id'] not in self.manifest_hooks:
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/pre_commit/repository.py", line 154, in manifest_hooks
    repo_path = self.store.clone(repo, rev)
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/pre_commit/store.py", line 150, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/pre_commit/store.py", line 126, in _new_repo
    make_strategy(directory)
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/pre_commit/store.py", line 142, in clone_strategy
    cmd_output(*cmd, env=env)
  File "/home/amirouche/.local/share/virtualenvs/socialite-xGgT8vff/lib/python3.6/site-packages/pre_commit/util.py", line 177, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/home/amirouche/.guix-profile/bin/git', 'clone', '--no-checkout', 'https://github.com/ambv/black.git', '/home/amirouche/.cache/pre-commit/repo0zpk0ncw')
Return code: 128
Expected return code: 0
Output: (none)
Errors: 
    Cloning into '/home/amirouche/.cache/pre-commit/repo0zpk0ncw'...
    fatal: unable to access 'https://github.com/ambv/black.git/': server certificate verification failed. CAfile: none CRLfile: none
```

I am using Ubuntu 18.04 LTS, latest Guix (with up to date certificate) and a fresh pipenv

**Comment by amirouche** [comment]
I just tried on a machine that does not use guix and it works. This is most likely a problem with environment variables that are not taken into account by 'pre-commit' or pre-commit has some expectations regarding .bashrc vs .base_profile.

Anyway, it's not pre-commit specific. I will close the issue.

**Comment by amirouche** [comment]
pre-commit is very nice.Thanks for sharing.
