### ISSUE TITLE
pre-commit (installed via brew): "dyld: Library not loaded: @executable_path/../.Python"

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#822]
```console
$ pre-commit install
dyld: Library not loaded: @executable_path/../.Python
 Referenced from: /usr/local/Cellar/pre-commit/1.10.5/libexec/bin/python3.7
 Reason: image not found
Abort trap: 6
```

Fix is to `brew reinstall pre-commit`

(Creating this mostly for SEO / documentation purposes)

**Comment by Lordnibbler** [comment]
FWIW if this doesnt work:

```sh
$ brew postinstall pre-commit --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb
==> Postinstalling pre-commit
/usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall pre-commit`
==> An exception occured within a child process:
  Errno::ENOENT: No such file or directory @ realpath_rec - /usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.7

/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb:31:in `realpath'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb:31:in `realpath'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb:31:in `block in post_install'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/pathname.rb:490:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/pathname.rb:490:in `each_child'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb:29:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1011:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:868:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1010:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:523:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1002:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:16:in `<main>'
```

try this

```sh
$ brew list | grep python
python
python3
python@2
```

you have a messed up old version of python3 from a bad bad time in brew's history

```sh
$ brew uninstall python3
```

now you should have

```sh
$ brew list | grep python
python@2
```

all good, reinstall precommit 

```sh
$ brew install pre-commit
```

profit
