### ISSUE TITLE
1.12.0 breaks for Python 3.4.3

### ISSUE THREAD

**Issue by wting** [pre-commit/pre-commit#854]
We're installing and running pre-commit as part of our CI builds and the latest version is breaking our Python 3 repos:
```
+ sudo pip3 install pre-commit
Collecting pre-commit
  Downloading https://files.pythonhosted.org/packages/56/c7/a1211acfdcd251b09d9dd6e51a582d2bf9c890ededc9016dd6e47aca1758/pre_commit-1.12.0-py2.py3-none-any.whl (147kB)
Collecting identify>=1.0.0 (from pre-commit)
  Downloading https://files.pythonhosted.org/packages/09/65/75d8f14c096096ddc28f22e701b7fb4d43e9f91596336cc96bdfe2f97c92/identify-1.1.7-py2.py3-none-any.whl
Collecting cfgv>=1.0.0 (from pre-commit)
  Downloading https://files.pythonhosted.org/packages/65/53/049d31c9a486f75326f7431ac2119b1a4549e8db69c6280109e7b1e80b81/cfgv-1.1.0-py2.py3-none-any.whl
Collecting importlib-metadata (from pre-commit)
  Downloading https://files.pythonhosted.org/packages/d5/e4/49da554657aebdfe3e26beefc605fabd5dfa054b1864f8a2c527537a3dba/importlib_metadata-0.6-py2.py3-none-any.whl
Collecting cached-property (from pre-commit)
  Downloading https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl
Collecting nodeenv>=0.11.1 (from pre-commit)
  Downloading https://files.pythonhosted.org/packages/36/ca/1a635c6cd6049105fadfdc05c8de364f368fcc7aebad3081dd8ccb0c5c7f/nodeenv-1.3.2.tar.gz
Collecting importlib-resources; python_version < "3.7" (from pre-commit)
  Downloading https://files.pythonhosted.org/packages/d2/09/1f4148ee5ec0022d122bb9a94428a70f858863d47df573dd8c382fa8f1c2/importlib_resources-1.0.1.tar.gz
  Running setup.py (path:/tmp/pip-build-hfx6rwdp/importlib-resources/setup.py) egg_info for package importlib-resources produced metadata for project name unknown. Fix your #egg=importlib-resources fragments.
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python3/dist-packages (from pre-commit)
Collecting virtualenv (from pre-commit)
  Downloading https://files.pythonhosted.org/packages/b6/30/96a02b2287098b23b875bc8c2f58071c35d2efe84f747b64d523721dc2b5/virtualenv-16.0.0-py2.py3-none-any.whl (1.9MB)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from pre-commit)
Collecting toml (from pre-commit)
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting aspy.yaml (from pre-commit)
  Downloading https://files.pythonhosted.org/packages/9f/e3/5d2ba9d098b687d3676a5a557f7edc15bb544d4c2af9fc7105469d2ba624/aspy.yaml-1.1.1-py2.py3-none-any.whl
Building wheels for collected packages: nodeenv, unknown, unknown
  Running setup.py bdist_wheel for nodeenv: started
  Running setup.py bdist_wheel for nodeenv: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f3/91/e8/836a7b82342fbb2925f1022678a857970820595faae108182f
  Running setup.py bdist_wheel for unknown: started
  Running setup.py bdist_wheel for unknown: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/ed/86/db/fd92adc6c6572b6d2dddf61a35565c463be7d50a786c009e29
  Running setup.py bdist_wheel for unknown: started
  Running setup.py bdist_wheel for unknown: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hfx6rwdp/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpjukn4l0epip-wheel- --python-tag cp34:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.4/tokenize.py", line 438, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-hfx6rwdp/unknown/setup.py'
  
  ----------------------------------------
  Failed building wheel for unknown
  Running setup.py clean for unknown
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hfx6rwdp/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.4/tokenize.py", line 438, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-hfx6rwdp/unknown/setup.py'
  
  ----------------------------------------
  Failed cleaning build dir for unknown
Successfully built nodeenv unknown
Failed to build unknown
Installing collected packages: identify, cfgv, importlib-metadata, cached-property, nodeenv, unknown, virtualenv, toml, aspy.yaml, pre-commit
Successfully installed aspy.yaml-1.1.1 cached-property-1.5.1 cfgv-1.1.0 identify-1.1.7 importlib-metadata-0.6 nodeenv-1.3.2 pre-commit-1.12.0 toml-0.10.0 unknown-0.0.0 virtualenv-16.0.0
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ make lint || (git status -sb; git diff --abbrev; return 1)
Traceback (most recent call last):
  File "/usr/local/bin/pre-commit", line 7, in <module>
    from pre_commit.main import main
  File "/usr/local/lib/python3.4/dist-packages/pre_commit/main.py", line 11, in <module>
    from pre_commit import git
  File "/usr/local/lib/python3.4/dist-packages/pre_commit/git.py", line 7, in <module>
    from pre_commit.error_handler import FatalError
  File "/usr/local/lib/python3.4/dist-packages/pre_commit/error_handler.py", line 12, in <module>
    from pre_commit import output
  File "/usr/local/lib/python3.4/dist-packages/pre_commit/output.py", line 7, in <module>
    from pre_commit.util import noop_context
  File "/usr/local/lib/python3.4/dist-packages/pre_commit/util.py", line 22, in <module>
    from importlib_resources import open_binary
ImportError: No module named 'importlib_resources'
make: *** [pre-commit] Error 1
## HEAD (no branch)
```

Our current workaround is to pin to 1.11.2.

**Comment by asottile** [comment]
Hmm, I suspect a very old version of setuptools is to blame?  It seems to be failing to build `importlib-resources` / `importlib-metadata` from source

**Comment by asottile** [comment]
yeah setuptools that ships with trusty is too old.  I'd suggest using a virtualenv or upgrading setuptools.

With a virtualenv you can ~simulate a global installation:
```bash
virtualenv /venv -ppython3
/venv/bin/pip install pre-commit
export PATH=/venv/bin:$PATH
```

with docker:

```dockerfile
ENV PATH=/venv/bin:$PATH
RUN virtualenv /venv && pip install pre-commit
```

(+/- some upgrading / downgrading of setuptools)

It also appears that importlib-resources doesn't have the right metadata to support python3.4, so you might also need to `pip3 install typing` to make it work.

After upgrading setuptools I was able to get it to install properly:

```
root@d4fb71459e0b:/# pip3 install pre-commit
Downloading/unpacking pre-commit
  Downloading pre_commit-1.12.0-py2.py3-none-any.whl (147kB): 147kB downloaded
Requirement already satisfied (use --upgrade to upgrade): cfgv>=1.0.0 in /usr/local/lib/python3.4/dist-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): cached-property in /usr/local/lib/python3.4/dist-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): virtualenv in /usr/local/lib/python3.4/dist-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): nodeenv>=0.11.1 in /usr/local/lib/python3.4/dist-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): identify>=1.0.0 in /usr/local/lib/python3.4/dist-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): aspy.yaml in /usr/local/lib/python3.4/dist-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python3.4/dist-packages (from pre-commit)
Downloading/unpacking importlib-resources; python_version < "3.7" (from pre-commit)
  Downloading importlib_resources-1.0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/importlib-resources/setup.py) egg_info for package importlib-resources
    warning: no previously-included files found matching '.gitignore'
    no previously-included directories found matching 'build'
    no previously-included directories found matching '.tox'
Requirement already satisfied (use --upgrade to upgrade): importlib-metadata in /usr/local/lib/python3.4/dist-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): toml in /usr/local/lib/python3.4/dist-packages (from pre-commit)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python3.4/dist-packages (from importlib-resources; python_version < "3.7"->pre-commit)
Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/lib/python3/dist-packages (from importlib-resources; python_version < "3.7"->pre-commit)
Installing collected packages: pre-commit, importlib-resources
  Running setup.py install for importlib-resources
    warning: no previously-included files found matching '.gitignore'
    no previously-included directories found matching '.tox'
  Could not find .egg-info directory in install record for importlib-resources; python_version < "3.7" (from pre-commit)
Successfully installed pre-commit importlib-resources
Cleaning up...
root@d4fb71459e0b:/# pre-commit --help
Traceback (most recent call last):
  File "/usr/local/bin/pre-commit", line 7, in <module>
    from pre_commit.main import main
  File "/usr/local/lib/python3.4/dist-packages/pre_commit/main.py", line 11, in <module>
    from pre_commit import git
  File "/usr/local/lib/python3.4/dist-packages/pre_commit/git.py", line 7, in <module>
    from pre_commit.error_handler import FatalError
  File "/usr/local/lib/python3.4/dist-packages/pre_commit/error_handler.py", line 12, in <module>
    from pre_commit import output
  File "/usr/local/lib/python3.4/dist-packages/pre_commit/output.py", line 7, in <module>
    from pre_commit.util import noop_context
  File "/usr/local/lib/python3.4/dist-packages/pre_commit/util.py", line 22, in <module>
    from importlib_resources import open_binary
  File "/usr/local/lib/python3.4/dist-packages/importlib_resources/__init__.py", line 25, in <module>
    from importlib_resources._py3 import (
  File "/usr/local/lib/python3.4/dist-packages/importlib_resources/_py3.py", line 12, in <module>
    from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
ImportError: No module named 'typing'
root@d4fb71459e0b:/# pip3 install typing
Downloading/unpacking typing
  Downloading typing-3.6.6-py3-none-any.whl
Installing collected packages: typing
Successfully installed typing
Cleaning up...
root@d4fb71459e0b:/# pre-commit --help
usage: pre-commit [-h] [-V]
                  {install,install-hooks,uninstall,clean,autoupdate,migrate-config,run,sample-config,try-repo,help}
                  ...

positional arguments:
  {install,install-hooks,uninstall,clean,autoupdate,migrate-config,run,sample-config,try-repo,help}
    install             Install the pre-commit script.
    install-hooks       Install hook environments for all environments in the
                        config file. You may find `pre-commit install
                        --install-hooks` more useful.
    uninstall           Uninstall the pre-commit script.
    clean               Clean out pre-commit files.
    autoupdate          Auto-update pre-commit config to the latest repos'
                        versions.
    migrate-config      Migrate list configuration to new map configuration.
    run                 Run hooks.
    sample-config       Produce a sample .pre-commit-config.yaml file
    try-repo            Try the hooks in a repository, useful for developing
                        new hooks.
    help                Show help for a specific command.

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         show program's version number and exit
```

**Comment by asottile** [comment]
the weirdness with `pip` appears to be the debian patches.  I'd suggest a virtualenv even more :)

I'm wrong above about the incorrect metadata -- it does appear correct

**Comment by asottile** [comment]
This would solve the issue btw: https://gitlab.com/python-devs/importlib_resources/issues/67

**Comment by asottile** [comment]
even better would be to nudge importlib-resources maintainers to make a wheel available on pypi CC @warsaw @brettcannon

**Comment by brettcannon** [comment]
Yes, it looks like @warsaw forgot to do that. 😉

**Comment by warsaw** [comment]
Well, not so much as forgot as just didn't do it.  If it helps folks, I'm happy to release a wheel in addition to the sdist.

**Comment by chriskuehl** [comment]
@warsaw a wheel would be great if it's not too much trouble -- this is also causing issues for us internally (can't build from the sdist as our setuptools is too old for unfortunate reasons), so we've been temporarily using an older pre-commit version.

**Comment by asottile** [comment]
Upstream uploaded a wheel (1.0.1) -- this should be fixed now :tada:
