### ISSUE TITLE
autoupdate from a revision to a repo with latest tag missing .pre-commit-hooks.yaml errors

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit#856]
It should just skip updating these repositories.

```yaml
repos:
- repo: https://github.com/python-modernize/python-modernize
  rev: a234ce4e1
  hooks:
  - id: python-modernize
```

```console
$ pre-commit  autoupdate
Updating https://github.com/python-modernize/python-modernize...[INFO] Initializing environment for https://github.com/python-modernize/python-modernize.
[INFO] Initializing environment for https://github.com/python-modernize/python-modernize.
An error has occurred: InvalidManifestError: 
=====> /home/asottile/.cache/pre-commit/repolsycg5yp/.pre-commit-hooks.yaml does not exist
Check the log at /home/asottile/.cache/pre-commit/pre-commit.log
```

```console
$ cat ~/.cache/pre-commit/pre-commit.log 
An error has occurred: InvalidManifestError: 
=====> /home/asottile/.cache/pre-commit/repolsycg5yp/.pre-commit-hooks.yaml does not exist
Traceback (most recent call last):
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/cfgv.py", line 46, in reraise_as
    yield
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/cfgv.py", line 344, in load_from_filename
    raise ValidationError('{} does not exist'.format(filename))
cfgv.ValidationError: 
=====> /home/asottile/.cache/pre-commit/repolsycg5yp/.pre-commit-hooks.yaml does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pre_commit/main.py", line 256, in main
    repos=args.repos,
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pre_commit/commands/autoupdate.py", line 129, in autoupdate
    new_repo_config = _update_repo(repo_config, store, tags_only)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pre_commit/commands/autoupdate.py", line 60, in _update_repo
    hooks_missing = hooks - (hooks & set(new_repo.manifest_hooks))
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/pre_commit/repository.py", line 157, in manifest_hooks
    return {hook['id']: hook for hook in load_manifest(manifest_path)}
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/cfgv.py", line 356, in load_from_filename
    return apply_defaults(data, schema)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/cfgv.py", line 49, in reraise_as
    six.reraise(tp, tp(e), tb)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/cfgv.py", line 46, in reraise_as
    yield
  File "/home/asottile/opt/venv/lib/python3.6/site-packages/cfgv.py", line 344, in load_from_filename
    raise ValidationError('{} does not exist'.format(filename))
pre_commit.clientlib.InvalidManifestError: 
=====> /home/asottile/.cache/pre-commit/repolsycg5yp/.pre-commit-hooks.yaml does not exist
```

**Comment by asottile** [comment]
via #857

**Comment by asottile** [comment]
This has been released as part of [v1.13.0](https://github.com/pre-commit/pre-commit/releases/tag/v1.13.0) :tada:

**Comment by john-bodley** [comment]
Sadly I'm experiencing this same issue in v1.15.2 (note I'm new to `pre-commit`):

```
> more .pre-commit-config.yaml 
repos:
  - repo: git@<hidden>
    rev: master
    hooks:
      - id: autopep8
        files: '^src/'
```

```
> pip3 install pre-commit==1.15.2
> pre-commit install 
> pre-commit run
An error has occurred: InvalidManifestError: 
=====> /Users/<user>/.cache/pre-commit/repoj_9i9olk/.pre-commit-hooks.yaml does not exist
Check the log at /Users/<user>/.cache/pre-commit/pre-commit.log
> more /Users/<user>/.cache/pre-commit/pre-commit.log
...
Traceback (most recent call last):
  File "<path>/lib/python3.6/site-packages/cfgv.py", line 46, in reraise_as
    yield
  File "<path>/lib/python3.6/site-packages/cfgv.py", line 413, in load_from_filename
    raise ValidationError('{} does not exist'.format(filename))
cfgv.ValidationError: 
=====> /Users/<user>/.cache/pre-commit/repoj_9i9olk/.pre-commit-hooks.yaml does not exist
```

**Comment by asottile** [comment]
ah so that's a different error -- it's saying that `.pre-commit-hooks.yaml` doesn't exist in the remote `repo: ...` you're referencing.

Make sure that that repository has set up proper [pre-commit metadata](https://pre-commit.com/#new-hooks)  -- note that there's two files in play here, the first is the `.pre-commit-hooks.yaml` (remote metadata, think of it like a package definition) and the `.pre-commit-config.yaml` (local metadata, where you list the remote hooks you're installing)

fwiw, it looks like you're trying to use `autopep8` which you can grab from https://github.com/pre-commit/mirrors-autopep8

**Comment by asottile** [comment]
@john-bodley oh, another thing you might be running in to is the cache, `master` is a mutable ref and doesn't play well with the caching: https://pre-commit.com/#using-the-latest-version-for-a-repository

if you `pre-commit autoupdate` first you'll likely get into a better state?

**Comment by john-bodley** [comment]
@asottile I tried `pre-commit autodate` as well but alas I ran into the same issue.

Using your recommendation of using the `autopep8` mirror fixed the issue.
