### ISSUE TITLE
Support for Python projects that don't have setup.py

### ISSUE THREAD

**Issue by tonybaloney** [pre-commit/pre-commit#862]
I've tried both the python and python_venv language plugins, but I'm trying to add my python project as a new pre-commit plugin.

my package uses flit and pyproject.toml so it doesn't have a setup.py. Is there any plan/workaround for pre-commit to support this?

**Comment by tonybaloney** [comment]
How do you upgrade the pip version used in try_repo? I tried deleting the cache, running clean etc. couldn’t figure out where it was getting the old version from

**Comment by asottile** [comment]
That `pip` version comes from the whatever `virtualenv` version you have installed (`virtualenv --version`) -- for instance for `virtualenv` [16.1.0](https://github.com/pypa/virtualenv/tree/4ad2742eec5266c2e42b0651d1cd4b78393699c4/src/virtualenv_support) you'd get pip 18.1

Though if you're using `python_venv` -- I think it's based on whatever version of pip is bundled with your python installation -- less familiar with how that works though tbh

**Comment by gaborbernat** [comment]
pip does not support pep 517 yet, so cannot pip install a flit project, unless previously you create wheel/sdist with it

**Comment by asottile** [comment]
mmmm that would do it then :(

I wonder if it's worth rolling our own pep 517 support or waiting until pip fills the gap 🤔

**Comment by gaborbernat** [comment]
maybe just fallback on tox implantation tox -e py --sdistonly --isolated and then pip install that 😅@pfmoore how's pep-517 coming along?

**Comment by tonybaloney** [comment]
Feel free to try it out to see what happens with python_venv (first) and python (second).

I still cannot figure out where it is getting pip 10 from!

```
pre-commit try-repo https://github.com/tonybaloney/wily
[INFO] Initializing environment for https://github.com/tonybaloney/wily.
===============================================================================
Using config:
===============================================================================
repos:
-   repo: https://github.com/tonybaloney/wily
    rev: 191be01f6fb4617e57460559e063e8c94f1f0c9b
    hooks:
    -   id: wily
===============================================================================
[INFO] Installing environment for https://github.com/tonybaloney/wily.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/private/var/folders/3p/ffph9q490876shz82kqxhmhm0000gn/T/tmp_lf5go2c/repo8e6k_x94/py_venv-python3/bin/python3', '/var/folders/3p/ffph9q490876shz82kqxhmhm0000gn/T/tmp_lf5go2c/repo8e6k_x94/py_venv-python3/bin/pip', 'install', '.')
Return code: 1
Expected return code: 0
Output: (none)
Errors: 
    Directory '.' is not installable. File 'setup.py' not found.
    You are using pip version 10.0.1, however version 18.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    

Check the log at /Users/anthonyshaw/.cache/pre-commit/pre-commit.log
(.venv) ➜  wily git:(master) pre-commit try-repo https://github.com/tonybaloney/wily
[INFO] Initializing environment for https://github.com/tonybaloney/wily.
===============================================================================
Using config:
===============================================================================
repos:
-   repo: https://github.com/tonybaloney/wily
    rev: 161461985b5a467a5b9a0de36047dac9e0af9346
    hooks:
    -   id: wily
===============================================================================
[INFO] Installing environment for https://github.com/tonybaloney/wily.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/var/folders/3p/ffph9q490876shz82kqxhmhm0000gn/T/tmp65ltnccw/repoa6oetlkf/py_env-python3/bin/python3', '/var/folders/3p/ffph9q490876shz82kqxhmhm0000gn/T/tmp65ltnccw/repoa6oetlkf/py_env-python3/bin/pip', 'install', '.')
Return code: 1
Expected return code: 0
Output: 
    Processing /private/var/folders/3p/ffph9q490876shz82kqxhmhm0000gn/T/tmp65ltnccw/repoa6oetlkf
      Installing build dependencies: started
      Installing build dependencies: still running...
      Installing build dependencies: finished with status 'done'
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/var/folders/3p/ffph9q490876shz82kqxhmhm0000gn/T/tmp65ltnccw/repoa6oetlkf/py_env-python3/lib/python3.6/tokenize.py", line 452, in open
            buffer = _builtin_open(filename, 'rb')
        FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/3p/ffph9q490876shz82kqxhmhm0000gn/T/pip-req-build-j5bp6apz/setup.py'
        
        ----------------------------------------
    
Errors: 
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3p/ffph9q490876shz82kqxhmhm0000gn/T/pip-req-build-j5bp6apz/
    

Check the log at /Users/anthonyshaw/.cache/pre-commit/pre-commit.log
(.venv) ➜  wily git:(master) 
```

**Comment by gaborbernat** [comment]
Does not matter much, pip 18.1 supports pep 518 only, so still only supports setuptools, but can pull in build dependencies. Hence why flit generates setup.py shim in sdist.

**Comment by tonybaloney** [comment]
pre-commit could implement the same isolated build that you built @gaborbernat ? https://github.com/tox-dev/tox/blob/4c03d419fb686975e04cb12405980a579dfb44f4/src/tox/package/builder/isolated.py

**Comment by asottile** [comment]
the pip version you'll get is based on the `virtualenv` alongside `pre-commit`.  For instance:

```console
asottile@wat~$ $(head -1 $(which pre-commit) | cut -d'!' -f2) -m virtualenv --version
16.1.0
```

but yeah, even with latest virtualenv=>latest pip, it still gives me the second output you have above.  I do think `pre-commit` could (for now) implement isolated build, and then rip it out when pip supports it natively.

**Comment by asottile** [comment]
heck, `pre-commit` already depends `toml` + `virtualenv` so the dependencies are already there 😆

**Comment by tonybaloney** [comment]
See this thread for a good run-down of workarounds https://github.com/takluyver/flit/issues/74

**Comment by tonybaloney** [comment]
wait, why can't pre-install just install plugins from PyPI @asottile ?

**Comment by pradyunsg** [comment]
PEP 517 support will be there in pip's next release.

The PEP-related implementation is fine, we're mostly just discussing UI details and internal cleanups that pip should get while we're doing that. ;)
