### ISSUE TITLE
pre-commit using python2.7 even when trying to force python3

### ISSUE THREAD

**Issue by cglewis** [pre-commit/pre-commit#917]
after removing the `.cache` directory, installing pre-commit 1.14.2, installing git version 2.20.1 and ensuring that my default python version was `Python 3.7.2 (default, Jan 13 2019, 12:50:01)`. Running on OSX 10.14.2.

I have this config:
```
default_language_version:
    python: python3
repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: double-quote-string-fixer
    -   id: check-yaml
-   repo: git@github.com:asottile/reorder_python_imports
    rev: v1.3.4
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
```

and get a failure with reorder-python-imports because it's using python2.7:
```
Reorder python imports...................................................Failed
hookid: reorder-python-imports

Traceback (most recent call last):
  File "/Users/cglewis/.cache/pre-commit/repojTwO3T/py_env-python2.7/bin/reorder-python-imports", line 11, in <module>
    sys.exit(main())
  File "/Users/cglewis/.cache/pre-commit/repojTwO3T/py_env-python2.7/lib/python2.7/site-packages/reorder_python_imports.py", line 685, in main
    application_directories=args.application_directories.split(':'),
  File "/Users/cglewis/.cache/pre-commit/repojTwO3T/py_env-python2.7/lib/python2.7/site-packages/reorder_python_imports.py", line 413, in fix_file_contents
    partitioned = partition_source(contents)
  File "/Users/cglewis/.cache/pre-commit/repojTwO3T/py_env-python2.7/lib/python2.7/site-packages/reorder_python_imports.py", line 63, in partition_source
    ast_obj = ast.parse(src.encode('UTF-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 64
    print(line, file=self.file)
                    ^
SyntaxError: invalid syntax
```

Here's what the cache looks like after it installed the repos, which as you can see it's installing python2.7 env still somehow:
```
pre-commit cglewis$ ls -lah repo*
repohHHsfE:
total 136
drwx------  21 cglewis  1337   672B Jan 14 11:52 .
drwxr-xr-x   8 cglewis  1337   256B Jan 14 11:51 ..
-rw-r--r--   1 cglewis  1337   557B Jan 14 11:51 .coveragerc
drwxr-xr-x  13 cglewis  1337   416B Jan 14 11:51 .git
-rw-r--r--   1 cglewis  1337   183B Jan 14 11:51 .gitignore
-rw-r--r--   1 cglewis  1337   962B Jan 14 11:51 .pre-commit-config.yaml
-rw-r--r--   1 cglewis  1337   6.2K Jan 14 11:51 .pre-commit-hooks.yaml
-rw-r--r--   1 cglewis  1337   586B Jan 14 11:51 .travis.yml
-rw-r--r--   1 cglewis  1337   7.3K Jan 14 11:51 CHANGELOG.md
-rw-r--r--   1 cglewis  1337   1.1K Jan 14 11:51 LICENSE
-rw-r--r--   1 cglewis  1337   6.3K Jan 14 11:51 README.md
-rw-r--r--   1 cglewis  1337   290B Jan 14 11:51 appveyor.yml
-rwxr-xr-x   1 cglewis  1337   1.0K Jan 14 11:51 get-git-lfs.py
drwxr-xr-x  33 cglewis  1337   1.0K Jan 14 11:51 pre_commit_hooks
drwxr-xr-x   8 cglewis  1337   256B Jan 14 11:52 py_env-python2.7
-rw-r--r--   1 cglewis  1337    45B Jan 14 11:51 requirements-dev.txt
-rw-r--r--   1 cglewis  1337    31B Jan 14 11:51 setup.cfg
-rw-r--r--   1 cglewis  1337   3.3K Jan 14 11:51 setup.py
drwxr-xr-x   5 cglewis  1337   160B Jan 14 11:51 testing
drwxr-xr-x  35 cglewis  1337   1.1K Jan 14 11:51 tests
-rw-r--r--   1 cglewis  1337   549B Jan 14 11:51 tox.ini

repohq5jbt:
total 32
drwx------   8 cglewis  1337   256B Jan 14 11:52 .
drwxr-xr-x   8 cglewis  1337   256B Jan 14 11:51 ..
drwxr-xr-x  13 cglewis  1337   416B Jan 14 11:51 .git
-rw-r--r--   1 cglewis  1337   148B Jan 14 11:51 .pre-commit-hooks.yaml
-rw-r--r--   1 cglewis  1337     6B Jan 14 11:51 .version
-rw-r--r--   1 cglewis  1337   432B Jan 14 11:51 README.md
drwxr-xr-x   8 cglewis  1337   256B Jan 14 11:53 py_env-python2.7
-rw-r--r--   1 cglewis  1337   140B Jan 14 11:51 setup.py

repojTwO3T:
total 152
drwx------  20 cglewis  1337   640B Jan 14 11:51 .
drwxr-xr-x   8 cglewis  1337   256B Jan 14 11:51 ..
-rw-r--r--   1 cglewis  1337   538B Jan 14 11:51 .coveragerc
drwxr-xr-x  13 cglewis  1337   416B Jan 14 11:51 .git
-rw-r--r--   1 cglewis  1337    76B Jan 14 11:51 .gitignore
-rw-r--r--   1 cglewis  1337   923B Jan 14 11:51 .pre-commit-config.yaml
-rw-r--r--   1 cglewis  1337   286B Jan 14 11:51 .pre-commit-hooks.yaml
-rw-r--r--   1 cglewis  1337   413B Jan 14 11:51 .travis.yml
-rw-r--r--   1 cglewis  1337   1.0K Jan 14 11:51 LICENSE
-rw-r--r--   1 cglewis  1337   5.8K Jan 14 11:51 README.md
-rw-r--r--   1 cglewis  1337   190B Jan 14 11:51 hooks.yaml
drwxr-xr-x   8 cglewis  1337   256B Jan 14 11:52 py_env-python2.7
-rw-r--r--   1 cglewis  1337    23K Jan 14 11:51 reorder_python_imports.py
-rw-r--r--   1 cglewis  1337    39B Jan 14 11:51 requirements-dev.txt
-rw-r--r--   1 cglewis  1337    31B Jan 14 11:51 setup.cfg
-rw-r--r--   1 cglewis  1337   967B Jan 14 11:51 setup.py
drwxr-xr-x   4 cglewis  1337   128B Jan 14 11:51 test_data
drwxr-xr-x   3 cglewis  1337    96B Jan 14 11:51 testing
drwxr-xr-x   4 cglewis  1337   128B Jan 14 11:51 tests
-rw-r--r--   1 cglewis  1337   308B Jan 14 11:51 tox.ini
```

**Comment by cglewis** [comment]
also in my home directory inside of `.pre-commit-venv` I have this:
```
.pre-commit-venv cglewis$ ls -lah
total 8
drwxr-xr-x    7 cglewis  1337   224B Jan 14 12:05 .
drwxr-xr-x+ 100 cglewis  1337   3.1K Jan 14 12:05 ..
lrwxr-xr-x    1 cglewis  1337    80B Jan 14 11:37 .Python -> /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/Python
drwxr-xr-x   16 cglewis  1337   512B Jan 14 11:37 bin
drwxr-xr-x    3 cglewis  1337    96B Jan 14 11:37 include
drwxr-xr-x    3 cglewis  1337    96B Jan 14 11:37 lib
-rw-r--r--    1 cglewis  1337    59B Jan 14 11:37 pip-selfcheck.json
```

**Comment by asottile** [comment]
Can you show `pre-commit version` and `pre-commit run --all-files`

**Comment by cglewis** [comment]
Running `pre-commit 1.14.2`.  Huh. wasn't aware of that run --all-files. It's not complaining about the error anymore. Still not sure why it was doing python2.7 stuff, but seems to be resolved for me now. Thanks!

**Comment by asottile** [comment]
Weird! My guess is that you have pre-commit installed somewhere else under python 2 and at an older version :man_shrugging:

**Comment by cglewis** [comment]
I ran into the issue again, but figured out the root cause. I had a stale `pre-commit` installed in the specific repo.  After removing that and running `pre-commit install` everything was good to go.

**Comment by asottile** [comment]
awesome!  In the future I'll probably make unknown keys a warning so this'll at least be a more obvious failure -- we're already doing that for individual hooks and it probably won't be much to do it at the repository and top level as well
