### ISSUE TITLE
UnicodeDecodeError on Windows because of old pip

### ISSUE THREAD

**Issue by nicoddemus** [pre-commit/pre-commit#932]
Howdy!

I'm getting this error when trying to commit on pytest from the latest `master`:

```
λ pre-commit run -a
[INFO] Installing environment for https://github.com/ambv/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('X:\\.cache\\pre-commit\\repoz0ikumr2\\py_env-python3\\Scripts\\pip.exe', 'install', '.')
Return code: 2
Expected return code: 0
Output:
    Processing x:\.cache\pre-commit\repoz0ikumr2

Errors:
    Exception:
    Traceback (most recent call last):
      File "x:\.cache\pre-commit\repoz0ikumr2\py_env-python3\lib\site-packages\pip\_internal\basecommand.py", line 228, in main
        status = self.run(options, args)
      File "x:\.cache\pre-commit\repoz0ikumr2\py_env-python3\lib\site-packages\pip\_internal\commands\install.py", line 291, in run
        resolver.resolve(requirement_set)
      File "x:\.cache\pre-commit\repoz0ikumr2\py_env-python3\lib\site-packages\pip\_internal\resolve.py", line 103, in resolve
        self._resolve_one(requirement_set, req)
      File "x:\.cache\pre-commit\repoz0ikumr2\py_env-python3\lib\site-packages\pip\_internal\resolve.py", line 257, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "x:\.cache\pre-commit\repoz0ikumr2\py_env-python3\lib\site-packages\pip\_internal\resolve.py", line 210, in _get_abstract_dist_for
        self.require_hashes
      File "x:\.cache\pre-commit\repoz0ikumr2\py_env-python3\lib\site-packages\pip\_internal\operations\prepare.py", line 324, in prepare_linked_requirement
        abstract_dist.prep_for_dist(finder, self.build_isolation)
      File "x:\.cache\pre-commit\repoz0ikumr2\py_env-python3\lib\site-packages\pip\_internal\operations\prepare.py", line 126, in prep_for_dist
        build_requirements, isolate = self.req.get_pep_518_info()
      File "x:\.cache\pre-commit\repoz0ikumr2\py_env-python3\lib\site-packages\pip\_internal\req\req_install.py", line 448, in get_pep_518_info
        pp_toml = pytoml.load(f)
      File "x:\.cache\pre-commit\repoz0ikumr2\py_env-python3\lib\site-packages\pip\_vendor\pytoml\parser.py", line 10, in load
        return loads(fin.read(), translate=translate, filename=getattr(fin, 'name', repr(fin)))
      File "x:\.cache\pre-commit\repoz0ikumr2\py_env-python3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 867: character maps to <undefined>
    You are using pip version 10.0.1, however version 19.0.1 is available.
    You should consider upgrading via the 'python -m pip install --upgrade pip' command.


Check the log at x:\/.cache\pre-commit\pre-commit.log
```

The bug happens on `pip`, but `pre-commit` is using an old version and the new version does not contain that bug anymore.

I already tried `clean` and `gc`, with the same results. I'm using `pre-commit 1.14.2` on `Python 3.6.6`.

Any advice? 😁

**Comment by asottile** [comment]
Upgrade `virtualenv` that's installed alongside `pre-commit` (that's what controls the version of `pip` that ends up inside the hook environments)

Duplicate issue: #835

**Comment by asottile** [comment]
Looks like [`virtualenv>=16.1.0`](https://github.com/pre-commit/pre-commit/issues/835#issuecomment-434731877) is the ticket :tada:

**Comment by nicoddemus** [comment]
Ahh should have made a better search, sorry!

Thanks, worked like a charm! 👍

**Comment by asottile** [comment]
No problem! Thanks for the issue :tada:
