### ISSUE TITLE
[Win10, Py3.72, pre-commit 1.14.4] InvalidManifestError: Expected array but got 'OrderedDict'

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [pre-commit/pre-commit#955]
```batch
An error has occurred: InvalidManifestError:
==> File C:\Users\Nebu/.cache\pre-commit\repofw7i5ae9\.pre-commit-config.yaml
=====> Expected array but got 'OrderedDict'
```

Using this config file:
```yaml
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
```

On this repository: https://github.com/pipxproject/pipx

**Comment by asottile** [comment]
Interesting, do you have a branch I can check out and poke at?

**Comment by Laurentiu-Andronache** [comment]
Here: https://github.com/Laurentiu-Andronache/pipx/tree/add-precommit-hooks

**Comment by asottile** [comment]
Awesome, thanks -- can you `pip freeze --all` for me?  seems odd that it's trying to load a manifest (usually `.pre-commit-hooks.yaml`) from `.pre-commit-config.yaml`

fwiw it's working locally for me on posix, I'm starting my windows VM right now:

```console
$ pip freeze --all
aspy.yaml==1.1.2
cfgv==1.4.0
identify==1.3.0
importlib-metadata==0.8
nodeenv==1.3.3
pip==19.0.3
pre-commit==1.14.4
PyYAML==3.13
setuptools==40.8.0
six==1.12.0
toml==0.10.0
virtualenv==16.4.1
wheel==0.33.1
zipp==0.3.3
$ pre-commit run --all-files
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Trim Trailing Whitespace.................................................Passed
```

**Comment by asottile** [comment]
Also the crash log would be useful -- it's usually stored in `~/.cache/pre-commit/pre-commit.log`

**Comment by asottile** [comment]
Seems to have worked for me on windows, looking forward to your additional information:

```
IEUser@MSEDGEWIN10 MINGW64 /tmp/t/pipx (master)
$ git checkout add-precommit-hooks
Switched to a new branch 'add-precommit-hooks'
Branch 'add-precommit-hooks' set up to track remote branch 'add-precommit-hooks' from 'origin'.
(venv)
IEUser@MSEDGEWIN10 MINGW64 /tmp/t/pipx (add-precommit-hooks)
$ pre-commit run --all-files
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Trim Trailing Whitespace.................................................Passed
(venv)
IEUser@MSEDGEWIN10 MINGW64 /tmp/t/pipx (add-precommit-hooks)
$ pip freeze --all
aspy.yaml==1.1.2
cfgv==1.4.0
identify==1.3.0
importlib-metadata==0.8
nodeenv==1.3.3
pip==19.0.3
pre-commit==1.14.4
PyYAML==3.13
setuptools==40.8.0
six==1.12.0
toml==0.10.0
virtualenv==16.4.1
wheel==0.33.1
zipp==0.3.3
IEUser@MSEDGEWIN10 MINGW64 /tmp/t/pipx (add-precommit-hooks)
$ python --version --version
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
```

**Comment by Laurentiu-Andronache** [comment]
Here's my crash info:
```
An error has occurred: InvalidManifestError: 
==> File C:\Users\Nebu/.cache\pre-commit\repofw7i5ae9\.pre-commit-config.yaml
=====> Expected array but got 'OrderedDict'
Traceback (most recent call last):
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 37, in validate_context
    yield
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 407, in load_from_filename
    validate(data, schema)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 376, in validate
    schema.check(v)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 266, in check
    check_array(check_any)(v)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 359, in check_array_fn
    'Expected array but got {!r}'.format(type(v).__name__),
cfgv.ValidationError: 
=====> Expected array but got 'OrderedDict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 46, in reraise_as
    yield
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 408, in load_from_filename
    return apply_defaults(data, schema)
  File "C:\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 40, in validate_context
    six.reraise(ValidationError, ValidationError(e, ctx=msg), tb)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 37, in validate_context
    yield
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 407, in load_from_filename
    validate(data, schema)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 376, in validate
    schema.check(v)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 266, in check
    check_array(check_any)(v)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 359, in check_array_fn
    'Expected array but got {!r}'.format(type(v).__name__),
cfgv.ValidationError: 
==> File C:\Users\Nebu/.cache\pre-commit\repofw7i5ae9\.pre-commit-config.yaml
=====> Expected array but got 'OrderedDict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\pre_commit\error_handler.py", line 46, in error_handler
    yield
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\pre_commit\main.py", line 291, in main
    return run(args.config, store, args)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\pre_commit\commands\run.py", line 262, in run
    for hook in all_hooks(config, store)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\pre_commit\repository.py", line 221, in all_hooks
    for repo in root_config['repos']
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\pre_commit\repository.py", line 222, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\pre_commit\repository.py", line 197, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\pre_commit\repository.py", line 167, in _cloned_repository_hooks
    by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 408, in load_from_filename
    return apply_defaults(data, schema)
  File "C:\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 49, in reraise_as
    six.reraise(tp, tp(e), tb)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 46, in reraise_as
    yield
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 408, in load_from_filename
    return apply_defaults(data, schema)
  File "C:\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 40, in validate_context
    six.reraise(ValidationError, ValidationError(e, ctx=msg), tb)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 37, in validate_context
    yield
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 407, in load_from_filename
    validate(data, schema)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 376, in validate
    schema.check(v)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 266, in check
    check_array(check_any)(v)
  File "c:\projects\python\_helping\pipx\venv\lib\site-packages\cfgv.py", line 359, in check_array_fn
    'Expected array but got {!r}'.format(type(v).__name__),
pre_commit.clientlib.InvalidManifestError: 
==> File C:\Users\Nebu/.cache\pre-commit\repofw7i5ae9\.pre-commit-config.yaml
=====> Expected array but got 'OrderedDict'
```

**Comment by asottile** [comment]
Can you provide the contents of `c:\projects\python\_helping\pipx\venv\lib\site-packages\pre_commit\repository.py` and `c:\projects\python\_helping\pipx\venv\lib\site-packages\pre_commit\constants.py`

I suspect there's been some tampering with one of those two files

I can reproduce your error only when I apply this (incorrect) diff:

```diff
 def _cloned_repository_hooks(repo_config, store, root_config):
     repo, rev = repo_config['repo'], repo_config['rev']
-    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
+    manifest_path = os.path.join(store.clone(repo, rev), C.CONFIG_FILE)
     by_id = {hook['id']: hook for hook in load_manifest(manifest_path)}
 
```

**Comment by Laurentiu-Andronache** [comment]
yes, I just deleted the venv to try again (because I noticed that it works outside of it), but I think I have it in recycle bin

**Comment by asottile** [comment]
Did you edit some files and then forget about it?  I can't think of a way you'd end up with broken files when installing from pypi

**Comment by Laurentiu-Andronache** [comment]
Probably PyCharm edited, I must have reformated the code from the venv by mistake. It actually happened to me in the past, but for another package. I feel so bad about it now. :(

**Comment by asottile** [comment]
no problem! glad you figured it out :tada:

**Comment by ninjakx** [comment]
My **sample.py** :
`a = [1,2,3,4]`

`pre-commit run sample.py `

gives

```
An error has occurred: InvalidConfigError: 
==> File /home/pygirl/learn_git/.pre-commit-config.yaml
=====> Expected array but got 'OrderedDict'
Check the log at ~/.pre-commit/pre-commit.log
```

**.pre-commit-config.yaml:**
```
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8


```

**Comment by asottile** [comment]
@ninjakx please create a new issue and fill out the template. bumping a years old issue is BM
